### ISSUE TITLE
TypeError: Cannot convert tz-naive Timestamp, use tz_localize to localize

### ISSUE THREAD

**Issue by fzumstein** [xlwings/xlwings#1012]
#### Describe your issue (incl. Traceback!)

See: https://stackoverflow.com/questions/53785805/using-xlwings-to-write-pandas-datetimeindex-to-sheet

```python
TypeError: Cannot convert tz-naive Timestamp, use tz_localize to localize

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import pandas as pd
import xlwings as xw

wb = xw.books.active
sheet = wb.sheets['Sheet1']

ix = pd.date_range('2017-12-31', '2018-12-31', freq='BM')
sheet['A1'].value = ix
```

**Comment by gryBox** [comment]
Ran into this today `pandas` to `xlwings`

**Comment by fzumstein** [comment]
xlwings doesn't directly support pandas Index objects. Turn it into a list first:

```
import pandas as pd
import xlwings as xw

wb = xw.books.active
sheet = wb.sheets['Sheet1']

ix = pd.date_range('2017-12-31', '2018-12-31', freq='BM')
sheet['A1'].value = list(ix)
```
