### ISSUE TITLE
RunPython when workbook is in a folder with a quote in the name

### ISSUE THREAD

**Issue by AdrienLeconteEJAM** [xlwings/xlwings#1021]
#### OS (e.g. Windows 10 or macOS Sierra)

Windows 10
Xlwing version 0.15.1

#### Describe your issue 

I get the following error when trying to run RunPython form a workbook located in a folder named with an apostrophe (i.e.: C:\Path\to\my\python's test\folder\workbook.xlsm)

![path error](https://user-images.githubusercontent.com/46884045/51458001-f1c48980-1d96-11e9-9d60-bdf42a874fc7.png)

This is probably related to this : https://github.com/ZoomerAnalytics/xlwings/issues/958

**Comment by tacobeard** [comment]
This bug sadly prevents me from distributing any network saved files, as our network drive includes spaces :/

**Comment by fzumstein** [comment]
Given that we solved this: https://github.com/xlwings/xlwings/issues/1063 in the last release, this should probably be fixable accordingly.

**Comment by tacobeard** [comment]
Forgive me I misread, I'm having problems using filepaths with spaces in them in the VBA, even when using escape characters.  Quotes are not the issue.  Thank you for all of the work you've done over the years!!

**Comment by fzumstein** [comment]
can you open a new issue then and attach a sample to replicate the issue please.

**Comment by fzumstein** [comment]
Same problem with single quotes in names of files.
