### ISSUE TITLE
API wrapper for EnableEvents

### ISSUE THREAD

**Issue by slishak** [xlwings/xlwings#1025]
At the moment, in order to disable events, you need to go to through the underlying COM object (`app.api.EnableEvents = False`). The documentation says to open an issue in this case under "Missing Features", so maybe adding a platform-independent wrapper for this would be good!

Could go hand in hand with https://github.com/ZoomerAnalytics/xlwings/issues/254 as this also suggests a way to disable events from xlwings (and it's exactly the use case I have).

For some more information on the problem I'm having - I want to disable the `Worksheet_Change` events in my workbook while xlwings is operating on the workbook to prevent conflicts. I can do this with `app.api.EnableEvents = False`, but then I have to manually trigger the VBA macros that were suppressed once xlwings has finished. It would be nice to have some way of "delaying" VBA events so they all trigger when event handling is re-enabled, but probably quite a big task!

**Comment by jaymegordo** [comment]
Second this, I also use ` app.api.EnableEvents` often

**Comment by fzumstein** [comment]
available since 0.24.4.
