### ISSUE TITLE
Re: Running very very slow

### ISSUE THREAD

**Issue by jinwang7** [xlwings/xlwings#1031]
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.15.2, excel 2013, Python 3.7
#### Describe your issue (incl. Traceback!)
Try to read spreadsheet and it's very very slow. There are some calculation and filters in the spreadsheet but I don't think it's the issue. 

```python
# Your traceback here
Running forever
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
import xlwings as xw
sht = xw.book('path+file').sheets['sheetname']

```

**Comment by fzumstein** [comment]
are you able to attach a sample workbook to reproduce the issue?

**Comment by fzumstein** [comment]
any news on this? I assume `xw.book()` is a typo? should be `xw.Book()`
