### ISSUE TITLE
Could not activate Python COM server

### ISSUE THREAD

**Issue by hangli2** [xlwings/xlwings#1036]
Hi there,

I have difficulty pointing Python interpreter to the virtual environment.

I have set INTERPRETER (in worksheet xlwings.conf) to be the python interpreter in the virtual environment (Y:\\Dev\\Python\\venv\\Scripts\\python.exe), but then see Excel error ‘Could not activate Python COM server’.

What is the correct way to use a virtual environment pls?

Thanks!

**Comment by fzumstein** [comment]
How did you create the venv?

**Comment by hangli2** [comment]
Thanks Felix.
I created the venv in PyCharm. xlwings is installed in this environment too (I have tried both ver 14 and 15. Saw the same error msg).

Alex

**Comment by fzumstein** [comment]
Can you check if the xlwings dlls are either next to the python.exe or in the parent folder?

**Comment by hangli2** [comment]
I have seen the following dll files in the same folder of the python executable (Y:\Dev\Python\venv\Scripts\):
xlwings32-0.11.8.dll
xlwings32-0.14.0.dll
xlwings32-0.15.1.dll
xlwings64-0.11.8.dll
xlwings64-0.14.0.dll
xlwings64-0.15.1.dll

and the following dll files in the parent folder (Y:\Dev\Python\venv\):
xlwings32-0.14.0.dll
xlwings64-0.14.0.dll

**Comment by fzumstein** [comment]
I am assuming this is this issue: https://github.com/xlwings/xlwings/issues/1166 feel free to reopen if that's not the case.
