### ISSUE TITLE
atexit registered functions not triggered while restarting UDF server

### ISSUE THREAD

**Issue by mattveil** [xlwings/xlwings#1048]
Windows 7
Excel 2013 32 bits
Python 3.6 x64
xlwings 0.15.3

When registering some fonctions through the atexit module in a python project including xlwings, they are correctly triggered when calling directly the python interpreter.
However they're not triggered through Excel while using the "Restart UDF server" functionality in the add-in.

Would it be related to the way the python interpreter is killed via Excel add-in?

Thanks

**Comment by fzumstein** [comment]
I would say rather to the way the functions are loaded. What's your use case?

**Comment by mattveil** [comment]
Hi,
Sorry for the late answer...

Here's my use case (happy to provide more details if needed) : 
I have a python file with an "import atexit" function defined without input expected doing a shutil.rmtree of an existing folder.

Then I register this function via a atexit.register call.

I also added another python function accessible from Excel through xlwings just to ensure the xlwings lib works well and is correctly set-up on my side.

When I run on a standalone way this python code, the folder is indeed deleted when python.exe is ending.

When I start the python.exe UDF server from Excel I manage to call and use the interfaced python function. However when I either restart the UDF server or close Excel the python.exe is either restarted or killed but the folder expected to be deleted by the atexit registered function isn't.

Hope it helps to reproduce. Let me know otherwise.
Thank you !

**Comment by fzumstein** [comment]
Ok it's been some time ;) but yes, looks like it's an issue because the Python process gets killed and therefore can't run the atexit handler...
