### ISSUE TITLE
Integration with Koala or Formulas

### ISSUE THREAD

**Issue by Brad-eki** [xlwings/xlwings#1056]
Although I am currently using xlwings for an accounting integration, I usually work in a data analysis scenario.

Fair declaration; I have contributed in a minor way to the Koala2 Library. For those who don't know it, Koala2 reads formulas from an Excel file and evaluates those formulas natively in Python. I understand another project called Formulas does something similar.

Has anyone put thought or effort into integrating a library which reads and evaluates Excel formulas in Python? For Example Koala or Formulas. ...Doesn't have to absorb the other project.

For the company I work for, having the ability to have all the NumPy/Pandas/Matplotlib in Excel is incredible but we also have need, on occasion, to allow non-coders to input formulae in a familiar environment and then process it in Python, often as part of a more complex model.

It would be awesome to have the ability to evaluate Excel formulas in Python on a workbook that is currently open. Join that with the other features of xlwings and there's an astoundingly powerful tool there.

Any appetite out there for such a thing (beyond me)?

**Comment by Brad-eki** [comment]
There is a good example for design of a solution in Java for formula reading and evaluating:
https://github.com/apache/poi/tree/trunk/src/java/org/apache/poi/ss/formula

It's the Horrible SpreadSheet Format (HSSF). I used it 10 years ago to do stuff in a different life. It was a great library then and it seems they've added formula evaluation since.

I don't know if it's possible to Jython that stuff in, or wrap it or something.

The _best_ would be to extend Pandas and NumPy so that the formulas are literally built in. I don't know how hard that is though...

**Comment by Brad-eki** [comment]
Looks like what I am trying to describe is writing an xlwings converter for the Koala library.

**Comment by fzumstein** [comment]
In what way would that be better than using openpyxl to do the job?

**Comment by Brad-eki** [comment]
Openpyxl is fantastic however it doesn't have the ability to evaluate the formulas / actually do the calculation, it can only read and write the text of the formula.

The openpyxl library is used by Koala to read formulae from an Excel file but Koala goes further to follow all the referenced cells (values and other formulas) and provides the facility to actually execute the calculation in Python. In one sense it could be seen to be replacing the calculation engine of Excel but this isn't necessarily a practical view. What something like Koala really offers is a very rapid way to iterate scenarios using Excel formulas as a highly configurable user interface for defining mathematical models in Python.

There are many uses, mostly in engineering and science domains or where you bridge financial modelling with technical model scenario domain searching.

One example is if you have a technical model where some elements of the calculation are open to change. With something that reads formulae, interprets them into Python and then proceeds to calculate in Python you can have the flexibility by allowing a user to change particular parts (or all) of your model and rapidly respond with answers.

Another example is optimizing a financial model by calculating through various parameter ranges on a technical model. The technical model may require big data, distributed or cluster computing.

It essentially allows you to choose where your calculation is happening.. Within Excel or in Python (which could have any number of calculating engines locally, clusterrd or cloud).

**Comment by Brad-eki** [comment]
This may not make much sense without the associated Excel files but here goes;

koala_xlwings.xlsm: the spreadsheet we are working from. Has xlwings and a button linked to the following subroutine LoadKoalaModel which has our RunPython. We also use a UDF in this spreadsheet.

Book1.xlsx: has a formula in the cell Sheet1!A2.

So, this code uses Koala to load the formula from Book1.xlsx Sheet1!A2 into a cache on the running xlwings server as part of the koala_xlwings module. The reason Koala is important here is it converts the Excel formula into Python code. Essentially we now have a mathematical model in Python as described by an Excel formula.

Now, using a UDF "KoalaModel" within koala_xlwings.xlsm, we can change the terms of the mathematical model and evaluate the result in Python, returning the result to the cell which calls the UDF.

I reckon it would be awesome to make this an extension for xlwings.

```vb
Sub LoadKoalaModel()
    RunPython ("import koala_xlwings as kxw; kxw.LoadKoalaModel('" & Sheets("Sheet1").Range("M3") & "', '" & Sheets("Sheet1").Range("G1") & "', inputs = ['Sheet1!A2'])")
End Sub
```

```python
import xlwings as xw

from koala.ExcelCompiler import ExcelCompiler
from koala.openpyxl import utils, cell

koala_models = {}

def LoadKoalaModel(file_name, model_name, inputs = None, outputs = None):
    global koala_models
    c = ExcelCompiler(file_name)
    c.clean_pointer()
    sp = c.gen_graph(inputs= inputs)
    koala_models[model_name] = sp
    print("Model '%s' has been loaded" % model_name)

@xw.func
def KoalaModel(model_name, *terms):
    """=KoalaModel(MODEL_NAME, TERM1, TERM2, TERM3, ...)"""
    global koala_models
    model = koala_models[model_name]

    column_counter = 2
    for term in terms:
        address = 'Sheet1!{0}2'.format(utils.get_column_letter(column_counter))
        koala_models[model_name].set_value(address, term)
        column_counter += 1

    return koala_models[model_name].evaluate('Sheet1!A2')
```

**Comment by Brad-eki** [comment]
I am at a point now where I'd like to offer a PR with support for Koala, however I am struggling to determine where it needs to live.

First reaction is this is an extension. However the change requires the ability to load files and would best include the ability to cache things. I can turn everything into UDFs but I'm not certain that aligns with the paradigm of an extension.

I then thought this was similar to matplotlib. But matplotlib neatly fits into the concept of pictures and so has code in main.py.

It has occurred to me that this probably needs configuration options in the Ribbon (including a toggle to turn its use off and on), which is fine and can be done, but I'm still a little unsure as to where the body of the code would sit.

Any guidance?

```python
import xlwings as xw

from koala.ExcelCompiler import ExcelCompiler
from koala.tokenizer import ExcelParser
from koala.openpyxl import utils
import pandas as pd

koala_models = {}
excel_compiler = None

def reloadKoala(file_name, ignore_sheets= None):
    global excel_compiler
    print("Loading workbook")
    excel_compiler = ExcelCompiler(file_name, ignore_sheets=ignore_sheets)
    excel_compiler.clean_pointer()
    print("Workbook '%s' has been loaded." % file_name)
    print("Ignored workwheets %s" % ignore_sheets)

ignore_sheets=['Sheet1', 'Sheet2']
excel_file_name = r'Mathematical_Model.xlsm'
reloadKoala(excel_file_name, ignore_sheets=ignore_sheets)

@xw.func
@xw.arg('model', xw.Range, doc='This is the named Range (cell) of the model formula')
@xw.arg('refresh', doc='Flag to refresh the model if this is to load a new one')
def generateModelGraph(model, refresh = False):
    global koala_models

    if refresh == False and model in koala_models.keys():
        return 'Model %s is already cached, set refresh True if you want it to refresh it' % model.name.name

    parser = ExcelParser()
    tokens = parser.parse(model.formula)
    inputs = parser.getOperandRanges()
    koala_models[model.name.name] = excel_compiler.gen_graph(inputs= inputs, outputs= [model.name.name])
    print("Successfully loaded model %s" % model.name)
    return 'Cached Model %s' % model.name

@xw.func
def resetKoalaModelCache():
    global koala_models
    koala_models = {}

@xw.func
def getCachedKoalaModelNames():
    global koala_models

    names_of_cached_models = []
    for model_name in koala_models.keys():
        names_of_cached_models.append(model_name)

    return names_of_cached_models

@xw.func
@xw.arg('model', xw.Range, doc='The name of the model that needs to be removed')
def unloadKoalaModelFromCache(model):
    global koala_models
    del(koala_models[model_name])

@xw.func
@xw.arg("model_name", doc='The name (string) of the model requiring evaluation')
@xw.arg("terms", pd.DataFrame, header=1, index=False, doc='An Excel Range of the terms to evaluate including headers which match input paramters')
@xw.ret(index=False, header=False, expand='down')
def EvaluateKoalaModel(model_name, terms):
    global koala_models

    def eval_model(row, model):
        row_dict = row.to_dict()
        for key in row_dict.keys():
            model.set_value(key, row_dict[key])

        return model.evaluate(model_name)

    current_model = koala_models[model_name]

    results = terms.apply(eval_model, axis= 1, model= current_model)
    return results
```

**Comment by fzumstein** [comment]
Hey Brad, I appreciate all the infos here and it certainly looks like an interesting project! However, xlwings is a general purpose library that connects Excel and Python. So anything that goes beyond that core functionality should really live in a separate repository that makes use of xlwings, koala etc. etc. as dependencies. It's good to have a reference here in the issues where other people will find it, but there's not room for that in the core library.
