### ISSUE TITLE
Space in frozen python (name.exe) path causes error

### ISSUE THREAD

**Issue by jvaldiviezo9** [xlwings/xlwings#1063]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Latest xlwings v15.5
#### Describe your issue (incl. Traceback!)

![Capture](https://user-images.githubusercontent.com/18518204/55101429-b8a3e080-5089-11e9-9af3-f0975bcc2a65.PNG)

```python
# Your traceback here



```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

On vba after generating the dist executable with pyinstaller I've got this:

Sub run_frozen()
    
    this_path = ThisWorkbook.Path
    'this_path = "D:\Desktop\project test\"    - note the space on project test folder
    RunFrozenPython (this_path + "\dist\" + "pyfile.exe")

End Sub

on python I've got a simple file that writes to a cell on excel

import xlwings as xw
wb = xw.Book.caller()
wb.sheets("Sheet1").range("A1") = "ok

the problem arises when on the path I've one space, let's call it:
this_path_fails = "D:\Desktop\project test\"
this doesn't happen when we put an underscore in the path or remove the space.
this_path_works = "D:\Desktop\project_test\"



```

**Comment by fzumstein** [comment]
Can't seem to make this work. I would have the following changes expected to work (wrapping the whole string and the path in `"`):

in Main:
```
    ExitCode = Wsh.Run("cmd.exe /C " & Chr(34) & DriveCommand & _
                   RunCommand & _
                   "--wb=" & """" & WORKBOOK_FULLNAME & """ --from_xl=1" & " --app=" & Chr(34) & _
                   Application.Path & "\" & Application.Name & Chr(34) & " --hwnd=" & Chr(34) & Application.Hwnd & Chr(34) & _
                   Chr(34) & " 2> """ & LOG_FILE & """ ", _
                   WindowStyle, WaitOnReturn)
```

Then call RunFronzePython like this:

```
Sub SampleCall()
    RunFrozenPython Chr(34) & ThisWorkbook.Path & "\dist\frozenargs\frozenargs.exe" & Chr(34) & " arg1 arg2"
End Sub

```

**Comment by jvaldiviezo9** [comment]
did you try to just put the quotation on the part of the path that contains spaces?
In what file is this code located on source code?

**Comment by fzumstein** [comment]
should have tried that too, yes. Double click the xlwings addin (password xlwings), then this is in Main module

**Comment by jvaldiviezo9** [comment]
Found solution!
The issue is on PythonCommand, we need to put the double quotes there instead WORKBOOK_FULLNAME.
I added this to the RunCommand and it worked
![image](https://user-images.githubusercontent.com/18518204/56868632-7fc59700-69ba-11e9-81bf-825245aadde5.png)

**Comment by jvaldiviezo9** [comment]
ElseIf IsFrozen = True Then
        RunCommand = PythonCommand
        'Debug.Print RunCommand
        RunCommand = Chr(34) & RunCommand & Chr(34) & " "
        'Debug.Print RunCommand
    End If

**Comment by fzumstein** [comment]
the issue is that it doesn't work with arguments. In your case, you should be able to resolve it by leaving the xlwings addin untouched and changing your call to this:

```
Sub run_frozen()
    
    this_path = ThisWorkbook.Path
    RunFrozenPython (Chr(34) & this_path + "\dist\" + "pyfile.exe" & Chr(34))
```

**Comment by jvaldiviezo9** [comment]
Some idea in how to make it work with Args?

**Comment by fzumstein** [comment]
Ah ok I see what's going on, you're right, currently you have to hack it there. Yes, I'll probably have to separate out the args to make this work. Thanks for your help!

**Comment by jvaldiviezo9** [comment]
You're welcome :). So is this still planned for the next release?

**Comment by jvaldiviezo9** [comment]
If this helps I figured out that this mod works with args:
`RunCommand = Chr(34) & "D:\Desktop\path with spaces\dist\test_args.exe" & Chr(34) & " " & "Arg1 Arg2" & " "`

**Comment by fanchao1985** [comment]
Hi,

I have similar problem.
![image](https://user-images.githubusercontent.com/51043010/58378445-7f72e880-7fc6-11e9-9259-eb1019afaca1.png)

In RunFrozenPython, I have to specify the whole path and if the path contains space, it will fail with the same message above.

Is this issue fixed already?

Best regards,
Fanchao

**Comment by fzumstein** [comment]
yes, see release notes http://docs.xlwings.org/en/stable/whatsnew.html#v0-15-6-apr-29-2019. Post your VBA code and xlwings addin version if you have issues.

**Comment by fanchao1985** [comment]
Thanks a lot, Felix. It works fine after installing bas file!

Best regards,
Fanchao
