### ISSUE TITLE
Use temp file for Python code to be executed instead of "-c" option

### ISSUE THREAD

**Issue by ankostis** [xlwings/xlwings#107]
When invoking python-code from Excel's (using internally VBA), it is not possible to use the the double-quotes(`"`) character, and no indentation.
Therefore, no function definitions or control-flow constructs are possible.
Particularly the capability to define function is imports for receiving back results from the python side (aka callbacks).

This root cause of the above the fact that the python-code is appended as a _cmd-line argument_ to a `python -c` command.
An alternative approach, to create a temporary python-script, would not have these limitations.

I can provide a patch on the `xlwings.bas` file (for Windows) if the suggested change is OK.

**Comment by stonebig** [comment]
hi @ankostis , did you go any  further on your experiment ?

**Comment by fzumstein** [comment]
We have released xlwings PRO which allows you to embed your Python code directly in a sheet. I believe this solves this issue.
