### ISSUE TITLE
can't connect jupyter to excel on mac

### ISSUE THREAD

**Issue by deltahedgetech** [xlwings/xlwings#1073]
#### OS (e.g. Windows 10 or macOS Sierra)
macOS Mojave v10.14.3

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings v0.15.5
Excel v16.23
Python 3.6.5 Anaconda

#### Describe your issue (incl. Traceback!)

First attempt at using xlwings. Running the code in a Jupyter notebook, code is is listed below
# Your traceback here

CommandError: Command failed:
		OSERROR: -1743
		MESSAGE: OS error
		COMMAND: app(pid=17697).count(each=k.workbook)

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

import xlwings as xw
wb = xw.Book('/Users/stuartclark/Desktop/xlwings_test.xlsx')

Also get same error when running
wb = xw.Book()

I've installed the xlwings addin

I've run open /Users/stuartclark/Desktop/xlwings_test.xlsx in a terminal - all ok.

Also run xlwings runpython install and got Successfully installed RunPython for Mac Excel 2016!

```

**Comment by fzumstein** [comment]
Please see this issue: https://github.com/xlwings/xlwings/issues/967 Please reopen if you can't solve it with the instructions there.
