### ISSUE TITLE
xlwings ribbon does not show User Defined Functions component

### ISSUE THREAD

**Issue by joukejensma** [xlwings/xlwings#1075]
## Issue description
My issue is that the ribbon lacks the User Defined Functions component (as shown here https://docs.xlwings.org/en/stable/_images/ribbon.png).
The Python and Advanced parts are shown however.

## Versions
I'm using Windows 10 with Excel 2016. Version of xlwings is 0.15.4 (though other versions have the same issue), Python 3.6.8. 

Also relevant info:
the Excel addin is installed in the %appdata%\Roaming\Microsoft\Excel\XLSTART folder (and the ribbon is shown). However, trying to add the xlwings addin via the VBA screen yields a "Requested type library or wizard is not a VBA project". (For both .xlsx as .xlsm files).

Creating a new xlwings project via the 'xlwings quickstart name' creates an Excelfile which also yields the same error when I'm trying to add the xlwings.xlam file.

Macros are enabled as well as the "trust access to the object model" part in the Excel Trust Center.

It used to work on Windows 7 by the way. Reverting to win7 is not a possibility however (company computers). Perhaps user policies prevent the right part of the ribbon from loading?

**Comment by fzumstein** [comment]
Does it not fix itself when you restart Excel? I've seen this happening sometimes, too. The reason is that the mac/windows platform conditionals don't seem to work 100% reliable which is why it hides that part (thinking it's on mac). I need to look how we can make that 100% reliable.

**Comment by joukejensma** [comment]
Sadly, no. I logged out & back on again but no change...
I'm wondering if fixing the mac/windows conditionals would also fix the "Requested type library or wizard is not a VBA project" error as well...?

I'm using Miniconda3 (variant of Anaconda) by the way if that makes a difference!

**Comment by fzumstein** [comment]
I have not seen that error before, and google doesn't have an easy explanation. Maybe download the addin directly from the release page (https://github.com/xlwings/xlwings/releases) and try with that one (if you haven't done that already).

**Comment by joukejensma** [comment]
I've tried to install the addin manually but to no avail...

To find a solution I've tried to find where the Mac/Windows check is done but apparently not in the xlwings.xlam file...? 
If there's any testing I can do to check potential solutions just let me know.

**Comment by fzumstein** [comment]
were you ever able to make this work @joukejensma ?

**Comment by joukejensma** [comment]
@fzumstein : unfortunately no. My home setup has Windows 10 with Excel 2016 as well and no problems there (the aforementioned setup is a company setup).
So perhaps the root cause might be found in company-specific setup, such as user policies or other possible restrictions...!

**Comment by fzumstein** [comment]
Can you try with this version and let me know if everything shows up?
[xlwings.zip](https://github.com/xlwings/xlwings/files/3145548/xlwings.zip)

**Comment by joukejensma** [comment]
I tested the file and the UDF field (including the new conda fields) show up! No time to test any further for today but I'll confirm later this week whether the UDF files etc. work. But for now everything seems to look as it should.
Thanks for getting back on this issue! Much appreciated.

**Comment by fzumstein** [comment]
thanks for the feedback! The ribbon won't work if you use UDFs as it has the 'dev' version stamp on it (it would look for the dlls with the dev version). But I know how to fix now and will hopefully release this soonish.

**Comment by fzumstein** [comment]
Closing this as it seems to be a very seldom edge case.
