### ISSUE TITLE
Can't use RunPython function from xlwings

### ISSUE THREAD

**Issue by Magic-fan** [xlwings/xlwings#1077]
Hello Guys,
 
I just followed the same instructions as mentioned in the documentation.
But i can't use Run Python function.
I get this error by the way : 
Python is not recognized as an internal or external command

Could you help me to fix this issue ?
Do you have any ideas how to avoid this ? 

I really appreciate your help.

Sincerely Yours

**Comment by fzumstein** [comment]
You'll either need to add python to your PATH env var or you'd need to specifiy the full path to the pythonw.exe in your interpreter, see: http://docs.xlwings.org/en/stable/addin.html#global-settings
