### ISSUE TITLE
path problems

### ISSUE THREAD

**Issue by vks2** [xlwings/xlwings#1078]
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here
Could not load source '<string>': Source unavailable.
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
import xlwings as xw
import os
import tkFileDialog

dirname = tkFileDialog.askdirectory()
xlsFileList = [ ]
for root, dirs, files in os.walk(dirname):
    for file in files:
        if file.endswith(".xls") or file.endswith(".xlsx"):
            xlsFileList.append(os.path.join(root, file))
for f in xlsFileList:
    try:
        myCell = xw.Book(f).sheets[1].api.UsedRange.Find("710*")
        print myCell.address
    except:
        print -1

```
os.startfile sees all files in list, but xlwings - no.
What i'm doing wrong?
Thank you.

PS hardcoded dirname = r"C:\f\s\a\b" doesn't work either. (while os.startfile  works)

**Comment by fzumstein** [comment]
xlwings currently doesn't have a deterministic working directory. try to set the working directory at the top to the one you have when you run it outside of xlwings and see if that resolves the issue.

**Comment by vks2** [comment]
sorry, it doesn't.
I have lot of subfolders with a 5-6 xls inside them, so I used other decisions to open files and work with them. xlwings in the root doesn't seem to work either.
Thanks a lot and sorry for this, the product seems to be really good, but not very suitable for my purposes.
