### ISSUE TITLE
ImportError: Import aem and _xlmac fail

### ISSUE THREAD

**Issue by volade** [xlwings/xlwings#1079]
#### OS (e.g. Windows 10 or macOS Sierra)

Mac OS Mojave

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

xlwings 0.15.4, Python 3.7, Excel Version 16.23

#### Describe your issue (incl. Traceback!)

I try to import xlwings and it gives me an error. I thought it was due to not having dependencies like appscript installed. I installed appscript but I still get an error. When I try to import appscript from the shell it gives me a ModuleNotFound error as well.

```python
# Your traceback here

Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    import xlwings
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xlwings/__init__.py", line 44, in <module>
    from . import _xlmac as xlplatform
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xlwings/_xlmac.py", line 10, in <module>
    import aem
ModuleNotFoundError: No module named 'aem'

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
how did you install appscript/xlwings?

**Comment by volade** [comment]
Thank you for responding, Felix. I figured it out just a few minutes ago! For some reason when I used conda and pip to install xlwings and appscript it didn't work. It wasn't until I downloaded "appscript-1.1.0-cp37-cp37m-macosx_10_7_x86_64.whl (84.1 kB)" from https://pypi.org/project/appscript/#files and installed that file through the terminal that it finally seemed to import without any error.

**Comment by Alishachen900** [comment]
> Thank you for responding, Felix. I figured it out just a few minutes ago! For some reason when I used conda and pip to install xlwings and appscript it didn't work. It wasn't until I downloaded "appscript-1.1.0-cp37-cp37m-macosx_10_7_x86_64.whl (84.1 kB)" from https://pypi.org/project/appscript/#files and installed that file through the terminal that it finally seemed to import without any error.

how can you clean the error? I have the same problem with you....Thanks

**Comment by Alishachen900** [comment]
> Thank you for responding, Felix. I figured it out just a few minutes ago! For some reason when I used conda and pip to install xlwings and appscript it didn't work. It wasn't until I downloaded "appscript-1.1.0-cp37-cp37m-macosx_10_7_x86_64.whl (84.1 kB)" from https://pypi.org/project/appscript/#files and installed that file through the terminal that it finally seemed to import without any error.

And I try to find the files you side, how to install that 'whl' file through the terminal ?
