### ISSUE TITLE
Copy sheet to new workbook

### ISSUE THREAD

**Issue by volade** [xlwings/xlwings#1080]
#### OS (e.g. Windows 10 or macOS Sierra)

MacOS 10.14.3 (Mojave)

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

xlwings 0.15.4, Python 3.7, Excel Version 16.23

#### Describe your issue (incl. Traceback!)

I am trying to have xlwings move a sheet from an .xlsx workbook into a new .xlsm workbook and then execute a macro in that new .xlsm workbook. The table in the original workbook is a pivot table and it has to be move/copied over exactly as it is without losing it's structure. I want all this to run in the background which I read somewhere is only possible by using "app = xw.App(visible=False)". I run into problems when I use this "sht.api.copy_worksheet(after_=sht_new.api)" to copy from the sheet in the original xlsx workbook to the sheet in the new xlsm workbook.

```python
# Your traceback here

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aeosa/appscript/reference.py", line 482, in __call__
    return self.AS_appdata.target().event(self._code, params, atts, codecs=self.AS_appdata).send(timeout, sendflags)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aeosa/aem/aemsend.py", line 92, in send
    raise EventError(errornum, errormsg, eventresult)
aem.aemsend.EventError: Command failed: The object you are trying to access does not exist (-1728)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/victorolade/Box/python_programs/scripts/yieldmo_report_pull.py", line 133, in <module>
    sht.api.copy_worksheet(after_=sht_new.api)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aeosa/appscript/reference.py", line 518, in __call__
    raise CommandError(self, (args, kargs), e, self.AS_appdata) from e
appscript.reference.CommandError: Command failed:
		OSERROR: -1728
		MESSAGE: The object you are trying to access does not exist
		COMMAND: app('/Applications/Microsoft Excel.app', newinstance=(0, 635035)).workbooks['2019 6_59_51 PM_2019-03-05_16686955.xlsx'].worksheets['Ad Group Performance'].copy_worksheet(after_=app('/Applications/Microsoft Excel.app', newinstance=(0, 635035)).workbooks['2019 6_59_51 PM_2019-03-05_16686955v2.xlsm'].worksheets['Sheet1'])

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
please include a full sample to replicated

**Comment by volade** [comment]
path = os.chdir('/Users/victorolade/Box/Domo - AARP/Yieldmo')

        filenames = glob.glob('../Yieldmo/*PM_*.xlsx')
        for file in filenames:
            bn = os.path.basename(file)
            no_ext = bn[:-5]
            new_name = no_ext + "v2" + ".xlsm"

            path2 = '/Users/victorolade/Box/Domo - AARP/Yieldmo/' + new_name

            workbook = xlsxwriter.Workbook(path2)

            path3 = '/Users/victorolade/Box/Domo - AARP/Yieldmo/vbaProject.bin'
            
            workbook.add_vba_project(path3)

            workbook.close()

            app = xw.App(visible=False)
            wb = app.books.open(file)
            
            sht = wb.sheets['Ad Group Performance']
            
            new_wb = app.books.open(path2)
            
            sht_new = new_wb.sheets['Sheet1']
          
            sht.api.copy_worksheet(after_=sht_new.api)
            wb.save(file)
            new_wb.save(new_name)
            app.kill()
 
SAMPLE file to be copied into new book:

[2019 6_59_51 PM_2019-03-05_16686955.xlsx](https://github.com/xlwings/xlwings/files/3080777/2019.6_59_51.PM_2019-03-05_16686955.xlsx)

Macro to be applied into new file:

Sub ChangeToTabular()
Dim PvtTbl As PivotTable
Dim pvtFld As PivotField

On Error Resume Next
Set PvtTbl = ActiveSheet.PivotTables(1)

If Not PvtTbl Is Nothing Then
    PvtTbl.RowAxisLayout xlTabularRow
    PvtTbl.RepeatAllLabels xlRepeatLabels
Else
    MsgBox "No pivot tables on this sheet"
End If

With PvtTbl
 For Each pvtFld In .PivotFields
 pvtFld.Subtotals(1) = False
Next pvtFld
End With

End Sub
