### ISSUE TITLE
-2147417843(8001010d) error is occurred when UDF is executed in the callback function

### ISSUE THREAD

**Issue by heury** [xlwings/xlwings#1081]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.15.5, Office 365, Python 3.7

#### Describe your issue (incl. Traceback!)

I defined printHello() as follows
```
@xw.sub
def printHello():
    print('Hello World')
```

'printHello() is executed normally in the vba script
```
Sub Test()
    Call printHello 
End Sub
```

'But -2147417843(8001010d) error is occurred when it is executed in the ole obj's callback function

```
Private Sub OleObj_OnLogin()
    Call printHello
End Sub

```
This error is caused by XLPyDLLActivateAuto
```
Function Py()
    XLPyLoadDLL
    If 0 <> XLPyDLLActivateAuto(Py, XLPyCommand, 1) Then Err.Raise 1000, Description:=Py
End Function
```

I doubt UDF defined by xlwings does not work in the callback function.

**Comment by fzumstein** [comment]
What calls `OleObj_OnLogin()`?

**Comment by heury** [comment]
It is callback function.
For example, following method will call it.
OleObj.Login(id, passwd)

**Comment by heury** [comment]
I googled and found following contents
Is it related with this error?

**You should only use the Excel COM object model from the main Excel thread. Thus not from other threads, Tasks that you create, timer callbacks that you set up**. It's safe to call it from a ribbon callback, of any macro (ExcelCommand). If you have a timer or some other thread that needs to do work back on the main thread, you can start a macro context running on the main thread with a call to ExcelAsyncUtil.QueueAsMacro(...). This waits for Excel to be ready, then runs the delegate you pass. In there, you can use the object model.
https://github.com/Excel-DNA/ExcelDna/wiki/COM-object-model-notes

**Comment by fzumstein** [comment]
@heury were you able to find a solution for this?
