### ISSUE TITLE
Raise exception when apps.excel.active called and no Excel instance is running?

### ISSUE THREAD

**Issue by BlooHirsch** [xlwings/xlwings#1083]
0.15.3/Office 2013/Python 3.7

#### Issue

While starting to write every code/notebook, I always have to include the following code to make this work:

```python
try:
    app = xw.apps.active
    onbook = app.books.open('sample.xlsx')
except:
    app = xw.apps.add()
    onbook = app.books.open('sample.xlsx')
onsheet = onbook.sheets.active
```

or I could go with this one:

```python
if xw.apps.active:
	app = xw.apps.active
```

First approach would probably be described as more pythonic way to do that (as it follows the doctrine of forgiveness instead of asking for permission), but it seems kind of sloppy to write exactly the same code two times. The issue is: I can't just wrap assigning `app` name in try/except block, because calling `xw.apps.active` while no instance is active doesn't raise any exception - just assigns `None` to variable. So in order to check if any exception was raised, I always have to write something after this statement. 

#### Summary

If there is any reason behind this, my apologies for ignorance (and kind of trivial question) - but as far as I am concerned, raising an exception would definitely be a forgiveness-friendly approach.

quick edit: of course I mean rather something like turning it into a *method* of getting the active instance instead of property (which of course couldn't raise exception) - that may have sounded unclear.

**Comment by fzumstein** [comment]
Hey, while it's true that exception handling is a big item on the todo list, you should probably just do `onbook = xw.Book('sample.xlsx')` in your case? That will happily use the active instance and if Excel isn't running, will start it.

**Comment by BlooHirsch** [comment]
Thanks! While starting an app manually is useful for me sometimes (e.g. for the sake of setting visibility), that approach is exactly what I was looking for.

**Comment by fzumstein** [comment]
you should still be able to set visibility of the app even when using this approach: 

```
wb = xw.Book(...)
wb.app.visible = False
```
