### ISSUE TITLE
Save as xlam

### ISSUE THREAD

**Issue by Charles-Fox1234** [xlwings/xlwings#1087]
Windows 10, xw 0.11.5

When I try to save a workbook as an excel add-in, I receive the following error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Excel', 'SaveAs method of Workbook class failed', 'xlmain11.chm', 0, -2146827284), None)

```python
bk.api.IsAddin = True
bk.api.SaveAs(tool_name,"xlOpenXMLAddIn")

```

However, I was able to get the below to work:

VBA in the project workbook:
`
Sub SaveThisBookAsAddIn(path)
    ThisWorkbook.IsAddin = True
    Application.DisplayAlerts = False
    ThisWorkbook.SaveAs path, xlOpenXMLAddIn
    Application.DisplayAlerts = True
End Sub

Sub DeployAsAddIn(path)
    ImportPythonUDFs
    SaveThisBookAsAddIn path
End Sub
`

```python
import xlwings as xw
import os,sys

def deploy_to_xlstart(project_folder):
    if sys.platform.startswith('win'):
        addin_path = os.path.join(os.getenv('APPDATA'), 'Microsoft', 'Excel', 'XLSTART')
    else:
        print("Cannot deploy addins automatically on Mac.")
        
    project_name = os.path.split(project_folder)[-1]
    app = xw.App(visible=False)
    bk = app.books.open(os.path.join(project_folder,project_name+'.xlsm'))
    macro = bk.macro('DeployAsAddIn')
    macro.run(os.path.join(addin_path,'xlwings_'+project_name))
    bk.close()
    app.kill()
    
    
if __name__ == "__main__":
    deploy_to_xlstart(os.path.join(os.getcwd(),"my_tool"))

```

Should DeployAsAddIn(path) or something similar be added to quickstart.xlsm?

**Comment by Pluckerpluck** [comment]
So I save using XLSB, and my guess is that you need to send the numerical variable as your second parameter.

I use

```python
xl_excel_12 = 50 # XLSB constant
workbook.api.SaveAs(path, FileFormat=xl_excel_12)
```

`xlOpenXMLAddIn = 55` in your case [as found here](https://docs.microsoft.com/en-us/office/vba/api/excel.xlfileformat)

---------

Xlwings should allow saving in different formats, but it is currently a work in progress: https://github.com/xlwings/xlwings/issues/187

**Comment by fzumstein** [comment]
It's not exactly work in progress yet, but the according issue exists, yes :)
