### ISSUE TITLE
RunFrozenPython won't run with spaces in filepath

### ISSUE THREAD

**Issue by tacobeard** [xlwings/xlwings#1095]
Windows 7 64 bit
Office 365 Excel
Python 3.6.4
Xlwings 0.15.6

Here is my script, although I run it as an executable using the commented out line at the bottom of the code below:

```python

import xlwings as xw


def comcall():
	import zenpy, datetime, zdcreds

	wb = xw.Book.caller()
	s1 = wb.sheets[0]
	
	ticket_list = s1.range('input').options(numbers=int, expand='down').value

	ticket_id_out = s1.range('ticket_id_out').options(ndim=2,expand='down',transpose=True)
	comment_text_out = s1.range('comment_text_out').options(ndim=2,expand='down',transpose=True)
	author_id_out = s1.range('author_id_out').options(ndim=2,expand='down',transpose=True)

	full_output = s1.range('ticket_id_out').expand()
	
	full_output.clear_contents()

	ticket_id_list = []
	comment_text_list = []
	author_id_list = []

	print(ticket_list)



	zenpy_client = zenpy.Zenpy(proactive_ratelimit=700, **zdcreds.creds)


	for t in ticket_list:
		for comment in zenpy_client.tickets.comments(ticket=t):
			ticket_id_list.append(t)
			comment_text_list.append(comment.body)
			author_id_list.append(str(comment.author))

	ticket_id_out.value = ticket_id_list
	author_id_out.value = author_id_list
	comment_text_out.value = comment_text_list


if __name__ == '__main__':
	xw.Book('commentcaller.xlsm').set_mock_caller()
	comcall()
	
#To create an executable run the following command:
#pyinstaller.exe --onefile filename.py
```

Here is the VBA I am mapping to a button in Excel:

```
Sub frozencomcall()
    RunFrozenPython ("C:\Users\104702\Desktop\Folder with Spaces\commentcaller\dist\commentcaller.exe")
End Sub
```

When I run it, I get the following error:

![image](https://user-images.githubusercontent.com/22082923/57148385-1b764f00-6d8f-11e9-9a24-c7bea34fd37d.png)

Thank you for your time

**Comment by fzumstein** [comment]
This is fixed since 0.15.6, see: https://github.com/xlwings/xlwings/issues/1063

replace `xw.Book('commentcaller.xlsm').set_mock_caller()` with `xw.Book.caller()`

**Comment by tacobeard** [comment]
Is there a way to write a script that both runs when called from the command line as well as called in vba either frozen as an executable or not?  When I run the code above from the command line after changing per your advice I get the error
```
Exception:  Book.caller() must not be called directly
```
Thank you!

**Comment by fzumstein** [comment]
With RunFrozenPython, it's best if you create a separate helper file, that way you can leave the set_mock_caller for local testing but you call your seperate file with .caller() from the frozen executable.

**Comment by tacobeard** [comment]
Alright it's working now, thank you!
