### ISSUE TITLE
[Support] Questions regarding Trust access to the VBA model

### ISSUE THREAD

**Issue by Pluckerpluck** [xlwings/xlwings#1100]
Hey,

I was just wondering how, in the code, the trigger for requiring `Trust access to the VBA project object model` occurs.

I'm attempting to use xlwings to "bake" pre-made Excel workbooks with Python functionality. As a result, as far as I can tell, there is no need for access to the object model. I could be wrong, but I believe it's about modifying the VBA code, and is used when doing stuff like `Import UDFs`. But as I "bake" my code into the sheet, this isn't needed.

I ask because this may potentially be a roadblock to my project. We're happy to modify our own fork of xlwings as a bypass for this issue if it's not too complicated, so I was wondering if you have any insight here.

If it's simply a COM call we can bypass that triggers it, then that's great! But if it's more complicated it would be nice to know.

**Comment by fzumstein** [comment]
You only need that to import your UDFs, not for anything at runtime.
