### ISSUE TITLE
xlwings sql function error when excel cell contains both " and '

### ISSUE THREAD

**Issue by atallaashraf** [xlwings/xlwings#1101]
#### Describe your issue (incl. Traceback!)

Issue: when an excel cell contains both quote (")  and apostrophe (') sql function returns an error

when using the following function:
=sql("SELECT * FROM a", A1:B3)

and cell B2 contains:  XXX" YYY'
[test_sql.zip](https://github.com/xlwings/xlwings/files/3180553/test_sql.zip)

I get an error:

sqlite3.OperationalError:   near "a2": syntax error         c.execute(stmt)       File   "C:\Users\atall\Anaconda3\lib\site-packages\xlwings\ext\sql.py", line   50, in sql         ret = func(*args)       File   "C:\Users\atall\Anaconda3\lib\site-packages\xlwings\udfs.py", line   311, in call_udf         res = call_udf(script, fname,   args, this_workbook, FromVariant(caller))       File   "C:\Users\atall\Anaconda3\lib\site-packages\xlwings\server.py",   line 198, in CallUDF         return func(*args)       File   "C:\Users\atall\Anaconda3\lib\site-packages\win32com\server\policy.py",   line 586, in _invokeex_         return S_OK, -1,   self._invokeex_(dispid, lcid, wFlags, args, None, None)       File   "C:\Users\atall\Anaconda3\lib\site-packages\win32com\server\policy.py",   line 283, in _invoke_         return self._invoke_(dispid,   lcid, wFlags, args)       File   "C:\Users\atall\Anaconda3\lib\site-packages\win32com\server\policy.py",   line 278, in _Invoke_
--

**Comment by fzumstein** [comment]
You must use valid sqlite column names, see: https://www.sqlite.org/lang_keywords.html

**Comment by atallaashraf** [comment]
I am using valid column names. I've attached a sample excel sheet that shows the error.
[test_sql.zip](https://github.com/xlwings/xlwings/files/3180547/test_sql.zip)

**Comment by fzumstein** [comment]
closed by #1102
