### ISSUE TITLE
Runtime Error '-1 (ffffff)': Method 'Run' for object 'IWshShell3' failed

### ISSUE THREAD

**Issue by tobiassoppa** [xlwings/xlwings#1103]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.15.1, Office 2016, Python 3.7.1 (using the Anaconda Distribution)

#### Describe your issue (incl. Traceback!)
RunPython gives "Runtime Error '-1 (ffffff)': Method 'Run' for object 'IWshShell3' failed"

#### Reproducing the issue on my machine
1. Open terminal in Jupyter Lab (only way for me to access the terminal)
2. Type ```xlwings quickstart hello_world```
3. Activate ```xlwings.conf``` sheet
4. Navigate to xlwings add-in tab, set "Interpreter" value to Anaconda's python path
5. Insert "Form Control Button" and assign ```SampleCall``` macro
6. Click on button -> "Runtime Error '-1 (ffffff)': Method 'Run' for object 'IWshShell3' failed"

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
Can you paste the content of `xlwings.conf` sheet? Or why do you activate it when you then set the interpreter in the add-in?

**Comment by tobiassoppa** [comment]
Deactivated the sheet, thanks for clarifying. It's still not working for me, but that shouldn't be related to xlwings. 

I don't have access to Windows' "cmd" on my current machine (it's blocked), thus the xlwings.xlam `ExecuteWindows` method can't be executed. Fortunately I have access to PowerShell, so I try to figure out how to call Python via PowerShell, not the cmd. But as I said, this is not related to xlwings.
