### ISSUE TITLE
xlwings.bas not included in Quickstart on latest version

### ISSUE THREAD

**Issue by jvaldiviezo9** [xlwings/xlwings#1104]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.15.8

#### Describe your issue (incl. Traceback!)
I can see that there is a problem related with the xlwings.bas, for some reason it's not included now whe using "xlwings quickstart myproject", it only references to the addin. Also, I'm unable to reference to xlwings if I manually add the xlwings.bas, not appearing in References

![image](https://user-images.githubusercontent.com/18518204/57880004-5478df80-77e3-11e9-8b31-f291066cccda.png)

What would be the correct approach to distribute a stand alone version without having to install the addin?

**Comment by fzumstein** [comment]
Use the standalone flag, see: http://docs.xlwings.org/en/stable/command_line.html#quickstart

**Comment by jvaldiviezo9** [comment]
But even with that I'm unable to add the references to the "References"

![image](https://user-images.githubusercontent.com/18518204/57881470-fb12af80-77e6-11e9-8ae5-a69d23fce6cb.png)
