### ISSUE TITLE
ExportAsFixedFormat equivalent in xlwings

### ISSUE THREAD

**Issue by wochner** [xlwings/xlwings#1111]
#### xlwings 0.11.8, Excel Office 10 and Python 3.6

Is there an equivalent of the command `ExportAsFixedFormat()` of the native win32com.client module in xlwings or what would be the best option to export/save a single worksheet to pdf? 

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python

import win32com.client as win32
xlapp = win32.DispatchEx("Excel.Application")
wb = xlapp.workbooks.open(r'path_to_excel_file')
wb.ActiveSheet.ExportAsFixedFormat(0, path_to_pdf)

```

**Comment by fzumstein** [comment]
It isn't as such built in, but you can make your life easier by just falling back to pywin32 api only when needed:

```
import xlwings as xw
wb = xw.Book(r'path_to_excel_file')
wb.sheets.active.api.ExportAsFixedFormat(0, path_to_pdf)
```

**Comment by wochner** [comment]
This works fine for us. Thank you for helping out.
