### ISSUE TITLE
xlwings password

### ISSUE THREAD

**Issue by ifuchs** [xlwings/xlwings#1113]
I am using Mac Excel 2011 and if I go to the VBA editor and click on the xlam addin, I get prompted for the password. I thought it was xlwings but that does not work. What is the password?

**Comment by fzumstein** [comment]
For whatever reason, Excel 2011 doesn't recognize the password. You'll need Excel 2016 on Mac or Excel on Windows. Excel 2011 is not supported anymore by Microsoft, so we don't consider this to be an issue. You can access the source code here if you don't have access to Excel 2016: https://app.xltrail.com/#/workbook/github.com%2FZoomerAnalytics%2Fxlwings.git%2Fxlwings%2Faddin%2Fxlwings.xlam/?branch=master&public=true

**Comment by ifuchs** [comment]
I could be mistaken, but I don’t believe there is an Excel 2016 for the Mac. There is Excel 2015 which is part of Office 2016. I have v 15.36. Would that work?

**Comment by fzumstein** [comment]
yes
