### ISSUE TITLE
xlwings run-time error "53" (xlwing 0.15.8)

### ISSUE THREAD

**Issue by KhoaPhamzz** [xlwings/xlwings#1117]
I have Anaconda3 installed on my computer(Windows 10 Home, 64-bit), and I am using office 16. When I run "import Functions" from add-in, which is also the same version with xlwings, and I got an error as below:

![1](https://user-images.githubusercontent.com/51881549/59564816-9a8cc180-9075-11e9-9803-c2bc1c27cf9f.PNG)

Please help me fix this.

#### Describe your issue (incl. Traceback!)

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
@KhoaPhamzz Were you able to solve this?

**Comment by glennmill** [comment]
Having the same exact issue here.

**Comment by jbmaggard** [comment]
Having problem with Import Functions on Office 365 (64 bit) that does not exist with Office 2016 (32 bit) on the same pair of .xlsm/.py files.

Error 53, xlwings64-0.15.10.dll
Windows 10, Office 365

Confirmed presence of .dll in the Anaconda 3 folder (2019.10), and tried adding that folder at beginning of system path before starting Excel 365.

Tried using full path to pythonw.exe in Interpreter both on Ribbon and in xlwings.conf worksheet tab.

Any help on getting VBA in Excel 365 to execute general .dll code (written in C or Fortran) would also be appreciated, as I also need this capability.

**Comment by fzumstein** [comment]
@jbmaggard Try to debug [this part](https://app.xltrail.com/#/workbook/github.com%2FZoomerAnalytics%2Fxlwings.git%2Fxlwings%2Faddin%2Fxlwings.xlam/module/Main/?branch=master&scroll=%23vba-Main%20.line-num1.linenum-306&public=true) to see on what path it is looking for the dll. That should give you a hint why it doesn't find it (the add-in password is `xlwings`).

**Comment by jbmaggard** [comment]
Felix,


<slaps.self.in.forehead><humility> Thank you. </slaps.self.in.forehead></humility>


Now to get access to a student's Office 365 Installation, or set up an old laptop that way.


-- Bryan



________________________________
