### ISSUE TITLE
Simple RunPython() Call does nothing but returns no error message. 

### ISSUE THREAD

**Issue by VincentGW** [xlwings/xlwings#1122]
Total noob here, sorry.

Windows 10
Most up to date versions of Excel(<1yr), Python(<1wk) and xlwings(<1wk)
No Error Msg

When running:

Sub myMacro()
    Range("A1:A6").Value = RunPython("print('Hello Python')")
End Sub

The cursor moves to Cell A6 but the cells contain no new information.

The other day, this function worked, but I fiddled around with a few options and it stopped working, and I don't remember what things I touched.

Python environment variables and PATH set via control panel. Same for pip. xlwings installed via pip. Python successfully runs in cmd and xlwings quickstart myproject runs with no errors but doesn't do anything.

Trying to invoke code through a .py module also does nothing as my IDE doesn't want to acknowledge import xlwings.

Much thanks!

**Comment by VincentGW** [comment]
Also,

I know your documentation says:

`Also, RunPython does not allow you to return values.`

But I did get it to return a string. I do not know if this is what you mean by "value" but I am trying to recreate the return of a printed string argument via print() nested within RunPython().

**Comment by fzumstein** [comment]
You'll need to have this part `Range("A1:A6").Value` in the python script, i.e. `xw.Book.caller().sheets[0].range('A1:A6').value = ...` or you need to use a UDF.

**Comment by VincentGW** [comment]
I got xlwings functional, thanks!

I have another question about for loops and the xw.Book objects. If I wanted to assign a series of pieces of scraped data to a range, would it work with a for loop? Here is my module:

```
import xlwings as xw
import win32clipboard as clipboard
import pyautogui as auto

def vn():
   
    wb = xw.Book.caller()
    auto.click(600, 5)
    auto.hotkey('alt', 'd')

    for counter in range(20):
        auto.typewrite(['left', 'left'])
        auto.hotkey('ctrl', 'c')
        clipboard.OpenClipboard()
        lineData = clipboard.GetClipboardData()
        clipboard.CloseClipboard()
        auto.typewrite('down')
        wb.sheets[0].cells(1, counter).value = lineData
    return;
```
I get a syntax error message that invokes some lines in the xlwings module itself. I may have an incorrect idea of how .cells() works, but I used it since counter does not seem to work within range().

**Comment by fzumstein** [comment]
xlwings doesn't support cells for this use case, use `range` with a tuple instead, see examples: http://docs.xlwings.org/en/stable/api.html#range
