### ISSUE TITLE
Fail to import pandas

### ISSUE THREAD

**Issue by Lars91** [xlwings/xlwings#1127]
**Windows 7 Professional
xlwings 0.11.8
Office 365
Python 2.7
pandas 0.24.2
numpy 1.14.2**

Problem: Fail to import pandas due to dependency issues with numpy (similar to #1115)

Hey guys,
I would like to run a python script with Excel. Xlwings is used via the xlwings VBA module.
PYTHON_WIN used in this module is: C:\ProgramData\Miniconda3\envs\py27\python.exe which is the path of my python interpreter (sys.executable).

When running "python" and "import pandas as pd" in anaconda promt everything is fine.
However, running the python script via Excel leads to the following issue:

**Error Message**
Traceback (most recent call last):
File "<string>", line 1, in <module>
File
"...\Worksheet.py", line 2, in <module> 
import pandas as pd
File
"C:\ProgramData\Miniconda3\envs\py27\lib\site-packages\pandas\__init__.py", line 19 in <module>
"Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']

**Python Code**
import xlwings as xw
import pandas as pd
from sqlalchemy import create_engine
import time
import os
import tia.bbg.datamgr as dm
from tia.bbg import LocalTerminal
mgr = dm.BbgDataManager()
import win32api
import requests

Many thanks in advance for your help.

**Comment by fzumstein** [comment]
Anaconda changed the way that they activate the conda enviroments so you'll need to upgrade to the latest xlwings version where you can properly set the conda environment. If you can't upgrade, you'll need to have pandas installed in the base installation and set the path as described in the other issue you mention.

**Comment by rhaskett** [comment]
I'm having this issue as well in Windows with a fresh install of the 2019.07 version of Anaconda.  Is there an example on how to set this in an xlwings.conf tab?

For instance, if my Anaconda is installed in "C:\anaconda3" and my src is in in "C:\[blah]\src"

**Comment by fzumstein** [comment]
@rhaskett I think you're seeing this issue: https://github.com/xlwings/xlwings/issues/1110 as for @Lars91 I think this is this issue: https://stackoverflow.com/questions/41859939/python-pandas-missing-required-dependencies-numpy-1

**Comment by rhaskett** [comment]
I see.  I tried to downgrade my xlwings version to before the conda environment code was added v0.15.1 and that did not seem to help.  Is there a better work around?

**Comment by rhaskett** [comment]
Adding the 

C:\anaconda3
C:\anaconda3\Scripts
C:\anaconda3\Library\bin
C:\anaconda3\usr\bin
C:\anaconda3\mingw-w64\bin

to the user's "Path" seems to solve the issue as you have suggested in other threads.   I'll keep an eye on #1117 

Sorry to hijack your thread Lars.
