### ISSUE TITLE
Run-time error '13' and '429' when starting xlwings

### ISSUE THREAD

**Issue by cnorvill** [xlwings/xlwings#1134]
OS - Windows 10

Versions of xlwings - 0.15.8
Excel - Office 365
Python - Python 3.7.4

Very new to xlwings. Following the installation guidelines, i have installed xlwings using pip in Python 3.7.4.

I used the `xlwings quickstart myproject' function to create a test document. When I attempt to call the test UDF, it does not find the UDFs in the associated .py file. Clicking import functions in the xlwings tab causes a Run-time error 429 "ActiveX component can't create object" to pop up. 

Clicking any of the other options or altering fields in the xlwings tab returns a Run-time error 13 "Type Mismatch" to pop up

If i try to use the examples called out in this thread, the functons all return "ActiveX component can't create object"

https://github.com/xlwings/xlwings/issues/574

"Debug" for the 13 runtime error causes the it to die in the (see screenshot) below place

![image](https://user-images.githubusercontent.com/37912636/62085434-8964d200-b229-11e9-929a-a52b30096ae0.png)

"Debug" for the 429 runtime error causes the it to die in the (see screenshot) below place

![image](https://user-images.githubusercontent.com/37912636/62085440-9255a380-b229-11e9-8812-3f89858ae659.png)

Reading and writing to excel docs works just fine from the python side, but I cannot seem to get UDFs to work. And suggestions?

![image](https://user-images.githubusercontent.com/37912636/62084915-60900d00-b228-11e9-8032-91282eb4244d.png)

![image](https://user-images.githubusercontent.com/37912636/62084891-4fdf9700-b228-11e9-8223-990d7e243b2c.png)

**Comment by fzumstein** [comment]
@cnorvill were you ever able to resolve this?

**Comment by samcormack** [comment]
I've run into the same error 429 in the same place (`CreateObject('WScript.Shell')`). 

Similar setup:

OS - Windows 10
Versions of xlwings - 0.15.1
Excel - Office 365
Python - Python 3.6.7

The error only occurs on one particular client's laptop and they are in a different city which makes testing things fairly difficult. It does seem that this is not really an xlwings problem, but a VBA/wscript/Windows problem. Unfortunately, the VBA error is vague enough that I'm not sure where to start debugging it. I did try running the 'wscript' command from the command line and it ran fine. 

If anyone has any ideas I can try, I'd be grateful.

**Comment by fzumstein** [comment]
There were cases where WindowsDefender or some anti virus software was causing issues...

**Comment by julioolvera1** [comment]
Hi guys, I have the same problem:

OS Windows 10
Versions of xlwings=0.20.7, Excel=365 and Python=3.7.9
I am having some problems with xlwings even after removing and reinstalling several times.

I created a completely new anaconda environment in Windows: excelPy

I installed the latest version of xlwings using:

conda install -c conda-forge xlwings

and got version 0.20.7

I installed the xlwings addin

xlwings adding install

I created a new project:

xlwings quickstart myproject

Opened the xlsm file, enabled content and tried "Run main", got:

Run-time error '429' ActiveX component can't create object

Also, I tried Repairing Office but did not work either, I keep getting Run-time error 429, ActiveX component can't create object.

I think the problem might be somewhere here:

![image](https://user-images.githubusercontent.com/30075340/95960807-234b7700-0dfc-11eb-8a4a-3f614787ca6e.png)

**Comment by julioolvera1** [comment]
Did anyone manage to resolve this?

**Comment by fzumstein** [comment]
See also here: https://www.access-programmers.co.uk/forums/threads/run-time-error-13-type-mismatch-occurs-for-createobject-outlook-application.158465/, as mentioned earlier in this thread, it looks more like an issue with your system than with xlwings. Do you have any anti-virus installed?
