### ISSUE TITLE
"ImportError: DLL load failed. The specified module could not be found." when using xlwings and trying to import numpy

### ISSUE THREAD

**Issue by jfmhbfrost** [xlwings/xlwings#1136]
I'm using Windows 7 64-bit laptop and version 0.15.8 of xlwings, excel 2007 and anaconda 3 with version 3.7 of python.

I've recently downloaded the xlwings package and I'm trying to use the 'Run Python' function to run some code in python through vba. I have been using Spyder to execute my code and in Spyder my code runs perfect with no errors. However, when trying to run this from vba with the xlwings package I receive an error: "ImportError: DLL load failed: The specified module could not be found." and this error relates to the numpy package.

I have tried uninstalling and reinstalling the anaconda package and using pip install numpy but I'm still returning the same error. I have also checked that I have the most up to date version of xlwings. I've also tried searching online for any answers, but I'm yet to find anything which works.

This is my VBA code:
`    RunPython ("import Demand; Demand.calibrate_Demand()")`

In spyder this is my code:

```
    import numpy as np
    import xlwings as xw
    import pandas as pd
    import statsmodels.api as sm
    from statsmodels.tsa.arima_model import ARMA
    from statsmodels.tsa.arima_model import ARMAResults
    from matplotlib import pyplot as plt
    import datetime

    def calibrate_Demand():
```
and my python file is called Demand.py

So when executing my vba code I receive the following error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "e:\julia\calibration automation\Demand.py", line 17, in <module>
    import numpy as np
  File "C:\Users\julia\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\julia\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.
If I place import pandas as pd first (before importing numpy) I receive this error

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "e:\julia\calibration automation\Demand.py", line 19, in <module>
    import pandas as pd
  File "C:\Users\julia\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']

I found issue #954 but this hasn't really helped me.

**Comment by fzumstein** [comment]
Try this: https://stackoverflow.com/questions/41859939/python-pandas-missing-required-dependencies-numpy-1

**Comment by jfmhbfrost** [comment]
I have tried uninstalling numpy but I'm then unable to reinstall numpy because of connection issues. This has meant I've had to uninstall anaconda and then reinstall it.

**Comment by kurt-rhee** [comment]
@fzumstein Hey Felix, I believe this is an issue with xlwings and not numpy/pandas.  I am able to run a script in Spyder inside of an Anaconda environment without any errors, but when run from runPython in excel I get the following:

![Error](https://user-images.githubusercontent.com/33131958/65379971-3be36f00-dc86-11e9-8c87-f8fcb236ac0f.JPG)

**Comment by fzumstein** [comment]
@kurt-rhee are you setting the conda env up in xlwings via conda base / conda env?

**Comment by kurt-rhee** [comment]
@fzumstein I am, but I can only get the xlwings program to run if I leave conda base empty.  Otherwise I get another set of errors.

**Comment by fzumstein** [comment]
Can you try with a conda env != base? as there is that: https://github.com/xlwings/xlwings/issues/1110

**Comment by kurt-rhee** [comment]
I believe conda env already != conda base

- interpreter:  G:\General\Solar\R_and_D\CodeLibrary\Python\anaconda3\envs\clim_env\pythonw.exe
- PythonPath:  G:\\General\Solar\R_and_D\CodeLibrary\Python\ClimateFile
- CondaBase:  G:\General\Solar\R_and_D\CodeLibrary\Python\anaconda3
- CondaEnv: G:\General\Solar\R_and_D\CodeLibrary\Python\anaconda3\envs\clim_env

I have also tried changing the interpreter to '' and to python but no luck, I get:

![image](https://user-images.githubusercontent.com/33131958/65533094-e2f81e80-deb1-11e9-806d-67724a6bb1ea.png)

**Comment by whoopnip** [comment]
I was also running into this issue. Not sure if it's an option for you, but adding Anaconda to Windows `PATH` got it working for me. It wasn't enough to add just the base Anaconda folder, I also added the `\Scripts` and `\Library\bin` folders, which are the same three that get added to `PATH` if you select that option during Anaconda install.

So for me, I edited the environment variable PATH to add:

`;C:\Users\username\Anaconda3;C:\Users\username\Anaconda3\Scripts;C:\Users\username\Anaconda3\Library\bin`

It would be the same for you, just replacing `C:\Users\username\Anaconda3` with your root folder for Anaconda.

**Comment by fakewalrus** [comment]
I wrestled with this for the better part of a day, trying all sorts of variants along the lines of the recommendation by @whoopnip and various adjustments to the xlwings parameters in the config file (CONDA BASE, CONDA ENV, INTERPRETER, PYTHONPATH).

What worked for me in the end was specifying the CONDA BASE and the CONDA ENV and leaving the INTERPRETER and PYTHONPATH blank.  There is a tidbit in the online documentation under Add-In/Global Settings section that mentions that if conda base is specified this "requires you to either leave the Interpreter blank or set it to python or pythonw."  For whatever reason, when I had made a specification in the INTERPRETER field as well as in the CONDA BASE and CONDA ENV fields, I encountered the problem of ModuleNotFoundError, however when I removed the specification in the INTERPRETER field, it worked.  In the end I did not need to make any adjustments to my PATH variables at user or system level along the lines of the remarks by @whoopnip 

Incidentally, I am using a CONDA ENV that is not "base"

**Comment by fzumstein** [comment]
I think this should be solved, maybe the docs can be improved for the conda part, but closing this.

**Comment by lucaspenna00** [comment]
@fakewalrus thank you! your suggestions worked here!

**Comment by fzumstein** [comment]
@lucaspenna00 note that these days you can just run:

```
xlwings config create --force
```
