### ISSUE TITLE
Import Functions Button Freezes/Crashes Excel

### ISSUE THREAD

**Issue by desanti6** [xlwings/xlwings#1137]
#### I installed the add-in bar as instructed. I have tried to follow all the docs for the add-in install, however, whenever I try to use the import functions button, excel freezes and I have to kill it from the task manager. I'm not sure why this is happening. xlwings works well from python (can read, write, etc). I'd really like to get the UDF working though. Any advice?

Thank you

**Comment by fzumstein** [comment]
This might be this error: https://github.com/xlwings/xlwings/issues/1166 feel free to reopen if it isn't.

**Comment by HKubinhetz** [comment]
Deleting the xlwings.conf file and running the quickstart seemed to do the trick here! No need to reinstall Office.
