### ISSUE TITLE
Command failed: The user has declined permission. (-1743)

### ISSUE THREAD

**Issue by bishonen** [xlwings/xlwings#1146]
macOS 10.14.6

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.15.8

#### Describe your issue (incl. Traceback!)

/Users/xxxx/Jetbrains/PyCharm/Go_slicer/venv/bin/python /Users/ijakubo/Jetbrains/PyCharm/Go_slicer/test.py
Traceback (most recent call last):
  File "/Users/xxxx/Jetbrains/PyCharm/Go_slicer/venv/lib/python3.7/site-packages/aeosa/appscript/reference.py", line 482, in __call__
    return self.AS_appdata.target().event(self._code, params, atts, codecs=self.AS_appdata).send(timeout, sendflags)
  File "/Users/xxxx/Jetbrains/PyCharm/Go_slicer/venv/lib/python3.7/site-packages/aeosa/aem/aemsend.py", line 92, in send
    raise EventError(errornum, errormsg, eventresult)
aem.aemsend.EventError: Command failed: The user has declined permission. (-1743)

```

import xlwings
xlwings.Book()
```

----------------------------------------------
The above is being returned in PyCharm (latest version)
I am able to add automation permissions as described in other (closed) issues for the terminal/iterm, but am failing to do the same with PyCharm.

**Comment by fzumstein** [comment]
Try to reset according to this blog: https://bitsplitting.org/2018/07/11/reauthorizing-automation-in-mojave/

When you use xlwings from PyCharm, it should ask you for the permission, you might have clicked "no" at some point.

**Comment by Gaomojiang** [comment]
> Try to reset according to this blog: https://bitsplitting.org/2018/07/11/reauthorizing-automation-in-mojave/
> 
> When you use xlwings from PyCharm, it should ask you for the permission, you might have clicked "no" at some point.

I have the same problem, when i use xlwings from pycharm,it di not ask me for zhe permission,how i can fix it

**Comment by bishonen** [comment]
> Try to reset according to this blog: https://bitsplitting.org/2018/07/11/reauthorizing-automation-in-mojave/
> 
> When you use xlwings from PyCharm, it should ask you for the permission, you might have clicked "no" at some point.

Thank you Felix. Unfortunately I have googled this solution, too, and found that it does nothing for PyCharm (tried it twice). Same as the poster above, PyCharm simply never asks for that automation permission. Resetting the settings and re-running xlwings from the terminal, triggers the permission instantly, on the other hand.

**Comment by Gaomojiang** [comment]
> > Try to reset according to this blog: https://bitsplitting.org/2018/07/11/reauthorizing-automation-in-mojave/
> > When you use xlwings from PyCharm, it should ask you for the permission, you might have clicked "no" at some point.
> 
> Thank you Felix. Unfortunately I have googled this solution, too, and found that it does nothing for PyCharm (tried it twice). Same as the poster above, PyCharm simply never asks for that automation permission. Resetting the settings and re-running xlwings from the terminal, triggers the permission instantly, on the other hand.

so am i ,

**Comment by fzumstein** [comment]
what versions of pycharm are you guys running?

**Comment by fzumstein** [comment]
Can you also include the following screenshot please:

<img width="780" alt="47533622-bd831f00-d8b4-11e8-9826-f0969ebb69ec" src="https://user-images.githubusercontent.com/2265504/65829645-c855e900-e2a7-11e9-9a41-a1964dc6708d.png">

**Comment by bishonen** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/11603939/65829769-13bcc700-e2a9-11e9-8cbc-18103b3e7056.png">

<img width="780" alt="image" src="https://user-images.githubusercontent.com/11603939/65829774-26cf9700-e2a9-11e9-8139-08779faf51f1.png">

**Comment by fzumstein** [comment]
Have you ever tried executing xlwings commands from the built-in terminal in PyCharm rather than using the play button?

**Comment by bishonen** [comment]
Yes, I did. Effect remains the same, unfortunately:

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/11603939/65830456-e293c500-e2af-11e9-85c9-04418c418260.png">

**Comment by fzumstein** [comment]
really don't know how to fix this - the only other thing I can think of is to also run xlwings from the built-in terminal instead of just iTerm2. I assume you have already tried running fro PyCharm with and without debug mode.

**Comment by fzumstein** [comment]
maybe open an issue with PyCharm, they may have some more ideas. maybe it's just broken in the EAP version you're using? @Gaomojiang what PyCharm version are you using?

**Comment by bishonen** [comment]
You're once again right, Felix. This seems to be an issue with PyCharm itself. Just installed and tested an older version of PyCharm (2018.2.8) and it gave me the pop-up immediately.

Opened an issue with PyCharm below.

Thanks for your help!

https://youtrack.jetbrains.com/issue/WEB-41640

**Comment by intelHEART** [comment]
I open pycharm by {terminal} 

use this  `alias pycharm=/Applications/PyCharm.app/Contents/MacOS/pycharm`
then you can use `pycharm` in terminal to open {Pycharm app}

**Comment by wilhan-nunes** [comment]
> I open pycharm by {terminal}
> 
> use this `alias pycharm=/Applications/PyCharm.app/Contents/MacOS/pycharm`
> then you can use `pycharm` in terminal to open {Pycharm app}

That worked great! It was the simplest way to solve the problem. Thanks!

**Comment by PLAYFULBOY** [comment]
> I open pycharm by {terminal}
> 
> use this `alias pycharm=/Applications/PyCharm.app/Contents/MacOS/pycharm`
> then you can use `pycharm` in terminal to open {Pycharm app}

That also works great for me! Thank you so much!

**Comment by qiezhenxi** [comment]
> I open pycharm by {terminal}
> 
> use this `alias pycharm=/Applications/PyCharm.app/Contents/MacOS/pycharm` then you can use `pycharm` in terminal to open {Pycharm app}

It is really great , Thank you for your help.

**Comment by theconsultant** [comment]
using `alias pycharm='/Applications/PyCharm\ CE.app/Contents/MacOS/pycharm'` and quoting the path worked for me in macOS Mojave 10.14.6 .. along with having Terminal be given Full Disk Access in System Preferences: Security and Privacy: Privacy: Full Disk Access.
