### ISSUE TITLE
how to use 'copy_object' on mac

### ISSUE THREAD

**Issue by edwardair** [xlwings/xlwings#1147]
#### i can use `copy_picture` like this:
```python
from xlwings.constants import CopyPictureFormat, PictureAppearance
sheet.range('A17').api.copy_picture(appearance=PictureAppearance.xlScreen,format=CopyPictureFormat.xlPicture)
```

#### but when i using `copy_object`:
```python
`sheet.range('A17').api.copy_object()`
```

#### errors:
> --> 496                         raise CommandError(self, (args, kargs), e, self.AS_appdata) from e
>     497 
>     498         def AS_formatcommand(self, args):
> 
> CommandError: Command failed:
> 		OSERROR: -1708
> 		MESSAGE: Application could not handle this command.
> 		COMMAND: app(pid=1010).workbooks['test.xlsm'].worksheets['xx'].cells['A17'].copy_object()

i want to copy&paste Range with all it's text/style/font/ect...
Pls help me, thank u

**Comment by fzumstein** [comment]
Use like so:

```
wb.sheets[0].range('A1').api.copy_range()
wb.sheets[0].range('B1').api.paste_special()
```
