### ISSUE TITLE
test_restapi.py not compatible with Python < 3.6

### ISSUE THREAD

**Issue by jonathonw** [xlwings/xlwings#1149]
[test_restapi.py](https://github.com/xlwings/xlwings/blob/master/xlwings/tests/restapi/test_restapi.py#L9) makes extensive use of literal string interpolation (`f''` strings), which was first introduced in Python 3.6 and is incompatible with Python 2.7 and Python 3 prior to 3.6.

**Comment by fzumstein** [comment]
true that, but not very critical since it's only the tests. I am currently trying to setup CI for the tests, so might fix it then.

**Comment by fzumstein** [comment]
in the meantime, 3.5 is EOL and xlwings has dropped support for <3.6
