### ISSUE TITLE
Hello. Thank you for your work on this package. I would like to both write inputs and read outputs of an excel in python without opening excel. The output uses lots of excel formulas, so the problem is that I can't read a cell with a formula in it. 

### ISSUE THREAD

**Issue by BenJShapiro** [xlwings/xlwings#1151]
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
xlwings always requires in installation of Excel with the file opened. You probably want to have a look at openpyxl to read out formulas from an Excel file directly.

**Comment by BenJShapiro** [comment]
Hello. Thanks for getting back to me. 

So if I have Excel installed and the file opened would I be able to write inputs and read outputs using xlwings?

Thanks

**Comment by fzumstein** [comment]
That is correct, yes.

**Comment by BenJShapiro** [comment]
Hello. I am trying to use the Goal Seek function in excel through Python. Is this possible via xlwings?

**Comment by fzumstein** [comment]
Yes, you'd have to access it via the `.api` interface, see: http://docs.xlwings.org/en/stable/missing_features.html
