### ISSUE TITLE
xlwings64-dev.dll required

### ISSUE THREAD

**Issue by cad21** [xlwings/xlwings#1153]
Hi,

After installing xlwing and adding through the cmd window for one of my team mate working on excel 365, i tried to import a library of functions (udfs), which worked since I could call them in any cells.

However when parameters where pass into the functions to retrive the output value, Microsoft Visual Basic generated a Run time error one such as shown below. Could you please advise how to fix this issue getting the xlwings64-dev.dll?

![xlwings_dll_issue](https://user-images.githubusercontent.com/55879508/65765396-0a542300-e120-11e9-85e4-2a18d709b53b.png)

**Comment by fzumstein** [comment]
You're using the dev version of the add-in from GH source code directly which won't work. It needs to be downloaded either from the Release page here on GH or you need to use the version that comes with the official Python package on PyPI. If you need further assistance please consider: https://www.xlwings.org/pricing

**Comment by cad21** [comment]
Hi, many thanks fzumstein! Just did it and it works
