### ISSUE TITLE
Dynamic Array UDFs Only Recalculate by Referenced Cells

### ISSUE THREAD

**Issue by nickderobertis** [xlwings/xlwings#1155]
#### OS (e.g. Windows 10 or macOS Sierra)

Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

xlwings 0.15.10, Excel Professional Plus 2016, Python 3.7

#### Describe your issue (incl. Traceback!)

First, I want to thank you for producing such a great package. 

The dynamic array functionality is very powerful and convenient, but I did hit one issue while trying to use it. When I pass a single cell as an input, and use the `@xw.arg(expand='table')` decorator, then the result will only be recalculated if the referenced cell changes, and not if any of the values picked up by expand change. 

As in my usage the referenced cell would typically be a header cell which is not changing, I must manually re-calculate using  `CTRL` + `ALT` + `F9` to see the result of the dynamic array UDF. Alternatively, I can add `@xw.func(volatile=True)` or `@xw.func(volatile=True, async_mode='threading')` for slow calculations, but this would be quite a bit less efficient in a large workbook where the table values are not changing often.

I looked a bit at implementing this in the Python code, but I think this may require a change to the C++ code as I didn't see anything in the Python code deciding when the UDF should be calculated. I don't have any experience with C++ but if you point me in the right direction I might be able to add a PR.

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Pointing this function at the lop left cell of a table, the output only 
# changes when the top left cell changes, and not any other cell in the table
@xw.func
@xw.arg('data', pd.DataFrame, index=False, expand='table')
@xw.ret(expand='table', index=False)
def print_table(data):
    return data

# Pointing this function at the entire cell range of the table, the output
# changes with any cell changes, but this doesn't use the dynamic expand
# functionality for the argument
@xw.func
@xw.arg('cell_range', pd.DataFrame, index=False)
@xw.ret(expand='table', index=False)
def print_range(cell_range):
    return cell_range

# This works with dynamic expand, but is inefficient
@xw.func(volatile=True)
@xw.arg('data', pd.DataFrame, index=False, expand='table')
@xw.ret(expand='table', index=False)
def print_table2(data):
    return data
```

**Comment by fzumstein** [comment]
Can you add a sample (or upload a sample book) of how the formulas are used in Excel? thanks

**Comment by whoopnip** [comment]
Sure, I've attached here a sample book. I'm not sure if there's some way to keep the xlwings macros, I had to save it as a plain XLSX to allow upload. It was just created with `quickstart` and then calling those functions described in the first post.

[testproj.xlsx](https://github.com/xlwings/xlwings/files/3725692/testproj.xlsx)

**Comment by fzumstein** [comment]
I believe this is not an issue with the new native Excel dynamic arrays, so will put this under 'known issues' with the legacy dynamic array hack.
