### ISSUE TITLE
No module found BS4 using RunPython from VBA

### ISSUE THREAD

**Issue by mfreak95** [xlwings/xlwings#1157]
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
XLWINGS 5.10
Office 365
Python 3.7.3
Anaconda

#### Describe your issue (incl. Traceback!)
I run XLwings with a conda base xl_config like this:

Conda   Base | C:\\Users\\Mark Buis\\Anaconda3
Debug UDFs | FALSE
Log File |  
Use UDF Server | FALSE

And it gives the error:
---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "c:\users\mark buis\onedrive - focus orange advisory b.v\hello2.py", line 10, in <module>

    from bs4 import BeautifulSoup

ModuleNotFoundError: No module named 'bs4'

This package is installed in anaconda since when i run it from spyder which is in anaconda it gives no problems also when i check the installed package lists.

```
Rest of the code runs fine in python so will most probably do fine. Printing hello world works when all the other import are not used.

**Comment by fzumstein** [comment]
My guess is you're seeing this error: https://github.com/xlwings/xlwings/issues/1110 -try to use a conda env for now instead of the base installation.

**Comment by mfreak95** [comment]
Thanks! Got it running by cloning the base environment of anaconda and put the path to this in the Conda Env variable.
