### ISSUE TITLE
How to subscript in a single cell using xlwings?

### ISSUE THREAD

**Issue by chn-cutelotus** [xlwings/xlwings#1161]
How to apply different Fonts in a single cell? 
Such as different color, subscription, superscription,and so on.
Please help, thanks a lot!

**Comment by fzumstein** [comment]
On Windows it's something like this: 

```
myrange.api.GetCharacters(start, end).Font.Bold = True
```

**Comment by chn-cutelotus** [comment]
Thank you @fzumstein for your help. This works. That's what I want.
