### ISSUE TITLE
Object required

### ISSUE THREAD

**Issue by sinto-git** [xlwings/xlwings#1163]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 7
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.16.08, Office 2010 (RU), Python 3.7.3
#### Describe your issue (incl. Traceback!)
When I run Python's function in Excel I get message "Object required".
The button "Run main" is working.

![image](https://user-images.githubusercontent.com/56632215/66909432-6e7a5080-f015-11e9-8b99-eeab8be45c72.png)

Please, help!
Thank you in advance.

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

import xlwings as xw

@xw.func
def main():
    '''Пишем в ячейку A1'''
    wb = xw.Book.caller()
    wb.sheets[0].range('A1').value = 'Hello World!'
    
@xw.func
def Hi_world():
    '''Hi, world'''
    wb = xw.Book.caller()
    wb.sheets[0].range('A1').value = 'Hello World!'
 
@xw.func
def double_sum(x, y):
    """Returns twice the sum of the two arguments"""
    return 2 * (x + y)
	
@xw.func
def hello(name):
    return 'Hello {0}'.format(name)


```

**Comment by fzumstein** [comment]
See: http://docs.xlwings.org/en/stable/addin.html#installation, you need to set the reference to xlwings in VBA editor.

**Comment by sinto-git** [comment]
Thank you, very much!!!
All is working!
I didn't undersand that the flag is needed to set if function imported.

Thank you once more!
