### ISSUE TITLE
RunPython not working on Mac after Catalina update

### ISSUE THREAD

**Issue by barhoom1978** [xlwings/xlwings#1165]
#### Versions of xlwings, Excel and Python 
Excel for Mac vs 16.29

#### Describe your issue (incl. Traceback!)

```python
I did the Catalina update yesterday. Afterwards Anaconda was not working. I reinstalled it, including xlwings. I also executed the following two commands successfully in zsh: 1. "conda install -c conda-forge xlwings" 2. "xlwings runpython install"
If i try to use RunPython in VBA, i get the following error message:
"To enable RunPython, please run 'xlwings runpython install' in a terminal once and try again."
(which i did several times)

Any ideas how to fix this?

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
I just tried on a fresh install of Catalina and Anaconda 2019.10 and couldn't replicate the issues. Make sure that your config is correct so that it still finds python according to your Interpreter settings, this may have changed after the upgrade. Also note that xlwings first sources the `.bash_profile` (conda is setting their conda init there).

**Comment by fzumstein** [comment]
I am closing this as I can't replicate the issue and assume it's a misconfiguration happening from an upgrade. Please reopen if you haven't solved the issue.

**Comment by mnadler** [comment]
@fzumstein I'm a new user and seem to be experiencing this issue on a fresh install via pip.

I am running macOS 10.12.6 and version 0.23.0 of xlwings.

I keep getting "To enable RunPython, please run 'xlwings runpython install' in a terminal once and try again." After running the CLI command. I also verified that the Apple Script installed to ~/Library/Application\ Scripts/com.microsoft.Excel/xlwings.applescript.

Thanks in advance for your help.

**Comment by fzumstein** [comment]
@mnadler do commands in Python (e.g., `xw.Book()`) work?

**Comment by jithuvp** [comment]
@fzumstein I just copied my xlwings-enabled Excel workbook to a new machine (also a Mac). I had to set up anaconda and xlwings from scratch on the new machine. I also installed Runpython. However, I keep getting, "To enable RunPython, please run 'xlwings runpython install' in a terminal once and try again." when I try to run a macro. I can confirm the path on the interpreter does match with that of `which python`. Do you have any idea as to what the issue might be? Please advise.

**Comment by fzumstein** [comment]
@jithuvp you could have a mismatch between the VBA part and the Python package. Feel free to open a new issue and provide more info on the versions as per the issue template.

**Comment by hsibanda** [comment]
Any solution for this yet? Just ran into this issue on a Mac with a new python 3.12 install and a new Excel installation. The command `xlwings runpython install` runs successfully and says RunPython should now be working but that popup still comes up. Tried closing all windows, restarting but no luck

**Comment by Scylla2020** [comment]
Any solution for this yet? Just ran into this issue on a Mac with a new python 3.12 install and a new Excel installation. The command xlwings runpython install runs successfully and says RunPython should now be working but that popup still comes up. Tried closing all windows, restarting but no luck
