### ISSUE TITLE
KeyError when running sheet.range api.Sort in Mac

### ISSUE THREAD

**Issue by tanglijhu** [xlwings/xlwings#1167]
OS (macOS Sierra)
Versions of xlwings, Excel and Python (e.g. 0.11.5, Microsoft Excel for Mac 16.16.14, Python 3.6)

I am trying to run api on an Excel sheet Range object. By appending the api property to the Range object yields a VBA Range object which in turn gives access to its VBA features. By this way, we can use VBA sorting functionality which xlwings does not have. However, I got an KeyError and an associated Attribute Error when I ran it. 

# Traceback:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/anaconda3/lib/python3.6/site-packages/aeosa/appscript/reference.py in __getattr__(self, name)
    574                 try:
--> 575                         selectortype, code = self.AS_appdata.referencebyname()[name]
    576                 except KeyError as e:

KeyError: 'Sort'

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
<ipython-input-56-439a514260c2> in <module>()
      1 ws.range(
----> 2 "A2:N{row}".format(row=last_row)
      3 ).api.Sort(Key1=ws.range("A:A").api, Order1=1)

/anaconda3/lib/python3.6/site-packages/aeosa/appscript/reference.py in __getattr__(self, name)
    575                         selectortype, code = self.AS_appdata.referencebyname()[name]
    576                 except KeyError as e:
--> 577                         raise AttributeError("Unknown property, element or command: {!r}".format(name)) from e
    578                 if selectortype == kProperty:
    579                         return Reference(self.AS_appdata, self.AS_aemreference.property(code))

AttributeError: Unknown property, element or command: 'Sort'

# My Python code:

ws.range("A2:N{row}".format(row=last_row)).api.Sort(Key1=ws.range("A:A").api, Order1=1)

Does anybody may provide any clue on why this happens? Is this something to do with the platform specific coding (api)? 

Thanks! Any help or suggestion will be highly appreciated. 
Li

**Comment by fzumstein** [comment]
Unfortunately, you can't just copy/paste the VBA version for the mac implementation, see also: https://github.com/xlwings/xlwings/blob/master/DEVELOPER_GUIDE.md#mac-implementation

This should work:
```
wb.sheets[0].range('A1:B4').api.sort(key1=wb.sheets[0].range('A:A').api, order1=kw.sort_descending)
```

**Comment by tanglijhu** [comment]
Thanks a lot! However, when I ran this code another error reported:
'''
NameError: name 'kw' is not defined
'''
May I please know what does 'kw' mean or define for in this case? 

Thanks!
Li

**Comment by tanglijhu** [comment]
Thanks a lot! However, when I ran this code another error reported:
'''
NameError: name 'kw' is not defined
'''
May I please know what does 'kw' mean or define for in this case?

Thanks!
Li

**Comment by fzumstein** [comment]
sorry - fixed now.
