### ISSUE TITLE
Change the hard coded UDF server startup timeout to be configurable

### ISSUE THREAD

**Issue by yhlam** [xlwings/xlwings#1168]
There is a hard coded 1 minute timeout of starting python server process: 
https://github.com/xlwings/xlwings/blob/14d0e5663b50a5a3767e06c0e75f4273ab808584/src/xlwingsdll/config.cpp#L479-L503

I have a python installation on a network drive. Sometimes, it can take more than 1 minute to start the python process due to network slowness. It would be nice if the timeout can be configured like other parameters, so that the timeout can be increased for use case like mine which expects long start up time.

Thanks.

p.s. This is a great project. Thank you so much for all your hard work.

**Comment by fzumstein** [comment]
How are you solving the issue currently?

**Comment by yhlam** [comment]
I currently have to start a debug server and use debug mode to work around it

**Comment by fzumstein** [comment]
ok good call! How long does it approx. take to start the server?

**Comment by yhlam** [comment]
Just the server startup is around 1.5min. It takes another 3-4min to import all the dependencies when RunPython is called in the first time. But after that, everything are loaded into memory, so no network related delay in further execution.

**Comment by fzumstein** [comment]
It's easy enough to increase the threshold to 2 minutes for the next release, but until I'll get around to make this properly configurable will take a lot longer.

**Comment by ankitagra** [comment]
I experience the same issue. 
I can load xlwings when I install Python environment (and xlwings) locally in C:.
But when I install Python on a network drive, then I get an error `Could not activate python COM server, hr = -2147221164 1000` (could be related to #1036). And the error pops up exactly after a minute.
@fzumstein is there a way I can change this hard-coded time in my local (xlwings) installation? Or would I need to wait for your release? Could you please tell when you plan to do it plz?

**Comment by fzumstein** [comment]
@ankitagra can you check how long it takes on your side by launching the server manually in debug mode? (see: http://docs.xlwings.org/en/stable/debugging.html#udf-debug-server)

**Comment by ankitagra** [comment]
@fzumstein I tested in debug mode and it takes somewhere around **2.5 mins** (including the Pycharm debugger loading time), so xlwings alone may be taking around **2mins** (or slightly lesser).

Btw, to give more context .... I tested loading xlwings on 2 windows PCs (exactly same build and MS office package) using the Python installation on a **network drive** - one of the PCs loads xlwings fast (around half a min), while the other (problematic) PC crashes (after hitting the cap of 1 min). It is the latter that takes 2+ mins in the debug mode.

I find that even the dll (xlwings32-0.15.3.dll) loading time is different on the 2 PCs (PC1 is quick, PC2 takes long). I was assuming that it should be very similar (considering both have same MSoffice packages, etc).

Please let me know if you want to test anything else.
Please let me know your plans on next xlwings release dates, or some quick fix that I can do on my side to get around with this crashing? Thank you.

**Comment by fzumstein** [comment]
@ankitagra you can download a test package from here: https://ci.appveyor.com/project/zoomeranalytics/xlwings/builds/28823558/artifacts

download the package, then install with pip: `pip install xlwings-4d11f88.tar.gz`.

It has the timeout doubled to 2mins. Let me know if that's good enough. Making it configurable unfortunately isn't something I have the time right now as this is a bigger thing (you can always make me change my mind via: https://www.xlwings.org/pricing)

**Comment by fzumstein** [comment]
HI @ankitagra have you had a chance to test?

**Comment by ankitagra** [comment]
Sorry @fzumstein, dint get time. I'll try to test over this weekend and let you know.
