### ISSUE TITLE
TokenElevationTypeLimited != elevationType

### ISSUE THREAD

**Issue by daviddekoning** [xlwings/xlwings#1170]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.16.0, Office 365, Python 3.7

#### Describe your issue (incl. Traceback!)

When I try to open a book with xlwings, I get the following error:

![image](https://user-images.githubusercontent.com/2060138/67592488-e0494d00-f72d-11e9-8a11-ad6437d9921f.png)

I get several off these pop ups all at once.

It might be an underlying com issue, and not something to do with xlwings, but I wondered if anyone has come across this and has a fix.

```python
com_error                                 Traceback (most recent call last)
<ipython-input-3-79ca5625e1ae> in <module>
----> 1 book = xw.Book()

C:\ProgramData\Miniconda3\lib\site-packages\xlwings\main.py in __init__(self, fullname, impl)
    497                     impl = apps.active.books.add().impl
    498                 else:
--> 499                     app = App()
    500                     impl = app.books[0].impl
    501 

C:\ProgramData\Miniconda3\lib\site-packages\xlwings\main.py in __init__(self, visible, spec, add_book, impl)
    210     def __init__(self, visible=None, spec=None, add_book=True, impl=None):
    211         if impl is None:
--> 212             self.impl = xlplatform.App(spec=spec, add_book=add_book)
    213             if visible or visible is None:
    214                 self.visible = True

C:\ProgramData\Miniconda3\lib\site-packages\xlwings\_xlwindows.py in __init__(self, spec, add_book, xl)
    294         if xl is None:
    295             # new instance
--> 296             self._xl = COMRetryObjectWrapper(DispatchEx('Excel.Application'))
    297             if add_book:
    298                 self._xl.Workbooks.Add()

C:\ProgramData\Miniconda3\lib\site-packages\win32com\client\__init__.py in DispatchEx(clsid, machine, userName, resultCLSID, typeinfo, UnicodeToString, clsctx)
    111     serverInfo = (machine,)
    112   if userName is None: userName = clsid
--> 113   dispatch = pythoncom.CoCreateInstanceEx(clsid, None, clsctx, serverInfo, (pythoncom.IID_IDispatch,))[0]
    114   return Dispatch(dispatch, userName, resultCLSID, typeinfo, clsctx=clsctx)
    115 

com_error: (-2146959355, 'Server execution failed', None, None)

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import xlwings as xw

book = xw.Book()

```

**Comment by fzumstein** [comment]
It's an error in the `pywin32` dependency, looks similar to: https://stackoverflow.com/questions/12705249/error-connecting-to-outlook-via-com
Any chance you're running Excel and Python as different users (like admin and standard users)?

**Comment by daviddekoning** [comment]
thanks, @fzumstein. I seem to have stumbled across the fix: my Office 365 credentials were expired, and once I re-signed in, xlwings is working again.

In case anyone else has this issue, I re-signed in by opening a file from OneDrive, and then clicking on the warning about expired credentials. Clicking the button didn't give any UI feedback, but it seems to have signed me in in the background.

**Comment by daviddekoning** [comment]
Unfortunately, this issue has re-occured. It is intermittent, and I have not been able to identify what conditions trigger the error.

based on the below error log, it seems that a priviledge service is being called (SeCreateGlobalPriviledge). There are two events - one under my username, and another under LOCAL SERVICE.

![image](https://user-images.githubusercontent.com/2060138/68408888-1fc36080-0154-11ea-991c-7fa1c70065f6.png)

![image](https://user-images.githubusercontent.com/2060138/68409544-3fa75400-0155-11ea-9d39-5eadf2f3366d.png)

**Comment by fzumstein** [comment]
do you have some special corporate security settings/tools on your computer?

**Comment by daviddekoning** [comment]
I'm sure there are, I am pursuing with my IT department as well. I'm posting this just in case someone happens to have come across the issue somewhere else.

**Comment by daviddekoning** [comment]
when I run the script as administrator, it works fine, which seems to confirm that this is a security issue, not an xlwings problem.
