### ISSUE TITLE
hi I'm having a problem with my xlwings.

### ISSUE THREAD

**Issue by Duchongc** [xlwings/xlwings#1172]
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here

```
		COMMAND: app('/System/Library/CoreServices/System Events.app').processes[its.unix_id == 28730].frontmost.set(True)

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```
os Permission I gave
thanks!

![image](https://user-images.githubusercontent.com/31360737/67767041-c50e7280-fa8a-11e9-88c2-54e7a4c2b280.png)

**Comment by Duchongc** [comment]
![image](https://user-images.githubusercontent.com/31360737/67767798-300c7900-fa8c-11e9-82ad-c00f2bbb9916.png)

**Comment by fzumstein** [comment]
Looks like a possible duplicate from here? https://github.com/xlwings/xlwings/issues/1146

**Comment by Duchongc** [comment]
ok，thanks，I'll give it a try.
