### ISSUE TITLE
Space in Conda Base Path causes issues

### ISSUE THREAD

**Issue by timomax** [xlwings/xlwings#1176]
Windows 7

Excel 2010, Xlwings 0.16

If you have a a path like C:\Program Files\Anaconda3 then the space causes issues when XLwings activates the environment. This is using the ribbon for configuration.

Tried wrapping in quotes, but that didn't work either.

**Comment by fzumstein** [comment]
usually, this has to fixed in the VBA code

**Comment by timomax** [comment]
Thanks Felix. Annoyingly couldn't figure out the CMD syntax to get it to work.. (even worse from vba!)

For now just mounted my Anaconda location as a drive using SUBST, which seems to do the trick.
