### ISSUE TITLE
i can't use xlwings when running excel as administrator

### ISSUE THREAD

**Issue by davidt35** [xlwings/xlwings#1185]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.15.8, Office 365, Python 3.7.3
#### Describe your issue (incl. Traceback!)
I can't run any xlwings code as administrator. Without admin rights (default state of excel) everything works fine. I just need to run excel as administrator so i am not getting these annoying security popups when clicking on external links because of the onedrive cloud.    

```
Type error: (-2147024156, 'The requested operation requires elevation.', None, None)
Traceback (most recent call last):
  File "chrts_linking.py", line 22, in <module>
    app = xw.App(visible=False)
  File "C:\Users\yyy\Anaconda3\lib\site-packages\xlwings\main.py", line 212, in __init__
    self.impl = xlplatform.App(spec=spec, add_book=add_book)
  File "C:\Users\yyy\Anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 296, in __init__
    self._xl = COMRetryObjectWrapper(DispatchEx('Excel.Application'))
  File "C:\Users\yyy\Anaconda3\lib\site-packages\win32com\client\__init__.py", line 113, in DispatchEx
    dispatch = pythoncom.CoCreateInstanceEx(clsid, None, clsctx, serverInfo, (pythoncom.IID_IDispatch,))[0]
pywintypes.com_error: (-2147024156, 'The requested operation requires elevation.', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chrts_linking.py", line 68, in <module>
    app.screen_updating = True
NameError: name 'app' is not defined
Press any key to continue . . .
```

+ This is by far the best python package for excel i've tried.

**Comment by fzumstein** [comment]
You will need to run Excel and Python with the same user, so run Python also as administrator and you should be fine.
