### ISSUE TITLE
rpy2: Unexpected Python Error

### ISSUE THREAD

**Issue by bgaspers** [xlwings/xlwings#1198]
Using: Windows 10, xlwings 0.16.1 on Office365 with Python 3.7 (Anaconda)

I'm trying to run a stepwise regression (don't judge) running some R commands as described [here ](http://blog.yhat.com/tutorials/rpy2-combing-the-power-of-r-and-python.html). It's basically using rpy2 to import R objects directly into Python vs. referencing a separate R file as set forth in the xlwings documentation. I'd prefer to have everything in one Python file, as seems doable from the yhat blog entry.

I'm copying an Excel range into a variant array (the independent and dependent variables for the regression, including column headers denoting variable names), passing that into the UDF, and converting that into a Pandas dataframe. My understanding is that pandas2ri will handle the conversion to an R dataframe when the argument is passed into the R object.

When I run the UDF, I get the following error dialog in VBA:

```
Run-time error '-2147467259 (80004005)'
Unexpected Python Error: ValueError: Buffer for this type not yet supported
```

Is this kind of thing just plain not supported in xlwings or is some other issue preventing this from running?

For reference, what I'm trying to do here is return the regression summary to get the regression variables and model statistics. I've set this up as a UDF (but not looking to run this off a cell formula entry), but I may look into using RunPython to write this information out to a sheet in Excel.

Code

VBA
```
vaDataFrame = Range("MarketVariables").value
vaTemp = Stepwise(MarketVariables)`
```

```python
import rpy2.robjects as robjects
import pandas as pd
from rpy2.robjects import pandas2ri
pandas2ri.activate()

from rpy2.robjects.packages import importr
stats = importr('stats')
base = importr('base')

import xlwings as xw
@xw.func
@xw.arg('MarketVariables', pd.DataFrame, index=False, header=True)
@xw.ret(index=False)

def Stepwise(MarketVariables):
    full = stats.lm('Delta~.',data=MarketVariables)
    null = stats.lm('Delta~1',data=MarketVariables)
    StepModel = stats.step(null,scope=base.list(upper=stats.formula(full), lower=stats.formula(null)),direction='both', k=2, trace=1)
    return base.summary(StepModel)
```

**Comment by fzumstein** [comment]
I have no experience really with integrating R and Python, but a quick Google search seems to indicate it's a rpy2 issue: https://github.com/conda-forge/rpy2-feedstock/issues/28

**Comment by bgaspers** [comment]
Thanks, that is probably the issue. I'm on numpy 1.17.4 and rpy2 2.9.4. I'll see if rpy2 v3.x resolves this.

**Comment by bgaspers** [comment]
Great, rpy2 v3.x not supported on Windows.
