### ISSUE TITLE
How do I get what Formula is in an excel sheet? For example, if Cell B1 of Sheet1 has =SUM(A1:A3), how can I get python to print that? Any amount of googling doesn't get me ahead.

### ISSUE THREAD

**Issue by lyt108** [xlwings/xlwings#1199]
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
simply search the docs and you should find this: https://docs.xlwings.org/en/stable/api.html#xlwings.Range.formula

**Comment by fzumstein** [comment]
https://docs.xlwings.org/en/latest/api/range.html#xlwings.Range.formula
