### ISSUE TITLE
how to use data analysis with xlwings?

### ISSUE THREAD

**Issue by wangxiuwen** [xlwings/xlwings#1201]
#### OS

Windows 10

I'm looking for a way to analyze data with xlwings, would you tell me how to?

![WechatIMG69](https://user-images.githubusercontent.com/17867124/70406900-3aebfd80-1a7d-11ea-9d4e-c118b679b285.png)

**Comment by wangxiuwen** [comment]
![WechatIMG69 1](https://user-images.githubusercontent.com/17867124/70406930-535c1800-1a7d-11ea-9abe-97eb42a2e76e.png)

**Comment by fzumstein** [comment]
What about using Python to do that part? e.g. https://pythonfordatascience.org/anova-python/

**Comment by wangxiuwen** [comment]
@fzumstein thx. I will try
