### ISSUE TITLE
XLwings doesn't work in sharepoint

### ISSUE THREAD

**Issue by mfreak95** [xlwings/xlwings#1203]
#### OS (e.g. Windows 10 or macOS Sierra)

####Office 365, Python 3.7, XLWings16.10

#### I have a directory in which all the files that are used for a certain worksheet that uses xlwings are stored. The python environment that it is using, the python code, and the excelfile. When i open it from my personal OneDrive, or a local directory it works just fine. Calls the python code and runs it. But now i uploaded this all to a sharepoint directory. So everything that is in the directory on the personal directories. But when i try to run the macro that call the python code using runpython right now, it gives the following error: no module named hello2, which is the name of the file the python code is stored in. Anyone has an idea how to fix this?
```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
Were you ever able to solve your issue?

**Comment by fzumstein** [comment]
Ok I think the issue you're facing is that it searches for the python module in the same folder as your Excel file. With onedrive and sharepoint, this is somewhere random, but not where you have the local version of the file. To solve this, either add the location with your python code to `PYTHONPATH`. The other alternative is to use xlwings PRO, where you can store the code directly in the Excel file which will prevent these kind of issues. I am closing this, please reopen if you continue to get this error even after setting the `PYTHONPATH`.
