### ISSUE TITLE
xlwings error reading Excel named range into Pandas dataframe

### ISSUE THREAD

**Issue by bgaspers** [xlwings/xlwings#1205]
Using: MacOS 10.14.6 (Mojave), xlwings 0.16.1 on Office365 with Python 3.7 (Anaconda)

This is a continuation of a prior issue [(GH1198)](https://github.com/xlwings/xlwings/issues/1198). This time, I've set my analysis up as a RunPython routine on the Mac (because no ryp2 v3.x in Windows) where I'm trying to read a named Excel range into a Pandas dataframe. The Excel range consists of column headers and then rows of data under those. This seems like a pretty basic function: we need to get data out of Excel to manipulate in Python. This looks like it is failing somewhere in xlwings.

```python
Traceback (most recent call last):
--
File "/Users/bgaspers/anaconda3/lib/python3.7/site-packages/aeosa/appscript/reference.py", line 460, in __call__
return self.AS_appdata.target().event(self._code, params, atts, codecs=self.AS_appdata).send(timeout, sendflags)
File "/Users/bgaspers/anaconda3/lib/python3.7/site-packages/aeosa/aem/aemsend.py", line 92, in send
raise EventError(errornum, errormsg, eventresult)
aem.aemsend.EventError: Command failed: The object you are trying to access does not exist (-1728)
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/bgaspers/BIITestBP/BIITestRP.py", line 33, in Stepwise
MktVar = xw.sheets[0].range('MarketVariables').options(pd.DataFrame, index=False, header=True).value
File "/Users/bgaspers/anaconda3/lib/python3.7/site-packages/xlwings/main.py", line 1557, in value
return conversion.read(self, None, self._options)
```

RunPython file
```python
import xlwings as xw
import pandas as pd
import rpy2.robjects as robj
from rpy2.robjects import pandas2ri
pandas2ri.activate()

from rpy2.robjects.packages import importr
stats = importr('stats')
base = importr('base')

wb = xw.Book.caller()

def Stepwise():
	MktVar = xw.sheets[0].range('MarketVariables').options(pd.DataFrame, index=False, header=True).value
	full = stats.lm('Delta~.',data=MktVar)
	null = stats.lm('Delta~1',data=MktVar)
	StepModel = stats.step(null,scope=base.list(upper=stats.formula(full), lower=stats.formula(null)),direction='both', k=2, trace=1)
	StepResult = base.summary(StepModel)
	StepAIC = stats.AIC(StepModel)
	StepBIC = stats.BIC(StepModel)
	wb.sheets['Scratch'].range('A1').value = StepResult
	wb.sheets['Scratch'].range('M1').value = StepAIC
	wb.sheets['Scratch'].range('M2').value = StepBIC
```

**Comment by fzumstein** [comment]
You should use `wb.sheets[0]...` not `xw.sheets[0]...` as the latter one will go against the active workbook. If that is not the issue, try to fire up a interactive Python prompt and see what you get for `wb.sheets[0].range('MarketVariables')` - you might have a typo or it's not a named range on sheet scope etc.

**Comment by bgaspers** [comment]
Thanks, Felix. I'm trying to reference a workbook-level name. Does xlwings let you do so? That isn't clear from the xlwings documentation and if I try:

```
MktVar = wb.Range('MarketVariables').options(pd.DataFrame, index=False, header=True).value
```

I get "AttributeError: 'Book' object has no attribute 'Range'"

Note: I can successfully run the script if I pass the fully qualified sheet reference (e.g., 'A1:AK73') through RunPython.

**Comment by fzumstein** [comment]
a Range as an attribute of a book is lower case: `wb.range`. To reference a workbook level name you need to use the names collection, see: http://docs.xlwings.org/en/stable/api.html#xlwings.Book.names which will eventually return a http://docs.xlwings.org/en/stable/api.html#xlwings.Name (and yes, the docs need some improvement there).

**Comment by bgaspers** [comment]
Thanks for the pointer, this is what works:

```
MktVar = wb.names('MarketVariables').refers_to_range.options(pd.DataFrame, index=False, header=True).value
```
