### ISSUE TITLE
RunFrozenPython Issue with argparse

### ISSUE THREAD

**Issue by DJHostetler** [xlwings/xlwings#1220]
#### Currently running into issues with trying to use the RunFrozenPython command with subcommands to run different functions within a single script.

I have tried several different approaches with no success. It appears that the optional argument is not getting passed back to argparse. 

```python
usage: test_args2.exe [-h] {foo,bar} ... 
test_args2.exe: error: unrecognized arguments: --wb=C:\_Work\Software\sumit\GC_WatershedManagementTool_v2.xlsm --from_xl=1 --app=C:\Program Files (x86)\Microsoft Office\Root\Office16\Microsoft Excel --hwnd=789422 

```

#### If I convert the following code to an executable (called test_args.exe) and then try to run the following code...

```python
import argparse
import xlwings as xw

def foo(args):
    wb = xw.Book.caller()
    ws1 = wb.sheets['Overview']
    ws1.range('G3').value = 'Hello World!'
    wb.save()

def bar(args):
    wb = xw.Book.caller()
    ws1 = wb.sheets['Overview']
    ws1.range('I3').value = 'Goodbye World!'
    wb.save()


parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers()
parser_foo = subparsers.add_parser('foo')
parser_foo.set_defaults(func=foo)
parser_bar = subparsers.add_parser('bar')
parser_bar.set_defaults(func=bar)

args = parser.parse_args()

if args.func:
    args.func(args)

```
And I use the following VBA tied to a button click...

```
Sub Button2_Click()

    Dim exe As String
    Dim arg As String

    exe = "C:\_Work\Software\sumit\test_args.exe"
    arg = "foo"

    RunFrozenPython exe, arg

End Sub
```
That is where I get the error posted at the top. I have a working example of RunFrozenPython with no additional arguments. I was able to test the script listed above with the mock caller and it worked without an issue.

**Comment by fzumstein** [comment]
Yes, seems like currently RunFrozenPython is incompatible with argparse. Two workarounds for now:

* Usually, you don't need argparse when freezing code: The frozen exe will expect your function arguments as positional command line argument. So in your case you could write something like:

```
import xlwings as xw

def foo(args):
    wb = xw.Book.caller()
    ws1 = wb.sheets['Overview']
    ws1.range('G3').value = 'Hello World!'
    wb.save()

def bar(args):
    wb = xw.Book.caller()
    ws1 = wb.sheets['Overview']
    ws1.range('I3').value = 'Goodbye World!'
    wb.save()

def main(arg):
    if arg == 'bar':
        bar()
    else:
        ...

if __name__ == '__main__':
    main(arg)
```

* As a workaround, your argparse code should work when you ignore unused args:

instead of 
```
args = parser.parse_args()
```
do:

```
args, unknown = parser.parse_known_args()
```

**Comment by DJHostetler** [comment]
Felix, thank you for taking the time to look at this. That was very helpful! The slightly amended code below worked for me ...

```python
import xlwings as xw
import sys

def foo():
    wb = xw.Book.caller()
    ws1 = wb.sheets['Overview']
    ws1.range('G3').value = 'Hello World!'
    wb.save()

def bar():
    wb = xw.Book.caller()
    ws1 = wb.sheets['Overview']
    ws1.range('I3').value = 'Goodbye World!'
    wb.save()


def main(arg):
    if arg == 'bar':
        bar()
    else:
        foo()
        
if __name__ == '__main__':
    arg = sys.argv[1]
    main(arg)
```
