### ISSUE TITLE
Errors running basic code

### ISSUE THREAD

**Issue by pj1989** [xlwings/xlwings#1229]
#### OS
Windows 10 version 1803

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.16.6
Office 365 version 1902
Python 3.7.1

#### Issue

I'm moving the first steps with xlwings and I'm trying to run a simple `test.py` script as
```
import xlwings as xw
wb = xw.Book('test.xlsx')
```

I'm facing the following issues (which I don't know if they are related):

1.  If I run the script with no excel window open, the following error appears:
![image](https://user-images.githubusercontent.com/7668531/71814768-5dba0380-3075-11ea-9f45-93898c368f97.png)
And the following traceback shows up in the python console
```
Traceback (most recent call last):

  File "C:\Users\xyz\Desktop\Auto-Clean\xlwings_test\test.py", line 10, in <module>
    wb = xw.Book('test.xlsx')

  File "C:\Users\xyz\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\main.py", line 519, in __init__
    app = App(add_book=False)

  File "C:\Users\xyz\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\main.py", line 212, in __init__
    self.impl = xlplatform.App(spec=spec, add_book=add_book)

  File "C:\Users\xyz\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 296, in __init__
    self._xl = COMRetryObjectWrapper(DispatchEx('Excel.Application'))

  File "C:\Users\xyz\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\client\__init__.py", line 113, in DispatchEx
    dispatch = pythoncom.CoCreateInstanceEx(clsid, None, clsctx, serverInfo, (pythoncom.IID_IDispatch,))[0]

com_error: (-2146959355, 'Server execution failed', None, None)
```

2. If I wrap the code above in a function declaration with `def main():` and I try to run the code from the xlwings excel addin in the `test.xlsx` file, I get the following error:
```
Run-time error '53':

File not found
```
I set `Conda Base` as `'C:\Users\xyz\AppData\Local\Continuum\anaconda3'` and `Conda Env` as `base`

#### Notes

- Running the code from python with an excel window open works (any window, not just `test.xlsx`).
 
- In `C:\Users\xyz\AppData\Local\Continuum\anaconda3` both `xlwings32-0.16.6.dll` and `xlwings64-0.16.6.dll` are present.

- If I use the "run main" command in the addin tab setting the interpreter to `"C:\Users\xyz\AppData\Local\Continuum\anaconda3\python.exe"` I receive an error `Could not find interpreter`

**Comment by fzumstein** [comment]
looks like a duplicate: https://github.com/xlwings/xlwings/issues/1170

**Comment by fzumstein** [comment]
I consider this solved via the referenced issue
