### ISSUE TITLE
Is it possible to copy a particular sheet? If possible, how will I do it?

### ISSUE THREAD

**Issue by juniusfree** [xlwings/xlwings#123]

**Comment by bersanri** [comment]
Hi!
I'm just writing you to know if this issue has been solved.

**Comment by fzumstein** [comment]
Nope, the status is on the top left - still open...

**Comment by iaindinw** [comment]
Is there a workaround on the new API? sheets(1).api.copy() doesn't return an error, but sheets(1).api.copy(Before=sheets(1).api) returns an error. As does specifying sheet directly.

**Comment by Morb** [comment]
Using v0.10.5 I had to replace `xl_sheet` with `api`: `Sheet(1).api.Copy(Before=Sheet(1).api)`

**Comment by Elijas** [comment]
If you want to copy a sheet to the end - the workaround for the broken After keyword is broken in pywin32 is to create a temporary sheet at the end using the native xlwings _sheet.add_, then copy a sheet Before the newly created sheet and finally delete the newly created sheet.

**Comment by fzumstein** [comment]
In the more recent versions of xlwings, here's an example of how to work around it:

```
import xlwings as xw
wb = xw.books.active
sht = wb.sheets['Sheet1']
sht.api.Copy(Before=sht.api)
```

**Comment by bobjoylove** [comment]
```
import xlwings as xw
wb = xw.books.active
sht = wb.sheets['Sheet1']
sht.api.Copy(Before=sht.api)
```

>     raise AttributeError("Unknown property, element or command: {!r}".format(name)) from e
> AttributeError: Unknown property, element or command: 'Copy'

Options alphabetically at sht.api.<tab> are beginswith(operand), contains(operand) and doesnotbeginwith(operand)
Notes: fresh install at 0.11

**Comment by manobeeslaar** [comment]
Hi there,

Is there a work around for MAC?  To copy a sheet from one workbook to another workbook?

Thank you,

**Comment by fzumstein** [comment]
Here you go:

```
import xlwings as xw

wb = xw.books.active
sht_api = wb.sheets[0].api
sht_api.copy_worksheet(before_=sht_api)
```

**Comment by manobeeslaar** [comment]
Thank you!

**Comment by mullimanko** [comment]
@fzumstein, I can't retrace what you wrote in your first post that `After` keyword is broken in pywin32. See: https://stackoverflow.com/questions/64820928/move-worksheet-within-a-workbook-to-the-end/64837195#64837195

**Comment by fzumstein** [comment]
@mullimanko gotcha, thanks for your note!

**Comment by ffisc** [comment]
> Here you go:
> 
> ```
> import xlwings as xw
> 
> wb = xw.books.active
> sht_api = wb.sheets[0].api
> sht_api.copy_worksheet(before_=sht_api)
> ```

Hi, has the API changes by any chance? I'm trying this and getting

```
File "C:\Users\xxx\Anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 141, in __getattr__
    self._oleobj_.GetIDsOfNames(0, item)
pywintypes.com_error: (-2147352570, 'Unknown name.', None, None)
```

**Comment by fzumstein** [comment]
@ffisc that's the macOS version, if you are on Windows, do: https://github.com/xlwings/xlwings/issues/123#issuecomment-408763631
