### ISSUE TITLE
How to resolve the AttributeError

### ISSUE THREAD

**Issue by JingmeiYang6** [xlwings/xlwings#1237]
Hi,
I just started to learn to programme Excel with Python, and got the problem with AttributeError. I've checked the version of xlwings is 0.17.0 which is the latest version. Change from book to workbook doesn't work either. 
Thank you very much in advance.

import xlwings as xw

wb =xw.Book()

C:\PycharmProjects\venv\Scripts\python.exe C:/PycharmProjects/test.py
Traceback (most recent call last):
  File "C:/PycharmProjects/test.py", line 3, in <module>
    wb =xw.Book()
AttributeError: module 'xlwings' has no attribute 'Book'

**Comment by fzumstein** [comment]
this almost looks as if you have somewhere a python file or folder called `xlwings` or `xlwings.py` where it imports it from instead of from the installed package. rename this to something like `xlwings_testing` and you should be good. If it's not that, maybe it did not install correctly.

**Comment by JingmeiYang6** [comment]
Hi Felix.
Thank you for taking the time out to answer my question. Unfortunately, the problem hasn't been solved 
![image](https://user-images.githubusercontent.com/59906197/72481738-560e1200-3860-11ea-8005-15b2c2002b78.png)

I deleted the folder called xlwings. But the error changed to ModuleNotFoundError: No module named 'xlwings'.
Then I uninstalled and installed all of them again. As you can see below, it shows the xlwings has been successfully installed in the command prompt, but in Pycharm it shows a properly version cann't be found.
![image](https://user-images.githubusercontent.com/59906197/72481651-147d6700-3860-11ea-82ae-df80c6354467.png)

![image](https://user-images.githubusercontent.com/59906197/72481441-77223300-385f-11ea-8f5f-96a8be5be527.png)

**Comment by fzumstein** [comment]
You have an virtual environment activated in pycharm. Maybe try to install pywin32 there manually.

**Comment by JingmeiYang6** [comment]
Thank you, Flix.
It doesn't work as shown below.
C:\PycharmProjects>pip install pywin32
Requirement already satisfied: pywin32 in c:\python\lib\site-packages (227)

![image](https://user-images.githubusercontent.com/59906197/72484456-27e10000-3869-11ea-8601-c87667f503a2.png)

**Comment by JingmeiYang6** [comment]
Hi,
I still struggle with installing xlwings. Any idea what is causing this?
![image](https://user-images.githubusercontent.com/59906197/72573702-6fc85b80-392b-11ea-9f7c-5ed5da586e4f.png)
![image](https://user-images.githubusercontent.com/59906197/72573827-cdf53e80-392b-11ea-9e43-27cbbd61201f.png)

Thank you very much!
![image](https://user-images.githubusercontent.com/59906197/72573894-085edb80-392c-11ea-80b8-74ab8fe99ca0.png)

**Comment by fzumstein** [comment]
In cases such as these, installing Anaconda or WinPython would probably be a good solution to have a clean environment.
