### ISSUE TITLE
Cannot run xlwings properly 

### ISSUE THREAD

**Issue by ekey8** [xlwings/xlwings#1239]
#### Describe your issue (incl. Traceback!)
Hi Git Hub, Is it possible to install xlwings manually inside pycharm?  I tried using pip but the installation does not go through it is looking for py# >=224 (or something.  I installed xlwings using cmd but when I try to run wb = xw.Book(), it does not open a workbook. 

```python
# Your traceback here
# none as I was working on another computer, the problem is as described above.
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
# see above
```

**Comment by fzumstein** [comment]
You might have an outdated version of pip in your pycharm setup. Make sure that pycharm is indeed using the python version you think it is. Installing pywin32 manually should be easy, refer to: https://pypi.org/project/pywin32/

**Comment by ekey8** [comment]
Thank you.  yes, that pywin32 >=224 it was looking for.  'Will try it tomorrow and will come back if more trouble arises.

**Comment by ekey8** [comment]
G'day, we tried to install as advised inside pycharm, and still does not work please see attachment for your reference.  Incidentally, I also included the comparison of the list of installed site-packages in python (through pycharm) from the newly installed and working computer.  I hope this will clear a few things.  Thank you in advance.  

[Pycharm of xlwings not working.pdf](https://github.com/xlwings/xlwings/files/4074871/Pycharm.of.xlwings.not.working.pdf)
[Pycharm of xlwings working.pdf](https://github.com/xlwings/xlwings/files/4074872/Pycharm.of.xlwings.working.pdf)

[pywin32 Install  Error.txt](https://github.com/xlwings/xlwings/files/4074797/pywin32.Install.Error.txt)

**Comment by ekey8** [comment]
Hi there, I am hoping if you can provide a resolution to our problem.  Thanks.

**Comment by fzumstein** [comment]
You cannot install an exe file via pip. You can try to download the respective wheel file from here: https://pypi.org/project/pywin32/#files and then try again. Also, for faster & direct support, consider [xlwings PRO](https://www.xlwings.org/pricing).

**Comment by ekey8** [comment]
Thank you for your offer.  At this moment, it is an exploratory project on the use of python on which buying the professional version needs to be justified.

**Comment by fzumstein** [comment]
If anyhow possible, try to use the Anaconda distribution as it comes with xlwings preinstalled. This will save you the sort of hassle you're currently going through.

**Comment by ekey8** [comment]
Hi, thanks for kind consideration and patience.  I think I may have found a way to solve the problem, please see below.

Procedure for Installing xlwings in Pycharm with missing pywin32 module 

1.  Install Python 3.8.0 (stable version) then Pycharm 2019.2.4.

2.  Test Python in Pycharm

3.  Update pip to the new/current version

4.  Disregard pip installation error.

5.  Install pywin32

6.  Install xlwings

7.  Test xlwings in Pycharm 

8.  Work on xlwings for a while then upgrade items using Pycharm.

9.  Install xlwings the above in Python at the command prompt.  Note that it is only installing xlwings that has a problem it 

10. Since the Pycharm above is an older version that is compatible with Python 3.8.0, you can upgrade Pycharm when flagged but be sure you follow the previous installation procedure and manually input previous directories so that directory references will no be lost.  The problem with Pycharm upgrades it automatically installs itself using its default directories and installation parameters.

'Hope this helps others with a similar problem.


Thanks again,

ekey8

**Comment by fzumstein** [comment]
Hi @ekey8 thanks for that detailed list. Were you using PyCharm EAP before?

**Comment by ekey8** [comment]
Hi @fzumstein, I am afraid not, but I also have a problem with installing xlwings in Pycharm on my computer a few weeks ago.  That also took some time to resolve.
