### ISSUE TITLE
System Error &H80004005 during background refresh

### ISSUE THREAD

**Issue by rahullak** [xlwings/xlwings#1244]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.17.0
Excel 2016 Version 1912 (Build 12325.20298)
Python 3.6.1

#### Describe your issue (incl. Traceback!)
An error occurs during background refresh. By background refresh, I mean that VBA schedules the execution of python UDF at a fixed time interval (refresh_rate). It works beautifully if we are working on other applications during the background refresh or working on the same excel workbook. However, if we work on a different Excel workbook, it results in this error.

![image](https://user-images.githubusercontent.com/41263061/73414142-e73ab980-4333-11ea-9883-f454b91d4469.png)

Kindly test using attached zip file which contains macro workbook and python script.
[trial.zip](https://github.com/xlwings/xlwings/files/4131842/trial.zip)

**Comment by fzumstein** [comment]
Closing this as slightly out of scope. I believe the proper way of doing this would be to use an RTD formula.
