### ISSUE TITLE
Hide UDF server window

### ISSUE THREAD

**Issue by jaymegordo** [xlwings/xlwings#1247]
Windows 10
0.17.1, Office 365, Python 3.8

#### Describe your issue (incl. Traceback!)
I'm building an app to be distributed to multiple users, and would like to use the UDF server to have faster response for all functions, keep database connection open, store variables etc.

Currently the server window launches, remains open and otherwise works fine. Ideally I'd like the server to run completely in the background, and have the users' only interaction to be with Excel.

In the docs I see that 
> If you use Conda Base and Conda Env with UDFs, you currently can’t hide the command prompt 
that pops up.

Which seems to imply that as long as I'm just using regular python I _can_ hide the window? Does that just mean minimized or actually running in the background?

I can't find anything in the docs or code anywhere to launch that window hidden like with the non-UDF `RunPython`.

Does anyone know of a way to launch the UDF window completely in the background, or to hide it after the fact?

**Comment by fzumstein** [comment]
If you don't use the conda settings, the windows should be hidden by default. If you set a path to an interpreter, make sure to set it to `...\pythonw.exe` instead of `...\python.exe`.

**Comment by jaymegordo** [comment]
Amazing thanks!! That was exactly the issue, I didn't understand the difference between pythonw.exe and python.exe. If anyone else is wondering:
[https://stackoverflow.com/questions/9705982/pythonw-exe-or-python-exe](https://stackoverflow.com/questions/9705982/pythonw-exe-or-python-exe)
