### ISSUE TITLE
Xlwings crashes when trying to add hyperlink longer than 175 characters

### ISSUE THREAD

**Issue by jclark4510** [xlwings/xlwings#1249]
OS: Windows 10

 xlwings 0.17.0, Office 365, Python 3.8

When adding long hyperlinks using .add_hyperlink() python locks up and excel needs to be closed from task manager. Adding URLs directly into excel allows for much longer links

example

sht.range((row,col)).add_hyperlink('http://ffm-mks3.auto.contiwan.com:7001/si/viewrevision?projectName=d:/mks/archives/projectdocs/Customer/Loooongprojectname/10_Project_Management/10_Project_Planning/10_Overall_Project/project.pj&selection=filenameonclientserver',"Test Link")

**Comment by Nate42** [comment]
I ran into the same issue. Was able to work around with:
ws.api.Hyperlinks.Add(Anchor=ws.range(row,col).api, Address=link_addr, SubAddress="", ScreenTip="", TextToDisplay=link_text)

**Comment by fzumstein** [comment]
closing in favor of #1867
