### ISSUE TITLE
xlwings 0.17.1 identified as trojan by Windows 10 Defender

### ISSUE THREAD

**Issue by kolyarice** [xlwings/xlwings#1250]
#### OS (e.g. Windows 10 or macOS Sierra)
Microsoft Windows [Version 10.0.19041.21]

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Python 3.7.4 (Anaconda distribution)
conda 4.8.1
xlwings                   0.17.0                   py37_0

#### Describe your issue (incl. Traceback!)
Attempting to upgrade  the xlwings version using pip (pip install xlwings -U) triggers an alert from Windows Defender that a threat was detected and removed.

Event log entry:
Microsoft Defender Antivirus has detected malware or other potentially unwanted software.
 For more information please see the following:
https://go.microsoft.com/fwlink/?linkid=37020&name=Trojan:Win32/Detplock&threatid=2147680291&enterprise=0
 	Name: Trojan:Win32/Detplock
 	ID: 2147680291
 	Severity: Severe
 	Category: Trojan
 	Path: file:_C:\Users\kolya\AppData\Local\Temp\pip-unpack-z9vaz69j\xlwings-0.17.1.tar.gz
 	Detection Origin: Local machine
 	Detection Type: FastPath
 	Detection Source: Real-Time Protection
 	User: CORUSCANT\kolya
 	Process Name: C:\Anaconda\python.exe
 	Security intelligence Version: AV: 1.309.304.0, AS: 1.309.304.0, NIS: 1.309.304.0
 	Engine Version: AM: 1.1.16700.3, NIS: 1.1.16700.3

**Comment by fzumstein** [comment]
Thanks for the report! It's funny as it only reacts when you download the tar.gz file. As soon as you unzip it and scan the unzipped archive, it's all ok. For now I'd suggest to either stay on 0.17.0 for now (the update was minimal) or try the via conda forge which seems also fine: https://anaconda.org/conda-forge/xlwings

**Comment by kolyarice** [comment]
Thanks. Confirming that I was able to upgrade to 0.17.1 successfully using conda. I probably shouldn't be using pip with conda anyway :)

**Comment by fzumstein** [comment]
I had submitted this as false positive and this is now fixed:

```
We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
```
