### ISSUE TITLE
sheets.calculate()

### ISSUE THREAD

**Issue by SaaSaaG** [xlwings/xlwings#1254]
Hi was wondering if there is a sheets('XYZ').app.calculate() function? which specifically recalculates only the specific sheet and not the entire workbook.

e.g.
import xlwings as xw
wb=xw.Book.caller()

ws=wb.sheets("XYZ")

**ws.app.calculate() #to recalculate sheet XYZ only**
#instead of wb.app.calculate which recalculates all open workbooks

**Comment by fzumstein** [comment]
It's currently not implemented, but makes total sense. As a workaround for now, you should be able to do: `ws.api.Calculate()` on Windows, see also: https://docs.microsoft.com/en-us/office/vba/api/excel.worksheet.calculate(method) and https://docs.xlwings.org/en/stable/missing_features.html

**Comment by SaaSaaG** [comment]
Hi, Thanks for this ! 
Just a quick question that is related to this. Is there anything similar for StatusBar?

e.g. wb.api.StatusBar="XYZ"

I tried the above and it doesn't seem to be working

**Comment by fzumstein** [comment]
StatusBar is a property of Application, so you'd have to do something like:

```
>>> wb.app.api.StatusBar = 'abc'
>>> wb.app.api.StatusBar = None
```

**Comment by SaaSaaG** [comment]
Thanks for fast response. Solves my problem !
