### ISSUE TITLE
Cannot add series to chart with different number of samples

### ISSUE THREAD

**Issue by mar2194** [xlwings/xlwings#1259]
I cannot figure out a way to add series to a line chart such that each series has a different number of samples, i.e. x1, y1 and x2, y2 where x1 =! x2

I tried using the api but keep getting the error that the pywin32 COMobject on Windows does not have an attribute "NewSeries". Clearly I'm confused and can't figure out how to use the NewSeries method associated with the "SeriesCollection"

**Comment by fzumstein** [comment]
Can you please ad the sample code that doesnt work?

**Comment by mar2194** [comment]
I apologize - the chart type I was using was probably incorrect (should be using scatter instead of line) but the issue persists:
The attached zip file contains the python code (copy pasted here) and Excel file
`# REQUIRED IMPORTS
from __future__ import division
import sys
import numpy as np
import xlwings as xw

def main():
    # On button press in Excel, instantiate sheet object
    sht = xw.Book.caller().sheets['Sheet1']
    # Set source data for pre-existing Chart Object (Chart 3)
    sht.charts['Chart 3'].set_source_data(sht.range('A1:D17'))
    # Attempt to define two series within that range that have different number of x,y samples
    # First series
    sht.charts['Chart 3'].api[1].SeriesCollection(1).XValues = sht.range('A1:A12')
    sht.charts['Chart 3'].api[1].SeriesCollection(1).XValues = sht.range('B1:B12')
    # Second series
    sht.charts['Chart 3'].api[1].SeriesCollection(2).XValues = sht.range('C1:C17')
    sht.charts['Chart 3'].api[1].SeriesCollection(2).XValues = sht.range('D1:D17')`
[XlwingsGitHub.zip](https://github.com/xlwings/xlwings/files/4226871/XlwingsGitHub.zip)

**Comment by mar2194** [comment]
Still stuck on this... at first I thought perhaps you cannot access the VB methods when using .api[1] but I was able to get this to work:

`wb = xw.books.open(r'C:\Example1.xlsm')
sht = wb.sheets['Sheet1']
cht = sht.charts['Chart 3']
# Using a VB Chart object method:
cht.api[1].SetElement(2)
# Manipulating a VB ChartTitle object property:
cht.api[1].ChartTitle.Text = 'Testing'
# Manipulating a VB Series object property:
cht.api[1].SeriesCollection(1).HasDataLabels = False
# For some reason this fails:
cht.api[1].SeriesCollection.Add(sht.range('A1:B12')
`
On Traceback I get:
`AttributeError: 'COMRetryMethodWrapper' object has no attribute 'Add'`

So it seems that I cannot access the Add method of a SeriesCollection object... and I suspect it is because cht.api[1].SeriesCollection doesn't return a SeriesCollection object but rather a _Series_ object.

Any help in accomplishing this seemingly simple task would be greatly appreciated!

**Comment by mar2194** [comment]
Extra Info:
OS
Windows 10 Pro

Versions of xlwings, Excel and Python
'0.16.1', Office 365, Python 3.7.3 (Anaconda)

**Comment by mar2194** [comment]
> Can you please ad the sample code that doesnt work?

I ended up interpolating the sample points (x) of the different functions (y) I was trying to plot to a common domain (X). In the future, it would be nice to be able to plot functions which sample different domains on the same plot.

**Comment by fzumstein** [comment]
yes, the charts api is currently completely underdeveloped...

**Comment by fantast4111** [comment]
I tried thousands of time
The correct command should be:
#Adding new series
cht.api[1].SeriesCollection().NewSeries()  
and for editing series source:
sht.charts['Chart 3'].api[1].SeriesCollection(1).XValues = sht.range('A1:A12')**.value**
(only if  ".value" is added, the value in the cell will be returned.

**Comment by oceanus741** [comment]
I find ".api" can add the series to a line chart.
```
sht.charts[0].api[1].SeriesCollection(1).Name= 'Name'
sht.charts[0].api[1].SeriesCollection(1).XValues = sht.range('A1:A12').api
sht.charts[0].api[1].SeriesCollection(1).Values = sht.range('B1:B12').api
```
