### ISSUE TITLE
Error message using UDFs: "Could not activate Python COM server, hr = -2147221164"

### ISSUE THREAD

**Issue by RobertvanLoon** [xlwings/xlwings#1260]
#### OS Windows 10, xlwings 0.15.10, Excel Office 365, Python 3.7.

I recently installed xlwings on my PC and it works great, really useful! I also want xlwings on my laptop so I've followed the same installation, but UDFs are not working. The fibonacci, mpl and simulation examples from the xlwings homepage work fine on my laptop. It's just UDFs that are causing issues.

When I use the udf example sheet, after clicking "import functions" a command prompt opens, and then everything freezes (can't do anything in Excel) until the error message "**Could not activate Python COM server, hr = -2147221164**" appears. When I close the command prompt early the following error message appears in the spreadsheet: "**Python process exited before it was possible to create the interface object**".

Everything on my laptop is the same as my PC, the OS, version of Python (setup via Anaconda), Excel etc.

I've spend hours trying different things but I just can't get UDFs to work.

Can anyone please help?

Thanks a lot!

**Comment by fzumstein** [comment]
Is your installation of Excel from the Microsoft Store? see https://github.com/xlwings/xlwings/issues/1166

**Comment by RobertvanLoon** [comment]
Well I thought it wasn't but it turns out my Office was from the Microsoft Store after all. I just reinstalled Office and xlwings works fine now. I am a very happy man! Thanks for your quick response.

**Comment by fzumstein** [comment]
Awesome, glad to hear! Will need to add this to the Troubleshooting docs.
