### ISSUE TITLE
OS error: -1743

### ISSUE THREAD

**Issue by balqx** [xlwings/xlwings#1262]
#### Describe your issue (incl. Traceback!)

I can't open any workbooks using xlwings on Spyder.

```
Traceback (most recent call last):

  File "/Users/*/opt/anaconda3/lib/python3.7/site-packages/aeosa/appscript/reference.py", line 460, in __call__
    return self.AS_appdata.target().event(self._code, params, atts, codecs=self.AS_appdata).send(timeout, sendflags)

  File "/Users/*/opt/anaconda3/lib/python3.7/site-packages/aeosa/aem/aemsend.py", line 92, in send
    raise EventError(errornum, errormsg, eventresult)

EventError: Command failed: OS error (-1743)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "<ipython-input-2-bcb86508eef1>", line 1, in <module>
    xw.Book()

  File "/Users/*/opt/anaconda3/lib/python3.7/site-packages/xlwings/main.py", line 529, in __init__
    impl = apps.active.books.add().impl

  File "/Users/*/opt/anaconda3/lib/python3.7/site-packages/xlwings/main.py", line 2854, in add
    return Book(impl=self.impl.add())

  File "/Users/*/opt/anaconda3/lib/python3.7/site-packages/xlwings/_xlmac.py", line 187, in add
    self.app.activate()

  File "/Users/*/opt/anaconda3/lib/python3.7/site-packages/xlwings/_xlmac.py", line 100, in activate
    appscript.app('System Events').processes[its.unix_id == self.pid].frontmost.set(True)

  File "/Users/*/opt/anaconda3/lib/python3.7/site-packages/aeosa/appscript/reference.py", line 496, in __call__
    raise CommandError(self, (args, kargs), e, self.AS_appdata) from e

CommandError: Command failed:
		OSERROR: -1743
		MESSAGE: OS error
		COMMAND: app('/System/Library/CoreServices/System Events.app').processes[its.unix_id == 20656].frontmost.set(True)
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```
import xlwings as xw
xw.Book()
```

**Comment by fzumstein** [comment]
This looks like as if spyder isn't asking for the permissions correctly on Catalina, see: https://github.com/xlwings/xlwings/issues/1146

**Comment by eshao16** [comment]
I downgraded my spyder to a previous version (3.3.6), and tried executing the same code again, but still received the same error. 

I am able to run xw.Book() successfully in the terminal, so I think it has to do with Spyder permissions, but I don't know how to prompt the permissions again. Please let me know if you have any thoughts on this.

**Comment by eshao16** [comment]
The MESSAGE on my error is also different - I am getting 'OS ERROR' whereas other people have been getting 'The user has declined permission.'

I also tried running the code in Pycharm to the same OS ERROR

**Comment by fzumstein** [comment]
One thing you could try is if you still get the same error if you comment out the following line: 
```
  File "/Users/*/opt/anaconda3/lib/python3.7/site-packages/xlwings/_xlmac.py", line 187, in add
    self.app.activate()
```

**Comment by eshao16** [comment]
When I comment that line out, I get different error:

Traceback (most recent call last):

  File "/Users/eshao/opt/anaconda3/lib/python3.7/site-packages/aeosa/appscript/reference.py", line 460, in __call__
    return self.AS_appdata.target().event(self._code, params, atts, codecs=self.AS_appdata).send(timeout, sendflags)

  File "/Users/eshao/opt/anaconda3/lib/python3.7/site-packages/aeosa/aem/aemsend.py", line 92, in send
    raise EventError(errornum, errormsg, eventresult)

EventError: Command failed: OS error (-1743)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "<ipython-input-4-bcb86508eef1>", line 1, in <module>
    xw.Book()

  File "/Users/eshao/opt/anaconda3/lib/python3.7/site-packages/xlwings/main.py", line 529, in __init__
    impl = apps.active.books.add().impl

  File "/Users/eshao/opt/anaconda3/lib/python3.7/site-packages/xlwings/main.py", line 2843, in add
    return Book(impl=self.impl.add())

  File "/Users/eshao/opt/anaconda3/lib/python3.7/site-packages/xlwings/_xlmac.py", line 188, in add
    xl = self.app.xl.make(new=kw.workbook)

  File "/Users/eshao/opt/anaconda3/lib/python3.7/site-packages/aeosa/appscript/reference.py", line 496, in __call__
    raise CommandError(self, (args, kargs), e, self.AS_appdata) from e

CommandError: Command failed:
		OSERROR: -1743
		MESSAGE: OS error
		COMMAND: app(pid=20656).make(new=k.workbook)

**Comment by balqx** [comment]
I've also done the reset automation permissions as you mentioned in [#1146 ](https://github.com/xlwings/xlwings/issues/1146)

**Comment by fzumstein** [comment]
has this always been like that or did you just recently upgrade to Catalina? Have you reinstalled Python since then? The fact that it does work in the terminal but not from other apps looks like it's not really an xlwings issue.

**Comment by balqx** [comment]
I have had Python (Anaconda) installed for a few months now, but am only now trying to use the xlwings package. I did not try xlwings before upgrading to Catalina. Should I try redownloading Anaconda?

**Comment by fzumstein** [comment]
Can't really say, but it might be worth a try. I'll upgrade to Catalina at the end of next month and will be able to tell you more. But I remember that Anaconda initially had some issues when upgrading to Catalina, but might be completely unrelated. Again, the fact that it works in the terminal means that it shouldn't really be an xlwings issue.

**Comment by fzumstein** [comment]
please see #1266 and https://github.com/ContinuumIO/anaconda-issues/issues/11387 to see if one of the suggestions solve it. First, try to start spyder from the command prompt if you don't do that already.

**Comment by balqx** [comment]
opening spyder from the terminal fixed my issue. Thank you

**Comment by fzumstein** [comment]
I claim that this is an issue with Spyder and PyCharm... VisualStudio code and Terminal correctly ask for permission when `xw.Book()` is run for the first time. It then appears correctly under Preferences > Security & Pricvacy > Automation. See also: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360005152379-Pycharm-cannot-get-permission-to-control-Excel-Mac-

Anyhow, starting Pycharm from a Terminal also works as a workaround for now.

**Comment by tollvam** [comment]
@fzumstein It works for me when i launch it from the terminal with python / ipython as it asks the first time if i allow it but when i launch it from the terminal in visual studio code with python / ipython i have this os error ! any idea ? (python 3.7, vsc 1.44, mojave 10.14.6) thanks !

**Comment by fzumstein** [comment]
It works fine for me even in the Terminal of VS Code. Are you sure you use the same Terminal in VS Code as you do externally?

**Comment by tollvam** [comment]
I think so yes as i never changed anything about it, it's the default one ? How can i verify ? And if it's not the same, why i don't have the popup when i try to do xw.Book() in the vsc terminal instead of the error ? Thanks !

**Comment by fzumstein** [comment]
I really can't tell why some people have issues, but it's a thing between the editor and macOS, nothing I can fix on the xlwings side.
Your default shell is shown in a dropdown in the Terminal. Should most likely be `zsh`.

**Comment by tollvam** [comment]
My terminal is bash in vsc but also on my os so it's the same. 
Ok i'll check with visual studio code then, thanks !

**Comment by fzumstein** [comment]
PyCharm 2020.1 seems to have fixed this
