### ISSUE TITLE
How can I paste to a continuous log records?

### ISSUE THREAD

**Issue by boyac** [xlwings/xlwings#1268]
Hi all,
I'm a newbie to xlwings packages. 
I'm trying to create a log records, manually I copy from a defined section from Sheet1 to Sheet2 (the log sheet). If using xlwings, how can I paste continuously after the last row with data on Sheet2?

Thanks

**Comment by fzumstein** [comment]
By using something like `mysheet['A1'].expand().last_cell` you should be able to get the cell you want to write to?
