### ISSUE TITLE
How can I write a pure numeric characters in the file by xlwings?

### ISSUE THREAD

**Issue by primary-student** [xlwings/xlwings#1269]
I have a list of uncertain length.
It contains int type and str types of pure numeric characters. eg [1,"001"]
When I write the list in Excel file with code "sheet.range("A1").value = [1,"001"] ".
The result in file is 
![image](https://user-images.githubusercontent.com/47291530/75320625-0df3fd80-58aa-11ea-85a6-a9d0dc4e85b5.png)

How can I write a pure numeric characters in the file by xlwings?

**Comment by fzumstein** [comment]
You can use an apostrophe:

```
wb.sheets[0]['A2'].value = "'001"
```
