### ISSUE TITLE
Don't require to set the PYTHONPATH when working with OneDrive

### ISSUE THREAD

**Issue by RobertvanLoon** [xlwings/xlwings#1275]
#### Windows 10, xlwings 0.17.1, Office 365, Python 3.7

Until yesterday my xlwings was working perfectly fine. This morning when I opened up the same spreadsheet I worked on the night before I got this error message:

```
ModuleNotFoundError: No module named 'Options_Pricer_RvL'
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\rober\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    module = import_module(module_name)
  File "C:\Users\rober\Anaconda3\lib\site-packages\xlwings\udfs.py", line 228, in get_udf_module
    module = get_udf_module(module_name)
  File "C:\Users\rober\Anaconda3\lib\site-packages\xlwings\udfs.py", line 447, in import_udfs
    return ToVariant(getattr(obj, method)(*pargs, **kwargs))
  File "C:\Users\rober\Anaconda3\lib\site-packages\xlwings\server.py", line 194, in Call
    return func(*args)
  File "C:\Users\rober\Anaconda3\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFl
```

I did not change anything to any settings. The same issue appears on my desktop and my laptop. I've tried different sheets, all have the same problem. I am 100% sure the spreadsheet has the same name, and is in the same location, as the corresponding .py file.

Any idea what is going on? Help is much appreciated!

Thanks.

**Comment by fzumstein** [comment]
Does a quickstart sample work?

**Comment by RobertvanLoon** [comment]
Strangely enough new clean sheet starting with udfs from scratch does work. But any existing sheet does not. Also not the 4 xlwings examples.

**Comment by fzumstein** [comment]
Do you have a value for `UDF Modules` in your add-in or config?

**Comment by RobertvanLoon** [comment]
Do you mean xlwings_udfs module in my spreadsheet? Yes, see pic.

![afbeelding](https://user-images.githubusercontent.com/47296978/76704321-6b74b080-66d8-11ea-91fd-ef3ee44afad1.png)

The problem is not just with UDFs. Also matplotlib plots don't work anymore.

**Comment by RobertvanLoon** [comment]
I did some more testing and even a brand new workbook and .py file (with same name and location) gives me the same error message now. I have not done any updates to my Windows or Office that I am aware of.

Are there other things I can do to help finding to find the source of this problem?

**Comment by fzumstein** [comment]
What I actually meant is to doulbe check your config in the Ribbon and/or config files: https://docs.xlwings.org/en/stable/addin.html

**Comment by RobertvanLoon** [comment]
I have not changed my configuration in the Ribbon since I start using xlwings. I double checked but all locations are correct. UDFs used to work without specifying the UDF modules in the Ribbon. I did try to specify it explicitly but that didn't help. This is my .xlwings\xlwings.conf file if that helps:

"C:\Users\rober\Anaconda3\python.exe",""
"C:\Users\rober\Anaconda3\python.exe",""
"INTERPRETER",""
"CONDA ENV","base"
"LOG FILE",""
"USE UDF SERVER","False"
"DEBUG UDFS","False"
"PYTHONPATH","C:\Users\rober\Anaconda3\python.exe"
"CONDA BASE","C:\Users\rober\Anaconda3"
"UDF MODULES",""

**Comment by RobertvanLoon** [comment]
Looks like I found the issue, it seems to have something to do with Onedrive. Since I've moved my files from Onedrive to my local C: drive, everything works fine again. After moving them back to Onedrive, same problems. This is quite annoying as I use Onedrive all the time to use files on both my laptop and desktop.

Any idea what I need to change to Onedrive to get this fixed?

**Comment by fzumstein** [comment]
Can you please check if you get the same behaviour with 0.18? You will need to upgrade both the add-in and the Python package.

**Comment by RobertvanLoon** [comment]
I've upgraded de add-in and tried to upgrade the package using pip. In 
Pycharm I still see 0.17.1 though instead 0.18. Also installing xlwings 
via Pycharm directly only gets me to 0.17.1. Got the below screen when 
using pip:



------ Original Message ------

**Comment by fzumstein** [comment]
you are on anaconda so might have installed xlwings previously via conda? best would be to clean up first via `pip uninstall xlwings` and `conda remove xlwings`, then try again with `conda install -c conda-forge xlwings`.

**Comment by RobertvanLoon** [comment]
Ok that clean-up worked. Have 0.18 installed now. But the Onedrive issue 
is still there unfortunately.
I'm trying out a couple different things to see if it works, but so far 
no luck.

------ Original Message ------

**Comment by fzumstein** [comment]
One thing I noticed is that your config file looks a bit funny, i.e. wrong e.g. with the PYTHONPATH. Can you cut it down to the following:

```
"CONDA ENV","base"
"CONDA BASE","C:\Users\rober\Anaconda3"
```

and try again?

**Comment by RobertvanLoon** [comment]
Looks like we're getting closer. But when I run xlwings I get error 
messages from which it looks like I have to reinstall all my packages 
like nump, scipy, matplotlib etc. Previously I have always installed 
packages through Pycharm. And I still see those packages as installed in 
Pycharm.


------ Original Message ------

**Comment by fzumstein** [comment]
While you can install them with PyCharm, you will always install them into one of the conda environments. Are they installed in the `base` environment where you are pointing xlwings to?

**Comment by RobertvanLoon** [comment]
A partial hurray! 0.18 is properly installed and working with files on 
Onedrive works on my desktop now. But for some reason not on my laptop 
yet where I have done the same upgrade to 0.18. Also have same links to 
conda in the ribbon.

------ Original Message ------

**Comment by fzumstein** [comment]
Actually, for now you'll need to set the `PYTHONPATH` when you use OneDrive to something like `%ONEDRIVE%\yourproject`.

**Comment by fzumstein** [comment]
or if you are on business: `%ONEDRIVECOMMERCIAL%\yourproject`

**Comment by RobertvanLoon** [comment]
Hooray! Everything is working fine again now. Thanks a lot for your help 
and patience! Much appreciated.

------ Original Message ------

**Comment by fzumstein** [comment]
I must have thought it's obvious when I fixed it, but it's obviously not - will try to document that soonish.
