### ISSUE TITLE
Relative paths not working as expected

### ISSUE THREAD

**Issue by juliuscrn** [xlwings/xlwings#1276]
Hi,

I have a python script which is triggered via Excel button. When I do this, all relative paths for some reason start at C:/, instead of the project folder.

For example, when I set up a handler to create log at ../logs

`logging.FileHandler(**f'../logs/**validations_{datetime.now().strftime("%Y%m%d_%H%M%S")}.log')`

I get this error:

![image](https://user-images.githubusercontent.com/10067941/76804856-9e549c80-67dd-11ea-8402-ac3cb0295f17.png)

The script is located at "C:\Users\usrname\Desktop\Projects\projectname\validations"

Any hints? I don't want to hardcode the paths :(

**Comment by fzumstein** [comment]
You currently can't set a working directory with xlwings, so construct an absolute path like this: 
https://github.com/xlwings/xlwings/blob/master/examples/database/database.py#L21 or like this: 

https://github.com/xlwings/xlwings/blob/master/examples/ga_dashboard/ga_dashboard.py#L11-L12

**Comment by juliuscrn** [comment]
Perfect, thank you!
