### ISSUE TITLE
Allow to use Threading and Dynamic Array Formulas

### ISSUE THREAD

**Issue by Colin-b** [xlwings/xlwings#1277]
Hi,

For now dynamic array formulas are prefixed with the [implicit intersection operator (@)](https://support.office.com/en-us/article/implicit-intersection-operator-ce3be07b-0101-4450-a24e-c1c999be2b34) when using threading on generated user defined functions.
Meaning that a single value is shown instead of the expected array.

```python
import xlwings as xw

@xw.func(async_mode='threading')
def many_values():
    return ["test", "test2"]
```
![image](https://user-images.githubusercontent.com/7591933/77068786-759ff300-69e7-11ea-82a7-d49bfb69b9de.png)

The issue comes from the fact that [Range.Formula] is used when updating the formula to trigger a new call retrieving the cached result: https://github.com/xlwings/xlwings/blob/7af17370cef4bb887ec41bd37d5df72dd3b8a4c5/xlwings/udfs.py#L39

Leading to the underlying use of Range.Formula as in the following:
https://github.com/xlwings/xlwings/blob/7af17370cef4bb887ec41bd37d5df72dd3b8a4c5/xlwings/_xlwindows.py#L743

Switching to [Range.Formula2] fixes the issue.
![image](https://user-images.githubusercontent.com/7591933/77068853-99fbcf80-69e7-11ea-8322-68d991490013.png)

I will gladly provide a pull request but I was wondering about the design approach for this fix, so first I would like to check with you if the following can be merged:

* Exposing `formula2` (as a property, the same way it is done for `formula`) inside [`xlwings._xlwindows.Range`](https://github.com/xlwings/xlwings/blob/7af17370cef4bb887ec41bd37d5df72dd3b8a4c5/xlwings/_xlwindows.py#L667) and [`xlwings._xlmac.Range`](https://github.com/xlwings/xlwings/blob/7af17370cef4bb887ec41bd37d5df72dd3b8a4c5/xlwings/_xlmac.py#L441) classes.
* In [`xlwings.udfs.AsyncThread.run`](https://github.com/xlwings/xlwings/blob/7af17370cef4bb887ec41bd37d5df72dd3b8a4c5/xlwings/udfs.py#L32), try to set `formula2` with the previous `formula2`, if it fails, fallback to previous behavior (setting `formula` with the previous `formula`).

However I would point out that I don't have access to a Mac then I am unable to test the behavior on Mac, that's why I am proposing to use a try/except block on the operation, as I am unaware of the result.

Also, I don't have access to a version of Microsoft Excel that does not have [Range.Formula2], so I am unable to test the behavior when [Range.Formula2] is not available, that's why I am proposing to use a try/except block on the operation, as I am unaware of the result.

According to my tests, [Range.Formula2] works fine with arrays and single value return types.

[Range.Formula]: https://docs.microsoft.com/en-us/office/vba/api/excel.range.formula
[Range.Formula2]: https://docs.microsoft.com/en-us/office/vba/api/excel.range.formula2

**Comment by fzumstein** [comment]
Mac currently doesn't support UDFs, so you don't have to worry about that part. You'll most likely get a `pywintypes.com_error` if the formula doesn't exist, so try/except sounds good. I'll be able to test it.
