### ISSUE TITLE
How would you access caller address using threading?

### ISSUE THREAD

**Issue by Colin-b** [xlwings/xlwings#1278]
I am wondering what the best way of doing it would be.

I need to access the application caller address, and of course, as we are in another thread when accessing the application.caller, it fails with:

```bash
excel_caller = excel_application.Caller
File "C:\Users\JS5391\pyxelrest\env\lib\site-packages\win32com\client\dynamic.py", line 527, in __getattr__
    raise AttributeError("%s.%s" % (self._username_, attr))
AttributeError: _Application.Caller
```

where excel_application is retrieved via

```python
@xw.arg('excel_application', vba='Application')
```

As the caller is already extracted before starting the Thread, would you consider returning a somehow fake application/caller instance to the user in this case?

I know this is a very specific use case and it's a bit ugly so that's why I am asking before submitting any PR.

**Comment by fzumstein** [comment]
Not sure I follow, did you see this? https://docs.xlwings.org/en/stable/threading_and_multiprocessing.html#id1 feel free to do a work-in-progress PR

**Comment by Colin-b** [comment]
This is a real specific use case and I can deal with the fact that I cannot access Application.Caller when using threading mode for my UDF.

Thanks for the reply :)
