### ISSUE TITLE
Not quite sure if it is a debug related bug

### ISSUE THREAD

**Issue by ImMial** [xlwings/xlwings#1282]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.18.0, Office 2019, Python 3.7
#### Describe your issue (incl. Traceback!)
I used pycharm with anaconda to create the envirment. Actually it works fine in running. But still strange in debugging.
I pined a break in the print(i,j) and the debug process existed when all the modification completed. Which means the program ran to the end and then debug process started. (the trace ended with -1 because I manually stopped it, the trarget excel is already written)
I am new to both python and xlwings, so I am doubt that it might be my mistake.

```python
C:\Users\xxx\.conda\envs\Excel\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.3\plugins\python-ce\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 62027 --file C:/Users/xxx/OneDrive/academic/Workbench/PythonExcel/copy.py
8 1
8 2
8 3
8 4
8 5
8 6
8 7
8 8
8 9
8 10
8 11
8 12
9 1
9 2
9 3
9 4
9 5
9 6
9 7
9 8
9 9
9 10
9 11
9 12
pydev debugger: process 1976 is connecting

Connected to pydev debugger (build 193.6911.25)
8 1

Process finished with exit code -1

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import xlwings as xw

summary = xw.Book('summary.xlsx')
summaryWS = summary.sheets['Sheet1']
for i in range(8, 10):
    for j in range(1, 13):
        print(i, j)
        dataWB = xw.Book('cdsheet - 201{} ({}).xlsx'.format(i, j))
        dataWS = dataWB.sheets['func'].range('A1:I3969').options(ndim=2).value
        summaryWS.range('A{}:I{}'.format((i - 8) * 3970 * 12 + (j - 1) * 3970 + 1,
                                         (i - 8) * 3970 * 12 + (j - 1) * 3970 + 3969)).value = dataWS
        dataWB.close()
summary.save()


```

**Comment by fzumstein** [comment]
If I understand correctly, the debugger didn't stop at your breakpoint? If that's the case, try to restart PyCharm, but probably not an xlwings issue.

**Comment by ImMial** [comment]
> 
> 
> If I understand correctly, the debugger didn't stop at your breakpoint? If that's the case, try to restart PyCharm, but probably not an xlwings issue.

Thank you for your reply！

I solved the problem... It's because I didn't fully adapt to Python from Matlab and forgot to use
`if __name__ == '__main__':`

I will close this issue now.
