### ISSUE TITLE
Function call through USE UDF Server set TRUE is returning an error

### ISSUE THREAD

**Issue by Thanasisleo** [xlwings/xlwings#1286]
#### Describe your issue (incl. Traceback!)

```python
xlwings server running, clsid={DB623610-836D-4E06-84E2-02412F7C9ABC}
pythoncom error: Python error invoking COM method.

Traceback (most recent call last):
  File "C:\Users\Public\alpine\Apps\Continuum\anaconda3\envs\py37\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Users\Public\alpine\Apps\Continuum\anaconda3\envs\py37\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Users\Public\alpine\Apps\Continuum\anaconda3\envs\py37\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return func(*args)
  File "C:\Users\Public\alpine\Apps\Continuum\anaconda3\envs\py37\lib\site-packages\xlwings\server.py", line 287, in Exec
    exec(stmt, globals, locals)
  File "<string>", line 1, in <module>
  File "n:\train\collab\trc\member\trcl\tools\smart modules\projects\thesource\awb.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\Public\alpine\Apps\Continuum\anaconda3\envs\py37\lib\site-packages\pandas\__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']


```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

Hi, I have an excel file which calls a function in a python script. I have included the xlwings.conf worksheet also.

In my computer it is running fine, with setting the **USE UDF Server** to **TRUE** or **FALSE**.

However, on my colleague's computer it only runs when the flag is set to FALSE. This is the error when he tries to run it with the flag to TRUE. 

Any idea why?

```python
# Your code here
RunPython ("import newtrades; newtrades.importNewTrades()")
```

**Comment by fzumstein** [comment]
This looks like the Conda settings have not been correctly set on his machine?

**Comment by Thanasisleo** [comment]
> This looks like the Conda settings have not been correctly set on his machine?

But why to work properly through pycharm or even from excel but only when the UDF Server is set to FALSE?

**Comment by fzumstein** [comment]
Can you paste the config of your colleague?

**Comment by Thanasisleo** [comment]
> Can you paste the config of your colleague?

Which exactly conda command should I run?

`conda config --show` ?

**Comment by fzumstein** [comment]
I meant the xlwings config

**Comment by Thanasisleo** [comment]
> I meant the xlwings config


Interpreter        | D:\Apps\Continuum\anaconda3\envs\py37\python.exe
PYTHONPATH   | N:\train\Collab\TRC\MEMBER\TRCL\Tools\Smart Modules\Projects\theSource
UDF Modules    |  
Debug UDFs      | FALSE
Log File             | N:\Trading\Collab\TRC\MEMBER\TRCL\Tools\Smart   Modules\Projects\theSource\Log.txt
Use UDF Server | TRUE

It is the same. If he sets the flag to FALSE, it works fine.

**Comment by fzumstein** [comment]
You have to use the Conda settings: 

```
Interpreter | 
PYTHONPATH | N:\train\Collab\TRC\MEMBER\TRCL\Tools\Smart Modules\Projects\theSource
Conda Base | D:\Apps\Continuum\anaconda3\
Conda Env | py37
UDF Modules |  
Debug UDFs | FALSE
Log File | N:\Trading\Collab\TRC\MEMBER\TRCL\Tools\Smart Modules\Projects\theSource\Log.txt
Use UDF Server | TRUE
```

**Comment by Thanasisleo** [comment]
Sorry, I have that, didn't added it in the post before because I thought what mattered was the Interpreter path.This is the full table:

`

Interpreter | D:\Apps\Continuum\anaconda3\envs\py37\python.exe
PYTHONPATH | N:\train\Collab\TRC\MEMBER\TRCL\Tools\Smart   Modules\Projects\theSource
UDF Modules |  
Debug UDFs | FALSE
Log File | N:\train\Collab\TRC\MEMBER\TRCL\Tools\Smart  Modules\Projects\theSource\Log.txt
Use UDF Server | TRUE
Conda Base | D:\Apps\Continuum\anaconda3
Conda Env | py37

`

That way works fine on my pc. Should I have the Interpreter blank?

**Comment by fzumstein** [comment]
yes, or just python/pythonw

**Comment by Thanasisleo** [comment]
> yes, or just python/pythonw

Indeed, that worked. Thank you. 

Now I have the following questions:
1) Why before the change on the config tab did the code work on my computer and not on my colleague's?
2) When I was using the **Interpreter path** and with **USE UDF SERVER** to **TRUE**, it used to open the terminal and I could see what was going on, at which state of the process was, a great way for debugging. Why has it disappeared now?

That's how the terminal looked like:

![image](https://user-images.githubusercontent.com/19855691/78142561-582e4880-742d-11ea-984b-5239b035494e.png)

Instead, I get the following message:

![image](https://user-images.githubusercontent.com/19855691/78141815-52843300-742c-11ea-8a59-51cc169b6726.png)

Which I can close and still the server will be running. 
3) Can I have the solution where I omit the interpreter path but also have the terminal open?

**Comment by fzumstein** [comment]
Set teh Interpreter to `python` and you should see the output again, by default it uses `pythonw` which hides it
