### ISSUE TITLE
Error in Book.caller() when calling xlwings from RunPython in VBA

### ISSUE THREAD

**Issue by FinancialRADDeveloper** [xlwings/xlwings#1288]
#### OS (e.g. Windows 10 or macOS Sierra)

Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

Office: 365 64 bit
xlwings: xlwings64-0.18.0.dll
Python : 3.7 64 bit via Anaconda

#### Describe your issue (incl. Traceback!)

```python
# Your traceback here

---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "C:\Users\alan_\anaconda3\envs\xlwings\lib\site-packages\xlwings\_xlwindows.py", line 431, in __call__

    return Book(xl=self.xl(name_or_index))

  File "C:\Users\alan_\AppData\Local\Temp\gen_py\3.7\00020813-0000-0000-C000-000000000046x0x1x9\Workbooks.py", line 198, in __call__

    ret = self._oleobj_.InvokeTypes(0, LCID, 2, (13, 0), ((12, 1),),Index

pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147352565), None)



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "c:\users\alan_\pycharmprojects\quantfinance\xlwings\hello.py", line 5, in SayHello

    wb = xw.Book.caller()

  File "C:\Users\alan_\anaconda3\envs\xlwings\lib\site-packages\xlwings\main.py", line 586, in caller

    return cls(impl=app.books[name].impl)

  File "C:\Users\alan_\anaconda3\envs\xlwings\lib\site-packages\xlwings\main.py", line 77, in __getitem__

    return self(key)



  File "C:\Users\alan_\anaconda3\envs\xlwings\lib\site-packages\xlwings\main.py", line 48, in __call__

    return self._wrap(impl=self.impl(name_or_index))

  File "C:\Users\alan_\anaconda3\envs\xlwings\lib\site-packages\xlwings\_xlwindows.py", line 433, in __call__

    raise KeyError(name_or_index)

KeyError: 'c:\\users\\alan_\\pycharmprojects\\quantfinance\\xlwings\\runpythonfromvba.xlsm'



Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```basic
Sub CallPythonFromVBA()

    RunPython ("import hello; hello.SayHello()")

End Sub
```

```python
# Your code here
import xlwings as xw


def SayHello():
    wb = xw.Book.caller()
    wb.sheets[0].range("A1").value = 'Hello World'

def HelloWorld():
    return 'Hello Wings'
```

**Comment by FinancialRADDeveloper** [comment]
![image](https://user-images.githubusercontent.com/17732614/78376803-be020800-75c6-11ea-8d2b-08de63fbdc85.png)



[RunPythonFromVBA.zip](https://github.com/xlwings/xlwings/files/4428222/RunPythonFromVBA.zip)

**Comment by FinancialRADDeveloper** [comment]
Looks like this is also mentioned here [https://github.com/xlwings/xlwings/issues/1288](url)

**Comment by akasolace** [comment]
I just updated my xlwings version and I start to experience the same issue ....

**Comment by fzumstein** [comment]
Make sure to upgrade your addin and/or vba module, too.

**Comment by akasolace** [comment]
> Make sure to upgrade your addin and/or vba module, too

did that, remove and resintall xlwings and now I run into another error can't import numpy (https://github.com/xlwings/xlwings/issues/954)

**Comment by fzumstein** [comment]
https://docs.xlwings.org/en/stable/addin.html#anaconda-miniconda

**Comment by akasolace** [comment]
@fzumstein I tried everything without success

 **- config 1   => can't load numpy**

Interpreter | D:\Apps\Continuum\anaconda3\envs\py37\python.exe
-- | --
Conda Base | D:\Apps\Continuum\anaconda3
Conda Env | py37

 **- config 2   => python not launched from anaconda environement**

Interpreter | python
-- | --
Conda Base | D:\Apps\Continuum\anaconda3
Conda Env | py37

**Comment by akasolace** [comment]
@fzumstein reverting to my previous version of xlwings fixed my issue

```
The following packages will be DOWNGRADED:
  xlwings                             0.19.4-py37hc8dfbb8_0 --> 0.15.8-py37_0
```

**Comment by pdavidson-actuary** [comment]
I had this problem and copying the new code from the xlwings1 VBA module in the 'quickstart_standalone.xlsm' file solved it for me.
It wasn't required to update the xlwings.conf worksheet (i.e. runs ok without defining 'Interpreter Mac' etc...)

Running v0.20.7

**Comment by fzumstein** [comment]
I am closing this issue as it is a mix a various things. Please open a new one if you continue to see any issue.
