### ISSUE TITLE
Can xlwings realize RTD (real time data) or similar functionality in excel? if not, will it support RTD in the future? 

### ISSUE THREAD

**Issue by fspwf** [xlwings/xlwings#1289]
Can xlwings realize RTD (real time data) or similar functionality in excel, like PyXLL?
If not, does xlwings have any plan to support RDT in the future? 

I love xlwings, and hope it become better and more powerful.

**Comment by fzumstein** [comment]
This is a duplicate of #888: Yes, it's on the list for xlwings PRO.
