### ISSUE TITLE
Change format of part of a cell

### ISSUE THREAD

**Issue by wave-DmP** [xlwings/xlwings#1296]
first of all, xlwings is great for working with excel! :)

I would like to submit a feature request:
In the course of my work, we see a lot of spreadsheets containing the text of entire document paragraphs within a single cell.

Currently it is possible to change the format of that cell in its entirety, however, I have not found a way to change the formatting of just part of the text (e.g. a group  of words) within this cell.  The functionality is there in excel and call be called via VBA.  It would be really cool if xlwings had this option so that all code could be left in python, rather than having to pass data to excel, then calling a vba function on it.

here's the vba implementation of this:
https://www.computergaga.com/blog/format-specific-words-in-a-cell-using-vba/

**Comment by fzumstein** [comment]
characters and Markdown-based formatting are now supported:

* https://docs.xlwings.org/en/stable/api.html#characters
* https://docs.xlwings.org/en/stable/markdown.html
