### ISSUE TITLE
Error with trying to execute a named range 

### ISSUE THREAD

**Issue by ghost** [xlwings/xlwings#1297]
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
python 3.8 
#### Describe your issue (incl. Traceback!)
I'm trying to execute a string that represents a sheet and named range in excel. I think the error is that it's unable to find the worksheet but the worksheet exists. 

```python
# Your traceback here
 File "C:\Users\YV999FY\AppData\Local\Programs\Python\Python38-32\lib\site-packages\xlwings\_xlwindows.py", line 62, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in Range
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2146827284), None)
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
There error is happening when I execute the string name of the named range. 
```python
code below:
wb=xw.Book("LTCFP Stat ALR Replication Cell1.xlsm")



#define worksheets

wsProductControl = wb.sheets["ProductControl"]
wsVarControl = wb.sheets("VarControl")
wsDBTables = wb.sheets("DBTables")

path = wsProductControl.range("Path").value
AssumPath = wsProductControl.range("AssumptionFolder").value
numRefVars = int(wsVarControl.range("numRefVars").value)
NumRefTbls = int(wsProductControl.range("NumRefTbls").value)
DbtblVarLoader = wsProductControl.range("DbtblVarLoader").value

##############

dDBtable = {} # dictionary of DB imported tables
dvar = {} # create dictionary of all tables
dtable = {} # create dictionary of all tables
dExcelTable = {} # create dictionary of all tables

numRefVars = int(wsVarControl.range("numRefVars").value)
ListRefVarsRange = 'B3:D' + str(int(numRefVars + 3))
ListRefVars = wsVarControl.range(ListRefVarsRange).value
ListRefVars = pd.DataFrame(ListRefVars)
ListRefVars.columns = ListRefVars.iloc[0]
ListRefVars = ListRefVars.reindex(ListRefVars.index.drop(0))

for index, row in ListRefVars.iterrows():
    StrNameRefVar = row['Excel Var Name']       # python variable names cannot have periods in them followed by a number. this strips away periods in the name and replaces them with underscores
    exec(StrNameRefVar + " = wb.sheets['" + row['Sheet'] + "'].range('" + row['Excel Var Name'] + "').value")
    dvar[StrNameRefVar] = eval(StrNameRefVar)

###

```

**Comment by fzumstein** [comment]
The error means something else:

```
>>> import win32api
>>> win32api.FormatMessage(-2146827284)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pywintypes.error: (15100, 'FormatMessageW', 'The resource loader failed to find MUI file.')
```

Try to google the error and see if it applies to your situation.

**Comment by jjaredrides** [comment]
This is the error I get when I evaluate the Pywin error#

"win32api.FormatMessage(-2146827284)
pywintypes.error: (1813, 'FormatMessageW', 'The specified resource type cannot be found in the image file.')"

**Comment by fzumstein** [comment]
Hard to tell what's the issue - I don't even know in which line of your code this is happening... A good strategy might be to simplify the tool until the issue disappears to see whats causing it. I assume that plain vanilla quickstart samples work ok?

**Comment by jjaredrides** [comment]
I modified the code to be:
######
for index, row in ListRefVars.iterrows():
    StrNameRefVar = row['Excel Var Name']      
    shtname = row['Sheet']
    wsTemp = wb.sheets[shtname]
    StrNameRefVar = row['Excel Var Name']
    dictVal = wsTemp.range(StrNameRefVar).value
    dvar[StrNameRefVar] = dictVal
#####
And it bombs when it loops through the next iteration with the error below:
_Traceback (most recent call last):
  File "C:\Users\YV999FY\AppData\Local\Programs\Python\Python38-32\lib\site-packages\xlwings\_xlwindows.py", line 62, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject <unknown>>", line 2, in Range
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2146827284), None)_
