### ISSUE TITLE
saving as .xlam breaks functionality

### ISSUE THREAD

**Issue by eventide99** [xlwings/xlwings#1298]
Windows 10 
0.17.1, Office 365, Python 3.7.6

a) created test.xlsm and test.py. UDF alldata() works properly
b) wish to expose alldata() to multiple other workbooks
c) save test.xlsm as an add-in (test.xlam)
d) close and restart excel, ensure test.xlam is installed as an addin
d) create new workbook test2.xlsm and invoke alldata()
e) traceback as below

Possibly an application.caller issue...looks like the xlwings addin does not pick up the correct location of test.py to send to the DLL.

Inspecting line the xlwings udf.py file, the error occurs at line 240:

237 def call_udf(module_name, func_name, args, this_workbook=None, caller=None):
238    
239      module = get_udf_module(module_name)
240            func = getattr(module, func_name)

and at runtime, module is set in 239 to
'<module 'test' from 'C:\\Users\\Generic\\Anaconda3\\lib\\test\\__init__.py'>'
clearly this is not the right place

when the UDF is called from test.xlsm (ie the original cwd in (a)) the location is correct

Thank you for your assistance

```python TRACEBACK
xlwings server running, clsid={B725C699-F169-4F2E-9C7F-6129C3E3697C}
pythoncom error: Python error invoking COM method.

Traceback (most recent call last):
  File "C:\Users\Generic\Anaconda3\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Users\Generic\Anaconda3\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Users\Generic\Anaconda3\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return func(*args)
  File "C:\Users\Generic\Anaconda3\lib\site-packages\xlwings\server.py", line 195, in CallUDF
    res = call_udf(script, fname, args, this_workbook, FromVariant(caller))
  File "C:\Users\Generic\Anaconda3\lib\site-packages\xlwings\udfs.py", line 240, in call_udf
    func = getattr(module, func_name)
AttributeError: module 'test' has no attribute 'alldata'

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by eventide99** [comment]
Follow up:

I have sort of solved this issue by using a standalone project (--standalone) which places the xlwings.bas module directly in test1.xlsm, which is retained when it is saved as test1.xlam.

**Comment by fzumstein** [comment]
You can have a look at the sql extension: https://docs.xlwings.org/en/stable/extensions.html and how it's implemented. You can add the wrapper UDF code to the add-in if you want, just need to replace `ThisWorkbook` with `ActiveWorkbook`. To make the UDF find the Python source, you'll need to place it somewhere where Python can find it, e.g. `site-packages` folder or you need to add the directory to your `PYTHONPATH` settings, see: https://docs.xlwings.org/en/stable/addin.html#global-settings
