### ISSUE TITLE
pywintypes.com_error in 0.18.0

### ISSUE THREAD

**Issue by Gilone** [xlwings/xlwings#1300]
#### OS
Windows 10
#### Versions of xlwings, Excel and Python 
xlwings 0.18.0, Office 365 ProPlus, Python 3.8.2
#### Describe your issue 
When I use VBA code 'RunPython' or 'RunFrozenPython'  to run my python script or EXE from Excel file, it comes with 'pywintypes.com_error'.
This error occurs when I use **Book.caller()**, but not when I use Book('file_path') or set_mock_caller() in Debug mode.
I have tried this script in **xlwings 0.17.0,** the error did not occur.

**Comment by fzumstein** [comment]
You'll need to upgrade the excel add-in, too
