### ISSUE TITLE
VBA Error occurs with subfile function

### ISSUE THREAD

**Issue by Anson1994** [xlwings/xlwings#1304]
Window10 OS 

xlwings 0.18.0 Python3.6 with Anaconda

VBA ERROR occurs with python subfile function 

If the code I run in Python file it does well, but while I use the VBA button and activate the function,
error occurs. Might I know how can I solve it?

Below attached is the error occur in the excel pop-up and my python directory structure.

```python
from option_analysis.function.cal_table import *

```
![error](https://user-images.githubusercontent.com/15684848/80480806-e261c200-8983-11ea-80a1-d030001ffce8.png)

![error1](https://user-images.githubusercontent.com/15684848/80480776-d413a600-8983-11ea-9315-0a1d376d7f28.png)

**Comment by fzumstein** [comment]
I believe this is a standard Python import problem, not something xlwings specific.
