### ISSUE TITLE
runpython install

### ISSUE THREAD

**Issue by sjcapferrat** [xlwings/xlwings#1320]
MacOS Catalina 10.15.4
Python 3.7.6
xlwings 0.17.1 (installed via Anaconda)

I am a very first time user trying to follow the advice (instllation page in docs.xlwings.org)below, then faced with the following problem. Please advice to get out from this.

(Note @docs.xlwings.org)
"When you are on macOS and are installing xlwings with conda (or use the version that comes with Anaconda), you’ll need to run $ xlwings runpython install once to enable the RunPython calls from VBA. This is done automatically if you install the addin via $ xlwings addin install."

(Problem: copied from my terminal)
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import xlwings
>>> xlwings.__version__
'0.17.1'
>>> $ xlwings rynpython install
  File "<stdin>", line 1
    $ xlwings rynpython install
    ^
SyntaxError: invalid syntax
>>> 

Thanks,

**Comment by fzumstein** [comment]
When the command starts with a `$`, it means that you have to type it in your Terminal directly, not while you are in an interactive Python mode. Also, if you can, I'd advise you to upgrade to the latest version if you can.

**Comment by sjcapferrat** [comment]
Done successfully with the suggested upgrade. Thank you!
