### ISSUE TITLE
How to add layout background image？

### ISSUE THREAD

**Issue by IATF** [xlwings/xlwings#1324]
How to add layout background image？

**Comment by fzumstein** [comment]
Most likely something like this should get you going:

```
sheet.api.SetBackgroundPicture(r"C:\path\to\picture")
```

See:
https://docs.xlwings.org/en/stable/missing_features.html and
https://docs.microsoft.com/en-us/office/vba/api/excel.worksheet.setbackgroundpicture

**Comment by IATF** [comment]
This is very useful, thanks！
