### ISSUE TITLE
Import Error Python 3.8.0

### ISSUE THREAD

**Issue by deltalite** [xlwings/xlwings#1325]
OS: Windows 10 
xlwings: 0.19.4
Excel:  Office 365 ProPlus
Python 3.8.0 

Hi, I was getting the below Importerror when simply calling
```python
import xlwings
```
which gave the following traceback related to **_xlwindows.py", line 14**:
```python
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import xlwings
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\xlwings\__init__.py", line 9, in <module>
    from . import _xlwindows as xlplatform
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\xlwings\_xlwindows.py", line 14, in <module>
    import pywintypes
  File "C:\Users\MyUser\AppData\Roaming\Python\Python38\site-packages\win32\lib\pywintypes.py", line 136, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "C:\Users\MyUser\AppData\Roaming\Python\Python38\site-packages\win32\lib\pywintypes.py", line 110, in __import_pywin32_system_module__
    raise ImportError("No system module '%s' (%s)" % (modname, filename))
ImportError: No system module 'pywintypes' (pywintypes38.dll)
```

This could certainly be an environment issue, but I reinstalled packages and other solutions to similar problems without success. 

I could import xlwings after copying over pythoncom38.dll and pywintypes38.dll from `C:\Users\MyUser\AppData\Roaming\Python\Python38\site-packages\pywin32_system32` to `C:\Users\MyUser\AppData\Roaming\Python\Python38\site-packages\win32\lib`, but if this is not just a problem with my environment, the solution to this issue would be to move those dlls to an appropriate location.

I understand that the win32 is a dependency, but had no problem when importing win32 alone.

Thanks for the work you do!

**Comment by fzumstein** [comment]
what version of pywin32 do you have?

**Comment by deltalite** [comment]
227

**Comment by fzumstein** [comment]
It must be your environment then. I've just set up an import test on GitHub actions as well as on an empty system and it had no problems. Bare in mind that pywin32 has all sorts of troubles if you have some dll from another python version somewhere on a path: https://github.com/mhammond/pywin32/issues/1327. Anaconda solves all these problems, by the way.
