### ISSUE TITLE
File not found: xlwings64-0.19.4.dll

### ISSUE THREAD

**Issue by AnonymousJY** [xlwings/xlwings#1328]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Excel 2013, Python 3.7.7

#### Describe your issue (incl. Traceback!)

I receive an error in Excel 
Run-time error '53':

File not found: xlwings64-0.19.4.dll

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
I have a file in UDF.py with a simple function that adds to variables. WHen I try to import functions in Excel xlwings addin ribbon I receive the above error. My xlwings addin version is showing 0.19.4. I have both xlwings32-0.19.4.dll and xlwings64-0.19.4.dll in my anaconda folder where pythonw and python.exe objects are.

```python
import xlwings as xw

@xw.func
def add(x, y):
    return x+y

```

What can I do to resolve the issue?

**Comment by AnonymousJY** [comment]
Resolved. I referenced #1117 . Closing.

**Comment by fzumstein** [comment]
Were you missing a path to the interpreter in the config?

**Comment by AnonymousJY** [comment]
Yes. I didn't realize this until I started debugging xlwings' VBA codes. Thanks.

**Comment by fzumstein** [comment]
no worries, I am planning to getting this finally in a more user friendly way: https://github.com/xlwings/xlwings/issues/1322

**Comment by AnonymousJY** [comment]
Thanks. Appreciate what you are doing for this library.
