### ISSUE TITLE
MemoryError: CreatingSafeArray wehn returning UDF XLWINGS

### ISSUE THREAD

**Issue by luizlu85** [xlwings/xlwings#1332]
Windows 10
xlwings0.19.2, Office 2016, Python 3.7

Faced some issues returning an array of scipy.interpolate.interp1d results.
The loop is running fine since I can get the result[2] for instance. But when i try to return the full array "result" in the UDF I get the error.
I also did a test with a test array of "n" to see if there is any issue in returning an array to excel. And it worked fine.
I couldn't understand this behavior, since I have already returned dataframes, arrays and lists in other UDFs without any issue.
Is there anyone who faced the same issue?

return interpol(n)   works
return test             works
return result[2]      also works!
return result          doesn't work

```python
@xw.func
@xw.ret(expand='table')
@xw.ret(index=False, header=False)
def interp(x,y): 

    interpol = scipy.interpolate.interp1d(x, y)
    result = []
    test = []
    
    for n in range (3,6):
        x = interpol(n)
        result.append(x)
        test.append(n)
        
    return result
```

**Comment by fzumstein** [comment]
result is a list of arrays that xlwings doesn't have a converter for, something like this:

```
[array(0.36787944), array(0.26359714), array(0.1888756)]
```

You'll first need to transform the list to contain floats instead of arrays.
