### ISSUE TITLE
Copy and Paste range as values with python xlwings

### ISSUE THREAD

**Issue by MarekSevela** [xlwings/xlwings#1337]
#### xlwings version 0.19.4.

Hi,
I started using Python with xlwings for Excel automation tasks. Currently, I am struggling to do copy/paste functions in cases I need to paste data as values. (excluded from inside formulas)

Lets say Excel Cell A1 contains "=A2+C2" which returns "72" How do I format the cell with xlwings so that the cell contains only the number?

Could someone please provide me with some code solutions?

There must be something like this in xlwings but I did not find anything in the documentation.

Just to clarify: Copy/paste with formulas included works fine for me.

Thank you very much for anything helpful!
```

**Comment by fzumstein** [comment]
The easiest way is actually to not use copy/paste at all. You can simply read the `value` property and assign it back to `value` again, which will get rid of the formula:

```
sheet.range('A1).value = sheet.range('A1).value 
```

If for whatever reason you need copy/paste, it's documented here (`paste=values`): https://docs.xlwings.org/en/stable/api.html#xlwings.Range.paste

**Comment by MarekSevela** [comment]
Thank you for such quick response, Sir! Worked as expected, I am closing this as resolved now.

Best regards,

Mark

**Comment by nidhipatel16595** [comment]
What if I need to copy a huge volume of data from one worksheet to another?
I am trying to copy using range.copy and it works fine but wanted to check if there is a way to only paste values and not with formatting
