### ISSUE TITLE
Can we wrap more in xlwings?

### ISSUE THREAD

**Issue by StephanSong** [xlwings/xlwings#1342]
Can we think about wrapping the following functions to xlwings from Excel. 

1. adding shapes
2. changing the apperance of the specific shape
3. format, such as borders, font color, font size, underline

**Comment by fzumstein** [comment]
Hi @StephanSong, the missing `Shapes.add` method looks like an oversight. For additional features such as your point 3, we're always adding those features first that are requested by our PRO clients.
