### ISSUE TITLE
xlwings64-dev.dll not found

### ISSUE THREAD

**Issue by Gseguelg** [xlwings/xlwings#1344]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.19.4
Office 365
Python 3.8.3

#### Describe your issue (incl. Traceback!)
I've downloaded the source code to install it manually (as antivirus recognize it as virus through pip) with `python setup.py install`. 
**Note** the current versión on releases are named 'dev' despite release name.

After installing the xlwings.xlam add-in with `xlwings addin install` I get the error of missing `xlwings64-dev.dll`.

**Comment by fzumstein** [comment]
You can't install directly from source, you need to download the xlwings.tar.gz package, unzip it and install from there. If the antivirus doesn't even allow you to download, then you should take it up with them. Alternatively you have to build it manually which will be a pain: https://github.com/xlwings/xlwings/blob/master/.github/workflows/main.yml

**Comment by Gseguelg** [comment]
I try to install it after a direct download from [pypi](https://pypi.org/project/xlwings/#files).
**The file `quickstart_standalone_win.xlsm` gets detected everytime by HP Secure Sense and interrupt the installation.**

So I deleated it from the *.tar.gz and ran `pip install --user xlwings-0.19.4.tar.gz`. No problem with running from python (at least).

For the moment, problem stays.

**Comment by fzumstein** [comment]
Hey I didn't catch if you solved it now ("no problem with running from python") or not ("problem stays").

**Comment by Gseguelg** [comment]
Thank you for your time. Apparently I was trying to run xlwings 64bits with a python 32 btis installation. I Just changed my python installation to 64 bits and everything is fixed.

Also I was able to install xlwings direct from pip, but not the 0.19.5 version.

Amazing library you all having here. Keep it up.

**Comment by fzumstein** [comment]
great to hear it's working, but your conclusion is wrong: xlwings works with any combination of excel and python bitness, so whatever fixed it, it was something else.
