### ISSUE TITLE
Allow double-quotes when invoking xlwings from Excel

### ISSUE THREAD

**Issue by ankostis** [xlwings/xlwings#135]
It is not possible to use the the double-quotes(") character.

I need this in order to construct dynamically html & json code using excel's cell contents

**Comment by fzumstein** [comment]
Hi, this is really the same as #107, right?

**Comment by ankostis** [comment]
Yes, but it does not dictate the solution :-)

**Comment by fzumstein** [comment]
gotcha ;-)

**Comment by fzumstein** [comment]
closing this as #107 is now solved as part of xlwings PRO
