### ISSUE TITLE
AttributeError: Unknown property, element or command: 'UsedRange'

### ISSUE THREAD

**Issue by LiuMaoDou** [xlwings/xlwings#1350]
#### OS (e.g. Windows 10 or macOS Sierra)
macOS Catalina

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.19.4 Python 3.8 Office365
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/opt/anaconda3/envs/python38/lib/python3.8/site-packages/aeosa/appscript/reference.py in __getattr__(self, name)
    574                 try:
--> 575                         selectortype, code = self.AS_appdata.referencebyname()[name]
    576                 except KeyError as e:

KeyError: 'UsedRange'

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
<ipython-input-6-5d1217e9cdda> in <module>
----> 1 ws.api.UsedRange.Row

~/opt/anaconda3/envs/python38/lib/python3.8/site-packages/aeosa/appscript/reference.py in __getattr__(self, name)
    575                         selectortype, code = self.AS_appdata.referencebyname()[name]
    576                 except KeyError as e:
--> 577                         raise AttributeError("Unknown property, element or command: {!r}".format(name)) from e
    578                 if selectortype == kProperty:
    579                         return Reference(self.AS_appdata, self.AS_aemreference.property(code))

AttributeError: Unknown property, element or command: 'UsedRange'

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```
import xlwings as xw
wb = xw.Book('wl-app-test.xlsx')
ws = wb.sheets['sheet1'] 
ws.api.UsedRange.Rows.count

**Comment by fzumstein** [comment]
Hi @LiuMaoDou, the api syntax on Mac is complicated and doesn't correspond to your (windows) version. Anyhow, you dont need `api` here, just do: `ws.used_range.rows.count`.

**Comment by LiuMaoDou** [comment]
@fzumstein thanks for your reply
