### ISSUE TITLE
Saving a xw.Book() object as CSV extension, file is damaged when you later open it

### ISSUE THREAD

**Issue by youngfella93** [xlwings/xlwings#1355]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.19.5, Office 2016, Python 3.7.7
#### Describe your issue (incl. Traceback!)
Hi,
I believe xlwings has trouble saving files as .csv extension. Reading them works perfectly fine.

I tried testing it out by just creating a blank workbook like this:
```python
Test= xw.Book()
```

then saved it by providing full path like that:
```python
Test.api.SaveAs(r"C:\Users\libm002\test.csv")
or Test.save(r"C:\Users\libm002\test.csv")
```

Which works well until I try to open the file. When I load the file it says "The file format and extension of "Test.csv" don't match, The file could be corrupted or unsafe. Unless you trust its source, don't open it. Do you want to open it anyway?"

If you click ok, it will open the file, but when I try importing that file in our web database, it won't work and I believe it is due to that error message. 

Let me know if any additional steps must be done in order to save files as csv or is it part of the missing/lacking features of xlwings?

Thank you!

**Comment by fzumstein** [comment]
Yes, this is an (admittedly annoying) current limitation and a duplication of #187, please continue there. I'll try to get this in soonish. In your workaround you're missing the FileFormat: https://docs.microsoft.com/en-us/office/vba/api/excel.workbook.saveas

**Comment by youngfella93** [comment]
Hey yes seems to be working adding the fileformat much thanks!!
