### ISSUE TITLE
Cannot hook open workbook saved on OneDrive

### ISSUE THREAD

**Issue by ghost** [xlwings/xlwings#1357]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10 Pro x64

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Tested 0.19.5 and 0.18.0. Office 365. Python 3.6.8

#### Describe your issue (incl. Traceback!)

Trying to hook an open workbook fails when it is located on OneDrive. AutoSave is off for the workbook.

```
Traceback (most recent call last):
  File "C:\myproject\excel.py", line 614, in excel
    wb = xl.books.open(filepath)
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\xlwings\main.py", line 2950, in open
    if not os.path.samefile(impl.fullname, fullname):
  File "C:\ProgramData\Miniconda3\envs\py3\lib\genericpath.py", line 96, in samefile
    s1 = os.stat(f1)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'https://d.docs.live.net/xxxxxxxxxxxxxxxx/mybook.xlsx'
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

all of these fail with the same error (where as xw = xlwings module and xl = hooked app):
```
xl.books.open('C:/myonedrive/mybook.xlsx')
xl.Book('C:/myonedrive/mybook.xlsx')
xw.books.open('C:/myonedrive/mybook.xlsx')
```

**Comment by fzumstein** [comment]
if the workbook is already open, you can just use the name of the book without path

**Comment by frogger72** [comment]
Many times it's not open so my script is meant to work for both cases (open only if closed). Also, I'm trying to ensure it's the correct notebook in case there is a notebook open with the same name but at a different path.

**Comment by fzumstein** [comment]
actually not sure what the best strategy is - can you try `os.dir(onedrive)` and then try to open with only the filename?

**Comment by fzumstein** [comment]
Actually - in my testing, this is only an issue if the file is already open - otherwise the following works correctly for me:

```
>>> import xlwings as xw
>>> wb = xw.Book('C:/Users/felix/OneDrive/Test 1.xlsx')
>>> print(wb.fullname)
https://d.docs.live.net/d743b0a57ec113d3/Test 1.xlsx
```

I think that should be fixable

**Comment by frogger72** [comment]
Yes that's the case. For now my workaround if the file is not open is... if it's in my OneDrive folder and wb.fullname contains live.net, I assume it's the same file if they have the same filename. This will miss edge cases where you have two files on OneDrive with the same filename but in different subpaths, but the workaround is good enough for me.

**Comment by fzumstein** [comment]
Another workaroun is to stop syncing Office files: https://support.microsoft.com/en-us/office/use-office-applications-to-sync-office-files-that-i-open-8a409b0c-ebe1-4bfa-a08e-998389a9d823?ui=en-us&rs=en-us&ad=us
