### ISSUE TITLE
Getting error while calling excel

### ISSUE THREAD

**Issue by Chawdavijay** [xlwings/xlwings#1358]
#### Describe your issue (incl. Traceback!)
Till yesterday it was working fine and i was using excel 2013 but now i have upgrade my excel to 2016 after that xlwings is not working properly PFB screesnshot of error, please help to resolve this issue.

![Xlwing error](https://user-images.githubusercontent.com/63785799/87630173-25952b00-c752-11ea-99f9-577e370c4dbf.jpg)

**Comment by fzumstein** [comment]
Try to delete `%TEMP%/gen_py`, then run in a python session `from win32com.client import makepy;makepy.main()`, selecting the new version of Excel in the pop-up. Not quite sure if simply deleting the folder would already be good enough.

**Comment by Chawdavijay** [comment]
I have delete the mentioned file from %temp% and also follow the steps which you have guide... PFA snapshot but still issue is not resolve

![15948882421411424269279980686536](https://user-images.githubusercontent.com/63785799/87646921-c7297600-c76c-11ea-9fe1-6ee1deb92f71.jpg)

**Comment by fzumstein** [comment]
do you get the exact same error now?

**Comment by Chawdavijay** [comment]
Yes

**Comment by Chawdavijay** [comment]
See the error. 
![Uploading 15948888510752969393577121801980.jpg…]()
A

**Comment by Chawdavijay** [comment]
Team, 
Can you please provide me solution ASAP if possible.

**Comment by fzumstein** [comment]
We have plans for ASAP cases: https://www.xlwings.org/pricing, otherwise it would be great if you could make sure your screenshots appear correctly in the first place.

**Comment by Chawdavijay** [comment]
Dear Team, 

I am getting this error for calling data from excel. Please check and let me know the solution
![15967836808535096564674490863862](https://user-images.githubusercontent.com/63785799/89618536-f2097480-d8a9-11ea-9228-274f37297427.jpg)

**Comment by fzumstein** [comment]
What's the value of `Excel_Column+Row_no_for_stock_PNL`?
