### ISSUE TITLE
How to set format fonts and cells 

### ISSUE THREAD

**Issue by code-merchant98** [xlwings/xlwings#1366]
macOS Sierra

xlwings 0.20

I'm trying to format font size, font color, horizontal alignment, border style/weight etc on a worksheet using python xlwings on a Mac. I know you'd have to use the missing features to do this type of editing on python but i don't know what api member functions to use in order to do these formatting on Mac. The ones for windows I can find everywhere online; for example:

import xlwings

wb = xlwings.Book('checker_output.xlsx')

wb.sheets.add('sheet1')

sht = wb.sheets['sheet1']

sht.range('A3:A26').api.Font.Size = 15

the above would work on the windows api, but not on a mac. Any work arounds for this?

**Comment by fzumstein** [comment]
see: https://github.com/xlwings/xlwings/issues/559
