### ISSUE TITLE
Set sheet to hidden

### ISSUE THREAD

**Issue by battlemage64** [xlwings/xlwings#1367]
Is there a way to do this? I certainly didn't see one in the API but it would be a very useful feature to have. I didn't see anyone asking for it, though, so here's my request.

**Comment by fzumstein** [comment]
Currently, you'd have to work around like this: https://docs.xlwings.org/en/stable/missing_features.html

**Comment by battlemage64** [comment]
Oh well. Hope this gets added later. Thank you!

**Comment by fzumstein** [comment]
fixed in 0.21.1 (`sheet.visible`)
