### ISSUE TITLE
Use xlwings with custom add-in / custom ribbon

### ISSUE THREAD

**Issue by tobiassoppa** [xlwings/xlwings#1368]
Hi,

my goal is to create a custom add-in that I can distribute to many users (all of which have python and xlwings installed). This add-in should enable users to use the same functionality (which should be accessed through a custom xml based ribbon) across multiple workbooks from completely different locations on the filesystem. (Minimal example below)

Is this currently possible in xlwings? Beacuse when trying it, I get some weird errors (mostly just an Excel popup displaying the number "400"). I was not able to find anything in your documentation, but only this old [Stackoverflow ](https://stackoverflow.com/questions/54046295/no-custom-ribbon-tab-based-on-xml-in-xlwings) post asking for the same functionality (at least according to my understanding of this post). Unfortunately I wasn't able to find a feature request from said user, so either I overlooked it, or such a feature does not exist right now. 

Could someone clarify this a bit and point me out to proper documentation if it exists? If the whole feature does not exist, could you please treat this as a feature request?

#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings: 0.15.4
Python: 3.7.3

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
Example ribbon
```xml
<customUI xmlns="http://schemas.microsoft.com/office/2009/07/customui"> 
  <ribbon startFromScratch="false"> 
    <tabs> 
      <tab id="ribbon" label="Custom Ribbon"> 
        <group id="group" label="Group"> 
		<button 
			id="btn" 
			imageMso="SignatureLineInsert" size="large" 
			label="Do Something" 
			screentip="Invoke python function through xlwings." 
			onAction="ribbon.do_something()"
		/>
        </group> 
      </tab> 
    </tabs> 
  </ribbon> 
</customUI> 
```
VBA code from a VBA module called `ribbon` that is part of the add-in
```vba
Sub do_something()
    ' The specific location of custom_library is available in xlwings.conf 
    RunPython ("import custom_library; custom_library.do_something()")
End Sub
```
Code inside `custom_library.py`
```python
def do_something():
    wb = xw.Book.caller()
    wb.sheets[0].range("A1").value = "Invoked from custom add-in/ribbon!"
```

**Comment by fzumstein** [comment]
yes, it's possible, it's just not really documented anywhere. Your main issue is that in the case of an add-in, `Book.caller()` is the add-in itself, not the active workbook, so simply change this to: `wb = xw.books.active` and you should be good. Other than that, import the `xlwings.bas` file that is contained in the installation directory or the package and that's pretty much it...you'll then need to make sure it's taking the correct settings - you can use the xlwings.conf sheet from inside your add-in, for example, to make sure it doesn't collide with an installed xlwings ribbon.

**Comment by tobiassoppa** [comment]
Thanks! changing `Book.caller()` to `books.active` solved the problem, now the add-in works. But unfortunately the old issue with the "400" VBA error still persists. Once I call `do_something()` via a button click on the ribbon, the cell gets properly filled with the value. Then after one to three seconds, the error pops up, even though the call was successful and the behaviour was as intended. 
![grafik](https://user-images.githubusercontent.com/16524863/88773774-d5bb5880-d182-11ea-80ca-9767f4dbd3e2.png)

**Comment by fzumstein** [comment]
feel free to upload your add-in and I can take a look.

**Comment by tobiassoppa** [comment]
I've been able to figure out the issue. In the XML describing the ribbon, the `onAction="ribbon.do_something()"` results in the script being executed twice (I think?) and then getting the "400" popup. To fix it, I had to remove the parenthesis `onAction="ribbon.do_something"`.

One additional, slightly offtopic question: If I use the AddIn and click a button on the ribbon it contains, it takes between 10-15 sec until the action is complete. This time is consistent with various tries, it's not just a single outlier. It definitely can't be because of some intensive computations in my application, because in my testcase all the button click does is to call a python script which then calls a VBA macro that does `MsgBox "Test"`.

Is there any way to reduce this time? My assumption, but I may be totally off, is that this wait time is the result of the interpreters "cold start" time (or however you want to call it). If that should be true, would it be possible to not close the interpreter once it has been initialised? So every subsequent action after the first call is faster?

That question doesn't really belong here, but before opening a new Issue I wanted to ask here first. If you want to, I can create a new issue for this question.

**Comment by fzumstein** [comment]
You can set `Use UDF Server` to `TRUE`.

**Comment by tobiassoppa** [comment]
Thanks for pointing that out, missed it in the docs. 

This is how my xlwings.conf looks like
```
"INTERPRETER","Path\To\pythonw.exe"
"PYTHONPATH","Path\To\Sourcecode"
"Use UDF Server","TRUE"
```
but there are still no performance improvements (and I don't overwrite the config file with a config sheet in my excel). Any ideas?

**Comment by fzumstein** [comment]
Yeah, this needs to be fixed, it's currently case sensitive and wrongly documented, just opened an issue for that: https://github.com/xlwings/xlwings/issues/1388 (it works ok if you generate the config file via the ribbon)

**Comment by tobiassoppa** [comment]
Thanks for pointing me in the right direction, appreciate all your help and fast replies! After having a look at the VBA code I've seen that indeed it needs to be 
```
"INTERPRETER","Path\To\pythonw.exe"
"PYTHONPATH","Path\To\Sourcecode"
"USE UDF SERVER","True"
```
Instead of
```
"INTERPRETER","Path\To\pythonw.exe"
"PYTHONPATH","Path\To\Sourcecode"
"Use UDF Server","TRUE"
```
(Just writing this out here in case anyone else is facing the same issue after writing the config by hand)
