### ISSUE TITLE
quickstart doesn't work out of the box, VB says `File not found`

### ISSUE THREAD

**Issue by danieltuzes** [xlwings/xlwings#1376]
#### quickstart doesn't work out of the box, VB says `File not found`
I installed the xlwings module with conda, then integrated it into Excel by issuing (username is masked and variable `%userprofile%` is used instead in the code)
```
(py36) %userprofile%>xlwings addin install
xlwings 0.19.5
Successfully installed the xlwings add-in! Please restart Excel.
```
Because `python.exe` is not in the path, and I have more versions of them, I copied the appropriate version from
```
(py36) %userprofile%>python -c "import sys; print(sys.executable)"
%userprofile%\AppData\Local\conda\conda\envs\py36\python.exe
```
Then I issued 
```
(py36) %userprofile%>xlwings quickstart myproject
xlwings 0.19.5
```
and moved to `%userprofile%\myproject`, where the Excel and Python files can be found. I opened the Excel file, enabled the content (the macros), opened the xlwings tab on the ribbon, and entered `%userprofile%\AppData\Local\conda\conda\envs\py36\python.exe` to the field Interpreter. The Conda Path is where my conda is, `%ProgramFiles%\Anaconda3`, and the Conda Env is `py36`, as it should be. Still, if I click on Run main, I get the following error:
```
Microsoft Visual Basic
Run-time error '53':
Files not found
```
If I open the xlwings.xlam module in the VBA editor, enter the the password xlwings, I am able to debug the code. The debugger says the problem is at the `Utils` Module, in the `ReadFile` function, at the first line of
```
    Open FileName For Input As #FileNum
        Do While Not EOF(FileNum)
            Line Input #FileNum, Token
            Content = Content & Token & LineBreak
        Loop
```

**Comment by fzumstein** [comment]
What's your version of conda (`conda --version`)? A modern version has to be configured via `Conda Path` and `Conda Env`, leaving the `Interpreter` empty. I know, it's a bit confusing right now, but the `xlwings addin install` should have configured this correctly with 0.19.5.

**Comment by danieltuzes** [comment]
Thank you for your fast reply! I have modified those fields in Excel already, so I tried to recreate all the files, but with no success. My conda says:
```
(py36) %userprofile%> conda --version
conda 4.5.4
```

When I tried to recreate the config files, I issued the install command, I've got:
```
(py36) %userprofile%>xlwings addin install
xlwings 0.19.5
Successfully installed the xlwings add-in! Please restart Excel.
There is already an existing config file. Run with --force if you want to overwrite.
```
So I tried to add `--force`, but it didn't work:
```
(py36) %userprofile%>xlwings addin install --force
xlwings 0.19.5
usage: xlwings [-h] {addin,quickstart,restapi,license,config} ...
xlwings: error: unrecognized arguments: --force
```
I still have the same issue with Excel. If I debug the code, it turns out it is looking for a log file called `%userprofile%\AppData\Local\Temp\xlwings-NUMBERS_AND_LETTERS.log`. I hope this helps.

**Comment by fzumstein** [comment]
Your conda version is too old, you'll need at least 4.6 to use the conda settings: https://docs.xlwings.org/en/stable/addin.html#user-settings (yes, it should check for that...)

You need to either upgrade conda or remove the conda settings and simply point to the python executable by putting in the full path into the interpreter setting.

**Comment by danieltuzes** [comment]
I don't have privileges to update conda, but I modified the settings and now it runs, thank you!
