### ISSUE TITLE
Default config file doesn't quote path strings on windows

### ISSUE THREAD

**Issue by RyskiQN** [xlwings/xlwings#1385]
When the default config file when installed fails to quote the C:\path\to\pythonw.exe in the command and so fails to find my interpreter that lies inside Program Files (x86).
I know that I can override this with xlwings.conf sheet but,
1. I can't seem to find documentation on how to do that anywhere
2. I shouldn't have to for something that basic
Any help is appreciated.
Also you probably won't want to tell me but where is the config file, I've been looking for ages because I had a broken one and the --force command suggestion that is printed by xlwings addin install does not exist as an argument I can parse.
Cheers.

**Comment by fzumstein** [comment]
> Also you probably won't want to tell me

That's a relatively strange thought with an open-source project? It's documented here: https://docs.xlwings.org/en/stable/addin.html#user-config-ribbon-config-file

So just to confirm: You didn't have to fix the python path, i.e. did it handled the program files path correctly or not?
