### ISSUE TITLE
Your Conda version seems to be too old for the Conda Settings. Use the Interpreter setting instead.

### ISSUE THREAD

**Issue by zxcvb2000** [xlwings/xlwings#1389]
Windows 10
xlwings 0.20.2
Excel 2019
Python 3.8.5

Hi, I've just done a new install of xlwings. I ran the standard "xlwings addin install" and "xlwings quickstart myproject". When I open "myproject" and click "Run Main" it works fine and "Hello xlwings!" appears.

However, when I run "Import Function" I get the Microsoft Excel error: "Your Conda version seems to be too old for the Conda Settings. Use the Interpreter setting instead."

This laptop has never had Conda installed. I've tried restarting and re-installing and modifying Interpreter paths and UDF Modules etc.

Thanks for your help

![image](https://user-images.githubusercontent.com/69715870/90310833-d6484300-df27-11ea-95c7-1ce68ba7cdac.png)

```
import xlwings as xw

@xw.sub  # only required if you want to import it or run it via UDF Server
def main():
    wb = xw.Book.caller()
    sheet = wb.sheets[0]
    if sheet["A1"].value == "Hello xlwings!":
        sheet["A1"].value = "Bye xlwings!"
    else:
        sheet["A1"].value = "Hello xlwings!"


@xw.func
def hello(name):
    return "hello {0}".format(name)


if __name__ == "__main__":
    xw.Book("myproject.xlsm").set_mock_caller()
    main()
```

**Comment by fzumstein** [comment]
sorry about that, that's now fixed in 0.20.3

**Comment by zxcvb2000** [comment]
Thanks! Works great now :)

**Comment by auggiecat** [comment]
I am on 0.20.4 and just got this error too.  Is it possible it came back with the newest version?

**Comment by fzumstein** [comment]
Can you paste the content of your your config file under `~/.xlwings/xlwings.conf`?

**Comment by auggiecat** [comment]
I am new here so I may not be doing this right - please let me know if this is not where you'd like this posted; 

"CONDA ENV","base"
"CONDA BASE","C:\Users\*********\Anaconda3"
"CONDA PATH","C:\Users\*********\Anaconda3"

the ******* are my full name which I'd prefer not posted here. There is a space between my first and last name - would that cause the issue?

**Comment by auggiecat** [comment]
"CONDA ENV","base"
"CONDA BASE","C:\Users\First Lastname\Anaconda3"
"CONDA PATH","C:\Users\First Lastname\Anaconda3"

**Comment by fzumstein** [comment]
yes, the space was the issue, I've opened a new issue for this (fixed with next release), see #1396

**Comment by fzumstein** [comment]
@auggiecat can you please try again with 0.20.5

**Comment by auggiecat** [comment]
Works thanks!

**Comment by foldmaster** [comment]
I am getting the same error, on version 0.21.4. Has this error crept back in?

Windows 10
xlwings 0.21.4
MS Office Plus Professional 2016
Python 3.6.5

**Comment by fzumstein** [comment]
what is your conda version?

```
(base) C:\Users\felix>conda --version
```

**Comment by foldmaster** [comment]
4.5.4

**Comment by foldmaster** [comment]
4.5.4

**Comment by fzumstein** [comment]
in that case, the message is accurate and not shown erroneously. Conda versions < 4.6 require the path to be set on as Interpreter. I'd recommend you to upgrade conda, but if that's not an option, replace

```
"CONDA PATH","C:\ProgramData\Continuum\Anaconda"
"CONDA ENV","base"
``` 

with 

```
"INTERPRETER_WIN","C:\ProgramData\Continuum\Anaconda\python.exe"
```

I guess the auto-configuration could be improved to check the version of Conda (on the other hand, 4.5.4 is almost 3 years old ;)

**Comment by foldmaster** [comment]
Couldn't upgrade, changing config worked. Thank you!

**Comment by slddnd** [comment]
Getting this error with xlwings 0.20.8 on a fresh conda install version 4.9.2. 
Conda path is c:\Users\jalbg\Anaconda3\python.exe

**Comment by fzumstein** [comment]
Conda Path should just be `c:\Users\jalbg\Anaconda3`

**Comment by slddnd** [comment]
That yields:

---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "\<string\>", line 1, in \<module\>

ModuleNotFoundError: No module named 'MooooTendance_2_00'



Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------


![image](https://user-images.githubusercontent.com/1362060/109882684-8452da80-7c37-11eb-89ee-b185ec774754.png)

**Comment by slddnd** [comment]
Upon further investigation this appears to be related to the OneDrive Path (Issue #1253), and the fix of adding the project to the PYTHONPATH seems to have fixed my issue. Thanks!

**Comment by fzumstein** [comment]
are you on macOS @slddnd? otherwise you shouldn't need to set the PYTHONPATH even with OneDrive, depends also on the version of xlwings.

**Comment by aragaki2003** [comment]
I have also an issue with running the addin in Excel. Either I get "your conda versions seems to be too old..." or "Could not create Python process.
Error message: Access is denied...."

**Comment by goroderickgo** [comment]
I'm also still having this issue, conda 4.11.0, xlwings 0.27.6, Windows 10

Using the interpreter path instead of conda path/env works though, at least in my testing so far.

**Comment by fzumstein** [comment]
@goroderickgo What's the values you've tried for both CONDA PATH and CONDA ENV?

**Comment by hari-rondo** [comment]
Hi there. Am getting this error again now in V0.30.10 and conda V23.7.3. Could you please help. Thanks

**Comment by fzumstein** [comment]
You probably haven't configured the add-in properly. It requires the Conda Path and Conda Env to be set. You can try to run `xlwings config create --force` from the Anaconda Prompt. Otherwise please open a new issue and paste your configuration of the ribbon add-in.

**Comment by hari-rondo** [comment]
Thanks mate. That worked !!!

**Comment by TMA8181** [comment]
Hello,

Having issues calling _python from excel_ from the quickstart project (with same error as original message here). _Python to excel_ works fine.

Below are my env details

- OS: Win 10
- Conda: 4.5.11
- xlwings : 0.29.1
- Excel: 2019

I have tried using both global and local configs.

> "CONDA PATH","C:\Program Files\Anaconda3"
> "CONDA ENV","311"
> "INTERPRETER_WIN","C:\Program Files\Anaconda3\envs\311\python.exe"
> "SHOW CONSOLE","True"


> (311) C:\Projects\code\xlwings\demo>xlwings addin status
> xlwings version: 0.29.1
> The add-in is installed at C:\Users\tma8181\AppData\Roaming\Microsoft\Excel\XLSTART\xlwings.xlam
> Use "xlwings addin remove" to uninstall it.

What am I missing? Are there any debug logs that I can enable to investigate the issue ?

TIA
