### ISSUE TITLE
Range: allow the specification of non-contiguous cell areas 

### ISSUE THREAD

**Issue by fzumstein** [xlwings/xlwings#139]
Like in Excel, e.g. `Range('A1:C3, D1:E5')`

**Comment by pepenu** [comment]
Sorry to bother you Felix, is this still in work? Do you know of a work around to select non-adjacent ranges (columns)?
Thank you so much for your work!

**Comment by fzumstein** [comment]
wow, wasn't aware that this was an open ticket (2015 seems like a long time ago...). No, we decided not to tackle this, so will close this. The workaround is simply to use two statements (or a loop, for that matter):

```
for address in ['A1:C3', 'D1:E5']:
    mysheet[address].value
```

**Comment by pepenu** [comment]
Thank you Felix! Have a great day!

**Comment by Scylla2020** [comment]
You can do this:
`sht.range(sht.range("A1:C3,D1:D5")).value`
