### ISSUE TITLE
xlwings.conf external file not configuring properly

### ISSUE THREAD

**Issue by TidyData** [xlwings/xlwings#1391]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

upgrading from xlwings 0.15.8 to 0.22.3 (problem with 0.22.3)

#### Describe your issue (incl. Traceback!)

Version 0.22.3 on windows 10 seems to not import configurations from xlwings.conf text files in either adjacent `xlwings.conf` file or `%USERPROFILE%/.xlwings/xlwings.conf`  

I do NOT have the addin installed and have been relying on `xlwings.conf` file adjacent to excel files for quite some time.  When I use the `xlwings.conf` tab _within the excel sheet then xlwings works_.  When, I disable the tab and duplicate those settings in `xlwings.conf` file adjacent the excel file then get below error when try and import UDF functions.
```bash
---------------------------
Error
---------------------------
File not found: xlwings64-0.20.3.dll 53
---------------------------
OK   
---------------------------
```
* Using Excel 2013 (15.0.5267.1000) MSO (15.0.5259.1000) 64-bit Part of Microsoft Office Professional Plus 2013  
* Windows version 10.0.17763 Build 17763  

Appreciate your xlwings work!  

Excel Tab name: `xlwings.conf` works and properly activates miniconda virtual environment and runs hello function.  

Interpreter_Win | python
-- | --
Interpreter_Mac |  
PYTHONPATH |  
Conda Path | C:\Users\USERNAME\programming\miniconda3
Conda Env | ENVSHORTNAME
UDF Modules |  
Debug UDFs | FALSE
Use UDF Server | FALSE
Show Console | TRUE

`xlwings.conf` adjacent file or in `%USERPROFILE/.xlwings/xlwings.conf`  **DOES NOT WORK**  
```
"Interpreter_Win",""
"Interpreter_Mac",""
"PYTHONPATH",""
"Conda Path","C:\Users\USERNAME\programming\miniconda3"
"Conda Env","ENVSHORTNAME"
"UDF Modules",""
"Debug UDFs",""
"Use UDF Server",""
"Show Console","TRUE"
```

**Comment by fzumstein** [comment]
possible duplicate of this here? https://github.com/xlwings/xlwings/issues/1388

**Comment by TidyData** [comment]
confirmed duplicate of #1388 thanks, I did search through issues but missed that one.

When using all uppercase config keys then it works for `xlwings.conf` adjacent file.  
```
"INTERPRETER_WIN","python"
"PYTHONPATH",";%USERPROFILE%\programming;"
"CONDA PATH","%USERPROFILE%\programming\miniconda3"
"CONDA ENV","ENVSHORTNAME"
"UDF MODULES",""
"DEBUG UDFS","FALSE"
"USE UDF SERVER","FALSE"
"LICENSE_KEY",""
"SHOW CONSOLE","True"
```
