### ISSUE TITLE
Cannot use the xlwings quickstart

### ISSUE THREAD

**Issue by danieltuzes** [xlwings/xlwings#1394]
#### xlwings: 0.19.5, Excel: 2016, Python 3.7.6
Conda:
```
(base) C:\Users\lenin>conda --version
conda 4.8.3
```

I installed xlwings and created a quickstart project, however, it doesn't work. If the interpreter and PYTHONPATH are filled, it gives the error if I click on Run main. This is shown in the terminal:
```
C:\Users\lenin\anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
xlwings server running, clsid={3DA3B005-5B91-4FDB-A21D-729D7F26D498}
```
And this is the message appearing:
![xlwings-error](https://user-images.githubusercontent.com/6088393/90912458-8dced080-e3d2-11ea-9917-e543f9e1b705.PNG)

If conda path and env are filled, it halts and the terminal says:
`xlwings server running, clsid={9B9EE64D-EA57-4D46-A129-183972FCB228}`
And the Excel window says after a minute:
![xlwings-error-filled-conda-and-env](https://user-images.githubusercontent.com/6088393/90912460-8e676700-e3d2-11ea-8550-e4d61748866b.PNG)

**Comment by fzumstein** [comment]
Ah i misssed this one here: Looks like you're using a version of Excel from the Windows store that is not supported, see #1166

**Comment by danieltuzes** [comment]
No, it is not a version from Windows store. One of them is a corporate version (this was the original purpose) and the other one is on my computer. I am happy to provide further debugging information.
