### ISSUE TITLE
Offset(0,0) API is incorrect

### ISSUE THREAD

**Issue by rudolfbyker** [xlwings/xlwings#1405]
#### OS

Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

- xlwings 0.19.5
- Python 3.8
- Office 365

#### Describe your issue

Offset is not working as expected according to docs at https://docs.microsoft.com/en-us/office/vba/api/excel.range.offset .

It smells like some compensation for Excel's one-indexing vs. Python's zero-indexing is happening where it should not. An offset is an offset, regardless of the type of indexing used.

#### Code sample

```python
import xlwings as xw

wb = xw.Book()
sht = wb.sheets['Sheet1']
print(sht.api.Range('C5').Address)
print(sht.api.Range('C5').Offset(0, 0).Address)
print(sht.api.Range('C5').Offset(0, 0).Offset(0, 0).Address)
wb.close()
```

#### Expected output

```
$C$5
$C$5
$C$5
```

#### Actual output

```
$C$5
$B$4
$A$3
```

**Comment by fzumstein** [comment]
By using `api`, you are using `pywin32`, not xlwings. you should do:

```
import xlwings as xw

wb = xw.Book()
sht = wb.sheets['Sheet1']
print(sht.range('C5').address)
print(sht.range('C5').offset(0, 0).address)
print(sht.range('C5').offset(0, 0).offset(0, 0).address)
wb.close()
```

**Comment by rudolfbyker** [comment]
I have a legitimate use case for the pywin32 API. I did not go into details, so as not to clutter the bug report. I can provide more info if needed.

Are you trying to say that this is in fact a bug in the pywin32 API? Because it's obviously a bug somewhere – I used the API correctly.

**Comment by fzumstein** [comment]
yes: https://bytes.com/topic/python/answers/28170-pywin32-com-problem-excel-range-offset
