### ISSUE TITLE
Can't print to pdf using xlwings

### ISSUE THREAD

**Issue by awa5114** [xlwings/xlwings#1408]
I am trying to use `xlwings` to print out spreadsheets automatically to pdf. I tried using the following code on a blank workbook called `test.xlsx`:

    import xlwings as xw
    
    wb = xw.Book('test.xlsx')
    ws = xw.sheets.active
    ws.range('A1').value = "BLABLABLA"
    wb.api.PrintOut(PrintToFile=True, PrToFileName='test.pdf')
    wb.save('result.xlsx')
    app = xw.apps.active
    app.quit()

However this did not work. The application opens some dialog boxes related to printing to pdf and quits, leaving the dialog boxes behind.

How can I do this fully automated such that excel creates pdfs for me with no manual steps in between?

**Comment by awa5114** [comment]
Anyone?

**Comment by fzumstein** [comment]
You will need to use this instead: https://docs.microsoft.com/en-us/office/vba/api/excel.workbook.exportasfixedformat

It's on the list to be added as as future feature to xlwings.

**Comment by fzumstein** [comment]
closing this as it is a duplicate of #1363
