### ISSUE TITLE
under a pipenv environment a standalone project not working.

### ISSUE THREAD

**Issue by boazdori** [xlwings/xlwings#1410]
Windows 10
 (0.20.7, Office 365, Python 3.8.3)

#### Describe your issue 
I built a standalone project in a pipenv environment. In the environment I have python 3.8.3 and xlwings 0.20.7.
when trying to run the sample code I am getting the following error.

---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "c:\users\user\google drive\excel_settle_compare\excel_settle_compare_proj\excel_settle_compare\excel_settle_compare.py", line 1, in <module>

    import xlwings as xw

ModuleNotFoundError: No module named 'xlwings'

under the config sheet, I gave the Interpereter_Win the python location ........\.virtualenvs\excel_settle_compare_proj-11_IsFMA\Scripts\python.exe"

when running the code from within the .py file the code worked, i.e. produced hello world in the spreadsheet.  The problem occurs when trying to run the code via the macro SampleCode in Excel.
Thanks
Boaz

**Comment by fzumstein** [comment]
Looks like it's not configured with the correct Python environment in Excel.
