### ISSUE TITLE
Date format issue while writing data-frame to excel file using xlwings

### ISSUE THREAD

**Issue by kprabhaahar** [xlwings/xlwings#1413]
i am trying to read a excel file and write it to another excel file using python Xlwings, but in the output1.xlsx excel file if the date value is lesser than 13 then the date and month part are getting interchanged . If the date >=13 then date value is same as input file. When i checked values in the data-frame, it is correct and the issue is happening while writing the dataframe to output1.xlsx file using Xlwings . while using pandas.to_excel(), the value are written to excel in correct format. Please help me with XLWINGS for the writing the data in dataframe to excel without changing date format.

**Issue:**
![image](https://user-images.githubusercontent.com/14325781/92374274-211b3c00-f11d-11ea-858b-29a5f31e5547.png)

**Note:**  1) in the picture left side is input data and right side is output. i have highlighted the wrong data in red color and the date values are less than 13.
                  2) In the input file Alnvalue column is converted to text by using Excel application. i used this step to stop preventing date parsing while reading the input file and convert it to data frame. 

**Expected output using xlwings:**
![image](https://user-images.githubusercontent.com/14325781/92374370-3d1edd80-f11d-11ea-9bf2-628b579acc5a.png)

**Code:**

```
import pandas as pd
import numpy as np
import xlwings as xw
df=pd.concat(pd.read_excel("input.xlsx",sheet_name=None,parse_dates=False,na_filter = False,dtype=str), ignore_index=True)
app = xw.App(visible=False)
# 1st output file using xlwings --> here the date vaues are wrong in output file output1.xlsx
book = xw.Book("output1.xlsx")
sht = book.sheets("Sheet1")
sht.range('A1').options(index=False,dates=False).value=df
book.save()
book.close()
app.quit()

# 2nd output file using pandas to_excel() -->> here the date values are correct
df.to_excel("output2.xlsx",index=False)

```

Input files: [file link](https://drive.google.com/file/d/1FM3lqc8B6hIu5WQOmQQ7qCg8o4GiLvW_/view?usp=sharing)

**Comment by fzumstein** [comment]
Your dataframe will need to have the column of dtype `datetime` to correctly format dates in Excel. A mixed column like you have will have dtype `object` which translates to text in Excel. You can check your dtypes with `df.info()`. Maybe you are better off with working with a nested list instead of a DataFrame where you can make sure the datatypes are of `datetime` before writing it to Excel.

**Comment by kprabhaahar** [comment]
Thanks for the help Felix, issue resolved.

**Comment by ale1397les** [comment]
Hi, can i ask you how you solve the problem? I have a dataframe like yours but it's generate by read_sql
