### ISSUE TITLE
Parsing list to Excel Range

### ISSUE THREAD

**Issue by anberalon** [xlwings/xlwings#1414]
#### Versions of xlwings =  0.11.8, Excel = Office 365 and Python 3.6

According to xlwings doc,

Examples

This VBA function:

Function MySum(x, y)
    MySum = x + y
End Function
can be accessed like this:

>>> import xlwings as xw
>>> app = xw.App()
>>> my_sum = app.macro('MySum')
>>> my_sum(1, 2)
3

As the VBA function Module1.BuildBootstrappingParameters expects to receive an Excel Range for the parameters self.pillar and self.weight, is it possible to format them as this type of object? In Python the variables are defined as list types.

#### Code sample

```python

BuildBootstrappingParameters = app.macro('Module1.BuildBootstrappingParameters')

class IR_Curve(object):

    def __init__(self, name, interp, index, disc_flow, zc_conv, generator, tenor, weight):
        self.name = name
        self.interp = interp
        self.index = index
        self.disc_flow = disc_flow
        self.zc_conv = zc_conv
        self.generator = generator
        self.tenor = tenor
        self.weight = weight
        self.product = [CreateProductsFromGenerators(i, j)[0][0] for i, j in zip(generator, tenor)]
        self.start_date = [GetProductsStartAndEndDates(i)[0][0] for i in self.product]
        self.pillar = [GetProductsStartAndEndDates(i)[0][1] for i in self.product]
        self.day_count = [i - j for i, j in zip(self.pillar, self.start_date)]

    def BuildBootstrappingParameters(self, solver_name='fsolve', solver_tol=1E-10, glob_tol=None, toy_index=None,
                                        toy_jump=0, toy_n=1, cfg_empty=None):
        self.bt_prob_param = BuildBootstrappingParameters(self.name, solver_name, solver_tol, self.zc_conv,
                                                                 glob_tol,  self.pillar, toy_index, toy_jump, toy_n,
                                                                 cfg_empty, False, self.weight)
        return self.bt_prob_param

**Comment by fzumstein** [comment]
`macro` accepts instances of type `App, Book, Sheet, Range, Shape, Picture, Name` which will be converted into the corresponding VBA object.

**Comment by anberalon** [comment]
Thanks for your reply.

Actually, what we need is:

Initially, in our code we have created a Python list variable. And then, we would like to call a VBA function via xlwings. This VBA function is expected to receive this variable mentioned as an Excel Range.

If we send this parameter as a Python list (without any transformation) to VBA function via xlwings, it doesn't work as expected.

Is there any way to do that?

**Comment by fzumstein** [comment]
you'd need to send an xlwings Range object

**Comment by anberalon** [comment]
Ok thanks for your help!

**Comment by fzumstein** [comment]
See: https://docs.xlwings.org/en/stable/quickstart.html or https://docs.xlwings.org/en/stable/api.html#range

**Comment by anberalon** [comment]
Thanks, but the input parameter that need to be passed to the VBA function (via xlwings > macro) is created in Python directly (i.e. it is not in any Excel Sheet). 

`self.pillar = [GetProductsStartAndEndDates(i)[0][1] for i in self.product]`

So, I can't use xw.Range(<Excel Range>).

**Comment by fzumstein** [comment]
reading this again, I think sending over a Python list should give you an array in VBA that you can loop through...
