### ISSUE TITLE
Desperately need code to scrap Linkedin post comments with nested comments using xlwings from Excel. 

### ISSUE THREAD

**Issue by jaryszek** [xlwings/xlwings#1417]
#### Describe your issue (incl. Traceback!)
hI,

Need code to get Linkedin's post comment object and find out how many comments there are. And if i am the author or not. 
How to check if via Excel and Xlwings. What library to choose? 

I thought to use xlwings and beautiful soap but i do not know if i have to load first all comments from specified post. 
Can anybody help how to start or provide simple sample?

Thanks!
Jacek

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
Hi @jaryszek, the issue tracker is for bug reports and feature requests for xlwings. StackOverflow may be a better place to ask questions like these.
