### ISSUE TITLE
on drawing chart title, error：pywintypes.com_error: (-2147352567, '发生意外。', (0, None, None, None, 0, -2147024891), None)

### ISSUE THREAD

**Issue by haorongLemon** [xlwings/xlwings#1419]
OS：Win7 Vista

software：xlwings=0.20.7 , WPS 2019（personal edition） and Python 3.8

#### Describe your issue (incl. Traceback!)
on running program, error occured: 
       pywintypes.com_error: (-2147352567, '发生意外。', (0, None, None, None, 0, -2147024891), None)
      the word ‘发生意外’ means unexptected.

```python
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/pythonProject/main.py", line 27, in <module>
    chart.api[1].ChartTitle.Text = i  ########  crash here.
  File "D:\toolchain\Python38\lib\site-packages\xlwings\_xlwindows.py", line 122, in __getattr__
    v = getattr(self._inner, item)
  File "D:\toolchain\Python38\lib\site-packages\win32com\client\dynamic.py", line 516, in __getattr__
    ret = self._oleobj_.Invoke(retEntry.dispid,0,invoke_type,1)
pywintypes.com_error: (-2147352567, '发生意外。', (0, None, None, None, 0, -2147024891), None)

Process finished with exit code 1


```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import xlwings as xw

app = xw.App(visible=True, add_book=True)
wb = app.books.active
sht = wb.sheets.active
# chart data
sht.range('A1').value = [['time', 'count'], ['一', 2], ['二', 1], ['三', 3], ['四', 4], ['五', 5], ['六', 6]]

dic ={
    'column_stacked_100': 53,
    'doughnut': -4120,
    'doughnut_exploded': 80,
    'line': 4,
    'line_markers': 65,
}
w = 385
h = 241
n = 0
x = 100
y = 10
for i in dic.keys():
    xx = x + n % 3 * w  # make x position
    yy = y + n // 3 * h  # make y position
    chart = sht.charts.add(xx, yy)
    chart.set_source_data(sht.range('A1').expand())
    chart.chart_type = i
    chart.api[1].ChartTitle.Text = i              ########  crash here.

    n += 1
wb.save('chart')
wb.close()
app.quit()


```

if i masked the sentence "chart.api[1].ChartTitle.Text = i ",  it's  running ok, but i can't set title for the chart。in china, most people use WPS Office(personal version) rather than MS Office, is that xlwings does not support for WPS?

i also change the args "Excel.Application" to "KET.Application" in _xlwinows.py(this solution find in baidu search engine):
```python
class App:  
    def __init__():
          ...  
         self._xl = COMRetryObjectWrapper(DispatchEx('Excel.Application')))  # change  to "KET.Application"
```

it's not worked too, but debug show 'app.api'  is  "COMObject KET.Application"，  but 'chart.api' is  (“COMObject Add", "COMObject unknown"), the words 'unknow' make me confusing...

**Comment by fzumstein** [comment]
It does work with Excel as expected, so I am afraid, not much we can do here as we don't support KET as it's not 100% compatible. The error message means: 

```
>>> import win32api
>>> win32api.FormatMessage(-2147024891)
Access is denied.
```

Maybe the object model is slightly different for charts with KET, but I really don't know.
