### ISSUE TITLE
Run-time error '1000': Could not create Python process. Error message: Access is denied

### ISSUE THREAD

**Issue by person142857** [xlwings/xlwings#1420]
#### Versions of xlwings, Excel and Python (0.20.7, Office 365, Python 3.7.9)

Hello, I'm trying to run a macro using xlwings.  For this particular example I'm trying to run the fibonacci.xlsm example, but I get the same error trying to run my own macros.  When I run with the "RunPython: Use UDF Server" box checked I receive the following error:
"""
Run-time error '1000':

Could not create Python process.
Error message: Access is denied.

Command: cmd.exe /K
""C:\Users\User\Anaconda3\condabin\conda" activate base
&& pythonw -B -c "import sys,
os;sys.path[0:0]=os.path.normcase(os.path.expandvars(r'C:\Users\U
"""

If I run without the  "RunPython: Use UDF Server" box checked I get the following error:
"""
Run-time error '70':

Permission denied
"""

For both I also get a Windows Security popup that says:
"""
App or process blocked: EXCEL.EXE

Blocked by: Attack surface reduction
Rule: Block all Office applications from creating child processes

Affected items: C:\Windows\System32\cmd.exe
"""

I've talked to our IT guy and he says he hasn't implemented any additional security protocols.  I've checked the "Trust access to the VBA project object model".  I've tried running with and without the "RunPython: Use UDF Server" option checked and with and without the "Debug UDFs" option checked and none of it will run.   Can someone please help? Thanks!

**Comment by fzumstein** [comment]
Hi, this looks like a Windows Defender issue which unfortunately sometimes comes up, see https://github.com/xlwings/xlwings/issues/1370 at the bottom for how to allow running the macros.

**Comment by person142857** [comment]
Thanks fzumstein. I concur seems to be a Windows Defender issue.  Unfortunately I don't have the "allow" option in the Windows Security > Protection History.  I tried making the file location a trusted location per the Microsoft support link, but that didn't work either.  I'm not sure how open my organization will be to changing the Attack surface reduction rules for Windows Security.  Are there any more work arounds for this issue?

**Comment by fzumstein** [comment]
I have already tried to sign the VBA code and that didn't seem to make any difference either. I am also not sure if it's only after a new release that it causes troubles. Will try to investigate.

**Comment by fzumstein** [comment]
I didn't find a solution here.

**Comment by aaronrongan** [comment]
I meet the same probem today. After several trials, I found reinstall addin in Excel ribbon is ok for my case.

Just type in command line: "xlwings addin install".
