### ISSUE TITLE
xlwings equivalent of "CTRL+SHIFT+DOWN"

### ISSUE THREAD

**Issue by MarekSevela** [xlwings/xlwings#1422]
Hello,

is there please a way to simulate cells selection that would select the whole column range from a desired position?

I cannot use any looping as my sheet contains a lot of data. Doing this through simple .select() + .erase() would do the job with desired speed.

Thank you very much for the guiedence on this!

Best regards,

MS

**Comment by ericbmoreira** [comment]
Does .expand() do what you need?
https://docs.xlwings.org/en/stable/converters.html

**Comment by MarekSevela** [comment]
Hi,

this is a bit different from what I would need.
I need to simply select all the cells down from the selected cell and delete them.
Equivalent in VBA would be:    Range(Selection, Selection.End(xlDown)).Select

Is there maybe a way this could be achieved through .api?

I have some additional looping set up around this which kind of forces me to choose this approach only.

**Comment by fzumstein** [comment]
what about `.expand('down')`? Too slow?

**Comment by MarekSevela** [comment]
Got it! Thank you guys, just had to play with .expand() a bit more.
Keep a good work with xlwings going, I quite like it, using it more and more. :)

Cheers!
