### ISSUE TITLE
Excel UDF returns a pandas dataframe as Excel {array} by default - a new behavior?

### ISSUE THREAD

**Issue by rutsyi** [xlwings/xlwings#1423]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 7.
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Python 3.8.5 / xlwings 0.20.7 / Excel 2010 14.0.7257.5000
#### Describe your issue (incl. Traceback!)
I was using a pretty old xlwings version before (can't find the version number, dates back 4 years). Recently updated to 0.20.7. I have a UDF called `MDS_GET_GR_DIV` that returns a pandas DataFrame:
```python
@xw.func
@xw.arg('mark_date', dates=dt.datetime)
@xw.arg('start_dt', dates=dt.datetime)
@xw.arg('end_dt', dates=dt.datetime)
@xw.ret(expand='table', index=False)
def MDS_GET_GR_DIV(class_name, undrl, label, start_dt, end_dt=None, mark_date=None):
    #  MDS_GET_GR_DIV is a wrapper for misc.mds_getgrdiv()
    div_tbl = misc.mds_getgrdiv(class_name, undrl, label, engine, start_dt, end_dt, mark_date)
    return div_tbl
```
What I saw before was the returned dataframe was just copied to cells in my sheet right below where I entered the UDF `=MDS_GET_GR_DIV(<params>)`. The resulting table was *editable*, each cells could have been removed/changed.
The new behavior I see is the *formula now returns an Excel array {}*, which is obviously non-editable. Nothing has changed in my Python code. The only thing that changed was updated xlwings and its addin.

Is this a return-as-excel-{array} a new type of behavior? Could it be overriden anyhow? I would like to have a possibility to edit the cells that get returned from the UDF.

Thank you!

**Comment by fzumstein** [comment]
Yes, that was introduced 2 years ago with https://docs.xlwings.org/en/stable/whatsnew.html#v0-15-0-nov-20-2018 - and I can't remember that anybody else has ever complained about the new behavior, whereas many users complained about the previous mechanics. The behavior you see is consistent with the new native dynamic arrays in Office 365. For the functionality you want, you could use a button that writes back an array as values to cells. Then you can do whatever you want with them.

**Comment by rutsyi** [comment]
Hi @fzumstein , thank you for your quick reply and appreciate your work.
I guess I will need to find a workaround, yes. That is no problem.

Just a bit of more background, maybe will be useful to others.
My output table is of variable number of rows = can grow or downsize. So if one day it is 10 rows, the next day it can be 7 rows. I need to clear the contents of the table in the beginning of the 2nd day because if I don't then on the 2nd day my table will be still 10 rows: 7 rows are new, 3 rows won't be erased or overriden so will stay there from the previous day.

Now with Excel {array} I cannot easily delete the table contents to override them with the new day's data because {array} in Excel is immutable.

I could delete the whole table including the formula now. But now I need to remember the formula before deleting it. And then reapply it into the same cell to generate another new day's {array} -- I guess I will make it the solution.

Best regards.
Cheers.

**Comment by fzumstein** [comment]
Not sure I follow: when you recalculate the formula and the returned array is smaller, it will resize the array automatically with `expand='table'`, even if the output is a CSE array.

**Comment by fzumstein** [comment]
Yes, that's not expected. Please play around with the `dynamic_array` sample here: https://github.com/xlwings/xlwings/tree/master/tests/udfs  to see if that works for you or - even better: upgrade your Excel to be able to use the new native dynamic arrays: https://www.xlwings.org/blog/dynamic-arrays-in-excel ;)

**Comment by rutsyi** [comment]
Hi @fzumstein , will do. The `dynamic_array` won't need office365, correct?
Updating not an options unfortunately :). Will break many more things.
Thank you again.

**Comment by fzumstein** [comment]
correct, they work with legacy arrays.

**Comment by rutsyi** [comment]
Got you, cheers.
