### ISSUE TITLE
Does the CE version also include the pro sub package?

### ISSUE THREAD

**Issue by StephanSong** [xlwings/xlwings#1426]
#### Windows 10
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.20.7
Office 365
Python 3.8.6

#### Describe your issue (incl. Traceback!)
I installed the xlwings via command pip install xlwings

When I ran python code from excel via RunPython macro, I always got an error. It said that I encoutered a license problem. 
Then I checked the installation folder for xlwings, I found the pro subpakcage in it. 

How can I fix the problem?

I can't run python from excel and the RunMain button doesn't work any more. 

```python

---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "c:\users\steph\appdata\local\programs\python\python38\lib\site-packages\xlwings\pro\__init__.py", line 9, in <module>

    from .embedded_code import runpython_embedded_code

  File "c:\users\steph\appdata\local\programs\python\python38\lib\site-packages\xlwings\pro\embedded_code.py", line 11, in <module>

    LicenseHandler.validate_license('pro')

  File "c:\users\steph\appdata\local\programs\python\python38\lib\site-packages\xlwings\pro\utils.py", line 51, in validate_license

    key = LicenseHandler.get_license()

  File "c:\users\steph\appdata\local\programs\python\python38\lib\site-packages\xlwings\pro\utils.py", line 46, in get_license

    raise LicenseError("Couldn't find a license key.")

xlwings.LicenseError: Couldn't find a license key.


```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python

Sub run_code()

    Dim codes As String
    
    codes = "import xlwings as xw"
    
    RunPython codes
    

End Sub

I just run this from excel. I failed and got the above message.
```

**Comment by fzumstein** [comment]
Hi @StephanSong, is it possible that you have a sheet with a `.py` ending? In that case, it expects a valid license. Other than that, you shouldn't notice the pro package when you don't need it (or it would be a bug). Feel free to upload the code and Excel file (best in a zip file) so I can take a look.

**Comment by StephanSong** [comment]
@fzumstein  I checked the excel sheet. You are right. There is a sheet with .py ending. Thanks.
