### ISSUE TITLE
Can use xlwings PRO at my company PC if my company buys the individual license for me?

### ISSUE THREAD

**Issue by StephanSong** [xlwings/xlwings#1427]
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
Yes, sure. xlwings PRO is a developer license, which means that it is tied to a person (no matter whether that's in a company or not). You will be able to deploy your tools to unlimited end users by generating a `deploy_key` via `xlwings license deploy`. Unlike the developer's license, the deploy key doesn't expire after a year but in return is bound to the version of xlwings you used to generate the deploy key.

**Comment by StephanSong** [comment]
Got it. Thanks.
