### ISSUE TITLE
Cannot get rid of header/indexes while parsing dataframe between xlwings defined sheets.

### ISSUE THREAD

**Issue by MarekSevela** [xlwings/xlwings#1428]
Hi,

i am struggling to get some basic data manipulation with pandas when applying to xlwings defined sheets.

I basically need to filter the data set for all the lines that have previous month date in column O ("Month")

I managed that by doing:
```
today = datetime.date.today()
first = today.replace(day=1)
lastMonth = first - datetime.timedelta(days=1)
previousMonth=lastMonth.strftime("%m %Y")
```
```
df=pd.read_excel('G:\AR\REPORTS\Automation Files\KPI Nihan Update\KPI_Aging TEST.xlsx', "Raw_Data",index=None,header=None)

`filteringData=df['Month']==previousMonth`
```

Now all I need is to take filteringData and parse it to the next sheet like so:

`KPI_Aging_Workbook.sheets['TEST'].range('A1').value=filteredData`

However, the data come with header and indexes like this:

![obrazek](https://user-images.githubusercontent.com/61273753/95317634-baad4900-0895-11eb-8bd7-d02539ccc41f.png)

I know I can get rid of headers and indexes through something like:

`filteredData2.to_excel('G:\AR\REPORTS\Automation Files\KPI Nihan Update\KPI_Aging TEST.xlsx','TEST',index=False, header=None)`

but this option destroys the previous sheet and leaves me only with the data itself. I also cannot apply index, header = False to pd.read_excel because I need that header for the "Month" filtering.

By now I am seriously stuck on this, would you guys know how I can resolve this? I am also open to using .api to get some of the VBA functions on board. something that would be of equivalent to this:

```
ActiveSheet.Range("$A$2:$X$259").AutoFilter Field:=3, Criteria1:= _
        "Month"

LR = Range("A" & Rows.Count).End(xlUp).Row

Range("A2:X" & LR).SpecialCells(xlCellTypeVisible).Select
```

Would prefer pandas solution, though.

Thank you very much!

**Comment by fzumstein** [comment]
Use the options method, see https://docs.xlwings.org/en/stable/converters.html#pandas-dataframe-converter:

```python
KPI_Aging_Workbook.sheets['TEST'].range('A1').options(header=False, index=False).value=filteredData
```
