### ISSUE TITLE
Antivirus software Bitdefender identifies component as Trojan

### ISSUE THREAD

**Issue by nikblanchet** [xlwings/xlwings#1432]
#### OS (e.g. Windows 10 or macOS Sierra)
macOS Catalina version 10.15.7 (19H2)

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Component | Version
--------- | -------
`xlwings` | 0.20.7
Excel | _Not installed_
Python | 3.8.5

#### Describe your issue (incl. Traceback!)
_Note: This seems similar to [an issue reported by another user](https://github.com/xlwings/xlwings/issues/1250), though the OS, xlwings version, and detection software are all different._

I received the following message from [Bitdefender Antivirus for Mac](https://www.bitdefender.com/) (Version  8.2.2.9).
```
An infected file attempted to run on your device.
Threat name: Trojan.GenericKD.34699063
Path: /Users/Nik/anaconda3/pkgs/xlwings-0.20.7-py38_0/lib/python3.8/site-packages/xlwings/addin/xlwings.xlam=>xl/vbaProject.bin
We deleted the file to prevent malicious commands from being executed on your device.
```
I attempted to resolve this by running the following.
```bash
conda update --force-reinstall xlwings
```
But I received the following output, which includes an error message.
```
Preparing transaction: done
Verifying transaction: / 
SafetyError: The package for xlwings located at /Users/Nik/anaconda3/pkgs/xlwings-0.20.7-py38_0
appears to be corrupted. The path 'lib/python3.8/site-packages/xlwings/addin/xlwings.xlam'
has an incorrect size.
  reported size: 53481 bytes
  actual size: 8697 bytes


done
Executing transaction: done
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
To reproduce, do the following.

1. Install Bitdefender Antivirus for Mac.
2. [Install Anaconda](https://docs.anaconda.com/anaconda/install/mac-os/#using-the-command-line-install). I used the command-line instructions.
3. Update conda
    ```bash
    conda update conda
    ```
4. Update all packages
    ```bash
    conda update --all
    ```

**Comment by pineappleburger** [comment]
I have the exact same problem with an identical message by Bitdefender. I have the same versions of xlwings and python as above. The problem only occured after I updated the package in a project conda environment, everything works fine in my conda root environment.

macOS Catalina 10.15.7
Bitdefender Virus Scanner 3.15.269

**Comment by fzumstein** [comment]
The Excel add-in and virus scanners can be an issue as the add-in makes a shell call which by default many virus scanners categorize as malicious. Every anti-virus software has an option though to a) whitelist certain applications and b) submit false positives. In the case of Bitdefender, you can read about the process here: https://www.bitdefender.com/support/what-to-do-when-bitdefender-detects-legitimate-applications-491.html

**Comment by fzumstein** [comment]
In your case @nikblanchet, it's even more extreme, as it was deleting the addin file from the python package installation folder without you even trying to run it from Excel. That's why conda then choked on it. You should be able to delete the `xlwings` folder from your `site-packages` folder before re-installing it again. Since you state that you don't have Excel installed: in that case, xlwings, won't help you much as it depends on an installation of Excel...

**Comment by pineappleburger** [comment]
@fzumstein, thanks for your fast reply and the helpful link! I didn't know about the possibility to submit false positives, I'll do just that.

**Comment by nikblanchet** [comment]
I've submitted the file as a false positive w/ bitdefender, but since I don't have an enterprise support account, I had to use a different URL: https://www.bitdefender.com/submit.

The file I submitted was `/Users/Nik/anaconda3/pkgs/xlwings-0.20.7-py38_0/lib/python3.8/site-packages/xlwings/addin/xlwings.xlam` because I don't know what the `=>xl/vbaProject.bin` part meant. (Thinking it might be a separate file, I ran `echo **/*vbaProject.bin*` from `/` in zsh, but no matches were found.)

**Comment by nikblanchet** [comment]
Either due to a change in xlwings moving to version `0.20.8` or Bitdefender updating its detection engine (hopefully in response to opening an issue with them), I am able to install xlwings without intervention from Bitdefender Antivirus for Mac!

**Comment by actuary87** [comment]
> The Excel add-in and virus scanners can be an issue as the add-in makes a shell call which by default many virus scanners categorize as malicious. Every anti-virus software has an option though to a) whitelist certain applications and b) submit false positives. In the case of Bitdefender, you can read about the process here: https://www.bitdefender.com/support/what-to-do-when-bitdefender-detects-legitimate-applications-491.html

Below is way to avoid virus scanners annoying warnings/popus for each shell call:
1. UnCheck Debug UDFs (xlwings addin)
2. UnCheck RunPython: Use UDF Server (xlwings addin)
3. Copy the output of the following formula "=XLPyCommand()" into a cmd/bat file
4. Check Debug UDFs (xlwings addin)
5. Check RunPython: Use UDF Server (xlwings addin)
6. Re-evaluate "=XLPyCommand()" formula. It should produce a fixed CLSID (the one used for debugging, mine is {506e67c3-55b5-48c3-a035-eed5deea7d6d} but I guess it is everyone's too)
7. Replace "$(CLSID)" (without quotes) in the cmd/bat file with the debug CLSID
[Optional] If you are behind a proxy and need to connect to the internet then add the following to the top of your cmd/bat file:
set http_proxy=proxyaddress:port
set https_proxy=proxyaddress:port

Note: requests package under python 3.9 likes the proxyaddress to be preceded with http:// or https:// depending on the proxy server protocol under use.
