### ISSUE TITLE
xlwings on jupyterhub?

### ISSUE THREAD

**Issue by tomnewg** [xlwings/xlwings#1437]
Hi everyone,

first things first, xlwings is one of the best tools out there. Thank you so much for this!

Is there a way to run xlwings on a jupyterhub or is this just not possible because Excel is not installed on the server? I have a few notebooks that require xlwings to open an excel file for the user to enter and change data in excel. The jupyter notebook is shared with users on a jupyterhub. If there is no workaround with xlwings, is there any other solution that would solve this issue?

Many thanks

Tom

**Comment by fzumstein** [comment]
Hi Tom, there's nothing wrong with using xlwings on a jupyterhub as such (if you run it locally, for example) but as you correctly guessed, xlwings automates Excel, so will need an installation of Excel. The options you have that don't require Excel are OpenPyXL and other reader/writer packages, depending on your needs.

**Comment by tomnewg** [comment]
Thank you for your answer. My issue is that I need to open an instance of Excel as the user needs to be able to alter data in the sheet which feeds back to the code. The jupyterhub is run on an ubuntu sever as the users need to have access over the internet. Do you have any idea how to solve this? 

1. Can I install an excel version on an Ubuntu server? (probably not)


1. 

So I have two options I think. I either:

- install Excel on the server where jupyterhub is run which is an ubuntu 

- Do you know of any libraries that would work as an alternative to excel?

**Comment by tomnewg** [comment]
Thank you for your answer. My issue is that I need to open an instance of Excel as the user needs to be able to alter data in the sheet which feeds back to the code. The jupyterhub is run on an ubuntu server as the users need to have access over the internet. Do you have any idea how to solve this? Things that I was thinking of:

Can I install an excel version on an Ubuntu server? (probably not possible)
Or use a different python library that mimics excel i.e. displays a panda dataframe and allows users to alter/input data - Do you know any good library for this?

In general, do all xlwings users run their code on the localhost? you must have had use cases when people want to use xlwings on a server?

Many thanks for your help

Tom

**Comment by fzumstein** [comment]
xlwings is to locally automate Excel, yes. You can make it run on a Windows server, but not on Ubuntu. You can look into LibreOffice, they have Python bindings or probably better have a look into Jupyter widgets, maybe something like this: https://github.com/quantopian/qgrid
