### ISSUE TITLE
How to use VBA's inputbox function

### ISSUE THREAD

**Issue by YesHub** [xlwings/xlwings#1439]
Ask how to use inputbox function and parameters。
xw.books.api.inputbox() Is that right? How to fill in the parameters?
thank you all！

**Comment by fzumstein** [comment]
You'd need to follow the docs here: https://docs.microsoft.com/en-us/office/vba/api/excel.application.inputbox

I.e. it's part of the `Application` object. Something in this direction:

```python
import xlwings as xw

wb = xw.books.active
mytext = wb.app.api.InputBox('enter a string', Type=2)
print(mytext)
```

**Comment by YesHub** [comment]
@fzumstein Thank you very very much!!
