### ISSUE TITLE
Include usage of "MsgBox" for UI alerting functionality

### ISSUE THREAD

**Issue by furritos** [xlwings/xlwings#144]
An enhancement to include MsgBox functionality

**Comment by fzumstein** [comment]
Windows: 

```
import xlwings as xw
import win32api

wb = xw.Workbook.active()
win32api.MessageBox(wb.xl_app.hwnd, "test")
```

**Comment by timrichardson** [comment]
or >=0.9
`win32api.MessageBox(wb.app.hwnd, "test")`

**Comment by jaymegordo** [comment]
Would be nice to have MsgBox functionality added to xlwings for both windows and mac!

**Comment by fzumstein** [comment]
closing if favor of #756
