### ISSUE TITLE
UDF that creates a new worksheet

### ISSUE THREAD

**Issue by Anubis93** [xlwings/xlwings#1442]
I'm working on a windows computer and want to create an UDF, that creates a new worksheet in my workbook. 
I tried it as followed

@xw.func
def new_worksheet():
    xw.Book.caller().sheets.add()
    return 'Done'

but it does not work even though in my opinion it should.  It returns the return value but does not add the new sheet. 

(working with the xlwings version 0.20.8)

**Comment by fzumstein** [comment]
UDFs don't support that kind of functionality, see: https://stackoverflow.com/questions/43146941/worksheets-add-in-udf-not-working
Adding a picture like it's done [here](https://docs.xlwings.org/en/stable/matplotlib.html#full-integration-with-excel) is an exception.
