### ISSUE TITLE
Change value from drop down list

### ISSUE THREAD

**Issue by kkumawat25** [xlwings/xlwings#1446]
My workbook cell contain a drop down list, how I can change value to be displayed in the same cell from dropdow list ? Cell is currently showing value a and contains dropdown list [a, b,c] , I want to display b in the same cell using xlwings.
Thanks a lot for your time.

**Comment by fzumstein** [comment]
Can you provide a screenshot to see which dropdown you're using?

**Comment by kkumawat25** [comment]
![16043814404109052479948943136935](https://user-images.githubusercontent.com/54132236/97952555-d851cd80-1dc3-11eb-8686-ea7bde5ce0a6.jpg)
Column C is dropdown list, it is created by using a excel formula that takes all the rows in another column (Let say Column J) and Column C shows most recent row. When new row is added Column J,  Dropdown list in column C is updated but I also want to update value shown in column C as most recent.

**Comment by fzumstein** [comment]
this is done via data validation, correct? Can't you just set the value of that cell, i.e. `mysheet['C4'].value = datetime(...)` ?

**Comment by kkumawat25** [comment]
Yes, it is done by data validation in excel. In xlwings, I want to read all values of dropdown and covert into date time then sort it and then set cell values as second Last date. How to read all values of dropdown using xlwings ?

**Comment by fzumstein** [comment]
Simply read in the range from where you populate the data validation drop down (your column J).

**Comment by kkumawat25** [comment]
Thank you , it works. I have one additional question, How I can save already existing chart in a sheet chart into a image file ? WB.sheet.charts['chart1'].api[1]. export ('img.png') creates empty file.

**Comment by scraja** [comment]
Folks - New to XLWings. 
Is there a way to actually add the data validation to a column programmatically using XLWings?

**Comment by fzumstein** [comment]
The solution is a combination of
* https://docs.xlwings.org/en/stable/missing_features.html
* https://docs.microsoft.com/en-us/office/vba/api/excel.validation.add

and in your case looks something like this (assuming you have a list of in range `A1:A3` and want to add validation in cell `C1`:

```python
import xlwings as xw
from xlwings.constants import DVType

book = xw.books.active
sheet = book.sheets.active
sheet['C1'].api.Validation.Add(Type=DVType.xlValidateList, Formula1='=A1:A3')

```

**Comment by jithuvp** [comment]
@fzumstein  `sheet['C1'].api.Validation.Add(Type=DVType.xlValidateList, Formula1='=A1:A3')` isn't working for me in mac. I get an error: `AttributeError: Unknown property, element or command: 'Validation'`. I tried a more pythonic way by using "validation.add"; that didn't work either. What am I doing wrong here? Please advise.

**Comment by fzumstein** [comment]
@jithuvp, on macOS you're writing `appscript` code via `.api`, not `pywin32`. Something like this should work:

```
from appscript import k
sheet['C1'].api.validation.add_data_validation(type=k.validate_list, alert_style=k.valid_alert_stop, formula1='=$A$1:$A$10')
```

**Comment by fzumstein** [comment]
Feature request added under https://github.com/xlwings/xlwings/issues/1868

**Comment by Joydeep4** [comment]
> Thank you , it works. I have one additional question, How I can save already existing chart in a sheet chart into a image file ? WB.sheet.charts['chart1'].api[1]. export ('img.png') creates empty file.

-- COuld you please help me with this? I need to validate a cell which contains dropdown list. can you share steps? I am new to 
xlwings

**Comment by fzumstein** [comment]
is it a chart on a worksheet or a chartsheet?

**Comment by circlelee1981** [comment]
when i run 'sh.api.validation.add(Type=DVType.xlValidateList, Formula1='=A20:b20')', error as below:

**Comment by circlelee1981** [comment]
when i run 'sh.api.validation.add(Type=DVType.xlValidateList, Formula1='=A20:b20')', error as below:

v = getattr(self._inner, item)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\flx\AppData\Local\Programs\Python\Python312\Lib\site-packages\win32com\client\__init__.py", line 582, in __getattr__
    raise AttributeError(
AttributeError: '<win32com.gen_py.Microsoft Excel 15.0 Object Library._Worksheet instance at 0x2709894971312>' object has no attribute 'validation'. Did you mean: 'Application'?

During handling of the above exception, another exception occurred:

**Comment by fzumstein** [comment]
capitalization matters, Validation and Add need to be capitalized

**Comment by madainigun14** [comment]
> The solution is a combination of
> 
> * https://docs.xlwings.org/en/stable/missing_features.html
> * https://docs.microsoft.com/en-us/office/vba/api/excel.validation.add
> 
> and in your case looks something like this (assuming you have a list of in range `A1:A3` and want to add validation in cell `C1`:
> 
> ```python
> import xlwings as xw
> from xlwings.constants import DVType
> 
> book = xw.books.active
> sheet = book.sheets.active
> sheet['C1'].api.Validation.Add(Type=DVType.xlValidateList, Formula1='=A1:A3')
> ```


my python version is 3.9.8, here is the code:

`range1.api.Validation.Add(xlwings.constants.DVType.xlValidateList, formula1="=A1:A10")`

but error as following:

{TypeError} Add() got an unexpected keyword argument 'formula1'

so, how to code correctly in python?

**Comment by fzumstein** [comment]
You may need to use named params (and yes, capitalization matters). So also say `Type=...`

**Comment by johodh** [comment]
@fzumstein Thanks for your quick reply. I just noticed it actually does work, even though i still get the error message the drop down appears. If someone else runs in to the problem: i managed to suppress the error message with a simple try/except (code below), and now it works as expected. 

```
try:
   sheet['C1'].api.Validation.Add(Type=DVType.xlValidateList, Formula1='=A1:A3')
except: 
   pass
```
