### ISSUE TITLE
xlEdge not exist Borders in four directions param

### ISSUE THREAD

**Issue by stevenling** [xlwings/xlwings#1448]
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here

```
xlEdgeBottom = 9  # from enum XlBordersIndex
    xlEdgeLeft = 7  # from enum XlBordersIndex
    xlEdgeRight = 10  # from enum XlBordersIndex
    xlEdgeTop = 8  # from enum XlBordersIndex

If I want to four directions. I must wirte four line. But I want to one Line. 

In vba just one line.
 Sheets(resWorkTableName).Range("A1" ).Borders.LineStyle = xlContinuous

**Comment by fzumstein** [comment]
This should do (with `mysheet` being your xlwings sheet object):

```
import xlwings as xw
from xlwings.constants import LineStyle

mysheet['A1'].api.Borders.LineStyle = LineStyle.xlContinuous
```

**Comment by stevenling** [comment]
Thank you very much. It is can achieve my goal

**Comment by ethannluong** [comment]
I was trying to only have the bottom border, so I tried using BordersIndex. It gets stuck at the line where I set the BordersIndex to xlEdgeBottom. I have it just like above but with BordersIndex. I tried LineStyle and that works fine but not BordersIndex.
