### ISSUE TITLE
Get values of separate cells

### ISSUE THREAD

**Issue by spar7453** [xlwings/xlwings#1452]
Can I get values of separate cells?

for example)

```python
range("A1,C1,XA1").value
range("A1:A3,XF1:XF3").value
```

or
```python
range(["A1", "C1", "XA1"]).value
range(["A1:A3", "XF1:XF3"]).value
```

I am looking for this feature since calling lots of range.value makes slow and calling huge table (in this case A1:XA1 or A1:XF3) at once seems unnecessary

**Comment by ericbmoreira** [comment]
What are you trying to do with them? You could have each one as a variable 
and then do what you need with them.

**Comment by spar7453** [comment]
I have quite large dataframe and I only need some columns (say columns A, AA, XA, AAA and so on).

Loading whole dataframe is unnecessary but using lots of range().value makes calculation slow

**Comment by ericbmoreira** [comment]
I use a named range for each column when I do something like that, and then 
concatenate it. Don't select the whole column or yes, it will be huge.

**Comment by spar7453** [comment]
Oh well... I think that I can name cells before getting values and unname them after i get values.
There are too many named cells by the way, so i'm trying to avoid adding more names

**Comment by spar7453** [comment]
I named B1:B5, E1:E5 as "test"
and calling range(test).value only returns the first column of the range.

**Comment by fzumstein** [comment]
xlwings doesn't support this feature and it's also not on the roadmap. You could fall back to pywin32 via `.api` that should support this.

**Comment by spar7453** [comment]
@fzumstein thanks i'll close this issue
