### ISSUE TITLE
How to set the color of individual letters?

### ISSUE THREAD

**Issue by vba34520** [xlwings/xlwings#1458]
How to set single word of a cell?
Like, "ABCDE", "C" is red.

![image](https://user-images.githubusercontent.com/40198281/98785589-cc0ae780-2437-11eb-86de-831b41823427.png)

Looking forward to your reply! Thanks

_Originally posted by @vba34520 in https://github.com/xlwings/xlwings/issues/1066#issuecomment-725272029_

**Comment by fzumstein** [comment]
You can do this with substring (currently not natively implemented in xlwings). The example is for bold, not red, but you should be able to adopt:

```
myrange.api.GetCharacters(start_index, length_string).Font.Bold = True
```

**Comment by vba34520** [comment]
It works! Thank you so much, best wish!

Here is example code:
```python
import xlwings as xw
from xlwings.utils import rgb_to_int

wb = xw.Book()
sht = wb.sheets['Sheet1']
sht.range('A1').value = 'ABCDE'

start_index = 3  # start from 1
length_string = 1
sht.range('A1').api.GetCharacters(start_index, length_string).Font.Color = rgb_to_int((255, 0, 0))  # Red

input('Enter to quit')
wb.close()
```

**Comment by frank7343** [comment]
It seems "range.api.GetCharacters" doesn't work on MacOS with appscript. I got the following error message:
===========
 raise AttributeError("Unknown property, element or command: {!r}".format(name)) from e
AttributeError: Unknown property, element or command: 'GetCharacters'
===========

Is it possible to set the color of individual letters on a Mac? Your help would be highly appreciated.
