### ISSUE TITLE
xlwings creates cell underline format

### ISSUE THREAD

**Issue by WIIIW** [xlwings/xlwings#1466]
#### Describe your issue (incl. Traceback!)

i can change the font size on mac by using following sentence: 

 'cell.api.font_object.font_size.set(12)'

but can not find a way to set the underline for font ,and i try write like this:

 'cell.api.font_object.underline.set('underline_style_single')'

but it didnt work.

need some help.

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
This should do: 

```
import xlwings as xw
from appscript import k

sheet = xw.books.active.sheets.active
sheet['A1'].api.font_object.underline.set(k.underline_style_single)
```

**Comment by WIIIW** [comment]
> This should do:
> 
> ```
> import xlwings as xw
> from appscript import k
> 
> sheet = xw.books.active.sheets.active
> sheet['A1'].api.font_object.underline.set(k.underline_style_single)
> ```

thx! sir!

**Comment by W0228H** [comment]
MacOS
Versions of xlwings, Excel and Python (e.g. 19.3.1, Office 365, Python 3.7)
Sir, I want to use xlwings on a mac to paint a certain part of the string in the excel cell in red, but I don’t know anything about appscript. I hope someone can help me answer this question. I am grateful.
just like this 
"abcdefg"-->"abc"is black , but "def" is red, and "g" is blue
