### ISSUE TITLE
how to set border and autofit with xlwlings on mac

### ISSUE THREAD

**Issue by WIIIW** [xlwings/xlwings#1467]
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
 i try to set border for range  like this:
  cell.api.border.line_style.set(k.continuous)
but it didnt work.

and i dont know how to autofit for specific range.
the code on windows like this 
  cell.api.autofit()
```

**Comment by fzumstein** [comment]
Autofit is natively available: https://docs.xlwings.org/en/stable/api.html#xlwings.Range.autofit

**Comment by fzumstein** [comment]
for the border syntax of appscript, see: 
https://github.com/xlwings/xlwings/issues/440

**Comment by WIIIW** [comment]
> for the border syntax of appscript, see:
> #440

thank you sir, you just solved my problem.
