### ISSUE TITLE
Prevent zombie processes after running app.quit()

### ISSUE THREAD

**Issue by czluo** [xlwings/xlwings#1469]
#### Describe your issue (incl. Traceback!)
Same problem as  #1397. I ran the code of that issue and found that the zoombie process still existed. I have to run "app.kill()" instead to end the process. Is this problem coming up again?

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import xlwings as xw
app = xw.App()
app.quit()
```

**Comment by fzumstein** [comment]
Can't replicate:

![nozombie](https://user-images.githubusercontent.com/2265504/100712019-5fd63080-33b2-11eb-8bb2-f9a1909155e9.gif)

**Comment by czluo** [comment]
Because I have no tools for video recording, please see the screenshot below, the difference is that my python is from anaconda, I don't know what my problem is.
![screenshot1](https://user-images.githubusercontent.com/75296572/100724539-f2e88800-33fd-11eb-8d65-bce56723ca52.png)
![screenshot2](https://user-images.githubusercontent.com/75296572/100724544-f5e37880-33fd-11eb-91f6-a7c1e89e9b9f.png)
![screenshot3](https://user-images.githubusercontent.com/75296572/100724560-f7ad3c00-33fd-11eb-8efe-6224cc392370.png)
![screenshot4](https://user-images.githubusercontent.com/75296572/100724564-f845d280-33fd-11eb-9e38-1efc77bbfe21.png)

**Comment by fzumstein** [comment]
I still can't replicate this with Anaconda and xlwings installed via conda. Given that it seems to work for others (@wkschwartz) I don't think it's an issue with xlwings.

**Comment by wkschwartz** [comment]
@czluo I'm not sure it matters, but what version of pywin32 is installed?

**Comment by czluo** [comment]
> @czluo I'm not sure it matters, but what version of pywin32 is installed?
Thank you for your reply，I upgraded Conda yesterday，Version of pywin32 is 227 now. Is there any other information? I'm more than happy to provide it~
![pywin32_version](https://user-images.githubusercontent.com/75296572/100815066-0fc4a000-347e-11eb-8fbf-30f0ce4d8c29.png)
.

**Comment by wkschwartz** [comment]
What happens if you upgrade to pywin32 version 228 or 300? (When I confirmed #1397, I used pywin32 228.)

**Comment by czluo** [comment]
> What happens if you upgrade to pywin32 version 228 or 300? (When I confirmed #1397, I used pywin32 228.)

I tried both versions and found that none of them worked

**Comment by czluo** [comment]
> What happens if you upgrade to pywin32 version 228 or 300? (When I confirmed #1397, I used pywin32 228.)

 I don't think it's an issue with xlwings either  ha-ha, but I am a layman about how xlwings works and so on, I use ".kill()"  as an altenative for the moment, will there be any side effects?

**Comment by fzumstein** [comment]
kill has the same effect as if you right click Excel in the task bar and force closing it. i.e. it might ask about recovering files you had open previously when you start Excel next time. I am going to close this issue as we don't manage to replicate it. My best guess is that there's something wrong with Excel or Windows or maybe somewhere something has a conflict with your packages. It would be interesting to see if you can replicate the behavior if you make a new conda env and only install xlwings there.

**Comment by czluo** [comment]
It failed again. My Office Computer have an Excel plug-in and Python Api of "Wind", a data provider of China. I think it may be the thing wrong.
![3c3e36b0df2607f3107517036d39793](https://user-images.githubusercontent.com/75296572/100855146-d5322600-34c4-11eb-9800-792e8e60ef3a.png)

**Comment by czluo** [comment]
> kill has the same effect as if you right click Excel in the task bar and force closing it. i.e. it might ask about recovering files you had open previously when you start Excel next time. I am going to close this issue as we don't manage to replicate it. My best guess is that there's something wrong with Excel or Windows or maybe somewhere something has a conflict with your packages. It would be interesting to see if you can replicate the behavior if you make a new conda env and only install xlwings there.

Thank you very much for your answer~

**Comment by wkschwartz** [comment]
> My Office Computer have an Excel plug-in and Python Api of "Wind", a data provider of China. I think it may be the thing wrong.

Maybe Wind connects to Excel via COM but doesn't release its reference properly? That would keep Excel alive. You wouldn't notice unless opening/closing Excel via a separate COM handle, which is how xlwings works.
