### ISSUE TITLE
How can I get merged cell information from an excel？

### ISSUE THREAD

**Issue by LeeYongchao** [xlwings/xlwings#1470]
when I read from an excel, often get an list like [[1,2,3], [4,nan,6], [7,8,9]], but which cell is merged with which cell? because the ’nan‘ may come from  merge with 4, or come from merge with 2 。

**Comment by fzumstein** [comment]
See https://docs.xlwings.org/en/stable/api.html#xlwings.Range.merge_area and https://docs.xlwings.org/en/stable/api.html#xlwings.Range.merge_cells
