### ISSUE TITLE
pywintypes.com_error: (-2147352567, '发生意外。', (0, None, None, None, 0, -2146827284), None)

### ISSUE THREAD

**Issue by Woody007** [xlwings/xlwings#1472]
There is an error occur on operate the excel during let the excel enter background.

**Comment by lxj361** [comment]
everyone who know the solution?

**Comment by fzumstein** [comment]
Please provide the answers to the questions asked when you open a new issue.

**Comment by fzumstein** [comment]
WPS often seems to be causing these sort of issues, just in case it is installed your system.

**Comment by Liincc** [comment]
I still cannot seem to find a workaround to this problem. I am running a macro called 'create' by doing:

macro = xlApp.api.Application.Run('Create')
macro()

and the macro in the .xlsm seems to correctly execute, however it does not carry out the remainder of my loop I've written in Python, and instead I am displayed with this error message pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2146788248), None)
