### ISSUE TITLE
Syntax Error when running python code from VBA

### ISSUE THREAD

**Issue by harshilkhakhkhar** [xlwings/xlwings#1473]
#### Issue when running VBA code in excel
![WhatsApp Image 2020-12-08 at 11 46 46 AM](https://user-images.githubusercontent.com/32437265/101447482-55d0a680-394b-11eb-9647-6ff7ebc928af.jpeg)
![WhatsApp Image 2020-12-08 at 11 47 18 AM](https://user-images.githubusercontent.com/32437265/101447486-579a6a00-394b-11eb-9eac-4de350caaff0.jpeg)
![WhatsApp Image 2020-12-08 at 11 47 50 AM](https://user-images.githubusercontent.com/32437265/101447491-59642d80-394b-11eb-8def-b10907b0dc44.jpeg)

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
You need to use a semicolon `;` instead of a colon `:` after the import statement.

**Comment by harshilkhakhkhar** [comment]
Now getting the eroor @fzumstein

**Comment by harshilkhakhkhar** [comment]
And everytime I open excel I get this message first, if xlwings add in is selected
![Uploading WhatsApp Image 2020-12-08 at 2.37.12 PM.jpeg…]()

**Comment by fzumstein** [comment]
Please start by using the quickstart command (`xlwings quickstart myproject`): https://docs.xlwings.org/en/stable/command_line.html

Looks like you have installed the xlwings addin in two different places - remove it completely before reinstalling via the command line only: `xlwings addin install`

**Comment by harshilkhakhkhar** [comment]
How to check for if xlwings add is installed twice and how to uninstall both
