### ISSUE TITLE
Could not activate Python COM server, hr = -2147221164

### ISSUE THREAD

**Issue by penguinboy2011** [xlwings/xlwings#1476]
#### OS (e.g. Windows 10 or macOS Sierra)
windows 10  （X64）

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings         0.21.4

Excel2016 （32bit）
![image](https://user-images.githubusercontent.com/36751781/101939082-7173cf80-3c1f-11eb-9811-ca0d25b4123a.png)

python 3.9.1 (32bit)

#### Describe your issue (incl. Traceback!)
in A1 Cell , a sql string is    select "hello"
in A2 Cell , =sql(A1)
in excel , when call  sql(),  then wait some minutes ,  return  "Could not activate Python COM server, hr = -2147221164"

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

![image](https://user-images.githubusercontent.com/36751781/101939660-43db5600-3c20-11eb-89d2-a7397c756817.png)


```

**Comment by fzumstein** [comment]
possible duplicate? https://github.com/xlwings/xlwings/issues/1166

**Comment by penguinboy2011** [comment]
> possible duplicate? #1166


Thanks, I reinstalled the office without micro store ,  then xlwings works well !

**Comment by penguinboy2011** [comment]
I reinstalled the office without micro store , then xlwings works well !
