### ISSUE TITLE
one drive for xlwings

### ISSUE THREAD

**Issue by yingmei223** [xlwings/xlwings#1477]
![image](https://user-images.githubusercontent.com/56168671/102100598-94db8c00-3e64-11eb-9779-2d1bd413c034.png)
cannot run main when save the excel at one drive but can run as usual when not in one drive

**Comment by fzumstein** [comment]
Can you please use the issue template? what version of xlwings are you running?

**Comment by yingmei223** [comment]
Hello, 
i am using version 0.21.4 thanks

**Comment by fzumstein** [comment]
Can you look at your environment variables (click on Windows icon, then type `env` and select `edit the system environment variables` > `Environment Variables...`? Do you see a value for `OneDrive` or `OneDriveConsumer` or `OneDriveCommercial`?

**Comment by yingmei223** [comment]
yes, got OneDrive and OneDriveCommercial.
![image](https://user-images.githubusercontent.com/56168671/102362923-e2d0cb00-3fef-11eb-99ec-bace9d11bbc4.png)

![image](https://user-images.githubusercontent.com/56168671/102363316-43f89e80-3ff0-11eb-878c-8eccf9272a96.png)

May I know what should I do with this? I have edited the configuration files, may i know is this the correct way to add it in? 

Much appreciated

**Comment by fzumstein** [comment]
Take the `OneDrive` row out and you should be good. If you leave this in, you need to provide a path to your local OneDrive, but that shouldn't necessary except for edge cases.

**Comment by yingmei223** [comment]
![image](https://user-images.githubusercontent.com/56168671/102375316-57f6cd00-3ffd-11eb-9abd-6c1bc43d450a.png)
Hi sir, but still not working but my conda version is 4.9.2 thanks

**Comment by fzumstein** [comment]
Take over the Conda settings from the ribbon and place them in the `xlwings.conf` sheet - or simply deactivate that `xlwings.conf` for now and rely on the preconfigured addin.
