### ISSUE TITLE
unable to run XLwings examples spreadsheets

### ISSUE THREAD

**Issue by jabed2020** [xlwings/xlwings#1479]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
XLwings 0.21.4 Excel 2016 and Python 3.7
#### Describe your issue (incl. Traceback!)
Hi all,

Wondering if someone is able to help with this issue.
I have managed to install XLWings and am trying to run an example https://www.xlwings.org/examples.

I tried to run example 2 monte carlo simulation

When I tried to run the file I got the error attached
![MVB error](https://user-images.githubusercontent.com/76046206/102210661-5ed0f300-3eca-11eb-9d18-38f420c07c6d.PNG)

I tried to Debug and I got a this message
![Debug](https://user-images.githubusercontent.com/76046206/102210813-9475dc00-3eca-11eb-9702-7441cf47d1d9.PNG)

Any help or advise would be greatly appreciate 

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
What are your ribbon settings?

**Comment by jabed2020** [comment]
Thanks for getting back.

I’m not sure what you mean by that?

What setting in particular? All the settings are set to default and I have enabled the Macros to run.

**Comment by fzumstein** [comment]
Are all fields empty in the ribbon add-in? how did you install the add-in? via `xlwings addin install` on the command prompt?

**Comment by jabed2020** [comment]
It was installed via CMD xlwings addin install.

Here is a screenshot of what the Xlwings ribbon has.

[cid:image001.png@01D6D380.46781DC0]

**Comment by fzumstein** [comment]
you'll need to upload the screenshot directly to GH

**Comment by jabed2020** [comment]
![XLwings ribbon](https://user-images.githubusercontent.com/76046206/102330088-0b6dac00-3f81-11eb-9ead-fba1d6043df1.PNG)

Here is the screenshot. hopefully you should be able to see it now

**Comment by fzumstein** [comment]
Your conda env name contains a space which is not allowed as far as I know.

**Comment by jabed2020** [comment]
just created a new environment inside anaconda navigator and linked it within excel.

Here is a screenshot of the new error.

Appreciate the help sir!
![Tracebook error](https://user-images.githubusercontent.com/76046206/102364951-f1e35900-3fae-11eb-9104-f0782a160757.PNG)

**Comment by fzumstein** [comment]
Run `conda install numpy` in that conda env.

**Comment by jabed2020** [comment]
Thanks soo much Felix!

That’s seemed to have worked
