### ISSUE TITLE
Feature request: getting error codes like #NUM!, #VALUE!, etc from cells

### ISSUE THREAD

**Issue by ckp95** [xlwings/xlwings#1482]
In the docs [it says](https://docs.xlwings.org/en/stable/whatsnew.html#v0-15-5-mar-25-2019):

>Cells that contain a cell error such as #DIV/0!, #N/A, #NAME?, #NULL!, #NUM!, #REF!, #VALUE! return now None as value in Python. Previously they were returned as constant on Windows (e.g. -2146826246) or k.missing_value on Mac.

This is a shame because I'd like to be able to query the exact error code that a cell gives.

I'm trying to use xlwings to do fuzz- and property-based testing of a library called [xlcalculator](https://github.com/bradbase/xlcalculator). I'm having [hypothesis](https://github.com/bradbase/xlcalculator) generate test inputs for formulae and feed them into xlwings, and then check that the xlcalculator implementation matches what Excel says. It's a great way to make sure the Python implementations replicate all of Excel's weird quirks and edge cases. However since xlwings reports error codes as `None` (the same as just a blank cell), this makes it more difficult. I have to do a workaround with the `ERROR.TYPE` formula within the spreadsheet, which is an extra layer of indirection.

Would it be possible for xlwings to report the exact kind of error in a cell? Perhaps in a separate `.error` attribute to preserve backwards compatibility?

#### OS (e.g. Windows 10 or macOS Sierra)

Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

xlwings 0.21.4
Python 3.7.9
Excel O365

**Comment by fzumstein** [comment]
Makes sense. I think I made it `None` for now as I think the information is missing on macOS.
