### ISSUE TITLE
Updating cells doesn't work if filters are being used

### ISSUE THREAD

**Issue by scovail** [xlwings/xlwings#1483]
[Test.xlsx](https://github.com/xlwings/xlwings/files/5758070/Test.xlsx)

#### Versions: xlwings 0.21.4, Excel 16.44,  Python 3.81

When I attempt to update cells in a sheet, if filters are being used then the updates aren't applied properly. This is probably a duplicate of #679, but I'm raising it again because I've not been successful using the workaround. I've set the AutoFilterMode to False, but that appears to have no effect on the sheet. I've also tried invoking the ShowAllData method via the api, but it's not available and causes an error. 

If I manually clear the filters in the test file prior to running the code shown below it works fine. However, if I load the workbook and run the code with no intervention, then the updates won't work.

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

(Test file included)

xlapp = xl.App(add_book=False)
wb = xlapp.books.open('test.xlsx')
tab = wb.sheets[0]
tab.api.AutoFilterMode = False
df = pd.read_excel('test.xlsx') 
val = df.values.tolist()
tab.range('A2').value = val

**Comment by fzumstein** [comment]
Yes, it's the same issue, but the solution there is only for Windows. The solution for mac is:

```
sht.api.autofilter_mode.set(False)
```

I am closing this issue, please continue in #679 if there's anything else.
