### ISSUE TITLE
pictures.add does not seem to change width and height if called in loop

### ISSUE THREAD

**Issue by nikolasharing** [xlwings/xlwings#1491]
#### When I call pictures.add it does not seem to change width and height of the second and further pictures if called in a loop. It could be related to:
https://stackoverflow.com/questions/65688768/why-are-the-properties-height-and-width-not-adjusting-the-picture-size-in-ex

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```
plot_size = 200

if plot_bool==True:
    for plot in plots_sheet.pictures: plot.delete()
    for count,plot in enumerate(plot_list):
        plots_sheet.pictures.add(plot, left=count*plot_size,width=plot_size,height=plot_size)

## with the following code, the height and width is actually changed for all pictures:
# for pic in plots_sheet.pictures:
#     pic.height = plot_size
#     pic.width  = plot_size

```

**Comment by fzumstein** [comment]
Can you please change this into a self-contained code snippet? i.e. include the plotting part, imports etc.

**Comment by nikolasharing** [comment]
You mean like this?

`import xlwings as xw
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(100)
y = np.random.randn(100)
plot_list = []

plots_book  = xw.Book()
plots_sheet = plots_book.sheets[0]

for plot in plots_sheet.pictures: plot.delete()

for i in range(5):
    fig, ax = plt.subplots()
    ax.plot(x,y)
    plot_list.append(fig)

plot_size = 200

for count, plot in enumerate(plot_list):
    plots_sheet.pictures.add(plot, left=count*plot_size,top=100,width=plot_size,height=plot_size)`

**Comment by fzumstein** [comment]
yes, thanks. This is what I see:

<img width="1536" alt="Screen Shot 2021-01-22 at 09 10 33" src="https://user-images.githubusercontent.com/2265504/105464341-bb75b980-5c91-11eb-8531-fda65bcf0b86.png">

**Comment by nikolasharing** [comment]
Yes exactly, but shouldn't the pictures be non overlapping from the left and width parameters chosen above?

**Comment by fzumstein** [comment]
Gotcha, yes, there seems to be an inconsistency in that the `width`/`height` parameters of the `pictures.add` method resize the picture before sending them over to Excel which uses a different unit than Excel.

**Comment by igorrev** [comment]
> Gotcha, yes, there seems to be an inconsistency in that the `width`/`height` parameters of the `pictures.add` method resize the picture before sending them over to Excel which uses a different unit than Excel.

Have the same issue. If I do `pic = xw.pictures.add(width=80, height=80)` image size is wrong. Next commands `pic.width=80` and `pic.height=80` sets right image size.

So @fzumstein , do you find other solution?

BTW, I think the issue doesn't appear in old-old Excel versions like 2007 and 2010.

**Comment by fzumstein** [comment]
Sounds like a good workaround @igorrev - it's not a priority on my end (you can always [change](https://www.xlwings.org/pricing) that).
