### ISSUE TITLE
Opening Excel files stored on SharePoint

### ISSUE THREAD

**Issue by tkc5** [xlwings/xlwings#1496]
#### OS (e.g. Windows 10 or macOS Sierra)

Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

xlwings 0.21.4
Office 365
Python 3.7.9

#### Describe your issue (incl. Traceback!)

I am no longer able to reliably access files stored on SharePoint via xlwings. I am attempting to run a script using PyCharm. The script should open an excel file via the file name. This works if the file is not currently open, but not if the file is already open. Previously, it would work fine as long as the python code (rather than me using file explorer) opened the excel file originally.

I have a folder on my SharePoint accessible via File Explorer: C:\Users\<username>\<organization name>\<SharePoint folder name>\path\to\excel\file\myexcelfile.xlsx

That is the path I pass to xw.Book(path). However, the error thrown suggests that this path somewhere gets converted to a path beginning with https://<myorg>.sharepoint.com. 

This did not happen until recently. The only change I recall making was putting my local python scripts directory onto a git project, and I don't see why this should have any impact. It's possible there were also Windows updates that occurred that I did not notice.

I have not found any other issues here that appear to directly address my problem. There are similar issues (#1275, #1253), which appeared to be resolved by setting the OneDrive environmental variable. However, my OneDrive environmental variable is set to the appropriate path already.

```python
  File "C:\Users\<username>\my\local\scripts\openexcel.py", line 44, in <module>
    main()
  File "C:\Users\<username>\my\local\scripts\openexcel.py", line 35, in main
    wb = xw.Book(excelfilename)
  File "C:\Users\<username>\Anaconda3\lib\site-packages\xlwings\main.py", line 543, in __init__
    add_to_mru, local, corrupt_load).impl
  File "C:\Users\<username>\Anaconda3\lib\site-packages\xlwings\main.py", line 3459, in open
    if not os.path.samefile(impl.fullname, fullname):
  File "C:\Users\<username>\Anaconda3\lib\genericpath.py", line 100, in samefile
    s1 = os.stat(f1)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'https://<myorg>.sharepoint.com/sites/<sitename>/Shared Documents/path/to/excel/file/myexcelfile.xlsx'

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
def main():
    excelfilename = r'C:\Users\<username>\<organization name>\<SharePoint folder name>\path\to\excel\file\myexcelfile.xlsx'
    wb = xw.Book(excelfilename)

main()

```

**Comment by fzumstein** [comment]
It's likely that SharePoint requires an extra fix like the one for OneDrive you link to. In your case, you might however be able to work around it by testing if the file is already open like this:

```python
try:
    wb = xw.books['mybook.xlsx']
except KeyError:
    wb = xw.Book('fullpath/mybook.xlsx')
```

Or you could take away the `Use Office applications to sync Office files that I open` (at least that's how it's called in the OneDrive settings - not sure if it's the same for SharePoint). This will make the path local again, but will also prevent you from live collaborating.

**Comment by tkc5** [comment]
Thanks! Your solution of checking if the file is already open resolved my issue. For anyone else who sees this, I ended up implementing as:

```python
try:
    wb = xw.books['mybook.xlsx']
except (KeyError, AttributeError) as e:       # Handles instance when no excel files are open and the xw.books attribute does not exist
    wb = xw.Book('fullpath/mybook.xlsx')
```

Thanks very much for your help!
