### ISSUE TITLE
RunPython ignores files in directory that are necessary for running scripts

### ISSUE THREAD

**Issue by sabualkaz** [xlwings/xlwings#1499]
#### Issue
RunPython seems to ignore the the .json files in directory. When I run the python script from the command line I don't get any errors the script executes as expected. When I execute RunPython I get the following error.
Note that I tested the code without reading the .json file and it worked without errors as expected.

```python
---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "c:\users\user1\git\testxlwings\xlwingsjson.py", line 7, in <module>

    with open('xlwingsjson.json') as config:

FileNotFoundError: [Errno 2] No such file or directory: 'xlwingsjson.json'



Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------



```

#### Code sample

```python
import xlwings as xw
import json

with open('xlwingsjson.json') as config:
    data = json.load(config)

def main ():

    wb = xw.Book('xlwingsjson.xlsx')
    sht2 = wb.sheets[0]
    sht2.range((1,1)).value = data['metadata']
    

if __name__ == '__main__':
    main()

```

**Comment by fzumstein** [comment]
You can't use relative file paths as `RunPython` will not have the same working directory as when you run it directly. Use an absolute path or something like this:

```python
from pathlib import Path
this_dir = Path(__file__)
json.load(this_dir / 'xlwingsjson.json')
```

**Comment by sabualkaz** [comment]
I do indeed need to make it work with relative paths. Your suggestion needed a minor tweak to make it work. Thanks for the quick reply.

```python

from pathlib import Path
this_dir = Path(__file__).parent 
json.load(this_dir / 'xlwingsjson.json')

```

**Comment by fzumstein** [comment]
ouch, you're right, sorry about that!
