### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by rmalh** [xlwings/xlwings#1504]
#### Describe your issue (incl. Traceback!)
I'm using options(expand='table') to get data from an Excel table, which has 12 columns and 0+ rows. If the first row in the table has any blank cells, xlWings stops there and picks up only partial table data. Is there a way to force it to pick up data from all 12 columns, including blanks?

Secondly, if the table has only 1 row of data, xlWings creates a vertical list with 12 rows and 1 column each, instead of 1 row of 12 columns, which is what Python expects. If we can force it to pick up data from all 12 columns, this may also get resolved.

You can get the Excel file here - https://www.icloud.com/iclouddrive/0DGWKkmNgUJZ3LDB6hMTExPqA#TestApp

```python
# Your traceback here
No errors or traceback, just that data picked up is incomplete or incorrect.
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
def getData():
    wb = xw.Book.caller()
    callingWorksheet = wb.sheets.active.name

    # Get location of the Excel cell address where "Table to pickup" begins
    temp_macro = wb.macro("locateTable")
    cellAddress = temp_macro(wb.name, callingWorksheet, 'OrderList')

    # Pick up data
    dataFromXL = []
    if wb.sheets(callingWorksheet).range(cellAddress).value.strip() == "":
        raise ValueError ("No data to pickup")
    else:
        dataFromXL = wb.sheets(callingWorksheet).range(cellAddress).options(expand='table').value

```

**Comment by fzumstein** [comment]
You'll want to look into:

* `ndim=2`, see: https://docs.xlwings.org/en/stable/datastructures.html#lists
* `tables`, see: https://docs.xlwings.org/en/stable/api.html#table

**Comment by rmalh** [comment]
Thanks fzumstein. The solution that worked is a combination of named Excel tables, data_body_range, "ndim=2".

If Python uses name of the table when calling for data, the full table is returned regardless of empty cells since Excel knows table width. This also ensures that tables with one row of data are returned correctly. Below is the code:

wb.sheets(callingWorksheet).tables[callingWorksheet + 'OrderListTable'].data_body_range.options(ndim=2).value
