### ISSUE TITLE
Unusable workbook

### ISSUE THREAD

**Issue by rmalh** [xlwings/xlwings#1509]
#### Describe your issue (incl. Traceback!) My VBA macro calls a Python function, which has an infinite loop to gather data from the server and update Excel tables every 60 sec. As soon as I run the macro, Excel gets "locked" i.e. no cells can be updated other than by the running Python code. I'm still able to navigate between worksheets, though. Note that this issue cropped up a couple of days ago when I moved the setup from MacOS to Windows 10.

```python
# No traceback available since no error is thrown

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
def main():
    global ib, wb
    ib = ibi.IB()

    #Create an object for the caller Excel workbook
    wb = xw.Book.caller()

    # Start IB api connection
    ib.connect('127.0.0.1', getIbConnectionPort(wb.sheets.active.name), clientId=1)

    while True:
        # Create a dictionary initialized with account numbers and empty lists
        # The lists will be populated with positions for the account
        acccountPositionsDict = {}
        for accountNumber in getAccountNumberDict():
            acccountPositionsDict[accountNumber] = []

        # Get positions for all accounts and organize them into the dictionary of lists created above
        for acccountPosition in ib.positions():
            acccountPositionsDict[acccountPosition.account].append([acccountPosition.contract.localSymbol, float(acccountPosition.avgCost), float(acccountPosition.avgCost)*float(acccountPosition.position)])

        # Update the worksheets with positions
        for accountNumber in acccountPositionsDict:
            sheetName = getAccountNumberDict().get(accountNumber)

            #Set NVL and Cash values in Excel cells
            wb.sheets(sheetName).range("B1").value = accountValue(accountNumber, 'NetLiquidationByCurrency')
            wb.sheets(sheetName).range("D1").value = accountValue(accountNumber, 'CashBalance')
            acccountPositionsDict.get(accountNumber).sort()

            # Refresh the  "Portfolio" table in Excel
            cellAddress = wb.sheets(sheetName).tables[sheetName + 'PortfolioTable'].data_body_range(1, 1).address
            wb.sheets(sheetName).range(cellAddress).value = acccountPositionsDict.get(accountNumber)
            ib.sleep(60)

        ib.disconnect()

```

**Comment by rmalh** [comment]
[ib_insync_XL.zip](https://github.com/xlwings/xlwings/files/5939852/ib_insync_XL.zip)

Attached here is the workbook, if needed for reference.

**Comment by fzumstein** [comment]
`RunPython` works currently differently on mac on windows: mac uses a background process, i.e. doesn't block the Excel UI while the call in Windows is synchronous and blocks the UI for as long as the Python code is running. You could hack it by setting `Dim WaitOnReturn As Boolean: WaitOnReturn = True` to `False` in the VBA code, but there is no mechanism in place that will handle errors in this case so I wouldn't really recommend it. You should also be able to run your endless loop in a thread so it won't block the main script.

**Comment by rmalh** [comment]
@fzumstein Is the WaitOnReturn flag set UDF or somewhere else?

**Comment by fzumstein** [comment]
It's in the VBA code module `main` there is this line: `Dim WaitOnReturn As Boolean: WaitOnReturn = True` but that's only for RunPython, not UDFs.
