### ISSUE TITLE
Exclude index when adding a DataFrame to a range

### ISSUE THREAD

**Issue by mrgou** [xlwings/xlwings#1512]
I wish there was an option to exclude the index when setting the values a range to a DataFrame:

```python
wb = xw.Book()
sht = wb.sheets['Sheet1']
sht.range('A1').value = df
```

Column A will then contain the dataframe's index, which can be what you want, but will not always be.

**Comment by fzumstein** [comment]
How about:

```python
wb = xw.Book()
sht = wb.sheets['Sheet1']
sht.range('A1').options(index=False).value = df
```
😎

**Comment by mrgou** [comment]
Nice, thank you!!! :-)
