### ISSUE TITLE
Pivot table 

### ISSUE THREAD

**Issue by Cbarrow98** [xlwings/xlwings#1513]
#### Versions of xlwings, Excel and Python- 0.19.5, Office 365, Python 3.8

```python
# Your traceback here

```Hello, I am trying to figure out what’s the most efficient way to create a pivot table automatically in excel (windows) using xlwings. I notice an issue 191 posted something similar to this. However, that post was almost six years ago. So, it’s likely an update has occurred since then with regards to the function. Thanks.

**Comment by fzumstein** [comment]
No progress on this so far, so https://github.com/xlwings/xlwings/issues/191 is indeed the correct issue and the only way this is supported currently is via `.api`. I am closing this issue and would ask you to continue there, thanks!
