### ISSUE TITLE
xlwings cannot locate python module when using drive backup and sync

### ISSUE THREAD

**Issue by chsir17** [xlwings/xlwings#1516]
#### OS (e.g. Windows 10 or macOS Sierra)

Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

0.22.1, Office 365, Python 3.7

#### Describe your issue (incl. Traceback!)

My python file and my workbook are in google drive and I am using backup and sync.

If my files are directly in G:\ it works, but if they are in a folder with "G:\.shortcut-targets-by-id\0B1...." I get a module not found error.

I have tried to add manually the full path to my python file in PYTHONPATH and it still does not work.

```python
# Your traceback here

---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "<string>", line 1, in <module>

ModuleNotFoundError: No module named 'CalculCoutsV4'



Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------


```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
So is G:\ outside of Google drive?

when the module isn't found, can you go into the VBA editor's immediate windows and type 

```
?ThisWorkbook.FullName
```
ls this the path that corresponds to the physical location on disk?
