### ISSUE TITLE
Trying to find out if an item is already in a combobox (Control, not activex) that I have on a worksheet - List method fails

### ISSUE THREAD

**Issue by kirbyschapman** [xlwings/xlwings#1519]
Hello - I'm trying to find out if an item is already in a combobox (Control, not activex) that I have on a worksheet. I can add items to it just find. Then, when I'm ready to add more items to the box, I need to first see if the item is already in the box. If it is, then I want to make it the selected item. But I can't get past the point of finding out if it already exists.

Here's how I populate the box the first time around (this works great):
```
def fill_name_cb():
    cb = ct.WS_MAIN.shapes("cbNames").api.ControlFormat
    cb.RemoveAllItems()
    cb.AddItem("Select Client")
    cb.AddItem("Add New Client")
    cb.AddItem("Update List")
    for name in ct.CLIENT_NAMES:
        cb.AddItem(name)
    cb.ListIndex = 1
```
This populates the box and then selects item 1 with the ListIndex method as expected - works great.

I've tried a variety of methods to test if each item in the box is equal to a new name. My latest effort (which doesn't work)  is:
```
    cb = ct.WS_MAIN.shapes("cbNames").api.ControlFormat
    print(f'Items in cbNames: {int(cb.ListCount)}')
    print(f'Sel Item in cbNames : {int(cb.ListIndex)}')
    number_items = int(cb.ListCount)
    print(f'Number Items: {number_items}')
    for index in range(1, number_items + 1):
        cb.ListIndex = index
        name = cb.Value # <--- this only returns the index, not the value in the box
        print(f'Value showing on combobox: {name}')
        # Crashes with the error below
        value = cb.List(index)
        print(f'value of index {index} is {value}')
```
The print results and error are:
```
cell_id B2
cell_id B2 data point: Kirby Chapman
Items in cbNames: 6
Sel Item in cbNames : 1
Number Items: 6
Value showing on combobox: 1.0 <----- Oddly this comes back as a float, but I convert it to an int
Traceback (most recent call last):
  File "c:/Users/kirby/OneDrive/calculations/helpers.py", line 158, in <module>
    retreive_assessment_data(5)
  File "c:/Users/kirby/OneDrive/calculations/helpers.py", line 94, in retreive_assessment_data
    value = cb.List(index)
  File "C:\Users\kirby\AppData\Local\Programs\Python\Python38-32\lib\site-packages\xlwings\_xlwindows.py", line 66, in __call__
    v = self.__method(*args, **kwargs)
  File "C:\Users\kirby\AppData\Local\Temp\gen_py\3.8\00020813-0000-0000-C000-000000000046x0x1x9.py", line 6525, in List
    return self._ApplyTypes_(861, 1, (12, 0), ((12, 17),), 'List', None,Index
  File "C:\Users\kirby\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\__init__.py", line 467, in _ApplyTypes_
    self._oleobj_.InvokeTypes(dispid, 0, wFlags, retType, argTypes, *args),
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Excel', 'List method of DropDown class failed', 'xlmain11.chm', 0, -2146827284), None)
```
According to [Microsoft docs](https://docs.microsoft.com/en-us/office/vba/api/excel.controlformat.list), ControlFormat in Excel does have a `List` method, which makes me think I'm doing something really dumb... 
It seems the List method is failing for some reason, and I can't figure it out. I also tried (unsuccessfully) to do this so there aren't any issues with variable types - I get the same List method failed error and never get to the print statement:
```
   cb1 = cb.List(1)
   print(cb1)
```
Can anyone help? Thanks in advance - I've been pulling my hair out over this, as it just doesn't seem that difficult.

EDIT: I should also mention that I tested this within the VBA environment like this, and it returns the actual name in the combobox as expected:
```
Sub get_name()
With ThisWorkbook.Sheets("Assessment").Shapes("cbNames").ControlFormat
    current_value = .List(.ListIndex)
    MsgBox current_value
End With
    
End Sub
```

FYI: I'm running Win 10 and have the latest updates for Excel and xlwings. Python is 3.8 and (I believe) is the 32 byte version.

_Originally posted by @kirbyschapman in https://github.com/xlwings/xlwings/issues/442#issuecomment-778466208_

**Comment by fzumstein** [comment]
Try this: 

`xw.sheets.active.shapes("Drop Down 1").api.OLEFormat.Object.List`

see also: https://www.thespreadsheetguru.com/blog/2014/5/14/vba-for-excels-form-control-combo-boxes

**Comment by kirbyschapman** [comment]
> Try this:
> 
> `xw.sheets.active.shapes("Drop Down 1").api.OLEFormat.Object.List`

That did it - it created a tuple of the all the entries in the drop down, which will work great with `listindex`! Thanks for the help!!

> see also: https://www.thespreadsheetguru.com/blog/2014/5/14/vba-for-excels-form-control-combo-boxes

I hadn't come across this reference - it's definitely worthy of bookmarking!
