### ISSUE TITLE
Handling #SPILL error when editing python function in excel

### ISSUE THREAD

**Issue by carlinakim** [xlwings/xlwings#1521]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.22.0
Office 365
Python 3.7

#### Describe your issue (incl. Traceback!)

I have created a function in python that reads in a datatable, wrangles it, and spits back out a new table in the format that needs to be inputed to an excel sheet. The function works fine when the designated columns (ex column A - J), but once I try to edit the values in the function table, it results in a SPILL error. Is there a workaround this? 

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
  
    @xw.func
    @xw.ret(index=False)
    def Create_Tracking_Sheet(terminal_name):
...
    #remove header
    tracking_sheet = tracking_sheet.rename(columns=tracking_sheet.iloc[0]).drop(tracking_sheet.index[0])
    
    return tracking_sheet.reset_index(drop=True)

```
I import this function successfully and write =Create_Tracking_Sheet("Toronto") and a table is populated, however dissapears when I edit it or use a dropdown filter. 

Thanks for any assistance!

**Comment by fzumstein** [comment]
Not quite sure I follow, can you upload a few screenshots maybe?

**Comment by carlinakim** [comment]
The first image shows the function being written in cell B6 =Create_Tracking_Sheet("Pickering") and populates the table into columns B through L with the spill range in blue. 

![Screen Shot 2021-02-18 at 12 25 02 PM](https://user-images.githubusercontent.com/47160194/108417152-74bda580-71e4-11eb-9f5c-6566d8b2a5f8.png)

Once I try to edit the cells within that table, or use the filter in Driver Name, the function erases with a #SPILL error. I know this is an issue with Excel, but is there a way in xlwings to override the issue?

![Screen Shot 2021-02-18 at 12 25 19 PM](https://user-images.githubusercontent.com/47160194/108417169-79825980-71e4-11eb-9cf0-2e72c5549e73.png)

**Comment by carlinakim** [comment]
I have tried putting in @ in front of the function but that did not work for me

**Comment by fzumstein** [comment]
from where to where is the spill area? the blue border is hard to recognize on the screenshot.

**Comment by carlinakim** [comment]
from B6:L15

**Comment by fzumstein** [comment]
in that case I guess it's expected and changing it into a CSE array by using @ would also not help you. You would have to take column L out of the array, i.e., return value. You can't have an array and change a field of it.
