### ISSUE TITLE
Streaming Loop output into excel cell

### ISSUE THREAD

**Issue by Cbarrow98** [xlwings/xlwings#1525]
#### Describe your issue (incl. Traceback!)
Trying to display the output of a loops results in excel however not sure how to get results to iterate through each cell and not just stay in and constantly change 'A1'
```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
for i in SL3.index:
        stock=str(SL3["Ticker"][i]) 
        df = yf.Ticker(stock).info['previousClose'] 
        PB_no+=1
        Last_Price[PB_no] = [df] 
        print(df)
        ws2.range('A1').value = df
```

**Comment by fzumstein** [comment]
try not to loop through cells as this is slow. rather construct a whole DataFrame, then write out the whole DataFrame.
