### ISSUE TITLE
Debugging UDF with Spyder: "No command specified in the configuration, cannot autostart server"

### ISSUE THREAD

**Issue by matteovallucci** [xlwings/xlwings#1527]
#### Issue
Using udf file myfile.xlsx, linked to myfile.py, in the same folder
In the xlswing ribbon menu, I flag the option Debug UDFs
When updating the cells with udf, I get the following message

```python
# No command specified in the configuration, cannot autostart server
```

**Comment by fzumstein** [comment]
are you running the server manually as explained here? https://docs.xlwings.org/en/stable/debugging.html#udf-debug-server

**Comment by matteovallucci** [comment]
I was sure I did, instead I didn't do it correctly.
