### ISSUE TITLE
Sharing jupyter notebooks that use xlwings with other users

### ISSUE THREAD

**Issue by tomnewg** [xlwings/xlwings#1537]
Hi guys,

I built a few jupyter notebooks that use xlwings. I would like to share these notebooks with non-technical users and don't seem to find any elegant solution. I can't use jupyterhub as I am not able to install excel on the server. The local Excel installation should be used by the notebook. It is also not a solution to use other packages such as openpyxl as I need xlwings because these notebooks interact with specific excel files while they are open. Is there any other solution apart from installing anaconda with a specific environment on the user's machine?

Many thanks for your help

Tom

**Comment by fzumstein** [comment]
xlwings does indeed require a local installation of Python, so given that you won't be able to install Excel on the server, I don't see any other alternative than getting Python and the dependencies installed on the end-users desktops. If you think that Anaconda/conda envs are too cumbersome (?), I'd be happy to show you how the xlwings one-click installer works that comes with the PRO version, see: https://docs.xlwings.org/en/stable/deployment.html#zero-config-installer
