### ISSUE TITLE
excel cannot load xlwing dll from folders

### ISSUE THREAD

**Issue by SvenneRag** [xlwings/xlwings#1538]
OS: Windows 10 

Versions: 
xlwings: 0.23.0 
Excel: Office 365
Python: Python 3.8.8

I have just reinstalled xlwings using pip and I have created a new project via xlwings quickstart. But when I import functions in excel I get the following message:

![image](https://user-images.githubusercontent.com/5476154/110446769-d4122580-80bf-11eb-9e61-e4cf50d6a051.png)

When I run
where xlwings
in a prompt it points to a different location than where my python.exe is located which I can understand from homepage is the problem
```
C:\Users\svend\XlwingsTest>where xlwings
C:\Users\svend\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts\xlwings.exe
```

When I installed xlwings I got the following message:
```
C:\Users\svend>pip install xlwings
Collecting xlwings
  Using cached xlwings-0.23.0-py3-none-any.whl
Requirement already satisfied: pywin32>=224 in c:\users\svend\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from xlwings) (300)
Installing collected packages: xlwings
Successfully installed xlwings-0.23.0
```

I could imagine that this is the reason why excel cannot find xlwings.

I used to have Anaconda installed but chose to uninstall. It could appear that there are some legacies that have not been removed.

How can I proceed?

Thank you in advance
Svend Andreasen

**Comment by fzumstein** [comment]
Hi Svend, I believe that the official Python installer changed a few things and split off the installation of 3rd party packages like xlwings from the rest of the installation. I think this causes the issue. I'll need to look into it with a bit more time to see what the best solution is, but as a quick fix, you should be able to fix the issue by copying the two `dll` files from the directory of your `python.exe` (you can find the path by running `import sys;sys.executable`) and copying them into the first path you see printed in your error message.

**Comment by curcuminx** [comment]
I'm not 100% sure, but it seems like both previous issues I had- the one reminded here and #1260 were wiped clean once I uninstalled **Microsoft Store** Python 3.9 and reinstalled python 3.9 from the **official site**. I'm guessing it is similar the issue with MS store Excel, might be wrong though..
