### ISSUE TITLE
sht.range('A1').value =[[1],[2],[3],[4],[5]]# Column orientation (nested list) will crash when give a special strings

### ISSUE THREAD

**Issue by help1234** [xlwings/xlwings#1540]
#### OS windonws server 2019

#### Describe your issue (incl. Traceback!)

```python
# Your traceback here
 the script will keep runing the excel file and never end. looks like in death loop
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```import xlwings as xw
testlist = [[1],[2],[3],[4],[r'=HF132\n\nTJ-B-007\n\nFS701=HF132']]
try:
  wb = xw.Book('test.xlsx')
except:
  wb = xw.Book()
  wb.save('test.xlsx')
wb.sheets.active.range('A1').value =testlist # if do so, the script will keep runing the excel file and never end

**Comment by fzumstein** [comment]
please fill in the template (OS etc).
Try a raw string (`r'=HF132\n\nTJ-B-007\n\nFS701=HF132'`)

**Comment by help1234** [comment]
I update the os infomation and xlwings version . change the string to a r string got  same result. 
Are there anyone reproducing these errors in your environment?
![Uploading traceback.jpg…]()

**Comment by fzumstein** [comment]
You will need to escape the leading `=` or otherwise Excel thinks it's an (invalid) formula. This works:

`xw.books.active.sheets.active.range('A1').value = "'=HF132\n\nTJ-B-007\n\nFS701=HF132"`

depending on whether you want the `\n\n` to be new lines or literal characters, use a leading `r` or not.
