### ISSUE TITLE
wb.save xlsm error

### ISSUE THREAD

**Issue by mybdye** [xlwings/xlwings#1546]
#### OS (e.g. Windows 10 or macOS Sierra)
macOS Catalina 10.15.7 (19H524)
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xw 0.23.0
office 365
python 3.9
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3 /Users/he/Desktop/xw/test.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aeosa/appscript/reference.py", line 482, in __call__
    return self.AS_appdata.target().event(self._code, params, atts, codecs=self.AS_appdata).send(timeout, sendflags)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aeosa/aem/aemsend.py", line 92, in send
    raise EventError(errornum, errormsg, eventresult)
aem.aemsend.EventError: Command failed: Parameter error. (-50)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/he/Desktop/xw/test.py", line 10, in <module>
    wb.save('2.xlsm')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/xlwings/main.py", line 740, in save
    self.impl.save(path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/xlwings/_xlmac.py", line 270, in save
    self.xl.save_workbook_as(filename=hfs_path, overwrite=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aeosa/appscript/reference.py", line 518, in __call__
    raise CommandError(self, (args, kargs), e, self.AS_appdata) from e
appscript.reference.CommandError: Command failed:
		OSERROR: -50
		MESSAGE: Parameter error.
		COMMAND: app('/Applications/Microsoft Excel.app', newinstance=(0, 6133209)).workbooks['1.xlsm'].save_workbook_as(filename='macOS:Users:he:Desktop:xw:2.xlsm', overwrite=True)

Process finished with exit code 1
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
# test.py

import xlwings as xw

app = xw.App(visible=False, add_book=False)
app.display_alerts =False
app.screen_updating =False

wb = app.books.open('/Users/he/Desktop/xw/1.xlsm')
sheet = wb.sheets['Sheet1']
sheet.range('A1').value = 'test'
wb.save('2.xlsm')
app.quit()
```
[xw.zip](https://github.com/xlwings/xlwings/files/6175349/xw.zip)

**Comment by fzumstein** [comment]
This is basically the same as #187. I've fixed it on this branch: https://github.com/xlwings/xlwings/tree/xlwings-1546-fileformat, but the Windows implementation and tests are still missing and it might take me a while before I get there. In the meantime, you could just use the attached packge:

[xlwings-baa09c8.tar.gz](https://github.com/xlwings/xlwings/files/6176547/xlwings-baa09c8.tar.gz)

**Comment by mybdye** [comment]
Works perfectly, thank you.

> This is basically the same as #187. I've fixed it on this branch: https://github.com/xlwings/xlwings/tree/xlwings-1546-fileformat, but the Windows implementation and tests are still missing and it might take me a while before I get there. In the meantime, you could just use the attached packge:
> 
> [xlwings-baa09c8.tar.gz](https://github.com/xlwings/xlwings/files/6176547/xlwings-baa09c8.tar.gz)
