### ISSUE TITLE
DLL loading fails without internet connection.

### ISSUE THREAD

**Issue by malwinweiler** [xlwings/xlwings#1550]
#### Describe your issue (incl. Traceback!)

I am having a very strange issue based on internet connectivity.

#### What I try to do:
In Excel I have multiple test cases that need to be calculated with different input parameters. The input parameters are defined in Excel by engineers and are then passed via a UDF call to Python. Python then formats the input and passes it to Optimizer.dll. To do so Python loads the Optimizer.dll with ctypes (see Python example). Optimizer.dll itself has a link to RealTimeOptimzer.dll which is located in the same directory (as is the Excel file and everything that could possibly be accessed by the code).

#### What happens:
Whenever I am connected to the internet there are no problems at all. The problems only occur when I am disconnected, thus the entire problem description is without internet connection.

#### Debug UDFs Function is activated in Excel:
I start up the debug server in my local VS Code and set some breakpoints. Everything works fine, no issues to report. The dll loads fine and does its calculations.

#### Debug UDFs Function is disabled in Excel:
This is where everything breaks. 
I try to run the exact same code with the exact same input but without spinning up the debug server. The python code works fine up until it tries to load the dll as in the Python example.

I furthermore get a Message Box that tells me: "RealTimeOptimzer.dll not found. File must be available to run the application!"

```python
xlwings server running, clsid={C05EC813-1E77-4A24-B69C-E74E181307B0}, event loop on 18408
pythoncom error: Python error invoking COM method.

Traceback (most recent call last):
  File "C:\Users\username\Anaconda3\envs\xlwupdate\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Users\username\Anaconda3\envs\xlwupdate\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Users\username\Anaconda3\envs\xlwupdate\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return func(*args)
  File "C:\Users\username\Anaconda3\envs\xlwupdate\lib\site-packages\xlwings\server.py", line 198, in CallUDF
    res = call_udf(script, fname, args, this_workbook, FromVariant(caller))
  File "C:\Users\username\Anaconda3\envs\xlwupdate\lib\site-packages\xlwings\udfs.py", line 505, in call_udf
    ret = func(*args)
  File "c:\[Redacted]\LVF_python_module.py", line 114, in LVF_python_module
    ctypes.WinDLL("C:/[Redacted]/Optimizer.dll").__getattr__("calc_ana")
  File "C:\Users\username\Anaconda3\envs\xlwupdate\lib\ctypes\__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import ctypes, os
os.environ["PATH"] += os.pathsep + os.path.dirname(os.path.realpath(__file__))
opt_dll = ctypes.WinDLL(os.path.dirname(os.path.realpath(__file__))+"/Optimizer.dll").__getattr__("calc_ana")

(opt_dll = ctypes.WinDLL("C:/[Redacted]/Optimizer.dll").__getattr__("calc_ana"))

```

#### What I know
Based on the error from the Message Box I expect there to be a path problem. The Optimizer.dll is looking for the RealTimeOptimzer.dll but cannot find it and thus throws this error. Why this only happens without internet connection and only when not using the debug server, I cannot explain.

Additional info: The DLL is protected with CodeMeter. When the DLL is accessed it checks for a running CodeMeter instance and valid license and then releases the DLL. Both DLLs are protected. CodeMeter is set-up to run independently of internet access. This has been verified with a separate python file that loads the DLLs successfully and gets the calculations done.

#### What I tried
I have tried to hardcode ctypes.WinDLL("C:/[Redacted]/Optimizer.dll").__getattr__("calc_ana").

I have tried to set my user environment variables in Windows to the correct directory without luck.

I have loaded the DLL (in the same way described in the Python example) in a separate python file that is not connected to Excel or xlwings. By starting the python file from cmd the DLL is loaded correctly and performs its calculations. Thus I am certain that the problem is with the xlwings server.
Note: CodeMeter does not cause issues when the file is run like this.

#### My ideas:
The xlwings that is started is very different between debug and non-debug mode. This difference is causing the issue.
In debug mode VS Code forces the xlwings server to be executed in the correct directory:

```python
(LVF) C:\[Redacted]> c: && cd c:\[Redacted] && cmd /C "C:\Users\username\Anaconda3\envs\LVF\python.exe c:\Users\username\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\lib\python\debugpy\launcher 14962 -- c:\[Redacted]\LVF_python_module.py "
xlwings server running, clsid={506E67C3-55B5-48C3-A035-EED5DEEA7D6D}, event loop on 17236
```

When in non-debug mode the xlwings server is located somewhere else and there is an issue with setting and passing the correct path variables. The xlwings server is also not able to access the user path variables.

Edit: That theory is under pressure. When running in non-debug mode and showing the console I can see some of the arguments. In particular:

sys.path[0:0]=os.path.normcase(os.path.expandvars(r'C:\[Redacted];....

So from that I would guess that the path variables are also set correctly within the non-debug mode.

Another idea could be that the non-debug xlwings server somehow restricts access to CodeMeter. However, Optimizer.dll can be accessed without problems since it is already actively looking for RealTimeOptimizer.dll. Thus, I doubt that CodeMeter is the culprit.

Thank you in advance!
Any help is appreciated :)

**Comment by fzumstein** [comment]
The working directory will be different when you run the server from Excel, but other than that, there shouldn't be really a difference...I just tested the env vars and they seem to be fine for me (you do use the Conda settings in the add-in, don't you?):

```
@xw.func
def envs():
    return dict(os.environ)
```

Maybe try to do `os.chdir(...)` at the beginning of your function to be in the same directory as when you start it from VS code?

**Comment by malwinweiler** [comment]
Hi,

thank you very much for your reply.

Indeed, changing the directory at the very beginning solved my problem:

os.chdir(os.path.dirname(os.path.realpath(__file__)))

A more detailed summary for anybody running into similar issues:
In debug mode (VS Code) the directory is the one opened with VS Code, whereas in the non-debug mode xlwings started the code in my "Documents" directory.

Although, in the python environment the environment variables were set correctly and the system environment variables were also set correctly, the DLL was still not able to find the linked DLL when not in debug mode. Changing the directory then solved the issue and all linked DLLs could be found and used.

Unfortunately, I am still not able to explain why the internet connection has any relevance in this issue.

Nevertheless, thanks you for your help!
