### ISSUE TITLE
Pdf gets cropped when xlwings tries to convert using to_pdf() 

### ISSUE THREAD

**Issue by noureentaj** [xlwings/xlwings#1552]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings(0.23.0)
#### Describe your issue (incl. Traceback!)
No error raised. PDF is vertically cropped, first two columns on one page and rest on the next page

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
app = xw.Book()
sht = app.sheets['sheet1']
sht.range('A7').options(index=False).value = df
# IMAGE
rng = sht.range('F1')
pic = sht.pictures.add("default_logo.jpg", top=rng.top, left=rng.left)
pic.width = 190
pic.height = 90
app.to_pdf()
```

**Comment by fzumstein** [comment]
You would have to setup the page / print area accordingly so it fits on 1 page

**Comment by noureentaj** [comment]
I am trying to also use autofit on a range of cells. If I dont use that, the cell values dont get displayed on the pdf properly, they get cropped. Is there any way I can make sure all of the data is available in readable format and not split vertically in two pages?
I can limit font size to 8 and that is all I can do to setup the page currently

Need support on pdf margin which is eating up the space in the page

**Comment by fzumstein** [comment]
Under Page Setup, you can select `Fit to ... Pages wide by ... Tall` to make it fit on 1 page

**Comment by noureentaj** [comment]
Not quite sure how I should do that in my script. I don't and can't use print settings. I want the file generated fit automaticaly in one piece, any hack there?

**Comment by fzumstein** [comment]
You'd have to use `.api` in connection with: https://docs.microsoft.com/en-us/office/vba/api/excel.pagesetup, see also: https://docs.xlwings.org/en/stable/missing_features.html

For example, to set the print area, you would do:
```python
mybook.sheets[0].api.PageSetup.PrintArea = '$C$2:$K$55'
```

**Comment by noureentaj** [comment]
Hey Felix,
Thanks a lot for the prompt replies. This still did not work for me but due to xlwings' limited capabilites to be used in a linux environment, I had to default to xlsxwriter. There were some errors on package downloads in the environment
