### ISSUE TITLE
AttributeError: module 'xlwings' has no attribute 'load'

### ISSUE THREAD

**Issue by Ulan-A** [xlwings/xlwings#1555]
#### Unable to load selected cells into Pandas DataFrame.

```wb.sheets['myTab'].range('C5').expand().select()```   ##This section is the beginning and it works.

```df = xw.load()```   ##This section is the objective and it causes errors.

**Error message:**
`AttributeError: module 'xlwings' has no attribute 'load'`

#### Also tried:
```wb = xw.Book(strMyExcelFile)```   ##This section establishes the workbook and active tab.
```wb.sheets[strTab].activate()```

```df = wb.load()```   ##This section was the objective and it failed. 

**Error message:**
`AttributeError: 'Book' object has no attribute 'load'`

**Comment by ericbmoreira** [comment]
This is what I usually do:
```
wb = xw.Book('my_book.xlsm')
sht = wb.sheets['my_sheet']
df = sht.range('ticketing_trans_input_data_rng')
            .options(pd.DataFrame, index=False, header=False).value
```
I think you can skip the sht part but I like to be overly explicit.

**Comment by fzumstein** [comment]
`load` should exclusively be used in interactive mode, as it uses the active sheet, see: https://docs.xlwings.org/en/stable/jupyternotebooks.html. I realize that this warning is missing in the API docs though. For scripts, always use the fully qualified API as shown by the previous answer.
The error may indicate that you use an older version of xlwings, make sure via `xlwings.__version__`.

**Comment by Ulan-A** [comment]
Thank you @ericbmoreira , @fzumstein for your suggestions! I was able to leverage on your insights.

Here is my full solution:

    #Open Excel file and select a target tab.
    wb = xw.Book(strMyExcelFile)
    wb.sheets[strMyTab].activate()

    #Select a starting cell, C5 in this case, and all adjacent cells.
    wb.sheets[strMyTab].range('C5').expand().select()

    #Define the range of selected cells to use downstream.
    cellRange = wb.app.selection

    #Assign data from the selected range into Pandas DataFrame. The first row in Excel file is headers. 
    df = wb.sheets[strMyTab].range(cellRange).options(pd.DataFrame, index=False, header=True).value

    #Close Excel file without saving it. 
    wb.close()

**Comment by fzumstein** [comment]
For scripts, you should not rely on active objects/selections as this will cause issues if you manually click around in Excel wile your script runs. Try this instead:

```python
#Open Excel file and select a target tab.
wb = xw.Book(strMyExcelFile)
sheet = wb.sheets[strMyTab]

#Select a starting cell, C5 in this case, and all adjacent cells.
cellRange = sheet.range('C5').expand()

#Assign data from the selected range into Pandas DataFrame. The first row in Excel file is headers. 
df = cellRange.options(pd.DataFrame, index=False, header=True).value

#Close Excel file without saving it. 
wb.close()
```

**Comment by Ulan-A** [comment]
@fzumstein, yes, your solution is better. Appreciate the insight!
