### ISSUE TITLE
How to return lists and arrays from xlwings to use in VBA

### ISSUE THREAD

**Issue by mokaam** [xlwings/xlwings#1559]
I've noticed below example from the documentation and I want to do something similar, but I keep getting "Type Mismatch" when I try to return a 1d list to a vba dynamic Array of Variants. How is `arr = my_imported_function(...)` achieved?

```
Sub MySub()

Dim arr() As Variant
Dim i As Long, j As Long

    arr = my_imported_function(...)

    For j = LBound(arr, 2) To UBound(arr, 2)
        For i = LBound(arr, 1) To UBound(arr, 1)
            Debug.Print "(" & i & "," & j & ")", arr(i, j)
        Next i
    Next j

End Sub
```

The function I'm calling from VBA looks like this:

```
@xw.func
def fetch_column(data_base, table, column_name):
    con = sql_connection(data_base)
    cur = con.cursor()
    values = []
    cur.execute("SELECT " + column_name + " FROM " + table)
    response = cur.fetchall()
    for idx, item in enumerate(response):
        values.append(''.join(item))
    con.close()
    return values
```

**Comment by fzumstein** [comment]
You'll most likely have some sort of row object from your SQL driver--transform it into lists of list or tuples of tuples and you should be good. For example, this works with the example for the docs:

```
@xw.func
def my_imported_function():
    return [[1, 2], [3, 4]]
```
