### ISSUE TITLE
AssertError:read can not have position excceed buffer length

### ISSUE THREAD

**Issue by dipranjan** [xlwings/xlwings#1566]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.22.0, Office 365, Python 3.7
```
---------------------------
Error
---------------------------
AssertError:read can not have position excceed buffer length



Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------
```

#### Describe your issue (incl. Traceback!)

From Python everything runs fine, issue happens when it is triggered from excel. The goal is to read input data from excel, load a saved Machine learning model, get the output and send it back to excel.
[price_predictor.zip](https://github.com/xlwings/xlwings/files/6344334/price_predictor.zip)

All files are attached

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by dipranjan** [comment]
It was related to the virtual environment, I think the message could have been a little clear. Anyways closing this.

**Comment by sildolfogomes** [comment]
How did you solve?
