### ISSUE TITLE
Read Excel formula value and not formula on Linux(any workaround?)

### ISSUE THREAD

**Issue by abhoiteHV** [xlwings/xlwings#1567]
#### OS (e.g. Windows 10 or macOS Sierra)
CentOS
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Python 2.6.8
xlwings 
0.23.1
#### Describe your issue (incl. Traceback!)
[xlwings.docx](https://github.com/xlwings/xlwings/files/6355685/xlwings.docx)

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

**Please find attached document with all the details.**

from openpyxl import Workbook
from openpyxl.utils import get_column_letter
from openpyxl import Workbook
from openpyxl import load_workbook
import xlwings as xw
# import pythoncom
import pandas as pd
import csv

fname='/opt/riskapi/e.xlsx'
wb = Workbook()
wb = load_workbook(fname)
ws1 = wb['Sheet1']
#
ws1['A10']=30000
ws1['A11']=40000

wb.save(fname)
# wb.close()

####
# pythoncom.CoInitialize()

excel_app = xw.App(visible=False)
excel_book = excel_app.books.open(fname)
excel_book.save()
excel_book.close()
excel_app.quit()

wb = load_workbook(fname, data_only=True)
ws1 = wb['Sheet1']

print(ws1['J18'].value)

print(ws1['J18'])
#Gives below result
# =INDIRECT("j"&MATCH(C17,K11:K14,0)+10)

calculatedRate = ws1['J18'].value

print(calculatedRate)
```

Traceback (most recent call last):
  File "pandas.py", line 9, in <module>
    import xlwings as xw
  File "/opt/riskapi/venv/lib64/python3.6/site-packages/xlwings/__init__.py", line 11, in <module>
    from . import _xlmac as xlplatform
  File "/opt/riskapi/venv/lib64/python3.6/site-packages/xlwings/_xlmac.py", line 10, in <module>
    import aem
ModuleNotFoundError: No module named 'aem'

**Comment by fzumstein** [comment]
xlwings only runs on macOS and Windows, see: https://docs.xlwings.org/en/stable/installation.html which is also very clearly stated in the Error you get when you try to install it via pip.
Use openpxyl with the data_only flag to get the values:

```
openpyxl.load_workbook("myfile.xlsx", data_only=True)
```

**Comment by abhoiteHV** [comment]
Thank you for your response!

Actually problem is openpyxl.load_workbook("myfile.xlsx", data_only=True) works only after I open Excel manually save and close it.
I used below code for that. After using below code I am able to read the Excel formula value.

excel_app = xw.App(visible=False)
excel_book = excel_app.books.open(fname)
excel_book.save()
excel_book.close()
excel_app.quit()

I am not sure why Excel is not reading the formula value using data_only=True 

Is there any issue with my code?

Thanks!

**Comment by fzumstein** [comment]
no, but it will only run on macOS/Windows. You should get look for support from OpenPyXL as you should not be required to open it.
