### ISSUE TITLE
How to create a password protect copy of the excel file used with xlwings? 

### ISSUE THREAD

**Issue by Rachid70** [xlwings/xlwings#1568]
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
At the moment, you would have to go via the ".api" workaround: 

```
import xlwings as xw

book = xw.Book()
book.api.SaveAs(r'C:\path\to\withpassword.xlsx', Password='password')
```

**Comment by Rachid70** [comment]
Yes it worked for me too. Thank you 
Can I make the file read only in a similar way?

**Comment by fzumstein** [comment]
Try this:

```python
import xlwings as xw
from xlwings.constants import FileAccess

book = xw.books.active

book.api.ChangeFileAccess(Mode=FileAccess.xlReadOnly)
```

**Comment by wobo-evan** [comment]
Hi - would this be possible with MacOS? It uses appscript, not pywin32, so the api.SaveAs method doesn't work and I haven't been able to find an equivalent!

@fzumstein

**Comment by fzumstein** [comment]
It's a bit harder to workaround on macOS due to the path handling, but it would be trivial to build it in. Basically, you'd have to provide the `password` argument here:

https://github.com/xlwings/xlwings/blob/master/xlwings/_xlmac.py#L321-L333

I'll try to include support for this in one of the next releases.

**Comment by wobo-evan** [comment]
@fzumstein thank you so much!! I've been trying to do it myself, but got as far as trying to inject <workbookProtection> XML tags into the underlying .zip structure. When that still allowed read-only access, I gave up haha. I never knew encrypting a workbook would be so hard...

**Comment by vishalkumarpatel1610** [comment]
@fzumstein 

> 

Do we have any function for this now? or still be using a workaround? Also what if I have already files and want to save as with a new name and make them password protected?

**Comment by fzumstein** [comment]
See https://docs.xlwings.org/en/latest/api/book.html#xlwings.Book.save

**Comment by vishalkumarpatel1610** [comment]
it works fine - but it opens up an excel file right away after the execution.
