### ISSUE TITLE
license key error

### ISSUE THREAD

**Issue by basicx-shivani** [xlwings/xlwings#1572]
once I clicked on run python I am getting an 
![Untitled](https://user-images.githubusercontent.com/82450270/116771277-a914d400-aa67-11eb-9e7b-bcf9e9fa42df.png)
invalid license key error.
even I a not able to import Udf also.
I want to interface python with excel through xlwing

**Comment by fzumstein** [comment]
Hi @basicx-shivani, please fill in the answers to the question on the template (like which version you're using etc.)

**Comment by basicx-shivani** [comment]
Python 3.8.5
Xwings version: 0.23.1

**Comment by fzumstein** [comment]
Does this happen with a new project from scratch? i.e. generated via `xlwings quickstart testproject`?

**Comment by basicx-shivani** [comment]
No, it happen when I made a python file and generate excel file by xlwings

**Comment by fzumstein** [comment]
It looks to me that a) you may not run on the latest version of the add-in and b) you may use a sheet with embedded python code but without pro license key?

**Comment by basicx-shivani** [comment]
thank you, 
resolved
