### ISSUE TITLE
Is is possible to use run main when the excel file has a different name to the .py file?

### ISSUE THREAD

**Issue by lancetrance350** [xlwings/xlwings#1573]
#### I want to run a python script in excel using run main, but I need the excel file to have a different name to that of the .py file. Specifically, I want my excel file to be called MyFile_Mar21.xlsm and my python file to be called MyFile.py. This would allow me to have multiple excel files with different date extensions, but where all of them point to the same .py file.

I have tried editing the RunPython call in VBA to remove characters from the string name, but xlwings still ends up looking for the full excel file name (i.e. it looks for MyFile_Mar21.py instead of MyFile.py).

Any pointers greatly appreciated.

```python
# ---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "<string>", line 1, in <module>

ModuleNotFoundError: No module named 'NLURPremRes_Mar21'

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
Sure thing, you just need to write the following VBA wrapper:

```vb
Sub WhateverNameYouWant()
    RunPython "import MyFile; MyFile.my_function()"
End Sub
```

I know that the docs are bad currently, so you may want to give my new book  a read where I lay out exactly this problem in chapter 10 (there's a free 30-day trial via the O'Reilly platform, as provided by the link on: https://www.xlwings.org/book)
