### ISSUE TITLE
Macros not getting executed properly 

### ISSUE THREAD

**Issue by Chaitanyachavali** [xlwings/xlwings#1576]
#### OS
>  macOS BigSur

#### Versions of xlwings, Excel and Python 
> xlwings - 0.23.1
> Excel - Microsoft Excel 16.48 (Microsoft 365 Subscription)
> Python - 3.8.2

#### Describe your issue 
I made simple excel [test2.xlsx](https://github.com/xlwings/xlwings/files/6429931/test2.xlsx). Have 3 sheets, first sheet have some values, second have some references from sheet1 and third have some values.
Now I have made a macro to take the values on Sheet3 and pick some on Sheet2 and multiply. As here (this macro is on sheet3):
```VB
Sub TestMacro()
Dim cell As Range
Dim count As Integer
count = 1
For Each cell In Range("A1:A10")
    cell.Offset(0, 3).Value = Sheets("Sheet2").Range("B" & CStr(count)) * cell.Value
    count = count + 1
Next cell
End Sub
```
When I execute it on excel it works, but the same I do via xlwings it doesn't populate any data.

I have tried given some params to the function, selecting some specific sheet and update still didn't work. Those samples are:
```VB
Sub Test()
Set ws = Worksheets("Sheet3")
   ws.Range("E2").Value = 20
End Sub
--------------------------------------
Sub TestNew(number)
Set ws = Worksheets("Sheet3")
   ws.Range("E4").Value = number
End Sub
```
Above works with direct execution but not from python xlwings.

Also one thing I have observed is that even if I give some random macro which doesn't exists it would just execute without any error.
Here is the full python script for all above execution cases:
```python
import xlwings

def main():
    wb = xlwings.Book('/Users/chaitanya.reddy/Desktop/test2.xlsm')
    test_macro = wb.macro('TestMacro')
    test_macro()
    test_macro1 = wb.macro('Test')
    test_macro1()
    test_macro2 = wb.macro('TestNew')
    test_macro2(10)
    non_existing_macro = wb.macro('SomethingNotThere')
    non_existing_macro()
    wb.save()
    wb.close()
    print("done")

if __name__ == '__main__':
    main()
```

A bit clueless here on why the execute invocations on python doesn't seem to be reflecting also when there is no macro why isn't there any exceptions of sort. Am I missing anything fundamental here or any suggestions how can I get this sorted?

**Comment by fzumstein** [comment]
I can't replicate this issue (other than the uploaded Excel file being empty and in the `xlsx` instead of `xlsm` format).

**Comment by Chaitanyachavali** [comment]
Sorry @fzumstein I mistakenly attached a wrong excel. Not able to attach a
`xlsm` file here, github is not allowing files of that extension.
Attaching it via email, checking if this works.

**Comment by Chaitanyachavali** [comment]
@fzumstein Can't attach `xlsm` file here or via email, any suggesting how I can share across or how you generally take in `xlsm` files?

For now I have uploaded it `WeTransfer` and here is the [link](https://we.tl/t-WJHO6YGY97), it that's okay to take it from here else please suggest.

**Comment by fzumstein** [comment]
in general, zipping it up should work, but in this case, there's no need: I have added 2 sheets, and copied in your VBA code -- it worked for me, so can't really say what's happening on your end.

**Comment by fzumstein** [comment]
well, ok, I see you're saving it under a `Sheet`. Insert a Module instead and store the code there.

**Comment by Chaitanyachavali** [comment]
That's it, that's what I messed up 😅. Moving all the code to module works!
Thanks for the help @fzumstein !!

_Closing the issue_

**Comment by fzumstein** [comment]
Actually, you could have also left it there and fully qualify it like this:

```
wb.macro('Sheet1.NameOfMacro')
```

but this will not return values if it's a Function (Sub should work fine though). I specifically have a section about this in chapter 9 in my new book (there's a free 30-day trial via the O'Reilly platform, as provided by the link on: https://www.xlwings.org/book).
