### ISSUE TITLE
remove string from a column using  auto filter

### ISSUE THREAD

**Issue by Cbarrow98** [xlwings/xlwings#1585]
#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# prism_sheet.range("A7:F87").api.AutoFilter(Field=1, Criteria1="United States")

```

**Comment by fzumstein** [comment]
I haven't tried this out, but something like this might work:

```python
from xlwings.constants import CellType
yourrange.api.SpecialCells(CellType.xlCellTypeVisible).EntireRow.Delete()
```

Inspired by: https://www.launchexcel.com/excel-tutorial-how-to-use-vba-to-delete-filtered-rows-fast-but-not-delete-hidden-rows/

**Comment by Cbarrow98** [comment]
Hi Felix, 
 
Thanks for the suggestion, still working on this currently and cant seem to figure it out. Although, I found something similar workaround but not for xlwings which is frustrating but instead for xlsxwriter (https://xlsxwriter.readthedocs.io/working_with_autofilters.html) which lets you filter strings and conditions from a column. Maybe look to add something similar with next update ?

**Comment by Cbarrow98** [comment]
Solved it you need to add operators "<>*yourstring*" like below

prism_sheet.range("A7:F87").api.AutoFilter(Field=1, Criteria1="<>*United States*")

**Comment by fzumstein** [comment]
well yes, it depends on which ones you want to keep and delete. I've tried this out now and would probably go for something like this:

```python
from xlwings.constants import CellType, Direction
...
myrange.offset(1).api.SpecialCells(CellType.xlCellTypeVisible).Delete(Shift=Direction.xlUp)
```
