### ISSUE TITLE
transpose ignored in using raw_value to set column data

### ISSUE THREAD

**Issue by john-drummond** [xlwings/xlwings#1587]
#### OS (e.g. Windows 10 or macOS Sierra)
Mac Big Sur
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
python 3.8.7 xlwings 23.0
#### Describe your issue (incl. Traceback!)

the second fills the column with 0 to 9, the first all with 0

I was expecting the transpose to work with raw_value
as well. Maybe that's what's supposed to happen.

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
thisbk = xw.Book.caller()
thisbk.sheets.active.range((1,1),(10,1)).options(transpose=True).raw_value = [0,1,2,3,4,5,6,7,8,9]
thisbk.sheets.active.range((1,1),(10,1)).options(transpose=True).value = [0,1,2,3,4,5,6,7,8,9]
```

**Comment by fzumstein** [comment]
Hi John, this is indeed a feature, as `options` currently only applies to `values`. You can, however, use the raw converter like this:

```python
thisbk.sheets.active.range((1,1),(10,1)).options('raw', transpose=True).value = [0,1,2,3,4,5,6,7,8,9]
```

I am actually thinking about deprecating `raw_value` to remove redundancies.

**Comment by john-drummond** [comment]
Fair enough - I went for [[I] for I in [0,1,2,3,4,5,6,7,8,9] ] on the right side. 
My vote would be not to deprecate raw_value - I'm shifting 100's of thousand or more cells (in separate arrays) on and off the sheet and raw_value even doing the above takes a 1/3 of the time.

**Comment by fzumstein** [comment]
options('raw').value and .raw_value should be equivalent speedwise. Let me
know if not.

**Comment by john-drummond** [comment]
fwiw options('raw', transpose=True).value didn't transpose the values for me.

I tried 
  ).options().raw_value = [[i] for i in  [0,1,2,3,4,5,6,7,8,9]]
  ).options('raw').value = [[i] for i in [0,1,2,3,4,5,6,7,8,9]]


An informal benchmark of pasting 100 times a range of a column of 1030 rows 
on six runs each time options().raw_value  was about a second faster than options('raw').value  on a run on four and slower on two on a run taking around 50 seconds

and as a single block the run takes under 3 seconds :)
It would be nice to be able to write non contiguous ranges saving lots of round trips, also to be able to shut off the screen updating between calls - e.g. in a loop to write the cells the screen updates each run

So nothing conclusive from this informal testing - given most of the time is the call back and forward it doesn't look significant.  Interestingly calling from python notebook in vscode raw is still significantly faster, but not 1/3 of the time.
My main concern at the moment is looking to reduce round trips
Thanks again

**Comment by fzumstein** [comment]
Thanks for looking into this and you are totally right about the options being ignored no matter whether going via `raw_value` or the `raw` converter, sorry about that!
