### ISSUE TITLE
Dates as numbers

### ISSUE THREAD

**Issue by edugca** [xlwings/xlwings#1588]
#### OS (e.g. Windows 10 or macOS Sierra)

Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

xlwings 0.23.2

#### Describe your issue (incl. Traceback!)

What is the easiest way of reading Excel dates as numbers (ints or floats) when they are passed as inputs to udfs?

**Comment by fzumstein** [comment]
No elegant solution at the moment, I am afraid, but you could do:

```python
@xw.func
@xw.arg('name', xw.Range)
def hello(name):
    return name.api.Value2
```

See https://docs.xlwings.org/en/stable/converters.html#xw-range-and-raw-converters and https://docs.xlwings.org/en/stable/missing_features.html

**Comment by edugca** [comment]
Thanks a lot! I believe this workaround would raise an error in case the argument is passed as an array by a different formula. I will test it, anyway.

**Comment by fzumstein** [comment]
no, it won't make any difference whether it's a single cell or array.
