### ISSUE TITLE
VBA: 'RunPython' throws error 'Could not load xlwings32-0.23.1.dll' after upgrade XLWINGS to 0.23.3.

### ISSUE THREAD

**Issue by ThomasAJ05** [xlwings/xlwings#1595]
#### 'RunPython' throws error 'Could not load xlwings32-0.23.1.dll' after upgrade XLWINGS to 0.23.3.

'xlwings32-0.23.1.dll' does not exist anymore. I did a search. Computer has been restarted.

I downgraded Xlwings to 0.23.1 to overcome the issue.

So I suspect the version must be stored in the Registry and does not get updated after an upgrade?
Could it be stored in the XALM file?

**Comment by fzumstein** [comment]
You always need to update the Python package together with the addin (or standalone VBA module), see: https://docs.xlwings.org/en/stable/installation.html#update
