### ISSUE TITLE
are UDFs compatible with the new microsoft office 365 ? related to #1166

### ISSUE THREAD

**Issue by Arcturus122** [xlwings/xlwings#1596]
Hello,

when doing the quickstart example for UDFs functions.

When opening the excel file it seems that Excel is freezing for a while before responding with the error :

could not activate Python COM server.

Would it be releted with the issue #1166 ?

As 365 is now an ecosystem of tools (all the MS office tools) maybe it could have broken xlwings ?

details :

i have python 3.8 virtual environment wiht xlwings 0.23.3 installed.
```
xlwings addin install
xlwings quickstart test
```

then i open test.xlsm. verify my Interpreter is ok.
the dll are well in my virtual env
i click on run main it works !
i click on Import functions or Restart UDF server, and then it freezes my Excel for a while before displaying an error message 
could not activate Python COM server.

Many thanks in advance for your help !

**Comment by Arcturus122** [comment]
thank you for your answer

i think i have a "click and run" installation then
![image](https://user-images.githubusercontent.com/31570340/118976495-5b5bff00-b975-11eb-8adf-ab0174467a38.png)
which is i think a locally installed one ?

here is my conf file 
![image](https://user-images.githubusercontent.com/31570340/118976890-d8877400-b975-11eb-9108-6311e73a3513.png)


i've already tried to force regenerate the config but without any success

**Comment by fzumstein** [comment]
yes, Excel installation looks good and the config file also. In that case, I don't have an answer right now, other than maybe rebooting or trying on a colleague's computer to determine if it's something local to your computer or not.

**Comment by Arcturus122** [comment]
i have tried to remove xlwings and re install also i have tried to reboot but no chance.
but i am thinking now. I think that for some reason i installed my python 3.8 from the microsoft store ... could it be possible that this is the reason why it does not work ?

**Comment by fzumstein** [comment]
ha, yes, somebody reported this before. Sorry didn't think of asking. Will need to put this all on the troubleshooting page...

**Comment by ericbmoreira** [comment]
I've found that different places for installing Python can cause issues. This also applies to using pip install or conda install. I have an Anaconda environment and always use conda forge to install anything. I will only use pip if it is not on conda. I also like to use a conda env for my xlwings use. Then you can update the config in the Excel ribbon or the other methods of config in xlwings.
