### ISSUE TITLE
Reading [#All/#Headers/#Data/#Totals] didn't work in xlwings (anymore ?)

### ISSUE THREAD

**Issue by TenchiMuyo1984** [xlwings/xlwings#1597]
Versions of
- OS: Windows 10 20H2
- xlwings: 0.23.3
- Excel: 2013
- Python: 3.8.0

It seems that these parameters didn't work in xlwings anymore:
[#All]
[#Headers]
[#Data]
[#Totals]

```python
import xlwings as xw

s_table_name = 'test1'
wb = xw.Book(r'D:\Python\test.xlsx')
d_table = xw.Range(f'{s_table_name}[String]') # this works
d_table1 = xw.Range(f'{s_table_name}[[#All],[String]]') # this didn't -> raise an exception -> see below
```

```python
Traceback (most recent call last):
  File "D:/Python/Experiments/test.py", line 6, in <module>
    d_table1 = xw.Range(f'{s_table_name}[[#All], [String]]').value # this didn't -> raise an exception
  File "D:\Python\Experiments\venv\lib\site-packages\xlwings\main.py", line 1244, in __init__
    impl = apps.active.range(cell1).impl
  File "D:\Python\Experiments\venv\lib\site-packages\xlwings\main.py", line 404, in range
    return Range(impl=self.impl.range(cell1, cell2))
  File "D:\Python\Experiments\venv\lib\site-packages\xlwings\_xlwindows.py", line 427, in range
    xl1 = self.xl.Range(arg1)
  File "D:\Python\Experiments\venv\lib\site-packages\xlwings\_xlwindows.py", line 66, in __call__
    v = self.__method(*args, **kwargs)
  File "C:\Users\marti\AppData\Local\Temp\gen_py\3.8\00020813-0000-0000-C000-000000000046x0x1x8.py", line 42299, in Range
    ret = self._oleobj_.InvokeTypes(197, LCID, 2, (9, 0), ((12, 1), (12, 17)),Cell1
pywintypes.com_error: (-2147352567, 'Ausnahmefehler aufgetreten.', (0, None, None, None, 0, -2146827284), None)
```

I tried these as well but raises the same exception:
```python
d_table1 = xw.Range(f'{s_table_name}[[#All]]')
d_table1 = xw.Range(f'{s_table_name}[#All]')
```

My code based on this post:
https://stackoverflow.com/questions/36392633/how-to-reference-excel-table-column-names-in-xlwings/36396797#36396797
I know, the example is quite old. `Workbook` was replaced with `Book()`, but with what was `[#All]` replaced?

I hope someone can help me. 

Edit: Sry, I posted the wrong (old) exception.

**Comment by fzumstein** [comment]
Are you using a non-English version of Excel by any chance? These keywords are language-specific.

**Comment by fzumstein** [comment]
In the meantime, the (almost) full API is also supported: https://docs.xlwings.org/en/stable/api.html#table

**Comment by TenchiMuyo1984** [comment]
> Are you using a non-English version of Excel by any chance? These keywords are language-specific.

Yes, I'm using a german version of excel 2013.
But the code in VBA (created with the macro recorder) has shown me this:
```
Sub Makro1()
    Range("test1[#All]").Select
End Sub
```
So, english.

I want to get the whole table and not the values (without the headers).
Or the Headers only, but both `[#All]` and `[#Headers]` give me the same exception.

**Comment by fzumstein** [comment]
Then it may be the separator: use `;` instead of `,`.

**Comment by TenchiMuyo1984** [comment]
> Then it may be the separator: use `;` instead of `,`.

I tried these as well:
```
d_table1 = xw.Range(f'{s_table_name}[[#All]]')
d_table1 = xw.Range(f'{s_table_name}[#All]')
```

There is no need for `,` or `;`.

But yes, I tried `;` as reparator as well, but got this:

```
Traceback (most recent call last):
  File "D:/Python/Experiments/test.py", line 6, in <module>
    d_table1 = xw.Range(f'{s_table_name}[[#All]; [String]]').value # this didn't -> raise an exception
  File "D:\Python\Experiments\venv\lib\site-packages\xlwings\main.py", line 1244, in __init__
    impl = apps.active.range(cell1).impl
  File "D:\Python\Experiments\venv\lib\site-packages\xlwings\main.py", line 404, in range
    return Range(impl=self.impl.range(cell1, cell2))
  File "D:\Python\Experiments\venv\lib\site-packages\xlwings\_xlwindows.py", line 427, in range
    xl1 = self.xl.Range(arg1)
  File "D:\Python\Experiments\venv\lib\site-packages\xlwings\_xlwindows.py", line 66, in __call__
    v = self.__method(*args, **kwargs)
  File "C:\Users\marti\AppData\Local\Temp\gen_py\3.8\00020813-0000-0000-C000-000000000046x0x1x8.py", line 42299, in Range
    ret = self._oleobj_.InvokeTypes(197, LCID, 2, (9, 0), ((12, 1), (12, 17)),Cell1
pywintypes.com_error: (-2147352567, 'Ausnahmefehler aufgetreten.', (0, None, None, None, 0, -2146827284), None)
```

**Comment by fzumstein** [comment]
In this case I don't know what's happening but I'd use the full API instead (link above)

**Comment by TenchiMuyo1984** [comment]
> In this case I don't know what's happening but I'd use the full API instead (link above)

Ok, I tried it, ad it "works" but to use a different implementation (API) didn't feel that good.
On the other hand, it looks stupid that I must know the name of the sheet to get access to the table. The name of the table is unique in the whole document.

Here as an example I tried and worked:
```
import xlwings as xw

s_file_name = r'xlwings_test.xlsx'
s_sheet_name = 'xlwings_sheet'
s_table_name = 'xlwings_table'
s_headline1 = 'Headline 1'

wb = xw.Book(s_file_name)
sht = wb.sheets[s_sheet_name]
tables = sht.tables[s_table_name]
```
Why isn't this possible as well?:
```
tables2 = wb.tables[s_table_name]
```

I talked about that thing with some python-devs on discord about that and they have the same problem (USA, UK, etc.)
Could it be, that my problem with:
```
xw.Range(f'{s_table_name}[[#All]]')
```
is a bug?

**Comment by fzumstein** [comment]
I followed the original Excel object model which only exposes tables, aka ListObjects as part of the sheet object. Apparently, the names are unique, so `mybook.tables` could be added, too. For now, you will have to loop through the sheets manually.

As for your examples, they all work over here, so unfortunately can't replicate them.

**Comment by fzumstein** [comment]
According to StackOverflow, you'd need to use `#Alle` in the German version despite VBA showing `#All`: https://stackoverflow.com/questions/36392633/how-to-reference-excel-table-column-names-in-xlwings/36396797?noredirect=1#comment119875603_36396797

**Comment by TenchiMuyo1984** [comment]
I saw the response as well, thanks. ^^
But what is with the other options?
- '#Headers'
- '#Data'
- '#Totals'

Will it be this?:
- '#Überschriften'
- '#Daten'
- '#Gesamt'

And why is it localized and not complete english?
Microsoft has changed the programming language in VBA from localization to english only in Office 1997.

**Comment by fzumstein** [comment]
According to https://de.excel-translator.de/translator/ it's:

```
[#Kopfzeilen]
[#Alle]
[#Daten]
[#Ergebnisse]
```

As to why it behaves like this I have no idea.

**Comment by TenchiMuyo1984** [comment]
I think it's a problem from Excel itself and not from your library.

But I've a request.
To avoid this issue, can you add a function in your library that translates the commands from english to the required language?
That the user is using all english, but it will translated into a different language, if it's required.
But the command in his (non english) language is stil possible.

As example (for german): 
Use '#All' in python, but will translated into '#Alle'
But '#Alle' will still works.
Same for `,` and `;`

Problem is:
When somone creates a program for his excel. He can never be sure, that a different user, with different langue still can run that code. It'll raise an exception.
When I send my code, with german commands, a person in the USA will got an exception, because his Excel didn't understand german.
Same for spanish, italian, french, etc...

**Comment by fzumstein** [comment]
The only thing the API is currently missing is `table_columns` and `row_columns` properties, otherwise, you can do everything in a robust way without having to care about any translation or regional settings:

![Screen Shot 2021-06-06 at 11 54 19](https://user-images.githubusercontent.com/2265504/120920193-f404b580-c6bd-11eb-87b8-0751cb35031c.png)

```python
import xlwings as xw

sheet = xw.sheets.active

# Get table body
print(sheet['Table1'].value)
print(sheet.tables['Table1'].data_body_range.value)

# Get column data
print(sheet['Table1[a]'].value)
print(sheet.tables['Table1'].data_body_range.columns[0].value)  # proper support for table_columns missing to be able to select by name

# Get column including header and total rows
print(sheet['Table1[[#All], [a]]'].value)
print(sheet.tables['Table1'].range.columns[0].value)

# Get header row for one column
print(sheet['Table1[[#Headers], [a]]'].value)
print(sheet.tables['Table1'].header_row_range.columns[0].value)

# Get total row for one column
print(sheet['Table1[[#Totals], [a]]'].value)
print(sheet.tables['Table1'].totals_row_range.columns[0].value)

# Two or more adjacent columns
print(sheet['Table1[[a]:[b]]'].value)
print(sheet.tables['Table1'].data_body_range.columns[0:2].rng.value)  # currently requires the rng hack
``` 

Closing this in favor of https://github.com/xlwings/xlwings/issues/1610
