### ISSUE TITLE
xlwings ribbon only showing partially on Mac

### ISSUE THREAD

**Issue by bsauvage1** [xlwings/xlwings#1598]
MacOs BigSur 11.3.1, Macbook Air (M1, 2020)
xlwings 0.23.3, Excel 16.49. python 3.9

The ribbon only shows partially, missing the "Conda", "UDFs", "Advanced" sections!

![image](https://user-images.githubusercontent.com/4017313/119118166-88cfa800-ba5c-11eb-84b3-16e8bd8f110d.png)

**Comment by fzumstein** [comment]
This is by design as these options are currently not supported (UDFs) or necessary (unlike on Windows, Conda works correctly on macOS by pointing to the path of interpreter in the Conda env).

**Comment by bsauvage1** [comment]
Hi Felix

Thanks. So 3 set-up/usage questions please:

0/ UDFs not supported: do you mean I can't create my own functions like on windows? or if I can, what is the procedure please ?

1/how do I setup the config file? Initially, only the Interpreter was setup, so I've tried to replicate what I had in windows but pointing to the relevant locations:
"INTERPRETER_MAC","/usr/local/Caskroom/miniforge/base/bin/python3.9"
"PYTHONPATH","/usr/local/PycharmProjects/pythonProject/ExcelSheets"
"CONDA PATH","/usr/local/Caskroom/miniforge/base/bin/python3.9"
"CONDA ENV","base"
"UDF MODULES","xlwings_addins"


2/ how do I activate debug mode ? Is the only way to add a config worksheet to each spreadsheet?

**Comment by fzumstein** [comment]
You'd just have to create a string in VBA. For example, if you wanted to provide a number that lives in cell A1 as the argument, you could do:

```vb
RunPython "import mymodule;mymodule.myfunction(" & Range("A1").Value & ")"
``` 

For strings, you'd have to add single quotes.

As for UDFs on macOS, I'll bet on Microsoft delivering this on their own over the next 1-3 years, so it's not on the roadmap right now for xlwings.

**Comment by bsauvage1** [comment]
Thank you very much. Really appreciate your help here. 
I guess this will have to do for the next 2-3 years!

**Comment by bsauvage1** [comment]
> You'd just have to create a string in VBA. For example, if you wanted to provide a number that lives in cell A1 as the argument, you could do:
> 
> ```vbnet
> RunPython "import mymodule; mymodule.myfunction(" & Range("A1").Value & ")"
> ```
> 
> For strings, you'd have to add single quotes.
> 
> As for UDFs on macOS, I'll bet on Microsoft delivering this on their own over the next 1-3 years, so it's not on the roadmap right now for xlwings.

Sorry one more question on that topic: assuming the python function returns something (either a value or an array) how can I assign it to a variable inside VBA? For example, the below doesn't work:
 ```vbnet
A = RunPython("import mymodule; mymodule.myfunction(" & Range("A1").Value & ")")
```

**Comment by fzumstein** [comment]
You can't, that's why I don't advertise it. You'd need to use UDFs instead (but they are Windows-only).

**Comment by bsauvage1** [comment]
ok clear, will use workaround functions to write the data inside specific excel ranges. Thanks

**Comment by bsauvage1** [comment]
when i run the above code from within a Sub, it's perfectly fine. But when trying to run it from a vba function, it fails: while the python is able to read arrays on the sheet, it can't write to them. Is this a limitation of an excel function not able to update arrays/cells that are different from where the function is called ?

**Comment by fzumstein** [comment]
yes

**Comment by bsauvage1** [comment]
thank you
