### ISSUE TITLE
`add_hyperlink` only works with one cell

### ISSUE THREAD

**Issue by pemocarlo** [xlwings/xlwings#1599]
Hi,
I tried to use the add_hyperlink method for range, but it is only applied to one cell.

Is there an equivalent to [`Hyperlinks.Add()`](https://docs.microsoft.com/en-us/office/vba/api/excel.hyperlinks.add)?

Thank you

**Comment by fzumstein** [comment]
yes, that implementation is currently a bit prehistoric...you may consider working around for now via `.api.Hyperlinks.Add()`, see: https://docs.xlwings.org/en/stable/missing_features.html

**Comment by carlosperezm** [comment]
Ah ok, I see. Thanks for the tip and for this nice library!

**Comment by fzumstein** [comment]
For what it's worth: I think the only solution to this is the following:

* Write the links as cell formulas: =HYPERLINK(url, [friendly_name]). For example, assume you want to write your links in A1, A2 etc. You could have your URLs in B1, B2 and the friendly names in C1, C2, then use xlwings to populate only the B and C columns (in cell A1, you'd write: =HYPERLINK(B1,C1) )

```python
mysheet['B1'].value = [
    ['https://www.xlwings.org', 'xlwings'],
    ['https://www.xltrail.com', 'xltrail'],
]
```
