### ISSUE TITLE
run xlwings module in pypy, but facing hard time, "No module named ''win32api", tried cmd : "pypy -m pip install pywin32", it returned error: Could not find a version that satisfies the requirement pywin32, No matching distribution found for pywin32

### ISSUE THREAD

**Issue by raaghulr** [xlwings/xlwings#1604]
Hi, I am trying to run xlwings module in pypy, but facing hard time, "No module named ''win32api", tried cmd : "pypy -m pip install pywin32", it returned error: Could not find a version that satisfies the requirement pywin32, No matching distribution found for pywin32
![pypy](https://user-images.githubusercontent.com/26132550/120013454-5e529180-bffe-11eb-980c-5271f2a1e96b.JPG)

_Originally posted by @raaghulr in https://github.com/xlwings/xlwings/issues/827#issuecomment-850527880_

**Comment by fzumstein** [comment]
dupe of #1603
