### ISSUE TITLE
xlwings.App.books.add() will generate 2 books first time after running an Excel

### ISSUE THREAD

**Issue by nicholasguan** [xlwings/xlwings#1608]
#### when i use xw.App.books.add() first time after running an Excel, the count of xw.App.books will increase 2. 
And i run the test<book.py it will generate an error in the case of test_add. And then, when i want to wb.save(), it will return an error-code:-1728 and can't save another default book, err message is :
>CommandError: Command failed:
>		OSERROR: -1728
>		MESSAGE: The object you are trying to access does not exist
>		COMMAND: app('/Applications/Microsoft Excel.app', newinstance=(0, 704684)).workbooks['工作簿11'].count(each=k.worksheet)

```python

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
app = xw.App(visible=True, add_book=False)
app.display_alerts=False
print(app)
print(app.books)
wb = app.books.add()
print(app.books)
```

**Comment by fzumstein** [comment]
Excel via xlwings behaves as if you start the application manually, i.e. you always get automatically an empty workbook. You aren't supposed to use the `add_book` parameter and it should disappear from the function definition:
https://github.com/xlwings/xlwings/issues/1545
