### ISSUE TITLE
Inserting into a named Excel Table in a Sheet and expanding thr Table

### ISSUE THREAD

**Issue by FireRedDev** [xlwings/xlwings#1609]
Hello! Is this supported? Basically in an excel sheet there is a named table orders which is empty except column headers. I want to insert the contents of a dataframe into that table and make it expand as much as needed. Is there a way to name access that table?

**Comment by fzumstein** [comment]
Yes, tables are supported: https://docs.xlwings.org/en/stable/api.html#table

https://docs.xlwings.org/en/stable/api.html#xlwings.main.Table.update is currently part of xlwings PRO, but you can obviously do the same with the open source version, you'd just need to take care of the cleaning/resizing yourself.
