### ISSUE TITLE
Transpose with formatting

### ISSUE THREAD

**Issue by Cbarrow98** [xlwings/xlwings#1611]
#### Currently trying to transpose a data range that is easily done with code below, however it just gives the raw value and does not keep the formatting of the original vertical range. Is it possible to transpose data and include the original formatting ?  

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# port_stats.range('B2').value = port_stats.range('A6:D53').options(transpose=True).value

```

**Comment by fzumstein** [comment]
You would need to apply/copy the format manually, for example:

```python
sheet['A1'].copy()
sheet['B1'].paste('formats')
```

**Comment by Cbarrow98** [comment]
port_stats = wb.sheets('Portfolio stats')
tried this in the form of port_stats['B2'].paste('formats')

However, I get the attribute error of "Range" object has no attribute 'paste' ?

**Comment by fzumstein** [comment]
you are definitely on xlwings 0.23.0 and not on an older version? `import xlwings;print(xlwings.__version__)`
