### ISSUE TITLE
Not able to close the excel file that is open by xlwings

### ISSUE THREAD

**Issue by Abhishekkini** [xlwings/xlwings#1619]
#### OS 
Windows 10 

#### Versions of xlwings, Excel and Python 
xlwings 0.23.3
Python 3.8.6
Office 365 
#### Description
I am new to xlwings,
The code below left an open instance of excel which is not shown and idk how to close it ,now every time I run any excel operation it gives me a [Errno13] permission denied.
I checked all permissions, everything is as need to be.  
There is an instance ~file.xlsx open when I see my VS code editor.
Although my code has .close() it doesn't close the open file
How do I close it? 
```python
# Your traceback here
Exception: [Errno 13] Permission Denied: 'filepath'
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import xlwings as xw
def write_to_excel(sheetname,df1,df2,df3,df4,df5)
    wb = xw.Book(r"filepath/file.xlsx")
    ws = wb.sheets(sheetname)  
    ws.cells(row,col).options(index=False, header=False).value = df1
    ws.cells(row,col).options(index=False, header=False).value = df2
    ws.cells(row,col).options(index=False, header=False).value = df3
    ws.cells(row,col).options(index=False, header=False).value = df4
    ws.cells(row,col).options(index=False, header=False).value = df5
    wb.save()
    wb.close()
```

**Comment by ericbmoreira** [comment]
Try quit() after .close(). I think that is what it is under. https://docs.xlwings.org/en/stable/api.html

**Comment by Abhishekkini** [comment]
I tried that it gives me this error:

Exception Type: com_error at function call

Exception Value: (-2147352567, 'Exception occurred.', (0, 'Microsoft Excel', 'Microsoft Excel cannot open or save any more documents because there is not enough available memory or disk space. \n\n• To make more memory available, close workbooks or programs you no longer need. \n\n• To free disk space, delete files you no longer need from the disk you are saving to.', 'xlmain11.chm', 0, -2146827284), None)

I have space on my disk

**Comment by fzumstein** [comment]
you'll need to write `wb.app.quit()`, just in case...

**Comment by Abhishekkini** [comment]
(-2147417848, 'The object invoked has disconnected from its clients.', None, None) getting this error when i am trying wb.app.quit() any solutions to this issue?

**Comment by fzumstein** [comment]
can you post (a simplified version of) your current version of the code to replicate?

**Comment by Abhishekkini** [comment]
```
import xlwings as xw
def write_to_excel(sheetname,df1):
    try:
            app = xw.App()
            wb = xw.Book(r"sample.xlsx")
            ws = wb.sheets(sheetname)  #Name of sheet where to append df
            ws.cells(5,1).options(index=False, header=False).value = df1
            wb.save(r"sample.xlsx")
            wb.close()
            wb.app.quit()
   
data = [['Alex',10],['Bob',12],['Clarke',13],['David','14']]
df1 = pd.DataFrame(data,columns=['Name','Age'],dtype=float)
write_to_excel("sample",df1)
```
the above code is an automation that runs every minute, could that be the reason of failure?
Also note that the sheet i am trying to write to is designed with format , formulas and sheets and all kind of stuff 
Iam getting this error now 
(-2147417848, 'the object invoked has disconnected from its clients.', none, none)
I have been facing a lot of such issues.

**Comment by fzumstein** [comment]
To work with a specific app (the one you're instantiating), you can't use `xw.Book`, as this uses the active app. Do this instead:

```python
app = xw.App()
wb = app.books.open(r"sample.xlsx")

...
app.quit()  # no need to go via wb
```

**Comment by Abhishekkini** [comment]
what if i dont want to instantiate then would my code look like -
```
wb = xw.Book(r"sample.xlsx")

. . .
wb.save(r"sample.xlsx")
wb.close()
wb.app.quit()
```

**Comment by fzumstein** [comment]
yes, but given your use case ("run every minute"), you'll run into the stability issues you describe: Excel wasn't made for unattended automation, so to make it reasonably stable, you have to work with new Excel instances.

**Comment by Abhishekkini** [comment]
@fzumstein , so i did that and it is closing the excel file but sometimes there is an excel process left hanging i am not sure why it is happening , but this also raised the below issues which are occuring like frequently -
```
(-2147023170, 'The remote procedure call failed.', None, None)
(-2146827284, 'OLE error 0x800a03ec', None, None)
```

**Comment by ericbmoreira** [comment]
Why do you need to open an Excel process and close the process every minute? What are you trying to do? I run a few different Excel processes, with active Python processes connected to them, and I leave them open. Is this some kind of a scheduled process? Because I use mscheduler to kick off processes intra-day, rather than Windows Scheduler or anything like that. It is a Python module so is not dependent on outside software. That way you could kick off whatever you are doing every minute but not have to start and kill a process every time. The actual loading of all of the Python modules and code will kill your performance if you are doing it every minute.

**Comment by Abhishekkini** [comment]
So my goal is to download an excel file from a site where they upload it , update the respective data I have in database to Excel every minute and I have to insert different data into five different pages in a worksheet and I have 3 worksheets as such in the same file which I have to update and upload it back to that site where people will update some values in it in different columns , then I have one more automation which downloads the same file and does read_excel from the same file. All this is done in a RDC and I'm using windows scheduler to run a python file which does all these tasks and a few more excel reading/writing on different files using openpyxl .

**Comment by ericbmoreira** [comment]
You can run into OLE issues when you have other Excel processes running when another one is trying to process something. Downloading a workbook, updating it with data from a database table as well as doing read-only processing on the same data every minute seems like a process that is begging to be fixed.

So the data that you are downloading every minute is changing every time you download it? I'm sure there is a lot going on to simplify it as this, but it sounds like the data needs to be on a database that everyone has access to and you just skip Excel.

Does your process work now if it is not run every minute? As in, can you process everything without killing the process and it works? If so, then the frequency of your process is causing the problem.

**Comment by Abhishekkini** [comment]
@ericbmoreira , Yes there is alot going on . if i don't kill the process i get errors in downloading as the file is being used. So, ill get [Errno 13] Permission denied. My process is working fine when i kill it once its done writing, even when it runs every minute .It might take more than a minute sometimes to finish which i need to optimize , but i noticed that windows scheduler runs tasks in a sequence so it waits for my first task to complete then it repeats so there is no overloading happening ,just sometimes i run into these excel issues and they are just causing alot of trouble in the application.

**Comment by fzumstein** [comment]
I believe this will be solved by using app as a context manager, see: I believe https://docs.xlwings.org/en/latest/whatsnew.html#v0-24-3-jul-15-2021
