### ISSUE TITLE
Access to Chart  Tab Header and Footer

### ISSUE THREAD

**Issue by josiahgerber** [xlwings/xlwings#162]
I can update sheet headers and footers with the following code.

```
xlwings.Sheet(1).xl_sheet.PageSetup.CenterFooter = '''&"Arial"&6&F'''
```

Charts on their own tab aren't changed with the command above so I tried the following:

```
xlwings.Chart(1).xl_chart.PageSetup.CenterFooter = '''&"Arial"&6&F'''
```

But I get this error: `AttributeError: ChartObjects.PageSetup`.

Chart headers on their own tab can be updated in VBA using code similar to `chart.PageSetup.CenterFooter`. When I run `print(xlw.Chart(1).xl_chart)` I can see that the ChartObject exists `<COMObject ChartObjects>`. Am I using the COM object incorrectly or is this a limitation of zlwings?

By the way, xlwings is awesome!

**Comment by fzumstein** [comment]
`xl_chart` translates into something like `Sheets(1).ChartObjects(1)`, see https://github.com/ZoomerAnalytics/xlwings/blob/master/xlwings/_xlwindows.py#L289. I believe that a full-tab chart is accessed differently.

If you can paste the exact VBA code that works, I am sure isn't difficult to use it from the underlying pywin32 object (e.g. `xl_sheet`)
