### ISSUE TITLE
classes from Excel python does not work

### ISSUE THREAD

**Issue by niubiguy** [xlwings/xlwings#1627]
#### Describe your issue (incl. Traceback!)

Hello Sir. At first my problem was similar to [this](https://github.com/xlwings/xlwings/issues/647). But I found another problem 
```python
TypeError: only integer scalar arrays can be converted to a scalar index
    if (self.Domain[idxElement] == UnionFind.NOSET): return UnionFind.NOSET
  File "c:\users\lab4\desktop\pv-002\UnionFin.py", line 93, in Find
    RightNeighborComponent = UF.Find(RightIdx)
  File "c:\users\lab4\desktop\pv-002\myproject.py", line 36, in extremos_dominantes
    ret = func(*args)
  File "C:\Users\Lab4\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\udfs.py", line 502, in call_udf
    res = call_udf(script, fname, args, this_workbook, FromVariant(caller))
  File "C:\Users\Lab4\AppData\Local\Continuum\anaconda3\lib\site-packages\xlwings\server.py", line 198, in CallUDF
    return func(*args)
  File "C:\Users\Lab4\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Users\Lab4\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Users\Lab4\AppData\Local\Continuum\anaconda3\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

I saved the following python file, UnionFin.py with the code

```python
class UnionFind:

NOSET = -1
    
    def __init__(self, NumElements):
        """Initializes the domain with @NumElements elements living in zero sets."""
        self.Domain = [int(UnionFind.NOSET)] * NumElements
        self.NumSets = 0
...
def Find(self, idxElement):
        """
        Finds the ID of the set to which the element @idxElement belongs.
        This function does not use compression, and therefore does not change any underlying data.
        """
        if (self.Domain[idxElement] == UnionFind.NOSET): return UnionFind.NOSET

        #~ Find the root of the set
        while True:
            idxElement = self.Domain[idxElement]
            if (idxElement == self.Domain[idxElement]): break;

        #~ Return root of set == ID of set
        return idxElement
...
```
I generate the following xlwings python code in a file myproject.py and myproject.xlsm

```python
import xlwings as xw
import numpy as np
import matplotlib.pyplot as plt
import UnionFin as uuff

@xw.func
@xw.arg('data', ndim = 2)

def extremos_dominantes(data):
     
    NumElements = len(data)
    
    SortedIdx = np.argsort(data, kind='stable')

    UF = uuff.UnionFind(NumElements)

    ExtremaAndPersistence = []
   
    for idx in SortedIdx:
        
        LeftIdx = max(idx - 1, 0)
        RightIdx = min(idx + 1, NumElements - 1)
        
        NeighborComponents = []
        LeftNeighborComponent = UF.Find(LeftIdx)
        RightNeighborComponent = UF.Find(RightIdx) 
....
```
help me please. I am newbie with xlwings be patient with me.

**Comment by fzumstein** [comment]
This looks like an issue with what you do in pandas, not xlwings:
https://stackoverflow.com/questions/50997928/typeerror-only-integer-scalar-arrays-can-be-converted-to-a-scalar-index-with-1d/50997969

**Comment by niubiguy** [comment]
Hello sir, thank you for your reply.

When I run it in Python it works fine, but if I want to apply with xlwing it fails.

**Comment by fzumstein** [comment]
In that case, please add a minimal sample that reproduces the issue.

**Comment by niubiguy** [comment]
As I said before https://github.com/xlwings/xlwings/issues/1627#issue-926652925 this problem is in Excel. However, in in python it works fine.

This is the main file
[myproject.txt](https://github.com/xlwings/xlwings/files/6711337/myproject.txt)

Here is a class file
[UnionFin.txt](https://github.com/xlwings/xlwings/files/6711338/UnionFin.txt)

When I use in Excel with xlwings it fails.

**Comment by fzumstein** [comment]
I'd need also need sample call, i.e. what are you using for `data`.

**Comment by niubiguy** [comment]
data = np.array([2.0, 5.0, 7.0, -12.0, -13.0, -7.0, 10.0, 18.0, 6.0, 8.0, 7.0, 4.0])
# In Excel (column A1:A12)

# To apply
extremos_dominantes(data)

**Comment by fzumstein** [comment]
Looks like your function returns something like `[(0, 1)]` so you'd need to clean this up into either `[0, 1]` or `(0, 1)` before returning to Excel.
