### ISSUE TITLE
modify PythonPath when using xlwings on different codes

### ISSUE THREAD

**Issue by IbanLavault** [xlwings/xlwings#1629]
Hi, i'm simply wondering how to change pythonpath when executing "RunPython" function on vba (using xlwings). To be clear about my issue, i'm currently trying to use "RunPython" function on 3 different projects (that have different paths) but once i settup manually the PYTHONPATH right here
![image](https://user-images.githubusercontent.com/60031903/123064415-8c18d380-d40e-11eb-89b5-e798999ba46f.png)
It accounts for the 3 files. 
So maybe there is a command line to input in the vba code directly in order to modify that path while launching the code.

Thanks for your answer 

(config :
Windows 10
xlwings -- v0.23.4
Excel -- Office 365
Python -- 3.8.8)

**Comment by fzumstein** [comment]
You can use a workbook-specific config sheet to set the PYTHONPATH for each workbook individually:
https://docs.xlwings.org/en/stable/addin.html#workbook-config-xlwings-conf-sheet

**Comment by IbanLavault** [comment]
thanks a lot
