### ISSUE TITLE
keyerror while running xlwings tutorial macro 

### ISSUE THREAD

**Issue by EthanTheMathmo** [xlwings/xlwings#1631]
#### 
python 3.8
xlwings v 0.23.4
Excel version: Microsoft® Excel® for Microsoft 365 MSO (16.0.14026.20294) 64-bit 

#### Describe your issue (incl. Traceback!)
I was working through the quickstart tutorial. I made an excel file and python file called heart.py and heart.xlsm using the command ```xlwings quickstart heart ``` (I was then going to copy a dataset of health data and experiment).  However, when I ran the module command 
```Sub SampleCall()
    mymodule = Left(ThisWorkbook.Name, (InStrRev(ThisWorkbook.Name, ".", -1, vbTextCompare) - 1))
    RunPython ("import " & mymodule & ";" & mymodule & ".main()")
End Sub
```

This then gives me the following error message

```
---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "C:\Users\Ethan-tuna\AppData\Roaming\Python\Python38\site-packages\xlwings\_xlwindows.py", line 466, in __call__

    return Book(xl=self.xl(name_or_index))

  File "C:\Users\Ethan-tuna\AppData\Roaming\Python\Python38\site-packages\xlwings\_xlwindows.py", line 156, in __call__

    v = self._inner(*args, **kwargs)

  File "C:\Users\ETHAN-~1\AppData\Local\Temp\gen_py\3.8\00020813-0000-0000-C000-000000000046x0x1x9.py", line 41312, in __call__

    ret = self._oleobj_.InvokeTypes(0, LCID, 2, (13, 0), ((12, 1),),Index

pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147352565), None)



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "c:\users\ethan-tuna\documents\excel plugin experiments\openpyxl test\heart\heart.py", line 6, in main

    wb = xw.Book.caller()

  File "C:\Users\Ethan-tuna\AppData\Roaming\Python\Python38\site-packages\xlwings\main.py", line 613, in caller

    return cls(impl=app.books[name].impl)

  File "C:\Users\Ethan-tuna\AppData\Roaming\Python\Python38\site-packages\xlwings\main.py", line 80, in __getitem__

    return self(key)

  File "C:\Users\Ethan-tuna\AppData\Roaming\Python\Python38\site-packages\xlwings\main.py", line 51, in __call__

    return self._wrap(impl=self.impl(name_or_index))

  File "C:\Users\Ethan-tuna\AppData\Roaming\Python\Python38\site-packages\xlwings\_xlwindows.py", line 468, in __call__

    raise KeyError(name_or_index)

KeyError: 'c:\\users\\ethan-tuna\\documents\\excel plugin experiments\\openpyxl test\\heart\\heart.xlsm'



Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------

```

I am not sure what is going wrong, as I installed the pywin dependencies, and made sure to use the latest version of xlwings. I also tried running the second example here https://www.xlwings.org/examples but I also got the key error problem

**Comment by fzumstein** [comment]
Can you double-check what's the version shown on your excel add-in?

**Comment by EthanTheMathmo** [comment]
ah ok. It says version 0.17.1 there, but I downloaded it yesterday so thought it would be the latest version

**Comment by fzumstein** [comment]
I don't see a way that this could have happened if you followed the docs and ran `xlwings addin install`, see: 
https://docs.xlwings.org/en/stable/addin.html#installation

Did you download and install the add-in manually?

**Comment by EthanTheMathmo** [comment]
I installed using the xlwings addin install command. I just uninstalled and reinstalled, and it had the same issue.

**Comment by fzumstein** [comment]
then you may not run the command from an environment where the correct version of xlwings is installed. When you run any `xlwings` command on the command prompt, it'll first print the version number. You may also want to run `pip freeze` or `conda list` to double check.

**Comment by EthanTheMathmo** [comment]
the command prompt says it is running version 0.17.1. As I installed yesterday I would expect the version to be correct. I am going to try setting up on my friend's computer and see if that avoids the problem

**Comment by fzumstein** [comment]
try `pip install xlwings --upgrade` or `conda upgrade xlwings`, depending on how you installed it. 0.17.1 is from 1.5 years ago. I am closing this issue as it will be fixed once you manage to upgrade.

**Comment by EthanTheMathmo** [comment]
Thank you very much for helping me out! I ran those commands, and in both instances it seemed to be upto date, yet run the older version. I have asked this as a separate question on stack exchange

```PS C:\Users\Ethan-tuna> pip3 show xlwings
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Name: xlwings
Version: 0.24.0
Summary: Make Excel fly: Interact with Excel from Python and vice versa.
Home-page: https://www.xlwings.org
Author: Zoomer Analytics LLC
Author-email: felix.zumstein@zoomeranalytics.com
License: BSD 3-clause
Location: c:\users\ethan-tuna\appdata\roaming\python\python38\site-packages
Requires: pywin32
Required-by:```

**Comment by fzumstein** [comment]
You may also give Anaconda or Miniconda a try, they make it easier to get started...
