### ISSUE TITLE
When I write "May 2020" in the xls worksheet, it is automatically changed to "May-20", how can I stop this behavior. I have tried all the methods I can think of. Please help me, thanks

### ISSUE THREAD

**Issue by lemisky** [xlwings/xlwings#1635]
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here
nothing
```
When I write "May 2020" in the xls worksheet, it is automatically changed to "May-20", how can I stop this behavior. I have tried all the methods I can think of. Please help me, thanks

**Comment by lemisky** [comment]
@fzumstein Please help me, thanks 🌹

**Comment by tagomatech** [comment]
Below is a non technical help.

From `Excel `side, you can try to set the type of that cell as `Text` or adding a single `'` before your actual value (e.g. `'May 2020`).

From xlwings perspective you can do as follows:

```
import xlwings as xw

wb = xw.Book()
sht = xw.sheets[0]

# get 'May-20'
sht.range('A1').value = 'May 2020'

# get 'May 2020'
sht.range('A2').api.NumberFormat = '@'
sht.range('A2').value = 'May 2020'
```

**Comment by lemisky** [comment]
@tagomatech 
Thank you very much, this is exactly what I need, and it solved my problem perfectly. Thanks here.

**Comment by lemisky** [comment]
The names of "NumberFormat" and "number_format" make novices a little confused.

Set global format `sheet.cells.number_format = '@'`

**Comment by fzumstein** [comment]
It's always `number_format`, you don't need to go via api workaraound. I've updated your sample, also see: 
https://docs.xlwings.org/en/stable/api.html#xlwings.Range.number_format

**Comment by lemisky** [comment]
> It's always `number_format`, you don't need to go via api workaround. I've updated your sample, also see:
> https://docs.xlwings.org/en/stable/api.html#xlwings.Range.number_format

thank you very much 🌹
