### ISSUE TITLE
NameError: name 'Environment' is not defined

### ISSUE THREAD

**Issue by miriam-z** [xlwings/xlwings#1637]
#### OS (e.g. Windows 10 or macOS Sierra)
BigSur
11.4

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Python 3.9.5
xlwings 0.24.1
Excel 16.16.27 (201012)

#### Describe your issue (incl. Traceback!)

```
import datetime
import os

import psycopg2
import pandas as pd
import pandas.io.sql as sqlio
import xlwings as xw
from xlwings.pro.reports import create_report

try:
    connection = psycopg2.connect(user="user",
                                  password="password",
                                  host="myreports.sample.io",
                                  port="5437",
                                  database="sample_db")

    cursor = connection.cursor() 

    xw.Book(input_template).set_mock_caller()
    template = xw.Book.caller()
    template_path = template.fullname
    report_path = os.path.join(os.path.dirname(template.fullname), output_file)
    app = template.app

  (not all shown)
   
   # OSERROR: -50, 
   # Parameter error, 
   # COMMAND: app(pid=95134).workbooks['sample_report.xlsx'].save(timeout=-1)
    wb = create_report(template_path, report_path, app=app, **data) 


```

If I run above code

(.venv) python sample.py

Two Excel files open accordingly but also

File "$HOME/sample/.venv/lib/python3.9/site-packages/xlwings/pro/reports/main.py", line 73, in render_template
    env = Environment()
NameError: name 'Environment' is not defined
 

But if:

(.venv) python3 sample.py
ModuleNotFoundError: No module named 'psycopg2'

 
(.venv) pip3 list
 
Package         Version
--------------- -------
appscript           1.1.2
cffi                      1.14.5
cryptography    3.4.7
numpy                1.21.0
pandas               1.2.5
pip                      21.1.3
psutil                5.8.0
psycopg2        2.9.1
pycparser        2.20
python-dateutil 2.8.1
pytz                 2021.1
setuptools      57.0.0
six                 1.16.0
wheel           0.36.2
xlwings         0.24.1

**Comment by fzumstein** [comment]
Hi @miriam-z, `create_report` requires `Jinja2` as a dependency (the error is currently not easy to understand, agreed!). Install it like so:

```
pip install Jinja2
```
As for the psycopg2 issue, try the following (this uses precompiled wheels):

```
pip install psycopg2-binary
```

**Comment by scheung38** [comment]
Yes but if Python and Python3 commands resolve to the same version of 3.9.5 then not sure why different responses.

**Comment by miriam-z** [comment]
After pip install Jinja2 and psycopg2-binary, fixed the name ‘Environment’ is not defined, opened the two Excels, but:

.venv/lib/python3.9/site-packages/aeosa/appscript/reference.py”, line 518, in __call__
    raise CommandError(self, (args, kargs), e, self.AS_appdata) from e
appscript.reference.CommandError: Command failed:
                OSERROR: -50
                MESSAGE: Parameter error.
                COMMAND: app(pid=61152).workbooks[‘2021_06_27_hb_daily_report.xlsx’].save(timeout=-1)

**Comment by fzumstein** [comment]
Can you paste a full code sample to reproduce the issue? currently there is no `create_report` call anymore in your sample.

**Comment by miriam-z** [comment]
located issue of create_report(), when this returns OSERROR: -50 is this related to only having trial license or that Excel is read-only?

**Comment by fzumstein** [comment]
No, it's an unrelated error, nothing to do with the license key. Does running a quickstart project work?

**Comment by fzumstein** [comment]
Instead of `NameError: name 'Environment' is not defined`, xlwings should complain that Jinja2 is not installed when using the reports package, same as it does with cryptography.
