### ISSUE TITLE
From openpyxl to xlwings

### ISSUE THREAD

**Issue by fat-tails** [xlwings/xlwings#1639]
My task: automate some calculations in an already-existing excel spreadsheet with macros (xlsm) in Python.

Problem: I did that with openpyxl only to later realise that macros aren't preserved once you save the new file (if you save the new file as xlsm it gets corrupted, if you save it as xlsx - macros aren't preserved). I tried a few proposed solutions online - such as keep_vba=True, read_only =False (none of which worked) in order to save back a well-functioning xlsm.

I thought I should probably do the data manipulation in xlwings instead, which supposedly preserves the macros. However, I've struggled to adapt my openpyxl code to xlwings. Can anyone help me do this?
 
(conda 4.10.1)

```
#Z-scores

df_excel=pd.read_excel("zz3.xlsm", engine="openpyxl")

df_name=df_excel[["Name"]]

df_excel=pd.read_excel("zz3.xlsm", engine="openpyxl", index_col=None, usecols="GN:IV")

df_zscore=(df_excel-df_excel.mean())/df_excel.std()

df55=pd.DataFrame()
df55=df_zscore.copy()
df55["Name"]=df_name.copy()

cols=list(df55.columns)
cols=[cols[-1]]+cols[:-1]
df55=df55[cols]
print(df55)

writer=pd.ExcelWriter("zz3.xlsx", engine="openpyxl")
df55.to_excel(writer, sheet_name="Skew scores", index=False)
writer.save()

#12-month moving averages 

df_excel=pd.read_excel("zscores.xlsm", engine="openpyxl")
df_ma12=df_excel.rolling(12).mean()
print(df_ma12)

```

**Comment by fzumstein** [comment]
You might get lucky with XlsxWriter, see here: https://stackoverflow.com/a/28170939/918626 which would be closer to your current solution.

**Comment by fat-tails** [comment]
> You might get lucky with XlsxWriter, see here: https://stackoverflow.com/a/28170939/918626 which would be closer to your current solution.

Thanks for your reply @fzumstein. My problem with xlsxwriter is that it doesn't read my original xlsm file (xlsx extension is ok).

**Comment by fzumstein** [comment]
You're right. Well, for xlwings, this should basically give you a good start:
https://docs.xlwings.org/en/stable/quickstart.html#scripting-automate-interact-with-excel-from-python
