### ISSUE TITLE
api.merge() freezes the program

### ISSUE THREAD

**Issue by kameaplli** [xlwings/xlwings#1642]
#### Versions of xlwings, Excel and Python (0.23.4, Office 365, Python 3.9.6)

Hi, 

I am trying to merge a range of cells using api.merge() and the program freezes and terminates after a few minutes. No tracebacks. If I remove api.merge() it just works. 

```python

    app = xw.App(visible=False)
    res_wbook = app.books.add()
    a_sheet = report_wbook.sheets.add('Test')
   
    # head_start and head_end are the cell values derived from other variables
    a_sheet.range(f'{head_start}:{head_end}').api.merge()

```

**Comment by fzumstein** [comment]
No need to use api: https://docs.xlwings.org/en/stable/api.html#xlwings.Range.merge
