### ISSUE TITLE
Can't pack data into an AEDesc (unsupported type): Decimal ?

### ISSUE THREAD

**Issue by miriam-z** [xlwings/xlwings#1644]
#### OS (e.g. Windows 10 or macOS Sierra)
Big Sur 11.4

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Excel 16.50
Python 3.9.5

#### Describe your issue (incl. Traceback!)

![Screenshot 2021-07-02 at 12 06 01](https://user-images.githubusercontent.com/19760229/124270905-b2d4b980-db34-11eb-92cf-6aa8b942682f.png)
```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
wb = create_report(template, report_path, app=app, **data)
 
```
where template is path to input xlsx
report_path:  is path to output xlsx
app Excel object
data kv pair

**Comment by fzumstein** [comment]
Hi @miriam-z, Excel doesn't support Decimals and xlwings doesn't currently convert them automatically, so you'd have to transform them first into floats...

**Comment by miriam-z** [comment]
thank you

**Comment by fzumstein** [comment]
yes, it's an Excel thing, unconnected to the OS.

**Comment by miriam-z** [comment]
Some data can easily convert:

float(data[0])

But others have real and imag? 
![Screenshot 2021-07-02 at 14 28 46](https://user-images.githubusercontent.com/19760229/124281637-d18d7d00-db41-11eb-8e84-5571f21ffc05.png)

Not sure how this is possible

**Comment by fzumstein** [comment]
Well, Excel doesn't support complex numbers either, so you'd have to deal with them also before sending them over, see also: https://github.com/xlwings/xlwings/issues/945 Your screenshot only shows imaginary units of 0 though.
