### ISSUE TITLE
Save() method isn't working. 

### ISSUE THREAD

**Issue by mobaset** [xlwings/xlwings#1649]
#### Describe your issue (incl. Traceback!)
I have the below code that split individual sheets into separate Excel files. If the sheet is empty it simply delete the sheet.

It was working perfectly fine few weeks back, but not sure why this code doesn't work anymore. The save method doesn't save the file at all. I have tried to troubleshoot by simply creating a file and saving on a different directory (minimal sample code further down below), but still doesn't work. What I'm missing?

The code doesn't produce any error message, the code is executing, but no files are saved.

```python
import os
import time
import xlwings as xw
from xlwings import App, Book
import pandas as pd
from pathlib import Path



# a function to create new folder if it doesn't exists
def create_dir(folder):
    if not os.path.exists(folder):
        os.makedirs(folder)
        return True
    else:
        return False


# split the individual sheets in the bid file into separate files
def split_sheets_into_files(book: Book, prop_book: Book, output_path: Path, xls_app: App) -> None:
    print('='*10, 'Splitting Process started', '='*10, "\n")

    # get sheet names from prop file
    live_client_names = prop_book.sheets['Table Properties']["A1"].expand('down').value
    print('*'*10, f'Number of live clients {len(live_client_names)-1}', '*'*10, "\n")
    
    # create output folder if not exists
    has_created = create_dir(output_path)
    if has_created:
        print('*'*10, f'OUTPUT FOLDER CREATED!', '*'*10, "\n")
    else:
        print('*'*10, f'OUTPUT FOLDER ALREADY EXISTS!', '*'*10, "\n")
    
    for sheet in book.sheets:
        if sheet['A3'].value == None:
            print('-'*10, f'{sheet.name} DELETED', '-'*10)
            sheet.delete()
        elif sheet.name in live_client_names:
            new_book = xls_app.books.add()
            sheet.api.Copy(Before=new_book.sheets['Sheet1'].api)
            new_book.save((output_path / f'{sheet.name}.xlsx'))
            time.sleep(1)
            new_book.close()
            # print('-'*10, (output_path / f'{sheet.name}.xlsx'), '-'*10)
            print('-'*10, f'{sheet.name} CREATED', '-'*10)
    book.save()
    book.close()
    print('='*10, 'Splitting Process ended', '='*10)


# #### Run main script ####
def run_split_process(bid_file, props_file, output_folder):
    # Instanciating invisible Excel instance 
    invisible_xl = App(visible=False)

    # Open necessary files
    bid_book = invisible_xl.books.open(bid_file)
    props_book = invisible_xl.books.open(props_file)

    # Run the splitting process
    split_sheets_into_files(
        book=bid_book, 
        prop_book=props_book, 
        output_path=output_folder,
        xls_app=invisible_xl)
    
    time.sleep(5)
    invisible_xl.quit()
    # Closing the invisible Excel instance to remove zombie processes
    # invisible_xl.kill()

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
from pathlib import Path
import time
import xlwings as xw


FILE_PATH = r'C:\test\TEST02.xlsx'
print(FILE_PATH)


new_book = xw.Book()

new_book.sheets['Sheet1']['A2'].value = 'test'
time.sleep(2)
new_book.save(FILE_PATH)
print(new_book.fullname)

time.sleep(4)
new_book.close()
```

**Comment by fzumstein** [comment]
If it used to worked, you're probably not missing anything. Try to run it in a fresh virtual/conda env, try to run it on a different computer. Things that people forget to mention and can sometimes play funny is if you've it to OneDrive/SharePoint recently?

**Comment by mobaset** [comment]
Sorry for my late reply. Yeah I forgot to mention that I ran the above script on my work computer, the script file and the files saved are on OneDrive. So here are few things that I did to isolate the problem with the results:

- I tried to run the minimal code on a none OneDrive folder - that didn't work.
- I tried to run the minimal code with fresh python installation (had Anaconda 3.8, then installed pure python 3.9) - that didn't work either.
- I tried to run the minimal code on my personal laptop on a none OneDrive folder - that did work ironically.

So it seems OneDrive is causing the issue, is there a workaround that I can try?

Thanks!

**Comment by fzumstein** [comment]
so `FILE_PATH` is the path to the local OneDrive folder?

**Comment by mobaset** [comment]
In reality yes, it should point to a folder on my local OneDrive. But for the sample code, I chose a location outside local OneDrive folder for testing, which it didn't work.

**Comment by fzumstein** [comment]
If you see the same issue when saving outside of OneDrive, then I have no idea what the issue could be, I am afraid...

**Comment by mobaset** [comment]
Ok, let's say it does work outside of OneDrive, how to make it work inside OneDrive? 
I'm desperate to try anything out, otherwise I will end up doing very laborious work or re-write the script with different package like OpenPyXL, which I don't want. I have other plans for XLwings.

**Comment by fzumstein** [comment]
Well, it shouldn't make any difference, really. I just tried to run it on my end and it works also with a OneDrive location. The only time OneDrive can cause issues is when you rely on `mybook.fullname` which is a URL in the case you store it on OneDrive. The only other workaround you can test out is to disable `Use Office applications to sync Office that I open` on the `Office` tab under the OneDrive settings. This will, however, disable the syncing/autosave of Excel. Other than that, there must be something local to your environment that it is not liking. Might be worth trying out if the corresponding code in VBA works.

**Comment by mobaset** [comment]
Ok, thanks @fzumstein for your help. Closing this issue now!

**Comment by mobaset** [comment]
Hi @fzumstein,

Just a thought, can I explicitly disable save dialog from `xlwings`?

The reason why I'm asking is, I tried to open blank workbook and save it to `C:` drive using `pywin32` to troubleshoot the issue, and I noticed `pywin32 `also fails to save. I suspect that the Save dialog is the issue. When I kept the XLS instance visible, I can see the save dialog popped up even after the below code is executed successfully. Just wondering if explicitly disabling the save dialog might solve my problem.

Thanks!

```
import win32com.client as win32
FILE_PATH = r'C:\test\TEST02.xlsx'

xls = win32.gencache.EnsureDispatch('Excel.Application')
xls.Visible = True
wb = xls.Workbooks.Add()
sheet = wb.Worksheets(1)
sheet.Range("A1").Value = 'test'
wb.SaveAs(FILE_PATH)
time.sleep(5)
wb.Close()
xls.Quit()

**Comment by fzumstein** [comment]
You can try setting `app.display_alerts = False`, see: https://docs.xlwings.org/en/stable/api.html#xlwings.App.display_alerts and https://docs.xlwings.org/en/stable/api.html#xlwings.App.properties

**Comment by mobaset** [comment]
Thanks @fzumstein. I afraid still didn't work. Will keep trouble shooting, hopefully something might work.

**Comment by fzumstein** [comment]
You can try to move up to save command, first thing after you have the book object. then again where you have it now.
