### ISSUE TITLE
[Question] FastAPI compatible?

### ISSUE THREAD

**Issue by scheung38** [xlwings/xlwings#1651]
Doc mentioned setting up with Flask, but is it also compatible with FastAPI as well? if so could you provide example if returning wb.fullname.

Also it was mentioned:

xlwings restapi run
Then perform a GET request e.g. via PowerShell on Windows or Terminal on Mac (while having an unsaved “Book1” open)

if Book1 is not opened then rest will not return wb object?

**Comment by fzumstein** [comment]
This seems to be the same questions as https://github.com/xlwings/xlwings/issues/1652 and https://github.com/xlwings/xlwings/issues/1646 so closing this as duplicate.
