### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by DariuszKobiela** [xlwings/xlwings#1659]
#### Missing Excel functions in xlwings api: 
LEFT()
XLOOKUP()
LEN()

I didn't find them here: https://docs.microsoft.com/en-us/office/vba/api/excel.worksheetfunction
So I suppose they are missing.

Code sample (working one):

```python
import xlwings as xw

def main():
    wb = xw.Book.caller()
    sheet = wb.sheets[0]
    sheet["A10"].value = wb.app.api.WorksheetFunction.Min(sheet['A1:A9'].api)
```

But when I try to use eg. Left function:

`sheet["B10"].value = wb.app.api.WorksheetFunction.Left(sheet['A10'].api, 1)`

It is not working, because there is not such function as 'Left'.

**Comment by fzumstein** [comment]
Please paste a full code sample to reproduce.

**Comment by fzumstein** [comment]
These functions don't exist as `WorksheetFucntion`, see https://docs.microsoft.com/en-us/office/vba/api/excel.worksheetfunction for full list.
