### ISSUE TITLE
Issue with writing lists to Excel

### ISSUE THREAD

**Issue by g-dixit** [xlwings/xlwings#1661]
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

I have a data frame 'df' in Python with the following structure and similar data :
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/GAURID~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/GAURID~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

rowdata1 | 2.33
-- | --
rowdata2 | 4.55
rowdata3 | [1,2,3]
rowdata4 | []

</body>

</html>
I'm using the following code to write to excel

```python

outputs_sheet.range('A1').options(pd.DataFrame).value = df
```

This works for the single value entries in the dataframe but doesn't write the list elements to the excel sheet. Any thoughts on why this is occurring and ways to fix this?

**Comment by fzumstein** [comment]
xlwings can only deal with basic objects in pandas DataFrames like datetime, strings and numbers.
If your column contains a list, you could transform them beforehand. For example, you could turn them into lists or explode them into different columns or rows, depending on what you'd like to see in Excel.

**Comment by fzumstein** [comment]
closing this in favor of #1794
