### ISSUE TITLE
Help for a working configuration to allow different (constant) folder for modules

### ISSUE THREAD

**Issue by rpelibertysurf** [xlwings/xlwings#1684]
#### Describe your issue (incl. Traceback!)
xlwings is great and I'd like to use it to improve an existing Excel VBA with many tools with some python, mainly for internet /database requests (the asynchronous part).

My needs are :
- to allow user to move around his workbook without bothering with the associated modules.py
- for a seamless experience, I prefer not to show the ribbon or use the addin (=> standalone)
 
I thought is was possible to store the modules.py in a different folder (from the workbook) , if the 'user/.../.xlwings/xlwings.conf had all the necessary parameters.

However, I can't seem to be able to have those parameters right, and also I couldn't find an example

Could you please tell me what's wrong in my config ?

Here's my xlwings.conf
```
"INTERPRETER_WIN","c:\users\xxxx\appdata\local\programs\python\python39\python.exe"
"PYTHONPATH","C:\Users\xxxx\Documents\Python"
"UDF Modules","udf"
````
Below are the codes but they are standard codes that come with quistart so I don't think the issue is there

My test module is stored in 
C:\Users\xxxx\Documents\Python\udf.py

```python : udf.py
import xlwings as xw

def main():
    wb = xw.Book.caller()
    sheet = wb.sheets[0]
    if sheet["A1"].value == "Hello xlwings!":
        sheet["A1"].value = "Bye xlwings!"
    else:
        sheet["A1"].value = "Hello xlwings!"


if __name__ == "__main__":
    xw.Book("test_otherFolder.xlsm").set_mock_caller()
    main()
# Your traceback here
---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "<string>", line 1, in <module>

ModuleNotFoundError: No module named 'test_otherFolder'



Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```VBA in 'test_otherFolder.xlsm' in a another folder
# Your code here
import xlwings as xw

def main():
    wb = xw.Book.caller()
    sheet = wb.sheets[0]
    if sheet["A1"].value == "Hello xlwings!":
        sheet["A1"].value = "Bye xlwings!"
    else:
        sheet["A1"].value = "Hello xlwings!"
if __name__ == "__main__":
    xw.Book("test_otherFolder.xlsm").set_mock_caller()
    main()
```

**Comment by fzumstein** [comment]
This looks pretty ok to me... you can further improve it by using environment variables so it works across different users. For example:

```
"INTERPRETER_WIN","%LOCALAPPDATA%\programs\python\python39\python.exe"
```

Make sure you don't have an `xlwings.conf` sheet that overrides your config file.

**Comment by rpelibertysurf** [comment]
@fzumstein  ,Thanks for the feedback. 

I thought I put my VBA code in the question but I realize that I put the python code twice instead ...
Since you confirmed the shared part was OK, it had to be VBA
Here's the corrected VBA that works

```
Sub SampleCall()
    mymodule = Left(ThisWorkbook.name, (InStrRev(ThisWorkbook.name, ".", -1, vbTextCompare) - 1))
    'not functionning code
    'RunPython "import " & mymodule & ";" & mymodule & ".main()" 

    'functionning code
    RunPython "import " & "udf" & ";" & "udf" & ".main()"
End Sub
````
I just forgot to change 'mymodule' which refers to the current workbook with the constant "udf".
It's also your comment on environment variable which put me in right direction (constant vs variable)

Now it works Thanks !

Last question on this subject
I havent yet fully understood the use of :
````
xw.Book("test_otherFolder.xlsm").set_mock_caller()
````
But, if it's vital to keep it, I suppose that I should pass the workbook.name as variable
How would you advise to do it ? For each and every function or only with main() ?

Thanks

**Comment by fzumstein** [comment]
I should probably add a few comments in the autogenerated code. You can make it even easier:

```
RunPython "import udf;udf.main()"
```

mock_caller is only for running things from Python (mostly during development/debugging) and can otherwise be deleted, see: https://docs.xlwings.org/en/stable/debugging.html

**Comment by rpelibertysurf** [comment]
Thanks a lot !
