### ISSUE TITLE
Help! Is it a bug?

### ISSUE THREAD

**Issue by 1011726441** [xlwings/xlwings#1691]
![image](https://user-images.githubusercontent.com/38745888/127731069-97cdc464-9c8f-4c01-8fb9-f66e51bf682a.png)
Help! I don't know what happen ? i can use it to batch processing of other files , but I can't save this file

**Comment by fzumstein** [comment]
Can't really tell... is there a way for you to strip make the file as simple as possible to find out what it doesn't like?

**Comment by SnowingFox** [comment]
I think you shoud 百度一下

**Comment by 1011726441** [comment]
> I think you shoud 百度一下

I can't find anything about this problems

**Comment by 1011726441** [comment]
> Can't really tell... is there a way for you to strip make the file as simple as possible to find out what it doesn't like?

The last message "330371008130001" which before the error was printed at line 304 ,but I could not save the file whose name was combined strings by the message

**Comment by 1011726441** [comment]
> Can't really tell... is there a way for you to strip make the file as simple as possible to find out what it doesn't like?

The last message "330371008130001" which before the error was printed at line 304 ,but I could not save the file whose name was combined strings by the message at line 310

**Comment by fzumstein** [comment]
I am closing this as I can't replicate. feel free to reopen if you can maybe add a sample file to repicate.
