### ISSUE TITLE
Mimic Vlookup *exactly*

### ISSUE THREAD

**Issue by Rkauff** [xlwings/xlwings#1694]
#### OS (e.g. Windows 10 or macOS Sierra)

Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

xlwings version: 0.20.8
Python 3.8.5

#### Describe your issue (incl. Traceback!)
No traceback, not an error.

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
#Create your DataFrames
wb_data = pd.ExcelFile('Timeliness File.xlsx')
data_frame_excel = pd.read_excel(wb_data, sheet_name="Timeliness Raw Data")
sec_dist_df = pd.read_excel('wb1.xlsx', sheet_name="Sheet1")

"""
data_frame_excel.describe #returns [18916 rows x 24 columns]
sec_dist_df.describe #returns [26656 rows x 13 columns]
"""

vlookup_mimic = pd.merge(data_frame_excel, sec_dist_df[['Unique Lookup Value to the Python File', 'Inbound Price Receipt Time']], left_on='Comments', right_on='Unique Lookup Value to the Python File', how='left')

vlookup_mimic.describe #returns [33604 rows x 26 columns]

```

vlookup in excel would yield 18916 rows. I understood left merge to be most like vlookup, yet it outputs nearly twice as many rows.

**Comment by fzumstein** [comment]
Can you upload the Excel file (preferably with a stripped down toy dataset that replicates your case)?

**Comment by Rkauff** [comment]
[wb1.xlsx](https://github.com/xlwings/xlwings/files/6934600/wb1.xlsx)
[Timeliness File.xlsx](https://github.com/xlwings/xlwings/files/6934604/Timeliness.File.xlsx)

**Comment by fzumstein** [comment]
You're looking at this issue: https://stackoverflow.com/questions/22720739/pandas-left-outer-join-results-in-table-larger-than-left-table

Slightly simplified code that works:

```python
import pandas as pd

df1 = pd.read_excel('Timeliness File.xlsx', sheet_name="Timeliness Raw Data")
df2 = pd.read_excel('wb1.xlsx', sheet_name="Sheet1")

df1.merge(df2.drop_duplicates(['Unique Lookup Value to the Python File']),
          left_on='Comments',
          right_on='Unique Lookup Value to the Python File',
          how='left')
```
