### ISSUE TITLE
function works outside of UDFs and doesn't work inside UDFs

### ISSUE THREAD

**Issue by EthanTheMathmo** [xlwings/xlwings#1700]
####Windows 10

#### Describe your issue (incl. Traceback!)

I have the following very simple bit of code

```
def open_macros():
    wb = xw.apps.active.books.open(r"C:\Users\ethan\Documents\excel stuff\testMacros.xlsm") 
```

The purpose of this code is to bring up a worksheet (which isn't visible) containing macros with shortcuts for a user to use.

This works fine by itself. But when I turn it into a UDF it doesn't work. It is needed as a UTF, as it is to be stored inside an add-in, and then called to activate the macros. (If I don't do this, I'd have to add some VBA code into their PERSONAL sheet in XLSTART so that they could use a macro to activate and deactivate the sheet with macros built using xlwings&python, but I'd rather not access this as installation would be messier).

From what I've read online there are often pitfalls with opening workbooks inside a UDF as it can reload the workbook, so perhaps the problem is completely in my approach.

**Comment by fzumstein** [comment]
Yes, that's a limitation of UDFs, see: https://support.microsoft.com/en-us/topic/description-of-limitations-of-custom-functions-in-excel-f2f0ce5d-8ea5-6ce7-fddc-79d36192b7a1
