### ISSUE TITLE
add to_pdf() support for Chart and Range

### ISSUE THREAD

**Issue by fzumstein** [xlwings/xlwings#1708]

**Comment by FabianGoessling** [comment]
Just stumbled across this issue and started coding a first iteration:

https://github.com/FabianGoessling/xlwings

If this is going in the right direction, i'd love to contribute, but so far this is blindly coded on a Mac without Excel installation.

**Comment by fzumstein** [comment]
This would only make sense if it can be exported directly from Excel, without png in the middle (from what I can see, you're doing this). Something like this (it would export the whole sheet though which it shouln't, so not sure it'll work out:

```python
import xlwings as xw
from xlwings.constants import FixedFormatType, FixedFormatQuality

book = xw.books.active
book.sheets.active.charts[0].api[1].ExportAsFixedFormat(Type=FixedFormatType.xlTypePDF,
                                                        Filename=r'C:\Users\felix\Desktop\test.pdf',
                                                        Quality=FixedFormatQuality.xlQualityStandard,
                                                        IncludeDocProperties=True,
                                                        IgnorePrintAreas=False,
                                                        OpenAfterPublish=False)
```

**Comment by FabianGoessling** [comment]
I agree, i totally missed the ExportAsFixedFormat method in the VBA Reference. 

If you add 

book.sheets.active.charts[0].api[0].Select()

before the export, your code does the job. 
For ranges it is the same, except the non-tuple api..

**Comment by fzumstein** [comment]
gotcha, thanks for letting me know!

**Comment by FabianGoessling** [comment]
If you didn't implement it already, I'll do it or at least make a first draft, so give me a sign.

**Comment by fzumstein** [comment]
Feel free to go for it!
