### ISSUE TITLE
I want to write a list content in a column, but it write in a row

### ISSUE THREAD

**Issue by niuzijia** [xlwings/xlwings#1712]
#### I want to write a list content in a column, but it write in a row 

```python
fill_sht.range('b6:b8').value = ['i', 'love', 'you']

```
#### I think the list content should write in excel range 'b6:b8',but actually, it write in  range 'b6:d6', is there anything wrong?
![image](https://user-images.githubusercontent.com/68538774/132166340-0ba18696-58ae-4398-a835-76c2a60162ea.png)

**Comment by fzumstein** [comment]
```python
fill_sht.range('b6:b8').options(transpose=True).value = ['i', 'love', 'you']
```

**Comment by niuzijia** [comment]
> ```python
> fill_sht.range('b6:b8').options(transpose=True).value = ['i', 'love', 'you']
> ```
The problem is fixed!
Thank you very much!
