### ISSUE TITLE
RunPython in VBA macro in excel 365 shared spreadsheet Mac

### ISSUE THREAD

**Issue by robzer** [xlwings/xlwings#1721]
#### xlwings 0.24.9 , Excel Office 365 (business pack), Python 3.8.3

I managed to run a macro that calls a python script stored locally, but I would like to know if it is also possible to do that if the spreadsheet is shared in the 365 cloud (OneDrive)

I am getting errors in the VBA script. If this is doable, what should my python path be? where shall i store the python script (on the OneDrive).

many many thanks

**Comment by fzumstein** [comment]
You'll need to set the ONEDRIVE_MAC setting, see: https://docs.xlwings.org/en/latest/troubleshooting.html#issue-couldn-t-find-the-local-location-of-your-onedrive-or-sharepoint

**Comment by robzer** [comment]
thanks for your reply. Yes I have tried amending it in the xlwings.conf file, but what should it point to? the OnDrive folder in which both the .xlsm and the .py files are located?

**Comment by robzer** [comment]
ok so I am stuck. Same specs as above.

files:
book_0.xlsm 
hello.py  (same as in your example)

both saved under "ONEDRIVE_MAC", "/Users/blabla/OneDrive - blablablabla"

xlwings.conf per below

"INTERPRETER_MAC","/Users/blabla/anaconda3/envs/mvpq/bin/python"
"ONEDRIVE_MAC", "/Users/blabla/OneDrive - blablablabla"

VBA script:
Sub book_0()
    RunPython "import hello; hello.world()"
End Sub


error:
Compile error:

Sub or Function not defined

I do not understand what is going on here. Looks like the issue is with the RunPython function. I did pip install the addin though. Any thoughts? thanks again

**Comment by fzumstein** [comment]
Hm and so just by moving out the project of OneDrive to a local drive everything works?

**Comment by robzer** [comment]
yes. But I just tried to open xlwings myproject on the OneDrive folder location from the terminal, it did then allow me to RunPython scpits fine from VBA. 
I also modified the xlwings.conf to 

`
"INTERPRETER_MAC","/Users/blabla/anaconda3/envs/mvpq/bin/python"

"PYTHONPATH","/Users/blabla/OneDrive - blablablabla"

"ONEDRIVE_MAC","/Users/blabla/OneDrive - blablablabla"
`

must be an issue with the way I create teh excel files?

**Comment by fzumstein** [comment]
Can't say for sure, but I am currently on this issue: https://github.com/xlwings/xlwings/issues/1630 and will definitely go through this again. But that'll have to wait another 2 weeks.

**Comment by robzer** [comment]
from a VBA module in myproject.xlsm I can even RunPython a python script that writes in book_0.xlsm but cant run the exact same VBA module in book_0.xlsm !

ok thanks for your help anyway. Am I creating the VBA module wrong? v weird

**Comment by fzumstein** [comment]
should be resolved sinc 0.25.0: https://docs.xlwings.org/en/stable/onedrive_sharepoint.html
