### ISSUE TITLE
while accessing worksheet.range com_error: (-2147352573, 'Member not found.', None, None)

### ISSUE THREAD

**Issue by ssprakash-seeni** [xlwings/xlwings#1724]
#### Describe your issue (incl. Traceback!)
The code worked fine the yesterday, but today it is not working.

```python
# Your traceback here
Traceback (most recent call last):

  File "C:\Users\ssp\SpyderPythonProjects\SSTrades\SSTradesAlgoZero\library\NSEtickerinExcel.py", line 108, in <module>
    print(dak.range("B2").value)

  File "C:\Users\ssp\AppData\Local\Programs\Python\Python38\Lib\site-packages\xlwings\main.py", line 1106, in range
    return Range(impl=self.impl.range(cell1, cell2))

  File "C:\Users\ssp\AppData\Local\Programs\Python\Python38\Lib\site-packages\xlwings\_xlwindows.py", line 689, in range
    xl1 = self.xl.Range(arg1)

  File "C:\Users\ssp\AppData\Local\Programs\Python\Python38\Lib\site-packages\xlwings\_xlwindows.py", line 70, in __call__
    v = self.__method(*args, **kwargs)

  File "<COMObject <unknown>>", line 2, in Range

com_error: (-2147352573, 'Member not found.', None, None)
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
pathhcurr = os.getcwd()
savepath = pathhcurr.replace("library","reference files")
xlfilepath = str(savepath) + str("\\NSE_analysis_list.xlsx")
wb = xw.Book(str(xlfilepath))
dak = wb.sheets("DataKeys")
dak.active = True
print(dak.name)
dak.range("a:b").value = None
```

**Comment by fzumstein** [comment]
`Member not found` usually means you're misspelling something or a sheet was deleted etc.

**Comment by ssprakash-seeni** [comment]
The same code working today, i have not done any change to the code, on that day when i got the error i was trying out may ways to clear the problem, but today the same code works. Any other things to be noted?

**Comment by Ca11MeE** [comment]
I have this error too, and found it happen in platform Win, when I install WPS and microsoft office and call save() func

when i cancel WPS file associations(.xls/.xlsx), also use microsoft office, it works

but i use it to build my RPA SDK, can not do it manual, how can i do it auto to switch diff excel app?

**Comment by Ca11MeE** [comment]
i know what happened

wps miss SaveAs func

**Comment by fzumstein** [comment]
closing this as non reproducible.
