### ISSUE TITLE
RunPython command

### ISSUE THREAD

**Issue by leyojoseph** [xlwings/xlwings#1726]
This is regarding the RunPython command from  excel vba.  As per my understanding, this command will  execute the .py file in the  pythonpath as shown below.
![image](https://user-images.githubusercontent.com/67446653/135880083-a9d2e403-9bdc-4b20-98b9-f6e40c9905fd.png)

Is it possible to  use this as part of RunPython?. I want to execute  .py files from different folders using RunPython command in VBA> I mean something like this "RunPython "C:\Python|tools\example.py, example.function"

**Comment by fzumstein** [comment]
It's not currently possible, no. But you can add multiple paths to the PYTHONPATH setting separated by semi-colon (`first;second`) and you can configure each workbook individually via the `xlwings.conf` sheet.
