### ISSUE TITLE
executing python code

### ISSUE THREAD

**Issue by leyojoseph** [xlwings/xlwings#1727]
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import xlwings as xw
# def world():
#     wb = xw.Book.caller()
#     wb.sheets[0].range('A11').value = 'Hello World!'
x=2
y=45*x
wb = xw.Book.caller()
wb.sheets[0].range('A13').value = y
```
This is a very basic question...sorry if it doesn't make sense. Following your example, I can  run the python function World() using  RunPython "import hello; hello.world()". I have a python  script which when  executes runs some actions (like turning on an instrument in the lab etc..). How to run this script directly from excel vba with xlwings. For example my above code doesn't have the function world(). Can I run this python script from excel vba using xlwings to get a value of 90 in range(A13).

**Comment by fzumstein** [comment]
By importing a module, it will be run, so in your case, you can simply do `RunPython "import hello"`
