### ISSUE TITLE
Option to Save as XLSB

### ISSUE THREAD

**Issue by sathish804** [xlwings/xlwings#1728]
#### OS (e.g. Windows 10 or macOS Sierra)

Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings : latest version
Python: 3.9
Office 365

#### Describe your issue (incl. Traceback!)

```Dear Developer, Please provide the option to edit an XLSB file with xlwings.
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
You only need to change the extension accordingly: `mybook.save('myfile.xlsb')`

**Comment by sathish804** [comment]
> You only need to change the extension accordingly: `mybook.save('myfile.xlsb')`

Hi, I want to edit an existing XLSB file and save it. Is there a way to do it?
