### ISSUE TITLE
How to Use Icon Sets with Xlwings 

### ISSUE THREAD

**Issue by tp-duarte** [xlwings/xlwings#1731]
OS : Windows 10 

 xlwings : 0.24.9
 Excel :  Version 2109 Build 16.0.14430.20224 64-bit  
 Python :  3.9.6

I am trying to use Icon Sets in my worksheet column with Xlwings, and I already know that xlwings by itself doesn't have a function that suports this kind of application. However, with the Microsoft api, this is possible.

[](https://docs.microsoft.com/en-us/office/vba/api/excel.xliconset)

The link above shows us the Icons that Excel displays and also the values to these Icons. But it's not clear for me how I can apply it in my columns with Xlwings. How can I solve this ?

**Comment by fzumstein** [comment]
Do you want to do something along these lines? https://www.bluepecantraining.com/portfolio/excel-vba-apply-icon-set-conditional-formatting-with-vba-macro/

**Comment by tp-duarte** [comment]
Exactly ! If you allow me to be a little more specific, I want to show only the green arrow that points up, from  the xl3Arrows, if I have a positive value in my table, if there is no valu, I would like to show nothing.
