### ISSUE TITLE
Xlwings error 53 when running through Excel Ribbon

### ISSUE THREAD

**Issue by HristoDimitrov** [xlwings/xlwings#1732]
#### OS (e.g. Windows 10 or macOS Sierra)
OS: Windows 10 

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings - 0.23.0
Excel - 2109 (Build 14430.20270)
Python - 3.9.4
Miniconda3 - conda 4.10.3

#### Describe your issue (incl. Traceback!)
I've been having issues running a Python script from within Excel. (I was able to run Python scripts that were able to access the Excel spreadsheet).

Originally I had a default Python installation where I installed xlwings. Later on, I found about the Anaconda/Miniconda and swap to using them instead (deleting my standalone python installation).

Following the commands described in the following guides:
https://www.xlwings.org/book
```shell
(base)> conda create --name xl39 python=3.9 -y
(base)> conda activate xl39
(xl39)> conda install anaconda -y
```
Followed by steps inside:
https://docs.xlwings.org/en/stable/installation.html#installation
```shell
conda install -c conda-forge xlwings
xlwings addin install
```

Subsequently I would create a Quickstart example through my Miniconda terminal following the instructions in:
https://docs.xlwings.org/en/stable/quickstart.html

```shell
xlwings quickstart myproject
```

Opening and filling the xlwings Ribbon fields as such:
Conda path - C:\Users\\_user_\Miniconda3
Conda env - xl39
(I tried with both PYTHONPATH empty and filled)
PYTHONPATH - C:\Users\\_user_\Miniconda3\envs\xl39\python.exe

![xlwings_excel_ribbon](https://user-images.githubusercontent.com/2874611/136751966-3c9a8de6-0bcc-4a8c-835c-3f5ed457fa83.png)

Running the "Run Main" button results in the following error:
![xlwings_excel_error_53](https://user-images.githubusercontent.com/2874611/136752633-3348cf12-8cb8-4204-b2a0-25fc318fca50.png)

Following the error through debug:
![xlwings_excel_error_53_debug](https://user-images.githubusercontent.com/2874611/136752753-bbd33b63-4f69-4919-8435-cde08cb0c0a7.png)

(The line just above the highlighted line was added by me for grab the name of the **FileName** trying to be opened)
The **FileName** that is being tried to be open is:
**C:\Users\\_user_\AppData\Local\Temp\xlwings-0884DCB2-D176-C42B-9E6F-2A2145FE60DB.log**

Additional information:

```shell
C:\Users\_user_>where python
C:\Users\_user_\AppData\Local\Microsoft\WindowsApps\python.exe
```
I've deleted my standalone python from my machine some time ago and checking this file, it is shown as empty. Checking my **PYTHON_WIN** environmental variable in my command prompt it is not set:
![xlwings_python_win](https://user-images.githubusercontent.com/2874611/136754484-a39e11ab-e4cc-40bb-b1db-27f5da4def76.png)

Miniconda3 does not appear in my command prompt as part of my **%PATH%** variable

The contents of my <user>\.xlwings\xlwings.conf are:
```shell
"CONDA ENV","xl39"
"UDF MODULES",""
"CONDA PATH","C:\Users\<user>\Miniconda3"
"PYTHONPATH","C:\Users\<user>\Miniconda3\envs\xl39\python.exe"
```

This is the Quickstart python script included below
```python
# 
import xlwings as xw


def main():
    wb = xw.Book.caller()
    sheet = wb.sheets[0]
    if sheet["A1"].value == "Hello xlwings!":
        sheet["A1"].value = "Bye xlwings!"
    else:
        sheet["A1"].value = "Hello xlwings!"


@xw.func
def hello(name):
    return f"Hello {name}!"


if __name__ == "__main__":
    xw.Book("crg_gen_5.xlsm").set_mock_caller()
    main()

```

I've been struggling to find a solution to this issue already documented somewhere. Could you please help me fix this?
Many thanks

**Comment by fzumstein** [comment]
you will need to create an exception in your antivirus so it won't block the call to conda.exe from Excel VBA.

**Comment by fzumstein** [comment]
Unfortunately, I have no idea about this, but I would encourage you to contact the provider of your antivirus with this question. All I can say is that the shell command that xlwings uses includes the name of the workbook and other arguments that are different for different workbooks. I am closing this issue as I think this is not an issue with xlwings but with the antivirus.
