### ISSUE TITLE
Invalid index COM error thrown when opening workbook

### ISSUE THREAD

**Issue by Lord-Mustang** [xlwings/xlwings#1741]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.24.7
Python 3.8.5
Excel  16.0.13801.21002 x64 (Office 365)
#### Describe your issue (incl. Traceback!)
During opening of any workbook, an invalid index error is thrown.

```python
# Your traceback here
Exception has occurred: com_error       (note: full exception trace is shown but execution is paused at: __call__)
(-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147352565), None)
  File "C:\Users\user\AppData\Local\Temp\gen_py\3.8\00020813-0000-0000-C000-000000000046x0x1x9.py", line 41312, in __call__ (Current frame)
    ret = self._oleobj_.InvokeTypes(0, LCID, 2, (13, 0), ((12, 1),),Index
  File "D:\program\main.py", line 111, in set_variant
    wb = app.books.open(r'direct\path\to\workbook.xlsx')
  File "D:\program\main.py", line 160, in main
    set_variant(1, excel_app)
  File "D:\program\main.py", line 281, in <module>
    main()
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
Tried both:
```python
# Your code here
app = xw.App()
wb = app.books.open(r'direct\path\to\workbook.xlsx')

```
and:
```python
xw.Book(r'direct\path\to\workbook.xlsx')
```
Both throw the same exception. I have tried deleting the gen_py contents and rebooted, but that did not help.

**Comment by fzumstein** [comment]
I dind't mean to move the conda env, just the Excel file. Anyhow, not sure, but may worth to delete `C:\Users\user\AppData\Local\Temp\gen_py\3.8` and try again...

**Comment by Lord-Mustang** [comment]
> I dind't mean to move the conda env, just the Excel file. Anyhow, not sure, but may worth to delete `C:\Users\user\AppData\Local\Temp\gen_py\3.8` and try again...
I tried both, to no avail unfortunately. I also tried to create a completely new Python project, in which I load an empty workbook with Jupyter, but that also results in the same error.

Strangely enough everything after the exception seems to work fine. Xlwings makes some edits to a sheet and saves it, and that seems to work just fine.

**Comment by valbinet** [comment]
Hello everyone,

I've been trying everything here without success (having the same issue).

I'm using:
xlwings 0.24.6
python 3.7.10
Excel Microsoft 365 MSO (16.0.14326.20706) 64-bit 

What's strange to me, is that it always worked, and stoped working it this computer. I'm using a virtual environment, then this is exactly the same librairies. 

Could it be something from Windows?

**Comment by waldo707** [comment]
@valbinet I was not able to solve this issue. But it was the same thing for me, a script worked for me on a different computer but it didnt work on the computer I needed it to. The script worked for me in a virtual environment but not locally even though both computers had the same xlwings package, python and Excel versions.

I ended up using openpyxl and creating dummy variables within my Excel sheets to be referenced within Excel to do the calculations I needed my script to do.

**Comment by valbinet** [comment]
Thank you @waldo707 for your feedback.

From my side, I chose to rewrite the functions using pywin32 (openpyxl doesn't work with some of my webscrapped files). 
It's going quite well so far, I'm finding this transition relatively easy and efficient.

**Comment by fzumstein** [comment]
I am closing this as you seem to have found workarounds and it's hard to replicate for me. @valbinet If you have a script in xlwings that shows this behavior and one in pywin32 that does not, I'd be happy to have a look at them!

Something to consider when it works on one machine and not on the other are also always antivirus programs...

**Comment by fzumstein** [comment]
@valbinet, do you usually have Excel already running when you run these commands?

**Comment by valbinet** [comment]
Yes: when it was working (on other PCs) it was the case.

And now, with pywin32, it keeps working perfectly (and cherry on the cake: it seems to be faster!).

**Comment by fzumstein** [comment]
The only difference I can see with your approach is that xlwings sends all args when opening a book:
https://github.com/xlwings/xlwings/blob/main/xlwings/_xlwindows.py#L735-L751

and the dispatch call is different (goes through a retry wrapper and creates a new instance of Excel if desired):
https://github.com/xlwings/xlwings/blob/main/xlwings/_xlwindows.py#L516

playing around with these elements could possibly identify the offending part.

**Comment by james5843** [comment]
I just had the same issue. I managed to fix it by doing a reinstall of xlwings. Not sure exactly why that helped but it did.
