### ISSUE TITLE
Loading functions from a .xla file

### ISSUE THREAD

**Issue by khrouatbi** [xlwings/xlwings#1742]
I'm trying to load .xla but no luck.

I saw another similar issue but the solution proposed did not work.

I tried:

import xlwings as xw
wb1 = xw.Book(location_file_xlsm)
wb2 = xw.Book(location_file_xla)

and 

wb1.app.api.RegisterXLL(location_file_xla)

none of them worked.

Can anybody help? I also tried with other libraries such aswin32com and openpyxl but nothing worked.

**Comment by fzumstein** [comment]
Can't replicate. Please fill in the provided template with versions, OS etc. and paste the error message that you see. (Don't use RegisterXLL, this is for xll, not xla).

**Comment by fzumstein** [comment]
I am closing this as I couldn't replicate it, feel free to reopen if you still need help.
