### ISSUE TITLE
Xlwings If Statment 

### ISSUE THREAD

**Issue by AhmedHelalM** [xlwings/xlwings#1755]
#### OS (e.g. Windows 10 or macOS Sierra)
os
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.23 & 3.9 & office 365
#### Describe your issue (incl. Traceback!)
Hi i created function "if statment " and i am using xlwings to assign macro and get result but after code run , result become on raw not column , i need the result to be stored on the created column 

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
def if_statmment():
    wb = xw.Book.caller()
    sheet = xw.sheets[2]
    df = sheet.range("A1").expand().options(pd.DataFrame).value
    z = df['Succes'] = np.where(df['stock']>10,'succeeded','not succeded')
    sheet["E2:E19"].value = z
<img width="1440" alt="Screen Shot 2021-10-29 at 10 19 04 PM" src="https://user-images.githubusercontent.com/93319774/139496921-5a8afc5f-f8ce-442d-b84a-4e623a58cdaa.png">


```

**Comment by fzumstein** [comment]
For 1d arrays, you'll need to transpose them:

```
sheet["E2"].options(transpose=True).value = z
```

See: https://docs.xlwings.org/en/stable/datastructures.html#lists

**Comment by AhmedHelalM** [comment]
issue still exist however i amend the code 
def if_statmment():
    wb = xw.Book.caller()
    sheet = xw.sheets[2]
    df = sheet.range("A1").expand().options(pd.DataFrame).value
    z = df['Succes'] = np.where(df['stock']>10,'succeeded','not succeded')
    sheet["E2"].options(transpose = True).value = z

**Comment by fzumstein** [comment]
Sorry I couldn't help. Feel free to reopen with a Excel workbook/Python code attached so I can easily replicate.
