### ISSUE TITLE
"DataLabels" in Excel Chart is Not Working

### ISSUE THREAD

**Issue by jpmungeri** [xlwings/xlwings#1756]
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by jpmungeri** [comment]
#MS Excel Version 16
#Window 10
#xlwings 0.24.9
Please find below the code..
Problem is: Code does show any Traceback error but desired DataLabes is not display on Chart neither on Pie nor on Line.. 
import pandas as pd
import xlwings as xw
dt3 = pd.DataFrame({'Org':['a','b','c','d'],
                  'revenue':[21, 19, 22, 24]}) 
wb=xw.Book()
wb.sheets.add('s')
ws=wb.sheets('s')
ws.range('a1').value = dt3
chart=xw.Chart()
chart.set_source_data(ws.range("c1:c5"))
chart.chart_type = 'pie'
#chart.chart_type = 'line'

chart.api[1].FullSeriesCollection(1).ApplyDataLabels
chart.api[1].FullSeriesCollection(1).DataLabels.ShowValue=True  
#chart.api[1].FullSeriesCollection(1).DataLabels.ShowPercentage = True

**Comment by jpmungeri** [comment]
When Using pywin32 (win32com.client) for Same  (#1756) .. throw following Traceback error...
#################################################
chart.SeriesCollection(1).DataLabels.ShowValue = True 
Traceback (most recent call last):

  File "<ipython-input-384-aa409913ecd1>", line 1, in <module>
    chart.SeriesCollection(1).DataLabels.ShowValue = True # Not working

AttributeError: 'method' object has no attribute 'ShowValue' 
######################
#My Code is.....
#pywin32 301
import win32com.client as win32
xa = win32.Dispatch('Excel.Application')
xa.Visible = True
workbook=xa.Workbooks.Open("px.xlsx")
worksheet = workbook.Worksheets('s')
chart_objects= worksheet.ChartObjects()
chart_object=chart_objects.Add(200,100,500,250) 
chart.SetSourceData(worksheet.Range('b1:c5'))
chart.XValues=worksheet.Range("b2:b5")
chart.ChartType =4 
chart.SeriesCollection(1).ApplyDataLabels
chart.SeriesCollection(1).DataLabels.ShowValue = True   <=== This line gives error

Pls Suggest..

**Comment by fzumstein** [comment]
Try `ApplyDataLabels()` (it's a method)

**Comment by jpmungeri** [comment]
Thanks... Its working Now
