### ISSUE TITLE
Hello, I met a difficulty and need help. Thank you.

### ISSUE THREAD

**Issue by zqgewd** [xlwings/xlwings#1759]
Windows10，64 bits
Py3.7
xlwings 0.25
pip Installation

Impore cannot be entered

It can't be used after successful installation. Reinstalling python, exles and WPS can't be solved. After entering "import xlwings as xw", it can't be entered. I always keep this interface. I hope I can get help. I really need this plug-in. Thank you.
![image](https://user-images.githubusercontent.com/40648428/140233176-42729ca7-e68d-4bcb-a7d0-6b09935e8d67.png)

**Comment by fzumstein** [comment]
Unfortunately, xlwings doesn't support WPS, see #1457
