### ISSUE TITLE
Custom Format for Trendline Equation

### ISSUE THREAD

**Issue by jpmungeri** [xlwings/xlwings#1760]
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by jpmungeri** [comment]
Window 10, 
MS Excel 16
xlwings 0.24.9
**_Objective is to highlight the only Coefficient of Trendline equation_** (copied in text box)
(Example: Highlight Only "31.712" in Equation : y = 31.712x + 1353.1)

 Win32com.client code for relevant part is as below..
 
chart_objects= worksheet.ChartObjects()
chart_object=chart_objects.Add(200,100,500,250) 
chart=chart_object.Chart 
tb=chart.Shapes.AddTextbox(1,100,100,200,50)
eq=chart.FullSeriesCollection(1).Trendlines(1).DataLabel.Text
tb.TextFrame2.TextRange.Characters.Text=eq
tb.TextFrame2.TextRange.Characters.Font.Size=23
tb.TextFrame2.TextRange.Characters.Font.Fill.ForeColor.RGB = xw.utils.rgb_to_int((255, 0, 0))

#Till above everythings is working fine.. but error in following line when trying to change color of coefficient part only...
tb.TextFrame2.TextRange.Characters(5,6).Font.Fill.ForeColor.RGB = xw.utils.rgb_to_int((0, 0, 255))

##################################################################################
Traceback (most recent call last):

  File "<ipython-input-391-db601cdc70ca>", line 1, in <module>
    tb.TextFrame2.TextRange.Characters(2,5).Font.Fill.ForeColor.RGB = xw.utils.rgb_to_int((0, 200, 255))

  File "C:\Users\mishjai\AppData\Roaming\Python\Python37\site-packages\win32com\client\dynamic.py", line 186, in __call__
    return self._get_good_object_(self._oleobj_.Invoke(*allArgs),self._olerepr_.defaultDispatchName,None)

com_error: (-2147352559, 'Does not support a collection.', None, None)

####################################################################################
#VBA Code for the Same is as below (Working fine)
Sub w()

    ActiveChart.Shapes.Range(Array("TextBox 1")).Select
    With Selection.ShapeRange(1).TextFrame2.TextRange.Characters(5, 6).Font.Fill
        .Visible = msoTrue
        .ForeColor.RGB = RGB(255, 0, 0)
        .Transparency = 0
        .Solid
    End With
    Selection.ShapeRange(1).TextFrame2.TextRange.Characters(5, 6).Font.Size = 28
End Sub

**Pls suggest the way to do it in win32com or in xlwings (version :0.24.9)**

**Comment by jpmungeri** [comment]
Also Tried..
tb1.TextFrame2.TextRange.**_GetCharacters(5,6)_**.Fill.ForeColor.RGB = xw.utils.rgb_to_int((0, 200, 255))
Get error......
Traceback (most recent call last):

  File "<ipython-input-468-ede806f15460>", line 1, in <module>
    tb1.TextFrame2.TextRange.GetCharacters(5,6).Fill.ForeColor.RGB = xw.utils.rgb_to_int((0, 200, 255))

  File "C:\Users\mishjai\AppData\Roaming\Python\Python37\site-packages\win32com\client\dynamic.py", line 554, in __getattr__
    raise AttributeError("%s.%s" % (self._username_, attr))

AttributeError: GetCharacters.Fill

**Comment by fzumstein** [comment]
See also: https://docs.xlwings.org/en/stable/api.html#font and https://docs.xlwings.org/en/stable/api.html#characters
