### ISSUE TITLE
Using xlwings how to add filters to column?

### ISSUE THREAD

**Issue by Kashfia18** [xlwings/xlwings#1767]
#### Describe your issue (incl. Traceback!)
I am trying to add filters to column. 
![Capture](https://user-images.githubusercontent.com/35579316/142686192-d338b704-4ea8-433c-90cc-c3bd0d04555b.PNG)

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

df.to_excel("abc.xlsx", index=False)
filename="abc.xlsx"
app = xlwings.App(visible=False)
 wb = xlwings.Book(filename)
ws = wb.sheets["Sheet1"]
ws.autofit(axis="columns")

#trying to add filters to columns here
ws.api.Filter (??)

wb.save(filename)
wb.close()
app.quit()
```

**Comment by fzumstein** [comment]
Try this:

```
ws['A1'].api.AutoFilter(Field=1)
```

See also: https://stackoverflow.com/questions/2967949/setting-criteria-on-an-autofilter-in-pywin32

**Comment by Kashfia18** [comment]
Thanks! It worked

**Comment by yawwwwwn** [comment]
I tried `sht.range('B1').api.AutoFilter(Field=1)` as I wanted to perform AutoFilter only on Column B. However, the filter arrows appeared on all columns with data. Why? And how could I achieve my thought? Thx.

**Comment by 2noScript** [comment]
![image](https://github.com/user-attachments/assets/960a8349-1197-4d0c-93c9-e6da9e79db0d)

![image](https://github.com/user-attachments/assets/fc203cbb-b995-4143-b34c-9044d77120eb)

I tried but it doesn't work on macos with version 0.33.4
