### ISSUE TITLE
need help~ Sorry to use this method

### ISSUE THREAD

**Issue by zcj52hz** [xlwings/xlwings#1770]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
 Python 3.7.6  Office2016
#### Describe your issue (incl. Traceback!)
Before I run the python script, I put the excel cell in the editing state, which caused the program to jam.
I see that in `_xlwindows.py` , there is a variable `N_COM_ATTEMPTS` cause that in dead cycle , I can change this variable to catch the `ExcelBusyError` and show a message info for user, but is there anyway to cancel the cell editing state api? I try to read the official website, but I haven't found the api can do that . I think it's not a issue, and I just want some help.
Best wishes !
```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
The only thing coming to mind is `app.interactive`: https://docs.xlwings.org/en/stable/api.html#xlwings.App.interactive, but this may not be the right thing in your case. Also see https://github.com/xlwings/xlwings/issues/1001.

**Comment by zcj52hz** [comment]
> The only thing coming to mind is `app.interactive`: https://docs.xlwings.org/en/stable/api.html#xlwings.App.interactive, but this may not be the right thing in your case. Also see #1001.

thanks for your help , I can catch the `ExcelBusyError` ,too .  I have tried to use the  `app.interactive`,  when cell is in editing, but it will be in dead cycle before the `app.interactive` work.
Thank you for your recovery anyway.   :D  👍

**Comment by fzumstein** [comment]
Great, thanks, closing this then.
