### ISSUE TITLE
Hi I cannot open a saved file with xlwings, it looks like it's not responding and creating error.

### ISSUE THREAD

**Issue by ivonkal** [xlwings/xlwings#1772]
Hi I cannot open a saved file with xlwings, it looks like it's not responding and creating error.
I also used r at the beginning of the code line
I am working with Windows.
Please see below

  line 1
    ‪"C:\\\Users\\\finance\\\Desktop\\\Test1p.xlsx"
     File "<ipython-input-71-817a3f5000db>", line 1
SyntaxError: invalid character in identifier

**Comment by fzumstein** [comment]
sorry, must have missed this, did you ever get this to work?
