### ISSUE TITLE
Could not activate Python COM server, hr = -2147221164 1000

### ISSUE THREAD

**Issue by Luanbird** [xlwings/xlwings#1774]
Try this:

* Install 0.20.7 and verify everything works
* Go to the directory of your Python installation and copy out the 2 files `xlwingsXX-0.20.7.dll`
* Install 0.20.8 (`pip install xlwings==0.20.8` and `xlwings addin install`)
* Activate the `Show Console` checkbox in the add-in
* Verify that things are broken (are you getting anything meaningful in the Command Prompt?)
* Close Excel and verify in the Task Manager that you don't have any Excel  zombie processes
* Rename the dlls you copied before from 0.20.7 to 0.20.8 and copy them over the ones that sit next to the Python intepreter, i.e. overwrite the ones installed by xlwings
* Test if it works now (yes, a quickstart project is always a good idea for that matter)

_Originally posted by @fzumstein in https://github.com/xlwings/xlwings/issues/1502#issuecomment-786473073_

Hi fzumstein:
I have try that but not solve the problem.when I overwrited the files installed by xlwings,the new problem pop up like this:
Error
Python process exited before it was possible to create the interface object.
Command: cmd.exe /K D:\Program Files\Python\Python39\python.exe -B -c "import sys, os;import xlwings.utils;xlwings.utils.prepare_sys_path("C:\Users\gaodong\myproject\myproject.xlsm;C:\Users\gaodong\AppData\Roaming\Microsoft\Excel\XLSTART\xlwings.xlam;;;;");import xlwings.server; xlwings.server.serve('{28362201-85ae-402b-86a6-37dc28d20796}')"
Working Dir: 1000

Any idea where I should start?
I appreciate any feedback here.

Luanbird

**Comment by Luanbird** [comment]
Hi fzumstein:
I have try that but not solve the problem.when I overwrited the files installed by xlwings,the new problem pop up like this:
---------------------------
Error
---------------------------
Python process exited before it was possible to create the interface object.
Command: cmd.exe  /K D:\Program Files\Python\Python39\python.exe -B -c "import sys, os;import xlwings.utils;xlwings.utils.prepare_sys_path(\"C:\\Users\\gaodong\\myproject\\myproject.xlsm;C:\\Users\\gaodong\\AppData\\Roaming\\Microsoft\\Excel\\XLSTART\\xlwings.xlam;;;;\");import xlwings.server; xlwings.server.serve('{28362201-85ae-402b-86a6-37dc28d20796}')"
Working Dir: <unspecified> 1000

Any idea where I should start?
I appreciate any feedback here.

Luanbird

**Comment by fzumstein** [comment]
Are you using a RunPython call or a UDF?

**Comment by Luanbird** [comment]
Hi fzumstein,
I import UDF module(which is the same py file) doesn't work. I face the same issue as MagneAA in #1502. I have try the solution,but it doesn't work. The old version of xlwings it worked fine.(i.e version 0.20.7 works fine.) 
Version 0.20.8 does not work.
Version 0.25.0 does not work.
Version 0.25.1 dose not work.
Any idea where I should start?

**Comment by fzumstein** [comment]
What happens if you run a quickstart project and hit the `Run main` button in the add-in?

**Comment by Luanbird** [comment]
Hi fzumstein,
I installed 0.20.8(or 0.25.1/0.25.2) via pip and succesfully created a project using quickstart.
when I run "Run main" it prints ""Hello xlwings". It obviously reads my module but import of UDF module(which is the same py file) doesn't work.

**Comment by fzumstein** [comment]
Does it work if you run UDFs in debug mode? See https://docs.xlwings.org/en/stable/debugging.html#udf-debug-server

**Comment by Luanbird** [comment]
![debugging报错](https://user-images.githubusercontent.com/94918345/145045755-8905fcd5-dc3f-41cc-977c-d5c9d61853f6.png)

**Comment by fzumstein** [comment]
This looks good, but can you switch to `Console` instead of `Debugger` on the bottom left to see the exception properly?

**Comment by fzumstein** [comment]
closing this since I didn't hear back.

**Comment by meenmo** [comment]
Hi @fzumstein, I am having exactly same issue. Could you provide further help?

**Comment by fzumstein** [comment]
@meenmo, please open a new issue, providing your exact details, thanks.
