### ISSUE TITLE
Copy paste formatting xlwings version 0.15.4

### ISSUE THREAD

**Issue by qzyu888** [xlwings/xlwings#1778]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10 Enterprise

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings=0.15.4
Excel=Microsoft Excel for Microsoft 365
Python=2.7.16

#### Describe your issue (incl. Traceback!)
I'm using an old version of xlwings which I can't update since it's part of a package from my company. I want to copy+paste some cells which includes the formatting. I've seen some solutions, but they only seem to work for higher versions of xlwings. I noticed in some other work that I can do some basic VBA commands with the .api command. Here, I've only managed to find a .Copy() but no corresponding .Paste() that includes the cell formatting.

In other words, I want to do what is similar to highlighting a range of cells in Excel and dragging it horizontally to copy paste over the cell functions/values and their formatting. Is this possible? Thank you for your time.
```python
# Your traceback here
sheet.range(some_range).api.Copy()

sheet.range(some_range).api.Paste()

---------------------------------------------------------------------------
com_error                                 Traceback (most recent call last)
<ipython-input-138-56fccbac40eb> in <module>()
----> 1 cap_trend_sheet.range(next_col_range).api.Paste()

C:\ProgramData\Anaconda2\lib\site-packages\xlwings\main.py in range(self, cell1, cell2)
    834                 raise ValueError("Second range is not on this sheet")
    835             cell2 = cell2.impl
--> 836         return Range(impl=self.impl.range(cell1, cell2))
    837 
    838     @property

C:\ProgramData\Anaconda2\lib\site-packages\xlwings\_xlwindows.py in range(self, arg1, arg2)
    592             arg2 = None
    593         else:
--> 594             xl1 = self.xl.Range(arg1)
    595 
    596         if arg2 is None:

C:\ProgramData\Anaconda2\lib\site-packages\win32com\client\dynamic.py in Range(self, Cell1, Cell2)

com_error: (-2147418111, 'Call was rejected by callee.', None, None)
```

**Comment by fzumstein** [comment]
You should be able to take over the corresponding code from its current implementation:
https://github.com/xlwings/xlwings/blob/main/xlwings/_xlwindows.py#L1020-L1048

**Comment by qzyu888** [comment]
@fzumstein Thanks for taking the time to help me with this, I really appreciate it. I gave it a try using the following:
```python
# Your traceback here
sheet.range(some_range).api.Copy()

sheet.range(some_other_range).api.PasteSpecial(Paste=-4104, Operation=-4142)
```
However, the result is simply that there's a new cell with the words 'PasteSpecial' and some other blank cells below it (I wanted to copy a column of cells over to the neighboring column of cells). I tried it with and without Operation. Is something wrong? Thank you for your time.
