### ISSUE TITLE
No command specified in the configuration, cannot autostart server 1000.

### ISSUE THREAD

**Issue by mininnx** [xlwings/xlwings#1785]
OS(Windows 11)
Versions of xlwings, Excel and Python (e.g. 0.25.2, Office 2016, Python 3.8.8)
Interpreter:D:\Program\python 3.8\python.exe
![屏幕截图 2021-12-14 164316](https://user-images.githubusercontent.com/96108851/145963746-cd78befe-23c2-427b-95cd-152e038b1fcb.png)

#### Describe your issue (incl. Traceback!)
issue ：No command specified in the configuration, cannot autostart server 1000.
![屏幕截图 2021-12-14 163752](https://user-images.githubusercontent.com/96108851/145962932-1b662b5c-1f96-4825-9cf2-93e0296011b2.png)
Hello, I am a student and a novice. I don't know how to solve the above problem. After checking a lot of information, there is no solution. Can you tell me what should I do?

```python
import xlwings as xw

@xw.func
def double_sum(x, y):
    """Returns twice the sum of the two arguments"""
    return 2 * (x + y)
```

**Comment by fzumstein** [comment]
Uncheck the `Debug UDFs` checkbox

**Comment by mininnx** [comment]
Uncheck the Debug UDFs checkbox, excel will not work, and then it's stuck.

**Comment by mininnx** [comment]
Uncheck the Debug UDFs checkbox, excel will not work, and then it's stuck. I have to end Excel through the task manager.

**Comment by fzumstein** [comment]
Activate `Show Console` and see what error it shows there.

**Comment by mininnx** [comment]
![屏幕截图 2021-12-14 171138](https://user-images.githubusercontent.com/96108851/145968352-fa208978-d876-48d6-8799-0d8e011b0ccb.png)

Hello, boss, how can I solve this problem, my other editors can recognize python3.8, why is this not possible?

**Comment by fzumstein** [comment]
can you translate the error msg?

**Comment by mininnx** [comment]
Sorry, the problem is that'D:\Program\python' is not an internal or external command, nor is it an executable program or batch file.

**Comment by fzumstein** [comment]
does the path to your python exe contain spaces? It's currently a bug with UDFs (RunPython works fine):https://github.com/xlwings/xlwings/issues/974

**Comment by mininnx** [comment]
No, but there is a "." in this path, is this the problem?

**Comment by fzumstein** [comment]
I honestly don't know. How did you configure the path to the interpreter in the add-in? manually or was that autogenerated during the installation of the add-in? If that was manual, try to reset the configuration by running `xlwings config create --force` (running this from a Command Prompt where the desired Python installation is the active one).

**Comment by mininnx** [comment]
Thank you very much, boss, I reconfigured the path and the problem was finally solved. I found that there was a problem with my original Python path. Thank you very much for your guidance.

**Comment by Alaric1-tech** [comment]
@mininnx I am facing the same problem now while running the code. Could you post what the solution is?

**Comment by Nikolas10091503440** [comment]
Good afternoon,

I tried to import UDF and I have received the following error from console
![console_error](https://user-images.githubusercontent.com/107265344/173094949-45337687-df22-4847-ac28-d7a825f24f59.jpg)


Along with the following popup " Could not activate Python COM server, hr=-2147221164 1000.

I don't have any problems when using Run Main or Run Python, only when trying to import UDF.

Thank you for your kind consideration

**Comment by mininnx** [comment]
The python file should have the same name as the Excel file and should be in the same directory.

**Comment by Nikolas10091503440** [comment]
mininnx thank you for your response. The python script (.py) and the the excel file they are under the same directory, that's why I don't have problem using the Run Main.

**Comment by fzumstein** [comment]
@Nikolas10091503440  try to delete  the `%TEMP%\gen_py` folder and try again. Also, for next time don't reuse closed issues but open a new one.
