### ISSUE TITLE
Returning a Scripting.Dictionary Object from VBA

### ISSUE THREAD

**Issue by cjsisco** [xlwings/xlwings#1795]
#### Issue: returning to Python a Scripting.Dictionary Object from VBA
The code snippet below returns... 
- VBA arrays as type: tuple
- VBA dictionary as type: COMRetryObject 

Can xlwings return a dictionary object? If not, is there a preferred method for passing this information?    

```python
# Test script to call VBA routine from Python and return objects

# %%
# import packages
import xlwings as xw 
import pandas as pd 

# %%
# get workbook object
xlFileName = "wb_Dict.xlsm"
wb = xw.Book(xlFileName)

# %%
# get macro object and call function
xlFctName = "Test_VBAtoPython"
fct = wb.macro(xlFctName)
A = fct("A")
B = fct("B")
dict = fct("all")

```
```VBA
' this routine is in a module inside "wb_Dict.xlsm"

Public Function Test_VBAtoPython(Optional str As String = "all")

    Dim A() As Double, B() As Double, _
        nR As Integer, nC As Integer, i As Integer, k As Integer
    
    'populate vars
    nR = 2
    nC = 3
    ReDim A(1 To nC), B(1 To nR, 1 To nC)
    For k = 1 To nC
        A(k) = nC * k
        For i = 1 To nR
            B(i, k) = i * k
        Next i
    Next k
    
    'construct dictionary
    Dim dict As New Scripting.Dictionary
    dict("A") = A
    dict("B") = B
    
    'return
    str = LCase(str)
    If str = "a" Then
        Test_VBAtoPython = A
    ElseIf str = "b" Then
        Test_VBAtoPython = B
    Else
        Set Test_VBAtoPython = dict
    End If
    
End Function
```

**Comment by fzumstein** [comment]
Scripting.Dicitionary isn't a VBA native structure, it comes from an external dll (and is therefore also not available in macOS). So I don't think there's an easy way to deal with it, no. See also:

https://stackoverflow.com/questions/11192437/com-interop-dictionary-used-in-c-sharp

**Comment by cjsisco** [comment]
Thank you for the quick response! I also tried returning a Collection object, which I think is a native VBA structure, and I had the same issue as with the Dictionary.

**Comment by fzumstein** [comment]
I think pywin32 does only handle the conversion of basic data types and arrays out of the box. There might be way to implement what you'd like, but I honestly don't know how. If you can do the conversion in VBA, it's definitely easier.

**Comment by cjsisco** [comment]
What I have is a lookup table with (x,y,z) coordinates and then a list of ~20 properties that correspond to each (x,y,z), and this information is obtained from a rather extensive calculation. 

I wanted to pull the variables into Python using a dictionary because this is the variable type this function has always returned. However, this case worked just fine to extract from the dictionary in VBA and pass to a variant array, then pass the variant array into Python, and then extract from within Python. It yields the same outcome as passing the dictionary would have done but with a couple of extra steps. Not a big problem at all.

**Comment by fzumstein** [comment]
ok great, closing this issue then.
