### ISSUE TITLE
How to call excel instance instead of WPS instance

### ISSUE THREAD

**Issue by githubfzq** [xlwings/xlwings#1796]
#### OS
Windows 10
#### Versions of xlwings, Excel and Python
xlwings: 0.25.3
Excel: 
- Office professional 2019
- WPS Office

Python: 3.10.0

#### Describe your issue 

`xlwings.apps` got empty instance:
```python
import xlwings as xw
print(xw.apps)

Apps([])
```

If call `Book` instance, WPS excel instance rather than Microsoft excel instance is called:
```python
wb = xw.Book('fresh/fresh.xlsm')
```
![WPS_excel](https://user-images.githubusercontent.com/19188149/149702787-8aed1acb-d84a-4493-9973-0f26a132c70f.png)

I have changed all default applications about excel to microsoft, but not work.

**Comment by fzumstein** [comment]
Maybe "repair" Microsoft Office, otherwise, I have no idea. Maybe it would be a good idea to ask WPS about that...Closing this as I consider this a WPS rather than an xlwings issue.
