### ISSUE TITLE
OS Error: -1743 (User has declined permission) when trying to use xlwings

### ISSUE THREAD

**Issue by febinjose24** [xlwings/xlwings#1797]
Hi,

I have made a program with a GUI (PyQt5) that edits excel sheets with Python, Openpyxl, and Xlwings. I have used PyInstaller to make this into an app.

Now I have the .app format and an exec. When I run the .exec by double-clicking from Finder the program works fine. When I run the .app from the terminal with this command:

`./dist/main_window.app/Contents/MacOS/main_window`
The program works fine.

However, when I try and double click the .app the GUI launches and the GUI works perfectly, but when I hit the button that uses openpyxl and xlwings the app crashes.

I tried catching the exception and got this:
![Screen Shot 2022-01-18 at 10 02 05 pm](https://user-images.githubusercontent.com/96866462/149951741-25242019-e337-47aa-ba9f-e89bc929eace.png)

I have checked my System Preferences -> Security & Privacy and have given the .app file Full Disk Access and Developer Tools Access.

This is how the structure of my code is:
A button in the GUI calls this function (this is where I use OpenPyxl):
```
def creating_planner(year, uni_name, bin_day, bin_week, add_school):
    wb = Workbook()
    jan = wb.create_sheet("JANUARY")
    feb = wb.create_sheet("FEBRUARY")...
    
... desktop = os.path.join(os.path.join(os.path.expanduser('~')), 'Desktop') 
    xlsx_name = str(year) + " Planner.xlsx"
    wb.save(desktop + "/" + xlsx_name)
    adding_colours_PH(year)
```
The code works well up to here, it saves the excel sheet on the Desktop. After this step, I use a function that opens this excel workbook in XlWings, the code is below:
```
def adding_colours_PH(year):
    info, reason = publicHolidays(year)
    desktop = os.path.join(os.path.join(os.path.expanduser('~')), 'Desktop') 
    xlsx_name = str(year) + " Planner.xlsx"
    wb = xw.Book(desktop + "/" + xlsx_name)...
```
I believe this is where the error message comes up.

Could you please help me fix this error?

**Comment by fzumstein** [comment]
If the program runs fine from the Terminal, I'd say it's an issue when you run it the PyInstaller exe. Maybe this thread helps: https://github.com/pyinstaller/pyinstaller/issues/4817

**Comment by febinjose24** [comment]
Apologies, to fix this problem a small tweak to the PyInstaller file was needed. Solution: https://github.com/pyinstaller/pyinstaller/issues/6516
