### ISSUE TITLE
Incorrect encoding in error messages (UTF-8 not decoded)

### ISSUE THREAD

**Issue by panda-34** [xlwings/xlwings#1799]
#### xlwings-0.25.3, Excel 2013, Python 3.7

if in python code I execute, for example `raise RuntimeError('ошибка')`
in Excel I get `err.Description = "RuntimeError: РѕСРёР±РєР°"` which is raw UTF-8 bytes reinterpreted in system codepage.
So it is impossible to raise errors in user's native language.
The error messages received from python should be decoded from UTF-8 to wide chars.

**Comment by fzumstein** [comment]
Is that by using the normal `RunPython` call?

**Comment by panda-34** [comment]
by RunPython or in UDF, doesn't matter

**Comment by fzumstein** [comment]
For RunPython, the problem is the way that VBA reads in the error dump. It should be fixable like this (on Windows): https://stackoverflow.com/questions/10996922/specify-encoding-when-open-for-input-vb

**Comment by panda-34** [comment]
The problem is actually with pywin32:
https://github.com/mhammond/pywin32/issues/1823

**Comment by fzumstein** [comment]
perfect, thanks for looking into this!

**Comment by mhammond** [comment]
FWIW, I'm working on a fix to pywin32 in https://github.com/mhammond/pywin32/pull/1833, so it will be in the next release, but I thought it worth noting:

> which is raw UTF-8 bytes reinterpreted in system codepage.
> So it is impossible to raise errors in user's native language.
> The error messages received from python should be decoded from UTF-8 to wide chars.

utf-8 shouldn't come into it here and remains unlikely to work. What *will* work us using normal Python unicode strings.

**Comment by fzumstein** [comment]
That's awesome, thanks @mhammond !!
