### ISSUE TITLE
Get drop down values from another sheet with custom formulas

### ISSUE THREAD

**Issue by anilsathyan7** [xlwings/xlwings#1806]
#### OS (e.g. Windows 10 or macOS Sierra)
Window s10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Python - 3.10.2
Excel wings - 0.26.1
#### Describe your issue (incl. Traceback!)
How can we access the drop-down values using data validation, when data validation **Formula1** contains a reference to another sheet(source values) or contains functions like INDIRECT, SUBSTITUTE, MATCH etc?

For eg: in a given wokrbook;
`options_name = sheet.range('J3').api.Validation.Formula1[1:]`

This gives the value
**=OFFSET(INDIRECT(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(K5," & ","___")," and ","___")," ","_")),0,0,COUNTA(INDIRECT(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(K5," & ","___")," and ","___")," ","_"))),1)**

Does xlwings support automatic parsing of such formulas, so that they can be accessed in a similar manner:-
`options = sheet.range(options_name)`

Ref: https://github.com/xlwings/xlwings/issues/901

**Comment by fzumstein** [comment]
No, xlwings doesn't support formula parsing, so you'd have to rebuild the logic in Python or introduce an intermediate step in your spreadsheet where you write out the values to a sheet before using them in the validation.

**Comment by anilsathyan7** [comment]
I tried to assign the formula value to an empty cell using xlwings; but it just assigns one value from the source drop-down values instead of all values. It correctly shows all values in excel when the same formula is added manually in the formula bar. 

```
sheet.range('G11').value = '=OFFSET(INDIRECT(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(I3," & ","___")," and ","___")," ","_")),0,0,COUNTA(INDIRECT(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(I3," & ","___")," and ","___")," ","_"))),1)'
 print(sheet.range('G11').value)
```

**Comment by fzumstein** [comment]
I guess it makes more sense the other way around then: implement the formula somewhere in your Excel workbook and read it from there.

**Comment by anilsathyan7** [comment]
After adding the formula and saving it, as shown above, an extra @ is added in the saved excel sheet in the corresponding cell formula and hence gives the wrong result.
` '=@OFFSET(INDIRECT(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(I3," & ","___")," and ","___")," ","_")),0,0,COUNTA(INDIRECT(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(I3," & ","___")," and ","___")," ","_"))),1)'`

Is there a way to fix this? This should solve the issue in that case.

**Comment by fzumstein** [comment]
Can you try to set it using `formula2` like: `myrange.formula2 = "...."`

**Comment by anilsathyan7** [comment]
Ok, thanks. It works now.  Is there a way to check if the cell contains data validation? The 'Type'  property for the Validation object throws an error if the cell does not have a validation formula or values. I was trying to extract all drop-down values from the sheet.
