### ISSUE TITLE
Patterns in xlwings

### ISSUE THREAD

**Issue by hghaffari** [xlwings/xlwings#1818]
#### Describe your issue (Hatching)

I want to implement variety of Hatches (i.e. Patterns) in Excel Cells (e.g. 

xlPatternsCrissCross, xlPatternDown, xlPatternVertical, xlPatternDiagonal, etc.)

How can I implement Patterns in xlwings?

**Comment by fzumstein** [comment]
You'd currently need to use pywin32 directly: 

```python
import xlwings as xw
from xlwings.constants import Pattern

myrange.api.Interior.Pattern = Pattern.xlPatternCrissCross
```

**Comment by hghaffari** [comment]
Felix:

I appreciate the tip. Now I can create patterns in Excel cells using
xlwings.


Thanks,

Homer Ghaffari
