### ISSUE TITLE
How to give RefreshAll a delay to finish

### ISSUE THREAD

**Issue by qzyu888** [xlwings/xlwings#1828]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xw=0.15.4 python=2.7

#### Describe your issue (incl. Traceback!)
I try to run RefreshAll on a workbook, but it jumps to a next line of code before it finishes. This causes a pop-up in Excel asking about whether to interrupt the refresh. I've seen workarounds in VBA etc., but is there something simple for xlwings?

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
wb = xw.Book(file_path) # Open workbook
wb.api.RefreshAll()
```

**Comment by qzyu888** [comment]
Figured out a workaround. From these two sources (https://stackoverflow.com/questions/20278363/this-action-will-cancel-a-pending-refresh-data-command), (https://www.excelcampus.com/vba/enable-background-refresh-on-all-power-query-connections/), I was able to guess that we need to disable the background refresh option. I'm not too clear on what it is exactly to be honest. However, I just used the api to access the VBA commands to do so. It seems to do the trick, where the refresh first takes place and Excel will wait until it finishes before closing. This works well when the refresh takes a good amount of time.

`
        wb = xw.Book(file_path)
        # Disable Background Refresh to allow RefreshAll to complete
        wb.api.Connections(1).OLEDBConnection.BackgroundQuery = False

        # Reference: https://stackoverflow.com/questions/53871709/refreshall-in-excel-file-with-xlwings
        # Perform RefreshAll on the data
        print("Refreshing data...")
        wb.api.RefreshAll()
        print("Finished!")
        # Re-enable Background Refresh as it was by default
        wb.api.Connections(1).OLEDBConnection.BackgroundQuery = True

        # Save and close
        wb.save()
        wb.close()
`

**Comment by alexandrdera** [comment]
Thanks! How did you find the answer? I don't understand how to use the xlwings api to access VBA commands(((
