### ISSUE TITLE
xlwings Attribute Error

### ISSUE THREAD

**Issue by polydorou96** [xlwings/xlwings#1844]
#### Describe your issue (incl. Traceback!)

I have an excel workbook which utilises xlwings but as soon as I open up the workbook I get the following error:
AttributeError: module xlwings.utils has no attribute 'prepare_sys_path'

I tried searching for what might cause this but nothing helped because all of xlwings.conf settings are inserted correctly, and I checked the vba editor that xlwings checkbox has been selected. I am not sure how to debug this and any help would be greatly appreciated!

**Comment by fzumstein** [comment]
Make sure you're using the same version of the add-in/VBA code as in the Python package.

**Comment by polydorou96** [comment]
From where can I check this?

**Comment by fzumstein** [comment]
on the add-in itself and by doing `import xlwings; print(xlwings.__version__)` on a Python prompt. Probably easiest if you just run `xlwings addin install` again as per update instructions: https://docs.xlwings.org/en/stable/installation.html#update

**Comment by polydorou96** [comment]
I think that worked. Thank you very much for your prompt replies I really appreciate it!
