### ISSUE TITLE
xlwings installation issue

### ISSUE THREAD

**Issue by hermie64** [xlwings/xlwings#1853]
#### Describe your issue (incl. Traceback!)
I'm trying to install xlwings but I'm getting error as shown in screenshot regarding setuptools:
![2022-03-04_145629](https://user-images.githubusercontent.com/5301621/157002778-e3df25db-a563-4225-9c22-aaa8d301b531.png)

On my local workstation with Windows 2010 where I have Anaconda installed and xlwings 0.20.8, I get the same error when trying to upgrade to latest version of xlwings 0.26.3.

**Comment by hermie64** [comment]
I finally found a fix.

I added --no-build-isolation --no-use-pep517 to pip

[source](https://stackoverflow.com/questions/63970507/pip-install-pyinstaller-fails-with-unable-to-connect-to-proxy-where-i-dont-have)

**Comment by fzumstein** [comment]
I should have uploaded wheels ages ago. Will fix this with hopefully the next release.

**Comment by fzumstein** [comment]
fixed by #1855
