### ISSUE TITLE
Excel crashes on wb.close()

### ISSUE THREAD

**Issue by hermie64** [xlwings/xlwings#1854]
#### OS (e.g. Windows 10 or macOS Sierra)
Local workstation: Windows 10 Pro
Windows Server 2012

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Local workstation: 0.20.8, Microsoft Excel for Microsoft 386 (16.0.14326.20702) 32 -bit, 3.8.5)
Windows Server 2012: 0.20.8 (also tested with 0.26.3), Microsoft Excel 2016 (16.0.5278.1000) 32-bit, 3.8.6

#### Describe your issue (incl. Traceback!)
Hi,

On my local development environment with Anaconda (Python 3.8.5) my script runs perfectly.
On a Window Server with Python 3.8.6 installed, Excel crashes and I get this error when the script wants to close a workbook:

```python
Traceback (most recent call last):
  File "py_broadcast_1.py", line 181, in <module>
    wb_collect.close()
  File "D:\Python38\lib\site-packages\xlwings\main.py", line 708, in close
    self.impl.close()
  File "D:\Python38\lib\site-packages\xlwings\_xlwindows.py", line 501, in close
    self.xl.Close(SaveChanges=False)
  File "D:\Python38\lib\site-packages\xlwings\_xlwindows.py", line 66, in __call__
    v = self.__method(*args, **kwargs)
  File "C:\Users\OPS175~1\AppData\Local\Temp\gen_py\3.8\00020813-0000-0000-C000-000000000046x0x1x9.py", line 45078, in Close
    return self._oleobj_.InvokeTypes(277, LCID, 1, (24, 0), ((12, 17), (12, 17), (12, 17)),SaveChanges
pywintypes.com_error: (-2147023170, 'The remote procedure call failed.', None, None)
```

I have no clue why this fails on server. Any suggestions?

**Comment by fzumstein** [comment]
Excel isn't meant to run on servers, but you can try to mess around with with the DCOM configuration:


change Excel to run under a specific user (Make sure to run the correct command depending on the bitness of Excel)
    * If Excel is 32-bit: `Start > Run > mmc comexp.msc /32`
    * If Excel is 64-bit: `Start > Run > mmc comexp.msc`
    * `Component Services > Computers > My Computer > DCOM Config > Microsoft Excel Application`. Right click, select `Properties > Identity`, and change the user to `This user`, browse for `Administrator` and type in the password.

**Comment by fzumstein** [comment]
related: https://github.com/xlwings/xlwings/issues/1743

**Comment by hermie64** [comment]
Turns out that the cause for these Excel 2016 crashes were check boxes.
if you copy a worksheet with check box to a new workbook and try to close this new workbook, Excel 2016 will crash.
