### ISSUE TITLE
correct xlwings ddl

### ISSUE THREAD

**Issue by richard-ander** [xlwings/xlwings#1864]
Installation mismatch,  runpython asks for xlwings32-0.26.3.dll, xlwings32-0. 24.9.dll is installed. (which seems correct for xlwings version installed) Tried to reinstalled using conda and pip, did not resolve problem. 

Windows 10
Excel 19
Python 3.9
xlwings0.24.9
Code:
Sub SampleCall()
    mymodule = Left(ThisWorkbook.Name, (InStrRev(ThisWorkbook.Name, ".", -1, vbTextCompare) - 1))
    RunPython "import " & mymodule & ";" & mymodule & ".main()"
End Sub
Error:
Run-Time error 52
File not found: xkwungs32-0.26.3.ddl

**Comment by fzumstein** [comment]
run `xlwings addin install` again to bring things into sync
