### ISSUE TITLE
Access to chart sheets Excel

### ISSUE THREAD

**Issue by AlbertoCasetta** [xlwings/xlwings#1865]
#### Describe your issue (incl. Traceback!)

Hallo,
I have a chart sheet in my Excel book.
If I try to find the sheets of my book the once which contains the chart is not listed out.
Also, if i manually activate the chart sheet and ask xlwings to list the charts, I obtain an empty list.
How can I access a chart sheet form xlwings API and interact with the chart?

Thank you in advance.

Alberto
```

**Comment by fzumstein** [comment]
Hi Alberto, I've always considered Chart sheets to be legacy, so xlwings doesn't currently support them natively. You'd need to go via api. For example, if `wb` is your xlwings book object, you can do things like this that will work on chart sheets:

```python
wb.api.Sheets(1).Name
```
