### ISSUE TITLE
question -  how to match excel row and col with df row and col

### ISSUE THREAD

**Issue by SSMK-wq** [xlwings/xlwings#1872]
#### Versions of xlwings, Excel and Python (0.24, Excel 2019, Python 3.7)

I have a dataframe like as shown below

    ID,ABC,DEF,GHI
    1,20,40,10
    2,nan,60,nan
    3,40,10,20
    
    DATA_1 = pd.read_clipboard() 

And my excel looks like below

[![enter image description here][1]][1]

I would like to enter the dataframe values into the excel sheet.

However, I would like to enter the data in excel only when the `ID` and `column name` matches between excel and dataframe (ex: ID = 1 and column name `ABC` matches between both excel and df. So, we enter the corresponding value - 20). You can refer my expected output below for easy understanding.

I was trying something like below but this is not right and not elegant. I can't do this for 70 columns.

    for a_cell in sales.sheets[2].range("A3:A6"):
        id = a_cell.value
        for b_cell in sales.sheets[2].range("B"+str(a_cell.row)+":"+"D"+str(a_cell.row)):
                col_name = b_cell.value
                print("col_name is ",col_name)
                DATA_1 = DATA_1[DATA_1['ID']==id]
                for index, row in DATA_1.iterrows():
                        print(row['ID'],row[])

I expect my output to be like as below. We enter only in `DATA_1` because my input df is `DATA_1`

[![enter image description here][2]][2]
 
Is this something that you would be able to help me with?

  [1]: https://i.stack.imgur.com/R3LB9.png
  [2]: https://i.stack.imgur.com/vv0BO.png

**Comment by fzumstein** [comment]
I think you're looking for this:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/2265504/159263469-7ec26fa0-d610-42ca-b2e2-bc0c31a680b6.png">

**Comment by SSMK-wq** [comment]
@fzumstein - What if the matching column is not an index column? I already have a seperate index column 0,1,2,3 etc. Don't wish to make this column as an index

**Comment by SSMK-wq** [comment]
omg, I am amazed. I am not a software developer but just an analyst. This looks like a magic and I cannot comprehend how it works but it does work. Fantastic package. However, one quick question

```
DATA_1.set_index('subject_ID',inplace=True)
DATA_1.rename(index={'subject_ID': 'ID'},inplace=True)
```
While I renamed my dataframe index to match my excel column, I see that in my final output in excel, I see the old index name as shown below

![image](https://user-images.githubusercontent.com/30723825/159271181-d0136254-9847-4e55-9964-b48868235a40.png)

Am I making any mistake?

Below is the code that I used

```
rows = sales.sheets[0]['A3'].expand('down').value
cols = sales.sheets[0]['B2'].expand('right').value
sales.sheets[0]['A1'].expand().clear_contents()
sales.sheets[0]['A2'].value = DATA_1.reindex(index=rows,columns=cols)
```

If you have time and for the purpose of learning, would you be interested to help me (on how can I do this the usual way) through loops or xlwings cell range etc. Am new to xlwings and would be useful to know how can it be done the beginner way. This can help me understand/allow me to write my own code for slightly different requirements

**Comment by fzumstein** [comment]
For posterity:

```python
import pandas as pd
import xlwings as xw


region_1 = pd.DataFrame(
    columns=["ID", "DIV", "APP1", "APP2", "APP3", "Col1", "Col4"],
    data=[
        [1, "A", "AB1", "ABC1", "ABCD1", 20, 40],
        [2, "A", "AB1", "ABC2", "ABCD2", 60, None],
        [3, "B", "BC1", "BCD1", "BCDE1", 10, 20],
    ],
)
region_1 = region_1.set_index(["ID", "DIV", "APP1", "APP2", "APP3"])

sales_book = xw.Book("dummy.xlsx")
sheet1 = sales_book.sheets[0]

index_names = sheet1["B4:F4"].value
index_data = sheet1["B5:F8"].options(numbers=int).value
col_names = sheet1["G3:J3"].value

df_template = pd.DataFrame(columns=index_names + col_names, index=range(len(index_data)))
df_template[index_names] = index_data
df_template = df_template.set_index(index_names)

region_1 = region_1.reindex(columns=df_template.columns, index=df_template.index)

sheet1["G5"].options(index=False, header=False).value = region_1
```
