### ISSUE TITLE
xlwings create AutomationServer Object

### ISSUE THREAD

**Issue by hermie64** [xlwings/xlwings#1878]
#### OS

Windows 10 Pro

#### Versions of xlwings, Excel and Python

xlwings 0.27.3 
Microsoft Excel for Microsoft 386 (16.0.14326.20702) 32 -bit
Python 3.8.5

#### Describe your issue (incl. Traceback!)
I have an xlwing app that currently connects through Excel VBA (called in xlwings) to an xll-based Add-In to logon and refresh data.
This works fine, but I now would like to get rid of the Excel-part and move it to xlwings.
This is the VBA I'm using:

```python
Sub LogonAndRefresh()
    Dim bSuccess As Boolean
    Dim CognosOfficeAutomationObject As Object
    Dim Reporting As Object
    Dim invokeAddin As Object

    Set CognosOfficeAutomationObject = Application.COMAddIns("CognosOffice12.Connect").Object.AutomationServer
    Set Reporting = CognosOfficeAutomationObject.Application("COR", "1.1")
    Set invokeAddin = Reporting

    CognosOfficeAutomationObject.SuppressMessages True
    bSuccess = CognosOfficeAutomationObject.Logon("https://server.net", "domain\user", "password", "CAM_name")
    bSuccess = CognosOfficeAutomationObject.Logon("https://server.net", "domain\user", "password", "DB_name")
    CognosOfficeAutomationObject.SuppressMessages False
    
    If (bSuccess) Then
        CognosOfficeAutomationObject.ClearAllData
        CognosOfficeAutomationObject.RefreshAllData
    End If
End Sub
```
I can with xlwings:

```python
for addin in app.api.COMAddIns:
    print(addin.description)
```

and:

```python
test = app.api.COMAddIns('CognosOffice12.Connect').Connect
```
returns True

but I think the issue is with .Object.AutomationServer:

```python
test = app.api.COMAddIns('CognosOffice12.Connect').Object.AutomationServer
```

returns an error:

pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'CognosOfficeInterfaceAddin12', 'AutomationServer object only available on a STA.', None, 0, -2146233088), None)

Any suggestions or examples how this could be done?

**Comment by fzumstein** [comment]
I wouldn't know, but the comment from your SO question has at least a few hints:

> So I am guessing STA stands for 'Single Threaded Apartment' ie the Object won't be reliable for multi-threading. You may need to go to the underlying pythoncom/win32com library to choose how to initialize COM. AFAIK Excel is by default a single-threaded execution model. Perhaps post your full python code. With win32com you can explicitly choose the COINIT_APARTMENTTHREADED threading model, which might help. [docs.microsoft.com/en-US/troubleshoot/windows/win32/…](https://docs.microsoft.com/en-US/troubleshoot/windows/win32/descriptions-workings-ole-threading-models) – 
[DS_London](https://stackoverflow.com/users/13812982/ds-london)
 [Feb 22 at 10:15](https://stackoverflow.com/questions/71204454/xlwings-create-automationserver-object#comment125888305_71204454)

**Comment by fzumstein** [comment]
You could try if it works on a pywin32 application object directly:

```python
from win32com.client.gencache import EnsureDispatch
app = EnsureDispatch('Excel.Application')  #  use this instead of app.api
```

Otherwise, you may want to reach out to the pywin32 issues/discussion forum as you're really working with pywin32 here, not xlwings.



```
