### ISSUE TITLE
Missing menu options with xlwings add-in

### ISSUE THREAD

**Issue by SSMK-wq** [xlwings/xlwings#1879]
#### Versions of xlwings, Excel and Python (e.g. 0.24, Excel 2019, Python 3.7)

I recently downloaded the xlwings add-in from the github page

When I enable the xlwings add-in, I see only the below

![image](https://user-images.githubusercontent.com/30723825/160233790-731799dd-5abf-4a41-aac8-7387aa2085bd.png)

But in the tutorial [here,](https://pythoninoffice.com/automate-excel-with-python-xlwings/) I see that they have more menu options with xlwings add-in

![image](https://user-images.githubusercontent.com/30723825/160233821-b20c0a5d-6888-4c9c-a518-93149c1da6db.png)

Why don't I see the same menu items when imported?  they are paid features?

**Comment by fzumstein** [comment]
No, your Excel thinks it's on Mac instead of Windows, it's only the 2nd time this is being reported. You can try to fix it here:
https://github.com/xlwings/xlwings/blob/main/xlwings/addin/RibbonXlwings.bas#L39-L45

as a workaround, just return always `True`.

**Comment by SSMK-wq** [comment]
@fzumstein - thanks for your help. But I don't see this code file in my python package xlwings folder (because I assume that's where the change has to be made). Below is the data that I see and when I navigate to `addin` folder, I see nothing ribbon like (shown below)

![image](https://user-images.githubusercontent.com/30723825/160234529-de88f95d-a038-48ef-bc27-e36777acd188.png)

![image](https://user-images.githubusercontent.com/30723825/160234565-3b1c51aa-3d14-403c-9d0b-521d8db28ff5.png)


In my python site-packages folder, I see the below two folder

![image](https://user-images.githubusercontent.com/30723825/160234603-10450cf0-4920-48a1-8c86-b4ea1ef7cb4c.png)

**Comment by fzumstein** [comment]
You would need to edit the addin directly in Excel: `Alt-F11`, double-click `xlwings` in the document tree on the left, type in `xlwings` as password, then you can open the module.

**Comment by SSMK-wq** [comment]
I updated the code  --> saved it --> restart excel --> import add-in again but I still see the same issue

Is it because, I get a message that "BLOCKED CONTENT - Macros have been disabled in this document by the enterprise administartor"?

I already clicked `enable all macros(dangerous to run code...)` option in macro settings

**Comment by fzumstein** [comment]
Well, the add-in does require macros to be enabled, yes. Not all macros, you just need to enable the macros once when the add-in is first used. 

What do you mean by "import add-in again"?

**Comment by SSMK-wq** [comment]
By import, I mean the below

![image](https://user-images.githubusercontent.com/30723825/160235228-9de53cc0-d61f-41b9-9f4c-e1a7f7c0f815.png)

I do this everytime because, as soon as I close excel file, `xlwings` tab goes away (and does not show up next time when I open the excel file)

So, I made the edit to the code by following below procedure

launch dummy.xlsx
press ALT+F11
double click xlwings, key in password
open module and naviagte to ribbon file
press save /ctrl+s
close the file

**Comment by fzumstein** [comment]
Have you originally installed the addin via `xlwings addin install`?

**Comment by SSMK-wq** [comment]
I was following this tutorial [here](https://pythoninoffice.com/automate-excel-with-python-xlwings/) and couldn't see a command like what you have given above

When I did `xlwings addin install` in my windows command prompt, I get the below error message
```
'xlwings' is not recognized as an internal or external command,
operable program or batch file.
```
When I do the same in Anaconda prompt, I get something like below (with no response for a while)

```
(base) C:\Users\Users>xlwings addin install
xlwings version: 0.24.9
-
```

**Comment by fzumstein** [comment]
Official docs are here: https://docs.xlwings.org/en/stable/installation.html#add-in

And yes, you'd run it in your anaconda prompt. I'd recommend to uninstall the add-in completely, then install it via xlwings command.

**Comment by SSMK-wq** [comment]
Thanks, the issue is resolved.
