### ISSUE TITLE
Question - End biz user system requirements

### ISSUE THREAD

**Issue by SSMK-wq** [xlwings/xlwings#1880]
#### Versions of xlwings, Excel and Python (e.g. 0.27.8,Excel 2019, Python 3.7)

I am currently trying to automate a manual task done in excel.

I wish to click a button and expect the python code to complete the task.

I have seen some YouTube tutorials online and understood how python can be used at the click of button

but my question, let's say my end user (VP, CEO) wants to click the button and the python code be run behind (automation tasks be completed)

Should they also install python, anaconda etc in their system? Or I should just transfer that folder (ex: quick-start demo project) to them?

**Comment by fzumstein** [comment]
Yes, they'll need a Python installation. See also: 

* https://docs.xlwings.org/en/stable/deployment.html
* https://docs.xlwings.org/en/stable/release.html
* https://docs.xlwings.org/en/stable/remote_interpreter.html
