### ISSUE TITLE
VS Code Error if open xw.Book() again

### ISSUE THREAD

**Issue by ActuarySense** [xlwings/xlwings#1884]
Hello Felix Sir,
I am trying to write a python code in VS where i take the data from file 1 and then i open another file
wb1 = xw.Book('file2') i am able to successfully paste the data in file 2 
and then i close it via
wb1.close()
and then within the same python script i open now file 3
Lets say wb2 = wb.Book('file3.xlsb') then my code break.
Few observations -: If i trigger the same code in Jupyter Notebook, it works smoothly. 
And if i trigger the code in VS code from the point where it breaks again..then it worked fine.

What am i missing sir? Why VS code won't let me open another wb via xlwings.

**Comment by fzumstein** [comment]
please add Traceback as per issue template.
