### ISSUE TITLE
RunPython not working on Mac Big Sur

### ISSUE THREAD

**Issue by jithuvp** [xlwings/xlwings#1888]
#### Excel 16.59(22031300)

(Opening a new issue as advised)
I just copied my xlwings-enabled Excel workbook to a new machine (also a Mac). I had to set up anaconda and xlwings from scratch on the new machine. I also installed Runpython. However, I keep getting, `To enable RunPython, please run 'xlwings runpython install' in a terminal once and try again.` when I try to run a macro. I can confirm the path on the interpreter does match with that of `which python`. Do you have any idea as to what the issue might be? Please advise.

**Comment by fzumstein** [comment]
Do you see the `xlwings.applescript` file under `~Library/Application Scripts/com.microsoft.Excel`?

**Comment by jithuvp** [comment]
@fzumstein  Yes, I do see `xlwings.applescript` under `~/Library/Application\ Scripts/com.microsoft.Excel`

**Comment by fzumstein** [comment]
Have you ever opened a Terminal and run the following? Does it work?

```
$ python
>>> import xlwings as xw
>>> xw.Book()
```

**Comment by jithuvp** [comment]
@fzumstein Yes it does.
<img width="560" alt="MicrosoftTeams-image (8)" src="https://user-images.githubusercontent.com/89812600/162101070-c3614447-ad9a-4826-a729-2a0c64d12827.png">

**Comment by fzumstein** [comment]
Can you try to upgrade to the latest version of xlwings (Python and Excel add-in) and see if the error persists?
