### ISSUE TITLE
UDF fails to return data frame type back to excel 2019

### ISSUE THREAD

**Issue by Drau** [xlwings/xlwings#1890]
#### OS
WIndows 10
#### Versions of xlwings, Excel and Python
xlwings == 0.27.5
Python == 3.9/3.10
Office 2019 home and business
#### Describe your issue (incl. Traceback!)
WIth the following UDF example
```
@xw.func
@xw.arg("rng", pd.DataFrame, index=False, header=True)
@xw.ret(header=True)
def format_table(rng, caller):
    return rng
```
The result in the excel cell remains blank. 
No errors, No exceptions, All seems to work good, except the cell remains empty.
(Ive debugged my real function and it works perfectly up until the return line, does manipulations on the data frame, etc... (i.e pandas installed))
* If I change ```return rng``` to ```return 5``` all works perfectly
* If i do json.dumps to my dataframe, its returned fine to the excel cell (As a string)

Ive copy/paste my code to a different windows 10, with same versions, but with office 365, and all works perfectly.

Thank you ! :)

**Comment by fzumstein** [comment]
Can you confirm that numpy/pandas versions are the same on both computers?

**Comment by Drau** [comment]
Yes, double checked. Latest versions.

**Comment by fzumstein** [comment]
Does that happen with every DataFrame?

**Comment by Drau** [comment]
Yes.
Ive tried multiple variations. 
Simply returned a range i selected in excel(as in the example) 
Or created a nre df inside the udf.

**Comment by fzumstein** [comment]
Given it works on another computer, that's a tough one. Things you can try:

* Set up a separate virtual/conda env from scratch and try with that
* Remove the ret decorator
* Return `df.to_numpy()` and `df.to_numpy().tolist()` and see what happens

**Comment by Drau** [comment]
Ok, so ive made progress.
Unfortunatly your suggestion did not work.
But i discovered the following:

The cell I entered the formula into, shows only the top left cell of the result.
Ive removed header=true from the ret decorator, and suddenly saw the data of cell at  row=0 and col=0.
Ive set index=false, and suddenly i see the first column's header text.

For some reason excel wont show the entire returned table. Only top left cell of the returned table.

The reason i saw nothing at my early tries is because header=true and index=true, cause the top left cell to be blank in the returned table.

I hope this helps somehow!

**Comment by fzumstein** [comment]
Looks like you don't have [dynamic arrays](https://support.microsoft.com/en-us/office/dynamic-array-formulas-vs-legacy-cse-array-formulas-ca421f1b-fbb2-4c99-9924-df571bd4f1b4) in this version of Excel then!

**Comment by Drau** [comment]
Ive checked, and seems Excel 2019 does NOT support dynamic arrays :( It never got that feature update from Microsoft... 

Thank you so much for the help! Now I know that by upgrading my office ill probably be able to use xlwings :)

Thanks again!

**Comment by fzumstein** [comment]
Yes, it's only in included in 365 or 2021. You can still use legacy CSE arrays or the xlwings workaround: https://docs.xlwings.org/en/stable/udfs.html#dynamic-array-formulas
