### ISSUE TITLE
XLWings - error - Your platform only supports the instantiation via xw.Book(json=...)

### ISSUE THREAD

**Issue by markdaltonmurray** [xlwings/xlwings#1893]
Hi,

I am new to python. I am getting the following error message when i try and use XLwings:

pip install xlwings

wb=xw.Book('202202-Equity Model.xlsx')
sheet=wb.sheets[0]
sheet1=wb.sheets[1]

XlwingsError: Your platform only supports the instantiation via xw.Book(json=...)

Could someone please help explain what this means/help fix the issue?

Thanks

![image](https://user-images.githubusercontent.com/88389231/162756816-b7ae811e-7bcf-46c5-b70f-b85acc21579c.png)

**Comment by fzumstein** [comment]
Hi Mark, at this point, xlwings only works either:

* On Windows or macOS with Excel installed
* On any OS as part of a web backend ("[remote interpreter](https://docs.xlwings.org/en/stable/remote_interpreter.html)")

See: https://docs.xlwings.org/en/stable/installation.html#prerequisites

Today, xlwings isn't the right package to read Excel files from disk. For that part you'd either need to use pandas or directly a package like OpenPyXL. While I am hoping to add this functionality to xlwings sooner or later, I don't know when it'll happen just yet.
