### ISSUE TITLE
Add, read, delete comments in Excel cell using xlwings

### ISSUE THREAD

**Issue by hghaffari** [xlwings/xlwings#1894]
I tried these and api.Comment,Delete does Not work
import xlwings as xw
wb = xw.apps[0].books[ 'test.xlsx']
wb.sheets['sheet1'].range('a1').api.Comment.Delete()

**Comment by fzumstein** [comment]
Since you didn't fill in the template: are you on Win or macOS?

**Comment by hghaffari** [comment]
Window.

**Comment by fzumstein** [comment]
`apps[0]` isn't a thing anymore since v0.13.0 (Oct 22, 2018). Use `app.active` or just `xw.Book()`. Also, either pasting a Traceback or describing what exactly doesn't work would help.

**Comment by hghaffari** [comment]
Felix:

the comment error is:

ms.sh_Main.range(hd.col_matlab_sum('fruits') +
str(iter)).api.Comment.Delete()

AttributeError: 'NoneType' object has no attribute 'Delete'

This refers to 2018 issue concerning Add/Delete Comment in xlwings:

pisteps <https://github.com/pisteps> commented on May 3, 2018
<https://github.com/xlwings/xlwings/issues/856#issue-319942983>

is it possible to delete a comment from a cell?

i managed to create a comment and read a comment, but can't delete it.

import xlwings as xw
wb = xw.apps[0].books[ 'test.xlsx']

#write a comment
wb.sheets['sheet1'].range('a1').api.AddComment('Some Text')

#read a comment
test = wb.sheets['sheet1'].range('a1').api.Comment.Text()

i tried this one to delete the comment but i get a "com_error":
wb.sheets['sheet1'].range('a1').api.DeleteComment()
[image: @fzumstein] <https://github.com/fzumstein>
Member
fzumstein <https://github.com/fzumstein> commented on May 3, 2018
<https://github.com/xlwings/xlwings/issues/856#issuecomment-386316454>

Just use Delete() instead of DeleteComment()
[image: @pisteps] <https://github.com/pisteps>
Author
pisteps <https://github.com/pisteps> commented on May 3, 2018
<https://github.com/xlwings/xlwings/issues/856#issuecomment-386320110>

thanks. is there anything that deletes just the comment and not the content
of the cell?
[image: @fzumstein] <https://github.com/fzumstein>
Member
fzumstein <https://github.com/fzumstein> commented on May 3, 2018
<https://github.com/xlwings/xlwings/issues/856#issuecomment-386321111> •
edited

I meant of course wb.sheets['sheet1'].range('a1').api.Comment.Delete()
[image: @pisteps] <https://github.com/pisteps>
Author
pisteps <https://github.com/pisteps> commented on May 3, 2018
<https://github.com/xlwings/xlwings/issues/856#issuecomment-386322020>

right. thanks a lot!
[image: @fzumstein] <https://github.com/fzumstein> fzumstein
<https://github.com/fzumstein> closed this on May 3, 2018
<https://github.com/xlwings/xlwings/issues/856#event-1608018637>
[image: @pisteps] <https://github.com/pisteps>
Author
pisteps <https://github.com/pisteps> commented on Aug 27, 2018
<https://github.com/xlwings/xlwings/issues/856#issuecomment-416275593>

in case i want to delete all comments from a range is there something i can
use?
i tried this but gives an error:
wb.sheets['sheet1'].range('a1:b100').api.Comment.Delete()
*Please give general directions on how to add/delete comments in xlwings.*

Thanks,


Homer Ghaffari

**Comment by fzumstein** [comment]
What happens when you do the following?

```python
ms.sh_Main.range(hd.col_matlab_sum('fruits') +
str(iter)).note.delete()
```

**Comment by hghaffari** [comment]
It gives Error:

AttributeError: 'Range' object has no attribute 'note'

Although range is used and the note and delete are visible as related
attributes!

ms.sh_Main.range(hd.col_matlab_sum('fruits') + str(iter)).note.delete()

**Comment by fzumstein** [comment]
What version of xlwings are you using? Or consider upgrading to latest...

**Comment by hghaffari** [comment]
I am using: xlwings version 0.24.3.

**Comment by fzumstein** [comment]
Since `wb.sheets['sheet1'].range('a1').api.Comment.Delete()` fails, which is a direct pywin32 call, I'd recommend to upgrade pywin32 and then try again, but this looks like an issue with pywin32 (or even Excel)  and not xlwings, so I am closing this.
