### ISSUE TITLE
Python COM Server, hr = -2147221164 1000

### ISSUE THREAD

**Issue by meenmo** [xlwings/xlwings#1895]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings: 0.27.5
Excel: Microsoft Office Professional Plus 2013 (64-bit)
Python: 3.10.4

#### Describe your issue (incl. Traceback!)
Followed by #1774

- RunPython works fine
- Run main button works well
- However, once I click the Import Functions (UDF), it hangs around a minute, and then "Python COM Server, hr = -2147221164 1000" comes out.

**Comment by fzumstein** [comment]
Activate `Show Console` in the add-in and you should see an error in the Command Prompt that's popping up.

**Comment by meenmo** [comment]
The console shows that "xlwings server running, clsid={802EFF2B-1F05-4591-8426-B9E9C139AF58}, event loop on 29516". Then it hangs for a couple minute, and pops up the error same as #1554.

**Comment by fzumstein** [comment]
Can't really make sense of that. Double-check that you're not running a windows store version of Excel: In https://github.com/xlwings/xlwings/issues/1261
And try if you can run it in debug mode: https://docs.xlwings.org/en/stable/debugging.html#udf-debug-server

**Comment by meenmo** [comment]
This occurred due to the absence of Windows administrator permission. Solved anyway. Thank you :)

**Comment by waldenlei** [comment]
> This occurred due to the absence of Windows administrator permission. Solved anyway. Thank you :)

Hi meenmo, could you suggest how you resolve the Windows administrator permission issue? Same issue here. Thanks a lot!
