### ISSUE TITLE
xlwings read large number incorrectly from xlsx

### ISSUE THREAD

**Issue by HoffmanZheng** [xlwings/xlwings#1898]
#### xlwings read large number incorrectly from xlsx

![WechatIMG6129](https://user-images.githubusercontent.com/45369893/164492251-12ffb7db-5027-404b-b611-6dc6fa697d88.png)

Bug reproduction repo: https://github.com/HoffmanZheng/xlwings-large-number-bug

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import xlwings as xw
app1 = xw.App(spec='wpsoffice', visible=True, add_book=False)
xlsx_file = r'large-number-bug-reproduction.xlsx'
wb2_result = app1.books.open(xlsx_file, read_only=False)
sht0 = wb2_result.sheets[0]
large_number = sht0.cells(1, 1).options(numbers=int).value  # (rows, column)

print('read number from xlsx: ', large_number)
```
[large-number-bug-reproduction.xlsx](https://github.com/xlwings/xlwings/files/8532335/large-number-bug-reproduction.xlsx)

**Comment by fzumstein** [comment]
That's an interesting one! [Excel's precision for a specified number is confined to 15 significant figures](https://en.wikipedia.org/wiki/Numeric_precision_in_Microsoft_Excel) and your number arrives in Python as `9.22337203462931e+18`, which has the following floating point effects:

```
>>> 9.22337203462931e+18 == 9223372034629310000
False
>>> 9.22337203462931e+18 == 9223372034629310464
True
```

And this becomes visible when you turn Excel's float into an int.

See also: https://stackoverflow.com/questions/37604428/rounding-very-large-numbers-in-python-left-of-the-decimal
