### ISSUE TITLE
  WPS:   A new QWidget form has been added outside the XLDESK window

### ISSUE THREAD

**Issue by SlarkMeng** [xlwings/xlwings#1899]
hello,   I found that a new QWidget form has been added outside the XLDESK window on wps
Causes xlwings to not work properly under wps

**Comment by fzumstein** [comment]
Unfortunately, I don't have the resources to support WPS. Feel free to open a PR if you know how to fix the issue though.

**Comment by SlarkMeng** [comment]
thanks,  I find this problem on wps version 11.1.0.10314;
I fix it by modify  _xlwindows.py
def get_xl_app_from_hwnd(hwnd):
    pythoncom.CoInitialize()
    child_hwnd = win32gui.FindWindowEx(hwnd, 0, "XLDESK", None)
    **# wps新版本中间添加了个KMainDockArea窗体
    if not child_hwnd:
        child_hwnd = win32gui.FindWindowEx(hwnd, 0, None, "KMainDockArea")
        child_hwnd = win32gui.FindWindowEx(child_hwnd, 0, "XLDESK", None)**

    child_hwnd = win32gui.FindWindowEx(child_hwnd, 0, 'EXCEL7', None)

    ptr = accessible_object_from_window(child_hwnd)
    p = _PyCom_PyObjectFromIUnknown(ptr, byref(_IDISPATCH_GUID), True)
    disp = COMRetryObjectWrapper(Dispatch(p))
    return disp.Application


In the latest version, this QWidget form was deleted again, and now everything works fine

**Comment by SlarkMeng** [comment]
thanks,  I find this problem on wps version 11.1.0.10314;
I fix it by modify  _xlwindows.py
def get_xl_app_from_hwnd(hwnd):
    pythoncom.CoInitialize()
    child_hwnd = win32gui.FindWindowEx(hwnd, 0, "XLDESK", None)
    **# wps新版本中间添加了个KMainDockArea窗体
    if not child_hwnd:
        child_hwnd = win32gui.FindWindowEx(hwnd, 0, None, "KMainDockArea")
        child_hwnd = win32gui.FindWindowEx(child_hwnd, 0, "XLDESK", None)**

    child_hwnd = win32gui.FindWindowEx(child_hwnd, 0, 'EXCEL7', None)

    ptr = accessible_object_from_window(child_hwnd)
    p = _PyCom_PyObjectFromIUnknown(ptr, byref(_IDISPATCH_GUID), True)
    disp = COMRetryObjectWrapper(Dispatch(p))
    return disp.Application


In the latest version, this QWidget form was deleted again, and now everything works fine
