### ISSUE TITLE
Returning a dataframe as an excel table from a UDF 

### ISSUE THREAD

**Issue by vasilopoulos** [xlwings/xlwings#1904]
#### Describe your issue (incl. Traceback!)
Researched this extensively and could not find a way. Straightforward to return a dynamic array, but is it possible to return an excel table? Can do in a Macro but not via an excel function.
```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
Can you provide your macro code?

**Comment by vasilopoulos** [comment]
In a macro I can do:
```      
    for item in sheet.tables:
            if item.name == aname:
                item.update(df, index=False)
           else:
               sheet.range('F1').options(pd.DataFrame, index=False, expand='table').value = df
               sheet.tables.add(source=sheet['F1'].expand(), name=aname)
```
in a UDF something like that will give the following error

> pywintypes.com_error: (-2147352567,..

which I understand happens because UDFs can only return a value to their calling cell and not mutate cells directly.
It would be nice to be able to return a Table.

**Comment by fzumstein** [comment]
You could try to use the async decorator:

```python
@xw.func(async_mode="threading")
```

However, dynamic arrrays and tables don't work well together, so you'd need to look into solving that also.
