### ISSUE TITLE
Find String in Sheet

### ISSUE THREAD

**Issue by dr431** [xlwings/xlwings#1907]
#### Describe your issue (incl. Traceback!)
Is there a way to find a string on a worksheet and return the cell that it is in?

```python
# No traceback available

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
This used to work in an older version of xlwings:
Cell = wb.sheets[sheet].api.UsedRange.Find(ParameterName)

```

**Comment by fzumstein** [comment]
still works for me, what error/behavior do you see?

**Comment by dr431** [comment]
It just hangs. It gets to that statement and doesn't go any further that I can tell.

**Comment by fzumstein** [comment]
closing this as I can't replicate

**Comment by dr431** [comment]
ok, thanks for checking into it.
________________________________
