### ISSUE TITLE
NaN is returned as an empty string to excel, how can we make it empty cell, rather than empty string.

### ISSUE THREAD

**Issue by StephanSong** [xlwings/xlwings#1910]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Python 3.10
xlwings 0.27.3
#### Describe your issue (incl. Traceback!)

I create a simple UDF returning a data frame from python to excel.
The NaN value in the pandas dataframe is converted to empty strings. 

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
@xw.func 
@xw.ret(pd.DataFrame)
def simple_df():
    values = [[1,2,3],
              [4,5,6],
              [None,4,None]]
    df = pd.DataFrame(values,columns = list("ABC"))
    
    return df
```

When I run this function in excel, the excel function ISTEXT returns true for the empty cells.
![image](https://user-images.githubusercontent.com/44339006/166825600-e15af28c-d99b-4d45-9c6d-2865987bfbae.png)

If I run the below codes

xw.Range("I56").value = simple_df() from the python side.

the empty cells is not empty strings. 

![image](https://user-images.githubusercontent.com/44339006/166825884-ec341f96-150e-403d-8320-2485aee4ac29.png)

This really confuses me. Anyone can explain why and how I can fix it.

I want to have emtpy cells, but not empty text cells.

Thanks

**Comment by fzumstein** [comment]
Hi Stephan, UDFs can't actually return empty cells, see: https://stackoverflow.com/questions/27196512/returning-empty-from-user-defined-function-returns-actually-0

The default behavior of Excel is to return 0 instead of an empty string, so if that's what you prefer, you should replace the Nones with 0 in your DataFrame.

**Comment by StephanSong** [comment]
@fzumstein Got it. thank you very much. Stephan
