### ISSUE TITLE
Windows Defender flags xlwings.xlam as malware

### ISSUE THREAD

**Issue by wkschwartz** [xlwings/xlwings#1911]
Windows Defender claims that `xlwings\addin\xlwings.xlam`[^1] as installed from the 0.27.7 wheel is [`Trojan:Script/Sabsik.FL.B!ml`](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aScript%2fSabsik.FL.B!ml&threatid=2147780207). It says

> Category: Trojan
> Details: This program is dangerous and executes commands from an attacker.

This appears to have occurred during a passive system scan. Oddly, I have multiple instance of the file on my machine, and it flagged only one copy of it. Anyway, I'm just letting you know in case this false positive starts happening to more people more frequently. Maybe code signing (costly though it may be) the addin would prevent this?

[^1]: The relevant line from `xlwings-0.27.7.dist-info/RECORD` is `xlwings/addin/xlwings.xlam,sha256=GMpwROfOiLl47BXjPqNciw9-0GlAql1UN1V6jPRgp5o,262569`

### Environment

* **Windows** 11 Enterprise, Version 21H2, OS build 22000.613, Windows Feature Experience Pack 1000.22000.613.0
* **Windows Security** (Is this the same thing as Windows Defender?)
  * Antimalware Client Version: 4.18.2203.5
  * Engine Version: 1.1.19200.5
  * Antivirus Version: 1.363.1430.0
  * Antispyware Version: 1.363.1430.0

**Comment by fzumstein** [comment]
Hi William, thanks for logging, but this is really an on-and-off issue, see e.g.: https://github.com/xlwings/xlwings/issues/1250

* The only thing that seems to work is to submit it as a false positive
* dlls and add-in have been code signed since 0.27: https://docs.xlwings.org/en/stable/whatsnew.html#v0-27-0-and-v0-27-1-mar-8-2022

**Comment by leducvin** [comment]
This is occurring in 2024 too. It says it is [Trojan:O97M/MalDoc!MSR](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:O97M/Donoff!MSR)

14/64 security vendors flag this file as malicious:
https://www.virustotal.com/gui/file/43216efe13d44470c5a7cc44170784da13967ffbd886666bb8ed4b78a9f2b4c4/detection
