### ISSUE TITLE
when i use xlwings write in excel. the yyyy-mm-dd become yyyy/mm/dd, How do I set it up so it doesn't happen

### ISSUE THREAD

**Issue by chinaniu** [xlwings/xlwings#1922]
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by ericbmoreira** [comment]
Please post the code that is the issue. You might just need to format the cell in Excel first.

**Comment by fzumstein** [comment]
Yes, xlwings uses the date formatting of your Excel workbook. I.e, either change it in Excel or format the cells via e.g. `mysheet['A1'].number_format = "yyyy-mm-dd"`

**Comment by chinaniu** [comment]
Thank you very much.  so the dates in options is useless?
`sht['A1'].options(chunksize=10_000,index=False,dates=datetime.date).value = df
    `

**Comment by fzumstein** [comment]
it’s a read-only option
