### ISSUE TITLE
Issue with xlwings standalone: xlsm does not open (file corrupt)

### ISSUE THREAD

**Issue by LePlanteur** [xlwings/xlwings#1923]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings: 0.27.8
Excel: Office 365
Python: 3.9.12

#### Describe your issue (incl. Traceback!)
The problem I'm experiencing is connected to the standalone functionality:
`xlwings quickstart Tool --standalone`
creates the .xlsm and .py files as expected.
However, I'm not able to open the .xlsm file. It throws the error msg:
"Excel cannot open the file because the file format or file extension is not valid. Verify that the file has not ben corrupted and that the file extension matches the format of the file."

Any idea what the reason could be? Thanks a lot!

**Comment by fzumstein** [comment]
I've just tried it and couldn't replicate. Any chance that there's some antivirus playing games?

**Comment by LePlanteur** [comment]
Hm... might actually be the case - I'll check.
Thanks a lot for the hint!
