### ISSUE TITLE
Copy and paste formulas with reference to the current sheet when copying sheets

### ISSUE THREAD

**Issue by visakhr1998** [xlwings/xlwings#1927]
#### Describe your issue (incl. Traceback!)

Hi
I am using python with xlwings for automation tasks to consolidate worksheets. My goal is to extract data from several excel sheets into a single one and perform certain calculations. All the source and destination sheets have the same format and to replicate the format. The destination file is newly created once (unless there is some change in structure). For this, I copy one of the source file to get the formulas and formatting in the new destination file. Then, I would want to use the other sheets to do some calculations in the destination sheet with the formulas copied. But, the issue I face is, when I copy the original sheet to create a template, the formulas are being copied but the formulas refer to the destination of the original sheet itself and not the current excel file. 

Eg:
If the original sheet has the formula:

```python
AVERAGE(A5:A10)
```
When I copy it to the new sheet, in it the formula is:

```python
C:\\users\\source of original file\\[original file.xlsx]AVERAGE(A5:A10)
```

When Ideally it should be:

```python
[Destination file.xlsx]AVERAGE(A5:A10)

```

Is there any work around to this?
Because all the calculations in the destination file are to be done using these upon filling some columns

**Comment by fzumstein** [comment]
I think this is an Excel feature. Instead of using copy, try something like this

```python
book2.mysheet.myrange.value = book1.mysheet.myrange.formula
```

**Comment by visakhr1998** [comment]
But would this get only limited values as you specify the column or row in the range? My requirement is to reproduce all of the sheet in the same format, but the formulas should be of the present sheet and not the old one. With this, is there a way to select all the data?

**Comment by fzumstein** [comment]
you can use something like `cells` or `used_range` for `myrange`

**Comment by stenci** [comment]
You can avoid the reference to the original workbook by copying both the range with the formulas and the referred ranges in the same operation.

I think this is only possible if the two ranges are next to each other on the same sheet, or if you copy sets of sheets (both the ones with the formulas and the ones with the referred ranges) in the same copy operation.

When this is not possible you will need to do a text replace and remove the pathname from the formulas. This can be done automatically too, right after copying the cells.

Here I am talking about Excel, not xlwings, but I assume things don't change if done via xlwings.

**Comment by fzumstein** [comment]
closing this as these seem to be Excel issues.
