### ISSUE TITLE
FileNotFoundError with embedded code

### ISSUE THREAD

**Issue by fzumstein** [xlwings/xlwings#1931]
* Python code embedded
* Using both, UDFs and RunPython with "Use UDF Server" enabled

can lead to:

```
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c:\\users\\xxx\\appdata\\local\\temp\\xlwings-mg2hf3dl\\xxx.py'
```

**Comment by jjaredrides** [comment]
So this isn't fixed in the non-pro version? So I have 2 machines and I'm only getting this error on one of the machines I use. Any suggestions?
