### ISSUE TITLE
Could not activate Python COM server, hr=-2147221164 1000.

### ISSUE THREAD

**Issue by Nikolas10091503440** [xlwings/xlwings#1934]
@fzumstein 
With ref to the closed issue #1785 I have deleted the %TEMP%\gen_py folder and tried again but the problem still appears, with the same error

![image](https://user-images.githubusercontent.com/2265504/173385072-fb18bf5a-d389-4064-a0ae-8a3cbb2fc6b5.png)

**Comment by fzumstein** [comment]
is there a way for you try out this out with an ASCII username? Not sure if pywin32 may have an issue with that...

**Comment by Nikolas10091503440** [comment]
Thank you for your reply. I don't quite understand what's your proposal. Where should I use this username?

**Comment by fzumstein** [comment]
I am referring to the Windows username that seems to be using greek (?) letters

**Comment by Nikolas10091503440** [comment]
Yes the username uses Greek letters :) !!

**Comment by fzumstein** [comment]
This would have to be done in Windows, Google for how to add a new user.
