### ISSUE TITLE
How can I change color of a line in chart?

### ISSUE THREAD

**Issue by lizheng2112** [xlwings/xlwings#1936]
#### OS (e.g. Windows 10 or macOS Sierra)
windows10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Office 365,Python 3.6
#### Describe your issue (incl. Traceback!)
I got VBA code below, How can I change color of a line in chart?
```python
# Your traceback here
Sub 宏1()
    With Selection.Format.Line
        .Visible = msoTrue
        .ForeColor.ObjectThemeColor = msoThemeColorAccent6
        .ForeColor.TintAndShade = 0
        .ForeColor.Brightness = 0
        .Transparency = 0
    End With
End Sub
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
For Example， Now I can add data label by code below：
```python
# Your code here
chart.api[1].FullSeriesCollection(1).Select()
chart.api[1].SetElement(208)
```

**Comment by fzumstein** [comment]
This should work:

```python
import xlwings as xw
from xlwings.utils import rgb_to_int

sheet = xw.books.active.sheets.active
sheet.charts[0].api[1].SeriesCollection(1).Format.Line.ForeColor.RGB = rgb_to_int((22,22,22))

```
