### ISSUE TITLE
How to add class to funtion?

### ISSUE THREAD

**Issue by jingwez7** [xlwings/xlwings#1940]
#### OS  
Windows 10

#### Versions of xlwings, Excel and Python 
0.27.9, Office 365, Python 3.8
#### Describe your issue (incl. Traceback!)
I'm able to use functionName to call udf in excel, but how can I add different Classes to different functions? Too many funcitons can be distrupting to use, so I want to add a class layer

```python
import xlwings as xw

@xw.func
def hello(name):
    return f'hello, {name}'

```python
I can enter =test() in excel to execute，how to use t.test() to execute? Like functions call in Excel
```
![image](https://user-images.githubusercontent.com/70096109/174693726-1c426837-d24e-4cd6-98fc-6a241b5a9788.png)

**Comment by fzumstein** [comment]
That's not supported by xlwings. What you can do is to add a category `@xw.func(category="xlwings")`.
