### ISSUE TITLE
Necessity for 32bit Windows numpy/scipy binaries in future

### ISSUE THREAD

**Issue by carlkl** [xlwings/xlwings#1941]
This is not an issue, but a RFC especially for @fzumstein and users of xlwings.

_How important is the availability of the 32-bit numpy/scipy stack in future?_

I'm asking here, because MS Office is AFAIK often installed as 32-bit due to compatibility to old Addins. I know the default bitness during install is 64-bit now, but many companies seem to install 32-bit due to the aforementioned reasons. In this case  32-bit Python version is still mandantory for xlwings, right?

This questions is also discussed here [Releasing (or not) 32-bit Windows wheels](https://discuss.scientific-python.org/t/releasing-or-not-32-bit-windows-wheels/282) and here https://github.com/scipy/scipy/issues/16286.

Any feedback to this question would be helpful.

**Comment by fzumstein** [comment]
Hi Carl, no, this is not an issue with xlwings as it runs out-of-process: you can freely combine your Excel and Python bitness, so you could run a 32-bit version of Excel with a 64-bit version of Python.

**Comment by carlkl** [comment]
Hi @fzumstein, thank you for the clarification!
