### ISSUE TITLE
Excel file closes when I run xlwings addin run main

### ISSUE THREAD

**Issue by TahirMubeen** [xlwings/xlwings#1942]
[hello.xlsx](https://github.com/xlwings/xlwings/files/8976538/hello.xlsx)
#### Describe your issue (Excel closes automatically when i try to run python script through xlwings add  inn Run main. I have installed xlwings add in through anaconda prompt. anaconda version was 4.13.0. .Any help will be highly appreciated )

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# 
import xlwings as xw



def first_python():
    wb = xw.Book.caller()
    sheet = wb.sheets[0]
    sheet.range("A1").value = "Hello Python!" 

def main():
    wb = xw.Book.caller()
    sheet = wb.sheets[0]
    sheet.range("B5").value = "This is simple!"   

```

**Comment by TahirMubeen** [comment]
Thanks for help. Please elaborate it little bit. 

Xlwings worked through python/anaconda.

**Comment by fzumstein** [comment]
When you call Python via the xlwings Excel add-in, the VBA code does either a shell or dll call, which is a technique that's also often used by malicious VBA code. Sometimes, virus scanners just blindly block this/close Excel altogether.
