### ISSUE TITLE
How to write a pandas df using python xlwings with skip_blanks enabled?

### ISSUE THREAD

**Issue by Rom2BE** [xlwings/xlwings#1944]
My python script generates a pandas dataframe containing some NaN values: 

```
       A         B         C         D
0.351741  NaN       0.238705  NaN     
0.950817  0.665594  0.671151  NaN     
NaN       0.442725  0.658816  NaN     
0.155604  0.567044  NaN       0.666576
NaN       0.751562  NaN       0.597252
0.577770  NaN       NaN       0.123392
```

I want to write this df into an excel spreadsheet using xlwings. The important point is that I need to skip the cells set to NaN and preserve the corresponding excel cells. **In my case, the cells that I want to preserve contain live excel formula.**

If my excel values are: 
```
      A         B         C         D
Excel A1  Excel B1  Excel C1  Excel D1 
Excel A2  Excel B2  Excel C2  Excel D2 
Excel A3  Excel B3  Excel C3  Excel D3 
Excel A4  Excel B4  Excel C4  Excel D4
Excel A5  Excel B5  Excel C5  Excel D5
Excel A6  Excel B6  Excel C6  Excel D6
```
The final output should be:
```
       A         B         C         D
0.351741  Excel B1  0.238705  Excel D1
0.950817  0.665594  0.671151  Excel D2
Excel A3  0.442725  0.658816  Excel D3
0.155604  0.567044  Excel C4  0.666576
Excel A5  0.751562  Excel C5  0.597252
0.577770  Excel B6  Excel C6  0.123392
```

Usually, I write to Excel using a simple xlwings call:
```
sht.range(r).options(index=False, header=False).value = df
```
But this call would write a blank cell for the NaN values overwriting the excel values that I want to preserve.

I checked the documentation and the code. It seems that the parameter skip_blanks is only implemented for the function paste(). The only workaround that I currently found is to use a temporary sheet where I save my df. Then I copy to the clipboard the range where it was saved and I can finally paste it where I want using the skip_blanks parameter obtaining the expected output: 
``` 
tmp_sht.range(r).options(index=False, header=False).value = df 
tmp_sht.range(r).copy(destination=None)
sht.range(r).paste(paste='values', skip_blanks=True) 
```

I suppose xlwings should be able to handle a direct call using the `skip_blanks`, something that would look like this:
```
sht.range(r).options(index=False, header=False, skip_blanks=True).value = df
```

Is it possible to do it? 

Many thanks in advance!

I created a post on Stackoverflow too:
https://stackoverflow.com/questions/72785290/how-to-write-a-pandas-df-using-python-xlwings-with-skip-blanks-enabled?noredirect=1#comment128561732_72785290

**Comment by fzumstein** [comment]
You should be able to read in the formula property of the range:

```python
df = sht.range(r).options(pd.DataFrame).formula
```

Then you can replace the `NaN` with the formulas in df and write the whole DataFrame back as usual.
