### ISSUE TITLE
Question - Efficient Find and replace using Xlwings python

### ISSUE THREAD

**Issue by SSMK-wq** [xlwings/xlwings#1945]
#### Versions of xlwings, Excel and Python (e.g. 0.24,Excel 2019, Python 3.7)

I have an excel sheet like below

![image](https://user-images.githubusercontent.com/30723825/176633573-0b30de84-2929-4af2-b81a-e3565f51c6af.png)

I would like to do the below

a) a) Add 1 to all year values. ex: EVENT 2021 should be EVENT 2022

b) Similarly FY_1920 becomes FY_2021 and FY_2021 becomes FY_2122 AND FY_2122 becomes FY2223

c) After step a) and b), save the file.

But the problem is each excel file has 12 sheets and we need to do step a) and b) for all 12 sheets.

Since the file is strictly formatted, I would like to access these cells in excel wherever those strings appear and do the replacements in excel file directly

So, I tried the below xlwings approach

```
sheet.range("A1:ZZZ1045678").api.Replace("EVENT 2021", "EVENT 2022")
sheet.range("A1:ZZZ1045678").api.Replace("FY_1920", "FY_2021")
sheet.range("A1:ZZZ1045678").api.Replace("FY_2021", "FY_2122")
sheet.range("A1:ZZZ1045678").api.Replace("FY_2122", "FY_2223")
sheet.range("A1:ZZZ1045678").api.Replace("FY1920", "FY2021")
sheet.range("A1:ZZZ1045678").api.Replace("FY2021", "FY2122")
sheet.range("A1:ZZZ1045678").api.Replace("FY2122", "FY2223")
```

Is there any better way to find and replace strings in excel using xlwings?

I expect my output to be like as below

![image](https://user-images.githubusercontent.com/30723825/176635554-dba0b6c8-4719-4112-8ecd-0647431bb713.png)

**Comment by fzumstein** [comment]
The approach seems reasonable to me, except that you could use used_range:

```python
sheet.used_range.api.Replace(...)
```

**Comment by SSMK-wq** [comment]
@fzumstein - Cool. your suggestion works much better. but one minor issue. When I replace `FY_1920` with `FY_2021`, it works. But in the subsequent lines, I also want to replace `FY_2021` (from last year) with `FY_2122`. But what it does, it overwrites all the values of `FY_2021` with `FY_2122`. So, my output ends up being like below

![image](https://user-images.githubusercontent.com/30723825/177078411-dc64a2bb-9120-448a-9f63-8ba88bc789dc.png)

How can I let xlwings know that it shouldn't touch/replace the words from location which it already did? Unfortunately, we don't have any pattern with cell number/location. These values could be present anywhere in the file.
