### ISSUE TITLE
Display all sheet names using Xlwings in jupyter notebook

### ISSUE THREAD

**Issue by SSMK-wq** [xlwings/xlwings#1948]
#### Versions of xlwings, Excel and Python (e.g. 0.24, Excel 2019, Python 3.7)

I am reading a excel file with 16 sheets in it.

So, I am able to get the count of sheets in a excel file using xlwings but how can I get the name to be displayed like a list for all 16 sheets?

I tried the below (in jupyter notebook) but it doesn't work.

```
pd.options.display.max_columns = None
pd.options.display.max_rows = None
wks = workbook.sheets
wks.count
print(wks)
```

but this doesn't show all the names of 16 sheets that I have in my excel. It only shows first few rows as below (despite me setting pandas display options to show all rows and columns)

![image](https://user-images.githubusercontent.com/30723825/177094967-b3408237-a139-4a94-9fc7-6713cc7c2040.png)

Should I only do for loop like below?

```
for i in wks:
    print(wks[i])
```

**Comment by fzumstein** [comment]
What you're looking at is just the object representation. Yes, something like a for loop or list comprehension will work:

```python
[s.name for s in wks]
```
