### ISSUE TITLE
How to get/set the colour of the worksheet tab using xlwings in Python?

### ISSUE THREAD

**Issue by Rom2BE** [xlwings/xlwings#1954]
The following example comes from the [documentation][1] of `xlsxwriter`:

    import xlsxwriter
    
    workbook = xlsxwriter.Workbook('tab_colors.xlsx')
    
    # Set up some worksheets.
    worksheet1 = workbook.add_worksheet()
    worksheet2 = workbook.add_worksheet()
    worksheet3 = workbook.add_worksheet()
    worksheet4 = workbook.add_worksheet()
    
    # Set tab colors
    worksheet1.set_tab_color('red')
    worksheet2.set_tab_color('green')
    worksheet3.set_tab_color('#FF9900')  # Orange
    
    # worksheet4 will have the default color.
    
    workbook.close()

Is it possible to do the same in xlwings? I do not see anything in the code of the class Sheet related to colours.

  [1]: https://xlsxwriter.readthedocs.io/example_tab_colors.html

**Comment by Rom2BE** [comment]
Is there a way to access the sheet properties using the pywin32 api?

For example, I can access the name of the sheet like this:

    for sht in wb.sheets:
        print(wb.sheets[sht].name, "==", wb.sheets[sht].api.name)
        print(sht.name, "==", sht.api.name)
        # print(sht.api.tabColor)

**Comment by fzumstein** [comment]
Yes, you can use the following:

```python
import xlwings as xw
from xlwings.utils import rgb_to_int

book = xw.books.active

book.sheets[0].api.Tab.Color = rgb_to_int((50, 50, 50))
```

**Comment by Rom2BE** [comment]
Thank you very much @fzumstein !
I try it right now.

**Comment by Rom2BE** [comment]
Thank you @fzumstein, this was exactly what I was looking for:

```
import xlwings as xw
from xlwings.utils import rgb_to_int, int_to_rgb

# Define RGB codes
red = (252, 228, 214)

# Connect to the Excel file
wb = xw.Book(EXCEL_FILENAME)
sht = wb.sheets[EXCEL_SHEETNAME]

for sht in wb.sheets:
    print("Sheet name {}, Tab color int: {}, Tab color RGB: {}".format(sht.name, sht.api.Tab.Color, int_to_rgb(sht.api.Tab.Color)))

wb.sheets["Test"].api.Tab.Color = rgb_to_int(red)
```
