### ISSUE TITLE
COM error when executing macro from PERSONAL.XLSB when excel is loaded with xlwings

### ISSUE THREAD

**Issue by cartercanedy** [xlwings/xlwings#1957]
#### OS (e.g. Windows 10 or macOS Sierra)
win10 20H2

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Python: 3.10.4
xlwings: 0.27.7
xl: Office 365

#### Describe your issue (incl. Traceback!)

```python
com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Excel', "Sorry, we couldn't find C:\\Users\\..\\PERSONAL.XLSB. Is it possible it was moved, renamed or deleted?", 'xlmain11.chm', 0, -2146827284), None)
```
No tracebacks from python, exception gets thrown from a com error when trying to start a new instance of Excel with xlwings and then run a macro saved in PERSONAL.XLSB. If there's already a desktop-started instance, no issues and the macro runs fine. Similar issue was reported a while ago, just thought I should bump it since it's still open.

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
wb = xw.Book()
active = wb.sheets.active
active.range("A1").value = "good"
wb.app.macro("'PERSONAL.XLSB'!Platemap_setup_1536").run()
```

**Comment by cartercanedy** [comment]
I think I was able to get around it by using this snippet, still not able to get macro book to initialize when opening from python from closed app.

```python
if xw.apps.active is None:
    os.system('start excel.exe')
    while xw.apps.keys() == []:
        t.sleep(0.5)
    wb = xw.books.active
else:
    wb = xw.Book()
```

**Comment by fzumstein** [comment]
You need to refer to your workbook to get access to its macros:

```python
import xlwings as xw

wb = xw.Book("PERSONAL.xlsb")
mymacro = wb.macro("MyMacro")
mymacro()
```

The `PERSONAL.xlsb` is just a normal workbook that sits in the XLSTART folder and therefore gets opened automatically every time you open Excel manually.

However, that's not true when you open Excel programmatically, so in this case, you'll need to open the PERSONAL.xlsb file manually:

```python
import xlwings as xw
from pathlib import Path

wb = xw.Book()
personal = xw.Book(Path(wb.app.startup_path) / 'PERSONAL.xlsb')
mymacro = personal.macro("MyMacro")
mymacro()
```
