### ISSUE TITLE
Password protect at different levels

### ISSUE THREAD

**Issue by SSMK-wq** [xlwings/xlwings#1962]
Versions of xlwings, Excel and Python (e.g. 0.24,Excel 2019, Python 3.7)

I see that excel can be password protected at different levels such as below
```

Workbook 
Sheet
Cells
```

I managed to find xlwings approach  for the Sheet level

```
import xlwings as xw
from xlwings.constants import DeleteShiftDirection
sales = xw.Book('BC_IND.xlsx', corrupt_load=1)
ws = sales.sheets[0]
ws.api.Protect(Password='test')
```

This doesn't allow me to make any changes to rows/cells/columns etc.  I guess it is working fine.

But how can I apply password protection to the workbook?

`sales.api.SaveAs(r'C:\path\to\withpassword.xlsx', Password='password')`

When protecting worksheet prevents us from deleting data, what is the use of protecting workbook?

Is protecting the workbook same as protecting the file? Meaning, users will be prompted for password to open the file

**Comment by fzumstein** [comment]
> Is protecting the workbook same as protecting the file? Meaning, users will be prompted for password to open the file

Yes, and it's natively available:

```python
sales.save(r'C:\path\to\withpassword.xlsx', password='password')
```

see: https://docs.xlwings.org/en/stable/api.html#xlwings.Book.save
