### ISSUE TITLE
Network files cannot be read: FileNotFoundError

### ISSUE THREAD

**Issue by mucmch** [xlwings/xlwings#1967]
#### xlwings 0.27.11, python 3.9

Xlwings fails to read Excel files from a mounted network drive via SAMBA/CIFS. 
It will claim that the file is not found, even though it definitely exists.

The cause of this bug can be found in xlwings\main.py in l.817:
`` fullname = fullname.lower()``

If I comment this line out, everything works smoothly.

**Comment by fzumstein** [comment]
Can you please provide more details (following the template would have been a great idea)? Please provide an anonymized sample path and provide a minimal sample to replicate the issue (i don't even know if you run things from Python or from Excel).

**Comment by mucmch** [comment]
Sorry, thought that there would be no need for sample code:

``source_path = r'P:\A\B\C\D\2022\7\X Investable\BacktestResults_X Investable_B.xlsx'``
``import xlwings as xw  # NOQA``
``wb_src = xw.Book(source_path)``

**Comment by fzumstein** [comment]
Unfortunately, I can't replicate the issue, you'd have to provide a traceback.

**Comment by mucmch** [comment]
Before, it was also often returning a FileNotFound error. 
With last attempts, was an invalid handle error. 
When uncommenting the line mentioned above ``fullname = fullname.lower()``, it works smoothly

Traceback (most recent call last):
  File "C:\Users\X\.conda\envs\dev39\lib\ntpath.py", line 651, in realpath
    path = _getfinalpathname_nonstrict(path)
  File "C:\Users\X\.conda\envs\dev39\lib\ntpath.py", line 601, in _getfinalpathname_nonstrict
    path = _getfinalpathname(path)
OSError: [WinError 6] The handle is invalid: 'p:\\a\\b\\c\\d\\2022\\7\\x investable\\backtestresults_x investable_b.xlsx'

**Comment by fzumstein** [comment]
closing this in favor of #2052
