### ISSUE TITLE
Copy formatting only (ignore data) from source sheet to destination sheet

### ISSUE THREAD

**Issue by SSMK-wq** [xlwings/xlwings#1969]
Versions of xlwings, Excel and Python (e.g. 0.24,Excel 2019, Python 3.7)

I am trying to split my data based on `email_id` column using below code.

```
for k, v in data.groupby(['email_id']):
    dept_unique_ids = '_'.join(v['Dept_id'].astype(str).unique())
    dept_unique_names = '_'.join(v['dept_name'].unique())
    location_unique = '_'.join(v['location'].unique())
    filename = '_'.join([dept_unique_ids, dept_unique_names, location_unique])
    with pd.ExcelWriter(f"{filename}.xlsx", engine='xlsxwriter') as writer:
        v.to_excel(writer,columns=col_list,sheet_name=f'{k}',index=False, startrow=1)
```
While the above works fine and generates the file for each email_id, I would also like to keep the formatting of my source file.

My source file looks like below (don't worry about the data but if you look at the color of rows and column and filter in column headers is important).

![image](https://user-images.githubusercontent.com/30723825/182031345-f1c64fdb-e97d-44e3-b521-b130bf0638e2.png)

**I would like to port over this color of rows, columns and column filters etc to my split files.**

Is there anyway in xlwings where we can just copy/apply the formatting only from source sheet to destination sheet 

![image](https://user-images.githubusercontent.com/30723825/182031217-f519fdf6-3f43-42f8-9cc6-01602c200d9c.png)

**Comment by fzumstein** [comment]
Have you tried `copy()`/`paste()` the range with the paste(paste='format') argument?
See:
https://docs.xlwings.org/en/stable/api.html#xlwings.Range.copy and
https://docs.xlwings.org/en/stable/api.html#xlwings.Range.paste

**Comment by SSMK-wq** [comment]
Yes. This doesn't copy the table formatting. Should I only design table formatting (and cannot copy table formatting)?
