### ISSUE TITLE
com_error: (-2147417848, 'The object invoked has disconnected from its clients.', None, None)

### ISSUE THREAD

**Issue by SSMK-wq** [xlwings/xlwings#1971]
This issue is related to [386](https://github.com/xlwings/xlwings/issues/386)

Versions of windows, xlwings, Excel and Python (Windows 10, 0.24,Excel 2019, Python 3.7)

I am trying to do the below

a) Read the input file (which has 15 sheets) - Old_file.xlsx

b) Find and Replace the keyword "Old Name" with each item from the python list

c) I have a python list of new names. So, Save a new copy of the file with a pattern including {name}.xlsx`

So, I tried the below

```
for name in new_names_list:
    print(name)
    file_name = f"FY2022_AP_{name}_Excel_Worksheet_Oct_2022_1.0.xlsx"
    print(file_name)
    with xw.App(visible=False) as app:
        app.display_alerts = False
        workbook = xw.Book('Old_file.xlsx')  # reading input file
        wks = workbook.sheets  
        for sheet in wks:  # navigating to each sheet to make replacement
            sheet.used_range.api.Replace("Old Name", name)  
        workbook.save(file_name)
        wb = xw.Book(file_name)  # I open the saved output file to verify whether the search term is replaced in all sheets.
        wbs = wb.sheets
        try:
            for sheet in wbs:
                myCell = sheet.used_range.api.Find('Old Name')  # finding for search term (to verify)
                print('---------------')
                print(myCell.address)
        except:
            print("Search term - Old Name not found and code is correctly working")
        wb.close()  # here is the error
        workbook.close()

```
q1) Why is the closing the `wb` an issue? When I remove `wb.close()`, it works fine. 

q2) Does it mean wb is not opened at all?

q3) Does not closing `wb` create any problem?? 

q4) finally, I see that this issue was marked as a bug in 2016. does bug mean this issue is still open? Sorry, am not aware of SW terminologies.

But doing this results in error as below (showing partial error message)

```
  46320         def Close(self, SaveChanges=defaultNamedOptArg, Filename=defaultNamedOptArg, RouteWorkbook=defaultNamedOptArg):
> 46321 		return self._oleobj_.InvokeTypes(277, LCID, 1, (24, 0), ((12, 17), (12, 17), (12, 17)),SaveChanges
  46322 			, Filename, RouteWorkbook)
  46323 

com_error: (-2147417848, 'The object invoked has disconnected from its clients.', None, None)
```

**Comment by fzumstein** [comment]
When you save a workbook to a different path, Excel will make the open file the one with the new path, i.e., the previous workbook is not open anymore and therefore can't be closed.

**Comment by SSMK-wq** [comment]
@fzumstein - if you don't mind me asking, can help clarify your response a little bit. Sorry, I am unable to understand it

**Comment by fzumstein** [comment]
Try to replicate it manually in Excel: If you hit `Save As` and save your file as a different one, you still only have one file open, and not 2, so you can only close 1 file at the end.

**Comment by SSMK-wq** [comment]
Yes, but I have two different files and two different objects (workbook and wb)..
