### ISSUE TITLE
The add-in installer doesn't really install an add-in

### ISSUE THREAD

**Issue by stenci** [xlwings/xlwings#1973]
#### Versions
Windows 11 Pro
xlwings: 0.27.11
Excel (Microsoft 365): 2206
Python (Anaconda): 3.10.4

#### Description of the problem
According to the "ain't broke, don't fix it" philosophy this is not an issue and can be ignored.
According to the "it works, but it ain't right" philosophy this should be fixed.

---
The command `xlwings addin install` "[copies the add-in from Python’s installation directory to Excel’s XLSTART folder](https://docs.xlwings.org/en/stable/addin.html#installation)".

The result is that, yes, the add-in works, but it is not really installed.

Clicking on `File -> Options -> Add-ins -> Manage: Excel Add-ins -> Go...` shows the list of installed add-ins, and xlwings is not there.

Also, typing the following code in the VBA Immediate window lists all the installed add-ins, but xlwings is not listed:
```
For Each A In AddIns: Print A.Name: Next
```

---
A few years ago I created a little script that does uninstall older versions and install newer versions of my Excel add-ins by copying them to a folder and setting some registry values so the add-ins are actually considered add-ins.

I remember struggling a little to find the correct registry keys, because they change with the Excel version, but it has been working without problem through Win 7, 8, 10 and 11, and through several Excel versions.

If you think that this should be fixed, I can translate my old PowerShell script to Python and submit it.

The advantage would be that the add-in would be an add-in.
The disadvantage would be that the installation on some configurations/versions that I have not tested could break.

**Comment by fzumstein** [comment]
Hi @stenci, thanks for your input, but no, I won't consider a change for the following reasons:

* The current approach is an acceptable use of XLSTART: https://docs.microsoft.com/en-us/office/troubleshoot/excel/use-startup-folders
* It has proven to be more reliable than any other approach
* It's less intrusive (no messing up of registry etc)
* It's cross-platform, i.e, no special code for macOS

However, `xlwings addin install` is just there to make things easier for the 99% of us. You can always:
* Unzip the Python package
* Install the contained add-in under `xlwings/add-in/xlwings.xlam` the way you want:
    * manual through Excel's menu
    * via your scripts -- feel free to post your script to this issue so other can use it who have the same feeling about XLSTART)

**Comment by stenci** [comment]
Thank you for your reply (I was expecting something similar: "ain't broke, don't fix it").

Here is my old PowerShell code for reference (the only PowerShell I have ever written).

Excel used to be configured to install `Nesting.xlam` add-in located on network drives `N:` or `Y:`. That was a bad idea, At best slow startup, at worse it wouldn't work.

The script copies the new add-in to the `Microsoft\Addins` folder if it doesn't exist or if it's older, then looks for the existing registry keys and replaces the path of the old add-in with the same file name with the current path.

```powershell
function UpdateExcelAddIn([string]$AddinName) {
    # Update the xlam file and the registry keys
    $SourceName = "N:\Tools\$AddinName"
    $DestName = "$AppDataFolder\Microsoft\Addins\$AddinName"
    if(CopyIfNewer $SourceName $DestName) {
        $Versions = Get-ChildItem 'Registry::HKCU\Software\Microsoft\Office'
        foreach($Version in $Versions) {
            $ExcelOptions = Get-Item "Registry::$Version\Excel\Options" -ErrorAction SilentlyContinue
            if($ExcelOptions) {
                foreach($ValueName in 'OPEN', 'OPEN1', 'OPEN2', 'OPEN3', 'OPEN4', 'OPEN5', 'OPEN6', 'OPEN7', 'OPEN8', 'OPEN9') {
                    $Value = Get-ItemProperty "Registry::$ExcelOptions" $ValueName -ErrorAction SilentlyContinue
                    if($AddinName -eq 'Nesting.xlam') {
                        if(!$Value -or $Value.$ValueName -eq '"N:\Tools\Nesting.xla"' -or $Value.$ValueName -eq '"Y:\Estimating Tools\Nesting.xla"' -or $Value.$ValueName -eq '"Nesting.xla"') {
                            # Replace the old setup on the N drive to the new local file
                            Set-ItemProperty "Registry::$ExcelOptions" $ValueName "$AddinName"
                            break
                        }
                    }
                    if($Value.$ValueName -eq "$AddinName") {
                        # The addin is already installed
                        break
                    }
                }
            }
        }
    }
}

function CopyIfNewer([string]$SourcePathName,
                     [string]$DestPathName,
                     [bool]  $CreateDestFolderIfNotExisting) {
    # return $True if the file has been successfully copied, $False otherwise
    if(!(Test-Path $SourcePathName)) {
        [void](AddToLog "Impossible to copy the file $SourcePathName because it is missing")
        return $False
    }
    if(Test-Path $DestPathName) {
        $Source = Get-Item $SourcePathName
        $Dest   = Get-Item $DestPathName -Force
        if($Source.LastWriteTime -le $Dest.LastWriteTime) { return $False }
    }
    elseif($CreateDestFolderIfNotExisting) {
        $I = $DestPathName.LastIndexOf('\')
        $FolderName = $DestPathName.Substring(0, $I)
        if(!(Test-Path $FolderName)) {
            [void](AddToLog "Creating the folder $FolderName")
            try   { New-Item -Path $FolderName -ItemType directory | Out-Null }
            catch {
                [void](AddToLog "*** Error a: $($error[0].exception.message)" 'red')
                return $False
            }
        }
    }
    [void](AddToLog "Copying the file $SourcePathName to $DestPathName")
    try   { Copy-Item $SourcePathName $DestPathName -Force -ErrorAction Stop }
    catch {
        [void](AddToLog "*** Error b: $($error[0].exception.message)" 'red')
        return $False
    }
    return $True
}

UpdateExcelAddIn 'Nesting.xlam'
UpdateExcelAddIn 'Addin2.xlam'
UpdateExcelAddIn 'Addin3.xlam'
```

**Comment by CamiloMN** [comment]
Hi,
When I try to install I get the error.
>>> xlwings addin install
  File "<stdin>", line 1
    xlwings addin install
                ^^^^
SyntaxError: invalid syntax

Any clue why?  best regards, It seems so simple that I do not know how will not work.

**Comment by fzumstein** [comment]
You need to run this command on the command prompt/anaconda prompt, not within a Python REPL
