### ISSUE TITLE
Timedelta must be real number

### ISSUE THREAD

**Issue by akald** [xlwings/xlwings#1991]
I have a df where 1 column is a timedelta.

On the latest version of xlwings, on Windows 10, Python 3.8.10 when trying to view the df, I'm getting the error below. 

```
view(df)
timedelta must be real number
```

But if I do ```df.to_excel(...)``` Excel is capable of reading a timedelta as a float which I can then manually format within Excel.

**Comment by fzumstein** [comment]
I agree (unlike back then: https://github.com/xlwings/xlwings/issues/492) but I think the best default behavior would just be to write it out as string instead of converting it to seconds/hours/day
