### ISSUE TITLE
pivot_item.visible does not work 

### ISSUE THREAD

**Issue by tsusoft** [xlwings/xlwings#2000]
#### OS (e.g. Windows 10 or macOS Sierra)
MacOS 12.5.1
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Python 3.9.5
xlwings 0.27.10
Microsoft Excel for Mac v16.62
#### Describe your issue (incl. Traceback!)
I am trying to automate manual steps: 1) refresh pivot table, and 2) clear manual filter, and 3) reset manual to unselect several kind of pivot items, such as '/'. 
pvt = sh.api.pivot_tables['PivotTable4']
pvt.refresh_table(timeout=300)
pfd = pvt.pivot_fields['Memo']
pfd.clear_manual_filter()
pfd.pivot_items['/'].visible = False

I manually selected or unselected '/', before executing this code, and pfd.pivot_items['/'].visible() showed exact result True/False. But pfd.pivot_items['/'].visible = False seems doesn't work at all. 

I also tried pfd.pivot_items['/'].visible(False), pfd.pivot_items['/'].visible.set(False), or field.pivot_items['/'].__setattr__('visible', False), there was no response. However, the relevant 'get' version calls worked.   

Has anybody encountered this issue, or somebody knows how to hack it or finds a workaround? Appreciate it.
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
pvt = sh.api.pivot_tables['PivotTable4']
pvt.refresh_table(timeout=300)
pfd = pvt.pivot_fields['Memo']
pfd.clear_manual_filter()
pfd.pivot_items['/'].visible = False

```

**Comment by fzumstein** [comment]
try `pfd.pivot_items['/'].visible.set(False)`

**Comment by tsusoft** [comment]
I think I may know why I cannot get it. 

I tried "pfd.pivot_items['/'].visible.set(False)", it didn't work. It said 'Can't get reference.' Maybe I was lost during debugging and corrupted some variables.  

Now I reboot python interpreter, re-execute all codes one by one, and your code runs well.  @fzumstein, thank you so much! 

I made same mistake while using "pvt.manual_update": I used code "pvt.manual_update = True", it replaced directly the manual_update attribute to 'bool', no longer a Reference, thus I realized we'd better use setter/getter instead direct assignment when using 'xxx.api'.

BTW, before closing this issue, would you mind do me a favor to help a little bit more, @fzumstein?  I want to disable auto-refresh while set pivot_item visibility.

```
pvt.manual_update.set(True)
pfd = pvt.pivot_fields['Memo']
pfd.pivot_items['/'].visible = False
pfd.pivot_items[''].visible = False
pvt.manual_update.set(False) 
```

seems manual_update doesn't take effect. Any idea?

**Comment by fzumstein** [comment]
Nope, no idea, `pvt.manual_update.set(False)` seems reasonable. Somtimes, AppleScript has a bug and there's not much you can do about it except waiting for Microsoft to fix it. To be sure, you'd have to try it in the Scripts editor with AppleScript directly...

**Comment by tsusoft** [comment]
Not having too much experience in AppleScript. Anyhow, that solved my problem. I will close the issue. Thanks, @fzumstein
