### ISSUE TITLE
Add `xw.apps.cleanup()` to remove zombie processes

### ISSUE THREAD

**Issue by fzumstein** [xlwings/xlwings#2001]
```python
import xlwings as xw
from shlex import split
import subprocess

res = subprocess.run(
    split('tasklist /FI "IMAGENAME eq EXCEL.exe"'),
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    encoding="utf-8",
)

all_pids = set()
for line in res.stdout.splitlines()[3:]:
    # Automatically ignored if there's no processes as then it prints only 1 line
    _, pid, _, _, _, _ = line.split()
    all_pids.add(int(pid))

active_pids = {app.pid for app in xw.apps}
zombie_pids = all_pids - active_pids

for pid in zombie_pids:
    res = subprocess.run(
        split(f"taskkill /PID {pid} /F"),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        encoding="utf-8",
    )

```

**Comment by bravegag** [comment]
@fzumstein thanks a lot for this! I have couple of questions:
1. should we run this at the beginning or at the end?
2. will the 2x python xlwings processes per excel will also be killed by this?

Cheers from Schwyz

**Comment by fzumstein** [comment]
* It should probably run during initialization and via atexit handler. The first one to clean up zombie processes caused by a crash in a previous python process and the latter one to clean up during an ordinary shut down. I'll need to test if it's also a better solution for the App exit: https://github.com/xlwings/xlwings/blob/main/xlwings/main.py#L774
* Not sure what you mean by 2, but please open a separate issue for this one.
