### ISSUE TITLE
Sporadic 'NoneType' object has no attribute error

### ISSUE THREAD

**Issue by CollierKing** [xlwings/xlwings#2005]
#### OS (e.g. Windows 10 or macOS Sierra)

Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

xwlings-0.27.12
Python-3.8
Excel-Office365

#### Describe your issue (incl. Traceback!)

Thank you for the great work on this package, it is awesome!
I have a process that runs with xlwings.  
Each morning a batch script starts up and kills running Excel instances.
Python starts and xlwings Excel instance and opens a Workbook (line 23-24)
The Script waits for several hours and then begins to iteratively insert data into the Excel workbook, wait for formulas to calculate and save the workbooks before reading the sheet's values with pandas (lines 35-77)
This has been working except, from time to time the script fails on the section that writes the data into the Excel (lines 48-53)
The error thrown is either `'NoneType' object has no attribute 'Range'` or `'NoneType' object has no attribute 'Worksheet'`.
I have attempted to open the workbook again when this error is thrown (line 76).

Do you know what causes this error and if this is the best way to handle such issues?  
After I run `wbxl = xw.books.open(rf"{filepath + filename}")`, do the other xlwings Excels still exist at this point or are still running as zombies? 
Is there a way to make sure the excel is successfully recycled to continue the process without duplicate workbooks being opened by xlwings?

Also worth noting, the Excel workbook sits on **Google Drive**.  Not sure if that causes some issue?  Or is not recommended for repeated inserting/saving/reading?

Additionally, the last line that calls `wb.close()` throws this error.  Is this last line not recommended/needed since `xl.App` is called via context manager?

Thank you again! Looking forward to getting this to work for my use case.

```
wbxl.close()
ERROR:root:

ERROR:root:  File "C:\Python\lib\site-packages\xlwings\main.py", line 708, in __exit__

ERROR:root:    
ERROR:root:self.quit()
ERROR:root:

ERROR:root:  File "C:\Python\lib\site-packages\xlwings\main.py", line 373, in quit

ERROR:root:    
ERROR:root:return self.impl.quit()
ERROR:root:

ERROR:root:  File "C:\Python\lib\site-packages\xlwings\_xlwindows.py", line 586, in quit

ERROR:root:    
ERROR:root:self.xl.DisplayAlerts = False
ERROR:root:

ERROR:root:  File "C:\Python\lib\site-packages\xlwings\_xlwindows.py", line 143, in __setattr__

ERROR:root:    
ERROR:root:return setattr(self._inner, key, value)
ERROR:root:

ERROR:root:  File "C:\Python\lib\site-packages\win32com\client\__init__.py", line 595, in __setattr__

ERROR:root:    
ERROR:root:self._oleobj_.Invoke(*(args + (value,) + defArgs))
ERROR:root:

ERROR:root:pywintypes
ERROR:root:.
ERROR:root:com_error
ERROR:root:: 
ERROR:root:(-2146777998, 'OLE error 0x800ac472', None, None)
```

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
from datetime import datetime
import os
import sys
import time
import numpy as np
import pandas as pd
import xlwings as xw

print(f"XLWINGS VERSION: {xw.__version__}")

filepath = 'C:/Users/User/My Drive/Contents/'
filename = "WB1.xlsx"

df_all_tracking_exp = pd.DataFrame({
    ""
})

n = 40
splits = int(np.floor(len(df_all_tracking_exp.index) / n))
chunks = np.split(df_all_tracking_exp.iloc[:splits * n], splits)
chunks.append(df_all_tracking_exp.iloc[splits * n:])

with xw.App(visible=False) as app: 
    wbxl = xw.books.open(rf"{filepath + filename}")

    while datetime.now().hour < 7:
        print(f"Time is: {datetime.now()}......sleeping")
        time.sleep(600)

    print(f"Time is: {datetime.now()}...getting ready")
    time.sleep(1800)
    print("Starting loop...")
    loop_n = 0
    post_close_run = 0
    while datetime.now().hour <= 18 \
            and post_close_run == 0:
        print(f"Loop: {loop_n}")
        print(f"...Hour is {datetime.now().hour}....running")
        if datetime.now().hour >= 18:
            post_close_run = 1

        df_list = []
        start_time = datetime.now()
        err_cnt = 0
        for idx, chunk in enumerate(chunks):
            try:
                print(f"Pulling chunk {idx} of {len(chunks)}")
                (
                    wbxl.sheets['Sheet1']
                        .range("A3")
                        .options(chunksize=1_000, index=False, header=False)
                        .value
                ) = chunk['Components_list']

                time.sleep(7)
                wbxl.save()
                df = pd.read_excel(filepath + filename, sheet_name="Sheet1", header=1)

                # if not logged in
                while (df['Data'] == 0).all():
                    print("...waiting")
                    # input(login_script_prompt)
                    time.sleep(30)
                    wbxl.save()
                    df = pd.read_excel(filepath + filename, sheet_name="Sheet1", header=1)

                df_list.append(df)
            except Exception as e:
                print(str(e))
                err_cnt += 1
                print("Error count:", err_cnt)
                if err_cnt >= 10:
                    print("Reached error count on workbooks...exiting")
                    sys.exit
                print("Re-opening workbook")
                wbxl = xw.books.open(rf"{filepath + filename}")
                continue
    wbxl.save()
    wbxl.close()

```

**Comment by fzumstein** [comment]
Yes, you won't need to manually close the book, quitting the app will do that automatically.

**Comment by CollierKing** [comment]
Thanks @fzumstein ,
Do you have insight into what causes the `'NoneType' object has no attribute 'Worksheet'` error on lines 48-53?

Does that mean that the context for the Excel instance died?  The except logic I added towards the end `wbxl = xw.books.open(rf"{filepath + filename}")` re-opens the workbook in another Excel instance which then interferes with (steals focus) from other running workbooks, which is not desired. 

Was hoping to 1) address the `Nonetype` error and 2) keep any error handling within original Excel instance to isolate from other Excel processes.

**Comment by fzumstein** [comment]
it might be the issue that xlwings basically requires an excel instance to have always at least 1 workbook open: https://github.com/xlwings/xlwings/issues/444

**Comment by CollierKing** [comment]
Ended up just wrapping the `wbxl` method calls in a Try/Except block and seems to run okay on retry
