### ISSUE TITLE
Open method of Workbooks class failed Error

### ISSUE THREAD

**Issue by lakshyap98** [xlwings/xlwings#2006]
While reading excel file, I'm getting this error:
```
import xlwings

xlwings.App(visible=False)
book = xlwings.Book(excel_path)
print(print)
```

pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Office Excel', 'Open method of Workbooks class failed', 'C:\\Program Files (x86)\\Microsoft Office\\Office12\\1033\\XLMAIN11.CHM', 0, -2146827284), None)

**Comment by fzumstein** [comment]
This sounds like there could be something wrong with your installation of Excel/VBA, see e.g.: https://social.technet.microsoft.com/Forums/office/en-US/e7fecbcb-3283-4fc0-96e2-03e1d85a1fbe/quotopen-method-of-workbooks-class-failedquot-when-opening-excel-file-via-internet-explorer?forum=excel
