### ISSUE TITLE
Installed xlwings runpython on terminal but still can't run python script in excel

### ISSUE THREAD

**Issue by ardamoin** [xlwings/xlwings#2008]
#### Versions of xlwings, Excel and Python (0.27.14, Office 365, Python 3.10)

Hi everyone. I installed xlwings and ran the command 'xlwings runpython install' in my terminal. Terminal didn't give any issues about the installation of runpython. However, when I try to call a python script through VBA, I still get the message "To enable RunPython, please run 'xlwings runpython install' in a terminal once and try again.". 

```python
Option Explicit

Sub Loop1()
    Dim i As Long
    Dim wsData As Worksheet
    
    Set wsData = ThisWorkbook.Worksheets("Sheet1")
    
    For i = 1 To 10
        wsData.Cells(i, 1).Value = i * 10
    Next i
    
    Set wsData = Nothing
    
End Sub

Sub Call_Python_Function()
    RunPython ("import hello; hello.SayHello()")
End Sub
        

```
My python file is located in /usr/bin/python and xlwings is located in /Library/Frameworks/Python.framework/Versions/3.10/bin/xlwings. Anyone have a solution for this problem?

**Comment by fzumstein** [comment]
Does xlwings work if you run it from Python? You might get a better idea if you unlock the xlwings add-in in the VBA editor (password is `xlwings`) and see where it breaks exactly.

**Comment by ardamoin** [comment]
Xlwings works fine when I run it from python. When I try to run function from my macros I get the message "Compile error: Sub or Function not defined" and the debugger highlights the RunPython function in VBA. Nothing is highlighted in the xlwings module and looks like nothing is breaking there. I get the "To enable RunPython, please run 'xlwings runpython install' in a terminal once and try again." error when I try 'run main' from the add-in.

**Comment by fzumstein** [comment]
You might be missing a Reference to xlwings in the VBA editor under Tools > References? This should be automatically done if you start via quickstart command though.

**Comment by Hochiss** [comment]
@fzumstein I have same issue as OP. How to add Reference afterwards like this:?
<img width="420" alt="Screenshot 2024-01-10 at 19 28 43" src="https://github.com/xlwings/xlwings/assets/36304198/4a787aba-6bb9-4389-9252-6a0c323e965c">

**Comment by fzumstein** [comment]
On macOS, open the VBA editor via `Alt-F11`, then go to `Tools`> `References...` and add a reference to xlwings
