### ISSUE TITLE
Add or copy a worksheet from a UDF doesn't work

### ISSUE THREAD

**Issue by adriendelsalle** [xlwings/xlwings#2009]
#### OS (e.g. Windows 10 or macOS Sierra)
OS: Win10, build 19044.1889

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings: 0.27.14
Python: 3.9.13 hcf16a7b_0_cpython (conda-forge)
Excel: 2019 Version 2207 Build 16.0.15427.20166

#### Describe your issue (incl. Traceback!)
The `add` or `copy` functions are not working as espected when called from a `UDF`.

`add` silently fails returning some broken ref:
- the `name` is equal to the current worksheet one
- trying to set a cell/range will produce an error

`copy` produces the following error (due to `set` diff in the Python code):
```python
xlwings server running, clsid={19350F28-C7D5-4413-8857-725673BBD03E}, event loop on 14004
Imported functions from the following modules: test
pythoncom error: Python error invoking COM method.

Traceback (most recent call last):
  File "<umamba-env>\lib\site-packages\win32com\server\policy.py", line 303, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "<umamba-env>\lib\site-packages\win32com\server\policy.py", line 308, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "<umamba-env>\lib\site-packages\win32com\server\policy.py", line 637, in _invokeex_
    return func(*args)
  File "<umamba-env>\lib\site-packages\xlwings\server.py", line 230, in CallUDF
    res = call_udf(script, fname, args, this_workbook, FromVariant(caller))
  File "<umamba-env>\lib\site-packages\xlwings\udfs.py", line 547, in call_udf
    ret = func(*args)
  File "<umamba-env>\repertoire\test.py", line 6, in add_sheet
    xw.sheets.active.copy(name="test2")
  File "<umamba-env>\lib\site-packages\xlwings\main.py", line 1549, in copy
    new_sheet_name = sheet_names_after.difference(sheet_names_before).pop()
KeyError: 'pop from an empty set'
```

Is it something I missed about `UDF`?

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

Create a simple `UDF` named `test.py` alongside an Excel workbook named `test.xlsm` with the following definition:
```python
import xlwings as xw

@xw.func
def add_sheet():
    xw.sheets.add("test1")
    xw.sheets.active.copy(name="test2")


def add_sheet2():
    xw.sheets.add("test1")
    xw.sheets.active.copy(name="test2")
```

This macro works as expected:
```vba
Sub add_sheet_macro()
    RunPython "import test; test.add_sheet2()"
End Sub
```

but the `UDF` doesn't.

**Comment by adriendelsalle** [comment]
Looks like the call stack is somehow blocked during those ops.
Trying to understand what's going on I enabled async using `threading` mode:
```python
@xw.func(async_mode='threading')
def add_sheet(*args):
    try:
        return xw.sheets.add("test1").name
    except ValueError:
        return ""
```
and it works.

Still need to investigate what happens here

**Comment by fzumstein** [comment]
That's not supported by UDFs, see e.g., https://github.com/xlwings/xlwings/issues/1700

**Comment by adriendelsalle** [comment]
Thanks for the pointer @fzumstein !
