### ISSUE TITLE
display_alerts =False doesn't hide the pop-up automatically

### ISSUE THREAD

**Issue by SSMK-wq** [xlwings/xlwings#2011]
OS (Windows 10)

Versions of xlwings, Excel and Python (e.g. 0.11.8, Excel 2019, Python 3.7)

I am dealing with a strictly formatted input excel file. Unfortunately, couldn't share the file as it has lot of sheets with confidential info etc

When I use xlwings to read and do some data entry operations in the file, I get the below pop-up window despite setting App Alerts and visible = False. File is not opened or App is not lauched (which is expected) but pop-up shows up

```
with xw.App(visible=False) as app:
    app.display_alerts = False
    sales = xw.Book('format_test.xlsx', corrupt_load=1)
    sales.sheets[1].range("H10:H500").clear()
    if sales.sheets[1].api.AutoFilterMode == True:
       sales.sheets[1].api.AutoFilterMode = False

    for a_cell in sales.sheets[1].range("B10:B300"):
         for id in top20rows:
              if a_cell.value == id:
                   sales.sheets[1].range('H' + str(a_cell.row)).value = 'X'

```

![image](https://user-images.githubusercontent.com/30723825/189120117-792368a5-e8d1-4cf2-a454-34db43b11644.png)

How can I hide this pop-up automatically?

**Comment by fzumstein** [comment]
Does it change if you set `corrupt_load=0` ?

**Comment by SSMK-wq** [comment]
Oh yes. weird but it worked. I thought corrupt _load is required to be set to 1 because of formatting issues and repair etc. Any idea?

**Comment by fzumstein** [comment]
0 doesn't mean it's turned off but is the constant for `xlNormalLoad`:

https://github.com/xlwings/xlwings/blob/main/xlwings/constants.py#L1093-L1096
