### ISSUE TITLE
Insert text in between and at end of a cell

### ISSUE THREAD

**Issue by Ak784** [xlwings/xlwings#2012]
OS (Windows 10)

Versions of xlwings, Excel and Python (e.g. 0.11.8, Excel 2019, Python 3.7)

I have a data like as below (attached the file as well)

[sample_data_file.xlsx](https://github.com/xlwings/xlwings/files/9533056/sample_data_file.xlsx)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/SATHAP~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/SATHAP~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#1122CC" vlink="#1122CC">

Student | Sid | Marks | Color | Comments
-- | -- | -- | -- | --
ABC | 1 | 300 | 500 | He is a good student and has   scored lot of marks in 2nd term during     He also focuses on extracurricular activities
DEF | 2 | 400 | 600 | He is a good student and has   scored lot of marks in 2nd term during     He also focuses on extracurricular activities

</body>

</html>

I would like to add certain keywords to already existing text based on student id

So, I tried the below

```
wb = xw.Book("sample_data_file.xlsx")
ws = wb["input"]
for i in ws.range(A:A):
        s = ws.cell(E[i]).value
        if s == 'ABC': 
            ws.(i).value = s.replace("He is a good student and has scored lot of marks in 2nd term during","He is a good student and has scored lot of marks in 2nd term during Aug,2022. Needs improvement on Maths")
```

But this doesn't help with formatting. So, am not sure how to do this efficiently. 

I expect my output to be like as below

![image](https://user-images.githubusercontent.com/61312399/189292912-eb0ead13-8fd3-4209-86f4-e2f48e7d3924.png)

**Comment by fzumstein** [comment]
Looks like this has been solved on SO: https://stackoverflow.com/questions/73658422/xlwings-write-text-in-between-and-at-the-end-of-a-cell
