### ISSUE TITLE
Copy worksheet from another workbook - Exception occurred

### ISSUE THREAD

**Issue by SSMK-wq** [xlwings/xlwings#2014]
I have two excel files. Using xlwings version 0.27.2 and python 3.7 on windows os

I would like to do the below

a) Copy one worksheet from `source_file` and paste it in worksheet (wb2).

b) rename the pasted worksheet in wb2

Repeat the above steps for multiple files in the folder 

So, I tried the below

```
%%time
key = 'Only_Structure'
app = xw.App(visible=False)
Ref_file = xw.Book('source_file.xlsx',update_links=False)
ws1 = Ref_file.sheets(1)

files = glob.glob('FY2022_*.xlsx')
for old_filename in files:
    print(old_filename)
    wb2 = xw.Book(old_filename,update_links=False)
    ws1.api.Copy(After=wb2.sheets(12).api)
    if key in [sh.name for sh in wb2.sheets]:
        wb2.sheets[key].name = '9) Definition'
    wb2.save(old_filename)
    wb2.close()
app.quit()
```

This resulted in the below error but I don't know why there is key error when the file is already present in the folder.

> ---------------------------------------------------------------------------
> com_error                                 Traceback (most recent call last)
> ~\Anaconda3\lib\site-packages\xlwings\_xlwindows.py in __call__(self, name_or_index)
>     700         try:
> --> 701             return Book(xl=self.xl(name_or_index))
>     702         except pywintypes.com_error:
> 
> ~\Anaconda3\lib\site-packages\xlwings\_xlwindows.py in __call__(self, *args, **kwargs)
>     207             try:
> --> 208                 v = self._inner(*args, **kwargs)
>     209                 if isinstance(v, (CDispatch, CoClassBaseClass, DispatchBaseClass)):
> 
> C:\Users\test\AppData\Local\Temp\gen_py\3.9\00020813-0000-0000-C000-000000000046x0x1x9.py in __call__(self, Index)
>   41116         def __call__(self, Index=defaultNamedNotOptArg):
> > 41117 		ret = self._oleobj_.InvokeTypes(0, LCID, 2, (13, 0), ((12, 1),),Index
>   41118 			)
> 
> com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147352565), None)
> 
> During handling of the above exception, another exception occurred:
> 
> KeyError                                  Traceback (most recent call last)
> ~\Anaconda3\lib\site-packages\xlwings\main.py in open(self, fullname, update_links, read_only, format, password, write_res_password, ignore_read_only_recommended, origin, delimiter, editable, notify, converter, add_to_mru, local, corrupt_load, json)
>    4839         try:
> -> 4840             impl = self.impl(name)
>    4841             if not os.path.samefile(impl.fullname, fullname):
> 
> ~\Anaconda3\lib\site-packages\xlwings\_xlwindows.py in __call__(self, name_or_index)
>     702         except pywintypes.com_error:
> --> 703             raise KeyError(name_or_index)
>     704 
> 
> KeyError: 'FY2022_AP_vendor_Tesla_ltd.xlsx'
> 
> During handling of the above exception, another exception occurred:
> 
> com_error                                 Traceback (most recent call last)
> <timed exec> in <module>
> 
> ~\Anaconda3\lib\site-packages\xlwings\main.py in __init__(self, fullname, update_links, read_only, format, password, write_res_password, ignore_read_only_recommended, origin, delimiter, editable, notify, converter, add_to_mru, local, corrupt_load, impl, json)
>     830                     if not app:
>     831                         app = App(add_book=False)
> --> 832                     impl = app.books.open(
>     833                         fullname,
>     834                         update_links,
> 
> ~\Anaconda3\lib\site-packages\xlwings\main.py in open(self, fullname, update_links, read_only, format, password, write_res_password, ignore_read_only_recommended, origin, delimiter, editable, notify, converter, add_to_mru, local, corrupt_load, json)
>    4845                 )
>    4846         except KeyError:
> -> 4847             impl = self.impl.open(
>    4848                 fullname,
>    4849                 update_links,
> 
> ~\Anaconda3\lib\site-packages\xlwings\_xlwindows.py in open(self, fullname, update_links, read_only, format, password, write_res_password, ignore_read_only_recommended, origin, delimiter, editable, notify, converter, add_to_mru, local, corrupt_load)
>     733         # Workbooks.Open params are position only on pywin32
>     734         return Book(
> --> 735             xl=self.xl.Open(
>     736                 fullname,
>     737                 update_links,
> 
> ~\Anaconda3\lib\site-packages\xlwings\_xlwindows.py in __call__(self, *args, **kwargs)
>      92         while True:
>      93             try:
> ---> 94                 v = self.__method(*args, **kwargs)
>      95                 if isinstance(v, (CDispatch, CoClassBaseClass, DispatchBaseClass)):
>      96                     return COMRetryObjectWrapper(v)
> 
> C:\Users\test\AppData\Local\Temp\gen_py\3.9\00020813-0000-0000-C000-000000000046x0x1x9.py in Open(self, Filename, UpdateLinks, ReadOnly, Format, Password, WriteResPassword, IgnoreReadOnlyRecommended, Origin, Delimiter, Editable, Notify, Converter, AddToMru, Local, CorruptLoad)
>   40992                         , Editable=defaultNamedOptArg, Notify=defaultNamedOptArg, Converter=defaultNamedOptArg, AddToMru=defaultNamedOptArg, Local=defaultNamedOptArg
>   40993 			, CorruptLoad=defaultNamedOptArg):
> > 40994 		ret = self._oleobj_.InvokeTypes(1923, LCID, 1, (13, 0), ((8, 1), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17)),Filename
>   40995                         , UpdateLinks, ReadOnly, Format, Password, WriteResPassword
>   40996                         , IgnoreReadOnlyRecommended, Origin, Delimiter, Editable, Notify
> 
> com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Excel', 'Open method of Workbooks class failed', 'xlmain11.chm', 0, -2146827284), None)

**Comment by fzumstein** [comment]
copy is available natively, see: https://docs.xlwings.org/en/stable/api.html#xlwings.Sheet.copy
