### ISSUE TITLE
Run-Time error '5'  when import UDFs

### ISSUE THREAD

**Issue by Mountainheld** [xlwings/xlwings#2015]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 11 Pro 21H2 22000.918
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.24.9(from Anaconda), Office 365, Python 3.9
#### Describe your issue (incl. Traceback!)
I'm a new user to of xlwings. Run-Time error '5' occurred  when I import UDFs. I was just trying the sample func "double_sum". Same problem doesn't happen on another pc. Need help please ;) 
```python
# Your traceback here
Run-Time error '5'
Invalid procedure call or argument
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
conf setting is like following:
```python
# Your code here
"CONDA PATH",""
"CONDA ENV",""
"DEBUG UDFS",""
"USE UDF SERVER",""
"ONEDRIVE_WIN",""
"ONEDRIVE_MAC",""
"PYTHONPATH",""
"INTERPRETER_WIN","C:\ProgramData\Anaconda3\python.exe"
"UDF MODULES","run_xlwings"
"SHOW CONSOLE","True"
```

**Comment by fzumstein** [comment]
Since you have the Show Console Flag set to True: is there anything it prints there?

**Comment by Mountainheld** [comment]
It's a VB message

**Comment by fzumstein** [comment]
Right, but does the Terminal not open?

**Comment by Mountainheld** [comment]
No， it didn't open

**Comment by fzumstein** [comment]
Just noticed now that your config is off: if you're using Anaconda, you have to set the Conda settings, not the Interpreter_Win. Run `xlwings config create --force` from an Anaconda prompt, restart Excel and try again.

**Comment by Mountainheld** [comment]
It works. Thanks! But still don't know why the same config setting works on another pc (same using anaconda).

**Comment by fzumstein** [comment]
Older versions of conda were working with your configuration, so that may be a reason.
