### ISSUE TITLE
ONEDRIVE_COMMERCIAL_MAC is not picked up

### ISSUE THREAD

**Issue by dpwrussell** [xlwings/xlwings#2018]
#### OS (e.g. Windows 10 or macOS Sierra)
macOS Monterey 12.5.1

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.27.14
Python 3.10.6
Excel 16.64

#### Describe your issue (incl. Traceback!)

When using OneDrive (for business) the documentation (https://docs.xlwings.org/en/stable/onedrive_sharepoint.html#onedrive-for-business) says to set `ONEDRIVE_COMMERCIAL_MAC `, but I think the code is actually using a different environment variable.

```python
❯ ONEDRIVE_COMMERCIAL_MAC="$HOME/Documents/OneDrive - MyBusiness" python main.py
Traceback (most recent call last):
  File "/Users/dpwrussell/Code/project1code/main.py", line 13, in <module>
    wb = xw.Book(file_name)
  File "/Users/dpwrussell/Code/project1code/.venv/lib/python3.10/site-packages/xlwings/main.py", line 867, in __init__
    wb.fullname.lower() == fullname
  File "/Users/dpwrussell/Code/project1code/.venv/lib/python3.10/site-packages/xlwings/main.py", line 1118, in fullname
    return self.impl.fullname
  File "/Users/dpwrussell/Code/project1code/.venv/lib/python3.10/site-packages/xlwings/_xlmac.py", line 538, in fullname
    return fullname_url_to_local_path(
  File "/Users/dpwrussell/Code/project1code/.venv/lib/python3.10/site-packages/xlwings/utils.py", line 537, in fullname_url_to_local_path
    raise xlwings.XlwingsError(
xlwings.XlwingsError: Couldn't find the local OneDrive for Business folder. Please configure the ONEDRIVE_COMMERCIAL_MAC setting, see: xlwings.org/error.
```

https://github.com/xlwings/xlwings/blob/main/xlwings/utils.py#L531-L534 shows that to determine the root it either looks for an environment variable of `OneDriveCommercial` or `OneDrive`, not `ONEDRIVE_COMMERCIAL_MAC`.

If I trace back the third option (`onedrive_commercial_config`) back to where it's defined (https://github.com/xlwings/xlwings/blob/main/xlwings/utils.py#L490-L493) it does not get any environment variables, it's instead looking for user config in a directory with `read_user_config` or looking for sheet specific config.

If I change my environment variable when I call Python then the root gets picked up correctly.

```
❯ OneDriveCommercial="$HOME/Documents/OneDrive - MyBusiness" python main.py
```

I'm not sure if this is a documentation error or if there was an intention to use `ONEDRIVE_COMMERCIAL_MAC` in the code. `ONEDRIVE_COMMERCIAL_MAC` doesn't really seem to get used for anything except for something sheet specific in https://github.com/xlwings/xlwings/blob/main/xlwings/_xlmac.py#L540 which I don't think is applicable here.

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import xlwings as xw
wb = xw.Book('/Users/dpwrussell/Documents/OneDrive - MyBusiness/Project1/sheet.xlsx')
```

Call it with
```
ONEDRIVE_COMMERCIAL_MAC="$HOME/Documents/OneDrive - MyBusiness" python main.py
```

**Comment by fzumstein** [comment]
These are settings, not env vars: https://docs.xlwings.org/en/stable/addin.html#user-config-ribbon-config-file
