### ISSUE TITLE
xw.App(add_book=False).calculate() gets stuck while loading the workbook

### ISSUE THREAD

**Issue by GrumeiA** [xlwings/xlwings#2019]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.27.14
### First of all, thank you for the continuous work to improve this library.
Now, back to the issue:
In a certain application we need to update an excel file, and update the excel with the new calculated formulas.
For this we are using the command:  `xw.App(add_book=False).calculate()`
Unfortunately, we say that the command is stuck in infinite loop, and our application is also stuck because of this.

Possible solution:
Now, we also saw that if we add a short sleep time in main.py, class App, at line 286, we have a change to let the application to load the workbook and not have a stuck application:
```
 def __init__(self, visible=None, spec=None, add_book=True, impl=None):
        if impl is None:
            self.impl = engines.active.apps.add(
                spec=spec, add_book=add_book, visible=visible
            ).impl
            time.sleep(3)
            if visible or visible is None:
                self.visible = True
        else:
            self.impl = impl
            if visible:
                self.visible = True
        self._pid = self.pid
```
The 3 seconds indicated there is simbolic, but it could also work with 1 second, or you can wait until the workbook is loaded.

```python
# Your traceback here
No traceback, just stuck in infinite loop
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
Your command creates a new Excel instance...? Can you try if the following works?

```python
yourbook.app.calculate()
```

**Comment by GrumeiA** [comment]
Actually, this is the way that I was using xlwings:
```
test_spec_excel = xw.Book("my_excel.xlsx")
            LOGGER.info("Recalculate formulas and save test specification")
xw.App(add_book=False).calculate()
test_spec_excel.save()
del test_spec_excel
```
It is not me who wrote this code, but now if I am looking from backstage, yes, that sniped seems off..
because we open the workbook with test_spec_excel , then we are not doing anything with it.. we just save it as it is.
Many thanks for the headsup!!!

This is the new code, and it works.
`test_spec_excel = xw.Book(self.args['test_spec'])
            LOGGER.info("Recalculate formulas and save test specification")
            test_spec_excel.app.calculate()
            test_spec_excel.save()
            del test_spec_excel`


I can close the issue immediately, but I still have one question : 
If you try to create a new excel instance as I did by mistake, will you still have an infinite loop  ?
Can you please check that on your project ? This is just for my curiosity, as from engineer to engineer.

**Comment by fzumstein** [comment]
I am closing this issue then. No, I don't see a loop. I'd rather guess that `add_book=False` could be the issue (xlwings needs at least 1 book open to communicate with Excel).
