### ISSUE TITLE
Fibonacci standalone example

### ISSUE THREAD

**Issue by barrera2** [xlwings/xlwings#2031]
Which command should I execute to generate a standalone version like the fibonacci example?

**Comment by barrera2** [comment]
Can you be more specific?

As I saw here: https://docs.xlwings.org/en/stable/deployment.html I can use pyinstaller. 

But, as you can see here: https://stackoverflow.com/questions/59201142/why-are-pyinstaller-executable-files-using-xlwings-or-openpyxl-over-30x-larger-t it generates a gigantic set of files

I executed "pyinstaller fibonacci.py" over the fibonacci "lite" example and it generated a set of files that seems different from the files the follow the fibonacci standalone example

**Comment by fzumstein** [comment]
the generated sample exe is very old and for issues with PyInstaller, it's usually better to ask on their channels.
