### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'apps

### ISSUE THREAD

**Issue by Diarmaid005** [xlwings/xlwings#2032]
I keep getting this message after I type the code below.

Also want to note that I'm using **_windows_** and im coding on **_Jetbrains Datalore_**

> Traceback (most recent call last):
>   at block 11, line 7
>   at /opt/python/envs/default/lib/python3.8/site-packages/xlwings/main.pyline 279, in __init__(self, visible, spec, add_book, impl)
> **_AttributeError: 'NoneType' object has no attribute 'apps'_**

```python
import xlwings as xw

# Use dict for your sheet/df mapping
sheet_df_mapping = {"A": df, "B": df1,  "C": df2}

# Open Excel in background
with xw.App(visible=False) as app:
    wb = app.books.open("output.xlsx")

    # List of current worksheet names
    current_sheets = [sheet.name for sheet in wb.sheets]

    # Iterate over sheet/df mapping
    # If sheet already exist, overwrite current cotent. Else, add new sheet
    for sheet_name in sheet_df_mapping.keys():
        if sheet_name in current_sheets:
            wb.sheets(sheet_name).range("A1").value = sheet_df_mapping.get(sheet_name)
        else:
            new_sheet = wb.sheets.add(after=wb.sheets.count)
            new_sheet.range("A1").value = sheet_df_mapping.get(sheet_name)
            new_sheet.name = sheet_name

wb.save()
```

**Comment by fzumstein** [comment]
when you leave the app context manager, you're Excel application with all workbooks will be closed, so you'll need to call `wb.save()` inside the `with` statement.

**Comment by CopperClover** [comment]
I am experiencing the same issue:

```
Traceback (most recent call last):
  File "C:\Users\...\process.py", line 106, in CreateReports
    with xw.App(visible = False) as app:                                            # Create an app instance of Excel that runs in the background
  File "C:\Users\...\lib\site-packages\xlwings\main.py", line 291, in __init__
    self.impl = engines.active.apps.add(
AttributeError: 'NoneType' object has no attribute 'apps'
```

My `wb.save()` is inside the `with` statement.

**Comment by fzumstein** [comment]
@CopperClover looks like `engines.active` is `None`. Are you running this on Windows with Excel installed?

**Comment by CopperClover** [comment]
@fzumstein, it's running on a clients machine through a virtual assistant with RoboCorp. I will make sure that they do have Excel installed. Thank you!

**Comment by fzumstein** [comment]
As a heads up: on Linux (which I guess is what RoboCorp uses), right now only the following modes/engines are supported:

* xlwings Server: https://docs.xlwings.org/en/stable/remote_interpreter.html
* xlwings Reader: https://docs.xlwings.org/en/stable/reader.html

**Comment by mjstamper** [comment]
I have the 'engines.active is None' error on Windows with Excel 2016 installed.  Is there a way to set the Engine?

**Comment by NanoSkillCorner** [comment]
Hi everyone!

I'm getting the same error but only when running it within a streamlit app. The process works fine in my jupyter notebook but for some reason it fails in streamlit:

The goal is to open an excel template, write the _final_df_ dataframe in the sheet_name named "RawData" and save the updated version for a user to download

The code is the following:

with xw.App(visible=False) as app:
    wb = app.books.open(existing_file_path)
    sheet = wb.sheets[sheet_name]

    sheet.range('A1').options(index=False).value = final_df
    wb.save(new_file_path)

<img width="1008" alt="Screenshot 2024-02-06 at 11 03 20 PM" src="https://github.com/xlwings/xlwings/assets/125462579/bdd2385c-be4f-4785-aed8-3de5550c6603">

It's on the local machine so not sure how the error coming from the engine happens - i have a mac and excel installed and as said , it works on jupyter notebook!

Any help ? any past experience on xlwings with streamlit ? Open to all suggestions !

**Comment by fzumstein** [comment]
do you have `appscript` installed on the environment used by streamlit?

**Comment by NanoSkillCorner** [comment]
I do ! should I import it ?

**Comment by fzumstein** [comment]
No, but usually that would be the issue of the error message. Please open a new issue as this one has already been closed and supply a minimal reproducible code sample with streamlit.

**Comment by wwlinm** [comment]
> 我遇到了同样的问题：
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\...\process.py", line 106, in CreateReports
>     with xw.App(visible = False) as app:                                            # Create an app instance of Excel that runs in the background
>   File "C:\Users\...\lib\site-packages\xlwings\main.py", line 291, in __init__
>     self.impl = engines.active.apps.add(
> AttributeError: 'NoneType' object has no attribute 'apps'
> ```
> 
> My 在语句中。`wb.save()``with`

你怎么解决的
