### ISSUE TITLE
Unsupported operand type(s) for *: 'decimal.Decimal' and 'float'

### ISSUE THREAD

**Issue by Rapid1898-code** [xlwings/xlwings#2035]
Hello - i am reading several worksheets and do some calculations - 
Normally this works fine without problems - but now i provided the script to another person on only on that computer i get the error

```
Traceback (most recent call last):
  File "updMaster.py", line 153, in <module>
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
[9044] Failed to execute script 'updMaster' due to unhandled exception!
```

When i run the program with the exactly same excel - i get no error.
How can this happen?
Could this be some different settings in excel on this 2 computers?

**Comment by fzumstein** [comment]
Currency-formatted cells get read in as Decimals, I'd suspect something is happening there. Not sure why it would behave differently on different computers though.

**Comment by Rapid1898-code** [comment]
Thanks - i think the problem is the complicated formating-formula in the cell: 
_("$"* #.##0,00_);_("$"* (#.##0,00);_("$"* "-"??_);_(@_)
I think when i format this as normal number - everything will work fine.
