### ISSUE TITLE
UDF cell value doesn't update when recalculating

### ISSUE THREAD

**Issue by stfnx** [xlwings/xlwings#2040]
Windows 10
xlwings 0.28.0
Excel 2101 Build 13628.20380
Python 3.10.7

I have a UDF that creates a note on the calling cell or changes the text of the note if it already exists.
In both cases I return a value.

When I edit the cell, change the UDF's argument value and hit enter, the cell value and the note updates as expected. Perfect!

But when I initially open the workbook or recalculate it with `Ctrl+Alt+F9`, the cell value freezes to `#N/A waiting...` and doesn't update. If I change `text` in my code and recalculate again, I can see that the note doesn't update either. This happens only with `async_mode="threading"`.

When I remove `async_mode="threading"` from `@xw.func`, the recalculation updates both the cell value and the note as expected.

I have some other function that run perfectly fine with `async_mode="threading"`, but they just return a value and don't interact with the cell/caller itself.

```python
@xw.func(async_mode="threading")
def find_matches(query, caller):
    text = someOtherFunc(query)
    if caller.note:
        caller.note.text = text
    else:
        caller.api.AddComment(text)
    return query
```

**Comment by fzumstein** [comment]
This is basically a hack, so I am not really surprised that there are issues with it... but you could try to make the function volatile? https://docs.xlwings.org/en/stable/api.html#udf-decorators

**Comment by stfnx** [comment]
What parts of this do you consider a hack?
I will play around with volatile but I think its not really the solution I'm looking for.

I need to make heavy use of cell notes/comments.

**Comment by fzumstein** [comment]
Excel doesn't allow UDFs to change the environment: https://support.microsoft.com/en-us/topic/description-of-limitations-of-custom-functions-in-excel-f2f0ce5d-8ea5-6ce7-fddc-79d36192b7a1
so having a UDF interact with a note is a hack. The async_mode simply spawns a Python thread that then tries to use the automation interface to interact with the note so the UDF can return.

Another idea: activate Show Console and see if there's an error message.

**Comment by stfnx** [comment]
Okay if that is generally not supported, I guess I don't want to rely on it either, even if I somehow could manage to make it work. I tried to move the function to a ribbon button instead and it works perfectly. This is also okay for my use-case, even if it isn't so fancy as the UDF approach. ;)

The last lines of the traceback are:
```
self._oleobj_.InvokeTypes(dispid, 0, wFlags, retType, argTypes, *args),
pywintypes.com_error: (-2147418111, 'Aufruf wurde durch Aufgerufenen abgelehnt.', None, None)
async_thread failed
```

(Windows cmd sucks so hard that when I try to copy the whole traceback, it removes all newlines and I end up with a single line of unreadable crap. That's why I posted only the last lines.)

---

Another question. Not sure if its appropriate to ask here, so please tell me if I should open a separate issue next time:

Is it possible to further interact with the note/comment? Stuff like changing the font and most important: Changing size of the note popup so that it fits a whole line without wrapping.

From the docs I can tell that xlwings doesn't provide such functionality, but `api.AddComment(text)` isn't native xlwings either. Where can I find documentation of what that api provides? I couldn't find it.
