### ISSUE TITLE
Override custom addin settings

### ISSUE THREAD

**Issue by stfnx** [xlwings/xlwings#2045]
I have created a custom addin with XLWings. It is using the worksheet config inside the xlam file.
I don't get how I am supposed to overwrite this config.

My goal is to have the Interpreter and Pythonpath set inside the xlam file for distribution and override it locally for development.

In the docs it says it works similar to the normal xlwings plugin, but it doesn't work for me:
I tried to create:
- `.xlwings/myaddin.conf` in the user home directory. - didn't work.
- `myaddin.conf` next to the xlam file - didn't work.

It is still using the worksheet config inside the xlam file. And if I rename this worksheet, it fails completely because it can't find an interpreter.

PS: I don't want to override it per workbook.

**Comment by fzumstein** [comment]
Custom add-ins are completely whitelabled, i.e., it would look in `.myaddin/myaddin.conf`, looks like the docs need some clarification.

Also, the sheet config overrides the user config, not the other way around.

**Comment by stfnx** [comment]
Sad that it is the other way around, since the Excel plugin is what you ship to end users, so I think it sould include the "final" settings. And for development it is useful to be able to overwrite them.

But that's not a problem, I've just created two environment varibales to set INTERPRETER_WIN and PYTHONPATH. Works great and creation of them can easily be automated.
