### ISSUE TITLE
Reader: includes non-Worksheets (like chartsheets) in xw.sheets

### ISSUE THREAD

**Issue by fzumstein** [xlwings/xlwings#2058]
Only include worksheets to align with other engines

**Comment by fzumstein** [comment]
Fixed by https://github.com/xlwings/xlwings/commit/a1cef267d846f60121333bb4e4de4ed47e89b34e

**Comment by ganinop28** [comment]
How can I access ChartSheets?

**Comment by fzumstein** [comment]
This isn’t available natively. You’d have to use something like mybook.api.Sheets(“…”).
