### ISSUE TITLE
Sheet.select() does not replace current selected sheet object

### ISSUE THREAD

**Issue by nicholasjaeger** [xlwings/xlwings#2065]
``#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10 Enterprise 21H2
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.28.0, Office 365, Python 3.10.5 64 Bit

I made a workbook and added another sheet (default name Sheet2)

```
excel_app = xw.App(visible=False)
wb = excel_app.books.add()
ws1 = wb.sheets['Sheet1']
ws2 = wb.sheets.add(after='Sheet1')
```

After code execution and opening the .xlsx file, Sheet2 is what is shown by default. I tried `ws1.select()` but it didn't work. I was able to have Sheet1 shown as default by doing `ws1.api.Select(Replace = True)`. Maybe a future update of xlwings could include the optional Replace parameter in the select() function?

**Comment by fzumstein** [comment]
Aren't you looking for `ws1.activate()` instead?

**Comment by nicholasjaeger** [comment]
That works as well! Thank you!
