### ISSUE TITLE
xlwings 0.28.5

### ISSUE THREAD

**Issue by Caplande** [xlwings/xlwings#2080]
#### Describe your issue (incl. Traceback!)
In a UDF fonction is it possible to obtain info about caller cell.
xw.Book.caller gives the book name but what about the sheet and the cell from which the call is thrown ?

# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
See https://docs.xlwings.org/en/stable/udfs.html#the-caller-argument

**Comment by Caplande** [comment]
`=get_caller_address()` gives me, in Excel, address of the current cell.
My purpose is to obtain **in python** this address
Perhaps I misunderstood your answer?

**Comment by fzumstein** [comment]
You misunderstand the docs: `caller` will be a range object in python.

**Comment by Caplande** [comment]
Excuse me but I, still, don't understand.
Here below my package Python:

```
# my_script.py

import xlwings

@xw.func
def get_caller_address(caller):
    # caller will not be exposed in Excel, so use it like so:
    # =get_caller_address()
    return caller.address
	
@xw.func
def my_function_python():
	...
	zone = xw.Book.caller().sheets[0].range('A1:Z500')
	adresse = get_caller_address(zone)
	...
	return adresse

```	
# MY COMMENT:
#  1) I Prepare a range:
#        zone = xw.Book.caller().sheets[0].range('A1:Z500')
#  2) I put in sheet[0]['A1'] of book my_script.xlsm, formula: '=my_function_python(zone)'
#  3) My_function_python returns '$A$1:$Z$500' in cell A1. Not really info for me. I was waiting for the answer 'A1'

**Comment by Caplande** [comment]
Ok perfect!
Thank you for precious help... and your patience (I'm a beginner on Python)
