### ISSUE TITLE
Office.UserPermission

### ISSUE THREAD

**Issue by jgarciaf106** [xlwings/xlwings#2083]
Does xlwings provide an functionality to replicate the following vba snippet:

Sub set_access()
    Dim UserPerm As Office.UserPermission        
    Set UserPerm = ActiveWorkbook.Permission.Add("name@company", msoPermissionChange)
 End Sub

**Comment by fzumstein** [comment]
I am not familiar with this functionality, but you might want to try the following:

```python
import xlwings as xw

mybook = xw.books.active
mybook.api.Permission.Add("name@company", 15)
```

**Comment by jgarciaf106** [comment]
Working Perfectly Thanks.
