### ISSUE TITLE
XLWings keeps tripping our Anti-Virus (SentinelOne) no matter how many times we whitelist it.

### ISSUE THREAD

**Issue by puseyr** [xlwings/xlwings#2086]
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7): Excel 365, XLwings 0.24.9, Anaconda(Python) 3.7,3.9

Hey all, I have a user in my office that's trying to run the XLWings macro but since each file is a temp file and named something different the whitelisting doesn't work correctly. Is there a way to have XLwings not right to the system temp files but instead have it write to a directory the user defines? 

 SentinelOne
New Suspicious threat detected - machine UsersMachine
A suspicious activity was detected on machine: UsersMachine.
External IP address: X.X.X.X, internal IP address: Y.Y.Y.Y.
On Thu, 27 Oct 2022, 16:14:42 UTC.
name: 340F2FD1.xlsm

Any hints or tips would be greatly appreciated.
```

**Comment by fzumstein** [comment]
What command exactly is causing the write of the temp file? `340F2FD1.xlsm` doesn't look like something xlwings is doing.

**Comment by puseyr** [comment]
The user says it's coming from XLWings with the following info


```
def writeToExcel(weights_df, blend_df,
                 clear_sheet = True,
                 starting_cell = 'A1',
                 file_path = r'\\blendmodel.xlsm'):
    wb = xw.Book(file_path)
    sheet = wb.sheets['Optimisation']
    if clear_sheet:
        sheet.clear_contents()
    sheet.range(starting_cell).value = weights_df



   shift_cell = shiftChar(starting_cell[0], 3) + starting_cell[1]
    sheet.range(shift_cell).value = blend_df
    pass



def shiftDict(i):
    i = i % 26
    alpha = 'abcdefghijklmnopqrstuvwxyz'
    return dict(zip(alpha,alpha[i:] + alpha[:i]))



def shiftChar(letter, places):
    temp = shiftDict(places)
    return temp[letter.lower()].upper()

```

and then this is called within another function that is tied to a macro button in excel to a macro using @xw.func

**Comment by fzumstein** [comment]
Nothing I can see that would make sense given the message from SentinelOne. I'd suggest you take it up with them. Mind you, it's "normal" that AntiVirus flag xlwings tools, as the VBA code calls an external dll and/or makes a shell call, but not because of it producing a file in the temp folder.

The other option is that you enroll into a paid plan and I can take a more detailed look into this (I'd need to see the a full  app).

**Comment by puseyr** [comment]
> Mind you, it's "normal" that AntiVirus flag xlwings tools, as the VBA code calls an external dll and/or makes a shell call. 
That makes sense as it would see it as suspicious calling out to dll files that aren't exactly tied to it.

Understood, I'll check with SentinelOne on this and see how we can whitelist it permanently despite the changing file name. I shall let the user know if they want an in-depth analysis to go the paid model route and submit from there. Thank you again Felix for taking a look at this!

**Comment by fzumstein** [comment]
Closing this as third-party issue. As a heads up: the next release will start supporting the new-school web-based add-ins which will not require VBA and hence won't clash with Anti-Virus. They'll require a backend server though.
