### ISSUE TITLE
Z-Axis Label Cutoff During Figure Printing to Sheet

### ISSUE THREAD

**Issue by artsinli** [xlwings/xlwings#2087]
#### OS:
Windows 11

#### Versions 
0.28.5, Excel Version 2210 Build 15726.20174, Python 3.10 

#### Issue:  
Not sure why, but it seems xlwings cuts off part of the z-axis label when doing 3d plots, is this a known issue or is there something I'm missing? 

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
@xw.func
def plotBoilerData(fileName, series,caller):
    x = processBoilerData(fileName)[0]
    y = processBoilerData(fileName)[1]
    z = processBoilerData(fileName)[2]

    x1, y1, z1 = interpolateBoilerData(processBoilerData(fileName))

    fig = plt.figure(figsize=(8, 8))
    ax = plt.axes(projection='3d')
    ax.set_title(series + ' Efficiency Chart')
    ax.set_xlabel('Water Return Temperature [°F]')
    ax.set_ylabel('Firing Rate [%]')
    ax.set_zlabel('Boiler Efficiency [%]')
    surf = ax.plot_surface(x1, y1, z1, cmap=plt.cm.cividis)
    fig.colorbar(surf, shrink=.5, aspect=8, label='Boiler Efficiency Gradient', orientation='horizontal')
    ax.scatter3D(x, y, z, color='red', label='Input Data')

    plt.legend()
    plt.show()

    caller.sheet.pictures.add(fig, name='McLein Plot', update=True)

    return str(series) + ' PLOT'

```
![image](https://user-images.githubusercontent.com/30050694/199800216-04f7c6c5-723f-4d79-938a-7ef561db680f.png)

**Comment by fzumstein** [comment]
You can pass the `export_options` to `pictures.add()`, see https://docs.xlwings.org/en/stable/api.html#xlwings.main.Pictures.add

Which will be passed on to `image.savefig()` to produce the image, see: https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html
