### ISSUE TITLE
xlwings - UDF

### ISSUE THREAD

**Issue by Caplande** [xlwings/xlwings#2090]
OS (e.g. Windows 10)
Versions of xlwings, Excel and Python (e.g. 0.28.5, Office 2013, Python 3.10)

Case of xlwings UDF functions: 
Is it possible to associate Python and Excel by files that do not have the same name and not the same path :
**my_file.py in one directory and my_other_file.xlsm in another directory**

**Comment by fzumstein** [comment]
yes, use `PYTHONPATH` in combination with `UDF Modules`: https://docs.xlwings.org/en/stable/addin.html#user-settings

**Comment by Caplande** [comment]
Ok it works... really nice!
Thanks
