### ISSUE TITLE
api property case sensitive

### ISSUE THREAD

**Issue by hunter-xue** [xlwings/xlwings#2093]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 11 & MacOS 13
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings: 0.28.5, python 3.8.9
#### Describe your issue (incl. Traceback!)
```python
Exception has occurred: AttributeError
Unknown property, element or command: 'Sort'

The above exception was the direct cause of the following exception:

  File "/Users/rockcat/code/ksyun/demo_xlsx/start.py", line 26, in <module>
    xlsxBook.sheets["demo"].used_range.api.Sort(key1=sortCol.api, Header=2, Orientation=1)
```
"Sort" with initial upper case cannot work on MacOS, changed to "sort" then works well on MacOS but error on Windows. 
#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
xlsxBook.sheets["demo"].used_range.api.Sort(key1=sortCol.api, Header=2, Orientation=1)
```

**Comment by fzumstein** [comment]
`.api` is just a workaround and OS-specific, see: https://docs.xlwings.org/en/stable/missing_features.html
