### ISSUE TITLE
Issue running two xlwings processes at the same time

### ISSUE THREAD

**Issue by Lukeesec** [xlwings/xlwings#2096]
#### OS (e.g. Windows 10 or macOS Sierra)
GCP - windows-server-2022-dc-v20220624

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
pandas==1.4.3
xlwings==0.27.10
Newest version of Excel via Office 365
Python 3.10

#### Describe your issue (incl. Traceback!)
We are trying to run the "minimal code sample" concurrently. As example within JupyterLab we'd have two notebooks, and within a for loop we would rerun the "minimal code sample" a couple times (unique filenames) for each notebook. If we run the code within a single notebook we do not get errors, but if we run concurrently we get the error shown below.

We've also gotten an error saying that "The process cannot access the file because it is being used by another process". This one is harder to recreate and seems random.

This has been tested on a Windows desktop as well with identical versions.

It looks like xlwings or excel does not like having multiple processes running like this. But I am unable to find this written down anywhere.

```python
ERROR:write_output_data_excel_existing:114: Unable to open workbook: abc.xml
Traceback (most recent call last):
  File "C:\Users\Public\Documents\example\app\base.py", line 112, in write_output_data_excel_existing
    output_wb = xw.Book(filename)
  File "C:\Python310\lib\site-packages\xlwings\main.py", line 901, in __init__
    impl = app.books.open(
  File "C:\Python310\lib\site-packages\xlwings\main.py", line 503, in books
    return Books(impl=self.impl.books)
  File "C:\Python310\lib\site-packages\xlwings\_xlwindows.py", line 643, in books
    return Books(xl=self.xl.Workbooks, app=self)
  File "C:\Python310\lib\site-packages\xlwings\_xlwindows.py", line 536, in xl
    self._xl = get_xl_app_from_hwnd(self._hwnd)
  File "C:\Python310\lib\site-packages\xlwings\_xlwindows.py", line 311, in get_xl_app_from_hwnd
    return disp.Application
  File "C:\Python310\lib\site-packages\xlwings\_xlwindows.py", line 186, in __getattr__
    v = getattr(self._inner, item)
  File "C:\Python310\lib\site-packages\win32com\client\__init__.py", line 583, in __getattr__
    return self._ApplyTypes_(*args)
  File "C:\Python310\lib\site-packages\win32com\client\__init__.py", line 572, in _ApplyTypes_
    self._oleobj_.InvokeTypes(dispid, 0, wFlags, retType, argTypes, *args),
pywintypes.com_error: (-2146827864, 'OLE error 0x800a01a8', None, None)
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
try:
    output_wb = xw.Book(filename)
except com_error as e:
    logging.exception(f'Unable to open workbook: {filename}', exc_info=e)
    return None

try:
  # Processing of the data done here... But even without this code we get the same error but less consistant
except com_error as e:
    logging.exception(f'Unable to process workbook: {filename}', exc_info=e)
    return None

  try:
      output_wb.save()
      output_wb.app.quit()
  except com_error as e:
      logging.exception(f'Unable to save and quit workbook: {filename}', exc_info=e)
      return None
```

**Comment by fzumstein** [comment]
You'd probably want to work with independent Excel apps for each process:

```python
with xw.App() as app:
    output_wb = app.books.open(filename)
```

**Comment by Lukeesec** [comment]
Using separate Excel apps allows me to get over the error specified above. Code example to open a workbook
```python
pythoncom.CoInitialize()
app = xw.App()
output_wb = app.books.open(filename)
```

I am running into one more error which has been appearing randomly, but since I am over the previous error I see this error consistently. After we open the workbook, process the data, then save the workbook and quit the app we want to remove the saved workbook as it is no longer needed. `os.remove()` is used for this. Though when we try and remove the file we get the following error:
```
PermissionError(13, 'The process cannot access the file because it is being used by another process')
```

This doesn't make a ton of sense as everything should be closed unless some pice of code is not working

```python
try:
    pythoncom.CoInitialize()
    app = xw.App()
    output_wb = app.books.open(filename)
except com_error as e:
    logging.exception(f'Unable to open workbook: {filename}', exc_info=e)
    return None

try:
    print('example')
except com_error as e:
    logging.exception(f'Unable to process workbook: {filename}', exc_info=e)
    return None

if len(xw.apps) == 1:
    # save the remaining workbook into temporary folder
    try:
        output_wb.save()
        app.quit()
    except com_error as e:
        logging.exception(f'Unable to save and quit workbook: {filename}', exc_info=e)
        return

os.remove(filename)
```

**Comment by Lukeesec** [comment]
Ah! Removing `if len(xw.apps) == 1:` seemed to have fixed the problem. Will report back later
