### ISSUE TITLE
Support merged Cells

### ISSUE THREAD

**Issue by fzumstein** [xlwings/xlwings#21]

**Comment by Juanlu001** [comment]
Does xlwings support merged cells already? Just a follow-up in case this issue is outdated.

**Comment by fzumstein** [comment]
No, no efforts have been made yet on this topic...

**Comment by rcaravella** [comment]
I recently tried to merge cells using the workaround listed in the docs
 `sht.range('A1:A10').api.Merge = True`

My script seemed to get stuck in an infinite loop. I am not sure if I was doing something incorrectly in the code or if there was some underlying bug. I am happy to help on trying to get this feature added to xlwings but would need some guidance as I am new to open source contributions.

**Comment by Nicomedes89E** [comment]
Any news about this feature?

**Comment by fzumstein** [comment]
still didn't get to the top, no

**Comment by ltx1171135686** [comment]
sht.range('A1:A5').api.merge()

**Comment by ltx1171135686** [comment]
> I recently tried to merge cells using the workaround listed in the docs
> `sht.range('A1:A10').api.Merge = True`
> 
> My script seemed to get stuck in an infinite loop. I am not sure if I was doing something incorrectly in the code or if there was some underlying bug. I am happy to help on trying to get this feature added to xlwings but would need some guidance as I am new to open source contributions.

Zhè quèshí huì chūxiàn cuòwù. Nǐ kěyǐ chángshì yīxià xiàmiàn de dàimǎ.
22/5000
This does have an error. You can try the code below.
sht.range('A1:A5').api.merge()

Best of Luck

**Comment by fzumstein** [comment]
closed by #1257
