### ISSUE TITLE
Add a strikethrough

### ISSUE THREAD

**Issue by zeldalyc** [xlwings/xlwings#2106]
#### OS 
       Windows 11

#### Versions of xlwings, Excel and Python 
        (0.23.0, Office 365, Python 3.8.8)
#### Describe your issue (incl. Traceback!)
Hi 
I want to add a strikethrough in a range，but when I use the method accroding to 'Missing Features'，such as below，it don't work.
Does it have any method to add a trikethrough? 
Thanks!
`sheet.range('A1').api.strikethrough = True`

**Comment by fzumstein** [comment]
This might help: 
https://stackoverflow.com/questions/72095741/how-can-i-add-a-strikethrough-to-a-piece-of-text-using-xlwings-in-python

**Comment by zeldalyc** [comment]
> This might help: https://stackoverflow.com/questions/72095741/how-can-i-add-a-strikethrough-to-a-piece-of-text-using-xlwings-in-python

Thanks, it worked
