### ISSUE TITLE
xlwings could not find interpreter, Windows 11

### ISSUE THREAD

**Issue by n1kkqt** [xlwings/xlwings#2107]
Hello, I have been facing the 'could not find interpreter' issue when clicking a custom ribbon button. I tried following the instructions in "Troubleshooting" but they did not help. 
xlwings32-<version>.dll and xlwings64-<version>.dll are both in the same directory as my python.exe file. In the second section of Troubleshooting, it says "Check your Interpreter in the add-in or config sheet. If it is empty, then you need to be able to open a windows command prompt and type python to start an interactive Python session. ". I am able to run the python command from any conda environment but am still facing the issue.
Here is what I've already tried:

1. Reinstall xlwings in the conda environment I'm running it from. 
2. Try running xlwings from the base environment.
3. Change interpreter, PYTHONPATH, conda path, and conda env to different values or leave them empty
4. Remove OneDrive backup completely so none of the files are associated with it.

Nothing helps. Please help. I can still work on my project and compile it into an .exe every time I want to test it but that makes the debugging process really time-consuming and difficult.

**Comment by fzumstein** [comment]
The trouleshooting section is a bit outdated. Run this from an Anaconda Prompt with the correct conda env activated:

```
xlwings config create --force
```

**Comment by n1kkqt** [comment]
> The trouleshooting section is a bit outdated. Run this from an Anaconda Prompt with the correct conda env activated:
> 
> ```
> xlwings config create --force
> ```

Still getting the same issue. Both of the xlwings .dll files are in the right folder. The interpreter path, conda path, and conda env variables are specified. Tried checking and unchecking the "Add workbook to PYTHONPATH" flag. Tried removing the interpreter path, still getting the same issue. 
Noticed one problem. When I try to check the xlwings flag in the custom xlam file, it says "Name conflicts with existing module, project, or object library" even though I deleted the previous xlwings app I installed through an .exe file.

**Comment by fzumstein** [comment]
So is this a custom add-in? in this case, it will look for a configuration with your project name, not xlwings: https://docs.xlwings.org/en/stable/customaddin.html#configuration

**Comment by n1kkqt** [comment]
This is helpful. Finally fixed the interpreter issue. Now, it says "The macro may not be available in this workbook or all macros are disabled.".
The .xlam custom ribbon is in the trusted location (the xlstart folder) so it's not a security issue. 
Any thoughts on how I could fix that?

**Comment by fzumstein** [comment]
This doesn't sound like an xlwings-specific issue. Try to create a VBA-only add-in from scratch and see if that works or if it shows the same issues.
