### ISSUE TITLE
Imprt Error

### ISSUE THREAD

**Issue by SungO-Kim** [xlwings/xlwings#2108]
Import xlwings as xw

C: "ProgranDat aWAnaconda3"l iblsite-packages lxl w ingslprolembedded_ code. py in <module>
9 from . .main inport Book

11 LicenseHandler . val idate_l icense(pro")
12
13
C: WProgranDat alAnaconda3"l iblsite-packageslxl w indsbrolut i ls. py in val idate_l icense(product , lic
49
def val idate_l icense(product , license_type-None):
50
51
cipher -suite - LicenseHandler . get_cipher()
key = LicenseHandler . get_l i cense()
53
\ icense_info - json . loads( cipher _suite . decrypt (key.encode() ). decode())
C: WProgramDat aWAnaconda3Wl ibWsite- dackages"lxl wingstprowut i ls. py in get_l icense()
34
35
if os.path.exists(config_file):
36
with open(config_file, 'r') as f:
config - f.readl ines()
38
for line in config:

**UnicodeDecodeError:
C949" codec can ' t decode** byte 0x9b in position 0: i llegal mult ibyte seauence

**Comment by fzumstein** [comment]
Can you attach a sample Excel workbook and code? thanks

**Comment by fzumstein** [comment]
try to upgrade and see if you still get the same error.
