### ISSUE TITLE
wb.save but appear save as panel window and update links alert

### ISSUE THREAD

**Issue by lsps80544** [xlwings/xlwings#2110]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10 
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.24.9, Office 365, Python 3.8
#### Describe your issue (incl. Traceback!)
I am running some script 
I use ```wb.open(path, update_links = True)```
then doing some data extraction
When I use ```wb.save()```, Excel appear update link alert as I choose update
Then appear save as panel window

Now I use ```wb.open(path, update_links=3)```, the updatelink alert do not appear 
but the save as panel still there.

```wb.save(path)``` or ```wb.api.Save``` are not working too
 
Is this a user bug?  

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
import xlwings as xw
app = xw.App(visible=False, add_book=False)
app.display_alerts = False
app.screen_updating = False
src_workbook = app.books.open(path, update_links=3)
src_workbook.save()
app.quit()
```

Update: Another question is in the save as panel window the save file name will become a garbled. If I give another path to save as a new file, it gave me ```[WinError -2147467259] Unspecified error```

**Comment by fzumstein** [comment]
I can't replicate the issue... (update_links expects True/False). If you could attach Excel files to replicate would help.

**Comment by lsps80544** [comment]
> I can't replicate the issue... (update_links expects True/False). If you could attach Excel files to replicate would help.

Sorry, I can't attach my Excel files, but the file type is .xlsm. I also confuse why the update_links parameter is work. 
I only know that when I set True, system will give the updatelink alert before I save. That make me confuse.

I prefer to know why there is a save as panel window when I save the file. 

Thanks for your reply.

**Comment by lsps80544** [comment]
Update: I already found the issue. That happens when Excel save and replace file but somehow it failed. Then the temporary file will ask you to save as new file. But still dont know why the update_links parameter works.

**Comment by fzumstein** [comment]
closing this as unable to replicate
