### ISSUE TITLE
Trying to mass assign using multiple ranges

### ISSUE THREAD

**Issue by farinidan** [xlwings/xlwings#2111]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 11

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.28.5
python 3.11
Excel 2021 pro

#### Describe your issue (incl. Traceback!)
I'm trying to mass assign multiple ranges but when trying to use value I'm only getting the first range
I'm trying to mass assign instead of doing it one by one but it looks like I need to go range by range which takes me 4 seconds to assign 32 values.
Is it possible to mass assign multiple ranges?
I've seen https://stackoverflow.com/questions/46735285/xlwings-selecting-non-adjacent-columns example fir selecting multiple ranges which works but value doesn't return all the values 

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
range = "A10:A11,B14:B15"
sheet= wb.sheets['Sheet']
sheet.range(range ).value = [1,2,3,4]
Sets A10,A11,A12,A13
```

**Comment by fzumstein** [comment]
No, this isn't currently supported.
