### ISSUE TITLE
Question: Hide Details (ShowLevels)

### ISSUE THREAD

**Issue by PH-Tools** [xlwings/xlwings#2115]
#### Python (Python 3.7)

I wonder if there is a way to use a [`sheet.Outline`](https://learn.microsoft.com/en-us/office/vba/api/excel.worksheet.outline) [`ShowLevels`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.office.interop.excel.outline.showlevels?view=excel-pia#microsoft-office-interop-excel-outline-showlevels(system-object-system-object)) method using xlwings?

In VB I can use:
```VB
Sub Macro1()
    Worksheets("Sheet1").Outline.ShowLevels 1
End Sub
```
which works to collapse all the 'Groups' on a worksheet (similar to using the 'Data / Hide Detail' command from the ribbon).

I'd like to do something similar in xlwings (shrink/collapse all the Groups by default) - but I am not sure how? I tried:

```python
import xlwings as xw
sheet = xw.books.active.sheets[0]
print(sheet.api.outline)
```
but `sheet.api` does not appear to have `outline` (or `Outline`) and I get an:

```python
AttributeError: Unknown property, element or command: 'outline'
```

I *can* do:
```python
import xlwings as xw
sheet = xw.books.active.sheets[0]
sheet.show_level = 1

# There is also an 'outline_level'
sheet.outline_level = 1
```

but that doesn't seem to do anything to my worksheet?

Is there a way to access `sheet.outline` that I might use? Or is there another better method to collapse all the 'Groups' on a Worksheet?

**Comment by fzumstein** [comment]
Try this:

```
sheet.api.outline_object.show_levels(row_levels=1)

```

**Comment by PH-Tools** [comment]
Thank you @fzumstein  - that worked perfectly! 

Just for my own understanding: Is there some method I might use to introspect these objects myself to find the right property names in the future? 

Are these appscript methods documented someplace? Their [website](https://appscript.sourceforge.io/py-appscript/index.html) someplace?  

I have tried using my usual techniques (`vars()`, `dir()`, `help()`, etc...) on the objects, and looking through the Excel API online, but I don't quite know where I should be looking to figure these things out properly on my own (when it comes the `.api` methods and properties)?

regardless: thank you - that is just what I needed in this case.

**Comment by fzumstein** [comment]
See https://github.com/xlwings/xlwings/blob/main/DEVELOPER_GUIDE.md#macos
