### ISSUE TITLE
Data failed to update during repetitive computations

### ISSUE THREAD

**Issue by joycezhuang** [xlwings/xlwings#2116]
#### OS:
 Windows 10

#### Versions of xlwings, Excel and Python:
xlwings 0.27.12, Office 2019, Python 3.9

#### Issue
 
I'm using xlwings to repeatedly write data to excel and get VBA's calculation result back. I used For loop in python. However, two lines of the same results were sent back in sequence from time to time (The raw data used to calculate was different for sure). The total number of results sent back is in line with expectations.
Based on issue #654, I think the reason shouldn't be that xlwings got the result before the calculation was finished. Also, I used another thread to automatically close Excel pop-ups. I'm not sure if I should locate the issue on the usage of multiple threads.

```python
class MsgBoxListener(Thread):
    def __init__(self, title: str, interval: int):
        Thread.__init__(self)
        self._title = title
        self._interval = interval
        self._stop_event = Event()

    def stop(self):
        self._stop_event.set()

    @property
    def is_running(self):
        return not self._stop_event.is_set()

    def run(self):
        while self.is_running:
            try:
                time.sleep(self._interval)
                self._close_msgbox()
            except Exception as e:
                print(e, flush=True)

    def _close_msgbox(self):
        '''Close the default Excel MsgBox with title "Microsoft Excel".'''
        win = Application(backend="win32").connect(title=self._title)
        win.Dialog.Button.click()

def start_calc():
    for i in range(0, resource.shape[1]):
    data = list(resource.iloc[:, i])
    wb.sheets[0].range("A2").options(transpose=True).value = data
    wb.app.calculate()
    result = wb.sheets[0].range("A7").value
    ret_sheet.range("G" + str(i + 1)).value = result

listener = MsgBoxListener('Microsoft Excel', 3)
listener.start()
start_calc()
```

**Comment by fzumstein** [comment]
I don't know exactly what the issue is, but interacting with the GUI is certainly won't make things more stable. Why don't you handle the whole logic (including handing over the data) in a VBA macro if you're already calling one?
