### ISSUE TITLE
File not found as soon as module is imported ——No such file or directory

### ISSUE THREAD

**Issue by quenlowi** [xlwings/xlwings#2119]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.28.5 + Python 3.7.6

#### Describe your issue (incl. Traceback!)

File not found as soon as module is imported

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
```python
import xlwings as xw
app=xw.App(visible=True,add_book=False)
app.display_alerts=False
app.screen_updating=False
wb1=app.books.open(r'test.xlsx')
>>>FileNotFoundError: [Errno 2] No such file or directory: 'test.xlsx'
```
```python
import os
print(os.path.exists('test.xlsx'))
>>> True
```
```python
import os
import xlwings as xw
print(os.path.exists('test.xlsx'))
>>> False
```
```python
import os
print(os.path.exists('test.xlsx'))
import xlwings as xw
print(os.path.exists('test.xlsx'))
>>> True
>>> False
```

**Comment by quenlowi** [comment]
no special directory 
I've tried replacing it with the absolute path
r"D:\MY_CODE\dchan\test\test.xlsx"
This path looks normal without any rare characters

**Comment by fzumstein** [comment]
Closing this for same reason as #2120
