### ISSUE TITLE
unable to import UDF's via xlwings

### ISSUE THREAD

**Issue by GovindaDumaru** [xlwings/xlwings#2124]
Windows 10
Versions of xlwings, Excel and Python (e.g. 0.28.5, Office 365, Python 3.7)

hi, i'm unable to import the udf in excel. i save the excel file in .xlsm format with the same name for python script code and also in the same folder. I have enable Trust access to VBA Project object model and checked the xlwings on VBA editor>tools>References. Eventhough i am getting error as 
![ModuleNotFoundError](https://user-images.githubusercontent.com/120766908/208222495-af1ef873-19c1-40da-9647-0af3374b4b34.JPG)

here pm is my python file name as pm.py
my Your code is

import xlwings as xw

xw.func
def anyfunc(a, c, d):
    return a+c*d

When Debug UDFs is checked, the error is as
![error_after_checking_debug](https://user-images.githubusercontent.com/120766908/208224576-b06039e3-77ee-44fb-95a9-2f790ea0e76f.JPG)

Please help in this issue
Regards Govinda

```

**Comment by fzumstein** [comment]
Do you have `Add workbook to PYTHONPATH` activated? Also activate `Show Console` that may give more feedback. Finally, start with a quickstart command `xlwings quickstart pm` -- you shouldn't need to add the UDF module if it's called the same and in the same dir.

**Comment by GovindaDumaru** [comment]
thanks for the quick response. 
i have given PythonPath and it does not popup the "ModuleNotFoundError". However the python fuction (anyfunc) is not still callable (does not appear in the function list in excel). 
![PythonPath](https://user-images.githubusercontent.com/120766908/208251724-23246586-d66b-46e2-ae99-8536f8bd30ba.JPG)
 When Debug UDFs is checked, the error is as still as previous
![error_after_checking_debug](https://user-images.githubusercontent.com/120766908/208251671-cf0a2ee6-fbe3-432c-8819-59757ec83150.JPG)
i don't get you for the reason behind the starting with  quickstart command.   Previously all works correct without above mentioned issues.

**Comment by fzumstein** [comment]
If you want to activate the debug checkbox, follow the docs here: https://docs.xlwings.org/en/stable/debugging.html#udf-debug-server

**Comment by GovindaDumaru** [comment]
dear sir, my main issue is not calling the python function in excel via xlwings. but i do not understand where i am wrong. At first these problem does not happen to ma.

**Comment by fzumstein** [comment]
Start from scratch, from a command prompt/anaconda prompt run:

```
xlwings config create --force
```

Then start with a quickstart sample:

```
xlwings quickstart pm
```
