### ISSUE TITLE
How to catch exceptions in VBA thrown from Python when using RunPython?

### ISSUE THREAD

**Issue by bravegag** [xlwings/xlwings#2125]
I'm using `RunPython` because it is simpler to setup. I haven't had luck running UDF as described here https://docs.xlwings.org/en/stable/udfs.html, on VBA always says `Syntax error` on the unknown UDF python function.

So I do from Python:

```
def test():
    raise ValueError("test catching this")
```

then from VBA:
```
Sub Test()
   On Error Goto PythonError
   RunPython(“import module; module.test()”)
   Exit Sub
PythonEror:
   ‘Do something sensible 
End Sub
```

the Goto PythonError is bypassed and the exception is propagated all the way to Excel and shown to the user.

How can I get this to work? do we have to raise a specific xlwings exception for VBA to be able to catch it?

**Comment by fzumstein** [comment]
Python uses `raise` instead of `throw`

**Comment by bravegag** [comment]
@fzumstein thanks, the question still applies :)

**Comment by fzumstein** [comment]
Unhandled Python exceptions are automatically shown in Excel, yes. So instead of handling it in VBA, you should handle it in Python by wrapping your call in a try/except.

**Comment by bravegag** [comment]
Thanks @fzumstein but if I wanted to stay away from UDF, which are not straightforward to setup (at least following the documentation I have not been able to make it work), how can I communicate information between VBA and Python, when things go wrong, for example, if database is not accessible, I'd like VBA to know but I can't with RunPython.

**Comment by fzumstein** [comment]
Nothing refers to UDFs in my answer. RunPython should return `-1` in case of an error, but I think it's still showing the error pop-up.

But yes, what you're trying to do sounds more like a UDF. You can always open a separate issue with what exactly doesn't work.

**Comment by bravegag** [comment]
@fzumstein thanks, the issue is that:
1. The error / exception is not caught by the VBA `On Error Goto X`
2. The error is propagated to the user, that's the last thing we want, right?

So, 1 and 2 is what this is all about. I am happy with RunPython returning -1 on exception, that's fine. The problem is more like I can't handle it in VBA if this is propagated all the way out, bypassing the On Error Goto X idiomatic error handling in VBA.

**Comment by fzumstein** [comment]
I did some thinking and the suggested way for `RunPython` to get rid of the generic unhandled error screens is this:

```python
import xlwings as xw


def main():
    try:
        hello()
    except TypeError:
        # If you want to handle specific cases
        xw.Book.caller().app.alert("Oops, a TypeError happend!")
        # Or log it, send an email, whatever...
    except Exception as e:
        xw.Book.caller().app.alert(str(e))


def hello():
    raise ValueError("There was a value error")
```

I.e., handle the error before it gets to VBA.

The idea of xlwings is to minimize the amount of VBA as well as create a cross-platform/client solution. This solution will turn out the same whether you call it from classic VBA, VBA in connection with xlwings Server, Google Apps Script, Office Scripts or office.js, while any client-side handling would have to be re-implemented 5x.
