### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by mullimanko** [xlwings/xlwings#2133]
Hi,
there are typos in the docs (https://docs.xlwings.org/en/stable/api.html#xlwings.main.Tables.add): 

> table_style_name (str, default 'TableStyleMedium2') – Possible strings: `'TableStyleLightN''` (where N is 1-21), `'TableStyleMediumN'` (where N is 1-28), ‘TableStyleDarkN’` (where N is 1-11)

It should be 

> 'TableStyleLightN'

and

> 'TableStyleDarkN'

 with just one single quote at the end, both should be formatted as code to be consistent (currently 'TableStyleDarkN' is not formatted as code).

**Comment by fzumstein** [comment]
thanks!
