### ISSUE TITLE
`async_thread failed` with remote API calls

### ISSUE THREAD

**Issue by pandichef** [xlwings/xlwings#2134]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.28.6, Office 365, Python 3.11

#### Describe your issue (incl. Traceback!)
I have a python function uses the `requests` library to pull data from a remote server.  I call this function asynchronously from ~5 cells in Excel.  A few of the cells resolve with the correct data, but others get stuck at `#N/A Waiting`.  Meanwhile, I see the following traceback in the console.

```python
async_thread failed
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\xlwings\udfs.py", line 79, in async_thread
    await base.set_formula2(stashme)
  File "C:\Python311\Lib\site-packages\xlwings\udfs.py", line 340, in set_formula2
    await self._com(lambda rng: setattr(rng.impl, "formula2", f))
  File "C:\Python311\Lib\site-packages\xlwings\udfs.py", line 313, in _com
    return await loop.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\xlwings\udfs.py", line 340, in <lambda>
    await self._com(lambda rng: setattr(rng.impl, "formula2", f))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\xlwings\_xlwindows.py", line 1189, in formula2
    self.xl.Formula2 = value
    ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\win32com\client\__init__.py", line 595, in __setattr__
    self._oleobj_.Invoke(*(args + (value,) + defArgs))
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2146827284), None)
async_thread failed
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\xlwings\udfs.py", line 79, in async_thread
    await base.set_formula2(stashme)
  File "C:\Python311\Lib\site-packages\xlwings\udfs.py", line 340, in set_formula2
    await self._com(lambda rng: setattr(rng.impl, "formula2", f))
  File "C:\Python311\Lib\site-packages\xlwings\udfs.py", line 313, in _com
    return await loop.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\xlwings\udfs.py", line 340, in <lambda>
    await self._com(lambda rng: setattr(rng.impl, "formula2", f))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\xlwings\_xlwindows.py", line 1189, in formula2
    self.xl.Formula2 = value
    ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\win32com\client\__init__.py", line 595, in __setattr__
    self._oleobj_.Invoke(*(args + (value,) + defArgs))
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2146827284), None)
```

**Comment by fzumstein** [comment]
When you force recalculate `Ctrl-Alt-F9`, does it affect random cells? or always the same?

**Comment by pandichef** [comment]
Random cells

**Comment by fzumstein** [comment]
In that case it probably just isn't robust enough (which is why it's got the experimental warning in the docs).

**Comment by pandichef** [comment]
I see.  Could `async`/`await` be used to get around this somehow?  I think VBA natively supports async.  My sheet will take ~2-3 minutes to update if it's all synchronous.

**Comment by fzumstein** [comment]
Have a look at https://github.com/cunnane/xloil, this may fit your use case better and should support all that.

**Comment by pandichef** [comment]
Thanks.  Is there a similar resource out there for using a Google Sheet in the same way (or Excel on the web)?

**Comment by pandichef** [comment]
> 

I did some more tests.  The Python functions all run correctly and the results are in somewhere in Excel.  The issue is that the "#N/A Waiting" string doesn't resolve.  If I F2+Enter on the cell, the data appears immediately (without calling Python again).

**Comment by fzumstein** [comment]
> Thanks. Is there a similar resource out there for using a Google Sheet in the same way (or Excel on the web)?

Well, xlwings does support both Google Sheets and Excel on the web via xlwings Server:
https://docs.xlwings.org/en/stable/remote_interpreter.html

It currently only supports the ``RunPython`` call, but adding support for UDFs is planned.

Good you found an easy solution, closing this issue then.

**Comment by pandichef** [comment]
fwiw, I think UDFs via xlwings Server would be a game changer
