### ISSUE TITLE
Error exporting cmap formatted DF to Excel

### ISSUE THREAD

**Issue by russwongg** [xlwings/xlwings#2135]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Running on Jupyter Notebook

#### Describe your issue (incl. Traceback!)
Hi, I am having an issue pasting dataframes that is formatted via background_gradient through pandas into Excel.

An unformatted dataframe works perfect but formatted ones throw up an error.

```python
# Your traceback here
TypeError                                 Traceback (most recent call last)
TypeError: must be real number, not Styler

SystemError: <built-in method Invoke of PyIDispatch object at 0x0000013BAF0C11D8> returned a result with an error set
#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import pandas as pd
import xlwings as xw
import numpy as np

df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))
df

wb = xw.Book()

ws1 = wb.sheets['Sheet1']


ws1['B2'].options(index=False).value = df

# works well until here

df1 = df.style.background_gradient(axis = 1, cmap = 'RdYlGn')
df1
# error when pasting df1


Thank you.
```

**Comment by fzumstein** [comment]
Thanks for reporting! However, since there seems to be an easy fix (write it to Excel before applying the styler), probably not a high prio.

**Comment by russwongg** [comment]
Thank you. Dumb question... how do I apply the styler after writing the df to Excel? (Apologies I'm a beginner in Python and xlwings)

**Comment by fzumstein** [comment]
I guess you do it correctly in your example? Just assign df to the excel cell, then apply the style. Why do you need to assign df1 again to Excel? the numbers should be the same as in df?

**Comment by russwongg** [comment]
Oh. I do it this way in my example because i would like to have the colour maps for the df in Excel too. Otherwise, have to manually colour map via conditional formatting in Excel

**Comment by fzumstein** [comment]
DataFrame styles are for HTML, not for Excel, so yes, conditional formatting is your friend or using range.color.
