### ISSUE TITLE
#Vba criando função virgula

### ISSUE THREAD

**Issue by AtheusAlves** [xlwings/xlwings#2149]
####vba criando fórmula vírgula

Fala pessoal!

Estou tentando criar uma função, onde coloco " , " 
vírgula depois de cada número ou palavra.
Segue o script do vba:

"Public Function Virgula(Texto1, Texto2)
Virgula = Texto1 & "," & Texto2 & ","

função final"

Só consigo até dois, mas queria até 1000, se possível.
É algo que irá me ajudar nos Scripts do sql.

**Comment by fzumstein** [comment]
Closign this as this is for xlwings-related questions only, not VBA.
