### ISSUE TITLE
Unable to embed code using version 0.28.9

### ISSUE THREAD

**Issue by MansuraKhanom** [xlwings/xlwings#2150]
### Only the following commands were used. The embedded code was working with xlwings version 0.28.8, but not working anymore with version 0.28.9

```python
# pip install xlwings
# xlwings license update -k noncommercial
# xlwings quickstart myproject --addin --ribbon
# xlwings code embed

```
[myproject.zip](https://github.com/xlwings/xlwings/files/10485543/myproject.zip)
![Screenshot 2023-01-22 123332](https://user-images.githubusercontent.com/74274076/213936269-af892fee-2288-4b02-aed4-b6fca2c0be26.jpg)

**Comment by fzumstein** [comment]
Custom add-ins are white-labeled xlwings add-ins and will look for the configuration not in xlwings.conf (file/sheet) but in whatever your project name is set to in the VBA code, e.g., myaddin.conf. So you'll need to set the license key there.

**Comment by MansuraKhanom** [comment]
Thanks for the reply.
I am not sure where to look for `myproject.conf` file/sheet. I believe it is not created automatically with the `quickstart` command.
### I tried the followings, and unfortunately none worked -
1. ### I created a `myproject.conf` file in the same directory.
![image](https://user-images.githubusercontent.com/74274076/214195966-a5ce2622-4e14-4b1f-86f5-fbad5e610577.png)
![image](https://user-images.githubusercontent.com/74274076/214196041-8d3f55e3-fca5-4baf-a0aa-407b04d67527.png)

2. ### I created a `myproject.conf` sheet.
![image](https://user-images.githubusercontent.com/74274076/214196176-5ee18730-2618-4b67-8e9d-d6819274003f.png)

3. ### I renamed the `xlwings.conf` sheet to `myproject.conf` and added the `LICENSE_KEY` there, just to try.
4. ### I changed the mapping from `{"auto_generated_random_number.py": "myproject.py"}` to `{"myproject.py": "myproject.py"}`, just to try.
5. ### I looked into `Developer > Visual Basic` to see if I could find anything related to `myproject.conf`. Couldn't find anything.
6. ### I also repeated the steps `1-3` with the `LICENSE_KEY` value as a string ("noncommercial").

# NOTE:
## with version 0.28.8 & noncommercial XWpro, I simply used `xlwings code embed` command, and it worked instantly using the embedded code from `auto_generated_random_number.py` sheet, and `xlwings.conf` sheet was also automatically added to do the file mapping.

### I am attaching my project files (xlam, xlsm, py) again for your review.
## [myproject.zip](https://github.com/xlwings/xlwings/files/10485906/myproject.zip)


# Thanks!

**Comment by fzumstein** [comment]
The default project name is `myaddin`, see at top of the VBA xlwings module. Use `myaddin.conf` instead of `myproject.conf` and it will work.

**Comment by MansuraKhanom** [comment]
Thanks, it worked.
