### ISSUE TITLE
range.value picks up formulas that evaluate to an empty string

### ISSUE THREAD

**Issue by Matt-Greer** [xlwings/xlwings#2152]
#### Operating System

- Windows 10 Pro

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

- xlwings version 0.27.11
- Office 365
- Python 3.9.15

#### Describe your issue (incl. Traceback!)
There's no error.  What's happening is I'm asking xlwings to pick up the values from a table, starting with a Named Range in Excel and expanding.  It extends out and includes a cell that has a formula in it which results in "", which is blank, or empty, no?

The named range 'Table2' references cell L5.  There's a formula in cell S5 that I would hope would be ignored by xlwings as the result of the formula is "".

I understand that if I was to enter the formula '=ISBLANK(S5)' the result would be 'FALSE'.  So if an empty string is considered a value, is it possible to use a formula in Excel that results in a blank cell?

At the moment the only workaround I can think of is to start at the end of the table and look for 'None' and work my way backwards, dropping columns.

The reason I'm doing this is I'm comparing the shape of two tables.  Table2 needs to match the shape of Table1.

Code sample:
```python
import xlwings as xw

wb: xw.Book = xw.books.active

myTbl: list = xw.Range('Table2').expand('table').value

# The column after 'Col7' shows a 'None' value in the list:
print(tbl_temps)
```
[Range Copies Formulas.xlsx](https://github.com/xlwings/xlwings/files/10538415/Range.Copies.Formulas.xlsx)

**Comment by fzumstein** [comment]
`expand` corresponds to the `Shift-Ctrl-Down-Right` key combination, which explains the behavior. I don't know enough about your use case, but checking the values in Python after reading in an expanded range may also give you the option to drop rows/cols that have empty values but non-empty formulas.

**Comment by Matt-Greer** [comment]
That's pretty much it.  Have to check the columns once I get the range values in python.  I came up with this, if you have any suggestions on how to improve it I'm all ears:

```py
    while df.columns[-1] == None and len(df.columns) > 0:
        df.drop(columns=[None], axis=1, inplace=True)
```

**Comment by fzumstein** [comment]
This is then a pandas-related question rather than xlwings, so I'll close this. But yes, you probably don't have to loop in pandas, but can just use the drop method directly.
