### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Jeroendevr** [xlwings/xlwings#2159]
#### Versions of xlwings, Excel and Python
xlwings - 0.27.15
Office 365 
Python 3.10.8
miniconda - conda 23.1.0

#### Quickstart Error after running main
```bash
---------------------------
Error
---------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'debugmodule'

Press Ctrl+C to copy this message to the clipboard.
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
- On a fresh windows 11 machine install miniconda, install xlwings
- in Anaconda prompt
```xlwings install addin```

    Resulting Conda Path is `C:\Users\hayer\miniconda3\condabin\..`
    Resulting Conda Env is `base`

- create quickstart `xlwings quickstart debugmodule`
- Run main from xlwings add-in

#### Performed checks
- [x] xlwings [reference](https://docs.xlwings.org/en/latest/addin.html#installation) is checked 
- [x] tried to change Conda Path to `C:\Users\Username\Miniconda3`
- [x] uncheck add workbook to PYTHONPATH

#### Comments
I developed a program on macOS (Ventura 13.1) and tried to copy it to a Windows 11 on Arm VM. It was resulting in this module not found error. So I decided to do a fresh install and only make use of the quickstart. 

When trying to create an new enviroment using
```conda -n quickstartdebug```
There is a warning about `pywin32` could that be a lead?
```
Preparing transaction: done
Verifying transaction: -
SafetyError: The package for pywin32 located at C:\Users\hayer\miniconda3\pkgs\pywin32-305-py310h2bbff1b_0
appears to be corrupted. The path 'Lib/site-packages/win32com/gen_py/dicts.dat'
has an incorrect size.
  reported size: 10 bytes
  actual size: 32405 bytes
```

#### Subsequent steps taken for later reference without further progress
- [x] ~Update Windows 11~
- [x] ~Renamed the `_xlwings.conf` sheet to `xlwings.conf` to use those settings~
- [x] ~Deleted the `xlwings.conf` sheet~
- [x] ~Performed conda update `conda update conda`~
- [x] ~Trust access to the VBA project model~
- [x] ~Install WSL~

### Workaround 
My guess is that some modules or the python language itself is not yet suitable for Windows on Arm. So I installed the [Python 3.11.1 Arm installer](https://www.python.org/downloads/release/python-3111/) which is considered experimental. 
- create a venv directory within the project `quickstartmodule`
- Activate it (Perhaps need to set execution policy to use scripts `set-executionpolicy RemoteSigned`)
- `pip install xlwings`
- add the path to `pythonw.exe`(from the newly installed python) as interpreter within xlwings excel add-in
- set pythonpath to project folder `C:\Users\Username\debugmodule`

**Comment by fzumstein** [comment]
This error: 

```
---------------------------
Error
---------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'debugmodule'

Press Ctrl+C to copy this message to the clipboard.
```

means: it can find python properly, so no issues with Conda Path/Env but it can't find the `debugmodule.py`. If you uncheck `add workbook to PYTHONPATH`, you'll need to provide the path to where the python source file is under PYTHONPATH.

**Comment by Jeroendevr** [comment]
Hi fzumstein, thanks for your fast response. Somehow I was asssuming that because of miniconda I should not mess with those settings, but you're right it works now. What could be a reason that it cannot find python properly? (as in could I fix it?)

**Comment by fzumstein** [comment]
I am bit lost now what works and what doesn't?

**Comment by Jeroendevr** [comment]
Sorry for the confusion,
To be clear here 
**Works**
_Option 1_
- Do quickstart as described in minimal working example
- uncheck `add workbook to PYTHONPATH` and provide path as you suggested
_Option 2_
As descriped by the workaround.

I close the issue because my understanding is better.
