### ISSUE TITLE
Loading in third party addin dll file

### ISSUE THREAD

**Issue by tomnewg** [xlwings/xlwings#2165]
Hi all,

I am opening Excel with xlwings and need to load in S&P Cap IQ addin which is a dll file.
I tried .app.api.RegisterXLL(file path + file.dll)  and this returns false

I also tried app.api.AddIns(file path + file.dll) 
error: com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147352565), None)

Also tried app.api.AddIns.Add(addin name in Excel)
same error.

Any other suggestions what I could try? I have no problems loading in xlam addins with app.api.RegisterXLL(file path + file.xlam) 

Many thanks for your help

Tom

**Comment by fzumstein** [comment]
I'd suggest you ask S&P Cap IQ if RegisterXLL doesn't work.

**Comment by fzumstein** [comment]
closing this as it seems to be a third party issue.
