### ISSUE TITLE
xlwings UDF fails after reopening the file

### ISSUE THREAD

**Issue by randomrandomguy12345** [xlwings/xlwings#2167]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.29.1 on python 3.11.2
#### Describe your issue (incl. Traceback!)
I successfully set up UDF module for an excel. The UDF module test.py contains the following codes:

import pandas as pd
import xlwings as xw

```
@xw.func
def double_sum(x, y):
    """Returns twice the sum of the two arguments"""
    return 2 * (x + y)

@xw.func
@xw.arg('data', ndim=2)
def add_one(data):
    return [[cell + 600 for cell in row] for row in data]
```

The xlwings.conf sheet has the following info: 

![image](https://user-images.githubusercontent.com/120117562/217843245-ec036d0c-745f-40e4-8e4d-4d9e697e63e0.png)

On sheet1 the function `=add_one(1)` returns 600 as expected. After saving xlsm file and reopening, running the same cell returns this:

![image](https://user-images.githubusercontent.com/120117562/217843342-509caaf6-6d31-44f1-959d-aca0fa1186d6.png)

This happens if I immediately execute it. If I wait like 10s instead of calling that function right away, it works fine.

Why this behavior? It was running fine  before saving and reopening the file. I am running xlwings 0.29.1 on python 3.11.2.

I can make it work again if I do "Restart UDF Server" and then "import Functions" multiple times, like 5-6 times. Doesn't make sense.
```python
# Your traceback here


AttributeError:   module 'test2' has no attribute 'add_one'                  ^^^^^^^^^^^^^^^^^^^^^^^^^^         func = getattr(module,   func_name)       File   "C:\Users\boris\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlwings\udfs.py",   line 458, in call_udf                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^         res = call_udf(script, fname,   args, this_workbook, FromVariant(caller))       File   "C:\Users\boris\AppData\Local\Programs\Python\Python311\Lib\site-packages\xlwings\server.py",   line 235, in CallUDF                ^^^^^^^^^^^         return func(*args)       File   "C:\Users\boris\AppData\Local\Programs\Python\Python311\Lib\site-packages\win32com\server\policy.py",   line 637, in _invokeex_                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^         return S_OK, -1,   self._invokeex_(dispid, lcid, wFlags, args, None, None)       File   "C:\Users\boris\AppData\Local\Programs\Python\Python311\Lib\site-packages\win32com\server\policy.py",   line 308, in _invoke_                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^         return self._invoke_(dispid,   lcid, wFlags, args)       File   "C:\Users\boris\AppData\Local\Programs\Python\Python311\Lib\site-packages\win32com\server\policy.py",   line 303, in _Invoke_
--


```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
AntiVirus/WindowsDefender messing with it could be one explanation.

**Comment by randomrandomguy12345** [comment]
I turned it off, still works intermittently. I think there should be some check to ensure things are properly loaded before allowing any computation.

**Comment by randomrandomguy12345** [comment]
I ran exactly same tests for pyxll, it works fine even for instances were xlwings fails.

**Comment by fzumstein** [comment]
Glad you found a solution! There's also https://github.com/cunnane/xloil, which uses the same tech as pyxll, but is Open Source. Also, I am working on adding UDF support to Office.js, which will also fix this (and many other) issues. Closing this as you've found a solution and not reproducible over here.
