### ISSUE TITLE
No Insert Sheet Row functionality

### ISSUE THREAD

**Issue by kimbyungnam** [xlwings/xlwings#2168]
Hi all,

#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings >= 0.28.6, Excel 2016, Python 3.10

![image](https://user-images.githubusercontent.com/32065940/219628756-3d87f63b-448f-4b3f-bde5-bf0078002999.png)

- I am looking for a functionality to insert sheet row
- I figured out there is range.insert()
- But this does not insert whole row

Is there any way to insert sheet row?

**Comment by fzumstein** [comment]
This actually works: 

```python
xw.sheets.active['4:4'].insert()
```

where 4 would be your row number.

**Comment by kimbyungnam** [comment]
Thank you!

It is exactly what I want

If this could be a method of Sheet class, it would be awesome
