### ISSUE TITLE
Fails to build a document by sphinx 

### ISSUE THREAD

**Issue by knmaki** [xlwings/xlwings#2172]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.28.9, Sphinx 4.5.0, Python 3.9

#### Describe your issue (incl. Traceback!)
I tried to build html documentation with command ``.\make.bat html`` , but it failed. The error message is as follows:

```powershell
> .\make.bat html
Running Sphinx v4.5.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "C:\Users\xxxxx\.venvs\base\lib\site-packages\sphinx\config.py", line 332, in eval_config_file    exec(code, namespace)
  File "C:\Users\xxxxx\Documents\github_work\xlwings\docs\conf.py", line 124, in <module>
    import xlwings
  File "C:\Users\xxxxx\Documents\github_work\xlwings\xlwings\__init__.py", line 83, in <module>
    from . import _xlwindows
  File "C:\Users\xxxxx\Documents\github_work\xlwings\xlwings\_xlwindows.py", line 299, in <module>
    _PyCom_PyObjectFromIUnknown = PyDLL(pythoncom.__file__).PyCom_PyObjectFromIUnknown
  File "C:\Program Files\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\dev\null' (or one of its dependencies). Try using the full path with constructor syntax.

```

I was able to build it by modifying `./docs/conf.py` as follows : 

```python
# conf.py
...
# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
# import xlwings    # <- comment out

# version = xlwings.__version__     # <- comment out
# The full version, including alpha/beta/rc tags.
# release = version    # <- comment out
...
```
(Commented  out ``import xlwings``, ``version=...``, ``release=...``)

Is there any other appropriate way to fix it?

**Comment by fzumstein** [comment]
I've never built the docs on Windows... did you follow these instructions? https://github.com/xlwings/xlwings/blob/main/DEVELOPER_GUIDE.md#docs

**Comment by knmaki** [comment]
I tried that way but got the same error.

**Comment by knmaki** [comment]
I found the cause of the error.

Cause :
It was caused by replacing ``pythoncom`` module with ``Mock()`` in ``conf.py``. In usual ``import xlwings``, the value of ``pythoncom.__file__`` in ``_xlwindows.py`` is the full path to ``pythoncom39.dll``, but in ``conf.py`` the value of ``pythoncom.__file__`` replaced ``"/ dev/null"`` (because ``Mock.__file__`` is ``"/dev/null"``). Then ``PyDLL(pythoncom.__file__)`` raises the error above.

Solution:
The part of the code that uses ``__PyCom_PyObjectFromIUnknown = PyDLL(pythoncom.__file__).PyCom_PyObjectFromIUnknown`` is probably unnecessary for document generation.
Therefore, I suggest modifying ``_xlwindows.py`` so that ``_PyCom_PyObjectFromIUnknown`` is not generated when called in ``conf.py``, that is, when ``pythoncom.__file__`` equals ``"/dev/null"``.


https://github.com/xlwings/xlwings/blob/a2e8930232b2e24e6d2ad83d4b0d1bdc2dc11f73/docs/conf.py#L31-L74

https://github.com/xlwings/xlwings/blob/a2e8930232b2e24e6d2ad83d4b0d1bdc2dc11f73/xlwings/_xlwindows.py#L299-L300
to be modified as 
```python:_xlwindows.py
if pythoncom.__file__ != "/dev/null":
    _PyCom_PyObjectFromIUnknown = PyDLL(pythoncom.__file__).PyCom_PyObjectFromIUnknown
    _PyCom_PyObjectFromIUnknown.restype = py_object
```

**Comment by knmaki** [comment]
I found the cause of the error.

Cause :
It was caused by replacing ``pythoncom`` module with ``Mock()`` in ``conf.py``. In usual ``import xlwings``, the value of ``pythoncom.__file__`` in ``_xlwindows.py`` is the full path to ``pythoncom39.dll``, but in ``conf.py`` the value of ``pythoncom.__file__`` replaced ``"/ dev/null"`` (because ``Mock.__file__`` is ``"/dev/null"``). Then ``PyDLL(pythoncom.__file__)`` raises the error above.

Solution:
The part of the code that uses ``__PyCom_PyObjectFromIUnknown = PyDLL(pythoncom.__file__).PyCom_PyObjectFromIUnknown`` is probably unnecessary for document generation.
Therefore, I suggest modifying ``_xlwindows.py`` so that ``_PyCom_PyObjectFromIUnknown`` is not generated when called in ``conf.py``, that is, when ``pythoncom.__file__`` equals ``"/dev/null"``.


https://github.com/xlwings/xlwings/blob/a2e8930232b2e24e6d2ad83d4b0d1bdc2dc11f73/docs/conf.py#L31-L74

https://github.com/xlwings/xlwings/blob/a2e8930232b2e24e6d2ad83d4b0d1bdc2dc11f73/xlwings/_xlwindows.py#L299-L300
to be modified as 
```python:_xlwindows.py
if pythoncom.__file__ != "/dev/null":
    _PyCom_PyObjectFromIUnknown = PyDLL(pythoncom.__file__).PyCom_PyObjectFromIUnknown
    _PyCom_PyObjectFromIUnknown.restype = py_object
```

**Comment by fzumstein** [comment]
I fixed it in docs/conf.py instead.

**Comment by knmaki** [comment]
Thanks!
