### ISSUE TITLE
xlwings ribbon showing error 62 end of flie error 

### ISSUE THREAD

**Issue by gauravtiwariac** [xlwings/xlwings#2174]
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here


on clicking the xlwings tab/ribbon, this error pops up.



#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```
![2023-02-28_12h43_48](https://user-images.githubusercontent.com/126551890/221780720-b0ea6a3f-2be4-48db-8e03-2937de8f9c81.png)

**Comment by gauravtiwariac** [comment]
on clicking the xlwings tab/ribbon, this error pops up.

**Comment by fzumstein** [comment]
Open your `C:\Users\<user>\.xlwings/xlwings.conf` file and delete any empty lines at the end of the file.
