### ISSUE TITLE
Python API book.macro(...) cannot use Python-set environment variables

### ISSUE THREAD

**Issue by jaredgreen-pillar** [xlwings/xlwings#2178]
#### OS
Windows 11 and macOS Monterey

#### Versions of xlwings, Excel, and Python
xlwings - 0.29.1
Office 365
Python 3.11 and 3.9

#### Describe your issue
When calling a VBA macro via the xlwings Python API, any environment variable set via Python code is lost and unable to be referenced by the VBA code. This is desirable so that we can write unit tests for our VBA code that setup the environment in different ways.

#### Code sample (Python and VBA)
https://github.com/jaredgreen-pillar/xlwings-pytest

```python
import xlwings as xw
import os

def test_GetEnvironment():
    os.environ["TEST"] = "dev"
    wb = xw.Book('VBAWorkbook.xlsm')

    getEnvironment = wb.macro('GetEnvironment')
    
    assert os.environ["TEST"] == "dev"    # Passes - the env variable is set
    assert getEnvironment() == "dev"      # Fails - The "TEST" env variable is still blank according to VBA

```

VBAWorkbook.xlsm -> GetEnvironmentVariable module
```VB
Public Function GetEnvironment() As String
    GetEnvironment = Environ("TEST")
End Function

```

**Comment by fzumstein** [comment]
Can you try if it works if you start the Excel process via Python by explicitly creating a new app? i.e.

```python
os.environ["TEST"] = "dev"
app = xw.App()
wb = app.books.open("VBAWorkbook.xlsm")
```

**Comment by jaredgreen-pillar** [comment]
@fzumstein Yes, that does work. Thank you!  I will be okay to close this issue if that makes sense to you.

However, can you or someone else help me understand why this is the case? Does`xw.App()` start Excel differently than `xw.Book("")`? Is this the desired behavior?

**Comment by fzumstein** [comment]
xw.Book uses the active Excel instance. That one was opened before you defined the env vars, so doesn't know about them. xw.App starts a new Excel process and so will have your env vars available.
