### ISSUE TITLE
Document build error on the readthedocs.org (non-English)

### ISSUE THREAD

**Issue by knmaki** [xlwings/xlwings#2179]
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.29.1

#### Describe your issue (incl. Traceback!)

Since 2023/2/9, due to a build error on the readthedocs.org, the documentation other than English has not been updated. For example:
- Japanese translation by [this pull request](https://github.com/xlwings/xlwings/pull/2171) has not been applied.
  - https://docs.xlwings.org/ja/latest/installation.html
  - https://docs.xlwings.org/ja/latest/onedrive_sharepoint.html
- The "License Key Handling [PRO]" page added by [this commit](https://github.com/xlwings/xlwings/commit/55316e3de9204d758ae7108a775d5244c08cd058)(2023/2/10) does not exist in non-English pages.
  - en - exists: https://docs.xlwings.org/en/latest/license_key.html
  - ja - not exits: https://docs.xlwings.org/ja/latest/license_key.html

I confrmed the build error status by:
- en(no error): https://readthedocs.org/projects/xlwings/builds/
- ja: https://readthedocs.org/projects/xlwings-japanese/builds/
- zh_CN: https://readthedocs.org/projects/xlwings-simplifiedchinese/builds/

Both ja and zh_CN have the same error since 2023/2/29:
```
Error
Build output directory for format "pdf" contains multiple files and it is not currently supported. Please, remove all the files but the "pdf" your want to upload.
```

Checking the zh_CN log (2023/2/9), the error was raised by the following command (also in ja but not highlighted).
```
latexmk -r latexmkrc -pdf -f -dvi- -ps- -jobname=xlwings-simplifiedchinese -interaction=nonstopmode
```
https://readthedocs.org/projects/xlwings-simplifiedchinese/builds/19435133/

Could you please modify the readthedocs.org settings to avoid build errors?

**Comment by fzumstein** [comment]
Switching off the PDF build fixed this. No idea what's causing this, but I hope this is good enough, so closing this. By the way, before you invest a lot of time updating the translation, it may be a good idea to quickly check with me to make sure I am not going to rewrite big chunks of it right after your translation.

**Comment by knmaki** [comment]
I will check for changes before the next translation. Thank you for your consideration.
