### ISSUE TITLE
when will xlwings bring udfs to macOS arm?!!!!!!!!!!!

### ISSUE THREAD

**Issue by 2473-t** [xlwings/xlwings#2184]
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
Can you paste your error please?

**Comment by fzumstein** [comment]
Oh, you're talking about UDFs: this is now supported with PRO: https://docs.xlwings.org/en/latest/pro/server/officejs_custom_functions.html
