### ISSUE TITLE
 RunRemotePython for serverless functions debugging

### ISSUE THREAD

**Issue by Jeroendevr** [xlwings/xlwings#2193]
#### OS (e.g. Windows 10 or macOS Sierra)

Digital Ocean Serverless functions platform

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Python 3.9, xlwings 0.30.1

#### Describe your issue (incl. Traceback!)
Wanting to implement the serverless function, I don't know how to debug my setup correctly. 

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
Reference Python Serverless Functions from DigitalOcean
[Joke](https://github.com/digitalocean/sample-functions-python-jokes)
[Hello](https://github.com/digitalocean/sample-functions-python-helloworld)

Based on those examples my files are as follows

```shell
#!/bin/bash
set -e
virtualenv --without-pip virtualenv
pip install -r requirements.txt --target virtualenv/lib/python3.9/site-packages
```
requirements.txt
```txt
xlwings==0.30.1
```
From the fastAPI example I think I need to write the python code as follows. Removing the fastapi app en replacing this with args and deconstructing them later. Inspired by DigitalOceans `hello` [implementation](https://github.com/digitalocean/sample-functions-python-helloworld/blob/master/packages/sample/hello/hello.py)
```python
import xlwings as xw

def hello(args):
    # Instantiate a Book object with the deserialized request body
    data : dict = args.get("body")
    
    book = xw.Book(json=data)

    # Use xlwings as usual
    sheet = book.sheets[0]
    cell = sheet["A1"]
    if cell.value == "Hello xlwings!":
        cell.value = "Bye xlwings!"
    else:
        cell.value = "Hello xlwings!"

    # Pass the following back as the response
    return book.json()

```

Code inside Module1
```VBA
Sub DOSampleRemoteCall()
    RunRemotePython "https://faas-ams3-2a2df116.doserverless.co/api/v1/web/fn-{fn-number}/sample/hello"
End Sub
```
Running the code results in a 
```Error
{
"code": "ad66cbfe69f59ebf6f601dea91d82f94",
"error": "There was an error processing your request."
}
```

What is a good debugging strategy? Is it possible for example to serialize the workbook which is send by the call myself so I can experiment with the terminal and see the complete response error myself?

Also does any one has a working serverless example?

**Comment by fzumstein** [comment]
You need to consult the logs of your function in the DO dashboard. Looks like you'll need to use it like so:

```python
def hello(args):
    # Instantiate a Book object with the deserialized request body
    book = xw.Book(json=args)
    # ...
    # Pass the following back as the response
    return book.json()
```

**Comment by Jeroendevr** [comment]
Thanks for the response. I am a step further then yesterday. 
Apperantly for Digital Ocean to work with non standard library the python file needed to be renamed to `__main__.py` and the function renamed to `main`.

I've created a repo https://github.com/Jeroendevr/doctl-xlwings-hello which can be included by the docs if I manage to get it working. 

Running the function from the cloud control panel yield the following (no argument is given so I expect it to not work)
Output
```Shell
Your platform only supports the instantiation via xw.Book(json=...)
```
And the log is
```Shell
Activation Id: 72013c72dba54473813c72dba5d47333
2023-03-17T09:29:25.83024457Z  stderr: Traceback (most recent call last):
2023-03-17T09:29:25.830287409Z stderr:   File "/lib/prelauncher.py", line 145, in <module>
2023-03-17T09:29:25.830292387Z stderr:     res = fun(payload, os.environ)
2023-03-17T09:29:25.83029904Z  stderr:   File "/lib/prelauncher.py", line 124, in fun
2023-03-17T09:29:25.830303214Z stderr:     return main(payload) or {}
2023-03-17T09:29:25.830307253Z stderr:   File "/tmp/main__.py", line 6, in main
2023-03-17T09:29:25.830311249Z stderr:     book = xw.Book(json=args)
2023-03-17T09:29:25.830315136Z stderr:   File "/tmp/virtualenv/lib/python3.9/site-packages/xlwings/main.py", line 937, in __init__
2023-03-17T09:29:25.830319296Z stderr:     if apps.active:
2023-03-17T09:29:25.830323177Z stderr:   File "/tmp/virtualenv/lib/python3.9/site-packages/xlwings/main.py", line 212, in active
2023-03-17T09:29:25.830340579Z stderr:     for app in self.impl:
2023-03-17T09:29:25.830344195Z stderr:   File "/tmp/virtualenv/lib/python3.9/site-packages/xlwings/main.py", line 5140, in impl
2023-03-17T09:29:25.830347796Z stderr:     raise XlwingsError(
2023-03-17T09:29:25.830351243Z stderr: xlwings.XlwingsError: Your platform only supports the instantiation via xw.Book(json=...)
2023-03-17T09:29:25.830354861Z stderr: 
```
So my guess is that is works and the only error is because of the missing serialized workbook. To provide the workbook I run the RunRemotePython from the workbook.

The error message when running `RunRemotePython` is 
```Error
{
"code": "32b27f5e8fff0260729ff3b3be966168",
"error": "Response is not valid 'message/http'."
}
```

**Comment by fzumstein** [comment]
do you have the XLWINGS_LICENSE_KEY set as an env var?

**Comment by Jeroendevr** [comment]
Nope 😅 thanks that was the missing piece. Is it ok if I write some step-by-step plan in the docs for serverless functions? And perhaps highlight DigitalOcean?

**Comment by fzumstein** [comment]
Sure, but I don't think there's much to share between the different vendors, so I'd just do a page for DO, one for Azure etc. At this point, just a Repo with a README may also be good enough and the docs can link to all the sample repos instead.

* https://github.com/xlwings/xlwings-server-awslambda
* https://github.com/xlwings/xlwings-server-azurefunctions

**Comment by Jeroendevr** [comment]
Completely missed the function repos already there 🙃. Ok I close this and start some docs next week. Thanks again.
