### ISSUE TITLE
RunRemotePython 204 Response

### ISSUE THREAD

**Issue by Jeroendevr** [xlwings/xlwings#2194]
#### OS (e.g. Windows 10 or macOS Sierra)
Digital Ocean Serverless Function

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
- xlwings 0.30.2
- Python 3.9

#### My local Settings
- xlwings 0.30.2 addin readded (to be sure it was updated from 0.30.1)
- macOS on ARM
- Excel 16.71

#### Describe your issue (incl. Traceback!)
Yesterday I had the "Hello xlwings" demo running fine. But probably did not saved every thing or there happens to be a bug somewhere. Cause when running 

```VBA
Sub DOSampleRemoteCall()
    RunRemotePython "https://faas-ams3-2a2df116.doserverless.co/api/v1/web/fn-{fn-number}/sample/hello"
End Sub
```

I recieve a `Error (204)` I guess this means the function on the server does [not return a value](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204). 

__main__.py
```python
import os
os.environ["XLWINGS_LICENSE_KEY"] = "{Deployment key}"

import xlwings as xw

def main(args):
    # Instantiate a Book object with the deserialized request body
    
    book = xw.Book(json=args)

    # Use xlwings as usual
    sheet = book.sheets[0]
    cell = sheet["A1"]
    if cell.value == "Hello xlwings!":
        cell.value = "Bye xlwings!"
    else:
        cell.value = "Hello xlwings!"

    # Pass the following back as the response
    return book.json()

```

#### Output of the function according to Digital Oceans' _output_ (so no `args` ) provided seems fine. 

```log
{
  "actions": [
    {
      "args": [
        null
      ],
      "column_count": 1,
      "func": "setValues",
      "row_count": 1,
      "sheet_position": 0,
      "start_column": 0,
      "start_row": 0,
      "values": [
        [
          "Hello xlwings!"
        ]
      ]
    }
  ]
}

```
Part 1 in the series #2193 
See my [demo repo](https://github.com/Jeroendevr/doctl-xlwings-hello)

**Comment by Jeroendevr** [comment]
Small update, there seems to be a mismatch what `RunRemotePython` is recieving and my api test program or terminal 

As with 
```Shell
curl -X POST \
 'https://faas-ams3-2a2df116.doserverless.co/api/v1/web/fn-{fn-number}/sample/hello' \
 -L
```

The result is:

```JSON
{
    "code": "300440dfb7578fd5f980bb80b5cfaaec",
    "error": "Response is not valid 'message/http'."
}
```

I thought it's perhaps related to my workbook, so I created a new workbook with the quickstart for fastAPI and change added the `RunRemotePython` there but no luck

**Comment by FabianGoessling** [comment]
Hi, i'm not that deep into xlwings server, but two questions:
- Why is your demo repo with a requirement.txt of 0.30.1 while the addin is at 0.30.2?
- Can you track what reaches your digital ocean function? Maybe by a simple print of the json object? 

Error log seems like the incoming json is not what is expected, i.e. no serialized book - can you output it before the version check fails?

**Comment by fzumstein** [comment]
On DO, you need to return the following:

```python
return {"body": book.json()}
```

Also, remove

```
import os
os.environ["XLWINGS_LICENSE_KEY"] = "{Deployment key}"
```

and provide it via `project.yml` (using templating via local `.env` file that is in `.gitignore`), see https://docs.digitalocean.com/products/functions/reference/project-configuration/

I should have a full sample repo ready soonish.

**Comment by fzumstein** [comment]
I've published a sample repo now: https://github.com/xlwings/xlwings-server-digitaloceanfunctions so will close this issue.
