### ISSUE TITLE
Change in date format when pasting cells to another excel workbook

### ISSUE THREAD

**Issue by AydanW99** [xlwings/xlwings#2199]
Microsoft Windows 10 Pro
xlwings version 0.27.15

Hello.
I have a Python code that copies a range from one Excel workbook and pastes it another.
The problem I have is that when it comes to pasting dates, xlwings seems to convert the date format to MM-DD-YYYY, when it should be DD-MM-YYYY. When pasting to the second Excel file 10/04/2023 becomes 04/10/2023 (Excel reads this as 4th of October, so I cant change it back by changing Excel format settings). It's as if xlwings reads 10/04/2023 as MM/DD/YYYY and pastes it to Excel in this format, which causes Excel (who's date settings are DD/MM/YYYY) to confuse the original date as the 4th of Oct. Does this mean I need to change the xlwings date format somehow so it reads dates as DD/MM/YYYY, or is this something I need to specify in the code?

Not sure I've done a good job explaining my issue, and this is my first time reporting an issue on GitHub. Any help will be appreciated.    

Note: The following is dummy code. The original code copies a much large range, the below still has the issue discussed however. 

```python
###Copy Cells
    testFile = xw.Book("testFile.xlsx")
    sname = 'testSheet'

    if sname in [sh.name for sh in testFile .sheets]:
        testSheet = testFile.sheets[sname]
    
    TestData = testSheet.range("H7").value  

###Paste Cells

    testFile2 = xw.Book("testFile2.xlsx")
    sname = 'testSheet2'

    if sname in [sh.name for sh in testFile2.sheets]:
        testSheet2 = testFile2.sheets[sname]
    
    testSheet2.range("A1").value = TestData
```

**Comment by fzumstein** [comment]
I haven't come across this yet. Are you able to share a dummy Excel files that shows that behavior?

**Comment by AydanW99** [comment]
> I haven't come across this yet. Are you able to share a dummy Excel files that shows that behavior?

I think I've came across the source of the issue. It might be that the original date it copies isn't classed as a Date type. For reasons, it's difficult for me to convert the original
[testFile2.xlsx](https://github.com/xlwings/xlwings/files/11029296/testFile2.xlsx)
[testFile.xlsx](https://github.com/xlwings/xlwings/files/11029298/testFile.xlsx)
 date as an date in Excel.

**Comment by fzumstein** [comment]
Yes, looks like this is the issue. You could parse that string in Python into a datetime object to get around that issue.

**Comment by AydanW99** [comment]
> Yes, looks like this is the issue. You could parse that string in Python into a datetime object to get around that issue.

Fair enough. I think this is more of a Python question than xlwings question, but how would I do that for a column range (e.g. A2:A25).
