### ISSUE TITLE
Problem with the use of asynchronous UDFs with parameters that are a result of a formula

### ISSUE THREAD

**Issue by talalvas** [xlwings/xlwings#2218]
#### OS
Windows 11
#### Versions of xlwings, Excel and Python
xlwings 0.28.5, Office 365, Python 3.11

#### My Issue
I try to write asynchronous UDF that creates an API call and return a one dim array of the results to my sheet.
The parameters of the API call are sent as a function parameters to the asynchronous UDF.

If all of the UDF parameters I send from Excel are values (meaning no formulas) or a very simple formula that is not dependent of multiple cells and named range, everything works fine.

The problem is when the input of the UDF are formulas that are dependent on named ranges and lookups on ranges from that kind,
the calculation of the asynchronous UDF is almost infinate.
It dependent on the size of the range it lookups.

#### My Code
This is my UDF:
```python
@xw.func(category='xlwings', volatile=False, call_in_wizard=True, async_mode='threading')
def check_fedex_api(shipper_post_code: str, shipper_country_code: str, service_type: str,
                    weight_kg: str, quantity: str, value: str, value_curr: str):
"""Get quick rate from FedEx API"""
    
ret_dict = quick_rate_quote(shipper_post_code=shipper_post_code, shipper_country_code=shipper_country_code,
                            recipient_post_code=7565427, recipient_country_code='IL',
                            service_type=service_code, preferred_currency='USD',
                            weight_kg=weight_kg, quantity=quantity, value=value, value_curr=value_curr)

ret_list = list(ret_dict.values())
return ret_list
```

If i call it like so:
```excel
=check_fedex_api("24064","IT","Economy",0.1,30,15.7894736842105,"USD")
```
everything works fine.

Now, if I call it like that:
```excel
=check_fedex_api(A1,"IT","Economy",0.1,30,15.7894736842105,"USD")
```
and in A1 I have just a value - everything works fine.
If A1 has a simple VLOOKUP with a simple lookup range it is also quite quick.
But if A1 contains a lookup formula that uses a larger lookup range things begin to act like an infinite loop.

One of the best practices for writing a UDF is to check inside the UDF if the cell calculation has completed.
But the problem is if I try to send the parameters as xw.Range objects, I cannot preform any actions on the object because I get the error:
```python
pywintypes.com_error: (-2147417842, 'The application called an interface that was marshalled for a different thread.', None, None)
```
But even if i was possible to check the ranges, the problem still remains that the asynchronous UDF will get enormous number of calls.

I hope i posted enough in order to reproduce.

Thanks a lot for your help.
Tal.

**Comment by fzumstein** [comment]
Hey Tal, the async option for UDFs is a bit of a hack and thus comes with these limitations (it's why it's labeled as an experimental feature in the docs).

You can have a look at either the new xlwings custom functions (part of PRO, but free for non-commercial: https://docs.xlwings.org/en/latest/pro/server/officejs_custom_functions.html) as they are automatically async.

Or you could have a look at another project https://github.com/cunnane/xloil, which can support async functions properly.

**Comment by talalvas** [comment]
Thanks @fzumstein
Will it have support in feature editions?
Does xloil and xlwings can coexist?

Best regards,
Tal.

**Comment by fzumstein** [comment]
* Proper async functions can't be added to the current VBA/COM-based technology of the UDFs, so no, nothing will be changed there.
* xlwings does have support for async functions, but you'll need to use the new custom functions. They are based on the modern JS-based stack and run everywhere, not just Windows. They also don't require VBA, so are a lot more future-proof.
* xloil and xlwings can certainly coexist, but xloil is a completely independent project. Since xloil uses the C-API it can use the native async functions.

Closing this as it's a "known limitation".
