### ISSUE TITLE
docs xlwings-installers feedback

### ISSUE THREAD

**Issue by Jeroendevr** [xlwings/xlwings#2222]
If there is another place to provide feedback for the installer docs `README.md` let me know. 

The following link is broken

# xlwings installer
> You can find a comprehensive documentation including video walkthrough here:
> https://docs.xlwings.org/en/latest/release.html

Should be 
> You can find a comprehensive documentation including video walkthrough here:
> https://docs.xlwings.org/en/latest/pro/release.html

**Comment by fzumstein** [comment]
thx, fixed for future repos.
