### ISSUE TITLE
Settings standalone add-in using the xlwings-installer

### ISSUE THREAD

**Issue by Jeroendevr** [xlwings/xlwings#2224]
Using the xlwings installer in combination with an add-in I struggle to find the correct settings. 
This issue is to log my attempts and used settings and hopefully would lead to improved docs for this specific use case. 

#### OS
Windows 11

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings = 0.30.4
python = 3.11
office = 365

#### Steps taken
project name = project-addin

1. Create template based on quickstart (note underscore because python modules need to be underscores.
```shell
xlwings quickstart project_addin --addin --ribbon
```

2. Clone installer repository
```shell
git clone {repo url}
```

3. Move the quickstart files to the installer repository. Folder structure looks like
```shell
.
├── README.md
├── addins
│   └── project_addin.xlam
├── data
├── installer-template.sh
├── packages
├── requirements.txt
└── src
    └── project_addin.py
```

Question 1 : 
Based on the installer `README` if I use files in the src file and use an addin, I don't need to provide and release a workbook, correct?

> ## Add-ins
> If you work with an add-in (xlam) rather than a normal Excel file (xlsx, xlsm, xlsb), you can add it in the addins folder so that it gets installed automatically. You could, however, also use a different mechanism to deploy the Excel add-in and only use the installer for the Python dependencies.

Question 2 :
Does the installer handle the configuration of the add-in `xlam` or do I need to provide the config myself?

Answer 2 :
Yes otherwise, the python installation can't be found.
> Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
> 
> Press Ctrl+C to copy this message to the clipboard.

4. Edit the add-in `xlam` settings 
As described [here](https://docs.xlwings.org/en/latest/customaddin.html#quickstart)
Setting the `Interpreter_Win`
`%LOCALAPPDATA%\project-addin\pythonw.exe`
Also tried with quotes
`"%LOCALAPPDATA%\project-addin\pythonw.exe"`

Still yields the Python not found error.

Question 3 :
What is the correct Interpreter setting when using the xlwings-installer? Or is the python interpreter missing because of some other setting?
( This installer has been built and installed on the target system, I can open a terminal by running `"C:\Users\hayer\AppData\Local\project-addin\python.exe"` and `"%LOCALAPPDATA%\project-addin\python.exe"`)

Question 4 :
Should the add-in `xlam` be configure before creating a installer so that the `.project-addin/project-addin.conf` gets created during installation?

Answer 4 : 
Did not made any difference same 
> Python was not found;
error

**Comment by fzumstein** [comment]
1) Actually, the `xlwings release` command doesn't currently work for custom add-ins. So you'll need to manually configure the config of the custom add-in (not `xlwings.conf`, but `myaddin.conf`, or whatever you have set the name to) to point to the correct Python interpreter, which by default is `"%LOCALAPPDATA%\project-addin\python.exe"`

2) The installer only takes the files in the `addin` folder and drops them in the XLSTART folder, nothing else.

3) You may be manipulating the xlwings config instead of the one of your custom add-in

4) You should configure it via the sheet configuration as you can't have a config file next to the addin when you install it in the XLSTART folder. And the installer is also not writing anything to the user's directory.

**Comment by Jeroendevr** [comment]
thanks for the fast and clear response!
Please give me feedback if I am troubling you too much. I appreciate the effort you put into helping me out. 

I've got it working, thanks. Issue was indeed editing the config of the addin and renaming the config sheet from `_myaddin.conf` to `myaddin.conf` to make it active. I think that on my test vm no config was active and therefore this message popped up. 

I'll edit the settings page and trouble shooting page for future me.
