### ISSUE TITLE
Automatically open a task pane with a document

### ISSUE THREAD

**Issue by p-d-h** [xlwings/xlwings#2233]
Is there a possibility to display an Office.js add-in task pane automatically when opening a document?
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document

**Comment by fzumstein** [comment]
I've never tried this, but if it works the way they describe it, it should work? This [StackOverflow question](https://stackoverflow.com/questions/56414047/auto-opening-side-loaded-taskpane) makes it look like it's not totally straight forward though. 

Just to confirm: what you'd like is the task bar to shows up automatically when a user opens a certain Excel file?

**Comment by p-d-h** [comment]
Just discovered the following example:
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document
https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/office-add-in-commands/auto-open-task-pane

Office.context.document.settings.set(
  'Office.AutoShowTaskpaneWithDocument',
  true
);
Office.context.document.settings.saveAsync();

in the manifest set the taskpane id Office.AutoShowTaskpaneWithDocument

**Comment by fzumstein** [comment]
Awesome, thanks for the link! Were you able to get it to work like this?

**Comment by p-d-h** [comment]
yes, important is the assignment of the TaskpaneId in the manifest
<TaskpaneId>Office.AutoShowTaskpaneWithDocument</TaskpaneId>
Only this id allows automatic opening of the taskpane when the file is
started.

Am Mo., 14. Aug. 2023 um 08:18 Uhr schrieb Felix Zumstein <
***@***.***>:

**Comment by fzumstein** [comment]
Great, closing this is issue then!

**Comment by fzumstein** [comment]
This seems to do the same thing... sort of (?): https://learn.microsoft.com/en-us/office/dev/add-ins/develop/run-code-on-document-open

**Comment by fzumstein** [comment]
I see, my link only loads the add-in, but doesn't automatically display the task pane.
