### ISSUE TITLE
Exception by reading a table-object from a not selected/visible spreadsheet

### ISSUE THREAD

**Issue by TenchiMuyo1984** [xlwings/xlwings#2234]
**Versions:**
- OS: Windows 10 Pro 22H2 (19045.2846)
- xlwings: several versions but focus lays on 0.27.11, 0.27.12 and 0.30.4 (latest version)
- Excel 2013 (german version) with all available updates
- Python 3.10.8

**I get this exception (version 0.27.12):**
```python
Traceback (most recent call last):
  File "D:\Python\sandbox\test12.py", line 150, in <module>
    a = xw.Range("Tabelle1[#Alle]").options(pd.DataFrame).value
  File "D:\Python\sandbox\venv\lib\site-packages\xlwings\main.py", line 1675, in __init__
    impl = apps.active.range(cell1).impl
  File "D:\Python\sandbox\venv\lib\site-packages\xlwings\main.py", line 514, in range
    return self.books.active.sheets.active.range(cell1, cell2)
  File "D:\Python\sandbox\venv\lib\site-packages\xlwings\main.py", line 1323, in range
    return Range(impl=self.impl.range(cell1, cell2))
  File "D:\Python\sandbox\venv\lib\site-packages\xlwings\_xlwindows.py", line 948, in range
    xl1 = self.xl.Range(arg1)
  File "D:\Python\sandbox\venv\lib\site-packages\xlwings\_xlwindows.py", line 104, in __call__
    v = self.__method(*args, **kwargs)
  File "C:\Users\marti\AppData\Local\Temp\gen_py\3.10\00020813-0000-0000-C000-000000000046x0x1x8.py", line 44946, in Range
    ret = self._oleobj_.InvokeTypes(197, LCID, 2, (9, 0), ((12, 1), (12, 17)),Cell1
pywintypes.com_error: (-2147352567, 'Ausnahmefehler aufgetreten.', (0, None, None, None, 0, -2146827284), None)
```

**I get this exception (version 0.30.4 (latest)):**
```python
Traceback (most recent call last):
  File "D:\Python\sandbox\test12.py", line 150, in <module>
    a = xw.Range("Tabelle1[#Alle]")
  File "D:\Python\sandbox\venv\lib\site-packages\xlwings\main.py", line 1806, in __init__
    impl = apps.active.range(cell1).impl
  File "D:\Python\sandbox\venv\lib\site-packages\xlwings\main.py", line 554, in range
    return self.books.active.sheets.active.range(cell1, cell2)
  File "D:\Python\sandbox\venv\lib\site-packages\xlwings\main.py", line 1438, in range
    return Range(impl=self.impl.range(cell1, cell2))
  File "D:\Python\sandbox\venv\lib\site-packages\xlwings\_xlwindows.py", line 1022, in range
    xl1 = self.xl.Range(arg1)
  File "D:\Python\sandbox\venv\lib\site-packages\xlwings\_xlwindows.py", line 121, in __call__
    v = self.__method(*args, **kwargs)
  File "C:\Users\marti\AppData\Local\Temp\gen_py\3.10\00020813-0000-0000-C000-000000000046x0x1x8.py", line 44946, in Range
    ret = self._oleobj_.InvokeTypes(197, LCID, 2, (9, 0), ((12, 1), (12, 17)),Cell1
pywintypes.com_error: (-2147352567, 'Ausnahmefehler aufgetreten.', (0, None, None, None, 0, -2146827284), None)
```

**My code (example):**
```python
import xlwings as xw

wb = xw.Book("test.xlsx")
a = xw.Range("Tabelle1[#Alle]")
```

**Steps to reproduce this error**
1. You need an excel-file with at least two spreadsheets
2. Add a table-objet on one of the spreadsheets
3. Select a different spreadsheet
4. Safe the file
5. Run the script

**Which analyzes have already been carried out?**
This eception occurs when a spreadsheet is selected (visible) that does not contain the desired table-object.

Problem exists since version 0.27.12
Tested with:
- 0.27.13
- 0.27.14
- 0.27.15
- 0.28.0
- 0.29.0
- 0.30.0
- 0.30.4 (latest)

Up to version 0.27.11 it doesn't matter which worksheet is selected. You can even access table-objects that reside on hidden spreadsheets.

**Comment by fzumstein** [comment]
could you upload an excel file to reproduce?

**Comment by TenchiMuyo1984** [comment]
Here are the files.
Please read the notes in green and red cells (F4 + G4) also!

[test_works.xlsx](https://github.com/xlwings/xlwings/files/11282708/test_works.xlsx)
Speadsheets `abcd` and `efgh` are visible but `abcd` has to be selected.
[test_doesnt_work_1.xlsx](https://github.com/xlwings/xlwings/files/11282703/test_doesnt_work_1.xlsx)
Speadsheets `abcd` and `efgh` are visible but `efgh` has to be selected.
[test_doesnt_work_2.xlsx](https://github.com/xlwings/xlwings/files/11282706/test_doesnt_work_2.xlsx)
Speadsheet `abcd` is hidden
spreadsheet `efgh` is visible and selected only.

The table-object `Table1` is located on spreadsheet `abcd`.

**The code:**
```py
import xlwings as xw

wb = xw.Book("test_works.xlsx")
a = xw.Range("Table1[#Alle]")
print(a)

wb = xw.Book("test_doesnt_work_1.xlsx")
a = xw.Range("Table1[#Alle]")
print(a)

wb = xw.Book("test_doesnt_work_2.xlsx")
a = xw.Range("Table1[#Alle]")
print(a)
```

The code will work without any exceptions up to version 0.27.11 for all 3 files.
If you use a version >= 0.27.12 it will work for the first file (`test_works.xlsx`) only and raise an exception for the other two files (`test_doesnt_work_1.xlsx` and `test_doesnt_work_2.xlsx`)

**Comment by TenchiMuyo1984** [comment]
Same problem on my device at work:
Versions:

- OS: Windows 10 Pro 22H2 (19045.2728)
- xlwings: several versions but focus lays on 0.27.11, 0.27.12 and 0.30.4 (latest version)
- Excel: Microsoft 365 (englisch version)
- Python 3.10.4

```py
import xlwings as xw

wb = xw.Book("test_works.xlsx")
a = xw.Range("Table1[#All]")
print(a)

wb = xw.Book("test_doesnt_work_1.xlsx")
a = xw.Range("Table1[#All]")
print(a)

wb = xw.Book("test_doesnt_work_2.xlsx")
a = xw.Range("Table1[#All]")
print(a)
```

Because of our IT-Sec rules, I am not allowed to send any tracebacks from this device.
This is just an information to explain that this problem effect not Excel 2013 or language (german) at all.

**Comment by fzumstein** [comment]
Thanks for providing the files and finding out when this was introduced! 

This is a side-effect of https://github.com/xlwings/xlwings/pull/1982, as it now looks at `xw.Range` strictly as a range on the active sheet. While this was unintended, I'd prefer to keep it as is because I'd like to stick closer to Office Scripts than to VBA going forward (Office Scripts doesn't have a global Range class). 

So to fix this, you should use `wb.sheet[0].tables["Table1"].range` instead of `xw.Range("Table1[#All]")`. What's currently missing though in xlwings is the ability to get all tables across all sheets directly via `wb.tables` (again, to be in line with Office Scripts), but this shouldn't be too hard to add in a future release.

If you don't know the sheet on which your table is, you would have to loop through the various sheets for now as a workaround.

**Comment by TenchiMuyo1984** [comment]
> Thanks for providing the files and finding out when this was introduced!

No problem.

> This is a side-effect of #1982, as it now looks at `xw.Range` strictly as a range on the active sheet. While this was unintended, I'd prefer to keep it as is because I'd like to stick closer to Office Scripts than to VBA going forward (Office Scripts doesn't have a global Range class).

That's a sensible decision. I don't like VBA either.

> So to fix this, you should use `wb.sheet[0].tables["Table1"].range` instead of `xw.Range("Table1[#All]")`. What's currently missing though in xlwings is the ability to get all tables across all sheets directly via `wb.tables` (again, to be in line with Office Scripts), but this shouldn't be too hard to add in a future release.

Thank you for the suggestion, I will think about that.
But you've here a type. It should be
`wb.sheets[0].tables["Table1"].range`
and not:
`wb.sheet[0].tables["Table1"].range`
But that will select the entire table-object. How I can select a special range?
[#All]
[#Headers]
[#Data]
[#Totals]
Or they will become obsolete?

I'd the same idea with `wb.tables`, but that isn't available for now.

> If you don't know the sheet on which your table is, you would have to loop through the various sheets for now as a workaround.

How I can loop? You mean with try and except?:
```py
for sht in wb.sheets:
    try:
        a = sht.tables["Table1"].range
        break
    except:
        continue
```

**Comment by fzumstein** [comment]
* You have pretty much the full API available on the table object: https://docs.xlwings.org/en/latest/api/table.html and unlike `[#All]` etc, it isn't language-specific.

* Yeah, I guess your loop works or something like the following:

  ```python
  tables = {}
  for sheet in wb.sheets:
      for table in sheet.tables:
          tables[table.name] = table
  ```

  then you can access your table via `tables["Table1"]` which is close to a future `wb.tables`.

* There's https://docs.xlwings.org/en/latest/pro/reader.html (part of PRO) to access files without Excel, but it doesn't currently support Tables, so current answer is "no"
