### ISSUE TITLE
xw.books.open() is not working properly

### ISSUE THREAD

**Issue by mqslllddyy** [xlwings/xlwings#2242]
#### When I run the below functions, it will return error:
_book = xw.books.open(r"D:\python\xlwings\XLWINGS OBJECT MODEL\Book\books.xlsx")_

So when and how can we use xw.books.open() separately without openning an App firstly??
```
Traceback (most recent call last):
  File "d:\python\xlwings\XLWINGS OBJECT MODEL\Book\books.py", line 18, in <module>
    book = xw.books.open(r"D:\python\xlwings\XLWINGS OBJECT MODEL\Book\books.xlsx")
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\xlwings\main.py", line 5043, in open
    if self.impl.app.engine.type == "remote":
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\xlwings\main.py", line 5183, in impl
    raise XlwingsError("Couldn't find any active App!")
xlwings.XlwingsError: Couldn't find any active App!
```

```
import xlwings as xw

book = xw.books.open(r"D:\python\xlwings\XLWINGS OBJECT MODEL\Book\books.xlsx")

```

**Comment by fzumstein** [comment]
In most cases, you want to work with `xw.Book()`, which does exactly what you want: open Excel if it isn't running yet, and open the file if it isn't open yet.

`xw.books` is the books collection of the active app. Likewise, `xw.sheets` is the sheets collection of the active book in the active app etc.

See: https://docs.xlwings.org/en/latest/connect_to_workbook.html

**Comment by mqslllddyy** [comment]
Yes, I agree with you, but I just read the doc of xlwins and found the method for Books, so i also think the method "open()" is not proper for Books.

https://docs.xlwings.org/en/latest/api/books.html

**Comment by mqslllddyy** [comment]
> Yes, I agree with you, but I just read the doc of xlwins and found the method for Books, so i also think the method "open()" is not proper for Books.
> 
> https://docs.xlwings.org/en/latest/api/books.html


Yes, I agree with you, but I just read the doc of xlwins and found the method for Books, so i also think the method "open()" is not proper for Books.

https://docs.xlwings.org/en/latest/api/books.html

**Comment by mqslllddyy** [comment]
> In most cases, you want to work with `xw.Book()`, which does exactly what you want: open Excel if it isn't running yet, and open the file if it isn't open yet.
> 
> `xw.books` is the books collection of the active app. Likewise, `xw.sheets` is the sheets collection of the active book in the active app etc.
> 
> See: https://docs.xlwings.org/en/latest/connect_to_workbook.html


Yes, I agree with you, but I just read the doc of xlwins and found the method for Books, so i also think the method "open()" is not proper for Books.

https://docs.xlwings.org/en/latest/api/books.html

**Comment by fzumstein** [comment]
It is, but you'd either have to have an active Excel instance, create one first, or use `books` as a property of a specific `app`. Docs can always be improved though.

**Comment by mqslllddyy** [comment]
got it！

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
