### ISSUE TITLE
Feature request: When trying to read workbook sheet that doesnt exist, throw a helpful error.

### ISSUE THREAD

**Issue by m4rz910** [xlwings/xlwings#2246]
Using xlwings version: 0.27.15

```python
wb.sheets['sheet1']  #Sheet1 exists but sheet1 doesnt exist in my workbook, so causes an error...
```

Yields a very obscure error that makes it hard to figure out what is going wrong 
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147352565), None)

**Comment by fzumstein** [comment]
I wouldn't say it isn't planned, it should be part of a bigger Exception handling refactor: https://github.com/xlwings/xlwings/issues/1993
