### ISSUE TITLE
Query on Picture.update()

### ISSUE THREAD

**Issue by mqslllddyy** [xlwings/xlwings#2249]
Hi Felix,

May I know can we use the relative file path as the param "image" for Picture.update()? just like below : 

picture.update("test.jpg")

**Comment by fzumstein** [comment]
Yes and no: if you control the working directory, then yes. For example if you run the script directly from Python in the directory of that script (and the jpg). But if you call it from the Excel add-in, the working directory is a different one, so you'd have to fully qualify the path.

You can use something like:

```python
from pathlib import Path
this_dir = Path(__file__).resolve().parent
# ...
picture.update(this_dir / "test.jpg")
```

**Comment by mqslllddyy** [comment]
Hi Felix,

Yes, your advice is very cool and fit for me, thx!

Best Regards!

Meng, Qingsong(Rocky)

发件人: Felix Zumstein ***@***.***>
发送时间: 2023年5月5日 14:36
收件人: xlwings/xlwings ***@***.***>
抄送: mqslllddyy ***@***.***>; Author ***@***.***>
主题: Re: [xlwings/xlwings] Query on Picture.update() (Issue #2249)


Yes and no: if you control the working directory, then yes. For example if you run the script directly from Python in the directory of that script (and the jpg). But if you call it from the Excel add-in, the working directory is a different one, so you'd have to fully qualify the path.

You can use something like:

from pathlib import Path

this_dir = Path(__file__).resolve().parent

# ...

picture.update(this_dir / "test.jpg")
