### ISSUE TITLE
xlwings.xlam fails malware tests

### ISSUE THREAD

**Issue by tfoale** [xlwings/xlwings#2254]
All operating systems

Latest version of xlwings (5th May 2023)

Our EPP service Deep Instinct blocks the addin xlwings.xlam from execution as part of the downloaded package and independent download on all OS tested, as a high-severity threat. The Mitre mapping categories detected are:

- Tactic: Initial Access (TA0001) and Execution (TA0002)
- Technique: Phishing (T1566) and User Execution (T1204)
- Sub-technique: Spearphishing attachment (T1566.001) and Malicious File (T1204.002)

The file hash of the xlwings.xlam file is ab1fbaba7ed761f7e00ab9d8e1c8815af7d939b47c55ae8798c9e2e0199e1675

To test the package I used DataDog’s guarddog which can scan pypi packages for malware. Its findings (probably not related to xlwings.xlam) are:

Found 2 potentially malicious indicators in xlwings

repository_integrity_mismatch: Some files present in the package are different from the ones on GitHub for the same version of the package: 
* ./Cargo.toml
* ./Cargo.lock
* ./MANIFEST.in
* ./setup.py
* tests/test_names.py
* tests/test_characters.py
* tests/test_sheet.py
* tests/test_shape.py
* tests/test_font.py
* tests/test_table.py
* tests/test_chunking.py
* tests/test_active.py
* tests/test_conversion.py
* tests/test_book.py
* tests/test_e2e.py
* tests/test_fileformats.py
* tests/test_range.py
* tests/test_markdown.py
* tests/test_app.py
* xlwings/server.py
* xlwings/_win32patch.py
* xlwings/constants.py
* xlwings/base_classes.py
* xlwings/quickstart_addin.xlam
* xlwings/_xlwindows.py
* xlwings/__init__.py
* xlwings/mac_dict.py
* xlwings/cli.py
* xlwings/quickstart_addin_ribbon.xlam
* xlwings/utils.py
* xlwings/reports.py
* xlwings/expansion.py
* xlwings/main.py
* xlwings/_xlmac.py
* xlwings/quickstart_standalone.xlsm
* xlwings/udfs.py
* xlwings/mistune/scanner.py
* xlwings/mistune/util.py
* xlwings/mistune/__init__.py
* xlwings/mistune/renderers.py
* xlwings/mistune/markdown.py
* xlwings/mistune/block_parser.py
* xlwings/mistune/inline_parser.py
* xlwings/mistune/directives/toc.py
* xlwings/mistune/directives/admonition.py
* xlwings/mistune/directives/__init__.py
* xlwings/mistune/directives/include.py
* xlwings/mistune/directives/base.py
* xlwings/mistune/plugins/task_lists.py
* xlwings/mistune/plugins/extra.py
* xlwings/mistune/plugins/abbr.py
* xlwings/mistune/plugins/__init__.py
* xlwings/mistune/plugins/table.py
* xlwings/mistune/plugins/footnotes.py
* xlwings/mistune/plugins/def_list.py
* xlwings/addin/WebResponse.cls
* xlwings/addin/Dictionary.cls
* xlwings/addin/xlwings.xlam
* xlwings/addin/WebClient.cls
* xlwings/addin/WebHelpers.bas
* xlwings/addin/WebRequest.cls
* xlwings/addin/IWebAuthenticator.cls
* xlwings/pro/_xlcalamine.py
* xlwings/pro/_xlremote.py
* xlwings/pro/__init__.py
* xlwings/pro/udfs_officejs.py
* xlwings/pro/embedded_code.py
* xlwings/pro/_xlofficejs.py
* xlwings/pro/utils.py
* xlwings/pro/module_permissions.py
* xlwings/pro/reports/__init__.py
* xlwings/pro/reports/pdf.py
* xlwings/pro/reports/markdown.py
* xlwings/pro/reports/main.py
* xlwings/pro/reports/image.py
* xlwings/pro/reports/filters.py
* xlwings/js/xlwings.ts
* xlwings/js/xlwings.js
* xlwings/quickstart_fastapi/main.py
* xlwings/ext/__init__.py
* xlwings/ext/sql.py
* xlwings/html/xlwings-alert.html
* xlwings/conversion/standard.py
* xlwings/conversion/framework.py
* xlwings/conversion/__init__.py
* xlwings/conversion/numpy_conv.py
* xlwings/conversion/pandas_conv.py
* xlwings/rest/serializers.py
* xlwings/rest/__init__.py
* xlwings/rest/api.py
* xlwingsjs/build.py
* xlwingsjs/devserver.py
* xlwingsjs/custom_functions.py
* xlwingsjs/check_version.py
* xlwingsjs/tests/udf_tests_officejs.py
* src/lib.rs

exfiltrate-sensitive-data: found 1 source code matches
  * This package is exfiltrating sensitive data to a remote server at xlwings-0.30.6/xlwings/pro/module_permissions.py:99
        response = requests.post(
                config["permission_check_url"],
                json=payload,
                timeout=10,
                headers=headers,
            )

**Comment by fzumstein** [comment]
Since you didn't ask any question, I am not quite sure what you expect as an answer, but maybe some explanations of why you get these false positives?

* `xlwings.xlam`: makes calls to the shell or dll to call Python, which dumb virus scanners categorize as a threat. You can get around this by using xlwings Server.
* repository_integrity_mismatch: there's a handful of files that are getting "built"  for a release like the Excel files (to update the version string and concatenate multiple modules into one), but 99% of the files on that list are the same. Please send over a case where that's not the case.
* exfiltrate-sensitive-data: xlwings PRO allows you to add an *own* URL to the settings to where xlwings will send the computer name so you can allow/block code execution.

**Comment by tfoale** [comment]
Thanks, that's great. I'm new to Github. Deep Instinct is deep learning AI, which means nothing gets past but it does occasionally catch a behaviour that is benign in context.
