### ISSUE TITLE
Mamba installs xlwings64-0.30.7.dll, xlwings in Excel looks for xlwings64-0.30.6, therefore cannot load UDF.

### ISSUE THREAD

**Issue by trent-shipley** [xlwings/xlwings#2263]
#### OS (e.g. Windows 10 or macOS Sierra)
Win11 beta
Version	10.0.22624 Build 22624

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

Python 3.11.3
XL: Microsoft® Excel® for Microsoft 365 MSO (Version 2306 Build 16.0.16505.20000) 64-bi

# packages in environment at C:\ProgramData\mambaforge\envs\python-for-excel:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2023.5.7             h56e8100_0    conda-forge
libexpat                  2.5.0                h63175ca_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libsqlite                 3.42.0               hcfcfb64_0    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
openssl                   3.1.0                hcfcfb64_3    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
python                    3.11.3          h2628c8c_0_cpython    conda-forge
python_abi                3.11                    3_cp311    conda-forge
pywin32                   304             py311h12c1d0e_2    conda-forge
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
vc                        14.3                hb25d44b_16    conda-forge
vc14_runtime              14.34.31931         h5081d32_16    conda-forge
vs2015_runtime            14.34.31931         hed1258a_16    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xlwings                   0.30.7          py311h1ea47a8_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge

#### Describe your issue (incl. Traceback!)

Whiile starting work on chapter 12 of Python for Excel (in English) which is 

I got the could not find DLL message.

Having read and applied [https://docs.xlwings.org/en/stable/troubleshooting.html](url) by deleting and re-installing the Mamba environment, then using mamba to reinstall xlwings, 

then redoing xlwings quickstart first_udf

then explicitly specifying PYTHONPATH, Conda Path, and Conda Env

xlwings was still looking for xlwings64-0.30.6.dll

BUT mamba had updated to xlwings64-0.30.7.dll so xlwings could not find it's DLL.

I changed the name of the DLL file to xlwings64-0.30.6.dll, which proved to be an effective workaround.

```python
# Your traceback here

N/A

**Comment by trent-shipley** [comment]
xlwings addin install

obviously.

**Comment by fzumstein** [comment]
Yes, you need to have both VBA and Python in the same version. It should really give you a better error message though and there's an open issue for that: https://github.com/xlwings/xlwings/issues/1099 (the new-school xlwings Server already handles this properly).
