### ISSUE TITLE
permission denied error when calling Python UDF from Excel

### ISSUE THREAD

**Issue by nroeth** [xlwings/xlwings#2264]
#### Describe your issue (incl. Traceback!)

We have multiple spreadsheets that use xlwings to call Python functions.  They recently started generating "permission denied, could not start Python process" errors.  I don't believe anything changed in our xlwings setup so it is most likely something that changed on our computers.  So far, that sounds like NOT an xlwings bug, but.... what exactly is xlwings trying to access when it starts a process from Excel that it might not have permission to read/write?  It shows the command it tried to execute in a dialog box and that command works just fine when run from a command prompt, i.e., the access denied doesn't seem to be anything related to running the Python command, it seems to be from something xlwings is doing when it executes the Python command.  In fact, if I start the xlwings server from the command line, the spreadsheet communicates with it and executes the functions just fine, so it really is something specific to the Python startup process that is the issue.  What files or folders is xlwings trying to access while it is starting the Python process?

The error occurs when we call some custom xlwings functions we wrote and call from the spreadsheet, but I also get a similar error when I run the hello.py example in the documentation with RunPython in VBA.  In this case, the exact and full error is "Run-time error '70': Permission denied".  Again, I can run that same Python script from the command line without errors so I clearly have permission to access the Python script and Python itself.

**Comment by fzumstein** [comment]
This is usually a virus scanner / Windows defender interfering. The xlwings VBA module runs shell commands and/or accesses the xlwings dll, which is often blocked.

Workaround would be to run the UDFs in debug mode and start the server manually from Python or use the new custom functions, which works basically the same, with the difference that you can also run the function server on a different machine, i.e., a real server.

**Comment by nroeth** [comment]
That was it.  We use a product called Carbon Black which as I understand it flagged the xlwings DLLs as possible malware, then a recent group policy change denied processes like spreadsheets from using any DLLs marked as such.

**Comment by ccsucic** [comment]
> That was it. We use a product called Carbon Black which as I understand it flagged the xlwings DLLs as possible malware, then a recent group policy change denied processes like spreadsheets from using any DLLs marked as such.

Did you find a workaround for using xlwings with Carbon Black?

**Comment by fzumstein** [comment]
@ccsucic not exactly the answer you're looking for, but upgrading to custom functions will get rid of any virus scanner issues: https://docs.xlwings.org/en/latest/pro/server/officejs_custom_functions.html
