### ISSUE TITLE
Runtime error 1

### ISSUE THREAD

**Issue by leyojoseph** [xlwings/xlwings#2277]
#### * Spyder version: 5.4.1  (conda)
* Python version: 3.10.9 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10
Xlwings addin version 0.30.8

#### Describe your issue (incl. Traceback!)
The xlwings integration of pythong and excel was working fine in my computer. Because of some issues, I had to uninstall Ananconda, xlwings etc and reinstall. After this I am getting the error 
![image](https://github.com/xlwings/xlwings/assets/67446653/85966f9e-a307-4b98-90ec-51b356be2e63)
"Could not load xlwings64-0.38.8 dll from either of the following folders: C:\users\ljoseph|Ananconda, C:\users\ljoseph
![image](https://github.com/xlwings/xlwings/assets/67446653/2b90e1fa-bf81-46e5-beb1-3195096ac159)

Please help me on this.
```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
Make sure that xlwings in your new anaconda installation has the same version as your add-in (or probably better the other way around): run `xlwings addin install` again from a Anaconda prompt.

**Comment by leyojoseph** [comment]
Thanks a lot. Did  as you suggested and and it fixed Run-Time error 1. But now I am getting the below error. Could you please help. 
![image](https://github.com/xlwings/xlwings/assets/67446653/6fd06a26-c7ea-4b40-91d3-176dc975983b)

**Comment by fzumstein** [comment]
Uncheck `Debug UDFs`, as this requires to start the server manually.

**Comment by leyojoseph** [comment]
Thanks a lot.. everything is working now
