### ISSUE TITLE
xlwings xw.Book will no responding when some excel file in edit mode

### ISSUE THREAD

**Issue by sunflyfairy** [xlwings/xlwings#2278]
#### Describe your issue (incl. Traceback!)

   When I have opened some excel file(the file I want to open or another) and enter excel edit mode(by double click a cell),the code will no responding.

```python
# Your code here
import xlwings as xw

with xw.App(visible=False) as app:
    wb = xw.Book("test.xlsx")

    # Do some stuff e.g.
    wb.sheets[0]["A1"].value = 123456
    wb.save("test.xlsx")
    wb.close()

```
![Capture](https://github.com/xlwings/xlwings/assets/87637658/0adcd0b4-d605-4834-b025-9659be4308ec)

**Comment by fzumstein** [comment]
This is a "feature" currently, but there's an open issue to fix this: https://github.com/xlwings/xlwings/issues/1001
so closing this as a duplicate
