### ISSUE TITLE
pywintypes.com_error: (-2147352573, '找不到成员。', None, None)

### ISSUE THREAD

**Issue by MorphineBlue** [xlwings/xlwings#2281]
#### Describe your issue (incl. Traceback!)

```python
# my traceback:
Traceback (most recent call last):
  File "E:\SouceCode\Python_project\SD电商仓文员快捷模板Dev\Version-005\依赖\xlwingsForWPS.py", line 23, in <module>
    Learn()
  File "E:\SouceCode\Python_project\SD电商仓文员快捷模板Dev\Version-005\依赖\xlwingsForWPS.py", line 17, in Learn
    wb.save(r'../输出文件/工作簿1.xlsx')
  File "C:\Users\Aorphine\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\xlwings\main.py", line 1156, in save
    self.impl.save(path, password=password)
  File "C:\Users\Aorphine\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\xlwings\_xlwindows.py", line 891, in save
    self.xl.SaveAs(
  File "C:\Users\Aorphine\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\xlwings\_xlwindows.py", line 121, in __call__
    v = self.__method(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aorphine\AppData\Local\Temp\gen_py\3.11\00020813-0000-0000-C000-000000000046x0x1x9.py", line 46813, in SaveAs
    return self._oleobj_.InvokeTypes(3174, LCID, 1, (24, 0), ((12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (3, 49), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17)),Filename
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.com_error: (-2147352573, '找不到成员。', None, None)

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# my code:
import xlwings as xw
from win32com.client import DispatchEx, Dispatch


_WPSxl = xw._xlwindows.COMRetryObjectWrapper(Dispatch("ket.Application"))
_WPSimpl = xw._xlwindows.App(visible = False, add_book = True, xl = _WPSxl)

def OpenApp():
	return xw.App(visible = True, add_book = True, impl = _WPSimpl)

def Learn():

	app = OpenApp()

	wb = app.books.add()

	wb.save(r'../输出文件/工作簿1.xlsx')
	wb.close()
	app.quit()

	pass

Learn()

```

## my issue
#A few days ago, I tried to use xlwings to operate xlsx files in the environment where Kingsoft WPS was installed, but the operation process was not very smooth. When I created the App object for the first time, an error occurred, forcing me to modify the 'excel.application' parameter to the 'ket.application' parameter, so that although the App object can be created normally and the workbook can be opened, after this setting , the workbook becomes unable to call book.save() or book.save(FullFileName). I can't solve this problem.
#If you are wondering why I don't uninstall WPS and use office excel instead, then I can only say that this is an office automation tool for a friend, and only WPS is installed on his computer, and there are some small functions on WPS Let him use it very smoothly, so he is unlikely to uninstall WPS. So is there a solution only at the code level?

```
#there is the 金山WPS’s Download link:
https://www.wps.com/home/
```

**Comment by MorphineBlue** [comment]
It's free, and I'm using the free version, although he has a paid enterprise version

**Comment by fzumstein** [comment]
xlwings doesn't support WPS, only Excel and Google Sheets, so I am closing this issue. There were other who tried their luck, maybe you find a solution in the closed issues: https://github.com/xlwings/xlwings/issues?q=is%3Aissue+wps+is%3Aclosed
