### ISSUE TITLE
Non commercial polyform ?

### ISSUE THREAD

**Issue by delassio** [xlwings/xlwings#2282]
Hello my question is about use of software in internal business only, is that possible and covered with actual license

**Comment by fzumstein** [comment]
* All the functionality that doesn't ask for a license key is covered by the BSD 3-clause open source license and can be used for everything, including internal business.

* Only the functionality that requires you to use a license key (such as xlwings Server or xlwings Reader) is governed by the polyform noncommercial license or the xlwings PRO license. Using it in a business is a commercial activity, so you can't use it under the polyform noncommerical license but would have to get an xlwings PRO license.
