### ISSUE TITLE
Conditional Formatting

### ISSUE THREAD

**Issue by dkanze** [xlwings/xlwings#2285]
#### Describe your issue 
I am looking to port my xlswriter code to xlwings.  What I cannot find in xlwings is conditional formatting, formulas, and dropdowns.
Are these available?  If not, can they be added?

Thanks
Dan

```

**Comment by fzumstein** [comment]
Hi Dan! Conditional formatting and dropdowns are indeed not natively available. Not sure about formulas though, see https://docs.xlwings.org/en/latest/api/range.html#xlwings.Range.formula

In that sense, the usual applies: yes, they can be implemented and you can workaround it for now by following these instructions (it's not that easy on macOS though):

* https://docs.xlwings.org/en/latest/missing_features.html
* For macOS, the following may also help: https://github.com/xlwings/xlwings/blob/main/DEVELOPER_GUIDE.md#macos
* For dropdown via data validation: https://github.com/xlwings/xlwings/issues/1446

**Comment by dkanze** [comment]
Thank you for the suggestions.  I enjoy using xlwings.
Dan

Sent from AT&T Yahoo Mail on Android 
 
  On Tue, Jun 20, 2023 at 10:23 AM, Felix ***@***.***> wrote:   


Hi Dan! Conditional formatting and dropdowns are indeed not natively available. Not sure about formulas though, see https://docs.xlwings.org/en/latest/api/range.html#xlwings.Range.formula

In that sense, the usual applies: yes, they can be implemented and you can workaround it for now by following these instructions (it's not that easy on macOS though):
   
   - https://docs.xlwings.org/en/latest/missing_features.html
   - For macOS, the following may also help: https://github.com/xlwings/xlwings/blob/main/DEVELOPER_GUIDE.md#macos
   - For dropdown via data validation: #1446

**Comment by dkanze** [comment]
Thank you for the information.
