### ISSUE TITLE
Docker Error

### ISSUE THREAD

**Issue by baserc** [xlwings/xlwings#2286]
#### OS (e.g. Windows 10 or macOS Sierra)
Docker Desktop in Windows 10 Machine
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Latest
#### Describe your issue (incl. Traceback!)

AttributeError: 'NoneType' object has no attribute 'apps'

Hello,

I have set it up a xlwings Docker environment with Python Flask App but unfortunately I can not run it.

```python

# ----------------- Flask (main.py) -------------
import os
from flask import Flask, make_response, request, jsonify
from redis import Redis
from rq import Queue
from server.excel_worker import run_excel_macro

app = Flask(__name__)
redis = Redis('redis', 6379)
q = Queue('excel_tasks', connection=redis)

@app.route('/add-task', methods=['POST'])
def create_task():
    json = request.json
    absolute_path = os.path.dirname(__file__)
    filename = os.path.join('excel-file', 'excel-file.xlsm')
    full_path = os.path.join(absolute_path, filename)
    task = q.enqueue(run_excel_macro, full_path, 'Macro1', json)
    data = {'message': 'Task Created', 'task_id': task.get_id()}
    return make_response(jsonify(data), 201)

@app.route("/tasks/<task_id>", methods=["GET"])
def get_status(task_id):
    task = q.fetch_job(task_id)
    if task.is_queued:
        response_object = {
            "data": {
                "task_id": task.get_id(),
                "task_status": task.get_status(),
                "task_result": task.return_value(),
            },
        }
        return jsonify(response_object)
    if task.is_started:
        response_object = {
            "data": {
                "task_id": task.get_id(),
                "task_status": task.get_status(),
                "task_result": task.return_value(),
            },
        }
        return jsonify(response_object)
    elif task.is_finished:
        return jsonify({'result': task.return_value()})
    else:
        return jsonify({"status": "error"})

if __name__ == '__main__':
    app.run(host='0.0.0.0')

# ----------------- Excel Worker-------------
def run_excel_macro(filename, macro_name, variable_dict):
   # Setting some parameters from variables
    name = variable_dict['name']
    surname = variable_dict['surname']
    # Set Some more
    # Run Excel macro using xlwings
    xw.App().visible = False -> Here makes the problem
    wb = xw.Book(filename)
    sheet1 = wb.sheets[0]
    # Write some values in Excel Sheet
     sheet1.range('A1').value = name
     sheet1.range('A2').value = surname
    macro = wb.macro(macro_name)
    # Run Macro 
    macro()
     # Get Calculation of Macro and send result
    result = {
      ... calculation result
    }
    wb.save()
    wb.close()
    return result

# -----------------Dockerfile-------------
FROM python:3.9
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
EXPOSE 5000
CMD ["python", "main.py"]
# -----------------Docker-Compose-------------
version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/redis

  flask-app:
    image: app-image
    container_name: flask-app
    restart: always
    build: app
    ports:
      - '5000:5000'
    depends_on:
      - redis

  worker:
    image: app-image:latest
    depends_on:
      - redis
    command: rq worker excel_tasks --url redis://redis:6379
    links:
      - redis

```

Can you please help me about that?

**Comment by baserc** [comment]
Hello @fzumstein so I need to buy the pro version of this library right?

**Comment by fzumstein** [comment]
Well, it depends: PRO is free for non-commercial use, see https://docs.xlwings.org/en/latest/license.html.
In a commercial context you can get a free trial license to check if the PRO functionality actually solves your use case: https://www.xlwings.org/trial

**Comment by baserc** [comment]
In order to test it, I have tried to install and added 'xlwings[pro]' in my requirements.txt and 
.env file with XLWINGS_LICENSE_KEY=noncommercial 
but I am still getting 'The interactive mode of xlwings is only supported on Windows and macOS. On Linux, you can use xlwings Server or xlwings Reader.' can you help me with that?

**Comment by fzumstein** [comment]
Note that the [pro] option isn't required anymore these days. 

xlwings on Linux/Docker doesn't support xw.App(), so you'll need to take that away. Instead, follow the intro/quickstart on either of those products:

* xlwings Reader: https://docs.xlwings.org/en/latest/pro/reader.html
* xlwings Server: https://docs.xlwings.org/en/latest/pro/server/server.html

**Comment by baserc** [comment]
@fzumstein First of Felix thank you for your help!

I have added 'RUN xlwings license update -k noncommercial' in my Dockerfile and also read the both documentation.

I have one question:

If I use a reader as following : 

```python
 with xw.Book(filename, mode='r') as wb:
        sheet1 = wb.sheets[0]
        sheet1.range('A1').value = name -> I can not set an item to workbook
        sheet1.range('A2').value = surname

       macro = wb.macro(macro_name)
        # Run Macro 
        macro()
         # Get Calculation of Macro and send result
        result = {
          ... calculation result
        }
        wb.save()
        wb.close()
        return result
```

or if I use a server 

```python
   with xw.Book(json=request.json) as book:  -> I dont know what to send in request.json in order to open the excel file
      sheet1 = wb.sheets[0]
        sheet1.range('A1').value = name -> I can not set an item to workbook
        sheet1.range('A2').value = surname

       macro = wb.macro(macro_name)
        # Run Macro 
        macro()
         # Get Calculation of Macro and send result
        result = {
          ... calculation result
        }
        wb.save()
        wb.close()
        return result
```
Can you help me again?

**Comment by fzumstein** [comment]
I think xlwings may not be the package you're looking for, have you tried OpenPyXL instead? Having said that:

* xlwings Reader is, as the name suggests, only a reader, so you can't write. See also limitations: https://docs.xlwings.org/en/latest/pro/reader.html#limitations
* xlwings Server: the json payload comes from one of the clients (VBA, Office Scripts, Office.js, or Google App Script): Go through the tutorial: https://docs.xlwings.org/en/latest/pro/server/server.html

**Comment by baserc** [comment]
Hello Felix,

I guess the openpyxl library does not support running Excel macros. openpyxl is a library for reading, writing, and manipulating Excel files (.xlsx format), but it does not have built-in support for executing macros.

To run Excel macros from Python, I need to use a library like pywin32 or xlwings, which provide access to the Excel object model and allow you to interact with Excel's COM interface but also I need to use Redis or any other queue to get requests from web server to put into queue. Then I can async worker can run the requests and send the results back. But I can not use both of these libraries with Linux Docker container.

Thank you for your time, if you have any ideas I am open for it.

**Comment by fzumstein** [comment]
So xlwings Server can do the Excel -> Python -> Excel roundtrip including calling macros, but it can't do Python -> Excel, i.e. you can't have a script in your Docker container and run this independently.

Maybe one day we'll add support for automation via Microsoft's Graph API, but that would require you to store the file on OneDrive/SharePoint and I don't think it allows to call VBA macros.

Maybe writing OfficeScripts instead of VBA and calling it via PowerAutomate fits your bill, not sure...

I am closing this as I think your use case (Python in Docker -> Excel without triggering it from Excel) isn't supported.
