### ISSUE TITLE
Standalone installation returns error "Sub or Function not defined"

### ISSUE THREAD

**Issue by Hemming01** [xlwings/xlwings#2290]
I have installed xlwings as a standalone module with ```xlwings quickstart hello --standalone```. That works fine and creates hello.py and hello.xlsm. When I run the SampleCall() in Module1 I get an error saying "Sub or Function not defined" for 'ConvertToUtc'. I thought this would be able to run straight out of the box. Is there some other dependency I'm missing? Or any other thing I need to add/do?

OS: Windows 10
python: 3.11
Excel: Microsoft 365 for enterprise
xlwings: 0.30.9

**Comment by fzumstein** [comment]
Yeah, sorry about that, that's actually a bug and the same cauas #2118.

To fix this, open the xlwings module and delete everything below and including the `Function GetAzureAdAccessToken`.

There's also the `Sub SampleRemoteCall` that you'll have to remove in Module1.

**Comment by Hemming01** [comment]
Thanks a lot! I tried searching for the error but couldn't it anywhere.

I tried deleting the GetAzureAdAccessToken function as well, thinking that shouldn't be needed anyway :) But I should have removed SampleRemoteCall as well.

**Comment by Hemming01** [comment]
FYI. I had to delete three or four other functions where some objects weren't defined. But after that it runs :)

**Comment by Hemming01** [comment]
@fzumstein, sorry for asking again regarding UDFs. Can those be run standalone as well?
