### ISSUE TITLE
table.update(df, index=False) overwrites table instead of updating it

### ISSUE THREAD

**Issue by Matt-Greer** [xlwings/xlwings#2294]
#### Code sample:
I included all the imports in case I'm doing something wrong...

```python
import pandas as pd
import xlwings as xw
from xlwings.constants import LookAt
from xlwings.main import Table, Range

def update_table(df: pd.DataFrame) -> None:

    wb = xw.books.active
    sheet = wb.sheets['Sheet1']
    
    # Get the existing data range of the table
    tbl: Table = sheet.tables['tbl1']
    tbl.update(df, index=False)


```

**Comment by Matt-Greer** [comment]
Thank you for the quick response!

There's two sheets in the workbook.  `pokemon_data` is the structured excel table.  `sheet1` is a backup of that data

The program will attempt to add one entry to the table; it overwrites the table.  To restore the table, just copy the data from Sheet1 to the table on the `pokemon_data` worksheet.

python program:
```py
import xlwings as xw
from xlwings.main import Book, Sheet
import pandas as pd


filename: str = "sample_data.xlsx"
sheetname: str = "pokemon_data"
tablename: str = "tblData"

wb: Book = xw.books.active
ws: Sheet = wb.sheets[sheetname]

data = {
    '#':[721],
    'Name':['Volcanion'],
    'Type 1':['Fire'],
    'Type 2':['Water'],
    'HP':[80],
    'Attack':[110],
    'Defense':[120],
    'Sp. Atk':[130],
    'Sp. Def':[90],
    'Speed':'[70]',
    'Generation':[6],
    'Legendary':[True]
    }

df = pd.DataFrame(data)

for ws in wb.sheets:
    for tbl in ws.tables:
        if tbl.name == tablename:
[sample_data.xlsx](https://github.com/xlwings/xlwings/files/11900176/sample_data.xlsx)

            tbl.update(df, index=False)
```

**Comment by fzumstein** [comment]
So from the way you describe it, this is indeed the purpose of `table.update`: to replace the whole table with a new DataFrame. To append a row to an existing table, you can simply insert a row/data at the end of the existing table and by default Excel extends the table by that new row.

**Comment by Matt-Greer** [comment]
I understand.  I very much appreciate you taking the time to help me better understand the functionality of `table.update`; thank you.

If I'm adding something to an existing table, would you agree the "best" methodology would be to grab a dataframe of the existing table and `pd.concat` with the new dataframe and then run `table.update`.

I can see where if I had two structured tables in Excel, appending one table to the other wouldn't require `table.update`, as it's as simple as:

```py
def append_tables():

    wb = xw.books.active
    ws = wb.sheets("Sheet1")
    tbl1: Table = ws.tables['Table1']
    tbl2: Table = ws.tables['Table2']

    tbl_final: list = tbl1.data_body_range.value + tbl2.data_body_range.value
    tbl2.data_body_range.value = tbl_final
```
That's pretty nifty actually.


But then with dataframes, I tried to write a function to do this; does this look like what you'd expect for such an operation?

```py
def append_to_table(df1: pd.DataFrame) -> None:

    wb = xw.books.active
    ws: Sheet = wb.sheets("Sheet1")
    tbl: Table = ws.tables['Table1']

    existing_data_range: Range = tbl.data_body_range

    # Check if the table is empty (for example, it's a template and you're starting from scratch):
    if existing_data_range is None:
        tbl.update(df1, index=False)
    else:
        # Get a dataframe of the existing table data
        data: list = tbl.data_body_range.value
        headers: list = tbl.header_row_range.value
        df2 = pd.DataFrame(data=data, columns=headers)

        # Merge the two dataframes
        df_final: pd.DataFrame = pd.concat([df1, df2], ignore_index=True)

        # Update the table in Excel
        tbl.update(df_final, index=False)
        
```

**Comment by fzumstein** [comment]
You can probably make it a little easier:

```python
tbl = ws.tables['Table1']
df = tbl.range.options(pd.DataFrame).value
```

**Comment by Matt-Greer** [comment]
I don't know if you'll see this comment, but your suggested method doesn't create an index which causes data to get dropped when I run the `pd.concat`, so I have to do this instead:

```py
        df2: pd.DataFrame = tbl.range.options(pd.DataFrame).value
        df2.reset_index(drop=False, inplace=True)
```

I haven't been able to figure out if there's a way to create an index using `.options(pd.DataFrame)`.  Can that be done?  It's only one extra line of code so really, no big deal, but I am curious.

**Comment by fzumstein** [comment]
You're probably looking for the index option: https://docs.xlwings.org/en/latest/datastructures.html#pandas-dataframes

**Comment by Matt-Greer** [comment]
Took a bit of trial and error but this looks like the code I'd need to use:

```py
df2 = tbl.range.options(pd.DataFrame, index=0).value
```

I went from here: https://docs.xlwings.org/en/latest/datastructures.html#pandas-dataframes
to here: https://docs.xlwings.org/en/latest/converters.html#converters

I was confused about the meaning of this statement fom the 2nd linked page:
> When reading, it expects the number of index columns shown in Excel.

This phrasing implies there are possibly multiple index columns coming from the range in Excel.

**Comment by fzumstein** [comment]
when you provide `index=2`, it takes the first 2 cols and turns it into a hierarchical index if I remember correctly off the top of my head.
