### ISSUE TITLE
Xlwings some times does not save file

### ISSUE THREAD

**Issue by joaomarrey** [xlwings/xlwings#2309]
#### xlwings 0.30.10, Office 365, Python 3.10.9

I have been using xlwings to edit some excel files in python, but i am having trouble for one specific file. After I am done editing it, I pass a command for python to save and close that workbook, but it closes the file before it´s done saving, I have used the following command to remediate the issue: time.sleep(2), but I understand that this is not very efficient, nor is it dinamic, and many times, even with that, the file closes before saving. I now that I could increase the seconds in the sleep command, but I would much rather prefer some code that waits for the save to finish for it to close.

I have looked around this website and many others and could´nt find an answer, people only mention ways for python to wait for some calculation to be complete in order for it to get some value, but they don´t mention wating for the save to close the file. My code is structured as follows:

```python
import xlwings as xw
import time

app = xw.App()

excel = xw.Book("file path")
excel_sheet = excel.sheets("sheet name")

##This is just an example of changing something in the file
excel_sheet.range("A1").value = 123

excel.save()
time.sleep(2)
excel.close()
app.quit

```

I have also tried using a context manager, but without success, here is my code:

```python
import xlwings as xw
import time

app = xw.App()

with xw.Book("file path") as excel: 
  excel_sheet = excel.sheets("sheet name")

  ##This is just an example of changing something in the file
  excel_sheet.range("A1").value = 123

  excel.save()

app.quit

```

**Comment by fzumstein** [comment]
I would need an Excel file to replicate this consistently. You could try out if `excel.api.Close(SaveChanges=True)` solves this.

**Comment by joaomarrey** [comment]
I have tried it and tested a couple times, but I can´t confirm that it will always work. Nonetheless, thanks for the help, and do you know why the code I was using before failed? I think it´s always good for me to understand what I am doing haha

**Comment by joaomarrey** [comment]
Well it just failed again

**Comment by fzumstein** [comment]
In that case there's nothing I can do as this would be the official solution, so I'll close this issue. I don't there's anything you did wrong, seems like a bug somewhere. Not sure though where as I don't recall this having come up before.
