### ISSUE TITLE
How to set the color of individual letters on a Mac? 

### ISSUE THREAD

**Issue by frank7343** [xlwings/xlwings#2313]
#### xlwings 0.23.0, Python 3.11.4
Is it possible to set the color of individual letters on a Mac? 
It seems "range.api.GetCharacters" doesn't work on MacOS with appscript. I got the following error message:

AttributeError: Unknown property, element or command: 'GetCharacters'

Your help would be highly appreciated.
```python
#  traceback here
  File ~/miniconda3/envs/spyder-env/lib/python3.11/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/Downloads/_work/_python/temp.py:10
    ws.range('A1').api.GetCharacters(1,3).Font.Bold= True

  File ~/miniconda3/envs/spyder-env/lib/python3.11/site-packages/aeosa/appscript/reference.py:598 in __getattr__
    raise AttributeError("Unknown property, element or command: {!r}".format(name)) from e

AttributeError: Unknown property, element or command: 'GetCharacters'
```

#### code sample to reproduce the issue 

```python
import xlwings as xw
from appscript import k
wb = xw.Book('test.xlsm')
ws = wb.sheets[0]
ws['A1'].value = 'testdata'
ws.range('A1').api.GetCharacters(1,3).Font.Bold= True
```

**Comment by fzumstein** [comment]
Well, while `characters` is now officially supported by xlwings (see: https://docs.xlwings.org/en/latest/api/characters.html), there's a bug in AppleScript that prevents it from working properly on macOS: https://answers.microsoft.com/en-us/msoffice/forum/all/applescript-and-excel-problem/6e5a50b1-6209-4fbf-91f4-6d6674f1e488

So you're best bet is to create a VBA macro and call it from Python via https://docs.xlwings.org/en/latest/api/book.html#xlwings.Book.macro

Closing this as it's a bug in a dependency.
