### ISSUE TITLE
xlwings removes leading zeroes from dataframe columns 

### ISSUE THREAD

**Issue by elijackson97** [xlwings/xlwings#2322]
Python 3.9, xlwings 0.24.9, 

Hey guys, first post here so sorry if anything needed isn't included. 

I'm trying to write a pandas dataframe to an existing sheet within an excel file that I have. When I run the following code, it copies the dataframe successfully into the sheet, but I am having an issue with leading zeroes in a few of my columns in my dataframe being dropped. These zeroes are important as they're used in other calculations in the same sheet. Does anyone know a workaround that can prevent the zeroes from being dropped?

```python
app = xw.App()
wb = xw.Book('path/to/file.xlsm')
ws = wb.Sheets('PyData')

ws.range('C2').options(index=False, header=False).value = dfAll (my dataframe)

```

The dataframe itself has the leading zeroes in it, but when xlwings writes it, they go away. I initially tried using the pandas to_excel to write to this sheet but every time it would corrupt my target excel file. to_excel would work fine when copying to a new sheet, and I could use a VBA macro to import this data, but I want to remove this step in the process. Could I potentially convert the column to a string column and avoid the dropping that way? I'm not sure if that would even matter with pandas dataframes. Does anyone have any advice? 

edit: I tried casting my dataframe columns with leading zeroes to a string, and that did not fix this error when copying to an excel file. 

below is the code I tried when trying to use to_excel to update the excel sheet data. This is what corrupted my file. If you guys could point me to why this is corrupting my excel, I could probably just use pandas to copy the necessary data. 

```
with pd.ExcelWriter('path/to/file.xlsm') as writer:
              dfAll.to_excel(writer, sheet_name=PyData, index=False, header=False)
```

**Comment by fzumstein** [comment]
duplicated of https://github.com/xlwings/xlwings/issues/1793

**Comment by elijackson97** [comment]
> duplicate of #1793

This resolved it, thank you. The column already showed as formatted as text but when I set that again it seemed to fix the issue.
