### ISSUE TITLE
In MacBook, with Xlwings, Can the data update real time?

### ISSUE THREAD

**Issue by jenish99** [xlwings/xlwings#2345]
#### Describe your issue (incl. Traceback!)

I am windows user and using xlwings for algo trading purpose.

I have a script which write live data to one excel sheet (suppose sheet name 'LiveData') of workbook, and all other sheets relevant formulas in Excel file get executed as per live written data.

I have tried this method with Linux, but it is not possible there.

Is this the way of working, works with MacBook?

I would like to buy a MacBook, but don't have anyone in nearby friends/family. If this doesn't works, then buying MacBook will not be useful for me.

Regards Jenish.
```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
Yes, writing a value to a cell works on macOS, too.

**Comment by jenish99** [comment]
Thank you for confirming.
