### ISSUE TITLE
Could not activate Python COM server, hr = -2147221164 1000

### ISSUE THREAD

**Issue by GreekQuant** [xlwings/xlwings#2346]
#### Versions:

1. xlwings == 0.29.1
2. Excel == Office 365 Apps for enterprise Version 2309
3. Python  == 3.11.5
4. Work laptop not personal

Hi Felix I am facing the issue as stated in the title of this post. 

This happens when I try to run ImportPythonUDFsToAddin(). It seems as if there is runing something multiple times and then the error hits. 

The context is that I have built a .xlam using the xlwings command line helper, a .py where the xlwings udfs can be imported from and I have also configured the configuration worksheet according to the guidelines on xlwings website. 

To be honest I have read similar issues here and I have checked most of the troubleshooting recommendations. Do you think that the fact that my username has a '.' in it would be the problem? What I mean is that it is of the form:

- my.username

I have checked the versions, the .dlls, the path where the python file is , the path where the environment is, the path where the python.exe is ...dont know what else to do.

Do you think there are other things I am missing?

**Comment by fzumstein** [comment]
You should get more details when activating the `Show Console` config.

**Comment by GreekQuant** [comment]
Figured it out - False alarm! 


Thank you Felix
