### ISSUE TITLE
Shape Objects, Grouping and Textbox fill color

### ISSUE THREAD

**Issue by VBlackie** [xlwings/xlwings#2352]
#### Versions of xlwings, Excel and Python (xlwings:030.10, Office 365, Python 3.11.4)

Hello! I was looking at the 'Missing Features' in the xlwings doc and wanted to do a request. I am fairly new to xlwings and any recommendations to this request or overall are welcomed.
Context; I am attempting to build an excel file comparer that highlights differences between then, sort of a 'changes done to previous iteration' review comparer.

I am comparing two excel files which have several sheets but the information on them is not very neatly structured. It has unnamed tables, some parts of the table are a subtable but you could only know because someone told you so, as well as images and textboxes that are in several places over a sheet. It's a big spaghetti, however it does have some logical structure.

# Request/Issue 1: Adding a method for fill color for textboxes.
I was able to track down _similarities_ between workbook_old and workbook_new using

```
wb_old = xw.Book('Book1.xlsx')
wb_new = xw.Book('Book2.xlsx')
sheet_old = wb_old.sheets[sheet_old]]
sheet_new = wb_new.sheets[sheet_new]

def find_object_names(sheet)
    object_names = [{'name': shape.name, 'text': shape.text} for shape in sheet.shapes if shape.text is not None]
    return object names

objects_old = find_object_names(sheet_old)
objects_new = find_object_names(sheet_new)
for object_iterator_new in objects_new:
    for object_iterator_old in objects_old:
        if object_iterator_new['text'] == object_iterator_old['text']:
           sheet_new.shapes[object_iterator_new['name']].font.color = (0, 255, 0)
           break
```

Originaly I wanted to literaly highlight the similarities. I was able to find the option for font.color but unfortunately I wasn't able to find a method for the textbox itself. In cells I was using sheet.range('A1').color = (R,G,B), but unfortunately it doesnt work that way with shapes. I tried using the api method (as in example of missing features 

> "sheet['A1'].api.WrapText = True"

) and looked for the documentation however I gotta admit my knowledge in that regard is quite lacking and the amount of info was overwhelming enough that I found myself lost. I was able to trackdown the documentation but wasn't able to see how to use it, or what methods were available. Maybe If you could also point me in the right direction how to use the .api to find what I am looking for I would be so grateful. I would love to learn that.

**Comment by fzumstein** [comment]
Hi and thanks for opening this issue! Please note that it would be better to open a separate issue for each topic.

One way to find the correct `.api` syntax is to use the VBA recorder and then search for more documentation on the official VBA docs. In your case, you should end up somewhere here, e.g.: https://learn.microsoft.com/en-us/office/vba/api/excel.shape.fill

Assigning a color on an api object should be doable like this:

```python
import xlwings as xw
from xlwings.utils import rgb_to_int

mysheet = xw.sheets.active
mysheet.shapes[0].api.Fill.ForeColor.RGB = rgb_to_int((50, 50, 50))
```

**Comment by VBlackie** [comment]
Thank you! It works like a charm. I will try to play around with the VBA recorder and see what else I can find. Regarding the other issue I have, should I edit this post into two to ask for assistance on the other issue? If not, is there a way to access the info in the subgroup to fetch the textbox data inside the group? Thank you again

**Comment by fzumstein** [comment]
yes, opening a separate issue would be better. I don't have any experience with grouped items, but maybe someone else has some ideas there.
