### ISSUE TITLE
Xlwings error 53

### ISSUE THREAD

**Issue by barungh** [xlwings/xlwings#2355]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10 
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings version 0.30.12
#### Describe your issue (incl. Traceback!)
![image](https://github.com/xlwings/xlwings/assets/12285528/4d427b10-dd84-42b0-bf73-5c651c157a3a)

###  
![image](https://github.com/xlwings/xlwings/assets/12285528/0939961d-e45b-4e7e-83df-6c30a35558f7)

**Comment by fzumstein** [comment]
your add-in version is out of sync with your python package. run `xlwings addin install` on a command prompt to fix this.
