### ISSUE TITLE
Weird interaction with Solver.

### ISSUE THREAD

**Issue by Andrewnolan13** [xlwings/xlwings#2369]
#### OS
Windows 10
#### Versions of xlwings, Excel and Python
xlwings-0.30.13
Python-3.12.1
Excel-Microsoft® Excel® for Microsoft 365 MSO (Version 2310 Build 16.0.16924.20054) 64-bit 
#### Describe your issue (incl. Traceback!)

*** TLDR. Get an error in code when trying to save a workbook. Typing 'wb' into console prints <Book 'SOLVER.XLAM'> instead of the actual name of the book. 

I've written code to automate excel processes in work. 

The idea of the code is as follows:
Go to a file from last month.
Open it. Update data sources and inputs.
Save a copy under a new name (following a naming convention based on what month it is)

The code works perfectly on my machine.

When I try to run it on my colleagues machine, it works for all files but one. The code goes something like:
```python
import xlwings as xw

old_filepath = 'A:\\somewhere\\January\\Excel_file 2023_01.xlsm'
new_filepath = 'A:\\somewhere\\February\\Excel_file 2023_02.xlsm'

wb = xw.Book(old_filepath, update_links = False)

# do stuff to wb

wb.save(new_filepath)
wb.close()
```

The error occurs when I try to do stuff to the workbook or save it. The error doesn't explain much, it just says SaveAs method failed.

After messing around with this, I noticed that immediately after the line wb = xw.Book(old_filepath,update_links = False) is run, if I enter 'wb' into the console/cell I get.

<Book 'SOLVER.XLAM'>

When the output should be

<Book 'Excel_file 2023_01.xlsm'>

For some reason, it is looking for SOLVER.XLAM. I know this is most likely an issue with the solver add-in on my colleagues machine but I couldn't find anything similar online so I decided to mention it here in the hopes that the devs have encountered/heard of this before. Also, it only happens with one file in particular, every other file works perfectly. 

```python
# Your traceback here

[d:\Program](file:///D:/Program) Files\Python312\Lib\site-packages\xlwings\main.py in ?(self, path, password)
   1159         """
   1160         if path:
   1161             path = utils.fspath(path)
   1162         with self.app.properties(display_alerts=False):
-> 1163             self.impl.save(path, password=password)

[d:\Program](file:///D:/Program) Files\Python312\Lib\site-packages\xlwings\_xlwindows.py in ?(self, path, password)
    890         elif path:
    891             # Save under new name/location
    892             alerts_state = self.xl.Application.DisplayAlerts
    893             self.xl.Application.DisplayAlerts = False
--> 894             self.xl.SaveAs(
    895                 os.path.realpath(path), FileFormat=file_format, Password=password
    896             )
    897             self.xl.Application.DisplayAlerts = alerts_state
...
  46833                         , FileFormat, Password, WriteResPassword, ReadOnlyRecommended, CreateBackup
  46834                         , AccessMode, ConflictResolution, AddToMru, TextCodepage, TextVisualLayout
  46835                         , Local, WorkIdentity)

com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Excel', 'SaveAs method of Workbook class failed', 'xlmain11.chm', 0, -2146827284), None)
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python

# Your code here

import xlwings as xw

old_filepath = 'A:\\somewhere\\January\\Excel_file 2023_01.xlsm'
new_filepath = 'A:\\somewhere\\February\\Excel_file 2023_02.xlsm'

wb = xw.Book(old_filepath, update_links = False)
wb.save(new_filepath) #<--- Error occurs here as it is trying to save 'SOLVER.XLAM' as new_filepath.


```

**Comment by fzumstein** [comment]
I can't really make sense of this, no. Is there anything special about that one file where this happens?

**Comment by Andrewnolan13** [comment]
My bad if I did a poor job of explaining the problem.

No, there is nothing special about it - it’s simply just an xlsm file. The
error doesn’t happen on my machine, just my colleague’s machine.

**Comment by fzumstein** [comment]
> When I try to run it on my colleagues machine, it works for all files but one.

But is it always the same file?

**Comment by Andrewnolan13** [comment]
Yes it is. We have a shared drive.

**Comment by fzumstein** [comment]
Yeah no, nothing that comes to mind given that it works on your machine. Maybe try to export the content of the workbook into a new one that you create from scratch and try again. Or run office repair on your colleagues' machine.

**Comment by Andrewnolan13** [comment]
Will try that tomorrow, thank you

**Comment by fzumstein** [comment]
Ok, I'll close this then. Somebody else just ran into a similar issue now -- will post an update here if we find something.
