### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'apps'

### ISSUE THREAD

**Issue by lijie20121990** [xlwings/xlwings#2370]
windows 10
Python 3.9.13 (tags/v3.9.13)
xlwings version: 0.30.13

I try to build a new Excel file by use the below code, but it fails as below trace.

# Your code here
>>> import xlwings as xw
>>> app = xw.App(visible = True)
Traceback (most recent call last):
  File "<pyshell#13>", line 1, in <module>
    app = xw.App(visible = True)
  File "C:\Users\LiJie\AppData\Roaming\Python\Python39\site-packages\xlwings\main.py", line 310, in __init__
    self.impl = engines.active.apps.add(
AttributeError: 'NoneType' object has no attribute 'apps'

**Comment by fzumstein** [comment]
do you have pywin32 installed?
