### ISSUE TITLE
Your Conda version seems to be too old

### ISSUE THREAD

**Issue by Gerry84** [xlwings/xlwings#2375]
Windows 10
Office 365
xlwings version: 0.29.1
Python 3.11.5
conda 23.7.4

Hi, I got a new laptop and installed xlwings, anaconda to run my previously working codes. For some reason I'm receiving the following error message when trying to run my python code via a VBA script which has and still is working perfectly fine on my old laptop:

"Your Conda version seems to be too old for the Conda settings. Use the Interpreter setting instead."

The VBA code I'm running and giving me the issue is:
RunPython ("import pythonscript")

As mentioned, the code is running fine on my old laptop but I'm not sure what is causing the issue on my new laptop.

Thanks for your help!
Gerald

**Comment by fzumstein** [comment]
Have you properly configured the add-in to point the Conda Path to where the (ana)conda root folder is? It's best to run `xlwings config create --force` from the correct conda Prompt to do that automatically.

**Comment by Gerry84** [comment]
I thought I did (based on my previous setup). The command just resolved the issue but it changed the Conda path from previously: C:\Users\User\anaconda3 to C:\Users\User\AppData\Local\anaconda3\condabin\..
Thanks for your quick help!

**Comment by fzumstein** [comment]
If I understand correctly, it's resolved? Closing this issue then.
