### ISSUE TITLE
File not found: xlwings64-0.30.13.dll

### ISSUE THREAD

**Issue by skissss** [xlwings/xlwings#2376]
I have just started with xlwings in excel.

I successfully went through installation of the package and the add in.

Then I created the .py file for the hello world test and the equivalent vba code in an excel file and run. Happy days everything worked great.

I saved and closed the file. Two hours later I reopened and tried to rerun and got the following message:
Run-time error '53':
File not found: xlwings64-0.30.13.dll

I removed the add in and uninstalled and reinstalled xlwings but nothing changed.

**Comment by fzumstein** [comment]
Try to check if your antivirus has removed the file? It should be under the root of your Python installation. Run `where python` from a command or Anaconda prompt and check in the directory of the python.exe.

**Comment by skissss** [comment]
Not sure what deleted it but it was the fact that the .dll was not in the same directory as the python exe

**Comment by skissss** [comment]
Thanks for the suggestion.
Not sure what deleted it but it was the fact that the .dll was not in the same directory as the python exe
