### ISSUE TITLE
Issue while Copying data with empty cells excluding header row

### ISSUE THREAD

**Issue by bhaveshdodia** [xlwings/xlwings#2387]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows Server 2019 Standard

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Python 3.8.5
Microsoft Office Professional Plus 2016
xlwings 0.30.9

#### Describe your issue (incl. Traceback!)
I have a source file with blank/empty cells in between. It has a header. 

I want to only copy the data _**excluding**_ the header row. I'm using expand().api.Copy() to copy and then pasteSpecial to paste into a new workbook but it stops on finding an empty cells. I read it's expected behaviour. I'm trying alternatives using used_range but it also copies the header row. Reason for using pasteSpecial was to retain the formatting.

Is there a way to around this?

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
You can slice ranges, so when you do `mysheet.used_range[1:].copy()`, it will leave out the top row. Note that copy/paste special are natively available: https://docs.xlwings.org/en/latest/api/range.html#xlwings.Range.paste

**Comment by bhaveshdodia** [comment]
Thank you for the slice suggestion. That works. But does it overwrite the paste special properties. I'm using code -4163 and it seems to carry over the formatting as well. It overwrites the existing formatting.

**Comment by fzumstein** [comment]
You would need to paste a full reproducible code sample.

**Comment by bhaveshdodia** [comment]
I'm marking this issue as closed as I was able to paste just the values without carrying over any formatting using range.value = range.value

Thanks @fzumstein for the suggestion of using slices for the copying issue.
