### ISSUE TITLE
xlwings in pyinstaller app only generates error while same code in VSCode works

### ISSUE THREAD

**Issue by volkerwill** [xlwings/xlwings#2391]
#### OS (e.g. Windows 10 or macOS Sierra)
MacBook, Sonoma 14.3 (23D56)
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
appscript==1.2.5
et-xmlfile==1.1.0
lxml==5.1.0
openpyxl==3.1.2
psutil==5.9.8
xlwings==0.30.13

Python: 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Excel: Version 16.81 (24011420)

#### Describe your issue (incl. Traceback!)
Running the tiny sample code in VSCode works as expected. Building an executable using pyinstaller (pyinstaller --windowed --onefile --clean xlw.py --name test) generates below error. I hope this is just me but after trying many variants of the below sample I am at a loss.

```python
# Your traceback here
Traceback (most recent call last):
  File "xlw.py", line 54, in <module>
    test()
  File "xlw.py", line 49, in test
    with xw.App() as app:
         ^^^^^^^^
  File "xlwings/main.py", line 310, in __init__
AttributeError: 'NoneType' object has no attribute 'apps'
[33674] Failed to execute script 'xlw' due to unhandled exception: 'NoneType' object has no attribute 'apps'
[33674] Traceback:
Traceback (most recent call last):
  File "xlw.py", line 54, in <module>
    test()
  File "xlw.py", line 49, in test
    with xw.App() as app:
         ^^^^^^^^
  File "xlwings/main.py", line 310, in __init__
AttributeError: 'NoneType' object has no attribute 'apps'

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import xlwings
def test():
    with xw.App() as app:
        bookx = app.books.open(XLS)
        bookx.save()

test()
```

**Comment by fzumstein** [comment]
RunFrozenPython isn't officially supported on macOS, but there's this:
https://github.com/xlwings/xlwings/issues/1154

**Comment by volkerwill** [comment]
Apologies:
`XLS=/tmp/budget.xlsx`

**Comment by volkerwill** [comment]
Thank you!
