### ISSUE TITLE
Could not activate Python COM server, hr = -2147221164 1000

### ISSUE THREAD

**Issue by rutsyi** [xlwings/xlwings#2395]
#### OS (e.g. Windows 10 or macOS Sierra)
Win 10 v 10,0,19044 Build 19044

#### Versions of xlwings, Excel and Python
xlwings 0.30.13 ; addin got installed after so versions match.
python 3.12.2 but also same issue on another PC with Python 3.10
Excel click to run v 2108 (see attached)
![IMG_7614](https://github.com/xlwings/xlwings/assets/57928572/ca2dc568-d12e-44ef-827e-6118cb157753)

#### Describe your issue 
Something changed overnight for me (no office updates or anything like that, but my PC was rebooted -- maybe there were some delayed accumulated updates after all -- now any UDF call gives me a 1 min hang and then an error message 'Could not activate Python COM server'. Very typical to what other guys wrote before on the same issue.

My Excel is not from MS Store (I believe?) -- see the screenshot above please -- says 'click and run'. So should be good?

Quickstart project works when I press "Run main" -- gives the hello and bye strings no problem. But errors out when I click 'Import functions".

Trust centre - trust access to the VBA is a tick , so it's good.

Interpreter works - with interpreter path or without , everything runs to problem.

When press Show console when Importing functions  I see "excel server running .... , event loop on 22112" then the window auto-closes and I get my "Could not activate Pythin COM..." error.

Tried downshifting to 0.20.7 but didnt help. So I moved back to the latest version. Moreover, the issue started today when I was on version around 0.27xx (I dont remember exactly which one), so it's not a version issue for me. 

Any ideas? Next steps to test? Appreciate any help.
Cheers.
===

**Comment by fzumstein** [comment]
> Something changed overnight for me

This sounds like it could be a Windows Defender/Antivirus issue

**Comment by rutsyi** [comment]
> > Something changed overnight for me
> 
> This sounds like it could be a Windows Defender/Antivirus issue

Thanks for quick reply Felix. I will try to disable it and see how it goes. I will make sure to come back here and update.

**Comment by rutsyi** [comment]
UPDATE: it works now! So over the weekend indeed there was Office update pushed onto my PC. I broker xlwings apparently and even xlwings reinstall didnt help.
I reinstall whole Office. New Excel version is 2108 build 14326.20738 FYI.
The issue can be closed now. Exact reason for the failure unknown.

**Comment by rutsyi** [comment]
Closed.
