### ISSUE TITLE
xlwings - Issue when copying worksheet with PivotTable

### ISSUE THREAD

**Issue by bhaveshdodia** [xlwings/xlwings#2406]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows Server 2019 Standard

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Python 3.8.5
Microsoft Office Professional Plus 2016
xlwings 0.30.9

#### Describe your issue (incl. Traceback!)
I am working with a workbook with the sheets (Data & Pivot). Pivot sheet contains a Pivot table with data source from the 'Data' sheet.

We're using xlwings to write data to a new workbook with worksheet as Data. As a second step, I want to copy the Pivot as the second worksheet that references data in the new workbook['Data'] that I created. However, when I copy it over, it keeps the data source as _[Workbook1.xlsx]Data'!$A:$Y_

I'd like to be copied over with data range as _Data!$A:$Y_ as in the original source sheet.

One of the reason I don't want to add an additional step to correct the data source range is because worksheets may or may not contain pivots. I have read documentations for xlwings and open items if any, but no luck yet.

```python

Using below code to copy the worksheet:
source_wb.sheets['Pivot'].copy(after=new_wb.sheets['Data'], name='Pivot')

# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
Does it behave differently if you do it manually?

**Comment by bhaveshdodia** [comment]
I tried this manually. If I copy a worksheet in a new workbook, it still points to the same data source (previous wb). The way I tried it was Ctrl+C all the contents and Ctrl+V.

**Comment by fzumstein** [comment]
So it's the same behavior, correct? In this case, there isn't much we can do here as xlwings is just automating things so can't really change this.
