### ISSUE TITLE
VBA: Export to/Import from a subfolder

### ISSUE THREAD

**Issue by Orz-PX** [xlwings/xlwings#2431]
#### Describe your issue:

When using 'xlwings vba export', all modules are exported to the root folder where the workbook is kept. This makes file management very difficult when the project is large. 

I'd like to ask if the change below is possible: 
Add an option when exporting vba modules, creates a subfolder called "FileName.src" or something similar first, then export all modules into this newly created subfolder. Similarly add an option to import modules from this subfolder.

Thanks in advance!

**Comment by fzumstein** [comment]
You should be able to simply run `xlwings vba export` from that subfolder and the files will be exported there.

**Comment by Orz-PX** [comment]
Works perfectly! Thank you very much!
