### ISSUE TITLE
User Defined Functions (UDFs) not working

### ISSUE THREAD

**Issue by ADV1977** [xlwings/xlwings#2448]
#### Describe your issue:  Problem importing UDF functions
Hello all,

I am trying to execute some User Defined Functions but so far I am not able to do it and instead I get the message "Object required" as you can see below in the screenshot
<img width="966" alt="image" src="https://github.com/xlwings/xlwings/assets/171322007/7d54362e-6f06-4a5b-ba01-0301b6fa2254">

Both xlwings and are installed in the same folder, as you can also see below:

![image](https://github.com/xlwings/xlwings/assets/171322007/c7f19e76-7b9e-46f6-bfde-f877379d79dd)

And also both the python and excel files are in the same folder, see below:
![image](https://github.com/xlwings/xlwings/assets/171322007/b93a9c51-892b-4b95-b5b2-28aec7060e96)

Any help to see what could be happening here is greatly appreciated.

KR,
ADV

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!): Below the python code I wish to execute.

```python
# 
![image](https://github.com/xlwings/xlwings/assets/171322007/8c38fcb2-c066-4371-bc2b-9d9651d300bf)


```

**Comment by fzumstein** [comment]
See https://github.com/xlwings/xlwings/issues/1163

**Comment by ADV1977** [comment]
Thanks for the quick reply.

It seems that, in my case, that reference is already added:

![image](https://github.com/xlwings/xlwings/assets/171322007/65dd058f-e16d-4f5b-88ad-e3528241585a)

Just to be sure, I restarted again the UDF server and the issue is still happening....

KR,
ADV

**Comment by fzumstein** [comment]
did you start with a quickstart project and have you Imported UDFs?

**Comment by ADV1977** [comment]
I'm learning how to use xlwings to add Python to my excel sheets and I pickup these UDFs from a Udemy course I'm doing, if this is what are you referring to....

**Comment by ADV1977** [comment]
When I go into the configuration file, i have the following setup:
<img width="228" alt="image" src="https://github.com/xlwings/xlwings/assets/171322007/7274fbb6-640f-41e3-a54b-4a4b00a5bd2d">
Which is different to the configuration suggested in your page.   Shall I edit it manually?  And how?

**Comment by fzumstein** [comment]
activate the `Add Workboook to PYTHONPATH` in the xlwings ribbon add-in (this will edit the conf file)
