### ISSUE TITLE
Running xlwings script from .bat causes MoudleNotFoundError (on embedded python distribution)

### ISSUE THREAD

**Issue by acameronfw** [xlwings/xlwings#2467]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Office 365,, Python 3.11.9, xlwings 0.31.4
#### Describe your issue (incl. Traceback!)
I am attempting to distribute my xlwings worksheet to other users. I have created downloaded and placed an embedded python install in the sub-directory of the .xlsm file. If I run the embedded python.exe on the demoDist.py file (i.e python/python.exe demoDist.py) from the command prompt or powershell inside VS Code, the code executes properly, and I can call RunPython and ImportUDF properly. If I try the same execution from a .bat file, I get the ModuleNotFoundError. I think its a path issue, I am just not sure how to fix it.
 
```python
# Your traceback here
---------------------------
Error
---------------------------
ModuleNotFoundError: No module named 'demoDist'
  File "<string>", line 1, in <module>
    exec(stmt, globals, locals)
  File "C:\Users\acameron\OneDrive - Farnsworth Group, Inc\_AC Documents\Programing\Projects\FG_Process\Python\Excel_Python\demoDist\Python\Lib\site-packages\xlwings\com_server.py", line 328, in Exec
           ^^^^^^^^^^^
    return func(*args)
  File "C:\Users\acameron\OneDrive - Farnsworth Group, Inc\_AC Documents\Programing\Projects\FG_Process\Python\Excel_Python\demoDist\Python\Lib\site-packages\win32com\server\policy.py", line 639, in _invokeex_
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Users\acameron\OneDrive - Farnsworth Group, Inc\_AC Documents\Programing\Projects\FG_Process\Python\Excel_Python\demoDist\Python\Lib\site-packages\win32com\server\policy.py", line 310, in _invoke_
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Users\acameron\OneDrive - Farnsworth Group, Inc\_AC Documents\Programing\Projects\FG_Process\Python\Excel_Python\demoDist\Python\Lib\site-packages\win32com\server\policy.py", line 305, in _Invoke_

Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
import xlwings as xw

#Start xlwings server (to bypass starting server through cmd scriptpip)
if __name__ == '__main__':
    xw.serve()


def main():
    wb = xw.Book.caller()
    sheet = wb.sheets[0]
    if sheet["A1"].value == "Hello xlwings!":
        sheet["A1"].value = "Bye xlwings!"
    else:
        sheet["A1"].value = "Hello xlwings!"


@xw.func
def hello(name):
    return f"Hello {name}!"


if __name__ == "__main__":
    xw.Book("demoDist.xlsm").set_mock_caller()
    main()

```

**Comment by acameronfw** [comment]
As a note the excel file is just the standard quickstart for testing. 

Also, using VS Code to run the python script with the embedded python.exe only seems to work if the terminal working directory is where the python exe is, otherwise, I receive the same error. A second error, UDFs are able to import when I don't receive the error, but when put into a cell they return "Object required". I am not as concerned with that at the moment, but it may be related.

**Comment by acameronfw** [comment]
I got the .bat Excel workbook to run RunPython calls successfully from launching with the .bat file. The bat file looks like this:

```batch
# Your code here
:: Store the path where the .bat file is located

SET parent=%~DP0

:: Add Python to PATH - UPDATE WITH THE PYTHON LOCATION FOR YOUR SYSTEM

SET PATH=%PATH%;C:\Temp\demoDist\Python\python.exe

:: And then you call the python script like this

python %parent%demoDist.py
```

I am still not able to get UDFs to work (Object Required at call of a function in excel), but my main issue is resolved. I used a standalone quickstart

**Comment by fzumstein** [comment]
I don't think I've seen UDFs work with a frozen version of the python dependency.

**Comment by acameronfw** [comment]
Well, I got it working fine on a different computer (embedded python in the same folder as Excel, config had interpreter path set to that python.exe). UDFs and RunPython work. It must be a computer security setting of some sort.

**Comment by acameronfw** [comment]
I was able to find a solution. I ended up creating a conda environment instead of the Python embeddable distribution. It is a larger file size, but it is adequate for my purposes. I am marking as closed.
