### ISSUE TITLE
Your xlwings version is different on the client (0.30.12) and server (0.31.7).

### ISSUE THREAD

**Issue by tuanlv14** [xlwings/xlwings#2469]
#### OS
Windows 10

#### Versions of xlwings, Excel and Python
0.31.7, Office 365, Python 3.12

#### Describe your issue (incl. Traceback!)

When I start server: python app/server_fastapi.py --> All custom_function worked well.
I already had done sideload the add-in well.
But once I click on ribbon button or task panel button, I got this error:

`Your xlwings version is different on the client (0.30.12) and server (0.31.7).`

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

I already changed:
```
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>My Task Pane</title>
  <!-- Load office.js and xlwings.min.js -->
  <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>
  <script type="text/javascript"
    src="https://cdn.jsdelivr.net/gh/xlwings/xlwings@0.31.7/xlwingsjs/dist/xlwings.min.js"></script>
  <!-- Bootstrap with the xlwings theme -->
  <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/gh/xlwings/bootstrap-xlwings@5.2.3-2/dist/bootstrap-xlwings.min.css"
    integrity="sha384-TZ8CaOSXLBEEL73Aw1vX6a/2YP7QHdiuilF2C8Put8X81F3FzyRgt9ba77CMKAXq" crossorigin="anonymous">
  <!-- Load Custom Functions -->
  <script type="text/javascript" src="/xlwings/custom-functions-code"></script>
</head>
```

And requirements-fastapi.txt:

```
fastapi==0.111.0
gunicorn==22.0.0
jinja2==3.1.4
pandas==2.2.2
uvicorn[standard]==0.30.1
xlwings==0.31.7
```

So pls help me check and give me the instruction to fix this. I need to use task panel.

**Comment by fzumstein** [comment]
Please use https://github.com/xlwings/xlwings-server instead of quickstart.

**Comment by tuanlv14** [comment]
Yes. It worked well. Close this.
