### ISSUE TITLE
Office.js Add-ins: VBA button call marco that use 'RunRemotePython' via fastAPI

### ISSUE THREAD

**Issue by tuanlv14** [xlwings/xlwings#2470]
#### OS
Windows 11

#### Versions of xlwings, Excel and Python 
0.31.7, Office 365, Python 3.12

#### Describe your issue (incl. Traceback!)

I started well Office.js Add-ins. All custom function worked well on server.
But once I created a VBA button and call VBA marco to FastAPI server (server_fastapi.py) by bellow script:

```VBA
Sub SampleRemoteCall()
     RunRemotePython "http://127.0.0.1:8000/hello"
End Sub

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

Then I got this error:
![image](https://github.com/xlwings/xlwings/assets/105999643/a92c88be-244d-4ebb-a6ba-bca305dc7dd7)

Pls help me detect bug & fix it.
Can I call FastAPI function in VBA marco with Office.js Add-ins from VBA button ?

If  I only use xlwings Server, call FastAPI function in VBA marco, all thing worked well with:
```VBA
Sub SampleRemoteCall()
     RunRemotePython "http://127.0.0.1:8000/hello"
End Sub

```
But Office.js Add-ins seem to be diffferent xlwings Server ?

**Comment by fzumstein** [comment]
make sure you'r not using http if your server uses https

**Comment by tuanlv14** [comment]
Yes. Solved for me.
