### ISSUE TITLE
Xlwings library import dont work properly in Serverless Environment like Lambda

### ISSUE THREAD

**Issue by vedantyerpude** [xlwings/xlwings#2480]
We are trying to make use of Xlwings library in the AWS Lambda environment to perform some functionalities on the excel file generation. 

The lambda function returns reponse saying -
{   "errorMessage": "'NoneType' object has no attribute 'apps'" }

Lambda code has a line as -> app = xw.App(visible=False)

Is there any solution to the above error in the lambda environment?

**Comment by fzumstein** [comment]
On Linux, you can only use xlwings Reader (https://docs.xlwings.org/en/latest/pro/reader.html) and xlwings Server (https://github.com/xlwings/xlwings-server).
