### ISSUE TITLE
Error when installing Excel add-in using pywin32==306

### ISSUE THREAD

**Issue by chris-park** [xlwings/xlwings#2490]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 11

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
* Python 3.11.4
* Office 365 Excel Version 2405
* `xlwings==0.31.10`
* `pywin32==306`

#### Describe your issue (incl. Traceback!)
Upon installing `xlwings==0.31.10` and running `xlwings addin install`, I get the following error:
```{shell}
> xlwings addin install
Rebuilding cache of generated files for COM support...
Checking 00062FFF-0000-0000-C000-000000000046x0x9x6
Could not add module (IID('{00062FFF-0000-0000-C000-000000000046}'), 0, 9, 6) - <class 'AttributeError'>: module 'win32com.gen_py.00062FFF-0000-0000-C000-000000000046x0x9x6' has no attribute 'CLSIDToClassMap'
Done.
Successfully installed the xlwings add-in!
```
I discovered this is specific to `pywin32==306`. I was able to install the xlwings addin without any errors using `pywin32==305`.

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
```{shell}
> pip install -U xlwings
> xlwings addin install
```

**Comment by fzumstein** [comment]
thanks for reporting! Would be interesting to see if removing `%TEMP%\gen_py` would resolve that with 306.

**Comment by chris-park** [comment]
Thanks @fzumstein. Is the below what you're referring to? https://github.com/xlwings/xlwings/blob/21cdde70108fe58c04a85ced9bb516ad19ae46ff/xlwings/__init__.py#L134

**Comment by fzumstein** [comment]
Kind of, I just meant if you delete that folder on disk and re-run it again with 306 to see if it still misbehaves.

**Comment by chris-park** [comment]
Thanks for clarifying - that seems to have done the trick!

**Comment by fzumstein** [comment]
In that case, it's probably more of a pywin32 issue rather than connected to 306. I'll close this issue but we can reopen if it comes back.
