### ISSUE TITLE
about xlwings config

### ISSUE THREAD

**Issue by lgxcxd** [xlwings/xlwings#2515]
#### OS (e.g. Windows 10 or macOS Sierra)
windows 11
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings : 0.32.1
#### Describe your issue (incl. Traceback!)

Settings must be done using the "xlwings.conf" worksheet; settings in the "addin" are invalid. You must set the PYTHONPATH, even if you use "xlwings quick start myprj" to set up your project, and this applies when you run "run main". In this project, the worksheets and Python modules are located in the same folder.

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
That's incorrect, but looks like something is off on your end.

**Comment by lgxcxd** [comment]
> That's incorrect, but looks like something is off on your end.

I also suspect that there might be an error in my Windows system causing this. Because after I uninstalled miniforge3, reinstalled it, set up the Python environment, and installed software such as Python, pandas, and xlwings, and then used "xlwings quickstart myprj" to create a project, I still had to set PYTHONPATH = to the folder containing the module, Excel workbook.

**Comment by lgxcxd** [comment]
> That's incorrect, but looks like something is off on your end.
Is this related to setting up the Python environment using miniforge3?

**Comment by fzumstein** [comment]
There's a checkbox in the ribbon saying: `Add workbook to PYTHONPATH` which should be checked if you don't want to add the path manually.

**Comment by lgxcxd** [comment]
> Reference in new



> There's a checkbox in the ribbon saying: `Add workbook to PYTHONPATH` which should be checked if you don't want to add the path manually.

The settings in my ribbon seem to be ineffective.
