### ISSUE TITLE
FileNotFoundError(2, 'No such file or directory') when trying to install

### ISSUE THREAD

**Issue by HansThorsager** [xlwings/xlwings#2529]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 11 Home

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Excel, Office 365
Python 3.12.4
xlwings 0.33.1

#### Describe your issue (incl. Traceback!)
I just got an annoying message from Windows Defender about xlwings being a trojan horse and therefore tried to remove it (xlwings). After some research I'm confident that it was a false positive and now I'm trying to reinstall xlwings, but instead I get an errormessage saying

> FileNotFoundError(2, 'No such file or directory')

![Skærmbillede 2024-10-07 132838](https://github.com/user-attachments/assets/f757c44c-3441-48a7-80fd-bf22f4bc6c93)

Already tried rebooting (well, it IS Windows, after all...) without any effect. In order to debug further it would help to know what's actually missing?

**Comment by fzumstein** [comment]
It probably can't find the `xlwings.xlam` in the source package as that might be blocked by Windows Defender before xlwings can copy it to the XLSTART directory, see also: https://github.com/xlwings/xlwings/issues/2512

**Comment by HansThorsager** [comment]
Thanks for getting back to me. You might be on to something - I don't know. I tried copying the `xlwings.xlam` in to the XLSTART directory by hand and now at least the tab shows up in the top ribbon again, but the install/upgrade command still fails.
However when hitting the `Restart UDF Server` I get a `Run-time error '1': Could not load xlwings64-dev.dll` - not that I actually use the function, but I guess it still might be important for the overall functionality? All I use the xlwings for is as an easy way to edit my VBA in a decent editor.

**Comment by fzumstein** [comment]
If you are referring to this: https://www.youtube.com/watch?v=xoO-Fx0fTpM, you don't need the xlwings add-in at all. See also the other video that uses the the precompiled xlwings.exe: https://www.youtube.com/watch?v=H-DlhBJkHDQ

**Comment by HansThorsager** [comment]
That's exactly what I'm referring to - thanks!
Anyway, since I removed the scan history from Windows Defender I managed to install the add-in again using the suggestions in [#2512 ](url) - but it still failed when attempting to install the official way. Weird...
