### ISSUE TITLE
about excel xlwings tab

### ISSUE THREAD

**Issue by lgxcxd** [xlwings/xlwings#2531]
#### OS (e.g. Windows 10 or macOS Sierra)
windows 11 
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.33.1
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```
"Why doesn't 'somename.xlsm' have an 'xlwings' tab after using the code wb = xw.Book(); wb.save(r'z:\\somename.xlsm')? However, if 'somename.xlsm' is a workbook created with 'xlwings quickstart somename', then opening it with wb = xw.Book(r'somename.xlsm') does include an 'xlwings' tab."

**Comment by fzumstein** [comment]
the quickstart adds the _xlwings tab for ease of use.

**Comment by lgxcxd** [comment]
> the quickstart adds the _xlwings tab for ease of use.

Thank you!
After manually adding the xlwings.xlam add-in, the xlwings tab appeared in this workbook. Of course, it's still better to use the "xlwings quickstart" command to set up the project.
