### ISSUE TITLE
xlwings 0.33.1 update problem, no xlwings64-0.33.1.dll found

### ISSUE THREAD

**Issue by NTdingsir** [xlwings/xlwings#2532]
#### OS (e.g. Windows 10 or macOS Sierra)
windows 11
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.33.1 and python 13.0
#### Describe your issue (incl. Traceback!)
after  I updated the xlwings from 0.32.1 to 0.33.1, I found there is no xlwings64.0.33.1.dll is missing, I cannot found it after all on my HDD(I used to manually copy it to the relative path), so I cannot run my UDFs in the Excel. but the UI of xlwings show normal(ribbon button exists).
```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by NTdingsir** [comment]
the VBA eniroment  tells, "Could not load xlwings64-0.33.1.dll from either of the following folders: \nC:\program Files\Python313 \nC:\Program Files" etc. I search this dll through all my HDD and cannot found it. so I guess the update step forget to fetch this these dlls to local driver.

**Comment by fzumstein** [comment]
probably an antivirus issue

**Comment by NTdingsir** [comment]
thanks, it is really caused by kaspersky antivirus. when it turned off and reinstall xlwings, the xlwings64-0.33.2.dll appears under somewhere, problem solved.
