### ISSUE TITLE
AttributeError : 'NoneType' object has no attribute 'apps'

### ISSUE THREAD

**Issue by Aleomar15** [xlwings/xlwings#2558]
#### Client machine version
- Python 3.12.1

#### My machine
- Python 3.7

- Hi guys, I was testing xlwings on a client's machine and then I got the error AttributeError: 'NoneType' object has no attribute 'apps'. But on my machine it worked perfectly.
```python
AttributeError : 'NoneType' object has no attribute 'apps'

```

#### Code:

```python
import xlwings as xw

try:
    app = xw.App(visible=False)
    print("Excel initialized successfully.")
    app.quit()
except Exception as e:
    print(f"Error initializing Excel: {e}")


```

**Comment by fzumstein** [comment]
hmmm, you're most likely missing the pywin32 dependency. I thought that this was actually fixed and you should get a more meaningful error. But check this first.

**Comment by Aleomar15** [comment]
> hmmm, you're most likely missing the pywin32 dependency. I thought that this was actually fixed and you should get a more meaningful error. But check this first.

I managed to fix it, thank you very much!!
