### ISSUE TITLE
xlwings addin install: Make sure XLSTART folder exists

### ISSUE THREAD

**Issue by fzumstein** [xlwings/xlwings#341]
The folder in `%AppData%/Microsoft/Excel/XLSTART` might not exist

**Comment by denfromufa** [comment]
Just hit this issue on Windows 10, Excel 2016

**Comment by denfromufa** [comment]
if xlstart is added manually, then this works

**Comment by fzumstein** [comment]
Yes, there are some user experience issues with installing the addin. My idea is to move away from the CLI installer and provide a download from the homepage (maybe with a smarter GUI installer).

**Comment by denfromufa** [comment]
Is there any alternative to this add-in install issue currently? Looks like
Excel can have very different locations for XLSTART depending on version.

https://support.office.com/en-us/article/Automatically-open-a-specific-workbook-or-template-when-you-start-Excel-be9cddc1-a148-4cbf-8f3b-779df08957a3

**Comment by fzumstein** [comment]
Yes you can download it from the release page and install it vie `File > Options > Add-ins > Go ...`

**Comment by fzumstein** [comment]
sorry, here the link: https://github.com/ZoomerAnalytics/xlwings/releases 

I ll try to make it available from the install instructions soon

**Comment by fzumstein** [comment]
fixed by #1316
