### ISSUE TITLE
xlwings.applescript doesn't get placed into the right folder when installed with sudo

### ISSUE THREAD

**Issue by markw63** [xlwings/xlwings#438]
Hi. Love the software but on Excel 2016 v 15.20, Mac OSX 10.11.3 I had to dig around with Ron de Bruin site and do the following to get the xlwings.applescript going even after the xlwings runpython install

To install xlwings.applescript
Open a Finder Window
Hold the Alt key when you press on Go in the Finder menu bar
Click on Library
Click on Application Scripts (if it exists; if not create this folder)
Click on com.microsoft.Excel (if it exists; if not create this folder) note: Capital letter E (I had to create this folder)
Copy the xlwings.applescript file from the xlwings package to this (maybe new) folder.
(Note the xlwings.applescript is a system file so on finder you have to search for it with an additional 'system files ARE included' option to find it)
Also for me in the xlwings VBA default parameters,  Thisworkbook.path does not work - I have to put in the full path to my python code as PYTHONPATH - i.e. /Users/Mark/Downloads/myproject/

Thank you

**Comment by fzumstein** [comment]
What version of xlwings do you have? There was an issue in v0.7.0 but that has been fixed with v0.7.1.

Everything you describe should be taken care of automatically by `xlwings runpython install`. Note also that this is only needed when installing xlwings with `conda`. `pip` should take care of all of this automatically.

**Comment by markw63** [comment]
0.7.1
I did pip install xlwings 
And the runpython install
And as superuser as well just in case.
Works fine now but just thought it worth mentioning. Is it perhaps that the directory needs creating in Application Scripts and the install can't do that? 

Mark Wyllie

**Comment by fzumstein** [comment]
I see. It would be great to get some insights into this issue as I can't replicated it over here. I imagine that it might be indeed a sudo/access issue.

When I open `~/Library` and delete the `Application Scripts` folder (I only have the xlwings script in there so I don't mind, but you might want to back up the folder just in case), and after that run `pip install xlwings`, it correctly creates the folders with the `xlwings.applescript` file in it for me. `xlwings runpython install` is only meant to be necessary when installing xlwings via conda.

Do you get any error message when pip installing and not having the `~/Library/Application Scripts/com.microsoft.Excel` folder already existing?

Just do be sure, when you do

```
$python
>>> import xlwings
>>> xlwings.__version__
```

you really do get v0.7.1 ?

**Comment by markw63** [comment]
Hi Felix
Showing you 3 screen shots 
Changed the directory name to 1com.microsoft.Excel.
Ran the xlwings runpython install
Did nothing
Checked version – as shown.
Removed it 
It is trying to remove /private/var/root/Library/Application Scripts/com.microsoft.Excel
Which is somewhere different I think?? 
I searched the whole HD and no other xlwings.applescript

Feels like it is putting the file somewhere not in my path but in another path somewhere??
If I do
 ls  '/private/var/root/Library/Application Scripts/com.microsoft.Excel/‘

Then it finds the file – but unfortunately Excel 2016 does not find it.

Let me know how I can help



Mark Wyllie
+35699936711
+447803850994 (when in UK)

**Comment by fzumstein** [comment]
The screenshots didn't make it, but never mind, I got the issue:  `setup.py` expects 
```
>>> import os
>>> os.path.expanduser("~")
```
to resolve to something like `/Users/<Username>` whereas you are ending up in `/private/var/root`. Do you know why that is? Are you not using a regular account to login?

**Comment by markw63** [comment]
Felix
Have to say I don’t really know. I just use the account I always used, that said this machine has been through a lot of installs etc. I login as me Romanka which is an administrator account on the system.
Sorry I can’t be more useful…

Mark Wyllie
+35699936711
+447803850994 (when in UK)

**Comment by fzumstein** [comment]
No worries, I am not exactly a Mac sys admin neither...in a terminal, if you type

```
$ cd ~
$ pwd
```

which path does it print?

**Comment by markw63** [comment]
Felix
That gives me from a new shell:

/Users/Romanka

Hope that tells you something


Mark Wyllie
+35699936711
+447803850994 (when in UK)

**Comment by fzumstein** [comment]
Well, that looks all good, what do you get with this then?

    $ python
    >>> import os
    >>> os.path.expanduser("~")

**Comment by markw63** [comment]
Felix

I get this:



cmeprlt34:Data Romanka$ python

Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 12:54:16) 

[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin

Type "help", "copyright", "credits" or "license" for more information.

>>> import os

>>> os.path.expanduser("~")

'/Users/Romanka'

>>> 


Best regards
Mark

Mark Wyllie
+35699936711
+447803850994 (when in UK)

**Comment by fzumstein** [comment]
My guess would have been that pip/xlwings command line don't have write-rights on your system for `~/Library/Application Scripts/com.microsoft.Excel` and therefore throw the applescript file to that other folder.

But I am surprised that you don't get an error when running `xlwings runpython install`. This is what it does: https://github.com/ZoomerAnalytics/xlwings/blob/master/xlwings/command_line.py#L171

Maybe you can try to run the commands manually (while having the folder renamed/removed) and see if that gives you any errors.

**Comment by markw63** [comment]
Hi Felix
Tried that  and :
>>> os.path.expanduser("~")

'/var/root'

>>> os.path.expanduser("..")

'..'

>>> os.path.expanduser(".")

'.'

>>> os.path.expanduser(" ")

' '

>>> os.path.expanduser("~user ")

'~user '

>>> os.path.expanduser("~user")

'~user'

>>> os.path.expanduser("~Romanka")

'/Users/Romanka'

>>> os.path.expanduser("~root")

'/var/root'

>>> 



And that’s the problem I guess — it installs xlwings.applescript, but in the root users com.microsoft.Excel directory not the actual user directory.


To run the xlwings runpython install command I need to be running as root (sudo su) otherwise the script falls over. But root does not have the home directory of /Users/Romanka but of /var/root.
I think you might need a different way of getting the non-root user’s home directory. Or switch to sudo at the point you need permissions??

Hope that makes sense.


Mark Wyllie
+35699936711
+447803850994 (when in UK)

**Comment by fzumstein** [comment]
OK I see this makes sense now, thanks for the inputs, I ll see if I can resolve this for sudo installations.

**Comment by fzumstein** [comment]
Closing this as the solution is simply to not run the command as root (as generally suggested for installing python packages).
