### ISSUE TITLE
where is button for importing xlwings setup code in excel modules from excelpython?

### ISSUE THREAD

**Issue by denfromufa** [xlwings/xlwings#482]
https://cloud.githubusercontent.com/assets/5197585/3917034/3623f40a-2385-11e4-9754-5e3b924e38a9.png

**Comment by denfromufa** [comment]
![image](https://cloud.githubusercontent.com/assets/7870949/15832543/522c61ec-2be8-11e6-8e23-0b3d4537171b.png)

**Comment by denfromufa** [comment]
"Setup ExcelPython"

**Comment by fzumstein** [comment]
Yeah that's actually a good idea to replace the Setup ExcelPython button with a button to import the xlwings VBA module.
