### ISSUE TITLE
Precise figure sizing

### ISSUE THREAD

**Issue by avonmoll** [xlwings/xlwings#519]
I'm building a custom Gantt chart generator and need to be able to precisely control the figure AND axes sizes in order to get a matplotlib graph to line up with the Excel grid:
![image](https://cloud.githubusercontent.com/assets/4260850/17110923/3617a2a4-526d-11e6-976c-98cf9c37b1e4.png)

The problem is that in `Plot.show()` when the figure is saved, `bbox_inches` is set to `'tight'` which basically undoes all my fine tuning of the axes position in Python. This behavior is probably desirable in most applications and situations and I'm considering just inheriting from `Plot` and overriding the `show` method. Is my situation too unique to account for in the `xlwings` library, or could/should the `bbox_inches` setting be settable by the user?

**Comment by avonmoll** [comment]
As a side note - successive redraws of the plot force the image to have the same height and width as the image it's replacing, which in my case is undesirable (e.g. if a row were added to the task list).

Feel free to put all this on the back burner, I hacked my way around both of these items.

**Comment by fzumstein** [comment]
Makes sense to me, yes...

**Comment by fzumstein** [comment]
0.27.7 allows to set the savefig options via

```python
sheet.pictures.add(image=myfigure, export_options={"bbox_inches": "tight", "dpi": 300})
```

Whether or not the updated picture should keep the exact dimensions of the previous picture is probably debatable, not sure. However, you can easily update a picture and change dimensions by deleting/inserting like so:

```python
    if "mypic" in sheet.pictures:
        sheet.pictures["mypic"].delete()
    sheet.pictures.add(
        image=myfigure,
        name="mypic",
        anchor=sheet["A1"],
        export_options={"bbox_inches": "tight", "dpi": 80},
    )
```
