### ISSUE TITLE
Suppress "update linked data source" warnings

### ISSUE THREAD

**Issue by penenkel** [xlwings/xlwings#562]
Hi, I'm trying to interact with several workbooks that display an 

> This file contains links to other datasources. Do you want to Update or Not Update? *

 alert upon opening. I'd like to suppress said alert, so I set `display_alerts=False` on the app. Unfortunately the alert is still displayed. Only when I set `visible=False` are the alerts actually suppressed, and that regardless of whether or not the `display_alerts` option is set.

Config:
- Windows 7
- Python 3.5.2 (64bit) [Continuum Analytics Distribution]
- xlwings 0.10.0
- Excel 14.0.6112 (32bit)  (i.e. Office 2010)

*) The actual wording might be somewhat different, as I translated this from my locale

**Comment by fzumstein** [comment]
According to [this answer](http://stackoverflow.com/a/14908550/918626) display_alerts is not the only thing needed to suppress these warnings.

**Comment by penenkel** [comment]
Interesting, that seems to match my use-case. Could you tell me how/if I can set the mentioned options in xlwings? That is `AskToUpdateLinks` and/or `UpdateLinks`. As they are not exposed through the xlwings api, I assume I have to set them on the underling COM objects somehow? I seem to remember reading somewhere in the docs that those are accessible.

**Comment by fzumstein** [comment]
Sure, follow the tutorial [here](http://docs.xlwings.org/en/stable/missing_features.html). You should be able to use the VBA syntax after `.api`

**Comment by penenkel** [comment]
Thanks, this should work for `AskToUpdateLinks`, as it is a property of `Application`.
Can I also pass native API options like `UpdateLinks` through the xlwing functions? Something along the lines of 

`app.books.open(fullpath, UpdateLinks=False)`?

**Comment by fzumstein** [comment]
You will also need to access pywin32's `Open` method directly:

    app.books.api.Open(fullpath, UpdateLinks=False)

**Comment by penenkel** [comment]
Ok, thank you for your help.
From my point of view this issue can be closed now.
Or perhaps it would be useful to mark it as an feature request as per the tutorial linked above.

**Comment by fzumstein** [comment]
See also: https://zoomeranalytics.uservoice.com/forums/269851-xlwings/suggestions/10755651-suppress-excel-update-links-error-message

**Comment by fzumstein** [comment]
replaced by #1189
