### ISSUE TITLE
use DelayWrite in xw.sub

### ISSUE THREAD

**Issue by sdementen** [xlwings/xlwings#569]
Is it possible to explicitly call DelayWrite from a sub (ie not in a udf mode) ?
When returning a large dataset, it takes time and Excel may trigger the "waiting for an OLE application" kind of message that then raise an exception in the script (or so I understand the messages I get but without a deep investigation).
If I could use DelayWrite explicitly, I would use it for the "push my dataframe to excel" part and avoid this issue.
is it clear ?

**Comment by fzumstein** [comment]
I think a better approach is to wait for the chunking or just call `app.display_alert = False`, if I remember correctly that should suppress that warning.

**Comment by sdementen** [comment]
indeed, it works and it is simple. 
Idea: could this display_alert be unset/set before calling the sub/func ? maybe as an argument to the xw.sub/xw.func decorators ?

**Comment by fzumstein** [comment]
closing this as display_alert seems to work
