### ISSUE TITLE
Excel Range.CopyPicture not supported?

### ISSUE THREAD

**Issue by EMIjess** [xlwings/xlwings#582]
Per Microsoft, Range has a method CopyPicture() -  https://msdn.microsoft.com/en-us/library/microsoft.office.interop.excel.range.copypicture.aspx

When testing in xlwings, using:
```
import xlwings as xw # for Excel interactivity
wb = xw.Book("test.xlsx")
mysheet = wb.sheets('Sheet1')
thisrange = mysheet.range("a1:b3")
pic = thisrange.CopyPicture('xlPicture', 'xlScreen')
```
I get this error
```
python testing.py
Traceback (most recent call last):
  File "testing.py", line 37, in <module>
    pic = thisrange.CopyPicture('xlPicture', 'xlScreen')
AttributeError: 'Range' object has no attribute 'CopyPicture'
```

Perhaps there is another solution for taking a screenshot of a worksheet or range within xlwings, but I did not see it in the docs.

**Comment by fzumstein** [comment]
It's not natively implemented, but as usual, you can always get it by following the instructions here: 
http://docs.xlwings.org/en/stable/missing_features.html

In your case that is
```
import xlwings as xw
from xlwings.constants import CopyPictureFormat, PictureAppearance

xw.Range('A1:B2').api.CopyPicture(PictureAppearance.xlScreen,
                                  CopyPictureFormat.xlPicture)
```

**Comment by camiloos618** [comment]
I have a problem in VBA with Range.CopyPicture method. Is this problem solved in xlwings? CopyPicture randomly generates error in VBA, please try this simple test in your VBA:

Sub test1()
    Dim x1 As Long
    For x1 = 1 To 100
        Range("A1:A1").CopyPicture
    Next x1
    MsgBox "Test completed !!"
End Sub


I wonder if using xlwings will solve my problem. I design controlling reports that are sent by e-mail and I sometimes need to attach an image from a range of cells.

**Comment by fzumstein** [comment]
You might see some of these issues: https://stackoverflow.com/questions/24740062/copypicture-method-of-range-class-failed-sometimes
