### ISSUE TITLE
Book and/or Sheet activate() failing

### ISSUE THREAD

**Issue by tosiabunio** [xlwings/xlwings#600]
This is a random issue I'm observing in my code. I have a quite complex script that processes around 20 Excel files, constantly reloading, reading and updating them. I noticed that sometimes wrong workbooks and worksheets are updated with the data that were supposed to be written elsewhere. I was able to find out that it was because different workbook/worksheet combination was active then expected despite using active() method before the actual update. Added the following asserts:
```
self.__workbook.activate()
self.__worksheet.activate()
assert(xw.books.active == self.__workbook)
assert(xw.sheets.active == self.__worksheet)
```
and they are occasionally failing as if activate() failed to switch the active workbook/worksheet. 

xlwings 10.1

**Comment by fzumstein** [comment]
What version of Excel is that?

**Comment by tosiabunio** [comment]
Excel 2016

**Comment by fzumstein** [comment]
Are multiple and/or invisible Excel instances involved?

**Comment by tosiabunio** [comment]
Yes, the scripts rereads multiple files while working, quite possibly having more than one instance of Excel active.

**Comment by fzumstein** [comment]
Can you provide a small code sample? You shouldn't use `activate()` in scripts but the fully qualified range including the workbook, e.g.

```
wb = xw.Book('...')
wb.sheets[0].range('A1').value
```

**Comment by tosiabunio** [comment]
Well, the problem stopped to manifest after recent update. I know this was Python 3.6 compatibility fix but solved my problem. 

The script is quite complex so it cannot be replaced with small sample because everything seem to work okay then. 

The documentation doesn't mention fact that `activate()` shouldn't be used.  The xlwings now seems to be very sensitive to the state of Excel application started by xlwings, e.g. very often I get `None` as a result of `Range()` function depending on how previous run was ended. If I stop debug session, all Excel process need to be killed in order for the script to run properly. This is debugging nightmare. For that reason I get more success with `xlwings.Range()` calls instead of fully qualified `range()` calls and for that reason I need to use `activate()`.

**Comment by fzumstein** [comment]
OK I am closing this issue then for now. Feel free to reopen should the issue return or should you get more insight in what's causing the instability.

**Comment by tosiabunio** [comment]
I have a good repo: https://www.dropbox.com/sh/xop23dgkm9sf360/AAAtRR39LKKwkxatxH3xFNG_a?dl=0

Tested on two different machines, both with Excel 2016, Python 2.7.10

Run `python Localization.py Data` and see assertion failing.

I cannot reopen the issue.

**Comment by fzumstein** [comment]
OK thanks. do you mind if I attached the repo directly here as zip?

**Comment by tosiabunio** [comment]
No problem with that. Quick fix would be appreciated because this is pretty critical script for me at the moment.

**Comment by fzumstein** [comment]
[xlwings#600.zip](https://github.com/ZoomerAnalytics/xlwings/files/708164/xlwings.600.zip)

**Comment by tosiabunio** [comment]
I rewrote the script to use fully qualified access and it works fine. This is slight PITA, as there's no simple way of getting the index for the specific workbook or worksheet - I wrote simple function to find those indexes and now insert those in other scripts that suffer from `activate()` problem.

**Comment by fzumstein** [comment]
using fully qualified ranges is the way to go in scripts. glad you found a way to do it. I will update the docs to make sure it's clearer that `activate()` is meant to be for interactive use.

**Comment by tosiabunio** [comment]
But `index()` function for books and sheets collection would be extremely useful.

**Comment by fzumstein** [comment]
can you open a separate issue for this please, thanks!
