### ISSUE TITLE
Provide embedded files in Excel

### ISSUE THREAD

**Issue by mik-de** [xlwings/xlwings#602]
Deploying xlWings requires not only the Excel file but also a set of additional files. That is a constant source of error and lets your folders look messie.

Yet I'm thinking of various solutions and I'm willing to implement it myself.

Before I'll start doing the hard work I'd like to know if you are interrested in merging such solutions?

**Comment by fzumstein** [comment]
Well, can you share a bit of your ideas. I am not sure it needs to be built into the library. You could, for example, build a standard python package with your code and have people install that. Then your spreadsheet is standalone with nothing differenatiating it from a standard vba enabled spreadsheet.

**Comment by mik-de** [comment]
I've already experimented with embedding raw data into Excel. So I've evolved the most simplest interface for the embedding solution.

The basic idea is to have a folder named equal as the Excel file for all project files. It may contain python source or any kind of configuration and raw data. The following VBA interface interacts with that folder

PackBootstrap()
Looks for a folder with the same name as the Excel file. ZIPs that folder. And finally embeds that ZIP file as OLEObject with visibility set to false and marks it as the bootstrap ZIP. If a OLEObject marked as bootstrap ZIP is contained it gets deleted before.

UnpackBootstrap(overwrite=true/false)
Looks for a OLEObject marked as bootstrap ZIP. Extracts it from the Excel file. Un-ZIPs that file into a folder named equal as the Excel file. If overwrite is set to false it will ask before overwriting any excisting file.

DeleteBootstrap()
Deletes any OLEObject marked as bootstrap ZIP.

Hope this clarifys my idea.

**Comment by fzumstein** [comment]
Not really sure if I follow. Would `UnpackBootstrap` unzip the code on the fly (e.g. when `RunPython` is called)? and where would it be unzipped?

**Comment by kaiaeberli** [comment]
hi mik, 
I am also looking for such a feature. Would you mind sharing your code?

**Comment by mik-de** [comment]
There is not much code. Finally I found that one can add files easily with VBA to an Excel but not extracting it. So I've tried Python win32api which did'nt work at all coming up with exception. Without a clear goal its not the effort worth to go on.

The snippet below is the last I've tried:

def packBootstrap():
	wb = xw.Book.caller()
	ws = wb.sheets[0]

	f = "C:\py_prototypePyPack.txt"
	#f = "C:/py_prototypePyPack.txt"
	name = "py_prototypePyPack.txt"
	obj = ws.api.OLEObjects()
	obj.Add( Filename=f, IconLabel=name )
	messagebox.showinfo(title="packBootstrap", message="Hello World!")

**Comment by kaiaeberli** [comment]
thanks for sharing. For extraction, why not use the Item Method on Ole Objects and write it to a file? The method is described here : https://msdn.microsoft.com/en-us/library/office/ff834312.aspx

**Comment by kaiaeberli** [comment]
The writing to file of a zip OLE object didnt work. However I found this:
https://danny.fyi/embedding-and-accessing-a-file-in-excel-with-vba-and-ole-objects-4d4e7863cfff#.rinipy3js

It works for me to extract an embedded zip file to the directory of the excel file.

**Comment by mik-de** [comment]
The given link requires the use of clipboard. This is very bad style and unacceptable.

Anyway. After some experiments its seems that adding OLE works with pywin32 with the code below.

There are various Python libs out there to parse OLE. By time I'll do some experiments.
```

import xlwings as xw
from tkinter import messagebox
# import tkmessagebox


def Bootstrap():
	wb = xw.Book.caller()
	ws = wb.sheets[0]
	obj = ws.api.OLEObjects().Item(1)
	# obj.Delete()

	messagebox.showinfo(title="Bootstrap", message="Hello World!")
	# TBD
	
def packBootstrap():
	wb = xw.Book.caller()
	ws = wb.sheets[0]

	f = "C:\\Users\\mik\\Documents\\py\\Excel\\prototypePyPack\\py_prototypePyPack.zip"
	name = "py_prototypePyPack.txt"
	#messagebox.showinfo(title="packBootstrap", message=dir(ws.api) )

	obj = ws.api.OLEObjects()
	obj.Add( Filename=f, IconLabel=name )
	messagebox.showinfo(title="packBootstrap", message="Hello World!")
	# TBD
	
def cleanBootstrap():
	messagebox.showinfo(title="cleanBootstrap", message="Hello World!")
	# TBD
```

**Comment by kaiaeberli** [comment]
True, mine is quite an ugly solution.

**Comment by mik-de** [comment]
There seems to be no solid solution to add and extract files to an Excel file. The code below inserts a base64-encoded string to a hidden worksheet. Acess to the ZIP file would be done best using [zipimport](https://docs.python.org/2/library/zipimport.html).


`RunPython ("import xlBootstrap; xlBootstrap.packBootstrap()")`

`RunPython ("import xlBootstrap; xlBootstrap.Bootstrap()")`

`import xlwings as xw
from tkinter import messagebox
import errno
import os
import base64
import zipfile

bootstrap = "bootstrap"
ws_name = "xlwings_" + bootstrap + "_zip"


def Bootstrap():
	wb = xw.Book.caller()
	path = os.path.dirname(wb.fullname)
	sub_name = wb.name
	(sub_name, ext) = os.path.splitext(sub_name)
	sub_name = "py" + sub_name	
	full_path = os.path.join(path, sub_name, bootstrap)
	zip_name = bootstrap + ".zip"
	zip_path = os.path.join(path, sub_name) 
	
	mkdir_p(full_path)
	unpackFile(wb, ws_name, path, os.path.join(zip_path, zip_name))
	
	zip_handle = open(os.path.join(zip_path, zip_name), 'rb') # TODO Search for Python standard libs
	z = zipfile.ZipFile(zip_handle)
	for name in z.namelist():
		z.extract(name, full_path)
	zip_handle.close()	

def packBootstrap():
	wb = xw.Book.caller()
	deleteSheet(wb, ws_name)
	path = os.path.dirname(wb.fullname)
	sub_name = wb.name
	(sub_name, ext) = os.path.splitext(sub_name)
	sub_name = "py" + sub_name
	full_path = os.path.join(path, sub_name, bootstrap)
	zip_name = bootstrap + ".zip"
	zip_path = os.path.join(path, sub_name) 
	
	mkdir_p(full_path)
	zip_file = zipfile.ZipFile(os.path.join(zip_path, zip_name), 'w', zipfile.ZIP_DEFLATED)
	zipdir(full_path, zip_file)
	zip_file.close()
	
	packFile(wb, zip_path, zip_name, ws_name)
		
def deleteSheet(workbook, sheetname):
	for sheet in workbook.sheets:
		if sheet.name == sheetname:
			sheet.delete()
			
def mkdir_p(path):
    try:
        os.makedirs(path)
    except OSError as exc:  # Python >2.5
        if exc.errno == errno.EEXIST and os.path.isdir(path):
            pass
        else:
            raise

def zipdir(path, zip_handle): 
	for root, dirs, files in os.walk(path):
		for file in files:
			file_path = os.path.join(root, file)
			zip_handle.write(file_path, file_path.replace(path, '', 1) )
			
def packFile(workbook, path, filename, sheetname):

	# check if sheetname exists
	for sheet in workbook.sheets:
		if sheet.name == sheetname:
				raise FileExistsError			
	active = workbook.sheets.active
	workbook.sheets.add(sheetname) # also activates the sheet
	active.activate()
	sheet = workbook.sheets[sheetname]
	sheet.api.Visible = False

	sheet.range((1,1)).value = "Do not touch. Machine readable content"
	sheet.range((2,1)).value = "TBD:MD5"

	offset = 3;
	pos = 0;

	chunkSize = 5000 # bytes # limit is 6144 -base64-> 8192 / 8k
	with open( os.path.join(path, filename), "rb" ) as f:
		while True:
			chunk = f.read(chunkSize)
			if chunk:
				row = offset + pos
				sheet.range( ( row, 1 ) ).value =  base64.b64encode( chunk ).decode('ascii')
				pos += 1
			else:
				break
	
def unpackFile(workbook, sheetname, path, filename):
	if filename is None:
		filename = sheetname
	
	sheet = workbook.sheets[sheetname]
	offset = 3
	
	with open( os.path.join(path, filename), "wb" ) as f:
		row = offset
		while sheet.range( ( row, 1 ) ).value is not None:
			bytes = sheet.range( ( row, 1 ) ).value
			bytes = bytes.encode('ascii')
			f.write( base64.b64decode( bytes ) )
			row += 1`

**Comment by fzumstein** [comment]
We have released xlwings PRO which allows you to embed your Python code directly in a sheet. I believe this solves this issue.
