### ISSUE TITLE
mac: Expand Environmental Variables

### ISSUE THREAD

**Issue by y2kbugger** [xlwings/xlwings#615]
So from the time I submitted the last pull request until now, I have been hard coding the address for each user.

Now finally trying to use the feature again in 10.1:

    PYTHON_WIN = "%LOCALAPPDATA%\Continuum\Miniconda3\envs\pydev\pythonw.exe"

yields:

     Could not load xlwings32.dll from either of the following folders: %LOCALAPPDATA%\Continuum\Miniconda3\envs\pydev, %LOCALAPPDATA%\Continuum\Miniconda3\envs

Since it has been so long I don't know when the regression happened. I figured you may know the answer right away before I dig in and attempt a fix.

**Comment by fzumstein** [comment]
Nope, can't say off the top of my head what could be causing it, but I found this related error: #616

**Comment by kaiaeberli** [comment]
how about using this: PYTHON_WIN = Environ("LOCALAPPDATA") + rest

**Comment by y2kbugger** [comment]
I think that fails on Mac

**Comment by sdementen** [comment]
Could we use on windows  http://www.robvanderwoude.com/vbstech_data_environment.php#WSHShell  to expand the environment variables ?
I have a use case too for an excel tool stored on a shared drive but using a local python install (via pipenv) that is stored in the %HOME%/.virtualenvs  so I would like to have in the xlwings.conf the value "%HOME%/.virtualenvs" for INTERPRETER

**Comment by fzumstein** [comment]
we had this working once: #358 so we should just be able to see what broke it

**Comment by sdementen** [comment]
ok, so theoretically it should work but there is a bug to hunt, correct understanding from my part?

**Comment by fzumstein** [comment]
yes

**Comment by sdementen** [comment]
but I see the expand only in the  Function ReadFile(ByVal FileName As String).
It should be at least called when assigning in PYTHON_WIN = GetConfig("INTERPRETER", "pythonw") ==> so probably best to do the expand in the GetConfig, no ?

**Comment by sdementen** [comment]
I have added at the end of the GetConfig function:
```
    ' Defaults
    If GetConfig = "" Then
        GetConfig = default
    End If
    
    ' Expand environement variables
    GetConfig = ExpandEnvironmentVariables(GetConfig)
End Function
```
with the function ExpandEnvironmentVariables doing the objShell.ExpandEnvironmentStrings magic and it works (ie the INTERPRETER is properly expanded)

**Comment by sdementen** [comment]
@fzumstein , do I prepare a PR for this ?

**Comment by fzumstein** [comment]
sure

**Comment by sdementen** [comment]
when I fork from origin/master, I do not see the xlwings.bas. Should I just modify the .xlam and push it ?

**Comment by fzumstein** [comment]
yes, xlwings.bas is being built during CI. the xlam is the only source file
for the VBA.

**Comment by sdementen** [comment]
ok, is there the equivalent of "expanding environment variables" under Mac ? is it what ToMacPath does ?

**Comment by fzumstein** [comment]
you have to add your fork to https://cloud.xltrail.com

**Comment by Brad-eki** [comment]
As far as I can tell this is solved (On Windows at least). Is that correct?

**Comment by fzumstein** [comment]
yes it's resolved on Windows, but the equivalent is still en issue on Mac, I've changed the title accordingly. On mac, we'd want `~` to be resolved correctly.

**Comment by Brad-eki** [comment]
Thanks for the correction. :D
