### ISSUE TITLE
Add index() method to books and sheets collections

### ISSUE THREAD

**Issue by tosiabunio** [xlwings/xlwings#617]
A fully qualified access to the sheets is a preferred method to do so and it requires index for the workbook or worksheet we want to work with. Unfortunately, all methods to create or add new workbooks or worksheets return Book or Sheet objects so there is no way to quickly find the proper index other than iterating with integer over the collection and comparing objects at each index.

The whole process would be much easier if the collection had `index()` method that would return the index of the object in the corresponding collection (or -1 if not present).

As the order of object may change (e.g. when some of Books are closed), using `index()` would be very frequent to those who process many Excel files at the same time.

**Comment by fzumstein** [comment]
You can also use names instead of indices, wouldn't that also work in your case?

```
import xlwings as xw

wb1 = xw.Book()
wb2 = xw.Book()


for wb in xw.apps[0].books:
    print(xw.apps[0].books[wb.name])
```

**Comment by tosiabunio** [comment]
Yes, using the name should work as well.

**Comment by tosiabunio** [comment]
Well, this isn't that easy. Consider the following sequence:

```
app = xw.App(visible=False)
database = xw.Book("Workbook.xlsx")
print xw.apps[0].books[database.name].sheet[0].range("A1").expand("right").value
```

Should work, right? The problem is that I have no idea which app has the database workbook opened with `xw.Book()`. If you restart the debug session, each `xw.App()` actually creates a new Excel instance and the book will be in `xw.apps[5].books` for instance.

Is there a way to open the book with specific instance? Using qualified access still requires to kill all zombie instance before our script is run. This is a major PITA.

**Comment by fzumstein** [comment]
I think there's a few things going on.

* `xw.Book("Workbook.xlsx")` will find your Workbook across all instances as long as you've only got it open a single time
* from a `Book` object, you can get the according app object:

```
wb = xw.Book("Workbook.xlsx")
app = wb.app
```

On the other hand, in your example above, you will want to open the book in your specific instance, so you would not use `Book` but rather:

```
app = xw.App(visible=False)
print(app.books[database.name].sheet[0].range("A1").expand("right").value)
```

**Comment by fzumstein** [comment]
The other thing is with regards to zombie processes. Generally speaking, you end up with a zombie process if you still have a global object that links to the workbook when you close it. So you either need to use `Book.kill()` or need to `del my_book` etc. before you use `Book.close()`.
