### ISSUE TITLE
Excel for Mac 2011: Retrieving values for a whole column may cause a timeout.

### ISSUE THREAD

**Issue by benjaminweb** [xlwings/xlwings#624]
**Data:** Cheese production per country in tonnes, 2014. 222 float values in cells A1 through A222.

**Task:** Select column `A:A`. Retrieve values.

**Problem:** The retrieval may fail due to timeout in Excel app.

**Sub-Problem:** Not responding Excel blocks other tests. Killing it creates another blockage in the 'Do you want restore data' dialogue on next start, preventing subsequent tests from execution.

**Minimum working example ([select_1_million_cells.zip](https://github.com/ZoomerAnalytics/xlwings/files/751379/select_1_million_cells.zip)):**
```
curl -O https://github.com/ZoomerAnalytics/xlwings/files/751379/select_1_million_cells.zip
unzip select_1_million_cells.zip
py.test select_1_million_cells.py
[…]
select_1mn_cells.py ....FF
```

The example carries the same data with varying selection that ranges from 222 cells (values only) through 1 million cells.

- Within Excel only, macros may be applied to A:A range (correct me, if I am wrong).
- From xlwings retrieval of A:A range may cause a timeout (and cause Excel not to respond; plus creating blockage on next start in form of data recovery dialogue).

**Related questions:**
- How to ensure Excel to be closed before running any test (and particularly after a failed test in case of hanging?
- How to close Excel properly after all tests?
- How to prevent the recovery dialogue?

=> How should the pytest [fixture](http://doc.pytest.org/en/latest/fixture.html#fixture-finalization-executing-teardown-code) look like?

**Wish:**

A guide on testing. Maybe a CLI command that inits a test environment, meaning boilerplate files (Python, Excel) for getting it up and running within under one minute.

**Software:**
macOS Sierra 10.12.3 (16D32)
Microsoft Excel for Mac 2011, Version 14.7.1 (161129)
Python 3.6
xlwings 0.10.2

**Comment by fzumstein** [comment]
* We haven't looked into the exact issue why things are timing out. Memory could be an issue but probably not the only one. For now, a way to work around this is to manually chunking it: https://github.com/ZoomerAnalytics/xlwings/issues/77

* If you are on Mac only, closing Excel is usually less of an issue than on Windows, so the setup I am using [here](https://github.com/ZoomerAnalytics/xlwings/blob/master/xlwings/tests/common.py) can possibly be simplified. i.e. closing all books and then quitting Excel should usually work ok.

* You may find something on how to suppress dialogues [here](https://github.com/ZoomerAnalytics/xlwings/issues/562)

* What's the idea with using `set_mock_caller()` in `select_1_million_cells.py`? That would only make sense if you have a `Book.caller()` somewhere.

* I haven't used pytest yet so can't really advise on that (we use the standard unittest module)

**Comment by benjaminweb** [comment]
* Timeout is no real issue for me, it's rather an edge case I noticed. I agree, chunking it manually is an option. Have you tried to implement it by default ([law of orthogonality] (http://fishshell.com/docs/current/design.html)) and assessing its impact on performance (if the selections are small usually, we would not expect an effect for most of the cases [if most are only a small selection], however benefitting from the edge cases being more robustly covered)? Dump this, if applicable.
* _What's the idea with using set_mock_caller() in select_1_million_cells.py? That would only make sense if you have a Book.caller() somewhere._ ➔ There is none: Copy and paste without thinking. Thanks for the hint!
* Okay, I've made up now that pytest boilerplate, incorporating the closing books and app loops (rendering the requirement of suppressing dialogues obsolete): 
```python
import pytest
from appscript import CommandError

SPEC = None


@pytest.fixture(scope='session') # session means per pytest execution
def ExcelApp(request):
    """Provides an Excel Application instance and kills the same after all tests have finished."""
    ExcelApp = xw.App(visible=False, spec=SPEC)
    yield ExcelApp # before yield statement comes the setup, after the teardown
    print('Tear down Excel')
    while len(ExcelApp.books) > 0:
        ExcelApp.books[-1].close()
    ExcelApp.kill()

# fixture to close all books in an Excel Application instance
@pytest.fixture(scope='function')
# as we depend here itself on the session level fixture ExcelApp, using the fixture Excel ensures that an ExcelApp is present
def Excel(request, ExcelApp): 
    """Provides an Excel Application instance with no working book opened."""
    Excel = ExcelApp
    while len(ExcelApp.books) > 0:
        ExcelApp.books[-1].close()
    yield Excel


@pytest.fixture(scope='function')
def ExcelClosed(request):
    for app in xw.apps:
        for book in app.books:
            book.close()
        app.kill()


def test_function_opening_a_workbook(Excel):
    wb1 = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'cheese.xlsx') 
    xw.Book(wb1) # open 
    assert function_to_test() is True


def test_function_requiring_Excel_to_be_closed(ExcelClosed):
    # here we expect an error as Excel is not open
    with pytest.raises(CommandError):
        function_to_test()
```

**Comment by fzumstein** [comment]
With 0.23.1 you can now do: `myrange.options(chunksize=10_000).value = df`
