### ISSUE TITLE
Using a generic frozen python as python installation

### ISSUE THREAD

**Issue by iiLaurens** [xlwings/xlwings#625]
Hi!

I was wondering if it would be possible to allow a generic stand-alone executable python file to work with xlwings. The whole Python + Excel combination is a powerfull combination, however other users to which the excel files will be shared also need a python installation. The other solution appears to be a frozen executable, but the process of freezing a python script is very prone to errors and needs to be redone whenever changes to the code are required.

I was wondering if it would be possible to have a generic python stand-alone python installation to work with XLwings. I am talking about a frozen python as distributed on [this website](http://www.orbitals.com/programs/pyexe.html). It is possible to throw external python scripts at this executable and it will execute just like a regular python installation would, given that no non-standard libraries are loaded.

I have been able to sideload the comtypes and xlwings packages by simply extracting it in the same folder as pyexe.html. So for it seems I can succesfully import xlwings and comtypes from this python version alone. So I feel that in theory, this could work with xlwings.

I have also been able to execute code launched from VBA using this python installation. The only think I found is that the "-B" flag cannot be used with the standalone version of python.
I fail once I try to have XLwings communicating with the python installation, even after correcting for the "-B" flag and the python executable path in VBA.

I was wondering if you possibly see a way to get this working? The benefits would be huge, as it would allow us to quickly build and share Python infused excel files without the need of manually freezing Python every time I update the code. It also prevents me from trying to install python on all the secured computers of my colleagues. So I really hope it is somehow possible to get this stand-alone python installation working on XLwings.

I'd love to hear your idea about this.

**Comment by fzumstein** [comment]
sure, things like that should be doable, but we're focusing on the library, not on the deployment as this is a general Python issue. I usually find it easier to have users install Anaconda (no admin rights needed) and distribute your app as standard python package that can be pip installed, for example.
