### ISSUE TITLE
Unable to sort columns using SortOrder

### ISSUE THREAD

**Issue by rajibsaha11** [xlwings/xlwings#627]
Hi there, I wrote the following code, utilizing the SortOrder constant, to sort data in columns A and B:
```
import xlwings as xw
from xlwings.constants import SortOrder

def xlwingstest():
    wb = xw.Book.caller()
    xw.Range('A2').api.Sort(xw.Range('A2:B8501', atleast_2d=False).api,
                            SortOrder.xlDescending)
```
I have date data in column A and price data in column B. Whenever I run the code it inverts the columns, placing all the data in column A into column B. I have headers in row 1, hence why my code starts in row 2. However, it doesn't seem to matter to xlwings as it is sorting the entire column.

I appreciate all your help in this matter.

**Comment by fzumstein** [comment]
`atleast_2d` has been replaced with `ndim=2` since v0.9. The following works on an assumed Range("A1:B5"):

```
import xlwings as xw
from xlwings.constants import SortOrder

def xlwingstest():
    wb = xw.Book.caller()
    xw.Range('A1:B5').api.Sort(xw.Range('A2:B5').api,
                            SortOrder.xlDescending)
```

**Comment by rajibsaha11** [comment]
Thanks for getting back to me. However, using your code still places the data in col A in Col B and the data in Col B in Col A. I am using python 2.7, xlwings 0.10.3, excel 13.

**Comment by fzumstein** [comment]
Not sure if I follow. Here are the screenshots before and after running your code (although directly as script, i.e. no function and no .caller):

![screen shot 2017-02-16 at 23 40 29](https://cloud.githubusercontent.com/assets/2265504/23044671/7f78323e-f4a1-11e6-9026-607d0c03b54c.png)
![screen shot 2017-02-16 at 23 40 51](https://cloud.githubusercontent.com/assets/2265504/23044673/817dd5c0-f4a1-11e6-8d65-d20f3ca91019.png)

**Comment by rajibsaha11** [comment]
hopefully this will illustrate the point. when using the SortOrder.xlDescending, data doesnt change, when using, SortOrder.xlAscending the data switches, here is the before:
![current](https://cloud.githubusercontent.com/assets/25406498/23044897/43f1597e-f470-11e6-898c-f1d33c0fc69d.PNG)

here is the after:
![after](https://cloud.githubusercontent.com/assets/25406498/23044907/516f1f82-f470-11e6-9195-88f402d73842.PNG)

i am running it from excel using the following vba script:
```
Sub sort_macro()
RunPython ("import xlwings_sort_data2; xlwings_sort_data2.xlwingstest()")
End Sub
```

**Comment by rajibsaha11** [comment]
I ran it through python directly like yourself and got the same results as i have been getting through excel. Is it because i am not using python 3?

**Comment by fzumstein** [comment]
No, nothing to do with python 3. Are you sure about xlwings being at 0.10.3?

**Comment by fzumstein** [comment]
If the attached sample doesn't work for you, you must be on an old version of xlwings:

[sort.zip](https://github.com/ZoomerAnalytics/xlwings/files/781763/sort.zip)

**Comment by rajibsaha11** [comment]
Sorry, I am using  0.10.2-py27_0. I just updated and installed, but still getting the same results. i updated from 0.10.0.

**Comment by rajibsaha11** [comment]
i tried your sample. get the same bug.. is the difference between 0.10.2 and 0.10.3 that big?

**Comment by rajibsaha11** [comment]
i went ahead and installed 0.10.3 and am still having the same problems.

**Comment by fzumstein** [comment]
I really don't know what it could be. Try using the version that comes with anaconda (or miniconda) and see if that works...

**Comment by rajibsaha11** [comment]
i was initially using the anaconda version, 0.10.2. i am new to programming, python and xlwings, and was actually proud of figuring out sort order on my own. I too am flummoxed as to why it works for you and not me.

**Comment by DougAJ4** [comment]
I tried both the original and modified code, with a small range and 200,000 rows.  All worked as expected with no problem.  Running from Excel using:
 RunPython ("import my_module; my_module.xlwingstest0()")

Python 2.7, xlwings 0.10.3 (Anaconda version), and Excel for Windows Version 1611

**Comment by rajibsaha11** [comment]
I appreciate all your help. For some reason, it doesnt want to work on my computer, which is weird. I am flabbergasted..

**Comment by fzumstein** [comment]
I am closing this as we can't we replicate it. feel free to reopen should you have more insights at some point.

**Comment by GalymzhanAbdimanap** [comment]
hello! I have the same problem like [this](https://github.com/xlwings/xlwings/issues/627#issuecomment-280489112). swaps columns. @rajibsaha11  How did you solve this problem?

**Comment by dimetrym** [comment]
@fzumstein 
my company trying to explore using Python/Excel and buy PRO version after successfull tests.
but in the first test(simple sort rows) i get the same issue.

wb.sheets[0]['A1:B5'].api.Sort(wb.sheets[0]['A2:B5'].api, SortOrder.xlDescending) 
sorts range by **COLUMNS** NOT BY ROWS.

wb.sheets[0]['A1:B5'].api.Sort(wb.sheets[0]['A2:B5'].api, SortOrder.xlDescending, **Orientation=2**) 
also sorts range by **COLUMNS** NOT BY ROWS.

wb.sheets[0]['A1:B5'].api.Sort(wb.sheets[0]['A2:B5'].api, SortOrder.xlDescending, **Orientation=1**) 
also sorts range by **ROWS** NOT BY COLUMNS.
 
VBA documentation snippet:
xlSortColumns  **1 Sorts by column.**
xlSortRows        **2 Sorts by row. This is the default value**.
 
looks like some mess in function parameters marshalling.
Could you help and investigate with this issue please ?
Thank you

![image](https://user-images.githubusercontent.com/7129551/115528966-2c316f80-a29b-11eb-94af-6fd2472eb034.png)

**Comment by fzumstein** [comment]
@dimetrym I can finally replicate the issue with your sample code, yes. The issue would have to be fixed in the underlying pywin32 library. I can, however, fix it when integrating it into the native xlwings API.

**Comment by fzumstein** [comment]
Yes, it looks like a bug in pywin32 that should be reported in their repository. xlwings only tests the functionality that is natively available, i.e. not through the `.api` interface as that really just means you're using pywin32 directly.

**Comment by dimetrym** [comment]
@fzumstein please close issue.
tested in VBA. the same behavior 100%. 
i'm really confused how range.sort works in VBA...

Sub sortTest()
    Dim rg As Range
    Dim rg1 As Range
    Set rg = Worksheets("Sheet1").Range("A1:B5")
    Set rg1 = Worksheets("Sheet1").Range("A2:B5")
    rg.sort Key1:=rg1, Order1:=xlDescending, Header:=xlYes, Orientation:=xlSortRows
End Sub

**Comment by fzumstein** [comment]
good catch then, should have tried it out, too, thanks for looking into it!
