### ISSUE TITLE
xlwings from open workbooks fails

### ISSUE THREAD

**Issue by JohnSmizz** [xlwings/xlwings#629]
Hi-
I am facing the situation where the xlwings add-in works fine, if I start an Excel session via commandline and starting it up via command line and python and then open a spreadsheet `myproject.xlsm` and run some python code in the same-folder Python file `myproject.py`:
```python 
import xlwings as xw
wb = xw.book()
```
However, when I want to open a spreadsheet that is configured for use with xlwings in an existing Excel session that was **not** started via the above process (ie instead I go the normal Excel way), I encounter an error. Attempts to run a Python macro via RunPython or import the UDFs via clicking "Import UDF" via the excelwings add-in fails. 

**Run a macro**
If I want to run a macro and step into it, the code fails when attempting to run the VBA line
` RunPython import myproject;world()` first with the ```Python has stopped working. Close the program / Debug the program``` splash, and then follows up with the error 
`Fatal Python error: Py_Initialize: unable to load the file system codec "C:\Program Files (x86)\NOT IN PATH Folder\Other Program\...\__init__.py", line 120 raise CodecRegistryError,\ SnytaxError: invalid syntax Current thread....`

I started up Excel in safe mode and ran a macro via xlwings and it worked fine - is xlwings erroneously starting things it shouldn't (that other program shouldn't be running any files at this stage).

**Run a UDF**
Again it fails when starting from the Excel session itself. It fails when the VBA code gets to line `If 0 <> XLPyDLLActivateAuto(Py, XLPyCommand) Then Err.Raise 1000, Description:=Py` initially with the ```Python has stopped working. Close the program / Debug the program``` splash and then follows up with a MS VB Error "Run-time error '1000':
Python process exited before it was possible to create the interface object..."

When starting from a safe-mode Excel session, loading up the UDFs also fails. The VBA error that is spit out is a `Run-time error 440: 'Automation Error'`

I am running Python 3.5.2 on Anaconda 4.2.0 as the sole Python installation on this Windows 7 installation. The Python installation is 64-bit but my Excel is 32-bit. My xw version is 0.10.2. The dll files are in the same directory (C:\Anaconda3\) as pythonw.exe, and I've specified the Win_python path to point to C:\Anaconda3\pythonw.exe as suggested in #574.

I dug around in the xlwings source code to find out what specifically is being set when I call `xw.Book()` that is being set differently when I start Excel conventionally but couldn't find a smoking gun (but I also don't know very much). 

Any idea as to why the addin works 100% if I run I start an Excel session out of a Python prompt but not in the case of opening an existing xlsm file and then attempting to run it through that?

I can ref  #574, and #583 because they have some of the identical-looking errors.

**UPDATE**
- it's definitely got to do with the other application that xlwings erroneously tries to call. If I unload the other plugin, start Excel and run xlwings and only thereafter import the other package xlwings runs fine. However if I load the first plugin and then load up xlwings (by running the macro) the crash mentioned above happens.
The other application is called **FINCAD Suite 2016 for Excel**. 
Any ideas how to configure xlwings so that it doesn't try and run that FINCAD __init__  file?

**Comment by fzumstein** [comment]
Do you know if Fincad does anything with Python?

**Comment by JohnSmizz** [comment]
I don't know, but I can ask them - however I will need to ask something more specific than 'does Fincad do anything with Python'. Any idea what exactly I could ask?

**Comment by fzumstein** [comment]
ok no worries. We're going to switch from the VBA module to an addin in the forseeable future, I recommend you wait until it's out and see if that solves your probleml

**Comment by fzumstein** [comment]
please reopen if the error persists with the xlwings addin.
