### ISSUE TITLE
xlwings random com_error -2147352570 

### ISSUE THREAD

**Issue by ededovic** [xlwings/xlwings#633]
I have a job scheduled to run daily. On random days, it stops working with com error shown below _(com_error: (-2147352570, 'Unknown name.', None, None))_. It appears to fail while trying to open a workbook: **wb = xw.Book(xls_file)**. I have found that shutting down excel fixes the issue. Any suggestions on how to recover from this error automatically and let the code continue? Any other suggestion? 

xlwings.__version__ = '0.10.3'

Error details: 
```
wb = xw.Book(xls_file)
File "C:\Users\prod\AppData\Local\Continuum\Anaconda2\lib\site-packages\xlwings\main.py", line 472, in __init__
for wb in app.books:
File "C:\Users\prod\AppData\Local\Continuum\Anaconda2\lib\site-packages\xlwings\main.py", line 358, in books
return Books(impl=self.impl.books)
File "C:\Users\prod\AppData\Local\Continuum\Anaconda2\lib\site-packages\xlwings\_xlwindows.py", line 374, in books
return Books(xl=self.xl.Workbooks)
File "C:\Users\prod\AppData\Local\Continuum\Anaconda2\lib\site-packages\xlwings\_xlwindows.py", line 302, in xl
self._xl = get_xl_app_from_hwnd(self._hwnd)
File "C:\Users\prod\AppData\Local\Continuum\Anaconda2\lib\site-packages\xlwings\_xlwindows.py", line 221, in get_xl_app_from_hwnd
return disp.Application
File "C:\Users\prod\AppData\Local\Continuum\Anaconda2\lib\site-packages\xlwings\_xlwindows.py", line 136, in __getattr__
self._oleobj_.GetIDsOfNames(0, item)
com_error: (-2147352570, 'Unknown name.', None, None)
```

**Comment by fzumstein** [comment]
I wouldn't use Excel for automated jobs. I can't really tell if xlwings or Excel itself is the issue, but just generally speaking these solutions are never really stable enough when Excel is involved in it. For automated jobs I would work with the reader/writer libraries that don't require Excel, like xlrd/xlwt, openpyxl and xlsxwriter if that's possible.

**Comment by ededovic** [comment]
Funny suggestion from someone who spends hours building tools to interact with Excel. 
Anyway,  do you know why the below workaround works? My guess is that current instances of excel may have run into some issue and are blocking xlwings somehow. I typically open multiple instances of excel in case a spreadsheet runs into an issue I do not loose all other spreadsheets/workbooks.  

This appears to work: 
>   
>   app = xw.App()
>   wb = app.books.open(xls_macro_file)
>   pass
>   wb.close()
>   app.quit()
> 

while this does not:
> wb = xw.Book(xls_macro_file)

**Comment by stolpovsky** [comment]
Just to raise awareness.

https://support.microsoft.com/en-us/help/257757/considerations-for-server-side-automation-of-office

**Comment by ishaan-k03** [comment]
From what I researched and got to know this issue is mainly with Excel.
So I opened **Task Manager** and closed **Excel** Instance that's it it started working again.

It happened when there was issue in your code you code has opened instance lot of time but didn't closed as error was occurred.
Better use **try/catch/finally**.

**Comment by nc82-nc** [comment]
I had this error "pywintypes.com_error: (-2147352570, 'Nom inconnu.', None, None)" because Excel was opened.  It prevented addin installation.
