### ISSUE TITLE
Mac: App(visible=False) is broken

### ISSUE THREAD

**Issue by misakichan** [xlwings/xlwings#652]
Hi, when I use xlwings XLSX file operation, set up the   `app = xlwings.App (visible = False)`   but in MAC will automatically open the Excel.app, and would not automatically open the Excel in win10.
mac os 10.12.4
windows10
Pycharm
python3.6
xlwings(last version from pypi)

**Comment by fzumstein** [comment]
Are you seeing this with Excel 2016 on Mac?

**Comment by 491637568** [comment]
Yes,Excel 2016 on mac(build15.32 170309)~

**Comment by fzumstein** [comment]
Yeah Mac Excel 2016 plays difficult. It did work for Mac Excel 2011 but I am not sure if it can be properly handled with Mac2016... so for now consider it a known bug...

**Comment by fzumstein** [comment]
Ok so currently it opens Excel as non-frontmost application. Maybe it would be better to hide it the same way as when you click the orange button (between the quit and maximize buttons).

**Comment by samsfisher** [comment]
Hello, the app is visible even with Excel 2011 Mac. Any ideas whats going wrong?

```
import xlwings as xw
# app = xw.App(visible=False,spec='/Applications/Microsoft Office 2011/Microsoft Excel')
app = xw.App(visible=False)

# PATH NAME
input_file_path = 'fname'
wb = app.books.open(input_file_path)
sht = wb.sheets['Log']
sht.range('D2').value = 'TT'
sht.range('D2').value 
```

**Comment by fzumstein** [comment]
Hiding windows on Mac works differently from Windows. It only moves them away as frontmost window. I was testing `app.api.windows[1].window_state.set(kw.window_state_minimized)` to see if the behaviour is more of what is expected by minimizing it instead of hiding the window, but that wasn't much more promising.

I think for now the best way to do it is to call `app.visible` after opening the book:

    import xlwings as xw
    app = xw.App()

    # PATH NAME
    input_file_path = 'fname'
    wb = app.books.open(input_file_path)
    app.visible = False
    sht = wb.sheets['Log']
    sht.range('D2').value = 'TT'
    sht.range('D2').value

**Comment by kevinjordan** [comment]
While you figure out if/how to suppress visible state of excel workbook.
Is it also possible to suppress the prompt to handle automatic links for an excel document that has links to another document? 
e.g. equivalent of 'ignore' 

![screenshot](https://user-images.githubusercontent.com/865901/27830015-4cab2f46-60bc-11e7-88d8-5887555b3e51.png)

**Comment by fzumstein** [comment]
@kevinjordan see this issue: https://github.com/ZoomerAnalytics/xlwings/issues/562
you'd need to adopt it to mac though

**Comment by fzumstein** [comment]
Looks like it's possible after all as it works properly when opening like this from the command line:

```
open -gj -a /Applications/Microsoft\ Excel.app
```
