### ISSUE TITLE
matplotlib figures in Excel: how to pass additional arguments to pictures.add?

### ISSUE THREAD

**Issue by denfromufa** [xlwings/xlwings#665]
How can I replicate something like this?

http://stackoverflow.com/a/4708018/2230844

The api for picture does not allow passing additional arguments, such as facecolor. Only alpha (transparency) is passed (e.g. fig.patch.set_alpha(0.9)).

http://docs.xlwings.org/en/stable/api.html#picture

Also how can I set resolution (dpi)? The resolution exported to Excel is much worse than the one in the notebook.

IMO, picture should accept dictionary with matplotlib settings that can be passed to savefig.

**Comment by denfromufa** [comment]
btw, I'm using `%matplotlib notebook` magic, and plotting API of pandas, if it makes any difference.

**Comment by DougAJ4** [comment]
The link below has some examples plotting matplotlib figures in Excel.  I don't think it answers your question, but it might be of some use anyway:
https://newtonexcelbach.wordpress.com/2016/02/14/use-matplotlib-from-excel-with-xlwings/

Note that the code in the blog post needs to be updated for the latest xlwings version.  I have updated the code in the download files, which should work.

**Comment by denfromufa** [comment]
@DougAJ4 i noticed your blog sometime ago, it looks great!

**Comment by denfromufa** [comment]
Anyway, I just posted extended version of my lightning talk about xlwings:

https://www.linkedin.com/pulse/flying-xlwings-what-time-best-visit-houston-denis-akhiyarov

https://nbviewer.jupyter.org/gist/denfromufa/175116ec142c91500f618a1715f52c54

**Comment by denfromufa** [comment]
you can see how much custom configuration I had to add to matplotlib plots.

**Comment by fzumstein** [comment]
I'am finally on this issue again - I'll need this to most importantly change the picture format from png to svg.

**Comment by fzumstein** [comment]
see also #519
