### ISSUE TITLE
Problems quitting after running python functions from Excel VB

### ISSUE THREAD

**Issue by rkpatel33** [xlwings/xlwings#671]
I am having a problem where I am often unable to quit Excel from the menu bar or hitting `Cmd+Q` after running macros that call python functions using:

```
RunPython ("import module; module.foo()")
```

This happens always when an error occurs in the python (but I see no message popup, which is a know bug I think), and also I think sometimes when all macros run successfully.

I am on Mac Excel 2016 and Python 2.7. Is this a known problem?

**Comment by fzumstein** [comment]
the missing error popup has been fixed in the upcoming release. The rest I am not sure but might be connected. I ll push the new version out soon.

**Comment by fzumstein** [comment]
0.11 fixes the missing popup, do you still see the other issue here?
