### ISSUE TITLE
How to get existing addins activated after calling xw.App( )

### ISSUE THREAD

**Issue by ededovic** [xlwings/xlwings#696]
If I have say Bloomberg or any other addin, they do not become available inside **app = xw.App()** as shown below. Is there an option that would load all excel addins when using the following code.
    **app = xw.App()**
    **xlb = app.books.open('xls_macro_file.xlsm')**
    ...
    xlb.close(); 
    app.quit()
An alternative that works is to use  **app = xw.apps.active**, while that works in most cases, Excel gets stuck at times, and xw ends up with an exception. 

I'd prefer to call xw.App( ) as that is more robust when working with excel. The only challenge is that addin calculations can not be called as add-ins are not loaded.

**Comment by fzumstein** [comment]
You need to manually load the addin, i.e. open the xlam, for xll addins see also: https://stackoverflow.com/questions/33125610/xlwings-wipes-out-my-excel-addin and the link therein.
