### ISSUE TITLE
make installation of addin easier and enable on mac also

### ISSUE THREAD

**Issue by fzumstein** [xlwings/xlwings#704]
see also #853

**Comment by hydrosquall** [comment]
Presently unable to install the add-in on Mac. When I try to install the adding by going to 

`/Users/cameron/Environments/xlwings/lib/python3.6/site-packages/xlwings/addin/xlwings.xlam` as directed by `xlwings addin install`, and then attempt to add a reference to xlwings, I get a complaint that "Requested type library or wizard is not a VBA project". As a result, I can't even get the hello world example to work.

**Comment by hydrosquall** [comment]
It works properly when I ran `xlwings quickstart` later,  now that the addin is installed. I think that maybe the issue was the xlwings quickstart didn't work if the addin hadn't been installed yet.

**Comment by fzumstein** [comment]
Change installation from semi-hardcoded `%APPDATA%\Microsoft\Excel\XLSTART` to `app.api.StartupPath`

**Comment by fzumstein** [comment]
#1316
