### ISSUE TITLE
Could not activate Python COM server

### ISSUE THREAD

**Issue by higherthananace** [xlwings/xlwings#706]
Hi - I have the latest version of xlwings installed

![capture](https://user-images.githubusercontent.com/29993854/27982332-6e737184-636d-11e7-9296-79cc05372ea9.PNG)

After following http://docs.xlwings.org/en/stable/udfs.html?highlight=one%20time and enabling Trust access to the VBA project object model

![image](https://user-images.githubusercontent.com/29993854/27982370-142aa110-636e-11e7-9223-aece8665b397.png)

And the latest addin with the following settings

![image](https://user-images.githubusercontent.com/29993854/27982377-34417258-636e-11e7-877b-3c723244c950.png)

When I click 'Import functions' I wait a while ~ 30 seconds and then the following error

![image](https://user-images.githubusercontent.com/29993854/27982357-ccece092-636d-11e7-90e9-1bdfb849ce12.png)

I also can't see the xlwings dll under references in the Visual Basic Editor

Please help!

**Comment by fzumstein** [comment]
Did you save the workbook as macro enabled workbook and set a reference to xlwings in the VBA editor, see http://docs.xlwings.org/en/stable/addin.html#installation?

**Comment by higherthananace** [comment]
HI - thanks,
Workbook - yes workbook is  xlsm format
Reference - it's checked
![image](https://user-images.githubusercontent.com/29993854/27984797-be45d122-63ac-11e7-9d31-de83022a25b2.png)

Then when I click import macros I get this
![image](https://user-images.githubusercontent.com/29993854/27984802-ee71c4aa-63ac-11e7-80bc-06f4f369ec73.png)

So in the Main module in xlwings.xlam I edited the path to xlwings%.dll to the full path (even though C:\ProgramData\Anaconda3 is in my $PATH)

![image](https://user-images.githubusercontent.com/29993854/27984831-b65ff1f8-63ad-11e7-9754-4b5022a1b1d3.png)

![image](https://user-images.githubusercontent.com/29993854/27984827-889f95b6-63ad-11e7-8c3e-8ae691c2e063.png)

Then I get the above COM error

**Comment by fzumstein** [comment]
Ouch, you're not supposed to change the VBA code. Start from scratch, then make sure that whatever you specify as interpreter in the ribbon works from a command prompt. so if you have `pythonw`, then that is supposed to start the correct interpreter. If not, use the full path there, i.e. in your case most likely `C:\ProgramData\Anaconda3\pythonw.exe`
