### ISSUE TITLE
If 0 <> XLPyDLLActivateAuto(unused, XLPyCommand, -1) Then Err.Raise 1000, Description:=unused

### ISSUE THREAD

**Issue by marcodor** [xlwings/xlwings#707]
Hi
i have downloaded the new add-in v0..11.2 and I have installed it in Excel 2010, windows 10.
i am getting this error when trying to restart the UDF server
![image](https://user-images.githubusercontent.com/7493648/28064697-90922d9c-662d-11e7-9c08-41fb923d5918.png)

Please let me know if am doing something wrong or if there is a known bug.
thank you very much for your help and work .

**Comment by fzumstein** [comment]
does a standard udf work? e.g. if you use the quickstart project that comes with a `=hello()` function?

**Comment by marcodor** [comment]
Hi, I am new to xlwings,  how would I invoke the =hello() function...

**Comment by marcodor** [comment]
There is no =hello() function in any module that i can see.. there is one Sample_Call but this is what i get...
![image](https://user-images.githubusercontent.com/7493648/28069575-deee5aec-6641-11e7-80ec-26f696da43e2.png)

**Comment by fzumstein** [comment]
You seem to be on an older version of the quickstart book which seems weird if you installed xlwings for the first time?

**Comment by marcodor** [comment]
Hi. I installed xlwings via the latest Anaconda3-4.4.0-Windows-x86_64 download. it did not work...Then after a lot of search I found one of your comments about the new xlwings v.11.2 file, which I downloaded and updated to the anaconda folder...but still not working...

**Comment by fzumstein** [comment]
make sure to uninstall de conda version first, before you pip install xlwings again

**Comment by marcodor** [comment]
Hi. I have uninstalled the original xlwings that came with Anaconda and re-installed version 0.11.2 with pip.
i opened the quickstart xl file and these are the results:
![image](https://user-images.githubusercontent.com/7493648/28156878-5bd88d00-67ac-11e7-956a-ac6683902c74.png)

![image](https://user-images.githubusercontent.com/7493648/28156889-64ac895e-67ac-11e7-9182-5d096bd5308e.png)

Then I tried to use the example UDF provided in the file, Sample Call and this is the result:
![image](https://user-images.githubusercontent.com/7493648/28156922-8e643076-67ac-11e7-8680-0a8ca61bf838.png)


![image](https://user-images.githubusercontent.com/7493648/28156933-9a0495f6-67ac-11e7-810e-c44e4f478159.png)

**Comment by fzumstein** [comment]
The first bug is now resolved in 0.11.3 (you will need to update the addin).

**Comment by marcodor** [comment]
Hi. I uninstalled the old one and pip installed 0.1103. Here are the screen prints of the tests:
These are the results using the "quickstart" xl workbook.

![image](https://user-images.githubusercontent.com/7493648/28325210-1fc49f84-6bd5-11e7-9387-eb3080a38794.png)

![image](https://user-images.githubusercontent.com/7493648/28325241-2fe557b4-6bd5-11e7-99c2-533518235e86.png)

![image](https://user-images.githubusercontent.com/7493648/28325258-3ef43c7a-6bd5-11e7-856a-b09f8ec6adef.png)

![image](https://user-images.githubusercontent.com/7493648/28325297-54fcff8e-6bd5-11e7-976d-ef8daf2f7c49.png)

![image](https://user-images.githubusercontent.com/7493648/28325316-66e9f792-6bd5-11e7-8e95-4364dc9e9347.png)

![image](https://user-images.githubusercontent.com/7493648/28325337-776aa364-6bd5-11e7-8fe0-d11667dd1591.png)

![image](https://user-images.githubusercontent.com/7493648/28325365-87d4ccde-6bd5-11e7-9d74-bd76d23252e2.png)

**Comment by fzumstein** [comment]
* You didn't update the addin correctly. uninstall it first, then try again. the new one has a password protection ("xlwings") so you wouldn't even get to the code without typing the pw.
* For the dll error, follow https://github.com/ZoomerAnalytics/xlwings/blob/master/docs/troubleshooting.rst
