### ISSUE TITLE
add-in 

### ISSUE THREAD

**Issue by aalvaradom** [xlwings/xlwings#717]
when i try to use the sql function and populate the arguments, I get an error: invalid procedure call or argument... any ideas what I'm doing wrong?

**Comment by fzumstein** [comment]
can you attach your sample book?

**Comment by aalvaradom** [comment]
[sql.xlsx](https://github.com/ZoomerAnalytics/xlwings/files/1159568/sql.xlsx)

**Comment by aalvaradom** [comment]
I tried to upload the macro enabled workbook, but was not able to.  I was able to upload a regular workbook.

**Comment by fzumstein** [comment]
The file/formula is ok. Are you using the latest version of the addin? If you double click it in the VBA editor, it would ask for a password ("xlwings"), otherwise you're not on the latest version.

**Comment by fzumstein** [comment]
Is `Debug UDFs` checked on purpose? To use the sql function, you don't need a macro-enabled book.

**Comment by aalvaradom** [comment]
I unchecked the Debug UDFs check box, no luck.  Not sure what may be causing the function not to work.  thanks for checking though.

**Comment by fzumstein** [comment]
I could check if the most basic things, the RunPython sample in the quickstart book works. and if the you can import the hello function from that quickstart book to find out where exactly it's having issues.

**Comment by fzumstein** [comment]
Closing this because of age.
