### ISSUE TITLE
[IDEA] record vba macros and convert them to python on the fly with vb2py

### ISSUE THREAD

**Issue by denfromufa** [xlwings/xlwings#720]
vb2py is a tool for converting vba code to python automatically and is licensed under BSD.

https://pypi.python.org/pypi/vb2py

The dependencies PythonCard, mxTextTools and Simpleparse are rather outdated, but generally it works great.

Here is sample output of conversion from docs:

```vb
Function addBaseDirectory(Path as String)
        addBaseDirectory = BASEDIR & Path ' BASEDIR is a global
End Function
```

command line call to converter:

`python converter.py -c -f vb/test/Utils.bas vb/test/test2`

```python
def addBaseDirectory(Path):
        _ret = BASEDIR + Path
        return _ret
```

**Comment by fzumstein** [comment]
thanks for the input, I ll add a section to the docs

**Comment by Dedalios** [comment]
vb2py est un outil permettant de convertir automatiquement le code vba en python sous licence BSD.
https://pypi.python.org/pypi/vb2py

Les dépendances PythonCard, mxTextTools et Simpleparse sont plutôt obsolètes, et je n'ai pas encore vérifier sont fonctionnement car cette application est écrit en python2.7 hors je n'utilise que les versions 3.7

Voici un exemple de sortie de conversion à partir de docs: 


Voici un exemple de sortie de conversion à partir de docs:
```
Function addBaseDirectory(Path as String)
        addBaseDirectory = BASEDIR & Path ' BASEDIR  est une organisation globale.
End Function

```

appel en ligne de commande au convertisseur:

python converter.py -c -f vb/test/Utils.bas vb/test/test2

```
def addBaseDirectory(Path):
        _ret = BASEDIR + Path
        return _ret
```
