### ISSUE TITLE
Returning arrays with more than 2 dimensions

### ISSUE THREAD

**Issue by DougAJ4** [xlwings/xlwings#722]
I have been working on updating some of my older spreadsheets to use the latest xlwings (0.11.3), including using the auto-generated code.  I am currently working on Numpy and Scipy linear algebra functions.  Mostly this works well, but in some cases I am getting a #VALUE! error, which seems to be associated with return values that are arrays or tuples with more than 2 dimensions.

Using the scipy.linalg.lu function as an example, if I run this in python with a 3x3 array as input, I get a tuple of 3 3x3 arrays returned, or if I wrap the return value with np.array() I get a 3x3x3 array.

If I call the same function from xlwings it returns an error, so I have written another function (in an another module) to extract one of the arrays into a 2D variant array, which can then be returned to the spreadsheet.  This works, but the shape of the array returned by xlwings does not match the shape in Python:

If I return the tuple from the python code, in VBA I get a variant array: 
Variant/Variant(0 to 0, 0 to 1, 0 to 2, 0 to 2)

If I return a numpy array from the python code, in VBA I get a variant array: 
Variant/Variant(0 to 1, 0 to 2, 0 to 2)

In both cases the results do not match those from running the same code directly in Python.

For now I will modify the Python code to return one 2D array, but is there a way to return all the data to VBA in the original format, ie in this case as a 3x3x3 array?

**Comment by fzumstein** [comment]
Yeah we haven't look at >2d arrays as it doesn't really make sense when you call functions from cells. It's a valid input though for calling functions from VBA, but not top prio right now from my perspective.

**Comment by DougAJ4** [comment]
OK, but I think some words in the docs would be good.  At the moment if you write a function to call the auto-generated UDF, and split the 3D array into a number of 2D arrays, it is not obvious that the arrays you get are different to those returned if you run the same code in Python.

**Comment by fzumstein** [comment]
could you maybe attach a sample for that case? that sounds like a bug

**Comment by DougAJ4** [comment]
[LU code.txt](https://github.com/ZoomerAnalytics/xlwings/files/1172193/LU.code.txt)
The attached file has a sample using the scipy.linalg.lu() function with:
Python code
Auto-generated VBA function (xl_LU)
VBA to call xl_LU from spreadsheet (RtnLU)

From the array returned by xl_LU I can extract two 3x3 arrays.

If the python function is run direct from python it returns 3 3x3 arrays.  Array[0] is not returned by the xlwings function.  Array[1] and Array[2] are the same as the two arrays returned by xlwings.

I have now modified the python function so it returns a specified 2D array (code also in the attached file). This will return any of the three arrays.

**Comment by fzumstein** [comment]
Not sure if this is still an issue, but I believe this included tweaked VBA wrapper code, which isn't supported, therefore I'll close this.
