### ISSUE TITLE
When calling python function in excel no data shown

### ISSUE THREAD

**Issue by andreicrisan11** [xlwings/xlwings#728]
Hi Felix, 

So I am writing a function in python with the @xw.func and I click Import Functions and excel recognises my new function. However, if I call it from excel, no data is displayed. 

On the other hand, if I write in python the following command : `sht.range('E1').value = fed_funds(sht.range('A1').value)`  it displays it. 

Any ideas on what the issue might be?

Thanks

**Comment by fzumstein** [comment]
You would need to show all your code or attach a complete sample.

**Comment by fzumstein** [comment]
closing due to inactivtiy
