### ISSUE TITLE
Reading excel data to pd.dataframe generates error

### ISSUE THREAD

**Issue by edupinto** [xlwings/xlwings#733]
Not sure there is a bug, but just in case it is and no one spotted it before.

Importing a table into a pandas dataframe with the code below.
df = sht.range('A1').expand().options(pd.DataFrame).value

In any cell in excel where the value is #NAME? ( due to formula error), the converted value is the number -2146826259 rather than NaN, or even a string.

I've researched the documentation but could not find the logic behind this conversion. I also searched online for this problem but couldn't find any similar questions/answers related to this.

**Comment by fzumstein** [comment]
You're right, the cell errors aren't handled properly yet, see also https://github.com/ZoomerAnalytics/xlwings/issues/61 and https://github.com/ZoomerAnalytics/xlwings/issues/496

**Comment by fzumstein** [comment]
fixed, see the referenced issues
