### ISSUE TITLE
Not possible to set reference to xlwings in VBA Editor

### ISSUE THREAD

**Issue by Exceluser** [xlwings/xlwings#736]
Hi,
I downloaded Anaconda, and installed in the standard way. Then, I installed the xlwings addin to my Excel using the Command Prompt and "xlwings addin install", which was succesfull according to the Command Prompt. The next step would be to set a reference to xlwings in the VBA Editor. But there is no such possible option. Also when i browse for the files and try to do it manually to the files xlwings32.dll or xlwings64.dll, it gives me an error. What am I doing wrong here?
I trusted the VBA project modul btw.

(+ My xlwings Ribbon is only the "import function" button and nothing else, I am not sure if this is the supposed way)

**Comment by fzumstein** [comment]
You're running the old version of the addin. Once the correct version is installed, it looks like here including the version number: http://docs.xlwings.org/en/stable/whatsnew.html#v0-11-4-jul-23-2017

Depending on how you were installing it before, you need to replace the addin with the new one. the command line installs it in the special XLSTART folder. You can also download the addin from here: https://github.com/ZoomerAnalytics/xlwings/releases

**Comment by fzumstein** [comment]
see also here: http://docs.xlwings.org/en/stable/migrate_to_0.11.html#install-the-add-in

**Comment by Exceluser** [comment]
I could fix this problem now but another one opened up:

I downloaded and installed Anaconda in the standard way, then replaces the AddIn with the new one. Also, I have trusted the VBA projects and the reference is now set. Nonetheless, when i try to import UDFs I get "Bad DLL calling convention 49. Make sure you are trusting access to the VBA project obejct module", which is did. You mentioned in another thread, that the DLL files should be from the 19. Feb 2017, but mine are last changed on 23. Feb 2017, if that helps? Also, if so, where would i get the right files from?
xlwings quickstart testproject does also not yield success, i. e. i cannot import functions there either.

(I would like to use this for work and I do not have admin rights on this pc, on my personal laptop at home everything works for some reason)

**Comment by fzumstein** [comment]
you need to make sure you're on the same version with the addin and the python package: upgrade the anaconda installation via the conda-forge channel: http://docs.xlwings.org/en/stable/installation.html

**Comment by Exceluser** [comment]
I did. Now the error says "File not found: xlwings32.dll 53. Make sure you are trusting access to the VBA project object module".

Also, when i go to the VBA editor and want to set the reference, there is xlwings, but it says "name conflicts with existing module, project or object library"  (There is a VBAProject, which is called xlwings, but i cannot remove it for some reason)

**Comment by Exceluser** [comment]
Regarding the second part: I tried renaming it, which makes the "xlwings" in the references box also change its name, so that one seems to be the same one and therefore it should be necessary to tick said reference box, i guess?

**Comment by fzumstein** [comment]
When you add a reference to the addin, you must not have a VBA module xlwings present. You should remove that beforehand as mentioned in the migration guide: http://docs.xlwings.org/en/stable/migrate_to_0.11.html

**Comment by w-haque** [comment]
Was having an almost identical issue. Followed until the last step and now experiencing the following error:
![2017-09-19 16_21_37-sdplab8 - vnc viewer](https://user-images.githubusercontent.com/32114007/30619832-ab83bc1e-9d56-11e7-9cff-104aefb1de16.png)

**Comment by fzumstein** [comment]
closing this as it's too old. please open a new issue if you still have issues.
