### ISSUE TITLE
Question regarding usage of UDFs for multiple members

### ISSUE THREAD

**Issue by Exceluser** [xlwings/xlwings#742]
No issue, rather a question:
Is it possible, that other people use my written UDFs w/o installing Anaconda completely? I'm thinking something like I have here with a C# AddIn: There are 2 .dll files, a .xll file, a .pdb and a .dna file in a folder, if I drag-and-drop the .xll file into an open .xlsm spreadsheet, which is in the same directory as said files above, I am able to use the in C# written functions in this spreadsheet.

**Comment by Exceluser** [comment]
I tried sending others the addin + the .py file with the functions as well as the xlwings.dll files and let them create a spreadsheet name it the same as the .py file but that does yield an error message when trying to import UDFs

**Comment by fzumstein** [comment]
To use xlwings, you always need a local python installation with xlwings in addition to the add-in. There are various forms how you can distribute python and the necessary packages, see also the discussion here: https://github.com/ZoomerAnalytics/xlwings/issues/662
