### ISSUE TITLE
refresh problems with UDFs in matrix

### ISSUE THREAD

**Issue by ilrico** [xlwings/xlwings#745]
I experienced issues with UDFs returning pandas.DataFrame when function is called in Excel matrix-way.
Function is just not called (usually it takes 1 to 2 secs to return the DF but when this problem occur cursor is available right after Shift-F9, so I feel function is not called at all).
As anyone same issue ?

xlwings 0.11.4, Excel 2013 64bit, Windows Server 2012 R2 Standard

**Comment by fzumstein** [comment]
Has it ever worked or does it work again after a restart of Excel?

**Comment by ilrico** [comment]
It works then i made changes in database (not UDFs) so data should change.
But no refresh.
Reload UDFs server + fx doesnt help.
Only Excel relaunch solves it.
