### ISSUE TITLE
Addin Issue: "Cant find DLL entry point..." Trust center setup as documented

### ISSUE THREAD

**Issue by whittles** [xlwings/xlwings#748]
I have uninstalled everything xlwings and reinstalled via Anaconda Navigator, Conda, and pip (only one instance at a time, I haven't been stacking them) and each time I get this generic error that from what I read, shouldn't be getting. Any ideas?

System: 
Windows 10 Pro
Office Professional Plus 2013 (32 bit)
Python 3.6 / xlwings version 0.11.4

![image](https://user-images.githubusercontent.com/19228096/29889834-31394738-8d8b-11e7-8415-655c0113b136.png)
![image](https://user-images.githubusercontent.com/19228096/29889842-35a020c6-8d8b-11e7-8fac-9ff1a95700af.png)

**Comment by fzumstein** [comment]
What version of the Excel Addin/Module are you running?

**Comment by whittles** [comment]
0.11.4

I installed xlwings then ran the command _xlwings addin install_ as per the documentation.

**Comment by fzumstein** [comment]
I haven't see this one before. I still guess that it's somehow getting the wrong version of the dll. If you've reinstalled so many times, it's possible that something got mixed up and not reinstalled properly. I will make things more fool proof in the next release, see #743 and #740

**Comment by fzumstein** [comment]
assuming this is solved, if not please reopen
