### ISSUE TITLE
Possible to get UDF to run and refresh at regular interval?

### ISSUE THREAD

**Issue by helpme1** [xlwings/xlwings#752]
Suppose I have this UDF defined in python v3.6 xlwings v0.11 to run on Excel 2016.

```
import xlwings as xw

@xw.func
def random_val(x):
    import random
    return random.random()*x
```
The UDF is imported into an Excel sheet which supports xlwings. I have tested that the formula =random_val(2) at cell A1 works fine.

Is it possible to run this UDF at regular time interval of 1 minute so that the output is refreshed at cell A1 every minute?

**Comment by Minionbob2019** [comment]
I'm facing exactly the same issue. I just fortunately found this question but looks like no one answered this old question. would really appreciate if someone can help please???

**Comment by fzumstein** [comment]
This would require RTD that xlwings currently doesn't support, see #888
