### ISSUE TITLE
Interactive Matplotlib Graph in Excel?

### ISSUE THREAD

**Issue by wochner** [xlwings/xlwings#753]
Is it possible to bring interactive matplotlib charts using [event handling](https://matplotlib.org/users/event_handling.html) into Excel using xlwings? 

Can we use the mpl_connect event manager in Excel? 

Matplotlib supports other interface toolkits (wxpython, tkinter, qt4, gtk, and macosx).

**Comment by fzumstein** [comment]
I don't think but I frankly don't know enough about it. However, I think the way to go should anyways be web based charts like plotly or bokeh. At least using the latest iteration of the HTML/JS based addins, it should be easier to do.

**Comment by fzumstein** [comment]
closing this as out-of-scope at the moment.
