### ISSUE TITLE
Repeated Calculation Of Excel Spreadsheet Slowing Down Over Time

### ISSUE THREAD

**Issue by treviesweets** [xlwings/xlwings#760]
Hi, 

We are using xlwings to populate, run, and extract results from a spreadsheet model for 000's of individual cases.

We run these lines at the outset...

```
self.EXCEL = xl.App()
self.EXCEL.calculation = 'manual'
self.EXCEL.screen_updating = False
```

Populate the spreadsheet and call calculate as so...

```
self.EXCEL.calculate()
```

Before extracting the results.

The python code is very simple - we are using the range('A1').value syntax to set and get the relevant values.

Turning of autocalc and screen updating has helped with speed but we have a strange issue where individual iterations take longer over time. For example, the first 100 cases run in about 0.6 seconds but when we get to the 10,000th case each case takes 10 seconds. 

This seems odd, and we are not sure whether it is an issue with Excel or xlwings.

**Comment by fzumstein** [comment]
if you can attach a barbone sample that reproduces the error, we can look
into it, thanks

Am 27.09.2017 10:56 vorm. schrieb "Trevor Sweetnam" <
notifications@github.com>:

**Comment by treviesweets** [comment]
Ok, thanks. I'll see what I can do tomorrow.
