### ISSUE TITLE
" referenced by anther workbook" warning

### ISSUE THREAD

**Issue by nyan314sn** [xlwings/xlwings#770]
When I open Excel, I see this error called "This workbook is currently referenced by anther workbook and cannot be used" 

Please note that I get this warning even when I open a blank workbook. The warning goes away when I unchecked xlwings frrom "Tools-> References -> xlwings"

I am using Windows 7 and Office 2010. 

![image](https://user-images.githubusercontent.com/7884934/31894933-d3c4f246-b7dd-11e7-9dbb-a9bd2581f0d1.png)

**Comment by fzumstein** [comment]
I think this might be an issue with your Excel setup rather than with xlwings. When I google it, I see this issue coming up with all kinds of add-ins like solver, analysis tool pack etc.

**Comment by su79eu7k** [comment]
Had a same issue but in my case, after cleaning up the files(including xlwings.xlam) under C:\Users\???\AppData\Roaming\Microsoft\Excel\XLSTART\ and reinstalled xlwings. Then problem solved. No idea what happened. Now the folder has xlwings.xlam only. There were many super-old & temporary excel files.

**Comment by SeungVictor** [comment]
> Had a same issue but in my case, after cleaning up the files(including xlwings.xlam) under C:\Users???\AppData\Roaming\Microsoft\Excel\XLSTART\ and reinstalled xlwings. Then problem solved. No idea what happened. Now the folder has xlwings.xlam only. There were many super-old & temporary excel files.

I had a same issue. In my case, it happend when I use xlwings on the developement tool in personal.xlsb. So I unchecked xlwings in personal.xlsb and it solved.
