### ISSUE TITLE
missing uninstall

### ISSUE THREAD

**Issue by tschm** [xlwings/xlwings#773]
Played a bit with xlwings today and did not get anywhere.
Uninstall instructions missing
xlwings does not show up properly in the Add-ins despite being installed and in the menu-bar (in excel)
In the VBA editor it would ask me for a password
xlwings32.dll is missing problem?

I gave up quickly...

**Comment by wkschwartz** [comment]
Does `pip uninstall xlwings` not cut it?

**Comment by tschm** [comment]
installed via conda (using condaforge?)

**Comment by tschm** [comment]
conda uninstall left plenty of traces of xlwings btw... in particular it was still hanging around in Excel

**Comment by frogger72** [comment]
try: xlwings addin remove before uninstalling

**Comment by gunkaragoz** [comment]
I did not want to reinstall and uninstall. Instead, I deleted xlwings.xlam file located in C:\Users\[USERNAME]\AppData\Roaming\Microsoft\Excel\XLSTART.

**Comment by fzumstein** [comment]
fixed with 0.19.4
