### ISSUE TITLE
Named ranges are created based on range currently selected

### ISSUE THREAD

**Issue by bsyouness** [xlwings/xlwings#774]
``` 
import xlwings as xw
wb = xw.Book()
n1 = wb.names.add('test', '=Sheet1!a1')
n1.refers_to
```
Returns: u'=Sheet1!F9', in my case because F9 was selected. The name created will have the address of whatever range you've selected with an offset corresponding to the `refers_to` range you pass (in my case `Sheet1!a1`, offset is (0, 0)). I tried running it with the API (`wb.api.Names.Add(Name='test', RefersTo="=Sheet1!a1"`), and the same thing happens. Does that mean that the problem is from `win32`?

**Comment by wkschwartz** [comment]
I can reproduce this bug on macOS 10.12.16 with Excel 2011 version 14.2.0 (120402), XLWings version 0.11.4, and Python 3.6.3

**Comment by wkschwartz** [comment]
However, I can't reproduce the direct-access-API bug, presumably because the APIs are different across OSes:

While I had manually selected cell G9:
```
>>> wb.api.Names.Add(Name='test2', RefersTo="=Sheet1!a1")
Traceback (most recent call last):
  File "/Users/billy/Documents/xlwings/venv/lib/python3.6/site-packages/aeosa/appscript/reference.py", line 575, in __getattr__
    selectortype, code = self.AS_appdata.referencebyname()[name]
KeyError: 'Names'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/billy/Documents/xlwings/venv/lib/python3.6/site-packages/aeosa/appscript/reference.py", line 577, in __getattr__
    raise AttributeError("Unknown property, element or command: {!r}".format(name)) from e
AttributeError: Unknown property, element or command: 'Names'
```

**Comment by fzumstein** [comment]
`api` means `pywin32` on Windows and `appscript` on Mac, and yes, they have a completly different syntax. You can get a feel for it by looking at the same function in `_xlwindows.py` and `_xlmac.py` respectively.

**Comment by fzumstein** [comment]
The issue here that you will need to use absolute cell address when adding the named range or else Excel treats them as relative named ranges: https://superuser.com/questions/800694/named-ranges-changing-randomly-in-excel-2010
