### ISSUE TITLE
RunPython calling incorrect module

### ISSUE THREAD

**Issue by cleverku** [xlwings/xlwings#777]
Hi,

I've been using xlwings for the last 6 months or so and have seen this little gremlin pop up a couple of times.  The only resolution seems to be to restart my computer. 

I have 2 different XL/xlwings solutions sitting in 2 different folders.  Both solutions happen to call a module with the the same name.  For some reason the RunPython function will attempt to call the module from the 1 of the folders only instead of determining the correct module location it needs to use.

I'll explain a bit further:

Folder 1:  C:\Solution1\  contains the following
xlMain.py (contain a sub called CountCows() ) 
MySolution1.xlsb  (contains RunPython ("import xlMain; xlMain.CountCows()")  ) 

Folder 2:  C:\Solution1\  contains the following
xlMain.py  (contain a sub called CountSheep() ) 
MySolution2.xlsb  (contains RunPython ("import xlMain; xlMain.CountSheep()") ) 

As you can see both py modules happen to have the same name (xlMain.py)

I spent most of this morning working and running the solution in folder 1.  Everything was running fine. 

Later during the day, when I tried running solution in folder 2, I get the error that "AttributeError: module 'xlMain' has no attribute 'CountSheep' "

The RunPython process seems to want to keep looking in the Folder 1 module instead of running from the Folder 2 code.  If I rename the py file Folder 2 to xlMain2.py for example it runs fine.  

Why is the RunPython process trying to keep referencing the same py module even though it is in a different folder to where the code is run from?  Is this something to do with Zombie processes running?  If so how can I kill them?

Any help appreciated.

**Comment by fzumstein** [comment]
this might actually be a bug in that xlwings doesn't insert the workbook folders path in the correct place and so it finds the other module first. I need to look into this.

**Comment by cleverku** [comment]
Thanks Felix.  Do you think there is any kind of short term workaround/hack for this?  My concern with this behaviour is that I may be running DEV code when truing to run PROD code without noticing.  In the example I gave I happened to notice the bug because different solutions happened to have the same module name.  But it makes me very nervous to know that the wrong code may run without throwing any kind of error.

**Comment by fzumstein** [comment]
So your folder structure is:

```
C:\Solution1\Folder1\ MySolution1.xlsb
C:\Solution1\Folder2\ MySolution1.xlsb
```

is that right?

Maybe it would help to see what you get when you log out (or write to a cell) what you get for `sys.path` in the two cases.

**Comment by cleverku** [comment]
Folder structure is as follows:

`
`
```
C:\SheepCounter\
    SheepCounter.xlsb   (contains VBA RunPython ("import xlMain; xlMain.CountSheep()")
    xlMain.py   (contains a function called CountSheep())

C:\CowCounter\
    CowCounter.xlsb   (contains VBA RunPython ("import xlMain; xlMain.CountCows()")
    xlMain.py   (contains a function called CountCows())
```

The problem appear to be that when I run the SheepCounter call from Excel via the RunPython it seems to want to use the xlMain from the CowCounter solution.  

As you hinted at it's as if the sys.path contains the C:\CowCounter even when running the SheepCounter code.  Unfortunately I restarted my machine so cannot verify the contents of sys.path. 

Do you know where the contents of sys.path are held and how one could reset them?  What would xlwings be doing that would cause the sys.path to hold onto the CowCounter path?   I tried killing excel and any python.exe or pythonw.exe processes but this didn't work.  Only rebooting my machine worked. 

Thanks.

**Comment by fzumstein** [comment]
Closing this as it's very old. feel free to reopen if this is still an issue.
