### ISSUE TITLE
Running Python from a server

### ISSUE THREAD

**Issue by indirextest** [xlwings/xlwings#788]
With xlwings, you have to have Python installed on your desktop, along with the Python script.  If there are multiple desktops in use, the same python script has to be copied to each machine.  As such, any changes that need to be made to a UDF have to be updated individually.

Is it possible to have the script be hosted and run from a cloud server?  This way, the code is only updated once, and can be the machines that have the Excel file on their local machine.  From what I understand, is it possible to get the RunPython function to refer to a server on a web address?

Thanks

**Comment by fzumstein** [comment]
You might be able to save the source files on a shared drive although it might slow down things too much.

**Comment by rbn920** [comment]
My way of "short of" doing this is freezing the script, placing it on the server and then having the spreadsheet look to it.

**Comment by indirextest** [comment]
Thanks fzumstein and rbn920 for your replies.  Not too worried if it slows things down a bit.  Key thing is that I don't want to have to go about installing Excel on all client machines.  Also, if the python code is on a server, it only has to be edited one, as well being kept private. Any idea how I might go about doing this?

**Comment by gonzague123** [comment]
Hi Indirextest, 
I'm looking for the same solution. Did you find a way to run python on a cloud server ?
Thanks

**Comment by falan** [comment]
Hello All,
I think the actual  question is "I don't want to have to go about installing Python on all client machines. ".
I have succeed with another way to doing this.
I wrap the python run-time and dependency like pandas, pyodbc using pyinstaller and put those run-time on shared folder. On Excel side, I leave the hook on workbook_open , when the workbook opened, it will check the run-time exists or not on local machine and update the run-time version if necessary. The actual python files on the  PYTHONPATH , I leave it points to shared folder, and the PYTHON_WIN points to the local run-time. It keep the best of both world. Leave the ability to dynamic change the python file and no need to install the python on every machine with python dependency.
For running on a cloud server, it will need the strong power of cloud if you are in a multiple user environment, it might not be a good idea.

FYR

**Comment by fastzombies** [comment]
I also need to distribute Python to random client machines that may or may not have access to a server or shared folder.  My solution is to create a virtual env in the same directory as the Excel file and configure the xlwings.conf sheet accordingly.  Then I zip up that directory and distribute it as a "package".  This adds 16M or so to my Excel files, but it solves a lot of problems.

**Comment by Fag42** [comment]
> , if not exists, it will copy run-time to local and update the run-time version if necessary. The actual python files is in the PYTHONPATH
Hello falan, interesting,
What is the script or code to do it when Excel is opened?

**Comment by fzumstein** [comment]
Remote interpreter was introduced with 0.26.0, currently for Google Sheets & Excel on the web only but will likely be extended to desktop apps.
