### ISSUE TITLE
Run time error # 53 - xlwings32.dll not found (V 0.11.4)

### ISSUE THREAD

**Issue by Faseeh16** [xlwings/xlwings#791]
Hi,

As i installed xlwings (using pip) the add in is giving following error (message). 

```
Run-time Error '53'
File not found: xlwings32.dll
```

As i searched through this forum I found following points that i checked for my case:

1- xlwings32.dll and xlwings64.dll are in the same directory as python.exe. 
2- I unloaded and uninstalled the addin and checked if any thing is left from xlwings. 
3- Trust center setting - already check mark the trust access to vba project object model. 

I am using windows xp and office 2010 and my xlwings version is 0.11.4. Please guide thank you.

Faseeh

**Comment by mzsf** [comment]
I'm having the same issue with office 2010, Window7, and xlwings version 0.11.6.

**Comment by fzumstein** [comment]
I am closing this due to age, please open a new issue if that error persists.
