### ISSUE TITLE
improving xlam

### ISSUE THREAD

**Issue by snb001** [xlwings/xlwings#799]
I am trying to improve the xlwings.xlam code.
Can anyone tell me whether the file '..\xlwings.conf' is being used/referred to  by other code than the code in the .xlam AddIn ?

**Comment by fzumstein** [comment]
it's only used by the addin

**Comment by snb001** [comment]
Thanks.

Can you tell me why the settings won't be stored in the AddIn itself ?

**Comment by fzumstein** [comment]
because they would get lost with every update and also because you can automate the deployment.

**Comment by snb001** [comment]
In that case we can use this built-in VBA method, that stores the setting in the registry.
2 example settings to illustrate what I mean:

```
Sub M_snb()
    SaveSetting "xlwings", "python", "path", "F:\Python"
    SaveSetting "xlwings", "python", "log", "F:\Python\xlwings.log"

    sn = GetAllSettings("xlwings", "python")
    MsgBox sn(0, 0) & vbTab & sn(0, 1) & vbLf & sn(1, 0) & vbTab & sn(1, 1)
End Sub
```

**Comment by fzumstein** [comment]
that won't work: I forgot about two other use cases: 1) it should work without the addin, too (like for `xlwings quickstart ... --standalone` and also on Mac. Mac doesn't have a registry. Also the recent addition to select between a global and a workbook directory config file wouldn't work. What's your issue with the config file?

**Comment by snb001** [comment]
In that case I'd suggest to create 2 Addin's: 1 for Windows, 1 for Mac.
I wasn't able to upload it here (even not in zipped format)
I created one myself, containing only 1 module (z_main), containg 1 Sub (not a Function !)

```
Sub M_Python(c00 As String)
  c00 = "py -B -c ~import sys, os; sys.path.extend(os.path.normcase(os.path.expandvars(r'" & ActiveWorkbook.Path & ";')).split(';'));" & c00 & "~ ~"
  
  With Application
    c00 = c00 & ActiveWorkbook.FullName & "~ ~from_xl~ ~" & .Path & "\" & .Name & "~ ~" & .Hwnd & "~ 2"
  End With
        
  Shell Replace(c00, "~", Chr(34)), 0
End Sub
```
It also contains an installation macro:

```
Private Sub Workbook_Open()
    If ThisWorkbook.Path & "\" <> Application.UserLibraryPath Then
        On Error Resume Next

        If Dir(Application.UserLibraryPath & ThisWorkbook.Name) = "" Then ThisWorkbook.SaveCopyAs Application.UserLibraryPath & ThisWorkbook.Name

        Application.EnableEvents = False
        AddIns(Replace(ThisWorkbook.Name, ".xlam", "")).Installed = True
        Application.EnableEvents = True
        ThisWorkbook.Close 0
    End If
End Sub
```
The Fibonacci sample file triggers the Macro M_Pyhon:
```
Sub M_Fibonacci()
    M_Python "import fibonacci; fibonacci.xl_fibonacci()"
End Sub
```
NB.-
- In VBA functions will be used to return a result in a variable thaat is identical to the Function's name.
- I don't see a need nor any advantage of indicating the name of the python compiler or the Python path. As soon as Python has been installed correctly the command 'py ' should suffice.

Please correct me if I am missing things.

**Comment by fzumstein** [comment]
You seem to have a very specific use case in mind. Why don't you create an own repo for that. Maybe it makes it a bit less difficult for me to follow your idea.

**Comment by snb001** [comment]
I did.
You can find it over here:

http://www.snb-vba.eu/VBA_Python_en.html

**Comment by snb001** [comment]
I must have closed this thread by mistake.

**Comment by fzumstein** [comment]
consider this solved.
