### ISSUE TITLE
Insert row and column functions

### ISSUE THREAD

**Issue by rkpatel33** [xlwings/xlwings#80]

**Comment by bklaas** [comment]
There's no description to this issue, but I'm assuming the wording means "add functions to xlwings to enable insert-column and insert-row actions on the spreadsheet". If that's the intention of the issue, +1 to this one.

**Comment by rkpatel33** [comment]
+1

Apologies for the brevity, I thought it was self-explanatory.

**Comment by Diego-MX** [comment]
I started using `xlwings` and am looking forward to get the most out of it, and to contribute back to the project as well.  A question that I had on this feature is if it's possible to insert a range of cells; and also to delete a range of cells.

**Comment by fzumstein** [comment]
You're talking about copying some Range, then inserting that, correct? Sure, whatever VBA supports should be implementable.

**Comment by Diego-MX** [comment]
Thank you for your answer.  My issue results from a selection that may not represent the whole table; it may have more cells below the actual selection.  So when copying the data, I also need to shift up whatever is below, and when pasting I also need to make sure that it won't override anything from below. 

In VBA I saw it can be done as `Selection.Insert Shift:=xlDown` and `Selection.Delete Shift:=xlUp`

**Comment by fzumstein** [comment]
Sure makes sense, we should take care of that when we get to it!

**Comment by Diego-MX** [comment]
Thanks.

**Comment by sanghkang** [comment]
+1
It would be very helpful

**Comment by puruzio** [comment]
+1

**Comment by y2kbugger** [comment]
Still looking for this.

**Comment by Elijas** [comment]
+1

**Comment by yejiawei1234** [comment]
+1

**Comment by Elijas** [comment]
For anyone wondering - a workaround is to access the native VBA API through excel wings exposed api property of xlwings objects

**Comment by mlntr** [comment]
@Elijas Can you elaborate on how to do that?

**Comment by y2kbugger** [comment]
Look here for a quick tutorial on how to do that:
http://docs.xlwings.org/en/stable/missing_features.html

**Comment by HartBlanc** [comment]
+1

**Comment by manobeeslaar** [comment]
+1

**Comment by fzumstein** [comment]
on Windows, this is:

```
from xlwings.constants import InsertShiftDirection
wb.sheets[0].range("A1").api.Insert(InsertShiftDirection.xlShiftDown)
```

 alternatively, `InsertShiftDirection.xlShiftToRight`

**Comment by manobeeslaar** [comment]
Is there a alternative in MAC as well or is this only for Windows...

**Comment by fzumstein** [comment]
yes but I'll need more time to figure out the syntax. As a quick note the MacScript is:

```
tell application "Microsoft Excel"
	insert into range column 3 of sheet 1
end tell
```

**Comment by fzumstein** [comment]
on mac it is:

```
wb.sheets[0].api.columns[1-based-index].insert_into_range()
```
