### ISSUE TITLE
ActiveX component can't create object

### ISSUE THREAD

**Issue by maxallen93** [xlwings/xlwings#808]
Keep getting ActiveX component can't create object error.

Even for code as simple as:

```
@xw.func
def TOOTER():
    return 0
```

Please help!

**Comment by maxallen93** [comment]
also getting an Automation error 440 on the import.

**Comment by fzumstein** [comment]
You could try to debug it: double click the xlwings VBA project and type in `xlwings` for the password, then when it breaks upon the import, write Err.Description on the immediate window of the VBA editor and copy/paste the error description here.

**Comment by maxallen93** [comment]
Ok, so I am able to import now. However, immediately upon running the code, I get “ActiveX component can’t create object” returned. Even for code as simple as such:

@xw.func
def qq():
    return 0

Any ideas?

Thanks.

**Comment by maxallen93** [comment]
I have already tried the workaround to calculate on open. Did not work.


Thanks.

________________________________
From: Max Schreiber
Sent: Thursday, February 8, 2018 5:28:34 AM
To: ZoomerAnalytics/xlwings; ZoomerAnalytics/xlwings
Cc: Author
Subject: RE: [ZoomerAnalytics/xlwings] ActiveX component can't create object (#808)


Ok, so I am able to import now. However, immediately upon running the code, I get “ActiveX component can’t create object” returned. Even for code as simple as such:



@xw.func
def qq():
    return 0



Any ideas?



Thanks.

**Comment by fzumstein** [comment]
Is the reference to xlwings in the VBA editor properly set?

**Comment by lsklyut** [comment]
I was getting this issue due to our Cylance settings - our IT team had to whitelist two URLs and all of a sudden everything started working. YMMV

**Comment by fzumstein** [comment]
@lsklyut do you know what urls these were?

**Comment by lsklyut** [comment]
Sorry for the confusion - the xlam add-in file needed to be whitelisted

**Comment by fzumstein** [comment]
Closing this. Please reopen if @lsklyut hint doesn't resolve it.
