### ISSUE TITLE
ImportPythonUDFS throws a run-time error '53' (xlwings 0.11.4)

### ISSUE THREAD

**Issue by jozefBR** [xlwings/xlwings#810]
I have Anaconda3 installed on my computer(Windows 7 Professional, 64-bit), and I am using Microsoft Excel 2010.

I added necessary xlwings.bas file to VBA as a module. When I press Alt+F8 button, which brings up "Macro" pop-up window, "ImportPythonUDFs" macro appears in the list. However, when I press "Run" button, it throws me "Run-time error '53'" error saying "File not found: xlwings32.dll".

**Comment by jozefBR** [comment]
Thank you for your answer. 
always the same problem !

**Comment by fzumstein** [comment]
so what version of xlwings are you using?

**Comment by jozefBR** [comment]
I use the version '0.11.4' of xlwings

**Comment by fzumstein** [comment]
I think the issue here is that the add-in was not properly updated, only the python package. Closing this.
