### ISSUE TITLE
RunPython raises 'error 70, permission denied'

### ISSUE THREAD

**Issue by FXCMAPI** [xlwings/xlwings#821]
Hi,
I work with xlwings for longer time and I never run in problems. But since yesterday, when I try to call Python from a Ecel Macro via RunPython, I got an 'error 70, permission denied', also with older applications working reliable in the past. It seems that some necessary file is blocked by some process. 
I does not made any updates of the Python environment, excel or xlwings at the moment the issue appears. Killing all Excel and Python processes does not help, a restart of the computer does also not help.

Has someone an idea what is going wrong,

Many thanks
Michael

**Comment by FXCMAPI** [comment]
To check this issue please email your username and token to api@fxcm.com<mailto:api@fxcm.com>

Regards,
Daniel Halpert

**Comment by rhaskett** [comment]
I am seeing the same problem:

Windows 10

xlwings 0.15.4 Excel 16.0.11328.20156 and Python 3.6

  A couple friends of mine and I use xlwings every day for months.  Last night it stopped working for all three of us through VBA.  Interestingly, it works fine when run in python code directly, but otherwise it fails immediately on the "RunPython" command in VBA.

![image](https://user-images.githubusercontent.com/2855412/55419550-dbbb0e00-5529-11e9-9c96-c243f5b81327.png)

snippit:
   RunPython ("from code_base.folder.folder2.file_name import main; main()")

**Comment by rhaskett** [comment]
I restarted using:

> xlwings quickstart hello

and I'm seeing the same error in the test code

> Sub SampleCall()
>     mymodule = Left(ThisWorkbook.Name, (InStrRev(ThisWorkbook.Name, ".", -1, vbTextCompare) - 1))
>     RunPython ("import " & mymodule & ";" & mymodule & ".hello_xlwings()")
> End Sub

**Comment by icehotcong** [comment]
I am also encountering this. Yesterday everything was fine and now it breaks. Does anyone have any idea how to solve it? One working project is pending.....

**Comment by fzumstein** [comment]
Double click the xlwings addin in the VBA editor (passsword `xlwings`), set the breakpoint according to screenshot, then, when it stops there, type

```
?"cmd.exe /C " & DriveCommand & _
                   RunCommand & _
                   "--wb=" & """" & WORKBOOK_FULLNAME & """ --from_xl=1" & " --app=" & Chr(34) & _
                   Application.Path & "\" & Application.Name & Chr(34) & " --hwnd=" & Chr(34) & Application.Hwnd & Chr(34) & _
                   " 2> """ & LOG_FILE & """ "
```
in the immediate window and copy paste the returned string into a command prompt (after stopping the VBA debugger). Does that work? 

<img width="1431" alt="Screenshot 2019-04-02 at 14 28 42" src="https://user-images.githubusercontent.com/2265504/55423122-a3c8c080-5553-11e9-953c-4528178748ec.png">

**Comment by icehotcong** [comment]
Hi,
Thanks for the answer. However, it works only by this procedure. After I remove the stop points, it does not work again.

**Comment by rhaskett** [comment]
I'm a step behind.  I typed the copy/pasted the command in Immediate, but I don't know how to run it there.

**Comment by icehotcong** [comment]
> I'm a step behind.  I typed the copy/pasted the command in Immediate, but I don't know how to run it there.

What I was doing is exiting the debug mode first and then open Anaconda Prompt. Type the line marked blue in the screen shot and then it runs automatically.

**Comment by fzumstein** [comment]
@FXCMAPI were you ever able to fix this?

**Comment by fzumstein** [comment]
where exactly does it break (on which line) when you run it with the vba addin unprotected?

**Comment by rhaskett** [comment]
OK figured out the Immediate.  In my Anaconda Prompt:

> (base) C:\anaconda3\Scripts>cmd.exe /C --wb="" --from_xl=1 --app="C:\Program Files\Microsoft Office\root\Office16\Microsoft Excel" --hwnd="1116940" 2> ""

> The system cannot find the path specified.

**Comment by icehotcong** [comment]
@fzumstein Hi Felix, when I try to execute again, the code stops here (Marked in yellow) and give me the error code "running time error 70" Permission denied.
![Unbenannt](https://user-images.githubusercontent.com/49206094/55424597-e48afe80-5580-11e9-8f2a-9047d4be9565.PNG)

**Comment by rhaskett** [comment]
Interestingly I have 

> C:\Program Files\Microsoft Office\root\Office16

 but not 

> C:\Program Files\Microsoft Office\root\Office16\Microsoft Excel

though there is an "excel.exe" in "Office16"

Is the Application.Name coming though differently now?

**Comment by fzumstein** [comment]
replace the corresponding part with this and try again:

```
"cmd.exe /C " & DriveCommand & _
                   RunCommand & _
                   "--wb=" & """" & WORKBOOK_FULLNAME & """ --from_xl=1" & " --app=" & Chr(34) & _
                   Application.Path & "\" & Application.Name & Chr(34) & " --hwnd=" & Chr(34) & Application.Hwnd & Chr(34) & _
                "
```

**Comment by rhaskett** [comment]
The above runs in the anaconda prompt.  After converting it with Immedate

> cmd.exe /C C: & cd "C:\anaconda3" & "C:\anaconda3\pythonw.exe" -B -c "import sys, os; sys.path[0:0]=os.path.normcase(os.path.expandvars(r'C:\anaconda3\Scripts\hello;C:\anaconda3\Scripts\hello\hello.zip;')).split(';'); import hello;hello.hello_xlwings()" --wb="C:\anaconda3\Scripts\hello\hello.xlsm" --from_xl=1 --app="C:\Program Files\Microsoft Office\root\Office16\Microsoft Excel" --hwnd="1116940"

**Comment by icehotcong** [comment]
> replace the corresponding part with this and try again:
> "cmd.exe /C " & DriveCommand & _
>                    RunCommand & _
>                    "--wb=" & """" & WORKBOOK_FULLNAME & """ --from_xl=1" & " --app=" & Chr(34) & _
>                    Application.Path & "\" & Application.Name & Chr(34) & " --hwnd=" & Chr(34) & Application.Hwnd & Chr(34) & _
>                 "

Hi Felix, still doesn't work. Give me the same error message.

**Comment by rhaskett** [comment]
I understand now.   I needed to be in debug.  I now get the below which runs fine in an Anaconda prompt:

> cmd.exe /C C: & cd "C:\anaconda3" & "C:\anaconda3\pythonw.exe" -B -c "import sys, os; sys.path[0:0]=os.path.normcase(os.path.expandvars(r'C:\anaconda3\Scripts\hello;C:\anaconda3\Scripts\hello\hello.zip;')).split(';'); import hello;hello.hello_xlwings()" --wb="C:\anaconda3\Scripts\hello\hello.xlsm" --from_xl=1 --app="C:\Program Files\Microsoft Office\root\Office16\Microsoft Excel" --hwnd="1116940" 2> "C:\Users\ryan.haskett\AppData\Roaming\xlwings.log" 

when I run

> ?"cmd.exe /C " & DriveCommand & _
                   RunCommand & _
                   "--wb=" & """" & WORKBOOK_FULLNAME & """ --from_xl=1" & " --app=" & Chr(34) & _
                   Application.Path & "\" & Application.Name & Chr(34) & " --hwnd=" & Chr(34) & Application.Hwnd & Chr(34) & _
                   " 2> """ & LOG_FILE & """ "

**Comment by rhaskett** [comment]
The xlwings.log from the above run gives an error and the traceback is

> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\anaconda3\scripts\hello\hello.py", line 5, in hello_xlwings
    wb = xw.Book.caller()
  File "C:\anaconda3\lib\site-packages\xlwings\main.py", line 555, in caller
    return cls(impl=app.books.open(fullname).impl)
  File "C:\anaconda3\lib\site-packages\xlwings\main.py", line 366, in books
    return Books(impl=self.impl.books)
  File "C:\anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 385, in books
    return Books(xl=self.xl.Workbooks)
  File "C:\anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 310, in xl
    self._xl = get_xl_app_from_hwnd(self._hwnd)
  File "C:\anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 220, in get_xl_app_from_hwnd
    ptr = accessible_object_from_window(child_hwnd)
  File "C:\anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 190, in accessible_object_from_window
    byref(IDispatch._iid_), byref(ptr))
  File "_ctypes/callproc.c", line 940, in GetResult
OSError: [WinError -2147467259] Unspecified error

**Comment by fzumstein** [comment]
In your VBA immediate Window, run:

```
?Application.Hwnd
```

Paste the number in the below script and run in Python, does that give an error?

```
from ctypes import oledll, POINTER, byref
from comtypes.automation import IDispatch
import win32gui

hwnd = PASTE_HERE
child_hwnd = win32gui.FindWindowEx(hwnd, 0, 'XLDESK', None)
child_hwnd = win32gui.FindWindowEx(child_hwnd, 0, 'EXCEL7', None)
ptr = POINTER(IDispatch)()
print(ptr)
res = oledll.oleacc.AccessibleObjectFromWindow(
    child_hwnd, -16,
    byref(IDispatch._iid_), byref(ptr))
print(ptr)
```

**Comment by rhaskett** [comment]
Same error.  We appear to be being blocked by windows?  Interestingly, one more friend is not experiencing this problem on her windows machine.  We are not sure what the differences are yet.


> <POINTER(IDispatch) ptr=0x0 at 2a1fa85fe48>
> Traceback (most recent call last):
>   File "C:/Users/[USER]/workspace/[PATH]/xlwings_test.py", line 12, in <module>
>     byref(IDispatch._iid_), byref(ptr))
>   File "_ctypes/callproc.c", line 940, in GetResult
> OSError: [WinError -2147467259] Unspecified error

**Comment by rhaskett** [comment]
Weird.  So I restarted my computer (for the nth time today).  I'm still getting the run-time error 70 in Excel, but now with the new "Hwnd" the pointer code seems to be working.  Outputting the following:

> <POINTER(IDispatch) ptr=0x0 at 211ce48fe48>
> <POINTER(IDispatch) ptr=0x211ce04b208 at 211ce48fe48>

**Comment by fzumstein** [comment]
and `xlwings.log` same error as before? Delete the file first to make sure you're not seeing the old version.

**Comment by rhaskett** [comment]
So I only see a log file if I run in Anaconda prompt using cmd.exe.  If I run in Excel no log file is created.

when I run the cmd in Anaconda (with a new hwind after a restart)

> cmd.exe /C C: & cd "C:\anaconda3" & "C:\anaconda3\pythonw.exe" -B -c "import sys, os; sys.path[0:0]=os.path.normcase(os.path.expandvars(r'C:\anaconda3\Scripts\hello;C:\anaconda3\Scripts\hello\hello.zip;')).split(';'); import hello;hello.hello_xlwings()" --wb="C:\anaconda3\Scripts\hello\hello.xlsm" --from_xl=1 --app="C:\Program Files\Microsoft Office\Root\Office16\Microsoft Excel" --hwnd="197270" 2> "C:\Users\[USER]\AppData\Roaming\xlwings.log" 

the log file is created but ends up blank.

**Comment by rhaskett** [comment]
Crazy weird.  So sometimes when the macro "SampleCall" runs it creates the run-time error 70 msgbox, but sometimes (~50%) it does not.  It does not appear to depend on the time between attempts.  On the advice of my IT guy we put a breakpoint after the Wsh.Run command. On the times the run-time error is not triggered the ExitCode is zero, but nothing is written to A1 on the sheet.

We inspected the full command being sent to Wsh.Run and it was exactly the same when the error msgbox appears and when it does not.   Either way it runs it does not create a log file in %APPDATA%\Roaming.  I searched the computer using Everything and did not find an xlwings.log anywhere.

When I run the command manually in a Command Prompt it works without fail.  Running from PyCharm works perfectly as well.  In either case the code writes "Hello xlwings!" in A1 and creates an empty log file in %APPDATA%\Roaming.

**Comment by rhaskett** [comment]
OK we have some evidence that an anti-virus "Security Manager AV Defender" might be causing the issue.  We will circle back when we have more information.

**Comment by rhaskett** [comment]
We have confirmed it is an odd interaction with the Anti-Virus software.  I'm not sure if you have run into this problem before and there is a known workaround.  We are looking into whitelisting solutions.

Many thanks for your time and for the great add-in.

**Comment by fzumstein** [comment]
Ok great, thanks for investigating! You might also be able to work around the problem by checking the `RunPython: Use UDF Server` box.

**Comment by dsm054** [comment]
I'm consistently seeing this run-time error 70 now too after my IT guys upgraded me to Win10 earlier this week.  Looking at the EventViewer logs suggests that RunPython is violating the "Block all Office applications from creating child processes" ASR rule with GUID D4F940AB-401B-4EFC-AADC-AD5F3C50688A which my firm has inconveniently, but not unreasonably, activated.

Disabling the real-time protection lets it work, so I can't be that far off.  My first few attempts to leave it on and to use the exclusion rules to let Excel create child processes all failed, but I'm a Linux guy and these are some mysterious corners to me so it's likely I missed something.

Some colleagues who have also been upgraded to Win10 aren't yet seeing this: I'll have to check to see if they have the same "Windows Defender Security Center" settings (and isn't that a mouthful.)

I'm a little worried this is going to become a real nuisance. 😟

**Comment by fzumstein** [comment]
See also https://www.howtogeek.com/359767/what-is-the-new-%E2%80%9Cblock-suspicious-behaviors%E2%80%9D-feature-in-windows-10/

Activating `RunPython: Use UDF Server` might improve the situation a bit as the process keeps running and doesn't start every time from scratch.

**Comment by dsm054** [comment]
Unfortunately the UDF is also blocked because of what seems to be a DCOM permissions situation.  Google suggests that a lot of people have this problem after switching to windows 10, and there appears to be a fix for it, which I haven't tried.  I'll give it a go this week and see if I can get that working.

**Comment by icehotcong** [comment]
@dsm054 Hi, did you find out any solution yet. Our IT had a look together with me today and it seems the VBA cannot call the command window, which causes the problem. But we failed  to solve this. What is the fix you were talking about? Thanks!

**Comment by dsm054** [comment]
@icehotcong: as a temporary hack I disabled the runtime protection services in Windows Defender.  (windows defender/virus & threat protection settings/real-time protection).  It automatically turns back on after a few seconds, but you can make that permanent (apparently) by changing a registry key.  That didn't work for me when I tried it, and I was on the clock, so I used a powershell script which kept turning it off every few seconds.  This makes me feel a little queasy but allows me to get some work done at a slight cost of security.  Unfortunately I wasn't able to get a more specific exclusion working, and the docs aren't even clear to me about whether it'll work in principle for that ASR rule.

Fortunately my firm has a McAfee installation which we can use instead of the default Defender, and it's a lot less restrictive.  After switching to that, the Defender ASR rule which is killing me isn't enforced, and it looks like my colleagues who weren't experiencing the problem were those whose IT guys had switched their boxen. I've been warned that's going away at my firm eventually, though, but at least for now I'm okay. 

So to see if your problem was the same as mine, try (1) turning off RPS and (2) checking the EventViewer logs for the GUID of the rule which is being broken.

**Comment by icehotcong** [comment]
@dsm054 Hi, thanks a lot for the information. I will have a look over it again.

**Comment by mm82** [comment]
Bringing this issue up again. I have the same problem - cannot run cmd commands from vba. This is blocked by McAfee in our firm with no possiblity to come around.
Does xlwings use the cmd commands only since the issue with different python environments has been implemented? I haven't had this issues before. Maybe there is a possibility to change the addin on my side, so that it does not use cmd commands? Any idea?

**Comment by fzumstein** [comment]
No, nothing changed from xlwings point of view. Much more likely that you got a Windows or AntiVirus update. You can always switch to the dev mode, i.e. start the xlwings server with a script manually and then use the UDF server.

**Comment by mm82** [comment]
Thanks for your help @fzumstein ! This works and I can at least update my old projects. Unfortunately this does not help too much in a production mode. If you have an idea let me know ... I also try to find a workaround.

**Comment by mm82** [comment]
Once again ... when I start the server manually I get the "ImportError: Missing required dependencies ['numpy']". As you stated in another place this has to do with how conda activates the environment. I do not know how to come around ... if someone knows, that would help a lot. thanks.

**Comment by fzumstein** [comment]
When you manually start the server, you only have to make sure to start it from a properly activated conda environment (i.e. `conda activate myenv`).

**Comment by mm82** [comment]
That

**Comment by mm82** [comment]
Sure, makes sense and works. Thanks.

**Comment by victorfaria87** [comment]
Hey There.
I see that this issue as been determined closed, 
but i am currently running in to it and nothing is resolving it.
![2022-10-22](https://user-images.githubusercontent.com/111878168/197336372-596e7c4f-6968-4794-a7db-d4cfe1027f35.png)
I dont have administrator privileges, and the administrator will not change the security settings.

**I found a possible solution in the internet, but does not work on my computer:**
![image](https://user-images.githubusercontent.com/111878168/197336528-464a7624-42cb-4461-8068-9a834b5ca771.png)

I am able to run python code and automate excel from the Visual Studio Code enviroment.
Error 70, comes up when i call a python scrip from VBA (Macro Button)
It also happens if i click the "Run main" button in the xlwings add-in.
![image](https://user-images.githubusercontent.com/111878168/197336858-35183376-d6cb-4f5c-a69d-e475b28a55d0.png)
Thanks.

**Comment by abudden** [comment]
I am also seeing this problem.  Is there any way to make Excel run python without needing to start cmd?

The advice above says to start the UDF server manually.  Is there any documentation on how to do this properly?

I've tried running python and typing

```python
import xlwings
xlwings.serve()
```

which says:

```
xlwings server running, clsid={506E67C3-55B5-48C3-A035-EED5DEEA7D6D}, event loop on 26404
```

but I still get the "Object required" message when I try to use a function.  Clicking Import Functions produces the Access Denied message.  I've clicked "RunPython: Use UDF Server", but I guess it doesn't know about the one I started manually so is trying to start one itself.

**Comment by acameronfw** [comment]
> I am also seeing this problem. Is there any way to make Excel run python without needing to start cmd?
> 
> The advice above says to start the UDF server manually. Is there any documentation on how to do this properly?
> 
> I've tried running python and typing
> 
> ```python
> import xlwings
> xlwings.serve()
> ```
> 
> which says:
> 
> ```
> xlwings server running, clsid={506E67C3-55B5-48C3-A035-EED5DEEA7D6D}, event loop on 26404
> ```
> 
> but I still get the "Object required" message when I try to use a function. Clicking Import Functions produces the Access Denied message. I've clicked "RunPython: Use UDF Server", but I guess it doesn't know about the one I started manually so is trying to start one itself.

Did you ever find a solution? I am able to get everything working on a different computer. I know it’s group security setting, but wanted to see if there was a workaround without whitelists

**Comment by acameronfw** [comment]
Right after I wrote this, I was able to get it working. I run the UDF Debug server. In the main python file added code listed here: https://docs.xlwings.org/en/stable/debugging.html

also ensured my config was setup correctly. Now I can load UDFs and run RunPython
