### ISSUE TITLE
Absolute file paths to UDF modules not supported

### ISSUE THREAD

**Issue by Htermotto** [xlwings/xlwings#826]
I was wondering why this was the case. If this is a bug, I do have a fix for it and would like to contribute. If this feature already exists, please tell me how to properly use it.

**Comment by fzumstein** [comment]
When you import a module in a python source file, you also don't specify an absolute file path. Same way it works in the xlwings addin: specifiy a module and make sure it's on python's search path (by extending the PYTHONPATH if need be).
