### ISSUE TITLE
error in addin install if XLSTART folder does not exist before

### ISSUE THREAD

**Issue by sdementen** [xlwings/xlwings#828]
When trying to install the xlwings addin on excel 16.0
$ xlwings addin install                                                                                              
[Errno 2] No such file or directory: 'C:\\Users\\username\\AppData\\Roaming\\Microsoft\\Excel\\XLSTART\\xlwings.xlam'  

If I create the XLSTART folder in C:\\Users\\username\\AppData\\Roaming\\Microsoft\\Excel before executing the command, it works.

**Comment by fzumstein** [comment]
fixed with #1316
