### ISSUE TITLE
Edit Workbook

### ISSUE THREAD

**Issue by rm17tink** [xlwings/xlwings#841]
Hello, I am updating excel .xlsx files sitting in a share-point folder on my desktop, however all of the excels when opened prompt you to Edit Workbook. Can I use xlwings to automatically choose that then write over the sheet. I have all the code for the writing over a sheet but it doesn't do it with workbooks that need the "Edit Workbook" Authorization.

```
wb = xw.Book(filename)
ws = wb.sheets['X_DATA']
ws.clear_contents()
ws.range('A1').options(index=False).value = df_ora_test
wb = xw.Book(filename)
wb.save()
xw.apps[0].quit()

```

**Comment by fzumstein** [comment]
xlwings nowadays supports all options when opening a book, which should solve this.
