### ISSUE TITLE
Random occasional FileNotFoundError

### ISSUE THREAD

**Issue by xjdeng** [xlwings/xlwings#842]
Hi,

I'm running xlwings 0.11.7 on Python 3.5 using Anaconda in Windows 7, and I've been having this problem for a while.  I've also gotten it when running previous versions of xlwings as well as on Python 2.7.

It's a little hard to reproduce this error since it seems to occur randomly, like maybe 1 out of 20 executions.  But here's what happens when it occurs:

I run a macro in Excel that calls one of my python scripts using RunPython.

When it gets to a line like the following:

`xlwings.Book.caller().sheets[My Sheet]`

I get a FileNotFoundError and it says that the Excel sheet I'm running the macro from cannot be found.

I try rerunning the macro and the error happens again.

The only way I've found that solves the error is to do something of the following:

1) In Excel, open the workbook that's experiencing this error.  
2) Go into the macros and edit the macros.  Select the code for one of the macros and cut the code.
3) Save the Workbook
4) Paste the code back
5) Save again
6) Then restart Excel and run the macro again

Maybe 50% of the time, this fixes the error and the macro runs again.  Sometimes, if it doesn't run, I'll try randomly cutting, saving, pasting, saving again, restarting Excel, and running the macro again and it seem to work and will continue to work for another 15-30 or so executions before failing again.

I just had this happen but unfortunately, forgot to save the error message.  If this issue isn't resolved yet, I'll try to remember to update you with an error printout the next time it occurs.

**Comment by fzumstein** [comment]
Were you ever able to solve this issue?

**Comment by xjdeng** [comment]
Nope, still unsolved.

Here's the thing: I'm running a cloud service called [Workplace_](https://www.os33.com/) which creates a S:\ drive in Windows which is a drive hosted on the cloud.  Sometimes, when I run an xlwings Python script embedded in a .xlsm file that's saved on the S:\ Drive that's enabled by Workplace_, it causes this "FileNotFoundError".  This seems to happen more when the python script is more CPU intensive.

I tried contacting tech support for Workplace_ but they've pretty much given up on this since they've never heard of Xlwings.  And unfortunately, I'm assuming you guys have never heard of Workplace_ either since they're just as obscure as Xlwings.

Unfortunately, Workplace_ and Xlwings don't play along nicely but having BOTH of these running simultaneously is essential and there's not other alternative.  What am I supposed to do in this situation?

**Comment by fzumstein** [comment]
did you ever upgrade from 0.11.7? I recently made some fixes for OneDrive that could also help here. We're at 0.19.4 now

**Comment by fzumstein** [comment]
more fixes for OneDrive in 0.21.2 - I am assuming these will fix this, if not, please reopen.
