### ISSUE TITLE
can't import xlwings

### ISSUE THREAD

**Issue by gflores87** [xlwings/xlwings#843]
Hi, 
I have a very basic code that sometimes works and sometimes crashes:

```
import xlwings as xw
path_to_the_addin = r'C:\blp\API\Office Tools\BloombergUI.xla'
wb_addin = xw.Book(path_to_the_addin)
libro = xw.Book(r'C:\Users\XXXX\Documents\Projects\Cap Arb\Misc\RBP.xlsx')
libro.sheets['IG'].range('C63:D66').value
```

With output:

AttributeError: module 'xlwings' has no attribute 'Book'

What is happening? why does it crash when I try to run the import?

> Traceback (most recent call last):
> 
>   File "<ipython-input-2-20169b6105b7>", line 1, in <module>
>     import xlwings as xw
> 
>   File "C:\Users\XXXX\Documents\Projects\Cap Arb\capArb\xlwings.py", line 4, in <module>
>     wb_addin = xw.Book(path_to_the_addin)
> 
> AttributeError: module 'xlwings' has no attribute 'Book'

**Comment by Colin-b** [comment]
Seems like a classic python mistake, when you import xlwings you are not
importing the xlwings python module from zoomer Analytics but yours
(xlwings.py). Rename your file and it should fix it.

**Comment by gflores87** [comment]
Agree on the mistake of having the wrong name. However it looks like it is slightly more complex than that. If I run my code without closing the excel instance manually then I can't run my code again. If I search for the processes in the task manager and kill them then I can run my code. Hence, I can run my code even with the badly chosen filename as long as I manage the running instances of Xl

**Comment by fzumstein** [comment]
closing this as the original issue is solved and I can't replicate the 2nd part
