### ISSUE TITLE
xlwings.view(dict) with lists doesnt output lists

### ISSUE THREAD

**Issue by gmonkman** [xlwings/xlwings#848]
```
bad = {'b': 1, 'a': 2}
xlwings.view(bad)
```

```
bad = {'b': [1,2,3], 'a': 2}
xlwings.view(bad)
```

![capture](https://user-images.githubusercontent.com/15924596/38509931-4253b37a-3c1b-11e8-9b32-0f67c8cff13d.JPG)

**Comment by fzumstein** [comment]
I think it's a bit difficult to cover anything beyond a simple key/value combination.... how would you translate something like `{'b': [1,2,{'a': 1, 'b': 2}], 'a': 2}` into cells without loosing information?

You can always build a custom converter for your specific use case: http://docs.xlwings.org/en/stable/converters.html#custom-converter or simpler: Just transform your dictionary into a list of list before you send it over

**Comment by gmonkman** [comment]
Thanks, appreciate that, 1 deep lists as items is probably a much commoner use case than more complex structures. I see two options-well 3 as no support is perfectly legitimate! ;)

The first is to ignore nesting within items and put the repr of the object in the cell, the other is the more complete approach.
![capture](https://user-images.githubusercontent.com/15924596/38606478-0656e992-3d6e-11e8-9708-4d234a752cae.JPG)

Keep up the good work though! I love the view() function alone.

**Comment by fzumstein** [comment]
closing this as it's not really a `view` specific issue but rather related to the available xlwings converters that don't currently cover nested datastructures.
