### ISSUE TITLE
xlwings AddIn not available when Excel is opened from Python (via xlwings)

### ISSUE THREAD

**Issue by gdementen** [xlwings/xlwings#853]
The addin is installed and works fine when Excel is opened directly by the user.

I have been able to open my own .xlam addins stored in `%AppData%/Microsoft/AddIns/` by using this code:

```python
app = xw.App()
xl_app = app.api
for i in range(1, xl_app.AddIns.Count + 1):
    addin = xl_app.AddIns(i)
    addin_path = addin.FullName
    if addin.Installed and '.xll' not in addin_path.lower():
        xl_app.Workbooks.Open(addin_path)
```
but apparently addins stored in `%AppData%/Microsoft/Excel/XLSTART` do not show up in .AddIns so I am a bit at a loss how to open/activate it automatically.

Maybe this would help:
https://stackoverflow.com/questions/10913237/cannot-find-all-the-addins-loaded-from-xlstart-folder-in-vsto

**Comment by fzumstein** [comment]
a pragmatic solution would be to either place the xlwings addin in the other folder or add the current path in your code to open it from there. maybe your SO solution also works.

the current installation experience via cli is anyhow to be improved, so maybe this can be taken into account.

**Comment by fzumstein** [comment]
In the meantime, I've found out that the addins folder is only for COM addins. You can get the XLSTART path, e.g. by using `app.api.StartupPath`

**Comment by gdementen** [comment]
Sorry, but I don't understand. How am I supposed to open Excel (via xlwings) and have the add in available?

**Comment by fzumstein** [comment]
Since the xlwings addin is just a standard vba addin, you simply need to open it like any other book:

```
xw.Book(r'path\to\xwings.xlsam`)
```

(or using `app.books.open(...)`)

With 0.19.4 the `xliwngs addin install` command should have been fixed to successfully place the addin in the `XLSTART` folder no matter what. So now you can do:

```
xw.Book(os.path.join(app.startup_path, 'xlwings.xlam')
```
