### ISSUE TITLE
How to delete one row or column? 

### ISSUE THREAD

**Issue by reaCodes** [xlwings/xlwings#862]
If I want to delete the first row, I can use `Sheet1.Rows(1).Delete` in VBA
or Using `Sheet1.Columns(1).Delete` to delete the first column.

How to achieve the same effect through it?

**Comment by gwdekker** [comment]
Supported trhough the api functionality:

import xlwings as xw
from xlwings import constants
xw.Range("A:A").api.Delete(constants.DeleteShiftDirection.xlShiftUp)

**Comment by reaCodes** [comment]
@gwdekker It works. But this kind of solution is a bit complicated. Is there a clear and concise way?

**Comment by reaCodes** [comment]
```python
import xlwings as xw 

wb = xw.Book('c:\\users\\zhong\\downloads\\test.xlsx')
sht = wb.sheets[0]
sht.range('A:A').api.Delete()
```
This can also works.
What functions does `.api.` have?

**Comment by fzumstein** [comment]
see http://docs.xlwings.org/en/stable/missing_features.html

**Comment by gwdekker** [comment]
In practice I found that the MS dev pages give a good idea on the available functionality through the win32 api, for example https://msdn.microsoft.com/en-us/vba/excel-vba/articles/range-delete-method-excel. 
another good page is https://github.com/pybokeh/jupyter_notebooks/blob/master/xlwings/Excel_Formatting.ipynb with a lot of the most common missing features addressed.

**Comment by jwilly1127** [comment]
This returns an error
    selectortype, code = self.AS_appdata.referencebyname()[name]
KeyError: 'Delete'

The above exception was the direct cause of the following exception:

    raise AttributeError("Unknown property, element or command: {!r}".format(name)) from e
AttributeError: Unknown property, element or command: 'Delete'

**Comment by fzumstein** [comment]
@jwilly1127 for the mac version you'll need to use: `sht.range('A:A').api.delete()` (lower case)

**Comment by a346145380** [comment]
hey, Felix. 
Do you consider include range(??).clear() type of functionality? I think it would be very useful. pywin32 documentation is not very helpful.

e.g.  wb.sheets['x'].range("B17").expand("table").api.ClearContents()

**Comment by fzumstein** [comment]
`clear_contents` is available, see https://docs.xlwings.org/en/stable/api.html

In the future, please open a seperate issue instead of hijacking a different issue.
