### ISSUE TITLE
The screen flashes when I start Excel, why?

### ISSUE THREAD

**Issue by reaCodes** [xlwings/xlwings#866]
When xlwings was installed in excel
---
![ezgif-2-cce3b8c3f5](https://user-images.githubusercontent.com/13817254/39698392-376278da-5227-11e8-99fa-4891d1f2f449.gif)

When xlwings was uninstalled
---
![ezgif-2-40f117d132](https://user-images.githubusercontent.com/13817254/39698389-36fb3422-5227-11e8-9ce7-8ca216b3e544.gif)

**Comment by fzumstein** [comment]
Did you install the xlwings addin?

**Comment by reaCodes** [comment]
I only run `xlwings addin install` in command line

**Comment by fzumstein** [comment]
closing this due to age
