### ISSUE TITLE
Converters within iterative structures

### ISSUE THREAD

**Issue by PJCampi** [xlwings/xlwings#868]
The ability to register converters is great but I think there may be two levels at which one wants to perform a conversion:

- **At range level:** that's basically what is done by the current `Converter` class. The value to pass to/from excel is directly routed to the relevant converter.

- **At cell level:** iterative structures like _lists_ and _dict_ are converted to ranges, but the the items within them are not converted. It means that despite my registering an `Enum` converter for example, I can't pass a list of `Enum` back to excel in a simple way.

I have solved this by replacing the `CleanDataForWriteStage` and `CleanDataFromReadStage` in my `ValueAccessor` with stages that include a _cell level_ convertion (like Enum). 
It may not the prettiest solution because it puts some burden on the user to determine whether a converter is a _cell converter_ or a _range converter_.

**Comment by fzumstein** [comment]
do you mind to make a PR out of this? Will make it easier for us to understand.

**Comment by PJCampi** [comment]
see #875

**Comment by fzumstein** [comment]
I realize this is many years later, and you hopefully moved on with your life, but I think at least I understand the issue now. However, I don't see a reason to add complexity here as the following should do its job?

```python
from enum import Enum
from xlwings.conversion import Converter
import xlwings as xw

class MyEnumConverter(Converter):

    @staticmethod
    def read_value(value, options):
        return [MyEnum[i] for i in value]

    @staticmethod
    def write_value(value, options):
        return [i.value for i in value]

class MyEnum(Enum):
    A = 'A'
    B = 'B'


xw.sheets.active['A1'].options(MyEnumConverter).value = [MyEnum.A, MyEnum.B]
print(xw.sheets.active['A1:B1'].options(MyEnumConverter).value)
```
Output

```python
[<MyEnum.A: 'A'>, <MyEnum.B: 'B'>]
```

I'll be closing this issue and connected PR, but feel free to comment which part I didn't get ;)
