### ISSUE TITLE
RunPython returning syntax error for fibonacci example

### ISSUE THREAD

**Issue by Aprataksh** [xlwings/xlwings#877]
Thank you for setting up such a useful project. I tried installing it and it went through without any problem. i.e. I did pip install .../then xlwings install .. /then xlwings quickstart I am getting the following message when trying to run fibonacci. I have added the references of xlwings  and also see it being mentioned in the project. The addin is also present.

So I'm not sure how it is getting invalid syntax. Can you please provide a resolution or at least some way to debug it can get you more information if possible?

---------------------------
Error
---------------------------
  File "<string>", line 1

    import sys, os; sys.path.extend(os.path.normcase(os.path.expandvars(r'C:\Zerodha\Pi\LinkExcel;C:\Users\Rv\Python_source_code\')).split(';')); import hello; hello.world()

                                                                                                                                               ^

SyntaxError: invalid syntax

Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------

**Comment by benmsmith1221** [comment]
Hi - I'm running into a similar issue. See Issue #801 for info that may help you. 

I'm wondering if anyone more experienced would be able to look at my issue as I'm not too familiar with the python/sys.path side of things:

https://stackoverflow.com/questions/53833886/calling-python-module-from-vba-xlwings?noredirect=1#comment94551167_53833886

**Comment by fzumstein** [comment]
Hi @benmsmith1221, please open a new issue with complete sample code to replicate.
