### ISSUE TITLE
File not found: xlwings32.dll 53 when try import function

### ISSUE THREAD

**Issue by naiiiiii** [xlwings/xlwings#878]
Hello 

I have Anaconda 3 and python 3.

When I tried to import function I have 

![image](https://user-images.githubusercontent.com/24571497/40422326-50027a74-5e8f-11e8-8569-a14f71bb9e36.png)

To install xlwings I tried : 

conda install -c conda-forge xlwings

then 

xlwings addin install

I verified and the .dll are in the folder than python.exe. Do you have a solution for me?

thank you,

Naïma

**Comment by fzumstein** [comment]
Closing this as too old. Feel free to open a new issue if you still have issues.
