### ISSUE TITLE
UDF reads data from a different workbook

### ISSUE THREAD

**Issue by DougAJ4** [xlwings/xlwings#891]
The UDF code below reads a 1D array containing cell or range addresses.  It returns a two column array listing the cell values in the first cell of the listed address, and the data types (either list, or the type of the value if the range is a single cell) .

If the workbook containing the UDF is the most recently opened it works as intended, but if there is another workbook opened later it returns the values from the equivalent range in that workbook.

The problem seems to be in: sht = xw.Book().sheets[shtname]

Is this a bug, or the intended behaviour?

If the latter, how do I get the workbook name of the calling UDF?

```
@xw.func
@xw.arg('rng', ndim = 1)
@xw.arg('xl_app', vba='Application')
def RtnRange2(rng, xl_app): 
    """
    Return a value and  data type from each value in rng
    Convert range addresses to arrays
    """
    rtn = []
    shtname = xl_app.Caller.Worksheet.Name
    
    sht = xw.Book().sheets[shtname]
    
    for val in rng:
        try:
            arr = sht.range(val).value
            try:
                if type(arr[0]) is list:
                    rtn.append([arr[0][0], str(type(arr))])
                else:
                    rtn.append([arr[0], str(type(arr))])
            except:
                    rtn.append([arr, str(type(arr))])
        except:
            rtn.append([val, str(type(val))])
    return rtn
```

**Comment by fzumstein** [comment]
You can use `xw.Book.caller()` see http://docs.xlwings.org/en/stable/connect_to_workbook.html or the "vba" keyword, see http://docs.xlwings.org/en/stable/udfs.html#the-vba-keyword and derive the Workbook from the Caller. `xw.Book()` opens/instantiates a new Workbook.

**Comment by DougAJ4** [comment]
Thanks for that.

I got it to work (eventually) with:
    shtname = xl_app.Caller.Worksheet.Name
    sht = xw.Book.caller().sheets[shtname]

It's not obvious to me why:
    sht = xl_app.Caller.Worksheet

doesn't work, but if I try:
    sht = xl_app.Caller.Worksheet
    return sht.range(rng[0]).value

 it gives an 'automation error' message, whereas the two stage process works.

Also I had to use xl-app.Caller() to get the worksheet name, but xw.Book.caller() to return the worksheet object.

**Comment by fzumstein** [comment]
your 2nd and 3rd `sht` is the pywin32 object, so you can't use xlwings syntax on it directly.
