### ISSUE TITLE
Import Functions fails: Could not activate python COM server, hr = -2147221164 1000

### ISSUE THREAD

**Issue by amcmullen** [xlwings/xlwings#895]
Hello,

When I click 'Import Functions' on the xlwings ribbon in Excel, the wheel spins for ~5 seconds, then Excel hangs for ~30 seconds before I get this error message:

![image](https://user-images.githubusercontent.com/7844535/41167775-ec729cfc-6b11-11e8-8663-2da5fc8ee84f.png)

When I step through the VBA code the error is raised on this line, where XLPyDLLActivateAuto is an external xlwings function:
![image](https://user-images.githubusercontent.com/7844535/41171202-af26df64-6b1d-11e8-9394-61df206ed952.png)

Trust center settings are set to trust all
There's a reference to xlwings in VBA
Python version: Anaconda 2.7.15 (32bit)
xlwings version 0.11.8

Other aspects of xlwings such as using RunPython to run python calls from VBA and modifying excel sheets from python code work fine, just having issues with the Import Functions functionality.

Any thoughts on what could be causing this and/or how to debug further?

**Comment by fzumstein** [comment]
@amcmullen were you ever able to fix this?

**Comment by airboost** [comment]
Any updates on this issue? I am having similar trouble but am running on windows 10, python 3.7, and xlwings 15.8

**Comment by fzumstein** [comment]
What's the exact error you're seeing?

**Comment by whoopnip** [comment]
I'm trying to get xlwings set up on about 35 machines. I've gotten most working, but 4 of them are hitting this exact issue. The same exact error pops up when clicking import functions on a newly created `quickstart` project. The details of two of the machines are as follows:

Windows 10 Home, Anaconda Python 3.7.3, Excel from 365 ProPlus (version 1909 build 12026.20320), xlwings 0.15.8

Windows 10 Home, Anaconda Python 3.7.4, Excel from 365 (version 1909 build 12023.20320), xlwings 0.15.10.

Both have trust access to VBA object model enabled. Both have Anaconda in windows PATH.

Let me know if you can provide any help in debugging. I'm happy to provide any other information that would be helpful.

**Comment by fzumstein** [comment]
@whoopnip Can you try the following: On a machine where it works, import the UDFs and save. Verify the `hello` function works. Then bring the workbook with the imported functions over the faulty machines and check if the UDFs work there to see if it's really only the importing that fails.

**Comment by whoopnip** [comment]
@fzumstein I'll try this test with a plain quickstart project a bit later today when I'm by the machines again. But I did already try this with an existing xlwings project that was working fine on another machine. When I loaded it, as soon as I changed a cell so that it would recalculate the functions, then it had the same long pause before printing the same error in the cells rather than popping up as an error box.

**Comment by fzumstein** [comment]
@whoopnip in that case try to run it in debug mode and see if it works then: http://docs.xlwings.org/en/stable/debugging.html#udf-debug-server

**Comment by whoopnip** [comment]
@fzumstein Ok so I tried debug mode with both non-working machines. I also tried it both with a quickstart project created on the non-working machine, and with a quickstart project created on the working machine calling the hello function. In all cases, I get the following error:

`No command specified in the configuration, cannot autostart server 1000`

If I try to use the quickstart created on the working machine, then the error comes in the cell, and if on the quickstart created on the non-working machine, then the error comes in a popup after I click import functions. I have also verified that the exact same debug process works on the working machine, I am able to enter pdb in the terminal.

Also, not sure if this is helpful, but on both these machines I had to manually set the interpreter path to the `pythonw.exe` in the Anaconda folder. Originally they were not able to find the xlwings DLL. About 5-10 of the other machines hit this issue and that fixed it. I have verified that there is only a single Python installation on both of the non-working machines.

**Comment by whoopnip** [comment]
Yes, I am positive, I have added `xw.serve()` in the `if __name__ == '__main__'` block and run the Python script in the terminal. It says `'xlwings server running, clsid=<long string>`. Same exact process works on the working machine.

**Comment by fzumstein** [comment]
Ok gotcha. Feel free to send me an email (on my profile) to discuss further strategies to resolve that.

**Comment by fzumstein** [comment]
@whoopnip I've moved this into a new issue and closing this one: https://github.com/xlwings/xlwings/issues/1166
