### ISSUE TITLE
how to automatic interruption to Excel?

### ISSUE THREAD

**Issue by AlphaSmartDog** [xlwings/xlwings#908]
os windows 10 x64
in  python 2.7.15 x32 with xlwings 0.11.8 it work well, but in python 3.6.1 x64 with xlwings 0.11.8, xlwings cannot automatic interruption to Excel? how to fit?
i hope the xlwings try wrtie Excel if wrong then raise wrong and i will catch this wrong in python, 

`
import gc
from time import sleep
import xlwings as xw

wb = xw.Book(filepath)
sht = wb.sheets[sheet_name]

while True:
    """
    get message from data api then do something
    """

    try:
        sht.range("A1").value = atm_vol
        shift = 5
        sht.range("A{}".format(shift)).value = iv_tables[0]
        sht.range("A{}".format(shift + 3 + iv_tables[0].shape[0])).value = iv_tables[2]
        sht.range("M{}".format(shift)).value = iv_tables[1]
        sht.range("M{}".format(shift + 3 + iv_tables[1].shape[0])).value = iv_tables[3]
        log.info("write")

    except:
        gc.collect()
        sleep(5)
        log.info("not write")
`

**Comment by AlphaSmartDog** [comment]
i mean when i using another excel, xlwings cannot write to Excel, this program will work

**Comment by fzumstein** [comment]
closing because of age. feel free to reopen if the issue persists.
