### ISSUE TITLE
Will the POST methods be implemented for the REST API?

### ISSUE THREAD

**Issue by sylvoslee** [xlwings/xlwings#969]
Will POST methods be implemented, I am very interested in this。

**Comment by fzumstein** [comment]
Hey thanks a lot for your feedback! Yes, we would love to, if we get some more of the same feedback (you're the first one really). In the meantime, do you mind to share how you would use this? This will help us to promote the feature.

**Comment by jeggs** [comment]
Having POST methods would really be a game changer for us! We would like to
- change cell values (including changing formulas)
- execute VBA routines

**Comment by fzumstein** [comment]
Hey @jeggs and @sylvoslee, do you mind pinging me on my email directly (it's on my profile) to connect and exchange some thoughts on that?

**Comment by pdonorio** [comment]
Hello there, 
so here's another use case for a possible `POST` usage

- I have a web app with dataframes as a result of computations
- the user is an "expert" one
- the user can run an xlswing rest API server on his current spreadsheet and give the web app his IP / port
- the web app calls POST on a new or existing sheet and fill out the dataframe or run other stuff there
- the user shutdowns the rest API 
- the user is quite happy with the results he had in realtime in his local file ^_^

--

Note: I was originally thinking about using S3 or Dropbox-like to generate the xlsx file on the web app server, but the server runs Linux and xlwings can't work there. And xlwings gives access to VBA stuff you can't reproduce in any other way.

**Comment by fzumstein** [comment]
Planning ahead, I consider this to be better served in (a) either a separate package or (b) dropped altogether as I have an impression that most of the time, users are baking this into their web backend themselves.
