### ISSUE TITLE
spaces in python interpreter make UDF import fail - block it for now

### ISSUE THREAD

**Issue by fzumstein** [xlwings/xlwings#974]
see: #766

**Comment by JB-AM** [comment]
Moving forward on this point would be appreciated. 
If I’m not mistaking, it seems that the command would only need an additional "&" before the path to be accepted. 
For example, my error message being: 
`Python process exited before it was possible to create the interface object.
Command: cmd.exe /showconsole /K "C:\Program Files\Python39\python.exe" -B -c "import sys, os;import lwings.utils;xlwings.utils.prepare_sys_path(\"C:\\Users\\redacted\\file.xlsm;C:\\Users\\redacted\\AppData\\Roaming\\Microsoft\\Excel\\XLSTART\\xlwings.xlam;;;;\");import xlwings.server; xlwings.server.serve('{redacted}')"
Working Dir: <unspecified> 1000
`
but copying and pasting it with the additional amp and validating:
`cmd.exe /showconsole /K &"C:\Program Files\Python39\python.exe" -B -c "import sys, os;import xlwings.utils;xlwings.utils.prepare_sys_path(\"C:\\Users\\redacted\\file.xlsm;C:\\Users\\redacted\\AppData\\Roaming\\Microsoft\\Excel\\XLSTART\\xlwings.xlam;;;;\");import xlwings.server; xlwings.server.serve('{redacted}')"`
seems to solve the problem, at least manually.

**Comment by JB-AM** [comment]
Not sure where I got the info. If I remembre it well, the & indicates to execute the following string, not trying to find some other hidden meaning. And yes, bash is probably more clear than cmd.exe.

**Comment by fzumstein** [comment]
nope, that didn't work, but this did:

* https://stackoverflow.com/a/6378038/918626
* https://github.com/xlwings/xlwings/pull/1809
